### ISSUE TITLE
Feedback on element_handle.type() reference

### ISSUE THREAD

**Issue by kaycebasques** [microsoft/playwright#10093]
Howdy old teammates :D

Regarding this section: https://playwright.dev/python/docs/api/class-elementhandle/#element-handle-type

![image](https://user-images.githubusercontent.com/4713486/140556284-39e40a0c-4417-4246-8daa-60abeabd82c6.png)

I have a use case where I add text to an input, do some other stuff on the page, wait for the SPA to render the new data, and then repeat the process again by adding other text to the original input. This reference page doesn't mention how to clear the input field. At first I tried this:

```
element_handle.type('')
element_handle.type('<new text>')
```

Because apparently `element_handle.fill()` supports passing an empty string in order to clear the input value. But this doesn't work for `element_handle.type()`. It just keeps appending the text to the value.

The solution appears to be to evaluate the expression on the element in JS-land:

```
my_selector = '...'
page.eval_on_selector(my_selector, 'el => el.value = ""')
my_element = page.query_selector(my_selector)
my_element.type('...')
```

Suggestions:

* Update the `element_handle.type('')` to have the same behavior as `element_handle.fill('')`
* Or update https://playwright.dev/python/docs/input#type-characters and https://playwright.dev/python/docs/api/class-elementhandle/#element-handle-type to explain this use case

I can possibly put in these changes myself unless Microsoft has a weird CLA for contributing to the docs

**Comment by JoelEinbinder** [comment]
Hi Kayce!

Type is a much older method than fill and has different behavior.

Type sends individual key press events matching whatever string you give it. It doesn't clear the input, because it doesn't even know there is an input to clear. It's for testing how your app responds to key events.

Fill looks at the element and tries to set its value to the provided string. It's for testing the way your app behaves with a specific value. It's also way faster than type.

We can't change the behavior of type("") as that would be a breaking change. But happy to add whatever to the docs to make it more clear. Microsoft has a CLA I don't know the specifics of how it works or whether it applies to one line patches.

**Comment by aslushnikov** [comment]
Oh hey hey @kaycebasques! 👋  Long time no see!

> As for the best way to clear an input, I'd use fill("") rather than the evaluate.

Adding my +1 here! That's a nice way to clear fields.

Feel free to send a PR if you'd like! I'll close this bug meanwhile since the discussion is staled.
