### ISSUE TITLE
[Question] (Pixels different win/linux) Run Windows type Browser instance on Linux eg

### ISSUE THREAD

**Issue by miapisquare** [microsoft/playwright#10120]
It turned out that browsers under Linux and Windows have pixel deviations (because of CSS) and have slightly different optical results (which are only noticeable in direct per pixel screenshot comparison between windows and Linux results, there are few pixels shifted). The goal was that the screenshot deviation on GUI-tests between "Linux" and Windows is zero. Literally.

Is it somehow possible to start a Windows instance of a playwright browser via wine (in this case chrome), for example? I need this to compare changes within my team, which are windows users. (The most use windows, some Linux - i do)

I don't care about the performance, the main thing is that it works - and I can test under Linux whether the view under Windows has changed when i have maybe made "bad" changes.

Did someone have had this kind of issue and found a solution?

Here is a example. The purple pixels are showing that there is something different. There are only some different (in most cases). But in our app some things are actually way too different! (Image 2)
![grafik](https://user-images.githubusercontent.com/58987715/140697298-7d15a760-93d2-43e7-8529-0bb21a7f6586.png)

![grafik](https://user-images.githubusercontent.com/58987715/140697512-11641645-a478-4760-8852-421adeb61379.png)

I would be happy to talk about such topics in general. I can imagine that there are many, who have these problems. I've read a lot about how to solve pro-active such problems. It seems to have something to do with CSS (em.), but it would be important for me to test what the view looks like under Windows anyways - with Linux.Without cross-testing i wouldn't have known this behaviour actually. To be able to do this within only one operating system, would be really useful. Doing this vice versa under Windows could be nice too.

**Comment by mxschmitt** [comment]
This is a common problem, since rendering and paining in browsers happens in WebKit on the platforms on entire different layers, so its often a bit different on a per pixel basis. Usually you solve it by splitting your tests up into normal tests and visual regression tests. These VRT tests you then run inside Docker to ensure you'll always get the same outcome. This will then work across all the operating systems (Linux, macOS, Windows) and produces the same result.

We're working on enhancing the story around this problem to bring a better DX to the users. So I'd probably merge it into #8161.
