### ISSUE TITLE
[Feature] Pause test (`page.pause()`) on failure

### ISSUE THREAD

**Issue by dtinth** [microsoft/playwright#10132]
Sometimes I ran Playwright test, the the test failed. The browser is closed before I can inspect it. The trace may not provide enough information (e.g. when debugging websockets or the test failed while waiting for a response from server).

When I run Playwright again with the inspector, I can no longer reproduce the problem.

Since E2E tests can be more prone to heisenbugs, I’d like to suggest having an option to pause the test when a test is failed — before the browser context is closed, so developers will have a chance to investigate what happened.

I have tried this:

```ts
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus) {
    await page.pause()
  }
})
```

However,

- The inspector closes itself because 30 seconds has passed (due to test timeout).
- Stack trace is not shown; there is no indication of what failed.

After a while I came up with this workaround...

```ts
// When running outside CI, pause Playwright when a test failed.
// See: https://github.com/microsoft/playwright/issues/10132
test.afterEach(async ({ page }, testInfo) => {
  if (!process.env.CI && testInfo.status !== testInfo.expectedStatus) {
    process.stderr.write(
      `❌ ❌ PLAYWRIGHT TEST FAILURE ❌ ❌\n${
        testInfo.error?.stack || testInfo.error
      }\n`,
    )
    testInfo.setTimeout(0)
    await page.pause()
  }
})
```

I wish this is available as a CLI flag.

**Comment by rwoll** [comment]
I'd find this feature helpful as well! As a bonus/scope-creep, would be nice to be dropped into a node repl with all the context (vars, etc.) that failure occurred at so you can poke around. Without this, I tend to throw a bunch of `console.log`s into my test one after another. (Yes, I probably should set up a debugger instead.)

**Comment by dgozman** [comment]
@dtinth, @rwoll Did you try running with inspector and clicking "resume" button so that the test goes to the end? Does this make the problem disappear so that you are unable to debug it?

I think we already pause at the end of a test if you run with inspector. If that does not work for you, I think the manual `page.pause()` like in the snippet above is a good workaround. Fixing #10353 will avoid the need for `test.setTimeout(0)`.

Why do you want to see the stack trace? Don't you get a failed action in the inspector? I am not sure there is a good place to show this error, before the test finishes and test reporter picks it up.

**Comment by hyatt-andydelso** [comment]
Could the trace viewer be used to accomplish this?

**Comment by ddaypunk** [comment]
Would using the trace viewer accomplish what you are looking for?

**Comment by dtinth** [comment]
@ddaypunk The trace viewer is very helpful in most cases. However, not everything is recorded in traces, e.g. WebSocket messages.

@dgozman Sorry for late reply.

> Did you try running with inspector and clicking "resume" button so that the test goes to the end? Does this make the problem disappear so that you are unable to debug it?

Here’s a small repro.

```js
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {
  // Let’s assume that in a real app, when clicking #button,
  // the #message would change to "Loading" and later "Completed".
  // However, in a rare case, the message would get stuck at "Loading".
  const html = `
    <!DOCTYPE html>
    <button id="button" onclick="message.textContent='Loading'">Click me</button>
    <p id="message">Message</p>
    `
  await page.goto('data:text/html,' + encodeURIComponent(html));
  await page.click('#button');
  await expect(page.locator('#message')).toHaveText('Completed');
});
```

I run this with:

```
env PWDEBUG=1 npx playwright test
```

Then clicked the "Resume" button.

> I think we already pause at the end of a test if you run with inspector.

Apparently, when the test is run to the end, the browser is gone, regardless of whether the test failed or passed. Coming from Cypress, when the test finished running, you can still interact with the web page, and having that facility helped us in debugging failed test tremendously.

> Why do you want to see the stack trace? Don't you get a failed action in the inspector? I am not sure there is a good place to show this error, before the test finishes and test reporter picks it up.

If a Playwright action failed, it _does_ show in the inspector:

![image](https://user-images.githubusercontent.com/193136/148425346-3d22534e-073b-47eb-88b7-88fe4ad157fb.png)

However, a test can also fail due to other reasons. For example, I changed this:

```diff
-  await expect(page.locator('#message')).toHaveText('Completed');
+  throw new Error('Test failed because something else');
```

In this case, nothing would show up on the inspector.

![image](https://user-images.githubusercontent.com/193136/148425733-d0324e5b-bffc-4289-be4c-966d8057cac0.png)

**Comment by pavelfeldman** [comment]
Check out Playwright Test for VS Code plugin, it'll stop on failure when debugging!

**Comment by bradydowling** [comment]
@pavelfeldman does that work with VS Code workspaces? It's not seeing the tests that I have in my workspace, just sees some random folders

**Comment by AlexDaniel** [comment]
I'm just starting with playwright and I'm a bit confused. Without this feature, how exactly am I supposed to use Playwright? So, I have a test file with a bunch of tests, let's say 3 of them fail (say I'm tweaking a bunch of stuff and need to adjust tests, or I'm moving from something else to playwright). OK, what should be my next steps? Right now I insert page.pause() before the fail, then I copy the test name and provide it with "-g", I rerun the tests to inspect the situation in the browser… I fix my tests, then I remove `.pause`, remove -g, let the tests run… still 3 tests failing, just on a different line this time, so I repeat the whole thing again. To summarize: an absolute freaking pain. It's nice to know that in VS Code this problem is resolved, but I'm not using VS Code.

Ideally, the workflow should be: you run tests, it pauses on failure automatically, you tweak tests and rerun them. That's it, no need to deal with command line args or anything.

**Comment by s-h-a-d-o-w** [comment]
> Check out Playwright Test for VS Code plugin, it'll stop on failure when debugging!

I would like to note that this doesn't work for browser extension testing, since that requires using a persistent context. Which obviously needs to be deleted between runs for consistency. And this plugin doesn't support running custom scripts before test start.

**Comment by s-h-a-d-o-w** [comment]
For me, overriding the timeout using `testInfo.setTimeout(0)` doesn't work, playwright still exits. Is it just me?

If not, how does everybody deal with the fact that playwright will either freeze forever if timeout is 0 and something can't be found or it will exit, preventing debugging.

> Check out Playwright Test for VS Code plugin, it'll stop on failure when debugging!

There are two problems with this:
1. Not everyone uses VS Code
2. The error isn't output anywhere (Of course a minor problem because one can just inspect the state - still, it's more convenient when one can see expected vs actual value in the terminal)

**Comment by Romex91** [comment]
**I think this feature is an absolute must-have.**
None of the suggested solutions worked for me:
* Would using the trace viewer accomplish what you are looking for?
No. It's very inconvenient, especially when having multiple browsers open simultaneously.
* Check out Playwright Test for VS Code plugin, it'll stop on failure when debugging!
No capability to specify environment variables 
* suggested workaround from the issue description :
```
// When running outside CI, pause Playwright when a test failed.
// See: https://github.com/microsoft/playwright/issues/10132
test.afterEach(async ({ page }, testInfo) => {
  if (!process.env.CI && testInfo.status !== testInfo.expectedStatus) {
    process.stderr.write(
      `❌ ❌ PLAYWRIGHT TEST FAILURE ❌ ❌\n${
        testInfo.error?.stack || testInfo.error
      }\n`,
    )
    testInfo.setTimeout(0)
    await page.pause()
  }
})
```
This doesn't help, because at this moment the test is torn down and all the browsers are closed. So you cannot observe the page in the state it was during the error.

**Comment by dtinth** [comment]
With the "Show & Reuse Browser" in recent versions, I no longer have issues debugging Playwright tests. Given the new feature, I now find this feature request unnecessary and resolved. Thanks for the great work! 🙏

**Comment by AlexDaniel** [comment]
What's “Show & Reuse Browser”? Can you elaborate?

**Comment by dtinth** [comment]
@AlexDaniel Check out this part of the release party video: https://youtu.be/NFLHA57a-so?t=141

**Comment by AlexDaniel** [comment]
@dtinth That doesn't help at all for anybody who is not using VSCode.

**Comment by dtinth** [comment]
@AlexDaniel Right… I’ll reopen it for the people who do not use VS Code.

**Comment by pavelfeldman** [comment]
We recommend using VS Code (with Playwright Extension) for better debugging. It addresses this issue among many other things. It is unlikely that we'll be improving the debugging story inside the inspector in the nearest future.

**Comment by AlexDaniel** [comment]
Uh… I'm not even sure how to react to that. I have some colleagues who use VS Code but still prefer to work with tests from the command line. And I'm not going to switch an entire IDE (or run another one in parallel) just because of a testing tool. Such a weird decision for a simple feature like that.

**Comment by nvsd** [comment]
It's hard to believe this is considered a solution without any follow-up or explanation on why this is the case.
It's a tough sell to tell my team when there's at least a little IDE lock-in. Is this also indicative of the direction you guys are taking? To have relatively expected features in the future, do we have to use vscode?

**Comment by dtinth** [comment]
You might have missed the [Playwright v1.32 release video](https://www.youtube.com/watch?v=jF0yA-JLQW0) that got published just yesterday.

Playwright now comes with a [UI mode](https://github.com/microsoft/playwright/releases/tag/v1.32.0). You can write your tests in Vim and they will re-run whenever you save, and it also lets you visually inspect the test.

![](https://user-images.githubusercontent.com/746130/227004851-3901a691-4f8e-43d6-8d6b-cbfeafaeb999.png)

**Comment by nvsd** [comment]
That's amazing. Thanks for the work.

**Comment by bennbollay** [comment]
Chiming in here - dedicated vim user.  Not being able to add a "break on failure" command line flag really complicates the development process, even with --debug involved (which I would expect to do exactly that).

**Comment by JustinAimiable** [comment]
Hey, this is a closed issue, but I am just chiming in because I found a way to do page.pause() on failure that may help others' use cases. My solution involves using soft assertions, `expect.soft()` combined with `test.info().failures`, like so:

```javascript
await expect.soft(this.page.getByRole('link', { name: 'Edit' })).toBeEnabled()

if (test.info().errors.length > 0) {
  await this.page.pause()
}
```

This has helped in debugging some flaky tests, so hope this helps someone else :)

**Comment by joepio** [comment]
Closing the window on failure in `--debug` mode seems like an odd choice. Also seems like a trivial thing to improve. Check if running in debug mode, if true, don't exit.
