### ISSUE TITLE
Hide/remove Elements from Screenshots

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#10162]
### Discussed in https://github.com/microsoft/playwright/discussions/5068

<div type='discussions-op-text'>

<sup>Originally posted by **rollin-cogers** January 20, 2021</sup>
Hey everyone! I've been very excited to use this tool for testing, as I've previously been using protractor for all my testing.

In the past I've used modules like webdriver-image-comparison that allow for options like [hiding and removing elements](https://github.com/wswebcreation/webdriver-image-comparison/blob/master/docs/OPTIONS.md#hideelements-5) from a screenshot by adding `visibility: hidden` or `display: none` to the styling for the passed elements.

Is this a feature that we might see in the future with playwright? Would anyone else benefit from the ability to exclude elements from screenshots?

I would love to see something like this:
```javascript
page.screenshot({fullpage: true, hideElements: ['div.dynamic_content', 'div#profilePicture']})
```</div>

**Comment by Evilweed** [comment]
Please consider allowing Playwright Users to define how element will be hidden. 

We are currently adding, and removing a class that makes text and background colors black so that the element is still on screenshot, just it's dynamic content does not affect screenshot tests. Some cases would need display:none.

**Comment by thorleifjaocbsen** [comment]
What about instead of hiding elements making a "mask" function?

I'd love to have this: 

```
page.screenshot({
  mask: {
    x: 10,
    y: 300,
    width: 500;
    height: 20
  }
});
```

**Comment by p01** [comment]
@Evilweed you know your use case better than anyone, but rather than `display: none`, but Playwright should rather use `visibility: hidden` to hide elements without effecting the layout of the page.

**Comment by aslushnikov** [comment]
Everybody: So far we're considering adding the blackout option to the screenshot:

```js
await page.screenshot({
  blackout: [
    page.locator('.my-dynamic-element'), 
    page.locator('.some-video'), 
  ],
});
```

Let us know if it will or will not work for you!

**Comment by thorleifjaocbsen** [comment]
Could you elaborate in what it does? Blackout seems to make the area of the element black instead of whatever color it has. This can be a problem if e.g. a fullscreen popup comes with transparent background. Will render the whole page black. Hehe.

But if it does visibility: hidden on them it should not really affect anything :) Other than that, I think it is a perfect implementation! :)

**Comment by p01** [comment]
Perfect!
The only objection is about the term `blackout`. Let's change for something more generic e.g. `hide`, or `hideElements`

**Comment by ph4un00b** [comment]
nice cool work @aslushnikov, I wanted to use that mask feature but it is not ready yet on 1.19.2, what is the easiest way to point out the main branch in order to use it on npm, since I currently have `"@playwright/test": "1.19.2"`

**Comment by aslushnikov** [comment]
@ph4un00b Playwright 1.20 is coming out in a few days. Meanwhile, you can install Playwright from tip-of-tree using `npm i @playwright/test@next`

**Comment by ph4un00b** [comment]
@aslushnikov all good, it works but I have an issue, seems like the mask is behaving like having a `z-index=Infinity` css prop.
![image](https://user-images.githubusercontent.com/1057021/157953176-20e2a041-fb3a-4328-9541-c079fe0f709b.png)
I have two buttons with higher z-index `z-index=10` than the mask locator, actually the class locator has a `z-index=-1` but the mask totally covers it up. Is that the expected behavior? I was expecting to see my two buttons above the mask.

**Comment by aslushnikov** [comment]
@ph4un00b yep, totally expected. In this case, it seems like using request interception to feed in some different image would work better for you!

**Comment by mav10** [comment]
Can not find any docs for this feature is it still present or was deprecated?

**Comment by NickDuBois** [comment]
In our case, dynamic content results in elements with all sorts of different height values.  Because of this, there are still differences even when using the mask feature.  Would be great if there was an option to set the color used for the mask.  

In my case I'd set it to the pages background color.

**Comment by matthias-ccri** [comment]
For posterity, the `mask` option is documented [here](https://playwright.dev/docs/api/class-locator#locator-screenshot)

**Comment by khryshyn** [comment]
Mask option does not work for cases If some elements appeared on the page because of rendering through SSR, It's hard to mock API and it would be really nice to have either option to mock SSR or hide elements from the page, for example global messages toast

**Comment by Albert-Valdes** [comment]
I ran into an issue with the mask feature and a `position: fixed` element. The mask is layered over the element I am trying to take a screenshot of. Similar to the issue @ph4un00b ran into. Is there a way to hide the masked element's visibility completely? Looking for a way to set `visibility: none;` on that element

**Comment by Albert-Valdes** [comment]
Some masks cause an overlay due to the masked item having `position: absolute`. This causes an issue where I am not able to screenshot the elements that are beneath the masked element's layer.

**Comment by nmay231** [comment]
@Albert-Valdes I ended up just using `page.evaluate()` to hide my elements manually, though I will keep the mask options in mind for future tasks.

**Comment by jehon** [comment]
For those coming here, you can inject a css file when running the tests...
https://playwright.dev/docs/api/class-page#page-screenshot

To configure it globally:
https://playwright.dev/docs/test-configuration#expect-options

In short: pass options with { stylePath: "e2e.css" }.
Hope it help

**Comment by yairEO** [comment]
This issue aught to be re-opened as the `mask` property does NOT solve all use-cases, as others mentions here that the mask is covering OVER the masked area which is in MANY cases not the desired outcome at all, which is to _HIDE_ page elements and _NOT_ mask them, because any element which is rendered at a masked X & Y position will also be masked, and I find this absurd for UI testing which usually has complex common scenarios with tooltips/popups and transformed elements which can appear.. anywhere over the masked area.

I really plead for this issue to be re-opened as this is a **very** basic and important thing playwright is expected to support out-of-the-box for UI screenshot tests, so please please give it a thought.
