### ISSUE TITLE
[Feature] introduce predicate web-first assertions

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#10235]
Context: https://github.com/microsoft/playwright/issues/10187

In general, this is a feature request to support predicate as an argument to `expect`:

```js
await expect(asyncPredicate).toBe(10);
```

The `await expect(..)` construct should retry predicate until it reaches certain value.

**Comment by PaperStrike** [comment]
I think it necessary to clarify how exactly this feature request will work.

I copied this line from a [comment](https://github.com/microsoft/playwright/issues/10187#issuecomment-964600993) in the initial issue as the proposed usage:

```ts
expect(page.locator('[e2e-target="summary-cost"]').getAttribute('e2e-data').then((value: string): number => Number(value))).greaterThan(1000);
```

Technically to achieve this we may need to rewrite the promise prototype methods, at least to design and change the interface used by internal methods like `locator.getAttribute`, to get the function(s) that is passed so that we can re-run.
Semantically it looks like redesigning promises, as we know a standard promise's resolved value never changes.

So this feature request, if accepted, seems more likely to be implemented in a way similar to the wait-for methods (e.g., [`page.waitForFunction`](https://playwright.dev/docs/api/class-page/#page-wait-for-function)),

```ts
const asyncPredicate = () => (
  page.locator('[e2e-target="summary-cost"]').getAttribute('e2e-data').then((value: string): number => Number(value))
);
await expect(asyncPredicate).toBeGreaterThan(5, { timeout: 3000 });
```

or

```ts
const asyncPredicate = async () => (
  Number(await page.locator('[e2e-target="summary-cost"]').getAttribute('e2e-data'))
);
await expect(asyncPredicate).toBeGreaterThan(5, { timeout: 3000 });
```

that wrap with functions, right?

**Comment by aslushnikov** [comment]
> ```js
> expect(page.locator('[e2e-target="summary-cost"]').getAttribute('e2e-data').then((value: string): number => Number(value))).greaterThan(1000);
> ```

This won't work since this passes in a promise, whereas we need a promise factory to be able to retry. Thus we'd need to have async function.

Following your example, it'd look like this:

```js
await expect(() => page.locator('[e2e-target="summary-cost"]').getAttribute('e2e-data')).toBeGreaterThan(5, { timeout: 3000 });
```

**Comment by PaperStrike** [comment]
This looks great as a "`waitForFunction`" that runs in Playwright's context!
