### ISSUE TITLE
[Feature] Add chromiumSandbox to configuration

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#10272]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Since bitbucket needs to have [chromiumSandbox off ](https://playwright.dev/docs/ci/#bitbucket-pipelines), it would be nice to have the configuration allowed here.

It wouldn't be out of place either since we have the [channel](https://playwright.dev/docs/test-configuration#basic-options) option, which is exclusive for the chromium browser.

However, in my brief POC tests, bitbucket seems to run fine without the `chromiumSandbox` setting, but since the documents state that it's necessary, exposing this still seems like a good idea down the line.

**Comment by PaperStrike** [comment]
I think you can already use it via [`launchOptions`](https://playwright.dev/docs/api/class-testoptions/#test-options-launch-options).

It works fine without an explicit setting probably because it [defaults to `false`](https://playwright.dev/docs/api/class-browsertype/#browser-type-launch-option-chromium-sandbox).

**Comment by A-ZC-Lau** [comment]
@PaperStrike You're right, I will close this.

Thanks.
