### ISSUE TITLE
[Question]: Why launch_persistent_context always open a new blank page

### ISSUE THREAD

**Issue by Leezj9671** [microsoft/playwright#10347]
### Your question

I used `--restore-last-session` args in launch_persistent_context, so every time I launch and close context will create one more blank page which confused me a lot.
What I want to know is how to use `launch_persistent_context` like `launch` so I can control when I open new page.

**Comment by Leezj9671** [comment]
[#7104](https://github.com/microsoft/playwright-python/issues/1024)

**Comment by Leezj9671** [comment]
Still a problem.

use ` await context.pages()[0].close();` or 
```
    const page = await context.pages()[0];
    await page.goto("http://microsoft.com")
    await page.waitForTimeout(403043)
    await context.close()
```
can't work. Because if I used `--restore-last-session` as chromium startup args, `pages()[0]` maybe not the new blank page but the last session page, so might be close the last session page.

**Comment by JoelEinbinder** [comment]
We open the blank page for consistency with headless/headful modes and and open up a page to make starting up playwright more consistent. This is not going to change.

Instead of just closing the first page, you can check its url to see if its the blank page you want to close. You can also use the [context page event](https://playwright.dev/docs/api/class-browsercontext#browser-context-event-page) to listen for new pages and decide if you want to close them.

This is out of scope from playwright's testing focus, so that's all I can offer.
