### ISSUE TITLE
[Question] Best way to write helper functions

### ISSUE THREAD

**Issue by alisterscott** [microsoft/playwright#10358]
Hi

We have a material UI app which has those (annoying) select lists which aren't actually select lists

I wrote some helpers to select a value, and first value as per below, but I am wondering are these the "Playwright way"? Is there a better, shorter, more in built approach for things like this?

thanks

`uihelper.ts`

```ts
import { Page } from '@playwright/test';

export async function selectValue(
    page: Page,
    buttonSelector: string,
    dataValue: string,
) {
    await page.click(buttonSelector);
    await page.click(`li[role="option"][data-value="${dataValue}"]`);
}

export async function selectFirstDisplayedValue(
    page: Page,
    buttonSelector: string,
) {
    await page.click(buttonSelector);
    await page.click('li[role="option"]');
}
```

**Comment by A-ZC-Lau** [comment]
generally, if they're components, I'd use a combination of Page Object Model, and Component Object Model (it's what I call it, which is based on the POM name).

A component object model is basically a page object model, but only should not be instantiated in an of itself, but requires a parent Locator. This is because you could have multiple of the same component on the same page (e.g. select list).

So an example of the code could be:

component.ts
```typescript
class SelectList {
	constructor (protected readonly _parent : Locator) {
	}
	get options () {
		return this._root.locator(`li[role="option"]`)
	}
	protected get _root () : Locator {
		return this._parent.locator(selectListIdentifier);
	}
}
```

page.ts

```typescript
class Page {
	constructor (protected readonly _page : Page) {
		// alternatively, you could pass a very generic Locator, e.g. page.locator("body") (which is what I normally do)
		// e.g.
		// constructor (protected readonly _page : Locator)
	}
	get select_list () {
		return new SelectList(this._root);
	}
	get _root () {
		return this._page.locator(rootIdentifier);
	}
}
```

usage example

```typescript
test("example", async ({ page }) => {
	const testPage = new Page(page);
	await testPage.select_list.options.nth(0).click()
})
```

**Comment by JoelEinbinder** [comment]
See https://playwright.dev/docs/test-pom

**Comment by alisterscott** [comment]
I wasn't really asking about page object model - more about handling UI elements which are common across a whole web app and how to write helper functions to handle them across many different pages. I'll just stick with my current approach anyway.

**Comment by An-dy1** [comment]
I see that this comment is closed, but fwiw, I am wondering the same: best practices for writing helper/utility functions. My use case is navigation within my app. The nav bar is something available when you're on all pages of the app, so it doesn't make sense to organize methods to interact with the nav menu in a specific page.

**Comment by alisterscott** [comment]
@An-dy1 see https://github.com/alisterscott/playwright-test-ts-demo/blob/main/lib/actions/nav.ts for an example of how I use 'actions' instead of pages to organise my Playwright code

**Comment by An-dy1** [comment]
Thank you! Actions and fixtures are an area where I have a lot to learn, and your example is helpful. 

Earlier today I ended up making a class called "NavigationHelper." I went with a class over individual functions (actions, I suppose) because I needed to reuse locators across various functions (we have a nested nav like a lot of sites so first you click a top-level link, then select a page where you're going, and that top-level link gets clicked for everything.) I could have just declared global variables for the locators but thought since they're all related, a class makes sense.

Anyway, thanks again!

**Comment by joeystdio** [comment]
I've created a material-helper.ts:

`
import { Page } from '@playwright/test';

export class MaterialHelper {
  readonly page: Page;

  constructor(page: Page) {
    this.page = page;
  }

  async autocomplete(locator: string, value: string) {
    await this.page.fill(`[formcontrolname="${locator}"]`, `${value}`);
    await this.page
      .locator(
        '.cdk-overlay-container .mat-autocomplete-panel .mat-option-text'
      )
      .filter({ hasText: `${value}` })
      .first()
      .click();
  }
}
`

then created a test-options.ts:

`
import { test as base } from '@playwright/test';
import { MaterialHelper } from './material-helper';

export type TestOptions = {
  helper: MaterialHelper;
};

export const test = base.extend<TestOptions>({
  helper: async ({ page }, use) => {
    use(new MaterialHelper(page));
  }
});

`

then in a test spec you can use it like so:
`
import { test } from './test-options';

test('should autocomplete', async ({ page, helper }) => {
  await page.goto('/');

  await helper.autocomplete('locator', 'VALUE');
});
`

I think it's the "correct" way at the moment.
