### ISSUE TITLE
infra: move docker publishing workflow to main repo

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#10351]
Turns out we can build arm64 docker image on x86_64 using `docker build --platform linux/arm64` command

**Comment by jamesmortensen** [comment]
Hi Alexey, I enjoyed your talk at TestJSSummit and decided to take a look.  Sorry if this isn't the right place for this question:  

Does Playwright support ARM64 platforms?  I am trying it on a Debian 11 ARM64 VM, and the Playwright-installed WebKit binaries all appear to be AMD64 not ARM, and from what I'm reading, I cannot simply pass a custom binary, such as /usr/lib/aarch64-linux-gnu/webkit2gtk-4.0/MiniBrowser because Playwright uses custom versions of these.  

I see you've mentioned building an arm64 docker image.  Are there arm64 browser binaries as well? Thank you.

**Comment by aslushnikov** [comment]
Hi @jamesmortensen! 

Thank you for listening to the TestJSSummit talk :) We **do support** Ubuntu 20.04 arm64; we **do not support** debian 11 on either x86_64 or arm64.
