### ISSUE TITLE
[BUG] page.uncheck: "Element is not attached to the DOM"

### ISSUE THREAD

**Issue by benwiley4000** [microsoft/playwright#10477]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Linux
- Node.js version: 14.16.3
- Browser: Firefox

**Code Snippet**

```
page.uncheck(flakySelector);
```

**Describe the bug**

I get an error message telling me that the element isn't attached to the DOM sometimes when using `page.uncheck` (and `locator.uncheck` but I'm not sure if this is expected since it's not a `page` method). This is in contrast to `click()` which always retries if the element is detached. I can replace all my instances of `check` and `uncheck` with `click` and my test passes, but I would prefer to use `check` / `uncheck` for greater validation.

I see this message for `page.uncheck` :

![2021-11-22_15-32](https://user-images.githubusercontent.com/13558253/142931454-3d1b3265-450a-46d2-9f29-4d96a3eb4706.png)

Maybe we forgot to catch this error ?»

I believe the problem is because something goes wrong between the click and the check for isChecked(), and I guess we don't handle detach after click gracefully.

**Comment by yury-s** [comment]
> This is in contrast to `click()` which always retries if the element is detached. I can replace all my instances of `check` and `uncheck` with `click` and my test passes, but I would prefer to use `check` / `uncheck` for greater validation.
> 
If you don't need to check if the checkbox actually gets checked after clicking on it and its element gets detached from the DOM tree for some reason then it may be a better way to use just click. Especially if the checkbox itself disappears due to navigation or something else and there is another element that shows that you can use to validate if the action has actually been performed.

> I see this message for `page.uncheck` :
> 
> Maybe we forgot to catch this error ?»
> 
> I believe the problem is because something goes wrong between the click and the check for isChecked(), and I guess we don't handle detach after click gracefully.

This is intentional, `setChecked` will also wait for the selected element to be attached to the DOM and clickable. Once the selector resolves to an attached element it is expected to stay attached after the click. If it gets detached too soon it'd be similar to the user not seeing it in the checked state at all. Click and validation that the checkbox changed its state are performed asynchronously and if the checkbox gets detached in between we'll not retry (as e.g. it could result in a second click on the same checkbox) and throw the error that you see instead.

**Comment by benwiley4000** [comment]
For context, the rendering engine (I didn't write it!) replaces the innerHTML of the whole view area whenever there's a state update, so yes the element gets detached after a change, but it's immediately replaced with an identical element. My test works if I use click but I also put expects before and after to validate the checkbox state. I thought this type of situation was the impetus for retrying a click if the element gets detached and I don't see why checking a box would be any different.

**Comment by benwiley4000** [comment]
To be clear I would not expect a click retry, I would just expect to requery the element if needed and validate that it's checked. Surely there's no downside ? If the element was truly detached and gone, the assertion will fail, but if another element's there in its place, I'd expect the assertion to pass.
