### ISSUE TITLE
[Feature] "Safe version" of page.type()

### ISSUE THREAD

**Issue by benwiley4000** [microsoft/playwright#10495]
Clicking has a bunch of precondition checks that don't happen for typing, including a visible check, an enabled check, and waiting for two animation frames before continuing. The consequence for me was an intermittent failure for page.type where the events had apparently been sent but nothing showed up in the field. I was able to resolve my problem by clicking in the field first before typing.

I'm still working on figuring out what I would need for a repro case / why the typing wasn't working at first. But given that so few checks are done before typing, I'm wondering if we could have an option that does check the same things as we would for a click before proceeding. I'm assuming fewer checks are done because we are accounting for the case of a hidden input element, but often these checks could be helpful.

**Comment by dgozman** [comment]
@benwiley4000 There is a balance to be had here. The `type` method is generic enough so that you can type anywhere. Most likely, you'd want to use [`locator.fill()`](https://playwright.dev/docs/api/class-locator#locator-fill) instead that does [more checks](https://playwright.dev/docs/actionability). This method is intended for filling a field - ideal for your usecase. Let us know if that helps.

**Comment by benwiley4000** [comment]
@dgozman I think this method seems to address the use case I was describing. I didn't realize that's what the fill method was for! Thank you.
