### ISSUE TITLE
libvpx.so.5 missing from webkit browser patches

### ISSUE THREAD

**Issue by AdrianNeatu** [microsoft/playwright#10508]
A while back libvpx.so.5 was added to the webkit browser patches in order to work on ubuntu 20.04, check this MR: https://github.com/microsoft/playwright/pull/2458

However, I see that this was removed afterwards in this commit: https://github.com/microsoft/playwright/commit/c1032ae483f67ea5e58c544ad4a9fa38be23615f

Is this intentional?

**Comment by mxschmitt** [comment]
Could you share more information about your environment (os, version etc.) - how you stumbled upon this?

You can install all the necessary dependencies using: `npx playwright install --with-deps`, then it should work. We run our tests ourselves on Ubuntu 20.04 without any issues.

**Comment by mxschmitt** [comment]
Could you use a pinned image like `docker pull mcr.microsoft.com/playwright:v1.17.0-rc1`? We run all our tests inside Docker as well to ensure [it works](https://github.com/microsoft/playwright/actions/workflows/tests_docker.yml) and could not identify any issues in the past few releases.

In your case it does more look like a full crash rather than a missing dependency. Would it be possible that you could narrow it more down and create a reproducible for us? Is it reproducible 100%?

**Comment by AdrianNeatu** [comment]
Same issue with the specific docker image. I'll get back with a narrowed down project in 2-3 days.

**Comment by yury-s** [comment]
@AdrianNeatu we need a repro to act on this, there is a crash in webkit which is triggered by some code in your script but it's hard to tell by looking at the screenshots where it is failing.

**Comment by AdrianNeatu** [comment]
@yury-s I didn't mage to isolate the issue in a slip repro setup. I need a bit more time. We can close this issue and I'll open a new one when I have all the details. Thanks!
