### ISSUE TITLE
[Question]Error using playwright in Tauri

### ISSUE THREAD

**Issue by yizhiyan** [microsoft/playwright#10528]
Error using playwright for Tauri.
I only created the basic Tauri program, which cannot be compiled after import.

I first used playwright with Tauri for development, but unfortunately there was an error when I first introduced the package

https://tauri.studio/en/

```
const {webkit}=require("@playwright/test")
console.log(webkit)
```
The following is the error message
```
 ERROR  Failed to compile with 5 errors                                                                      下午2:12:48

These dependencies were not found:

* electron/index.js in ./node_modules/playwright-core/lib/server/electron/electron.js
* module in ./node_modules/pirates/lib/index.js, ./node_modules/stack-utils/index.js
* readline in ./node_modules/playwright-core/lib/server/electron/electron.js, ./node_modules/playwright-core/lib/utils/processLauncher.js

To install them, you can run: npm install --save electron/index.js module readline
Error from chokidar (D:\): Error: EBUSY: resource busy or locked, lstat 'D:\pagefile.sys'
```

**Comment by mxschmitt** [comment]
Electron gets imported dynamically during the runtime see [here](https://github.com/microsoft/playwright/blob/master/packages/playwright-core/src/server/electron/electron.ts#L127).

I'm not familiar with Tauri, are you trying to bundle Playwright with it or just create some tests and not ship it next to your Tauri application?

Most likely you need to exclude Playwright from the build somehow. The error itself seems coming from webpack / vue.js.

Keep in mind, that you can't bundle Playwright inside your web-application since it requires a Node.js host.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by cosoc** [comment]
Why is it closed? This problem has not been solved. When it is packaged and released to customers, it will be specified that only specific browsers can be used. There is no need to have three browsers at a time. A size of more than 400 m cannot be found to be 1 g
