### ISSUE TITLE
[Question] What does it mean Error: strict mode violation ?

### ISSUE THREAD

**Issue by amrsalem1** [microsoft/playwright#10611]
```
 locator.click: Error: strict mode violation: "//button[text()='30']" resolved to 2 elements:
        1) <button tabindex="0" type="button" aria-label="Nov 30, 2…>…</button> aka playwright.$("text=30")
        2) <button tabindex="-1" type="button" aria-label="Nov 30, …>…</button> aka playwright.$(":nth-match(:text("30"), 2)")
```

**Comment by ltsuda** [comment]
the Locator API is strict, meaning if it finds more than one locator with your selector and you try to call a locator, like `.click()`, it will.

Look at the `Strictness` section here. I hope this helps.
https://playwright.dev/docs/api/class-locator

**Comment by dan-auth0** [comment]
For anyone reaching this issue via Google search,

The new page for Locators Strictness is here: https://playwright.dev/docs/locators#strictness

**Comment by samSam-0** [comment]
the things were written above are correct,
plus there might be a unique issue i faced before, for example if you use pom and trying to reach the element by using a path like **await Pages.mainPage.galeryView.itemList.getItem(id)** 
--> you need to be careful because when you try to reach something inside itemList but if you have some selectors related to getItem method which is taking you to another page that you store your item locators, **you might have added some of those locators in itemList page by mistake or confusion**, i know its a bit complicated but if you think that you element is absolutely unique and there should be not be such issue like that please consider the scenario i mentioned

**Comment by garyzhang21** [comment]
if i met this error, what should i do to click?

**Comment by ocleo1** [comment]
> if i met this error, what should i do to click?

@garyzhang21 through locator.first(), locator.last(), and locator.nth()

https://playwright.dev/docs/locators#works-fine-with-multiple-elements

**Comment by boatcoder** [comment]
> if i met this error, what should i do to click?

Or write a better locator expression that only selects 1 of the elements
