### ISSUE TITLE
[BUG] timeout in afterAll hook does not report which spec had the problem

### ISSUE THREAD

**Issue by MartinP-Autopilot** [microsoft/playwright#10624]
**Context:**
Playwright Version:1.16.2
Operating System: Windows and Linux
Node.js version: 14.17.3
Browser: Chromium

**Code Snippet**
Not sure which spec to provide the code snippet from

**Describe the bug**
I am currently running ~40 specs in CICD and one of them is causing the build to fail with the only reason "Timeout of 240000ms exceeded in afterAll hook" being printed to the console.  As the problem is in the afterAll hook, with none of the actual tests failing, there is no information about which spec has the afterAll problem.  

I am unable to identify which spec to investigate.

**Comment by mdemenko** [comment]
It's very inconvenient: basically any information in console or trace log if beforeAll and afterAll hooks were failed. Just general timeout error.

**Comment by dgozman** [comment]
@mdemenko I believe that `beforeAll` hook timeout is correctly attributed to the test file. If that's not the case, could you please provide a sample test?

**Comment by mdemenko** [comment]
@dgozman I use beforeAll hook to prepare some preconditions (navigate to the page and create test data, currently it can't be done through API). Due to low environment, sometimes hook fails with timeout error. In this case only error text is displayed in report (any test steps, screenshot and video). The same behavior if I add expect statement to beforeAll hook.
Maybe it works as expected since beforeAll hook doesn't support "context" and "page" fixtures. Could you please clarify this moment?
  
![Playwright Hook](https://user-images.githubusercontent.com/8157779/144584283-41604bed-024a-4f8d-a82e-a42444a06456.png)
