### ISSUE TITLE
[Feature] Validation of cropped / clipped text

### ISSUE THREAD

**Issue by kimchak** [microsoft/playwright#10686]
Add a validation method that would detect if text is clipped like in the example below. Using bounding-box methods such as isIntersectionViewport from puppeteer does not help in this case, and the only way to work arround this is visual testing (comparing with a snapshot):

![image](https://user-images.githubusercontent.com/60241771/144506725-7cd4b92e-89ea-4801-bedc-2461dda84b13.png)

**Comment by RockMinsk** [comment]
Hi, I have the same problem with cropped text - test passes when I'm using whole text in expectation although on UI it's cropped.
![2022_06_30_PW_cropped_text_validation](https://user-images.githubusercontent.com/30350649/176614713-66784932-9001-4c00-8c7b-bd1204653e5c.png)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
