### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID on https://playwright.dev/docs/intro

### ISSUE THREAD

**Issue by piotrszczepaniuk** [microsoft/playwright#10907]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: Not related
- Browser: All
- Extra: standard windows Windows 10 Enterprise environment

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // ...
})();
```

**Describe the bug**
I do not have access to playwright documentation via `[Getting started](https://playwright.dev/docs/intro)` link in your github documentation.
I have NET::ERR_CERT_AUTHORITY_INVALID error Certificate status The issuer of this certificate could not be found. Issued to: playwright.dev Issued by: infoblox.com. If I cannot read your documentation I can not use playwright.

**Comment by mxschmitt** [comment]
It seems like your antivirus/firewall/cooperate security program intercept the network traffic and break HTTPS connections. (Since you mentioned https://infoblox.com)

This is not something which can be fixed on our side, I'd suggest to disable temporarily your security software to find out which one breaks it.

**Comment by mxschmitt** [comment]
Closing since this is not an issue on our side, see above for more information.
