### ISSUE TITLE
[Feature] support route aka request interception for service workers

### ISSUE THREAD

**Issue by Francois-Esquire** [microsoft/playwright#1090]
Hi,

I'd like to be able to include markup directly instead of using `page.goto` to a remote address. I currently have a small example here of what I've tried out but it appears that `'serviceWorker' in navigator` is returning false and registering a service worker fails.

I've tried `page.setContent` as well and I had the same results.

Can anyone tell me what I'm missing? The example I am running:

```js
const { chromium } = require('playwright');

const msg = 'hi';

const serviceWorkerPath = '/sw.js';
const serviceWorkerScope = '/';
const serviceWorker = `console.log("${msg}");`;

const html = `<!doctype html>
<html>
  <head>
    <title>One Service Worker</title>
  </head>

  <body>
    <script type="text/javascript">
      console.log('serviceWorker' in navigator);

      try {
        navigator.serviceWorker.register('${serviceWorkerPath}', {
          scope: '${serviceWorkerScope}'
        });
      } catch (e) {
        console.error(e);
      }
    </script>
  </body>
</html>
`.trim();

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();

  await page.route('**/*.html', async request =>
    request.fulfill({
      status: 200,
      contentType: 'text/html',
      body: html,
    }),
  );

  await page.route(serviceWorkerPath, request =>
    request.fulfill({
      status: 200,
      contentType: 'text/javascript',
      body: serviceWorker,
    }),
  );

  await page.goto('http://example.com/index.html', {
    waitUntil: 'load',
  });

  const sw = await page.evaluate(`window.navigator.serviceWorker`);
  
  console.log(sw);

  if (sw) {
    const swTarget = await browser.waitForTarget(target => target.type() === 'service_worker');
    const worker = await browser.serviceWorker(swTarget);
    // use worker target/handle
  }

  await browser.close();
})();
```

**Comment by Francois-Esquire** [comment]
Any takers?

**Comment by arjun27** [comment]
Hi @Francois-Esquire, service workers are only available for [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), which is not the case for your example. Running `console.log(await page.evaluate("window.isSecureContext"))` returns false.

You could potentially serve the html over localhost with something like the [http-server](https://www.npmjs.com/package/http-server) NPM package. Would love to learn why you want to use inline HTML instead.

**Comment by Francois-Esquire** [comment]
Hey @arjun27 , appreciate you taking time to respond!

Hmm, I originally had set up a demo server on localhost and that was working as expected. I didn’t consider the secure context, but makes complete sense now in how I was using it... thanks for pointing that out. Maybe I could add:

`--unsafely-treat-insecure-origin-as-secure=http://example.com`

To the arguments, or change to `localhost`?

The goal essentially is to create a function I can reuse to execute code inside the service worker; on demand and with a portable solution not requiring an http server in place. I just need to register a service worker, thus a simple html page.

Is there a better way of achieving this?

**Comment by pavelfeldman** [comment]
`page.route` has no effect on the service workers since those live outside of page, inside the browser context. We will eventually get there. Two things are missing:
- move `page.route` to be `browserContext.route`
- attach to service workers and support interception there

**Comment by Francois-Esquire** [comment]
@pavelfeldman Thanks for addressing that, and really excited to hear the plan with that! Love the API design with that, would certainly help.

What I'm trying to do is register a service worker without a supporting web server to run `playwright` with - thanks to @arjun27 bringing up the point on secure context, I was able to have the `navigator.serviceWorker` in the browser context using inline `html` document, however the service worker registration hangs until it times out with this setup.

What could be the cause to this? Am I missing anything else? Again, this works with a conventional web server backing the playwright usage.

**Comment by Aaron-Pool** [comment]
Coming from #5014 . I added my thumbs up to the issue, but I also think it's worth explicitly pointing out that the inability to use `.route` with service worker requests makes playwright unable to listen to requests that have been intercepted and handled by [mswjs](https://github.com/mswjs/msw). MSW is a pretty big newcomer to the network mocking scene, thanks in large part to the articles and advocacy of Kent C. Dodds' (who is pretty much _the_ premier voice in the frontend testing world). I think compatibility between playwright and msw should be a pretty important consideration in playwright development.

**Comment by mszmida** [comment]
Hello 😃 

First of all I would like to thank the Playwright team for their effort. Great project awaited by me for a long time! Good job 👍 

I agree with @Aaron-Pool. The [MSW](https://github.com/mswjs/msw) library is a game changer in terms of the mocking of the back-end services and I think that not listening to the service workers requests is a significant drawback. I found this issue when I was looking for myself to integrate the MSW library with the Playwright with no luck. At least now I know the reason behind it.

Another reason why this functionality should be prioritized and implemented is the GraphQL that is used in the company that I work for and currently in the Playwright there is no easy possibility to differentiate the GraphQL requests. The MSW library solves this problem but currently Playwright do not like the service workers. I can easily imagine that a lot of people will have the same problem so this is not some kind of an edge case.

I would very much like this functionality to be implemented in a reasonable time.

Once again thank you for the Playwright 👍

**Comment by RFC2109** [comment]
Vote up for this feature.
It is very usefull because many website has service worker.
Disable sw is not a good idea,because it chang the system to test。

**Comment by Meir017** [comment]
Is it possible to implement this behavior currently using the `CDPSession` class directly?

**Comment by rwoll** [comment]
Upstream CR bug blocking proper interception of inital script: https://bugs.chromium.org/p/chromium/issues/detail?id=1304381

**Comment by rwoll** [comment]
Tracking additional upstream CR patch: https://chromium-review.googlesource.com/c/chromium/src/+/3526571

**Comment by rwoll** [comment]
The last two CLs landed with fixes required for this in-progress work; another one is needed for [crbug.com/1304795](http://crbug.com/1304795).

**Comment by kettanaito** [comment]
Hey. MSW author here. I'd very much love to see Playwright and MSW work together, which includes supporting more use cases. We've been testing MSW with Playwright for years and didn't have any issues. I think one of the things that confuses people the most is the execution context difference between your tests and the browser runtime in Playwright.

That being said, I'd love to migrate to `@playwright/test` in our repo and maybe have a designated smoke test for Playwright support. We have a few [such tests](https://github.com/mswjs/examples/tree/2338457a82f60e5d76a9a32a742157af21bf3606/examples) now but they are largely outdated as there's not enough hands to keep everything up-to-date.

**Comment by Aaron-Pool** [comment]
> Hey. MSW author here. I'd very much love to see Playwright and MSW work together, which includes supporting more use cases. We've been testing MSW with Playwright for years and didn't have any issues. I think one of the things that confuses people the most is the execution context difference between your tests and the browser runtime in Playwright.
> 
> That being said, I'd love to migrate to `@playwright/test` in our repo and maybe have a designated smoke test for Playwright support. We have a few [such tests](https://github.com/mswjs/examples/tree/2338457a82f60e5d76a9a32a742157af21bf3606/examples) now but they are largely outdated as there's not enough hands to keep everything up-to-date.
> 
> Let me know if I can be of any help when it comes to Service Worker nuances.

Playwright + MSW ❤️ 🔥 ❤️ 🔥

These are two of my favorite testing tools and I'd love to see them work together seamlessly.

**Comment by rwoll** [comment]
Thanks @kettanaito! Happy to hop on a chat and learn more about MSW from your perspective. You can find me on in the [Playwright Slack](https://aka.ms/playwright-slack).

At this point, this issue is tracking work in Playwright to ensure Network Requests occurring in SW's show up in Playwright's mocking/routing via `{context,page}.route`.

**Comment by kettanaito** [comment]
Would love to, @rwoll! Alas, that Slack link is no longer active. Could you per chance generate a new one?

I've just had an idea yesterday that may allow Playwright to know when requests are happening in the worker. Would love to tell you more about it and discuss whether it's something Playwright would want to support out of the box or as an extension.

**Comment by rwoll** [comment]
> Would love to, @rwoll! Alas, that Slack link is no longer active. Could you per chance generate a new one?
> 
> I've just had an idea yesterday that may allow Playwright to know when requests are happening in the worker. Would love to tell you more about it and discuss whether it's something Playwright would want to support out of the box or as an extension.

Oops—sorry about that! It should be updated now! 😄

**Comment by kettanaito** [comment]
Okay, I'm sharing my proposal below. 

## Context
A brief context to bring everybody onboard. 

Service Workers execute in their own thread, and have their own scope. Because of this, Playwright doesn’t know when requests are issued by the worker because there’s no standard means to know that. Although the worker’s requests appear in the Network, they still execute in their own (worker) scope.

## Proposal
I propose for Playwright to register a proxy worker that would look somewhat like this:
```js
// sw-proxy.js
self.addEventListener('install', () => {
  sendToClient({ type: 'event', name: 'install' })
})

self.addEventListener('fetch', (event) => {
  sendToClient({
    type: 'request',
    request: serializeRequest(request)
  })
})
```

The goal is to signal about the worker events back to the client (Playwright). You can use both `MessageChannel` and `BroadcastChannel` to do that, we can discuss which one is more suited for this particular case later.

There’s one catch though: there can only be 1 worker controlling the page. So, obviously, introducing `sw-proxy.js` means that any worker registered as a part of user’s tests will be ignored. To account for this, the proxy should _wrap_ any existing worker in itself.

One of the ways to achieve this wrapping is by using the `importScripts`:

```js
// sw-proxy.
// ...the rest of the proxy worker.

// Import the actual tested worker as the last thing.
// The order of imports affects the order of event
// propagation, so the proxy must always add its
// listeners first.
importScripts('/actual-user-worker.js')
```

When the workers are combined, the same events will bubbled through all of them based on the listener declaration order. If the proxy worker adds its listeners first, it will receive events first. On the premise that the proxy must treat events as readonly (never affect their outcome, for example, in the `fetch` event), we can find out when events happen, notify Playwright, and allow them to propagate to the underlying user worker to actually be resolved.

This order of execution may also allow us to influence event resolution in some cases. For example, if a request event matching a defined `.route()` pattern is received, Playwright may send back the mocked response, which the worker will use to respond to the request event:

```js
// sw-proxy.js
self.addEventListener('fetch', (event) => {
  signalToClient(
	  { type: 'request', ... },
    (data) => {
      const mockedResponse = JSON.parse(data)
		event.respondWith(mockedResponse)
    }
  )
})
```

> Keep in mind this is a pseudo-code, since delegating event response to a callback creates a race condition between the proxy request listener and the user worker request listener. You really want to use promises and await things properly but see the difficulties this brings below.

In a nutshell, this is how MSW works. 

There are 2 technical difficulties with this approach:

1. The “fetch” event listener must be synchronous. Any async logic must be deleted to the `event.respondWith()` that accepts a Promise as an argument.
2. Coming from the first point, if you call `event.respondWith()`, then you are handling the request _no matter the response outcome_. This will halt the event propagation to the user worker even when there’s no “route” defined for an intercepted request. 

Request spying is the most tricky part of this entire proposal. 

## Alternative route
I’m not aware how much Playwright is in control over the underlying Chromium but if it could patch the Service Worker’s global scope, then we could spy on the listeners without having to manage worker nesting and event propagation. Affecting the worker’s scope is rather dangerous so this must be approached with caution.

## Closing thoughts
In the end, the challenge is to know when certain worker events happen. And while tools like MSW already implement this client-worker channel that allows to intercept requests, they do not care for other worker events (like life-cycle events), which may be of interest to people who would want to test their workers extensively. At the same time, MSW operates with a single worker, and whenever people have their own worker we just recommend to use `importScript` manually in the `mockServiceWorker.js`. This isn’t a good strategy to adopt in Playwright, neither it’s a working strategy for it.

**Comment by kettanaito** [comment]
As a general route, given the scope difference between the client and the worker, it may be a good idea to consider a different API to control worker events/requests other than `.route()`. 

```js
page.serviceWorker.route('/user')
```

There may be cases when the same resource is fetched on the client and on the worker, and you may want to control those cases differently.

**Comment by rwoll** [comment]
@kettanaito Thanks for the proposal! I think it's important to separate the discussion into at least two components:

1. Network Mocking
2. Testing/Interacting with Service Workers themselves

Each can be solved different ways, and patching the browsers themselves is in scope (as needed). As part of https://github.com/microsoft/playwright/pull/14716 —which allows you to intercept all requests (including the main SW script as well as requests being made inside the SW) via Playwright's native `{context,page}.route(…)` interception/mocking, there's ~6 patches to CR upstream so far that builds on existing upstream work.[^1]

Proxying the SW is a neat idea worth exploring—but hitting limitations and interfering with user code as you've alluded to worries me. In general, we prefer native instrumentation, because it does not interfere with user code and brings us more capabilities.

If folks are looking for more ways to test Service Workers themselves, that has yet to be explored as I've mainly focused on their networking components, but PW APIs that give you visibility and hooks into the SW lifecycle/versions etc. will likely show up at some point, but let's have that discussion in a distinct issue to keep this focused on solving the issue of mocking network requests.

[^1]: As a work around today—until the patch lands—you can block SWs so all the requests show up in the native PW `{context,page}.route`.

**Comment by kettanaito** [comment]
> In general, we prefer native instrumentation, because it does not interfere with user code and brings us more capabilities.

I totally understand and share this direction. 

> but PW APIs that give you visibility and hooks into the SW lifecycle/versions etc. will likely show up at some point

Really looking forward to this! I know it'd help me test some of my worker logic.

**Comment by rwoll** [comment]
#14716 landed which means—on Chromium-only for now—network requests made within Service Workers to external resources (and the initial Service Worker main script request), are now instrumented and visible via `context.route(…)` and `context.on('request', …)`.

More exhaustive docs are still in the works, but for folks who want to try it out, you can try ToT `npm i @playwright/test@next` (or `npm i playwright@next` if you are using PW as a lib) and skim through the test(s) for examples of usage: 

https://github.com/microsoft/playwright/blob/71dcad3b2e03231a4f88d58e397e69417254888a/tests/library/chromium/chromium.spec.ts#L214

https://github.com/microsoft/playwright/blob/71dcad3b2e03231a4f88d58e397e69417254888a/tests/library/chromium/chromium.spec.ts#L42

https://github.com/microsoft/playwright/blob/71dcad3b2e03231a4f88d58e397e69417254888a/tests/library/chromium/chromium.spec.ts#L83

…and more in that file :) 

If you have questions—or bugs 🐛 —feel free to file a new issue under the question type and refer to this issue #1090. Please include your use case when filing so we can understand it in context.

**Comment by rwoll** [comment]
Playwright v1.24.0 was released this week. As part of the new release, we've updated the Playwright Network guide: https://playwright.dev/docs/network#missing-network-events-and-service-workers pertaining to this issue.

Please check it out and let us know if you have any questions or if your use case is not addressed by commenting on https://github.com/microsoft/playwright/issues/15684, or filing a **new** issue with a description of your use case.

Thanks!
