### ISSUE TITLE
[Feature] Add test.todo()

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#10918]
### Discussed in https://github.com/microsoft/playwright/discussions/10914

<div type='discussions-op-text'>

<sup>Originally posted by **zomars** December 14, 2021</sup>
This is pretty helpful for planning future tests and keep track of them.</div>

Jest has it: https://jestjs.io/docs/api#testtodoname

**Comment by pavelfeldman** [comment]
We call it test.fixme!

**Comment by zomars** [comment]
> We call it test.fixme!

I think they should be semantically different IMO.

**Comment by unlikelyzero** [comment]
I had a definite need for this when migrating a 5 year old angular app from nightwatch.js to Cypress.io. We almost went with jest-puppeteer over Cypress at the time.

We needed to keep track of all of the tests _which would exist if the app functionality existed_ separate from the tests which were broken.

Today, this would drastically improve our ability to manage test stubs for a 5 year old angular app _which has just completed it's move to vue2_. 

https://github.com/nasa/openmct/discussions/4303

**Comment by orenmizr** [comment]
i really hoped this would be available in 2022. for semantics  👀
fixme says it's broken, we know, no time at this moment to fix the broken test. 
todo says, there is nothing here yet. but we do need this test in the near future.

**Comment by pavelfeldman** [comment]
If you are looking for the parity with Jest, please use `test.fixme` and think of it as of `test.todo`. It has exact same semantics, but is slightly more flexible in that it allows putting some draft code into the test.

**Comment by zomars** [comment]
How does it has the same semantics? It clearly doesn't. Just declare that is out of scope and be done with it. But don't ignore the rain this issue got made in the first place.

**Comment by orenmizr** [comment]
true. i can understand if it is a very low priority. but it is not the same semantics. it is like saying that skip and fixme can by used for "skipping" broken tests.

**Comment by beorn** [comment]
It would be nice if test.fixme didn't require you to put code in, though.  I find it very useful to initially outline a bunch of tests, and it's annoying to have to provide a callback function.

Also, I agree that .todo() has a different semantic than .fixme(), so when it comes to tests-as-documentation/specification it would still be preferable to have .todo().

**Comment by markalanevans** [comment]
@pavelfeldman Any way we could reconsider this.

Often times we we want a way to track the work that needs to be done. And sometimes it's so much easier to have playwright be the source of truth.

For example:


test.describe.serial("Athlete Invites User To Join", () => {
  test.fixme("TODO: ", async ({ page }) => {
    test.info().annotations.push({ type: "manual" });
    test.info().annotations.push({
      type: "step",
      description: `Login as Athlete`,
    });
    test.info().annotations.push({
      type: "step",
      description: `Invite Coach to Join`,
    });
    test.info().annotations.push({
      type: "step",
      description: `Coach Receives Email and Joins`,
    });
  });
});

My wishlist:
* I really wish we could mark the test as todo. 
* We can easily see the steps as we can see them as we are planning. Either via test.step descriptions or annotations.
* We can see the annotations or steps nicely in the ui mode and in the run tests so that QA and Engineering can think communicate what needs to be done.

I'm thinking about using annotations or attachements since those at least can be seen in the UI mode... but it's so close to being a great TODO tool.
