### ISSUE TITLE
[Feature] Add byRole selector

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#11182]
Extracted from https://github.com/microsoft/playwright/issues/11145

https://testing-library.com/docs/queries/byrole/

**Comment by sebinsua** [comment]
[This comment describing the implementation](https://github.com/microsoft/playwright/issues/11145#issuecomment-1007647083) might be helpful:

> `ByRole` follows ARIA and related specifications e.g. the `name` option in `ByRole(role, { name })` implements [ACCNAME](https://www.w3.org/TR/accname-1.1/).
> 
> `role` is tied to [HTML-ARIA](https://www.w3.org/TR/html-aria/).
> 
> The [documentation for `ByRole`](https://testing-library.com/docs/queries/byrole/) goes into more detail.

**Comment by kevin940726** [comment]
Just found this, and I want to shamelessly plug my experimental library [`role-selector`](https://github.com/kevin940726/role-selector) here. Instead of using `@testing-library/dom` as the underlying engine, it uses [`axe-core`](https://github.com/dequelabs/axe-core) to compute the accessible roles and attributes. An example selector will look like following:

```js
page.locator('role=button[name="My button"]');
```

Although the library will technically work in puppeteer or even jsdom, it's designed with playwright in mind, thus intentionally not implementing duplicated features like `byText` or `visible`.

The selector syntax is similar to puppeteer's [aria selector](https://developer.chrome.com/blog/puppetaria/), but prioritizing `role` more than `name` to follow the philosophy of `@testing-library/*`'s `byRole`.

The library is still under development, but I plan to experiment with it in [gutenberg](https://github.com/WordPress/gutenberg)'s e2e test suites when we migrate to playwright (soon).

**Comment by kevin940726** [comment]
Just want to update that we're now using the official built-in role selectors in Playwright and it works perfectly fine [migrating](https://github.com/WordPress/gutenberg/pull/41389) from the `role-selector` package!

**Comment by mxschmitt** [comment]
Closing as per above, seems to be working as it is for a large customer.
