### ISSUE TITLE
[BUG] page.route returns partial responses when using Electron's onBeforeRequest

### ISSUE THREAD

**Issue by mkarp** [microsoft/playwright#11246]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Mac
- Node.js version: 16.13.0
- Browser: Electron 16.0.6

Hey there! I realize that Electron support is still experimental, but you might find this bug report helpful nevertheless.

I've created a small repo to reproduce the case https://github.com/mkarp/playwright-electron-route-issue.

It seems like if `electron.session.defaultSession.webRequest.onBeforeRequest()` is used for any URLs, mocked HTTP responses using Playwright's `page.route()` have status `0` for every URL. It's expected that status should be `200` or as specified with `page.route({ status: 123 })`.

Because this test case requires some setup to reproduce, please have a look at the reproduction repo I've mentioned before. There are some instructions how to run it.

Thank you for looking into it!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
