### ISSUE TITLE
[BUG] Inspector filling up with continue messages

### ISSUE THREAD

**Issue by sebinsua** [microsoft/playwright#11248]
**Describe the bug**

Similar to #10098, I'm seeing 100s of 'continue' messages posted in the Inspector, so I'm unable to debug anything else. This stops if I remove the single `page.route(url, ...)` that I have in my code.

![continue](https://user-images.githubusercontent.com/152098/148579650-b8f97334-ecc8-414d-8eee-436cb90011ab.png)

**Context:**

- Playwright Version: 1.17.1
- Operating System: Linux
- Node.js version: 12.14.1
- Browser: Chrome

**Code Snippet**

```javascript
test.beforeEach(async ({ page }) => {
  await page.route(someUrl, (route) => {
    logger.info(`Handling request for URL with mock call: ${route.request().url()}`);
    route.fulfill({
     status: 200,
     body: JSON.stringify({ /* some body goes here */ })
  });
});
```

**Comment by ecchochan** [comment]
@sebinsua 
Have you found a workaround or fix for this?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
