### ISSUE TITLE
[Feature] Add .launchPersistentContext(userDataDir[, options]) for electron

### ISSUE THREAD

**Issue by vyhv00** [microsoft/playwright#11240]
Hi, it would be nice to have the possibility set user data folder to a specific one, for example to some temp file because of not affecting tests by each other. For browsers there is `browserType.launchPersistentContext(userDataDir[, options])` which can set particular userDataDir or temporary directory instead. But electron has just a simple `electron.launch([options])​` through that you cannot even pass `user-data-dir` chromium argument.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
