### ISSUE TITLE
[Question] How to update firefox default prefs

### ISSUE THREAD

**Issue by star-kashyap** [microsoft/playwright#1124]
@arjun27 Can you please help unblocking us regarding below issue.
We are testing a streaming application and not able to play some contents (DRM) on firefox because media.gmp-manager.updateEnabled is set false in playwright.cfg file.

// Disable download and usage of OpenH264: and Widevine plugins
pref("media.gmp-manager.updateEnabled", false);

Is there a way to turn this pref true via api ?

**Comment by mxschmitt** [comment]
As a workaround maybe you could use a custom user directory like shown here. There you can have a file with your user preferences: https://github.com/microsoft/playwright/issues/917#issuecomment-584796639

---

Maybe this can be standardised for all the browsers and added natively to the Playwright API, since:
- Firefox has user preferences: `about:config`
- Chromium has flags: `chrome://flags`
- WebKit has experimental features not fully identical but goes into the direction

**Comment by pavelfeldman** [comment]
You can use [firefoxUserPrefs](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-firefoxuserprefs)
