### ISSUE TITLE
[Feature] Support for playing DRM content in bundled chromium.

### ISSUE THREAD

**Issue by star-kashyap** [microsoft/playwright#1125]
<img width="988" alt="Screenshot 2020-02-26 at 8 13 57 PM" src="https://user-images.githubusercontent.com/58773425/75356701-50333400-58d6-11ea-8ba6-fd57591d366d.png">

@arjun27 We are not able to play DRM content with playwright bundled chromium. Most probably its happening as its missing WideVine Content Decryption Module as shown in above screenshot (which I took from installed browser on my mac). Is there any workaround for this ? please help unblocking us ?

**Comment by arjun27** [comment]
Thanks for reporting this, @star-kashyap. As you have figured out, Chromium cannot play DRM content. Since we follow the upstream versions for Chromium, you can use [Chrome Canary](https://www.google.com/chrome/canary/), which will work with DRM.

Note that at this point we can only guarantee that Playwright will work with the browser that is bundled with Playwright. One way to verify whether the browser can work is to compare the version in `chrome://version` against the version in [our package readme](https://www.npmjs.com/package/playwright).
