### ISSUE TITLE
[Feature] Add possibility of creating Locators with variables

### ISSUE THREAD

**Issue by MikeShysh** [microsoft/playwright#11377]
Hi, it would be more convenient to create Locators with the possibility of specifying variable values exactly before executing some actions.
For example I have two elements on the page:
```
await this.page.click('.header-actions [helptag="default-filters"]:not(.mat-button-disabled)');
await this.page.click('.header-actions [helptag="apply-filters"]:not(.mat-button-disabled)');
```
As we can see, only `helptag` differs. 
With the current implementation of Locators I need to create 2 locator elements or make my own functions to generate raw string selector and pass it to locator.
I propose creating out-of-the box implementation in Locators for such functionality.
Maybe something like this:
```
headerActionBtns = this.page.locator('.header-actions [helptag="${btnName}"]:not(.mat-button-disabled)', btnName)
headerActionBtns.click({btnName: 'default-filters'});
or
headerActionBtns.with({btnName: 'default-filters'}).click(); 
```
 Please consider. Thank you

**Comment by dgozman** [comment]
@MikeShysh This proposal does not seem like a clear improvement so far. Perhaps there are more usecases or possible APIs that would work better?

```js
// proposed
headerActionBtns = this.page.locator('.header-actions [helptag="${btnName}"]:not(.mat-button-disabled)', btnName)

// works today - note `...` backticks
headerActionBtns = this.page.locator(`.header-actions [helptag="${btnName}"]:not(.mat-button-disabled)`)
```

**Comment by woytekn** [comment]
+1, adding this feature will be appreciated.

**Comment by andersoncorbellini** [comment]
+1, this feature will be awesome for the community.

**Comment by mahmutkaya** [comment]
+1, looking forward to have this feature :)

**Comment by davidrosevear** [comment]
If I’m understanding the problem/desire correctly, it seems this could actually be handled comparably by making the locator variable a function returning the locator instead. Using the proposal:

```typescript
// proposed
headerActionBtns = this.page.locator('.header-actions [helptag="${btnName}"]:not(.mat-button-disabled)', btnName)
headerActionBtns.click({btnName: 'default-filters'});
or
headerActionBtns.with({btnName: 'default-filters'}).click(); 

// Using a function
headerActionBtns = ({ btnName }) => this.page.locator(`.header-actions [helptag="${btnName}"]:not(.mat-button-disabled)`);
headerActionBtns({btnName: 'default-filters'}).click(); 
```

This takes advantage of native javascript rather than needing to add something to Playwright, and seems to do and feel about the same as proposed.

It could be similarly applied to the last example too, having the helptag value be passed in, and then potentially chaining the input to fill as needed. It seems it uses typescript too, in which case you could even provide options as the type (`‘topup-amount’ | ‘topup-fee’`).

I am also an advocate for simplifying, and believe that should do it as desired. Hope that helps someone, and definitely curious if it doesn’t work for anyone.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
