### ISSUE TITLE
[BUG] Chromium headed raises error on failed basic auth

### ISSUE THREAD

**Issue by dwt** [microsoft/playwright#11436]
**Context:**
- Playwright Version: 1.17.2
- Operating System: Mac
- Python version: 3.9.9
- Browser: Chromium

**Code Snippet**

See attached files. [reduction.zip](https://github.com/microsoft/playwright-python/files/7877329/reduction.zip)

**Describe the bug**

When checking that basic auth is indeed required when visiting a URL chromium behaves different than firefox or webkit and dies with an exception instead of just dismissing the auth dialog.

The way I see it, either the two other browsers should also die, or chromium should also just continue.

**Comment by mxschmitt** [comment]
https://github.com/microsoft/playwright/blob/b6c2b32b530e88bb8b468e84d26929d06a15af5f/tests/browsercontext-credentials.spec.ts#L32 this skip seems related.

Marking is as p3 for now (acknowledged bug inside the Chromium browser where headless and headed implementation is different). As a workaround you can use the headless mode.

**Comment by dwt** [comment]
@mxschmitt I'm not very familiar with your tags, is there any feedback I can provide?

**Comment by mxschmitt** [comment]
P3 means that we wait for more users to run into this issue which helps us to prioritize it.

Nothing needed from your side.

**Comment by Morasiu** [comment]
Same here

**Comment by rejectozaur** [comment]
Same here

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
