### ISSUE TITLE
[Feature] record bandwidth usage

### ISSUE THREAD

**Issue by andrisi** [microsoft/playwright#11438]
I need to measure the bandwidth used by playwright sessions. So I open a page, click here and there, use a web app, and at the end of the session - or perhaps as I go along - I need to know the app's network usage. Through a proxy too. Thanks.

**Comment by mxschmitt** [comment]
There are multiple ways of doing it as of today.

You can use the `request` and `response` events and calculate it yourself, see here: https://playwright.dev/docs/network#network-events

Also Playwright has HAR, which is a standardised format for http traffic, this might help you too (option when creating a context): https://playwright.dev/docs/api/class-browser#browser-new-context-option-record-har

**Comment by mxschmitt** [comment]
Closing since its answered! For further questions please file a new issue.

**Comment by andrisi** [comment]
Thanks!

**Comment by VGBijpuria** [comment]
@mxschmitt but that doesn't measure bandwidth when one for instance uses [`page.evaluate()`](https://playwright.dev/docs/evaluating) to use the browser's fetch API for grabbing content. To illustrate-
```python
async def fetch_html(page: Page, url: str) -> str:
    return await page.evaluate(
        """
        async (targetUrl) => {
            const res = await fetch(targetUrl, {
                method: "GET",
                credentials: "include"
            });
            if (!res.ok) throw new Error("HTTP " + res.status);
            return await res.text();
        }
        """,
        url,
    )
```
This issue has been discussed multiple times in multiple places for years. Can Playwright please make this an issue?

**Comment by andrisi** [comment]
Perhaps the recently added Chrome for Testing could add this feature?

**Comment by VGBijpuria** [comment]
@andrisi We unfortunately have to use Firefox-

- Chrome is bundled with certain features that Chromium does not have. Anti-bot providers can detect if you are using Chromium rather than Chrome. Since Chrome is closed source, patching Chrome is significantly more difficult.
- CDP is more widely used and known, so it's a more common target for bot detection
- Juggler operates on a lower level than CDP, making it less prone to JS leaks.
- Firefox is more ideal for fingerprint rotation. More research has been made on Firefox for fingerprinting resistance than on Chromium.
