### ISSUE TITLE
[BUG]: grant camera permissions not working in v1.17.1

### ISSUE THREAD

**Issue by Sushma-TSC** [microsoft/playwright#11441]
**Context:**
- GOOD Playwright Version:  "playwright/test": "1.17.0", "playwright": "1.17.0"
- BAD Playwright Version:  "playwright/test": "1.17.1", "playwright": "1.17.1"
- Operating System: Mac M1

**Code Snippet**

```javascript
test.beforeAll(async({ browser }) => {
        async function cursor(p) {
            await p.addInitScript(function() {
                navigator.mediaDevices.enumerateDevices = () => Promise.resolve([{ deviceId: 'blah', groupId: 'foo', kind: 'videoinput', label: '' }]);
                window.addEventListener('DOMContentLoaded', injectVideo);
            });
            return p;
        }
const context = await browser.newContext();
        await context.grantPermissions(['camera']);
        page = await context.newPage().then(cursor);

        await page.goto(baseUrl);
    });
```

**Describe the bug**
This was working fine for a good time and then it just stopped working without making any changes to the test itself. 
Here is the screenshot 

![image](https://user-images.githubusercontent.com/85895355/149825689-6f283cdb-ec18-4f8f-80ac-f04c0b2b86d6.png)

**Comment by mxschmitt** [comment]
If you did not change the Playwright version, this then can't be a Playwright issue. More likely that your application has changed something in their logic.

Normally we ask for a small repro, but since it stopped working at some point of time, and you don't have a working example at all, we can't act on this. Please file a new issue with a good / bad version or a small repro.

**Comment by Sushma-TSC** [comment]
Hello I have rechecked the version we were using - updated it in the notes of good and bad versions. Let me know Id new issue to be created or this can be reopened.

**Comment by Sushma-TSC** [comment]
> We need a small repro in form of a GitHub repository to demonstrate that the behaviour has changed. Between 1.17.0 and 1.17.1 there were no related changes, see here: [v1.17.0...v1.17.1](https://github.com/microsoft/playwright/compare/v1.17.0...v1.17.1)

Here is the repro that you have asked for in a repo - I replicated it in a publicly available website to make it easy https://github.com/Sushma-TSC/CameraTest .
Let me know if this will be sufficient or anything else is needed

**Comment by mxschmitt** [comment]
It's more likely that MacOS is preventing you from giving access to Chromium rather than Playwright allows the camera.

Did you see a macOS popup for the permissions, something like that?

![image](https://user-images.githubusercontent.com/17984549/150354832-af7cd6f4-3892-4635-95e9-9277dd111a61.png)

You can configure them in your system settings under Security & Privacy -> Privacy -> Camera.

It also makes sense to instead set the permissions inside you config if you have one, there under the "use section" you can put `permissions: ['camera']`
