### ISSUE TITLE
[Question] How to create a shared variable between all tests

### ISSUE THREAD

**Issue by anastasiyamazheika** [microsoft/playwright#11517]
Dear Playwright Team, 
I want to create a shared variable that can be used, edited, and accessible in all tests.

I used the fixture solution from this [page](https://playwright.dev/docs/test-fixtures#test-fixtures) and was able to get my initially empty list of strings in every test, let's call it `namesList`. 

```
test("First test", async ({ namesList, page }) => {
    namesList.push("hello");
  });

test("Second test", async ({ namesList, page }) => {
    namesList.push("world");
  });
```
Every test adds a new value to this `namesList` and I expect to have this variable full with all values added in the end of the test run, in this case `["hello", "world"]`. But unfortunately, it looks like this field isn't shared between all tests and gets created every time.

Am I doing something wrong or there's another solution how to create this variable that can be used and updated by every test of every test spec? 
I run my tests in parallel.

**Comment by mxschmitt** [comment]
If you want to have something shared across all the tests, this means that you need to limit the amount of workers to 1 and can't run them by that in parallel. Since each worker is its own operating system process. Also after every failing test a worker get's restarted and it looses its state. See [here](https://playwright.dev/docs/test-parallel#worker-processes) for reference.

In your example you are using test fixtures, they get re-created for every test, you want actually a worker fixture which are per worker. See [here](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures) for their syntax which is pretty similar.

For what are you using your variable? This might help to find the optimal solution for your problem.

**Comment by anastasiyamazheika** [comment]
Hello @mxschmitt,
Thanks for your answer. I want to use unique names of entities in all tests. I plan to add the generated name to the shared list of strings between all tests. When the new name is generated, I want to make sure that it was not used already in other tests.

I was able to do such things in pytest and NUnit previously. Does any solution come to your mind? 

Thanks!

**Comment by mxschmitt** [comment]
Playwright Test does ensure that a test-name per file is unique. Sounds like in your scenario it would make more sense to post-process them, with either the JSON reporter and read/process it afterwards or create a custom reporter which ensures unique test tiles per whole project.

Doing this inside a worker itself comes with a lot of drawbacks as mentioned with sharing the variable across workers since a worker also restarts once a test was failing see here: https://playwright.dev/docs/test-parallel#worker-processes

**Comment by anastasiyamazheika** [comment]
Thanks for the answer @mxschmitt!
