### ISSUE TITLE
[BUG] console.logs from page never shown

### ISSUE THREAD

**Issue by trusktr** [microsoft/playwright#11574]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.8
- Operating System: [e.g. Windows, Linux or Mac] Linux
- Node.js version: [e.g. 12.22, 14.6] 17
- Browser: [e.g. All, Chromium, Firefox, WebKit] All
- Extra: [any specific details about your environment] playwright docker image

**Code Snippet**

```js
  page.on('console', msg => console.log('LOG FROM INSIDE PAGE: ', msg));
```

**Describe the bug**

No matter where I put this, console.logs from the page never show in terminal.

**Reproduction**

none yet

**Comment by trusktr** [comment]
I misread my output. I see one test does not output anything, while another does. The tests look like this (using jest-playwright, which I hope doesn't have to do with it):

```js
// index-file.test.js

  test('should serve from index file', async () => {
    console.log(' ################## index-file test 1');
    await docsifyInit(sharedOptions);
    await expect(page).toHaveText( '#main', 'A magical documentation site generator');
    expect(page.url()).toMatch(/index\.html#\/$/);
  });

  test('should use index file links in sidebar from index file hosting', async () => {
    console.log(' ################## index-file test 2');
    const onceRendered = await docsifyInit(sharedOptions);
    await page.click('a[href="#/quickstart"]');
    await onceRendered();
    await expect(page).toHaveText('#main', 'Quick start');
    expect(page.url()).toMatch(/index\.html#\/quickstart$/);
  });
```

Both tests load the same index HTML file, with console.log statements in them. However, the output shows logs only from one test:

```
 FAIL   browser: firefox e2e  test/e2e/index-file.test.js (39.202 s)
  ● Console

    console.log
       ################## index-file test 1

      at Object.<anonymous> (test/e2e/index-file.test.js:12:13)

    console.log
       ################## index-file test 2

      at Object.<anonymous> (test/e2e/index-file.test.js:26:13)

    console.log
      LOG FROM INSIDE PAGE:  increment body renderCount

      at Page.<anonymous> (test/helpers/docsify-init.js:411:37)
```

Is there something that can prevent logs from reaching playwright? The failed test times out on a `waitForSelector`

**Comment by trusktr** [comment]
Hmmm, placement of the `page.on('console` matters. If I instead place those in the individual tests, rather than in a shared setup script, I see logs.

It isn't clear _where_ this event handler is supposed to be specified for it to work.

**Comment by mxschmitt** [comment]
`page.on('console', msg => console.log('LOG FROM INSIDE PAGE: ', msg));` this needs to be before the page emits console events (e.g. beforeEach or at the beginning of the page). I'd recommend to upgrade to the latest Playwright version, since 1.8 is very old. Also keep in mind that it only sets it for the page instance and not for further pages which get created.

Last but not least, not sure about how jest-playwright is working, we'd strongly recommend migrating to the official one, since it gives better reporting for timeouts, artifact handling (tracing, video, screenshot), web-first assertions, parallelism etc.

Let me know if this helps, as I said in the other issue, without a repro we can mostly give advise or assumptions rather than seeing the actual reason by digging into a repro.

**Comment by aslushnikov** [comment]
Thanks Max for the answer!

@trusktr I'll close this for now. Please, feel free to re-file with a good repro so that we can debug and be helpful!

**Comment by galhe2** [comment]
it doesn't seem to work for regular logs emitted by the browser. Such as console.log("hello world!") won't be displayed via page.on('console
