### ISSUE TITLE
[Feature] Step-scoped attachments

### ISSUE THREAD

**Issue by aposiker** [microsoft/playwright#11592]
In my current project, we starting the migration to Playwright (with playwright-test runner).
I've managed to build a decorator function that marks all methods of my Page Object as a test step, but it would be nice if I could add arguments that were passed to the corresponding method as attachments to the step in the report(ideally if it will be also displayed same way in allure HTML report).

**Comment by aslushnikov** [comment]
@aposiker Do I understand correctly that you'd like to have attachments to steps rather than test?

**Comment by aposiker** [comment]
@aslushnikov yes, that is correct

**Comment by baev** [comment]
BTW this one is the part of https://github.com/microsoft/playwright/issues/14364

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
