### ISSUE TITLE
[Feature] support xpath 2/3

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#11671]
may be able to leverage [this xpath 2 implementation](https://github.com/ilinsky/xpath2.js)

**Comment by aslushnikov** [comment]
For now, you can already create a [custom selector engine](https://playwright.dev/docs/extensibility#custom-selector-engines) that uses xpath2.

**Comment by kevin-brotcke** [comment]
Ran into Playwright throwing errors for valid xpath queries and realized it was this. It would be nice to be able to use `ends-width` and `matches`. For example:

```
//*[ends-with(@aria-label, 'the end')]
//*[matches(@aria-label,".*my regex$")]
```

**Comment by DetachHead** [comment]
i've made a custom selector engine using xpath2.js - https://www.npmjs.com/package/playwright-xpath

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
