### ISSUE TITLE
[Question] How does page.type work

### ISSUE THREAD

**Issue by Fyre91** [microsoft/playwright#11691]
I have a page on which on every keystroke a big script runs due to which the next page.type timeouts.  Is there a way I can avoid this other than increasing the timeout(seems unreliable depending on the length of script)

**Comment by timdeschryver** [comment]
Have you tried using `fill` instead?
https://playwright.dev/docs/api/class-elementhandle#element-handle-fill

**Comment by Fyre91** [comment]
Yeah I have tried fill for other usecases but I need page.type for the usecase I am testing.

**Comment by aslushnikov** [comment]
> I have a page on which on every keystroke a big script runs due to which the next page.type timeouts. 

@Fyre91 `page.type` types exactly the same way a user would. So if typing is unbearably slow, then it would be so for real users. Looks like a serious website issue; this can be fixed by fixing website.

> Is there a way I can avoid this other than increasing the timeout(seems unreliable depending on the length of script)

The only way to avoid this behavior would be to not type - which `page.fill` does. You did mention that you absolutely need `page.type`, so I'd fix website then.

**Comment by Fyre91** [comment]
Got it, thanks. Actually I want the website to be super slow for this usecase(odd I knw).  But thanks for responding. I will close this.
