### ISSUE TITLE
[Feature] page.click() scroll to be optional

### ISSUE THREAD

**Issue by godjira-homless** [microsoft/playwright#11716]
I have several problems in jqxgrid with page.click(). Click 2 rows upper than the element located (hover too), etc (jqx bug). I think the problem cause the Scroll the element into view if needed in click().
It could be nice to if scroll would be optional.
workaround: mouse.click() to bounding box, but I'd rather use the page.click()
thx

**Comment by aslushnikov** [comment]
> It could be nice to if scroll would be optional.

@godjira-homless If the element is outside of the viewport, than we can't click it with mouse; same way as users won't be able to.
You can try using [`locator.dispatchEvent`](https://playwright.dev/docs/api/class-locator#locator-dispatch-event):

```js
await page.locator('button').dispatchEvent('click');
```

**Comment by yury-s** [comment]
There is no way to disable scroll step as a human would also have to scroll the element into view to be able to click it. It might be that there is a bug in the app and how it reacts to scrolling. It may be that the element is not yet stable when playwright is clicking it, there were some fixes in 1.18 related to that. What version are you using? If you are not on 1.18 can you please try it and see if the problem persists?

If the problem is still there can you share a trace with us?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by MaruschkaScheepersW** [comment]
Same issue here. 

We have these comboboxes with multiple options. When they are opened we are presented with a listbox. For some reason playwright woulfd autoscroll the options into view when they are clearly visible. The dropdowns are designed to disappear when the user scrolls, so this causes plaky behaviour in test.
