### ISSUE TITLE
[Feature] Extended "mediaEmulation" API

### ISSUE THREAD

**Issue by Westbrook** [microsoft/playwright#11781]
For users looking to test code that might employ something like `matchMedia('(hover: none) and (pointer: coarse)').matches`, it would be awesome to be able to apply this context at testing time. We're currently able to test usage like `matchMedia('(max-width: 800px)').matches` via the `page.setViewportSize(viewportSize)` or `matchMedia('print').matches` via `page.emulateMedia({media: 'print')`, and I wonder if we could expand on `emulateMedia`, `setViewportSize`, and/or a new API to surface these extended realities.

It's possible that there is a combination of tangentially related settings that might similarly active this situation, in which case this _may_ just be a documentation request, however the ability to make these changes during runtime, as is available with the other APIs I have listed would be very valuable for easy testing of these sorts of features.

I'm sure that anyone who is working to test the responsivity of their code across the growing number of contexts in which a web application can be delivered would benefit from being able to leverage such an addition.

**Comment by yury-s** [comment]
Do you have a use case where you miss particular features you lack emulation for? Asking as [the list](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#syntax) is quite long and since we haven't had much requests for them we'd like to better understand the scearious.

**Comment by Westbrook** [comment]
Would be fun if there was a sort of `mediaEmulation(mediaQueryString)` API that was reciprocal to https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia...but I understand the list is long. At the current moment, I'm looking at the `hover` and `pointer` media features to help discern between "desktop web" and "mobile web", so: https://css-tricks.com/a-complete-guide-to-css-media-queries/#aa-interaction

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by Rajdeepc** [comment]
Hi @pavelfeldman Can this issue be reopened. Our team is not able to turnaround any mobile device specfic tests with touch events due to this! We are only able to create some snapshots with the viewPort api for now! This would add more control over our testing ecosystem and expand our tests boundary.
If this cannot be opened I am happy to create another one! Please let me know
