### ISSUE TITLE
[Bug]  'Timeout of 30000ms exceeded while shutting down environment' errors

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#11805]
We get them on the CI quite often since a few months.

**Comment by marckubischta** [comment]
I'm seeing these intermittently as well and I'm not sure what causes them. When this occurs, I get an extra artifact folder `./.playwright-artifacts-1` containing 1) a zero byte {hash}.webm file and another {hash}.webm file of length 0 seconds and approximately 1k in size. What other information would be useful to help debug this?

**Comment by SanRak987** [comment]
"@playwright/test": "^1.21.1", I am noticing this issue quite frequently now. This happens if page takes more than 4 seconds to load.
Handling it with other wait conditions.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
