### ISSUE TITLE
[BUG] hide waiting for selector, selector resolved to ... in page assertions

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#11867]
```
await expect(page).toHaveURL()
await expect(page).toHaveTitle()
```
they contain inside the expect logs useless information about root selectors which are confusing. We should hide or not send it over the wire.

**Comment by elaichenkov** [comment]
Why did you close it?
The log is really useless and confusing for the page's assertions.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/29764053/164973315-aa20c2e0-8cea-4054-bddd-29d8a9d96bcd.png">

**Comment by skysantoroa** [comment]
Having the same issue, do you have any update on this?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
