### ISSUE TITLE
[Feature] Support for React hybrid app automation in mobile

### ISSUE THREAD

**Issue by ShanmukhaGajula** [microsoft/playwright#11982]
We have a use case where we need to test the hybrid app in an Electron container on a desktop as well as in a hybrid mobile app. 
And I think most of the modern applications use hybrid model.  So that it can help others too.. #11963

**Comment by kvsrk432** [comment]
i am also looking for it..

**Comment by siddharththakurji** [comment]
In my project, i m working on hybrid app, It would be great if playwright supports it, so that i can make use of it.

**Comment by abhirammocharla** [comment]
BDD is always good to have

**Comment by abhirammocharla** [comment]
Yes this would be helpful...

**Comment by Akhila4062** [comment]
Iam looking for this support too!

**Comment by agarwalu** [comment]
i have same scenario to automate hybrid app in IOS

**Comment by IsabelFrancis** [comment]
Looking forward  to the much needed support for  hybrid app automation being pursued in our Team. Would appreciate the support.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
