### ISSUE TITLE
[Feature] Allow changing tracking settings is Safari

### ISSUE THREAD

**Issue by damevi** [microsoft/playwright#12026]
Hello, I would like to ask how can I disable website tracking in Webkit when running tests with Playwright?
I am talking about this setting specifically: 
<img width="696" alt="image" src="https://user-images.githubusercontent.com/73101548/153589181-1012e225-4e75-4c32-a696-7d392d71743e.png">

This is currently preventing me from the execution of my mobile tests because Safari blocks some of the cookies settings when running frontend on local while connecting to external server's API.

Kind regards,
Damevi

**Comment by pavelfeldman** [comment]
No such way, I'll turn this into the bug to collect the feedback.

**Comment by montebrown** [comment]
+1 this also blocks my test suite from running on webkit for reasons similar to @damevi's. Any update or workaround would be appreciated.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
