### ISSUE TITLE
[Feature] configure video quality

### ISSUE THREAD

**Issue by kgeis** [microsoft/playwright#12056]
I am trying to use Playwright to create production quality training screencasts. The video output is currently not very good. I think I could get really good output if:

- Screenshots are piped to FFmpeg as PNGs.
- I can control which encoder FFmpeg uses. I would prefer VP9.
- I can control the encoding bit rate. I would set it to at least 2MBit/s.

In addition, it would be great if instead of single-threading, encoding could default to `CPU count - 1`.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by byteofmydream** [comment]
Please reopen, default ffmpeg configuration in playwright is not optimal and should be configurable

**Comment by MuTsunTsai** [comment]
Hi @kgeis, @byteofmydream — sharing [`playwright-recorder-plus`](https://github.com/MuTsunTsai/playwright-recorder-plus), which covers exactly what was asked here: PNG-equivalent input quality (mjpeg `-q:v 1` is what the upstream code already uses), arbitrary encoder including VP9, and any bitrate / CRF target.

Built on Playwright 1.59+'s public `page.screencast` API rather than patching `recordVideo`, so it works with any package manager and stays compatible with Playwright updates. Not a Playwright maintainer; posting in case it helps with production-quality screencast workflows.
