### ISSUE TITLE
[QUESTION] ```subtree intercepts pointer events``` causes  Locator.hover failes  

### ISSUE THREAD

**Issue by zyscoder** [microsoft/playwright#12076]
**Context:**
- Playwright Version: latest
- Operating System: Linux
- Node.js Version: v14.15.1
- Browser: Chromium

**Code Snippet**

```javascript
const { chromium } = require('playwright');

(async() => {
    const browser = await chromium.launch({
        headless: false,
    });
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto("https://www.liaoxuefeng.com/wiki/1022910821149312/1023025597810528");
    const rows = page.locator('.x-wiki-index-item');
    const count = await rows.count();
    // console.log(count);
    console.log(await rows.nth(0).boundingBox());
    console.log(await rows.nth(0).textContent());
    rows.nth(0).hover({position: {x: 0, y: 100}});
})();

```

**Describe the question**
When running the code above, the following exception would be thrown:
```
waiting for selector ".x-wiki-index-item >> nth=0"
  selector resolved to visible <a class="x-wiki-index-item" href="/wiki/1022910821…>JavaScript教程</a>
attempting hover action
  waiting for element to be visible and stable
  element is visible and stable
  scrolling into view if needed
  done scrolling
  performing hover action
  <div depth="0" expand="true" id="1022910821149312">…</div> intercepts pointer events
retrying hover action, attempt #1
...
```
Why was the exception thrown?

**Comment by dgozman** [comment]
This is because the `rows.nth(0)` is `300x30` pixels in size, and you try to hover at `y:100` position. This position is outside of the row and Playwright complains that it cannot hover the row at this position.

If you indeed want to hover something else at `y:100` relative to this row, pass [`force:true` option](https://playwright.dev/docs/api/class-locator#locator-click-option-force) to skip this check.

Let me know whether this helps.
