### ISSUE TITLE
[BUG] require(...).addListFilesCommand error on 1.19.0

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#12081]
**Context:**
- Playwright Version: 1.19.0
- Operating System: Linux and official focal image
- Node.js version: 12,14, focal image
- Browser: Chromium
- Extra: Using ...devices syntax from official documentation

## System:
 - OS: macOS 11.6.3
 - Memory: 1.78 GB / 16.00 GB
## Binaries:
 - Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
 - npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.19.0 => 1.19.0

**Code Snippet**

Config https://github.com/nasa/openmct/blob/play/e2e/playwright-ci.config.js

Error: https://github.com/nasa/openmct/runs/5186998718?check_suite_focus=true

**Describe the bug**

Looks like the `...` syntax is not working as of 1.19.0. I saw that there were breaking changes to global playwright test configs but no other info specific to this change.

**Comment by dgozman** [comment]
@unlikelyzero Looking at your `package.json`, you have both `playwright` and `@playwright/test` as dependencies. We suggest to only leave `@playwright/test`, because it includes everything that `playwright` has.

Also, looking at [this PR](https://github.com/nasa/openmct/pull/4856), it only bumps one of the two, and that's where the discrepancy comes from. We should probably improve the docs - any PRs are welcome as well 😄 

Let me know if removing `playwright` does the trick for you.

**Comment by unlikelyzero** [comment]
@dgozman that was it! I really appreciate the feedback on this one. I can't think of the appropriate way of documenting this, but when I do, I will be sure to make a PR :)
