### ISSUE TITLE
[Question] what is the solution for the error 'decorators-legacy' isn't currently enabled. while using services which has Injectable.

### ISSUE THREAD

**Issue by chaitraAshu** [microsoft/playwright#12105]
Hello,

I can't use Playwright in an Angular project (with a classic official Angular CLI configuration), because of legacy decorators:
SyntaxError: /path/to/src/app/some.service.ts: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (4:1):

In the below comment they have suggested a solution for adjusting imports to use exact relative paths. have tried this but getting the same Syntax error.

https://github.com/microsoft/playwright/issues/7121#issuecomment-895496243

Currently I'm stuck with this Syntax error, unable to use services in e2e testing.

**Comment by pavelfeldman** [comment]
@baparham I don't think it'll make its way into 1.21. Could you share more about your source code structure? Are you importing your source code TS files from your test files?

**Comment by pavelfeldman** [comment]
I don't think we are going to support legacy decorators in Playwright. Leaving it open to collect the feedback.

**Comment by baparham** [comment]
@pavelfeldman I think I actually don't need it, now that I debug my issue more. The decorator was used in another unrelated portion of our codebase and it was getting pulled in by an import chain with some not-so-clean separation of concern. I've fixed and no longer require the use of decorators in my playwright code. Thanks for the update about the plans and the willingness to hear out any potential use cases, I appreciate that!

**Comment by pavelfeldman** [comment]
Awesome, thanks for the update, closing!

**Comment by amir-arad** [comment]
I've encountered this issue when upgrading @playwright/test from 1.20.1 to 1.21.1 . part of the test fixture uses typescript decorators which worked fine for me so far.

Is there another runner that supports decorators?

**Comment by fildasabo** [comment]
I need to use enum that is located with angular component in the same file. 

I have same problem: 

> _Support for the experimental syntax 'decorators-legacy' isn't currently enabled (17:1):      
> @Component({_

Do you know any fixes?

I don't want to move my enum to another file.

**Comment by prewk** [comment]
Feedback: It's a built-in pattern in the very common [nx + Angular](https://nx.dev/) combo to create sub-libs that do barrel exports.

These barrel files may include both Angular code (for instance an Angular module) and more general code that you may want to utilize in other places (such as Playwright).

Since Playwright has problems understanding the typescript environment it is in (TS aliases, more specifically), I wrote something that creates symlinks to the TS-aliased libs in `node_modules/`. Problem solved! Or so I thought..

Now I can't use the barrel files because Playwright crashes as soon at it sees an annotation, which I seriously doubt will ever be deprecated considering how important it is to Angular. It's used in every Angular-specific file, basically. Modules, directives, services, components...

**Comment by westhechiang** [comment]
>Now I can't use the barrel files because Playwright crashes as soon at it sees an annotation

Currently trying to figure out a workaround for this very problem. Seeking suggestions

**Comment by prewk** [comment]
@westhechiang FWIW I tried to constrain myself to only needing specific things from specific libs (which are aliased). After that I just created an extra barrel file where needed called `e2e-exports.ts` and added a new TS alias for it.

For instance, one lib called `@shared/util/url` exported too much via its `index.ts` barrel, so I created that new barrel and aliases it `@shared/util/url/e2e`.

It requires that the things that are exported don't cause any transient dependencies which use other problematic barrel files. And the pattern is a bit stinky because I'm modifying my app code to appease test tools. But that's my solution 😅

**Comment by prewk** [comment]
@westhechiang FWIW I tried to constrain myself to only needing specific things from specific libs (which are aliased). After that I just created an extra barrel file where needed called `e2e-exports.ts` and added a new TS alias for it.

For instance, one lib called `@shared/util/url` exported too much via its `index.ts` barrel, so I created that new barrel and aliases it `@shared/util/url/e2e`.

It requires that the things that are exported don't cause any transient dependencies which use other problematic barrel files. And the pattern is a bit stinky because I'm modifying my app code to appease test tools. But that's my solution 😅

**Comment by prewk** [comment]
God, the hoops we have to jump through for this at the moment... What would be the downside of enabling it? Decorators is fundamental to Angular and won't go anywhere.

I have to basically split up our code base into multiple dependency trees that can't touch each other to make TS useful in Playwright, because otherwise I can't import anything. And even then it often won't work, because the "test tree" need special rules that it can never use any decorators (which are super common in Angular) due to Playwright, contaminating so much code.

**Comment by FrancoisCamus** [comment]
Hi! I get a similar error when executing tests with playwright 'Support for the experimental syntax 'decorators' isn't currently enabled'. I'm generating a client api for my angular application with open api (nswag). It contains @Injector() decorator so it can easily be injected into my angular application. I tried several things and read all the other related closed issues without success.
I've been using Cypress for years and would like to switch to playwright for all my tests cases because I love it.
Most of my tests are executed by mocking the backend calls. It works great in Playwright until you want to do it properly: strictly type the response type. Most tutorials are setting the reponse as plain json.
I could just not use the api classes and interfaces in my test but then nothing would be strictly typed and what I want to do is create a testing framework that I can reuse over and over in my tests. If there are changes in the backend api I can just re-generate the api and I can just fix the compilation errors. Otherwise I know it will be a pain to troubleshoot the issue and I don want to go that way.
I'm a bit frustrated to not be able to go playwright all the way.
As anyone found a way to make it work with Angular decorators and of course keep the nice VS Code extension working properly?

**Comment by ffMathy** [comment]
@dgozman decorators are heavily used with dependency injection. We can't use Playwright right now because we can't reference any of our existing code, since it has classes with @injectable() decorators.

Can we re-open this and track it?
