### ISSUE TITLE
Reuse single page between tests difficult to find

### ISSUE THREAD

**Issue by jamsplodge** [microsoft/playwright#12162]
Hello, I needed to know how to prevent a new browser from opening between tests, however the information was included in the "Test Retry" page at https://playwright.dev/docs/test-retries#reuse-single-page-between-tests so this was difficult to find. Suggest moving this section to the "Configuration" page?

**Comment by dgozman** [comment]
We do not recommend this mode, so putting it to one of the most common docs is not the way to go. A [similar section](https://playwright.dev/docs/test-parallel#serial-mode) is also available in the "parallelism" doc.

Did you try searching on the docs site? If so, what do you search for? Entering "reuse" shows five different guides including this one. This [stackoverflow question](https://stackoverflow.com/questions/68699387/can-you-run-multiple-tests-in-one-browser-context-playwright-javascript) comes up when searching the internet as well.

**Comment by jamsplodge** [comment]
It depends on knowing the correct search terms to use, I was using "prevent browser context restart" (or similar) and found nothing. The word reuse didn't even occur to me. It really does have nothing to do with test retries though. The similar section in the parallelism doc does not actually suggest that the same browser would be used, so I wouldn't have known that would be use to me either. Anyway, was just a suggestion, I know where it is now.

**Comment by mxschmitt** [comment]
Closing since it seems answered.

**Comment by tsgautier** [comment]
Adding my $0.02 here because I find the answer discouraging.  "Hiding" a feature in the docs because it's discouraged doesn't seem the right way to go. I totally get that this is discouraged.  But you've documented it - so either you want to document it or not.  

IMO the section noted in this bug is mis-categorized.  It does not logically belong in the `Retries` section - and hence the confusion pointed out by the original reporter.  I agree with that sentiment - a section talking about page re-use (which breaks page isolation) doesn't belong in `Retries` because the two have nothing to do with each other.  It belons in `Parallelism`.  

I would urge you to re-consider your stance and put this section where it belongs.  It's fine to put a note discouraging the use (which I will note is NOT in the current section).  

The answer provided in this issue smacks of security-by-obscurity.  It would be better IMO to place the docs where they belong, so that they can be found/discovered by users, and appropriately labeled with encouragement or discouragement.  

I will note that I ONLY found this section of the docs when googling for it because of this issue - which is bad.

**Comment by tsgautier** [comment]
> We do not recommend this mode, so putting it to one of the most common docs is not the way to go. A [similar section](https://playwright.dev/docs/test-parallel#serial-mode) is also available in the "parallelism" doc.
> 
> Did you try searching on the docs site? If so, what do you search for? Entering "reuse" shows five different guides including this one. This [stackoverflow question](https://stackoverflow.com/questions/68699387/can-you-run-multiple-tests-in-one-browser-context-playwright-javascript) comes up when searching the internet as well.

I will note that this may have been true 2 years ago but no longer is true.
