### ISSUE TITLE
[Feature] allow use of toBeOK()​ with Response classes

### ISSUE THREAD

**Issue by alisterscott** [microsoft/playwright#12171]
Hi

I love using `toBeOK()​` with `APIResponse` - is there any reason we can't have this for `Response` also?

https://playwright.dev/docs/api/class-apiresponseassertions

Thanks

**Comment by mxschmitt** [comment]
Relates to https://github.com/microsoft/playwright/issues/12171

**Comment by stephenkilbourn** [comment]
I'd like to use this as well.  My use case: clicking a button to submit a form and intending to verify that the backend responded with a `200` to that POST.  the `toBeOK()` would make for a nice, succinct check.

**Comment by cpolera** [comment]
One option you'd have is to make your own custom matcher. 

But my preference is this
`  await expect(response.ok()).toBeTruthy();
`

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by sunker** [comment]
+1 for adding support for this.

``` js
// the following is simply more expressive 
const response = await page.waitForResponse('https://example.com/resource');
await expect(response).toBeOK();

// ..than doing this
const response = await page.waitForResponse('https://example.com/resource');
await expect(response.ok()).toBeTruthy();
```

It makes no sense that this matcher applies to `APIResponse` interface but not `Response` interface. 

Any chance you can re-open and reconsider this?
