### ISSUE TITLE
[Feature] automatically handle frames

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#12201]
currently to select an element that's located within a frame, you have to select the frame first:

```js
await (await page.frame("iframe")).$("foo")
```

it would be cool if playwright could just recurse through the frames to find the element matching this selector, so i can simply go

```js
await page.$("foo")
```

similar to how the chrome devtools work

**Comment by KotlinIsland** [comment]
This would be very based, and also consistent with how other web automation tools and libraries work.

**Comment by dgozman** [comment]
@DetachHead You can use frame locators to avoid multiple awaits and make things non-flaky:

```js
await page.frameLocator('iframe').locator('foo').click();
```

> it would be cool if playwright could just recurse through the frames to find the element matching this selector

In addition to this being technically challenging, it would also be surprising to most users. I can see this being opt-in, but with frame locators being available we will not prioritize it most likely.

> similar to how the chrome devtools work

Perhaps I don't understand what you mean, but I don't think you can do `$('foo')` across frames in developer tools.

**Comment by KotlinIsland** [comment]
> Perhaps I don't understand what you mean, but I don't think you can do `$('foo')` across frames in developer tools.

Yes it does search through all frames.


[UFT](https://www.microfocus.com/en-us/products/uft-one/overview) (🤮) searches through all frames.

[SeleniumLibrary](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html) has keywords for searching through all frames


> it would also be surprising to most users

In my experience I've only ever seen people be confused when a perfectly valid selector(`page.$("#my-div")`) doesn't return anything because the correct frame wasn't extracted first.

**Comment by DetachHead** [comment]
the current behavior is especially confusing because even the element explorer in the inspector searches through all frames, so in debug mode it highlights elements even though the script is unable to find them.

so the logic required to do this seems to already be present in the inspector

**Comment by klhex** [comment]
@dgozman 

> @DetachHead You can use frame locators to avoid multiple awaits and make things non-flaky:
> 
> ```js
> await page.frameLocator('iframe').locator('foo').click();
> ```

I (being not an expert on this, so maybe I am missing something) see two issues with this:

1. Quite some commercial web-based applications seem to be a) using iframes fairly intensively and b) using dynamic IDs and names for their iframes, meaning that those IDs and names change between each new login into the application. For this reason, so far we had to use alternative test automation frameworks instead of Playwright when we had to do test automation with such applications. (Luckily, this is the exception and in our day work we're testing our own app that works perfectly fine with PW.)

2. The need to specify technical details for element selection goes against the idea of the text- and layout-based selectors. If you are using those selectors (and in our team where we focus on e2e tests we're always striving to use them whenever possible) you usually expect the following principle to apply, I'd say: "If I can see a specific text on the screen I am able to select the underlying element with those locators without having to look at the page's source code."

And, indeed, PW's current behavior is somewhat confusing, like @DetachHead mentioned earlier. Here's a real-world, current example with regards to a commercial application as mentioned before:

Some elements on its main screen (left column) can be selected perfectly fine w/ text-based selectors as we're used to. Others, which seem to be part of an iframe, cannot. The text-based selector doesn't find them (it simply runs into a timeout), although the used text-based selectors (text=...) are actually provided by PW inspector's Explore functionality:

```
await page.locator('text=Category: Normal Change (2 Elemente)').click();
```
(Interestingly, when using "step over" in PW Inspector for that command, PW highlights the correct element in blue but nevertheless is unable to actually select it.)

Using PW Codegen gives us the following command:
```
await page.frameLocator('iframe[name="mif-comp-ext-gen-top295-625151"]').locator('text=Category: Normal Change (2 Elemente)').click();
```
Unfortunately, this one cannot be used since the iframe's name (as well as ID) contains dynamic parts which change upon every new login.

That means on the one hand we cannot use our beloved text-/layout-based selectors because we have to deal with elements within an iframe and on the other hand we cannot switch to the concerned iframe using the suggested method because of dynamic iframe names/IDs.

We'd love to be able to use text-/layout-based selectors also in cases where elements are located in iframes w/o having to research details in the page's source code.

> > it would be cool if playwright could just recurse through the frames to find the element matching this selector
> 
> In addition to this being technically challenging, it would also be surprising to most users. I can see this being opt-in, but with frame locators being available we will not prioritize it most likely.

I hope that my example regarding iframes and applications which use dynamic element names and IDs will help prioritizing it. 😃

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by DetachHead** [comment]
@pavelfeldman can this please be re-opened? there are many people who want this functionality, and considering selectors are deprecated in favor of locators, it's now even more of an issue than it used to be, since locators can be defined before their element is visible.

when using selectors, the issue is trivial to work around because you can just iterate over all the frames until you find the one that contains the element you're looking for:
```ts
await page.click("button")
const selector = "some element that's in an unknown iframe"
await page.waitForSelector(selector)
const element = findElementInFrame(selector) // function that iterates over all the frames until the selector is found
```

but with locators you need a way to do this every time the locator is used:
```ts
// defining a locator for an element that doesn't exist yet. my findElementInFrame function can't be used here
const locator = page.locator("some element that's in an unknown iframe")
await page.click("button")
await locator.waitFor()
```

**Comment by skptricks** [comment]
similar example to handle child frame in playwright  : [How to handle Child Frames in Playwright
](https://www.skptricks.com/2025/04/how-to-handle-child-frames-work-in-playwright.html)

**Comment by DetachHead** [comment]
thanks for reconsidering this!

an idea i had: what if `FrameLocator` was simply able to resolve to more than one frame?
```ts
page.frameLocator("*").locator("#foo") // match any frame that has the `#foo` element in it
```

this makes `FrameLocator` behave more consistently with regular locators which can only reduce confusion IMO

**Comment by DetachHead** [comment]
hmm actually that still wouldn't work in cases where you don't know whether an element is inside a frame or not

**Comment by DetachHead** [comment]
looks like this functionality has [finally been added in playwright 1.63.0](https://github.com/microsoft/playwright/releases/tag/v1.63.0)
