### ISSUE TITLE
[Question] How to click hidden elements?

### ISSUE THREAD

**Issue by talaikis** [microsoft/playwright#12267]
Example test:\

```js
const $hiddenButton = await getByTestId('hid')
$hiddenButton.click({ force: true })
```

gives, but fails:

```
elementHandle.click: Element is not visible
    =========================== logs ===========================
    attempting click action
      waiting for element to be visible, enabled and stable
        forcing action
      element is visible, enabled and stable
      scrolling into view if needed
    ============================================================
```

**Comment by mxschmitt** [comment]
Try: 

```js
await page.locator('#foobar:visible').click()
```

See here for more information: https://playwright.dev/docs/selectors#selecting-visible-elements

**Comment by talaikis** [comment]
> Try:
> await page.locator('#foobar:visible').click()

That will do nothing, because `:visible` selector finds only visible elements and hidden one already has unique test id. Playwright won't find the element by Id either, unlike visible ones.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by phil221** [comment]
> 

Hi @creativiii, I'm in the exact same situation w an invisible checkbox input. I need some way to run locator.check against that input in a test and it sounds like you achieved that somehow using labels. Can you explain more about your approach? Thanks!

**Comment by z-x** [comment]
@mxschmitt - could we reopen this. Hiding the input and leaving it's label to use custom styling is a common pattern.

**Comment by areriklq** [comment]
I solved it using native Javascript click:

JS
```
const $hiddenButton = await getByTestId('hid')
$hiddenButton.evaluate(node => node.click())
```

TS
```
const $hiddenButton = await getByTestId('hid');
$hiddenButton.evaluate((node: HtmlElement) => node.click());
```

**Comment by edmundcwm** [comment]
If we're looking to check a hidden checkbox/radio button, then doing something like `.setChecked(true, {force: true})` works for me.

**Comment by ggorlen** [comment]
> I solved it using native Javascript click:
> 
> JS
> 
> ```
> const $hiddenButton = await getByTestId('hid')
> $hiddenButton.evaluate(node => node.click())
> ```
> 
> TS
> 
> ```
> const $hiddenButton = await getByTestId('hid');
> $hiddenButton.evaluate((node: HtmlElement) => node.click());
> ```

This code is incorrect. `await` needs to be on the action, not on the locator.

**Comment by mdnahas** [comment]
I was able to make my situation work, eventually.  I have a custom checkbox that hid the default image with "display: none".  I was unable to click or set the input tag.   The input tag contained a "<span>" tag.  I gave that an "id" attribute and was able to manipulate the checkbox with:

`await page.click("[id='span_id']")`

I hope this helps someone else in the future.

**Comment by ggorlen** [comment]
> `await page.click("[id='span_id']")`

`page.click` is discouraged. It would be better to use locators and write this as `page.locator("#span_id").click()`, although this sounds _very_ use case specific.

**Comment by ITenthusiasm** [comment]
Hi everyone! As the maintainers requested, I've opened up a new issue that more specifically relates to `checkbox`es and `radio`s. The issue is #35885. **_If this is behavior that you want in Playwright, please go there and Upvote the Issue._**

Obviously, if you're not interested in the Issue, you shouldn't feel the need to bother with it. But if you do feel the matter is important, Upvoting it will be helpful, as it serves as part of the criteria the dev team uses for prioritizing their work and determining what to address.

CC: @leo-petrucci, @phil221, @z-x, @areriklq, @edmundcwm, @ggorlen, @mdnahas.
(Pinging because you expressed interest in either the idea and/or workarounds for it.)

---

As a sidenote, different Open Source repositories with large popularity seem to function differently. In Playwright's case, the best way to re-evaluate ideas seems to be opening new issues as `@mxschmitt` requested. So this is probably the most effective way to get responses from the team moving forward.
