### ISSUE TITLE
[Question] Add custom matchers to Playwright with Typescript support

### ISSUE THREAD

**Issue by HamedFathi** [microsoft/playwright#12264]
In [here](https://playwright.dev/docs/test-advanced#add-custom-matchers-using-expectextend) you are explaining how to write a custom matcher

```ts
// playwright.config.ts
import { expect, PlaywrightTestConfig } from '@playwright/test';

expect.extend({
  toBeWithinRange(received: number, floor: number, ceiling: number) {
    const pass = received >= floor && received <= ceiling;
    if (pass) {
      return {
        message: () => 'passed',
        pass: true,
      };
    } else {
      return {
        message: () => 'failed',
        pass: false,
      };
    }
  },
});

const config: PlaywrightTestConfig = {};
export default config;
```

but in the last line, you have mentioned:

> For TypeScript, also add the following to `global.d.ts`. You don't need it for JavaScript.
There is no following code!

Could you please help me to find out how to write a Typescript compatible code in `global.d.ts`?

I asked this in [stackoverflow](https://stackoverflow.com/a/71199825/3166171) first but based on the answer maybe there is a problem.

![JnfLS](https://user-images.githubusercontent.com/8418700/154927340-c2f91071-1418-45cc-8d98-4ae3abc9ae4f.png)

**Comment by mxschmitt** [comment]
There was a bug in our docs, that the snippet didn't got rendered. Thats what you need to use:

```ts
// global.d.ts
declare global {
 namespace PlaywrightTest {
    interface Matchers<R> {
      toBeWithinRange(a: number, b: number): R;
    }
  }
}
```

We'll fix it soonish.

**Comment by altamashali92** [comment]
How to specify the type of receiver argument while declaring a custom matcher?

Consider the declaration:

```ts
// global.d.ts
declare global {
 namespace PlaywrightTest {
    interface Matchers<R> {
      toBeWithinRange(a: number, b: number): R;
    }
  }
}
```

This matcher can be used as:

```ts
expect(1). toBeWithinRange(0,5);

// How to make it type safe so that we can't pass string inside expect:
expect("hello world"). toBeWithinRange(0,5);
```

**Comment by somebody1234** [comment]
@altamashali92 Late to the party but I have a working (if janky) solution:

[Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUwB5mQY3gXzgMyghDgHIABMAGwEMBPAdymAHMALGAehmQGcZSAKEEATLLSjI4LKhABGNKokFwAdjRB8wNTFIAKtRs3YwAKn3gIVcG5gir+cKAC44AV1XAAjm6m86IHIQVADc1rb2jjCuHt6+cP6BwWE2NsCqPFD4OlIAsjQwmGzIULwAPABKADRwpgB8yqmpANpQALquFSlNcM0wHbXdTTAQAELIAOrAMGzpFTSqLMgAFDPAvK75hcWlZR4A1qoQDKo1qm6BJXU1NK7nl1A1cncXciUAlJ1DcDjWv7+CNAYbDLACM7wAdCNxlM1qp5osVgAGKoAVneYSBWBgywARMUqLI4AxoFQRLjIdDJtNZvCFktlij0SEgA)
```ts
declare global {
 namespace PlaywrightTest {
    const r: unique symbol;
    const t: unique symbol;
    interface Matchers<R, T> {
      [r]: R;
      [t]: T;
      toBeWithinRange(this: Matchers<unknown, number>, a: number, b: number): R;
    }
  }
}
```

the funny unique symbols are needed otherwise the typecheck doesn't fail, because TS is structurally typed meaning that if `R`/`T` is never used in a property in `Matchers`, then there is no difference between a `Matchers<R, T>` and a `Matchers<R, U>`

**Comment by somebody1234** [comment]
@mxschmitt it looks like the docs are again missing (again due to some kind of formatting error?) from the new page?
