### ISSUE TITLE
[Question] Verify Reusable Locator Strategy

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#12355]
This is more of a validation of whether we can reuse locators.

I am using locator strategy in the tests.

I dont want to redefine locators for a specific pattern every time in the test.

i have added script below, 

Reusable Locator in file 1
```
  async buttonHavingText (buttonText: string): Promise<Locator> {
    return await this.page.locator(`//button[contains(text(),'${buttonText}')]`)
  }
````

Function in file 2
````
await ( await file1.buttonHavingText('SAVE')).click()
````
Queries

1) This scenario in file 2 i have to use multiple await, is this ok to use

2) File 1 contains locators, is it ok to drop async await, as they are locator

To simplify and write code like below
```
await file1.buttonHavingText('SAVE').click()
````

**Comment by mxschmitt** [comment]
Absolutely, Locators are made for reusability. Also creating Locators is a synchronous operation and not an asynchronous one. This means you can do:

```ts
  buttonHavingText (buttonText: string): Locator {
    return this.page.locator(`//button[contains(text(),'${buttonText}')]`)
  }
```

so your actual statement will look like:

`await file1.buttonHavingText('SAVE').click()`

To answer your queries:

1. you don't anymore, crating and wrapping locators or framelocators don't require await
2. yeah you need to drop it inside buttonHavingText and then file2 as well

btw. since you manually do text contains, we added some new APIs, which allow:

`this.page.locator('button', { hasText: buttonText })` see here: https://playwright.dev/docs/release-notes#locator-improvements

**Comment by jithintill** [comment]
thanks for clarifying, i wil look at the latest docs as well, seems like its close to what i am after
