### ISSUE TITLE
[Feature] ElectronApp.waitForFunction()

### ISSUE THREAD

**Issue by jjeff** [microsoft/playwright#12365]
It would be great if there were a method similar to [page.waitForFunction()](https://playwright.dev/docs/api/class-page#page-wait-for-function), but for the Electron main process.

I've created an implementation in the [electron-playwright-helpers](https://github.com/spaceagetv/electron-playwright-helpers) library for [waitForFunction(electronApp, function)](https://github.com/spaceagetv/electron-playwright-helpers/blob/1bb2f8c1607eb529cd5e54aa0c5d5708bdd76afb/src/general_helpers.ts#L18), but it really feels like this should be part of Playwright itself.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
