### ISSUE TITLE
[Feature] Locator.screenshot adds a parameter full_ element

### ISSUE THREAD

**Issue by luxuncang** [microsoft/playwright#12381]
- Full screenshot of scrollable elements

```python
page.locator("***").screenshot(full_ element = True)
```

similar

```js
 el = document.querySelector("***");
 el.scrollTo(0, el.scrollHeight);
```

**Comment by dimkin-eu** [comment]
please make this :)
as could be nice to test the whole webelement, which is half-hidden in some scrollable element
as this sometimes is not enough for testing :(
` If the element is covered by other elements, it will not be actually visible on the screenshot. If the element is a scrollable container, only the currently scrolled content will be visible on the screenshot.`

**Comment by dimkin-eu** [comment]
some hack/workaround is here https://github.com/microsoft/playwright/issues/12962

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
