### ISSUE TITLE
How do I record scripts without the inspector(Only use python api to open codegen mode and get the recorded scrips)？

### ISSUE THREAD

**Issue by l3yx** [microsoft/playwright#12407]
### Your question

I run playwright in docker ，and forward the screen of chrome through xvfb and x11vnc，but I found that I passed page.pause() does not display an inspector , so I want to record the script through the pure python code.

**Comment by aslushnikov** [comment]
This is not supported at the moment, but we might come up with something.

**Comment by whydna** [comment]
@aslushnikov +1 for this feature.

**Comment by hkfsc** [comment]
+1 for this feature, need codegen work with existing browser, currently it can't do such a job for me.

**Comment by masoncj** [comment]
I'm also working to automate Playwright code generation and/or create Playwright traces that combine both actions generated by a test or script and actions performed by a human in the browser.

I've had some luck in setting the environment variable `PW_CODEGEN_NO_INSPECTOR=true` and then calling `pause()`. This starts code generation without showing the inspector. However, this is still leaves the playwright process not accepting further commands, which is not what I want.

I've created a proof of concept of exposing the `recorder_supplement_enable()` server function on the client. This correctly starts a recording session and returns control the running Playwright script.  

I'd love to formalize this proof of concept by exposing this function. @aslushnikov would you be open to such a PR?  I'd welcome input about how to do this.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
