### ISSUE TITLE
[Question] Error: "context" and "page" fixtures are not supported in beforeAll.

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#12408]
Is there any way to open page `beforeAll` tests?

```
test.describe('Output Edit', () => {
    test.beforeAll(async ({page}) => {
        await page.goto('/test');
    });

    test('Simulations page', async ({page}) => {
        await page.click(SimResults.SimResultPage.simPage(2));
  });
});
```

Im trying not to duplicate `page.goto` in all my test files. As my URL would be same for all the tests.

**Comment by mxschmitt** [comment]
Replace beforeAll with beforeEach then it will work.

Playwright Test has context isolation by default, this means you have a new page and context for each test. By this its not possible to give you a page instance in the beforeAll hook, since there are different pages for each test. See here for more information: https://playwright.dev/docs/test-parallel

**Comment by aslushnikov** [comment]
@gauravgandhi1315 You can re-use a single page between tests: https://playwright.dev/docs/test-retries#reuse-single-page-between-tests
