### ISSUE TITLE
[BUG] Click misbehaviour for Chromium in visible area

### ISSUE THREAD

**Issue by DavertMik** [microsoft/playwright#1240]
**Context:**
- Playwright Version: 0.11.1
- Operating System: Mac
- Using interfactive pause in CodeceptJS (hope not that much related)
- React on the frontend. I assume this is related

#### Scenario: 

* open https://wetransfer.com first time
* agree on terms
* reload page 
* you will see splash screen with 3 buttons "Sign up for free", "Use Pro" and "No thanks"
* click "Sign up for free button"

#### Expected behavior: 

* a splash panel from right with sign up for will appear

#### Current behavior

* when clicked manually in chrome = same as expected
* when clicked in firefox = same as expected
* when click in webkit = same as expected
* when clicked in headless chromium = same as expected
* **when clicked in chromium BUT the button is in visible area - button is not clicked but background element receives a click and a new tab with a post is opened**

Videos attached:

1. Executing this test in Firefox.- expected behavior: https://recordit.co/Q1z7lw916a
2. Executing in Chromium - clicking on element triggers event for background (BUG), clicking manually works as expected https://recordit.co/qtix0XpMoc
3. Executing in Chromium but when the button is not inside viewport  - expected behavior https://recordit.co/cKGdq7HfNr

P.S. Bug appears to be Chrome-wide. Similar behavior happens in WebDriver & Puppeteer.
Everything works fine in headless mode but crashes once an element is visible.

**Comment by DavertMik** [comment]
@aslushnikov this may be the difference only in text but UI is the same.
Anyway, you can get the same text if open European version of the website. 
But according to your screenshot the button and UI should be the same.

Try this: when clicking "Take me to Free" - it should open login form
WHen clicking the same button in Chromium in Playwright in visible mode - it should open a new tab.

Here is the video of expected flow: https://recordit.co/d4nnY6hZCN
A video clicking in Playwright

**Comment by aslushnikov** [comment]
@DavertMik nicee, thank you! I was able to reduce this to a nice small test case. 

For the record: the root cause here is due to the incorrect input dispatching that we do on the chromium-side when dispatching input across iframes. We currently shortcut iframe picking  in [`input_handler.cc`](https://cs.chromium.org/chromium/src/content/browser/devtools/protocol/input_handler.cc?sq=package:chromium&dr=C&g=0&l=1398) using `RenderWidgetHostInputEventRouter::GetRenderWidgetHostAtPoint` - which is not correct. In fact, there are no other chromium clients for the method apart from us.

Instead, we should migrate onto `RenderWidgetHostInputEventRouter::GetRenderWidgetHostAtPointAsynchronously` so that we can properly dispatch events.

P.S. @DavertMik: you should be able to workaround this bug in chromium with `--disable-site-isolation-trials` flag.

**Comment by aslushnikov** [comment]
upstream fix: https://chromium-review.googlesource.com/c/chromium/src/+/2099229/
