### ISSUE TITLE
[Feature] route.fulfill() called without args should fulfill with the value of the response received over the wire

### ISSUE THREAD

**Issue by MartinP-Autopilot** [microsoft/playwright#12451]
```
page.route(path, async (route, request) => {
      console.log(`${path} was called from ${page.url()}`); 
      let r = await request.response();
      await route.fulfill({
        body: await r.body(),
        contentType: await r.headerValue('Content-Type'),
        headers: await r.allHeaders(),
        status: r.status(),
      });
    })
```
The above is an example of what I need to do just to log which browser view a particular request was made from.  There are possibly many scenarios in which I don't want to modify the response but just trigger something when the request is made.  It seems inefficent to have to figure out all of the above code to do this.

(Btw, one of the options for route.fulfill is `response`, but it is of type ApiResponse, whereas `Request.response()` returns an instance of `Response`, which doesn't match ???)

**Comment by yury-s** [comment]
You don't need request interception in this case (moreover, it will not work in the form you wrote it because you won't receive response while the request is intercepted), use [`page.on('response', r => console.log(r.url() + ' was called'))`](https://playwright.dev/docs/api/class-page#page-event-response) instead.
