### ISSUE TITLE
[Feature] --debug Inspector to not close immediately on finish

### ISSUE THREAD

**Issue by alanbqs** [microsoft/playwright#12525]
when running a script via ```--debug``` you get to step through the test script - stopping at most (but annoyingly not all) lines in the script.

When the script runs into an issue (in my case a ```await expect(...toBe('xxx))```, then I find the inspector closes immediately - leaving you unable to see where the problem was in the final executed line. 

Please can you have the Inspector to not close when finished (either by default or when run with a ```--``` option)

**Comment by janosh** [comment]
Would be a very useful change. I vote to make leaving the inspector open after the last step by default, shouldn't require an a CLI flag.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by janosh** [comment]
I think this is a crucial usability issue and should not be closed. I actually need to append spurious expects when debugging tests just to be able to inspect the failing line I care about.

**Comment by nikkwong** [comment]
Can someone suggest some way to achieve this or any workaround?

**Comment by sedghi** [comment]
I agree, it should stay open, otherwise it is a lot to get it run again

**Comment by NikolinaP** [comment]
I'm facing the same problem. If the Inspector closes immediately after a script runs into an issue, how are we supposed to debug it?
