### ISSUE TITLE
[BUG] `npx playwright install-deps chromium` installs all browsers

### ISSUE THREAD

**Issue by AmruthPillai** [microsoft/playwright#12566]
**Context:**
- Playwright Version: v1.19.2
- Operating System: Ubuntu 20.04
- Node.js version: 16.x
- Browser: Chromium

**Describe the bug**

When running `npx playwright install-deps chromium` installs the dependencies required, but also seems to install all other browsers even though the chromium flag is added.

**Comment by Mone71** [comment]
Thanks

**Comment by yury-s** [comment]
This is a known limitation running `npx playwright <any command>` will install 3 browsers, you can workaround that in 2 ways:
- run the command with `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1`, i.e. `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npx playwright install-deps chromium`
- run `@playwright/test` instead of playwright: `npx @playwright/test install-deps chromium`, it will also install deps without installing browsers.

**Comment by AmruthPillai** [comment]
@yury-s Perfect, this should work. Thank you so much!
