### ISSUE TITLE
[BUG] Unknown permission: push

### ISSUE THREAD

**Issue by connorjsmith** [microsoft/playwright#12649]
**Context:**
- Playwright Version: 1.8.1
- Operating System: Mac
- Node.js version: 16.4.1
- Browser: Chromium

**Code Snippet**

```javascript
const {chromium} = require('playwright');
const browser = await chromium.launch();
const context = browser.newContext({ permissions: ['notifications', 'push']})
```

**Describe the bug**
Setting the permissions above results in the following console error
```
Unknown permission: push
```

"push" is a valid permission according to https://playwright.dev/docs/api/class-browsercontext#browser-context-grant-permissions

Same issue as #5631

**Comment by ltsuda** [comment]
Apparently, the `push` permission is not available https://github.com/microsoft/playwright/blob/abd7084bcc3c75b49732fadfe1077010748655b8/packages/playwright-core/src/server/chromium/crBrowser.ts#L409

I don't know if it's the same as this https://developer.chrome.com/docs/extensions/mv3/permission_warnings/#permissions_with_warnings , but it doesn't exist `push` permission, maybe is for mobile browser but I'm not sure if there's a different documentation.

**Comment by yury-s** [comment]
'push' permission should be the same as 'notifications' since https://chromium-review.googlesource.com/c/chromium/src/+/758456/. I'm going to update the docs and remove that value from the api. Since the value was deprecated in 2017 it should not break existing clients as they would hit the same bug as described if they were passing 'push'.
