### ISSUE TITLE
[BUG] playwright install does not work behind socks5 proxy

### ISSUE THREAD

**Issue by labeldevops** [microsoft/playwright#12678]
playwright install does not work behind a socks5 proxy: 

```
$ playwright install chromium
Failed to install browsers
Error: Failed to download chromium v965416, caused by
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1585:19)
    at TLSSocket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I set HTTPS_PROXY=127.0.0.1:8080 - but, yes, I understand that HTTPS is not SOCKS5. It should just work with a socks5 proxy, like e.g. SSH tunnels.

**Comment by biswajitnayaak** [comment]
@labeldevops  did you got any solution for this?? i am getting this error

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
