### ISSUE TITLE
[Question] Which page event should I use to capture `securitypolicyviolation` event

### ISSUE THREAD

**Issue by archlichking** [microsoft/playwright#12694]
We're looking for a proper point during the page loading to inject a piece of js in order to capture [`securitypolicyviolation`](https://developer.mozilla.org/en-US/docs/Web/API/SecurityPolicyViolationEvent#browser_compatibility) event (more to read https://developer.mozilla.org/en-US/docs/Web/API/Element/securitypolicyviolation_event), but turns out there seems no proper event from [`Page`](https://playwright.dev/docs/api/class-page) class. Any help is appreciated.

**Comment by yury-s** [comment]
Although there is no dedicated event for this error (or other web errors) you can listen to  the console [messages](https://playwright.dev/docs/api/class-page#page-event-console):

```js
page.on('console', m => console.log(m.text()));
```
and parse that message, it will contain something like `"Refused to load the image 'http://localhost/HTTPRevved_fix_typo.png' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback."`
