### ISSUE TITLE
[Feature] Dynamically generated tests in globalSetup

### ISSUE THREAD

**Issue by leotg130** [microsoft/playwright#12857]
I noticed this https://github.com/microsoft/playwright/issues/12018.

Our use case is to use playwright itself in globalSetup to generate the tests. So the number of tests, names and parameters aren't known in advance, and we use playwright to discover them and then use that list to "generate" the tests.

Below pseudo code in globalSetup.ts:
```
const globalSetup = async (config: FullConfig): Promise<void> => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();

  const tests = page.doStuff(); // generate list of tests
  process.env.TESTS = String(tests);
};
```

Then in foo.test.ts:
```
const tests = process.env.BBF_SB_STORIES.split(',');

tests.forEach((aTest) => {
  test(`${aTest}`, async ({ page }) => {
    // Do stuff
  });
});
```

What would be the suggested way to generate the list of tests dynamically (+ async)?

**Comment by pavelfeldman** [comment]
I'd generate the tests as a different step before running Playwright. Or fetch all the necessary information before running tests, save it into json files and read those files synchronously when generating tests.

```
const tests = JSON.parse(fs.readFileSync('data.json', 'utf-8'));

tests.forEach((aTest) => {
  test(`${aTest}`, async ({ page }) => {
    // Do stuff
  });
});
```

**Comment by pavelfeldman** [comment]
> What's the difference between generate the tests as a different step before running Playwright vs fetch all the necessary information before running tests? Is there some intermediate step during which we could dynamically generate the tests still?

The reasons behind the change:
- Better tooling support (VS Code extension): we can't afford expensive / asynchronous test generation, so we assume that if this is the case, generation happens outside of the `npx playwright test`.
- Better reporting support: we wanted global setup to happen after tests started and global setup errors to be a part of the general reporting. We are about to introduce global fixtures (lazy bits of global setup that only trigger when the first test needs them) and that was all speaking for no test generation from the setup.

But it does not mean we can't add a 'generator' hook that would be generating the tests before running them. Here intent would be clear, we would know how to disambiguate it from the global setup in the tooling. We can re-title this issue as a request for that and collect upvotes. Easier to make it happen if you are open to sending a PR.

**Comment by leotg130** [comment]
Thanks for the info. I probably won't have time in the next couple of months, so let's leave it open and see if others are interested in the feature.

Will need to either downgrade to previous version or indeed generate tests prior to running playwright-test, for now.

Another possible alternative would be to run all of our tests within a single playwright test, though generating the tests within globalSetup was a bit more seamless as each test got its own test.

**Comment by WebWizhard** [comment]
@leotg130 is your first comment you made what you're using in real life or is it just some type of example code how this could work in the future? 
I'm currently at the point that I get an external config file that contains data for the test cases to run with which I want to dynamically populate data within the tests on the one hand, but actually also dynamically populate data within playwright.config. And I wonder if this is possible with your approach of the global setup? 
I hope you understand what I mean, otherwise I will try to explain it in more detail.

**Comment by leotg130** [comment]
@WebWizhard We were using PW (Playwright) in the global config, to generate the URLs we need to test. Using PW in the global config doesn't work anymore, you can only use PW in the actual tests.

Now we use PW separately, before tests, to generate a JSON file and then we use that JSON file in PW tests, to generate the list of tests.

I'm not exactly sure what it is that you're trying to achieve, but using an external config file shouldn't be a problem. You may want to look at https://playwright.dev/docs/test-parameterize.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
