### ISSUE TITLE
[BUG] Problems with parallelism and page.waitForSelector

### ISSUE THREAD

**Issue by joshuacc** [microsoft/playwright#12964]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Linux
- Node.js version: 14
- Browser: Chromium
- Extra: Our tests run on an Azure Devops pipeline agent with 2 cores and 7gb of RAM.

```javascript
page.waitForSelector('[data-test-hook="home-page-container"]', { state: 'attached', timeout: 1_000 });
```

**Describe the bug**

While migrating our E2E tests from Puppeteer to Playwright, I've noticed that as we increase the amount of parallelism to speed up our tests, our calls to `page.waitForSelector()` get flakier. To the point that in our trace files we can see that the desired selector is already attached in the 'before' tab, and yet we still get timeout errors.

Below I have attached a screenshot showing the issue. If it is helpful, I can provide the full trace file internally at Microsoft.

It is worth noting that if I use `page.$('[data-test-hook="home-page-container"]')` to test for the element's presence, it does not seem to be affected by the parallelism problem, but it comes with the major downside that it doesn't put records of the action into the trace file, which is often essential to our debugging.

![image](https://user-images.githubusercontent.com/171086/159581759-ad2c41b9-7174-4f3a-b79e-f919b189d50a.png)

**Comment by joshuacc** [comment]
Almost forgot to mention. We are not using Playwright Test, but our pre-existing E2E test framework to manage the parallelism. I can share details of that internally.

**Comment by dgozman** [comment]
@joshuacc Most likely, your pipeline machine is too overbooked that one of the processes just never had a chance to check for the element because it was not even scheduled to run during 1000ms. We've seen that on our (pretty weak) bots and we run tests with a single worker.

It does indeed look like the element was there. Trace says "duration: 1.2s" which is a lot longer than timeout of 1s, so overall slowness is the most plausible explanation I can come up with without debugging.

I also noticed that you have three `page.waitForSelector()` failures in the single test. Usually, test ends after the first failure - are you doing something special there?

**Comment by joshuacc** [comment]
@dgozman Regarding the additional `page.waitForSelector()` calls, yes, we are doing something special there at the end of each test scenario to check whether the failure was due to a couple of known causes, so we can categorize the failures.

I agree that overall slowness seems to be the precipitating cause. But it seems to me like there may be an underlying bug in Playwright here because...

1. The element is already present in the "before" snapshot. My understanding is that `page.waitForSelector()` should immediately return in that case.
2. When I use `page.$()` to check for the presence of that element, this failure doesn't occur. That suggests to me that there may be an issue with the way that timeouts are handled.

Of course, I could be entirely wrong here, but the combination of those two things just seem suspicious to me. :)

**Comment by dgozman** [comment]
@joshuacc There could definitely be a bug, but we'll need to debug locally with a repro to find it 😄 

> When I use page.$() to check for the presence of that element, this failure doesn't occur.

That's because `page.$()` does not have a timeout, so no matter how slow the machine is, it will eventually respond with an element. If you bump your `waitForSelector` timeout, you'll see less flakiness.

Overall, we recommend to run without any timeouts for specific actions (or with a rather large timeout like 30s), and instead rely on a single test timeout to find issues. This way, you usually do not have flakiness due to process scheduling under heavy load.

**Comment by joshuacc** [comment]
@dgozman Thanks for your help and suggestions! I've applied some tweaks based on what you've said and am going to try them out shortly. In the meantime, maybe you can help me update my mental model around how Playwright works?

My understanding of the way that `page.$()` works is that on the next turn of the event loop it will return either an `ElementHandle` or `null`. Is that correct?

Model A: My previous understanding of `page.waitForSelector()` is that on the next turn of the event loop it would check for the presence of the element and would synchronously start a timer, then periodically check for the presence of the element until the timer exceeded the timeout threshold. In this model, a slow machine would not ever have a timeout failure if the element was already present.

Model B: My current understanding of `page.waitForSelector()` is that it first synchronously starts a timer, and on the next turn of the event loop it checks for the presence of the element, then periodically check for the presence of the element until the timer exceeds the timeout threshold. In this model, a slow machine **could** have a timeout failure if the element was already present if the elapsed time between the start of the timer and the next turn of the event loop exceeds the timeout threshold.

Can you confirm that Model B is how Playwright actually works? Assuming that is the case, would there be any downsides to switching to Model A instead? Model A seems to me like a much more natural way of understanding what the timeout means. 🙂

**Comment by dgozman** [comment]
@joshuacc Model B is almost exactly how it works. When you say "on the next turn of the event loop", that's not entirely accurate though. Checking something in the page involves going to the other OS process (browser process vs playwright's node process), so the check is very much asynchronous as well. This also means that going to the Model A is impossible, because the very first iteration of checking for the element may take arbitrary amount of time.

In addition, I'd say `page.waitForSelector()` is rarely used. Most of the time you just do `page.locator().click()` and that waits for the element inside. If you had to resort of `page.waitForSelector()`, you have something unusual going on, and most likely the element is not immediately present in the page. Note this is just an opinion, no hard statistics behind it 😄

**Comment by joshuacc** [comment]
@dgozman Thanks for the insight! I've been able to make our Playwright adapter work much better based on this information.
