### ISSUE TITLE
[BUG] Codegen via iframes does not work all the time

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#12988]
Repro:

1. `npx playwright codegen https://support-shop.astoreprocurement.com/access/unauthenticated`
2. Wait for 5 seconds - do not focus the site
3. Try to fill something in the email page

Expected: Selector does get generated
Actual: It keeps saying just `iframe` and does not recognise the interactions inside the iframe.

Note: It seems its related to the lazy initiated iframe - when you reload just the iframe it then works correctly.

**Comment by Nhc007** [comment]
@mxschmitt We also faced that issue while interacting with iframes elements, but we fixed that by switching to iframe first, and use it as active frame and then just normally interact with it but do remember that, once you are done with interacting with iframe change the activeFrame back to page. Hope so this will fix the issues.

**Comment by kblok** [comment]
@yury-s Do you know if there is a way to see why an execution context crashes?
I'm getting some execution context leaks while running some scripts with iframes. Unfortunately, I wasn't able to isolate this yet.

<img width="355" alt="Screenshot 2022-11-18 at 14 46 13" src="https://user-images.githubusercontent.com/2198466/202802687-53c6400d-3aab-415c-a2c3-1d86d12deaa1.png">

**Comment by paescuj** [comment]
Might be worth to test it with a different browser, e.g. `--browser firefox`.
In my case that worked!
Although my issue was not directly related to an iframe, I believed so at first but recording in Chromium hasn't even worked after directly loading the page from iframe...

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
