### ISSUE TITLE
[BUG] AfterAll executes twice between tests

### ISSUE THREAD

**Issue by rolandz83** [microsoft/playwright#13044]
## System:
 - OS: Windows 10 10.0.17763
 - Memory: 7.80 GB / 15.88 GB
## Binaries:
 - Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
 - npm: 8.3.2 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - playwright: ^1.20.1 => 1.20.1
- Browser: [All]

## Code

![image](https://user-images.githubusercontent.com/78881730/159955789-97f6f0f2-75de-461b-a7ee-362dae36803d.png)

##Result
![image](https://user-images.githubusercontent.com/78881730/159956498-1957d463-bda9-45d5-8e0e-454edc68578f.png)

**Describe the bug**

Hey guys, for a long time I been trying to investigate the cause of failure on some of our 2-3 hours long e2e tests.
When we ran individual tests they pass but if we ran the whole thing we see target page close, browser close, with no trace files.
I concluded that the machine running the tests gets low on memory killing the browser ??? not sure if that is a possibility.
(If I run the same tests locally I do not have this issue.)

to make the long story short, in hopes to remedy the situation I tried adding test.afterAll to close the browser.

and now I discovered afterAll running twice between the tests. The first set of tests runs fine, when the second set begins browser closes with this error : browser.newPage: Target page, context or browser has been closed
Should I do something differently ?

And any suggestions on my initial problem of why a test stops with target page close.
As I am writing this some one posted this question which I believe are related issued.

#13038 

Thank you for your help !

**Comment by dgozman** [comment]
@rolandz83 This is expected behavior. Take a look at [this guide](https://playwright.dev/docs/test-retries#failures): it explains the similar story, using `beforeAll` as an example.

That said, you should not close the browser in `afterAll`, because that would be done automatically for you, at the best moment.

I see you are reusing the page between tests. If you don't have a very good reason for that, I'd suggest to use the built-in `page` as seen in every example in the documentation. If you don't like that, try to split your tests by files to avoid using the same page for too many tests at the same time.

**Comment by rolandz83** [comment]
When I use afterAll to close the browser, it does not stop the automatic behavior of closing it so it runs twice and tries to close something that is not there...
now it makes sense. Thanks!

**Comment by roscioli** [comment]
https://jestjs.io/docs/configuration#globalsetup-string
