### ISSUE TITLE
[FEATURE] Allow getting current default timeout values

### ISSUE THREAD

**Issue by Alturil** [microsoft/playwright#13051]
There are currently ways of changing the default tiemout values ([here](https://playwright.dev/docs/api/class-page#page-set-default-timeout) and [here](https://playwright.dev/docs/api/class-page#page-set-default-navigation-timeout) for example), but these values can't be retrieved as far as I can see. This is super annoying when trying to debug, especially when having multiple layers of configuration. Any chance we can make these properties accessible?

Thanks!

**Comment by virbyte** [comment]
would like this too!

**Comment by Dzhuneyt** [comment]
Very useful in the following scenario that I'm facing:
1. Tests usually take 80 seconds to complete
2. Our timeouts are configured to 90 seconds, which is more than enough to cover the actual test run
3. "context" teardown (because it encodes and saves logs, recordings, screenshots) sometimes takes 10+ seconds
4. This leads to tests randomly failing or succeeding, depending on how long the "context" teardown will take

Being able to retrieve the current timeout and remaining time until timeout at PlayWright runtime would allow us to conditionally extend that timeout when we know that context teardown will potentially lead to a test failure, e.g. something like this would have been nice:

```
  context: async ({ context, credentials }, use, testInfo) => {
    switch (testInfo.project.name) {
      case "chromium":
        {
          const context = // Create our own Chromium context here

          await use(context);

          // Suggestion start
          if(PlayWright.getRemainingTimeToTimeout() < 10000){
              PlayWright.setTimeout(PlayWright.getElapsedTimeSinceTestStart() + 20000);
          }
          // Suggestion end

          await context.close()
        }
        break;
      default: {
        await use(context);
        await context.close();
      }
    }
  },
```

Syntax made up and is open to debate, of course, but the general idea is: we should be able to extend the test timeout conditionally with not just a fixed value but a relative value (e.g. now + 20 seconds).

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
