### ISSUE TITLE
[Question] Did debug.enable('pw:api') stop working in Playwright 1.19?

### ISSUE THREAD

**Issue by ajssd** [microsoft/playwright#13052]
We use Playwright from the mocha test runner, launching everything from a node script.  We also use the verbose debugging that you get with DEBUG=pw:api.

Up through v1.18, we enabled debugging using `debug.enable('pw:api')` from the node script.  But starting with v1.19 -- no other changes -- this no longer works.

Of course, if I set a regular environment variable from the shell, DEBUG=pw:api, things work.  But we want to conditionally set the debug mode from within the node script.

Did something change that means we can't call `debug.enable('pw:api')` anymore?

**Comment by dgozman** [comment]
@ajssd This is most likely due to different version of `debug` library. Playwright 1.19 uses `debug@3.4.3`, and your `node_modules` most likely upgraded to `debug@3.4.4`. Due to how Node works, these end up with different "enabled" state.

As a workaround, you can require the `debug` as it's seen by `playwright-core`:
```js
const debugPath = require.resolve('debug', { paths: [require.resolve('playwright-core')] });
require(debugPath).enable('pw:api');
```

**Comment by ajssd** [comment]
Thanks @dgozman -- I just want to make sure those version numbers are correct.  Seems like PW might use 4.3.3 if I am looking in the right place? https://github.com/microsoft/playwright/blob/main/packages/playwright-core/package.json

**Comment by dgozman** [comment]
@ajssd That's right, 4.3.3 is the right one!
