### ISSUE TITLE
[BUG] - using `for loop` works, but using `.forEach` fails: page.goto: net::ERR_ABORTED; maybe frame was detached?

### ISSUE THREAD

**Issue by cliffordfajardo** [microsoft/playwright#13071]
**Context:**
- Playwright Version: 1.20
- Operating System: MacOS 11.6.5
- Node.js version: 14.17.5
- Browser: [e.g. All, Chromium, Firefox, WebKit]

**Code Snippet**
Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```ts
import { expect, Locator, test } from '@playwright/test';
import { mockAllRequests, NETGRAPH_ROUTES } from '../utils'; // TODO: make alias

test.describe('Basic component visibility smoke tests', () => {
  const APP_ROUTES = ['/route1', '/route2'];

  test.only(`all __ pages should have <PageHeader />`, async ({ page }) => {
    let PageHeader: Locator;

    // ✅ passes when using `for loop`
    for (const appRoute of APP_ROUTES) {
      await page.goto(appRoute);
      PageHeader = page.locator('.ant-page-header').first();

      expect(await PageHeader.isVisible()).toBeTruthy();
    }

    // ❌ Fails when using `forEach`: page.goto: net::ERR_ABORTED; maybe frame was detached?
    // APP_ROUTES.forEach(async (appRoute) => {
    //   await page.goto(appRoute);
    //   PageHeader = page.locator('[data-testid="PageHeader"]');

    //   expect(await PageHeader.isVisible()).toBeTruthy();
    // });
  });
});
```

**Describe the bug**
Using `for loop` works when repeating some repetitive tasks , but using `.forEach` with the following error:

```
 fails: page.goto: net::ERR_ABORTED; maybe frame was detached?
```

### Related
- https://github.com/microsoft/playwright/discussions/13070

**Comment by dgozman** [comment]
@cliffordfajardo This is because the `forEach` construct never awaits the results. It just starts a bunch of `page.goto()` operations at the same time, but never waits for them to finish (the proper way to wait would be using `Promise.all`).

That said, navigating the same page to multiple urls at the same time would not work at all. If you want parallelism here, create multiple tests and each test will get its own page. Read more in the [parallelism guide](https://playwright.dev/docs/test-parallel).

**Comment by cliffordfajardo** [comment]
> This is because the forEach construct never awaits the results. It just starts a bunch of page.goto() operations at the same time, but never waits for them to finish

I see
For future readers, this describes the behavior of why it won't work well
- https://zellwk.com/blog/async-await-in-loops/

**Comment by brunojbarros** [comment]
@cliffordfajardo 
I had to deal with a similar problem using forEach.

**Context**: I need to make some requests to generate data, that data is what I use to iterate in the forEach.

**This was my solution:**
1- Create a file with a function in which I make all the necessary requests and in which I generate some .json files. In my case, "setup.ts"
2- Create a file in which I call the function from file 1. In my case, "setupCaller.ts"
3- Create a .sh file so that it calls setupCaller.ts, and then runs the tests. In my case, "testRunner.sh".
4- Update the package.json so that it executes "testRunner.sh".

When executing the .sh: all the functions you need will be executed first. After finishing the execution of functions, the execution of the tests will begin, therefore, the array that iterates the forEach will be the one expected.

I'm not sure if it's an efficient solution, but it solved my problem.


**Code example**:

`setup.ts`
```
async function setup() {
  // What you need to do, for example:
  await createUsers();
  await createProducts();
}
```

`setupCaller.ts`
```
void (async () => {
  // All the functions you need to execute
  await setup();
})();

```

`testRunner.sh`
```
echo "Starting setup"
ts-node utils/setupCaller
echo "Setup finished"

echo "Starting test execution"
npx playwright test
echo "Tests executed"
```

`package.json`
```
  "scripts": {
    "test": "./testRunner.sh",
  },
```
