### ISSUE TITLE
[Docs]: Page not found /404.html

### ISSUE THREAD

**Issue by shibababa** [microsoft/playwright#13096]
Hello!

I was navigating to the following URL: https://playwright.dev/python/docs/library and it resulted in a 404 error.

**Comment by rwoll** [comment]
Thanks for your report. I can reproduce by going to the link directly or going to https://playwright.dev/docs/intro in Node.js mode, then clicking "Playwright Library", the switching to Python in the language switcher.

This may be expected behavior, but it isn't necessarily friendly! @mxschmitt Should we redirect https://playwright.dev/python/docs/library to one of the Python pages?
