### ISSUE TITLE
[Feature] A way to CDP using persistent contexts

### ISSUE THREAD

**Issue by szmarczak** [microsoft/playwright#13111]
https://playwright.dev/docs/api/class-browser#browser-new-browser-cdp-session

https://playwright.dev/docs/api/class-browsercontext#browser-context-browser

> Returns the browser instance of the context. If it was launched as a persistent context null gets returned.

So `persistentContext.browser().newBrowserCDPSession()` cannot be used because `.browser()` returns `null`.

Would `context.newContextCDPSession()` make sense?

**Comment by rwoll** [comment]
Added [P3-collecting-feedback](https://github.com/microsoft/playwright/labels/P3-collecting-feedback) label to gauge interest in this feature.

Please elaborate on your use case(s) below!

**Comment by anxsec** [comment]
Run into the same problem.

**Comment by szmarczak** [comment]
@rwoll It's been almost 6 months. Is there any interest in this? I'd like to use [`Target.setAutoAttach`](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-setAutoAttach) for target interception, since Playwright doesn't support it yet.

**Comment by khanguy00** [comment]
I think `launchPersistentContext` should `return browser` instead of this:

https://github.com/microsoft/playwright/blob/df143031e7eac11460bcd658dc3bb5a8951ccd64/packages/playwright-core/src/server/browserType.ts#L86

This way, it should be allow people getting both `browser` and `BrowserContext`.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by cAttte** [comment]
piece of shit library
