### ISSUE TITLE
[Question] Is there way to define testing timeout for after running a webserver?

### ISSUE THREAD

**Issue by togo26** [microsoft/playwright#13119]
Hi, thanks for this great project in advance. 
I'm curious is there any way to define a timeout for after running a webserver.
I found that a test running time has been included in a webserver build time so depending on build environments, it seems that a test could have a small and large time difference. 

Let's assume a timeout of the config is `50sec`, and the test time takes `45sec`. If the build time is less than `5sec` on my local, the test would be passed. However, if an env that is much slower than my local(exceed build time more than `5sec`) would be not.

I know the `webServer.timeout` is also useful but if I must run testing without timeout or any constraint of a webserver then it seems not proper one. To ensure testing time regardless of fluctuating build time, how about adding like `timeoutAfterRunningWebServer` for this? (the name could be weird but just for reference)

(Just for my quick workaround is to set a long timeout as possible but not sure that is the best solution..
By any chance, is there good way than mine, or I've missed any info regarding this from the official doc?)

```ts
// Build time 

// test.spec.js
test('It takes 45sec for testing', ({ page }) => {
  await page.waitForTimeout(45000);
});

// config.js
const config: PlaywrightTestConfig = {
  webServer: {
    command: 'npm run start',
    port: 3000,
    reuseExistingServer: !process.env.CI,
  },
  timeout: 50000
};

// Proposal - config.js
const config: PlaywrightTestConfig = {
  webServer: {
    command: 'npm run start',
    port: 3000,
    reuseExistingServer: !process.env.CI,
  },
  timeoutAfterRunningWebServer: 50000, // Not include build time
};
```

**Comment by rwoll** [comment]
> I'm curious is there any way to define a timeout for after running a webserver.

Can you explain more what you mean by this? Is it that you don't want your webServer starting up time to impact the test-level timeout? Or is it that your webServer starts, looks to be available according to playwright, but you still want to wait some amount of time before beginning your actual test (maybe as dev server finishes building/serving artifacts)?

In your case, what does `npm run start` trigger?

**Comment by togo26** [comment]
> Is it that you don't want your webServer starting up time to impact the test-level timeout?

Yes it is and the trigger is `webpack-dev-server` with React.

**Comment by rwoll** [comment]
Thanks @togo26 for the additional information.

I'd recommend trying the `url` option, instead of using `port`: https://playwright.dev/docs/api/class-testconfig#test-config-web-server

> If the url is specified, the server will wait for the URL to return a 2xx status code before running the tests.

Unlike the port check, the `url` option will wait for an actual 2xx response, so depending on what  webpack-dev-server is serving, this is likely more suitable.

Let me know if that works!

**Comment by togo26** [comment]
Thanks for the idea! @rwoll 

Before getting into this, on my further testing, I've found it seems the starting time of a webServer doesn't impact to the test-level timeout..Maybe I made some mistakes before😅

Anyway I've tried the `url` option but it looks same as the `port`. However, the difference between the `url` and the `port` was the total time of playwright test. Tested several time for each case.

#### `url` 
(The total time is `19sec`. Seems included in a serving time of a dev-server - my local takes around `7~9sec` for running)
<img width="532" alt="스크린샷 2022-03-29 오전 8 19 39" src="https://user-images.githubusercontent.com/30683515/160505078-1e5068e9-786b-4382-aac7-4a8aa4acc0ed.png">

#### `port`
(The total time is `11sec`. Seems not included in the serving time)
<img width="524" alt="스크린샷 2022-03-29 오전 8 19 53" src="https://user-images.githubusercontent.com/30683515/160505340-1b7606b3-4479-426c-8319-1f111a88dde5.png">

#### Test case
```js
test('basic test', async ({ page }) => {
  await page.waitForTimeout(9500);
});
```

As the results, I'm not sure which one is the best..is it valid to use the `url` option still instead of the `port`?

**Comment by rwoll** [comment]
> I've found it seems the starting time of a webServer doesn't impact to the test-level timeout

If you have:

```ts
import type { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  timeout: 1 * 1000,
  webServer: {
    command: "bash -c 'sleep 5 && python3 -m http.server 8888'",
    port: 8888,
  },
};

export default config;
```

your tests will still run. The test-level timeout is 1 second, and although it takes 5 seconds for the port to be available, we don't count that port check against the individual test timeout, so the test still has 1 second to run.

> As the results, I'm not sure which one is the best..is it valid to use the url option still instead of the port?

If you're dealing with a web server that does HTTP things (like webpack-dev-server), I recommend the URL option over port. Many dev servers will open a port, before actually being fully setup and serving HTTP requests, so using a URL option in this case is safer, otherwise, since the port is open, PW will move on and try your tests (and possibly timeout in there).

---

Here's an example that illustrates this subtle distinction:

Consider this simple server that:

1. immediately starts listening on port 8888
2. only serves 404s while it boots up for the first 5 seconds.
3. after booting up, it will start serving 200s and your actual application.

```js
const http = require('http');

// Create an empty server without any routes.
let dynamicRouteHandler = (req, res) => { res.statusCode = 404; res.end(); };
const server = http.createServer((req, res) => { dynamicRouteHandler(req, res) });

// Start listening on port 8888.
server.listen(8888, () => {
    console.log(`Server is running on http://localhost:8888`);
});

// Simulate taking 5 seconds to install an actual route handler to serve our HTML!
console.log('installing routes…');
setTimeout(() => {
    dynamicRouteHandler = (req, res) => {
        res.write(`<p>hello</p>`);
        res.end();
    };
    console.log('Routes installed!');
},5_000);
```

Your test looks like:

```ts
import test, { expect } from "@playwright/test";

test('works', async ({ page }) => {
  console.log('running actual test case');
  await expect(page.locator('p')).toHaveText('hello');
});
```

If your config uses port:

```
import type { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  timeout: 1000, // 1 second
  webServer: {
    command: "node ./server.js",
    port: 8888,
  },
};

export default config;
```

your test will fail, because the port check immediately passed, and Playwright went to run your test while we were in phase (2).

To fix this, you can specify `url`, so we wait until the server is serving the actual content before running the test:

```ts
import type { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  timeout: 1000, // 1 second
  webServer: {
    command: "node ./server.js",
    url: 'http://localhost:8888/',
  },
};

export default config;
```

Closing this issue since it sounds like you got things working, but feel free to open a new one if you need additional help!

Thanks! 🎉

**Comment by togo26** [comment]
> If you're dealing with a web server that does HTTP things (like webpack-dev-server), I recommend the URL option over port. Many dev servers will open a port, before actually being fully setup and serving HTTP requests, so using a URL option in this case is safer, otherwise, since the port is open, PW will move on and try your tests (and possibly timeout in there).

@rwoll Thanks for the great explanation and the example!👍
