### ISSUE TITLE
[BUG] Playwright fails to install on generic-linux

### ISSUE THREAD

**Issue by PSanetra** [microsoft/playwright#13128]
**Context:**
- Playwright Version: 1.21.0-alpha-mar-25-2022
- Operating System: Linux 5.10 Manjaro Linux
- Node.js version: v16.13.1
- Browser: All

**Code Snippet**

```bash
$ npx playwright install
Failed to install browsers
Error: ERROR: Playwright does not support chromium on generic-linux
```

**Describe the bug**

`npx playwright install` fails on generic-linux since this change: https://github.com/microsoft/playwright/pull/12966

It seems like support for `generic-linux` is missing in the `findExecutablePath` function: https://github.com/microsoft/playwright/blob/237b4d58212510fd652ce4751d91c0ca77d71b86/packages/playwright-core/src/utils/registry.ts#L246-L255

**Comment by rwoll** [comment]
Thanks for your report and the proposed PR. We don't currently have bots set up to test generic-linux. With the PR change applied (and PW installed via it), do all the tests pass out of the box?

**Comment by PSanetra** [comment]
@rwoll I have responded in #13129

**Comment by rwoll** [comment]
Thanks @PSanetra! I've added [P3-collecting-feedback](https://github.com/microsoft/playwright/labels/P3-collecting-feedback) to gauge interest from other Playwright users using this distro.

To set expectations, generally, we like to have a bot testing anything that's officially supported to ensure a great user experience. Since many users are on Ubunutu (and that's our officially supported and tested Linux distro), we may not add support in the tooling for others until we're ready to add infra to support testing that distro regularly.

cc'ing @aslushnikov since he has more experience with the Linux dep bits than me!

**Comment by PSanetra** [comment]
@rwoll I am ok with deciding not to officially support non-ubuntu distributions, but playwright got broken for non-ubuntu distributions in #12966 by trying to improve the experience for non-ubuntu distributions😅

So I would also be ok with reverting #12966.

**Comment by rwoll** [comment]
Ah, sorry! I missed the link in the original description that indicated this is likely a regression. Updated with increased priority so the team can take a look ASAP!

Sorry that we broke a workflow that used to work for you, and thanks for your patience!

**Comment by aslushnikov** [comment]
@PSanetra Oops sorry for regressing you, my bad! And thank you for the PR! 🔥
