### ISSUE TITLE
[Feature] Find bounding boxes of text in webpage

### ISSUE THREAD

**Issue by LucidHal** [microsoft/playwright#13266]
I was wondering if it is possible to add functionality to get the bounding boxes of all individual text groups in a page. I am thinking of using such a feature to test if certain text elements are in the correct relative position with respect to other elements (such as certain divs, inputs, etc). Is such a feature possible to add? I know hovering on text in Chrome's inspect element can provide its bounding box (such information seems to be stored in the text's parent element's .text attribute) but I'm not sure how this could work in playwright.
I believe this can be quite helpful to people for general UI testing purposes and for building other applications based on positions of webpage text.

**Comment by rwoll** [comment]
See https://playwright.dev/docs/api/class-locator#locator-bounding-box. For any give selector, you can get a bounding box.

**Comment by LucidHal** [comment]
I understand that you can get the bounding box for any given selector, but the problem is I don't see a way to get selectors for just the text inside elements. For example, how do you get the bounding box of the text inside a div element that looks like this:
```
<div class="outer">
   Lorem ipsum dolor sit amet...
   <div class="inner">
      ...
   </div>
</div>
```
I've noticed that in Chrome, you can inspect element and hover over "Lorem ipsum..." and get the bounding box of it since it's a part of div.outer.text, but I'm not sure how this is possible with Playwright.

**Comment by rwoll** [comment]
Thanks for the clarification; I don't think we have a nice abstraction to get at the `TEXT_NODE`'s bounding box directly.

So it looks like the goal is to get the bounding rect that contains "example text" in:

```html
    <div style='width: 1000px; height: 1000px'>
      example text
    </div>
```

not the div element's rect, but that of just the Node.TEXT_NODE.

(`await page.locator(text=example text)boundingBox()`will return a bounding box with width=1000, height=1000, so this doesn't do what you want.)

@dgozman Do you have a suggestion (other than evaluate+traverse for Node.TEXT_NODE+createRange+getClientRects)?

> I believe this can be quite helpful to people for general UI testing purposes and for building other applications based on positions of webpage text.

@LucidHal **Can you elaborate on specific use cases you're looking to solve with this?** Playwright exposes a lot of rich, high-level APIs to make testing easier. e.g. instead of thinking about finding specific coordinates on a screen, you can just write `page.locator('text=download me').click()`.

**Comment by LucidHal** [comment]
> @LucidHal Can you elaborate on specific use cases you're looking to solve with this? Playwright exposes a lot of rich, high-level APIs to make testing easier. e.g. instead of thinking about finding specific coordinates on a screen, you can just write page.locator('text=download me').click().

@rwoll Sure, I am looking at a use case where the webpage has dynamic text and it's not possible to get a locator based on static text values. An example can be a web form, where the task is to measure the distances from text to input boxes. Or it could be something like a blog, where the task is to verify the position of child text within blog cards.

**Comment by rwoll** [comment]
Thanks @LucidHal. Added P3-collecting-feedback for to gauge general interest.

As a a work around, you can use `(page|locator).evaluate` + some JS on the `Node.TEXT_NODE`s: https://developer.mozilla.org/en-US/docs/Web/API/range/getClientRects

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
