### ISSUE TITLE
[Question] Provision to capture user agent information in the report

### ISSUE THREAD

**Issue by harir5** [microsoft/playwright#13283]
Hi ,

is there a way to capture user agent information (For instance, Browser Name, Browser Version name, Operating system name, OS version etc) . we will be able to triage application specific information better (if we find a bug) when we do cross browser tests if this information is available.Also would like to know if we can capture this information in our custom reporter please ? 

I would like to create a summary section which will contain the following information :

Browser Name : [BrowserName]
Browser Version : [Browser Version]
OS Name : [OS Name]
OS version: [OS version]
Execution Start Time :[hh:mm:ss]
Execution End time :[hh:mm:ss]
Total time taken to run tests : [time in minutes/seconds etc]

**Comment by rwoll** [comment]
We are experimenting with a feature along these lines. https://github.com/microsoft/playwright/issues/11318

**Comment by Camo30** [comment]
@rwoll Same issue here. Is there a way to identify the browser name and version which is currently used while running the tests? Tried with a custom reporter but there is no information available.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
