### ISSUE TITLE
[Feature] Accessor for browser type from context

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#1330]
It would be nice to get the browser type from [context.browser()](https://github.com/microsoft/playwright/pull/1329).browserType().

Right now we are using duck typing to detect if the context is chromium. https://github.com/qawolf/playwright-video/blob/bd2fd3e9bab29c9673de4b6708854bac97612967/src/utils.ts#L36

**Comment by aslushnikov** [comment]
@jperl So `context.browser()` is something we don't want since it's undefined for the `playwright.launchPersistent()` mode.

It looks like what you want is `context.browserInfo()`. Would it work for you?

**Comment by jperl** [comment]
Yes that is great! Anything that gives me "chromium"/"firefox"/"webkit" from context works 👍.

**Comment by pavelfeldman** [comment]
I'm tentatively closing it since detecting a browser type mid test might lead to some bad testing patterns. I'd encourage test runners to expose it if they feel necessary.

**Comment by WesleyAC** [comment]
Would you consider re-opening this? I understand that detecting browser type might result in some brittle tests, but here's my usecase: I have some code that requires a API that's implemented in Firefox but not in Chrome. My code uses the API in Firefox, and gives the user a error in Chrome. I want to test this. I'm using `@playwright/test`, so I don't have the ability to change the test runner to pass in this info, AFAICT.

The simple solution is just to write the test and check that either the code works or an error is returned, but I'd be worried about the failure mode there that the code would return the error even when the API exists, and the test would incorrectly pass.

Instead of that, I'd like to require that it work correctly on Firefox, and allow the others to either work correctly or return a error.

What should I do here? Just stop using `@playwright/test` and write my own runner? Or is there a API for this that I just haven't found?

It also feels quite silly that I can get `page.context().browser().version()`, but not `page.context().browser().browserType()`.

**Comment by WesleyAC** [comment]
Ah, for future travelers: looks like `@playwright/test` does provide this, via [`testInfo.project.name`](https://playwright.dev/docs/api/class-test#test-call) :)

**Comment by maztak** [comment]
This is not the answer for this subject, but perhaps good solution.
We can use browserType like below, not from context.
```
const playwright = require('playwright');
(async () => {
    for (const browserType of ['chromium', 'firefox', 'webkit']) {
        const browser = await playwright[browserType].launch();
        const context = await browser.newContext();
        const page = await context.newPage();
        await page.goto('https://example.com');
        await page.screenshot({ path: `example-${browserType}.png` });
        await browser.close();
    }
})();
```

Or if you are using Playwright Test, you can get `browserName` like below.
https://playwright.dev/docs/intro#using-test-fixtures
