### ISSUE TITLE
[Question] Is there any possibility for using TestingLibrary as a selector library?

### ISSUE THREAD

**Issue by swernerx** [microsoft/playwright#13317]
We used [TestingLibrary](https://testing-library.com) as a nice solution for querying our React application structure in Jest and Cypress. In a new project I'll switch to Playwright, and I am looking for ways of integrating this very ARIA-focused way of accessing elements.

**Comment by mxschmitt** [comment]
In what kind of selectors are you interested in? (We're currently investigating into role selectors)

**Comment by swernerx** [comment]
Effectively it would be nice to have it 1:1 in Playwright. Our priority would be aligned with what TestingLibrary itself recommends:

Queries Accessible to Everyone Queries that reflect the experience of visual/mouse users as well as those that use assistive technology.

- `getByRole`: This can be used to query every element that is exposed in the [accessibility tree](https://developer.mozilla.org/en-US/docs/Glossary/AOM). With the name option you can filter the returned elements by their [accessible name](https://www.w3.org/TR/accname-1.1/). This should be your top preference for just about everything. There's not much you can't get with this (if you can't, it's possible your UI is inaccessible). Most often, this will be used with the name option like so: getByRole('button', {name: /submit/i}). Check the [list of roles](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques#Roles).
- `getByLabelText`: This method is really good for form fields. When navigating through a website form, users find elements using label text. This method emulates that behavior, so it should be your top preference.
- `getByPlaceholderText`: [A placeholder is not a substitute for a label](https://www.nngroup.com/articles/form-design-placeholders/). But if that's all you have, then it's better than alternatives.
- `getByText`: Outside of forms, text content is the main way users find elements. This method can be used to find non-interactive elements (like divs, spans, and paragraphs).
- `getByDisplayValue`: The current value of a form element can be useful when navigating a page with filled-in values.
Semantic Queries HTML5 and ARIA compliant selectors. Note that the user experience of interacting with these attributes varies greatly across browsers and assistive technology.
- `getByAltText`: If your element is one which supports alt text (img, area, input, and any custom element), then you can use this to find that element.
- `getByTitle`: The title attribute is not consistently read by screenreaders, and is not visible by default for sighted users
Test IDs
- `getByTestId`: The user cannot see (or hear) these, so this is only recommended for cases where you can't match by role or text or it doesn't make sense (e.g. the text is dynamic).

(Via: https://testing-library.com/docs/queries/about#priority)

**Comment by swernerx** [comment]
BTW: It would be probably helpful to have a small section in the docs for users of testing library e.g. when you used X in TestingLibrary use Y in Playwright.

**Comment by mxschmitt** [comment]
Thank you! Might make sense to add a small table as you proposed for it.

**Comment by dgozman** [comment]
Thank you for this issue! It is important for Playwright to support various selector strategies, and you can see [in the docs](https://playwright.dev/docs/selectors) that there are quite a few already.

I don't think that Playwright will have 1:1 matching selectors with testing library. For example, we have `text=Foo` for text selectors, which is not exactly the same syntax as `getByText`. However, we should have solutions for all selectors supported by testing library.

Already supported today:
* `getByText` - this is `text=some value` and all [other variations](https://playwright.dev/docs/selectors#text-selector).
* `getByTestId` - this is supported already, e.g. `data-testid=some value`. See [docs](https://playwright.dev/docs/selectors#id-data-testid-data-test-id-data-test-selectors).
* `getByPlaceholderText` - so far, we haven't seen much interest in this one. It is easily replaced by css: `[placeholder="some value"]`. That said, we can do a separate selector engine if more interest arises.
* `getByAltText` - seems to be equivalent to  `[alt="some value"]`. However, I think that `role=img[name="some value"]` is even better.
* `getByTitle` - seems to be equivalent to  `[title="some value"]`, but `role=button[name="some value"]` seems like a better solution anyway.

In development:
* `getByRole` - see #11182.

Should be considered:
* `getByLabelText` - this just works out of the box, e.g. `await page.locator('text=My Label').fill('input value')` will correctly target the associated input. We need more docs about this though.
* `getByDisplayValue` - this one is interesting, but we'll need more usecases before implementing it.

Note that it should be totally possible to implement a [custom selector engine](https://playwright.dev/docs/extensibility#custom-selector-engines) that uses testing library under the hood if you really prefer that.

---

I see the following action items today:
- Add a guide aimed at those familiar with testing library selectors.
- Cover "target the label instead of a control" usecase in the docs.
