### ISSUE TITLE
[Question] Getting Access-Control-Allow-Origin for mocked request

### ISSUE THREAD

**Issue by MikeYermolayev** [microsoft/playwright#13384]
Hello 👋🏻 

I'm trying to run tests in GitLab Ci but seems like there are some CORS errors that fail my tests.
The fun fact is that the request to another domain is mocked and tests works totally OK in my local environment. They only fail in CI pipeline

<img width="533" alt="image" src="https://user-images.githubusercontent.com/8783498/162178794-98f7f665-ab1b-4a4c-83fa-688bba9f211b.png">
<img width="950" alt="image" src="https://user-images.githubusercontent.com/8783498/162178888-44be29f9-978b-4101-b813-4b6a08d689f2.png">

I'm attaching my trace, will it be enough?
[9d5758e8ebbe225c7167ea8d116752615ca3c65e.zip](https://github.com/microsoft/playwright/files/8441940/9d5758e8ebbe225c7167ea8d116752615ca3c65e.zip)

Thanks in advance for any tips

**Comment by mxschmitt** [comment]
I think Chromium has some special rules that if you are localhost and headful or something like that they don't error out for cors errors, but don't remember correctly.

In your scenario it makes sense that it's not working, because you are making a request from localhost:3000 to icanhelp.host. This out of the box does not, and only works if you set the Access-Control-Allow-Origin header.

Why does it not feel right? See [here](https://developer.mozilla.org/de/docs/Web/HTTP/CORS/Errors) that by default CORS requests are not allowed in the web.

**Comment by MikeYermolayev** [comment]
Yeah, CORS errors are completely understandable. I just got a bit confused since tests are passing on my local machine. I'm running them in headless mode and use localhost as gitlab CI/CD does

**Comment by mxschmitt** [comment]
Closing since it seems solved then! Localhost/headful is probably some exception made by Chromium under the hood for a better DX.
