### ISSUE TITLE
[BUG] Import from TSX does not work

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#13422]
Tracking issue:

- https://github.com/microsoft/playwright/issues/13265
- https://github.com/microsoft/playwright/issues/13389

**Comment by pavelfeldman** [comment]
That's by design, Playwright does not support import from TSX.

**Comment by tihuan** [comment]
@pavelfeldman 
Happy Friday! I'm currently experimenting porting our e2e tests from Jest to Playwright Test, and our e2e tests do import functions/constants/etc. from the component files (.tsx) in order to have single source of truth. 

Just curious about the rationale behind the design decision of not supporting import from TSX 🙏 Thanks so much!
