### ISSUE TITLE
[BUG] tracing screenshots do not match tracing snapshots

### ISSUE THREAD

**Issue by bpasero** [microsoft/playwright#13448]
**Context:**
- Playwright Version: 1.20.x
- Operating System: macOS
- Node.js version: 16.x
- Browser: Chromium

When you look at attached traces that has snapshots and screenshots you see that the screenshots do not add up to the actual snapshots:

[playwright-trace-1-should_update_color_of_the_tab.zip](https://github.com/microsoft/playwright/files/8456330/playwright-trace-1-should_update_color_of_the_tab.zip)

Screenshots stop somewhere here:

![image](https://user-images.githubusercontent.com/900690/162557977-de5bc7b4-6c71-4255-9bc3-8c39abef51cc.png)

Snapshots correctly go until here:

![image](https://user-images.githubusercontent.com/900690/162557982-2b759b8f-b252-4c2e-83c0-0a469dc515e1.png)

**Comment by pavelfeldman** [comment]
@bpasero those look like they are from completely different scenarios:
- snapshots are from the shell in editor + change color there (matches test name)
- screenshots are about JSON settings - completely separate test?

Screenshots have id system based on page id + ordinal. Let me see what happens if I start/stop tracing on the same page several times - we never do that, all our tests have a fresh context / page, so this clash never happens...

**Comment by bpasero** [comment]
Let me know if you figure something our or whether I should attach another trace.

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/commit/11f51455f212c4452ff8b0722f72f473053a868a
