### ISSUE TITLE
[BUG] Scrollable locator's screenshot is taken incorrectly on a chromium

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#13486]
**Context:**
- Playwright Version: 1.20.2
- Operating System: Mac
- Node.js version: 16.3.0
- Browser: Chromium

**Describe the bug**

I'm unable to provide a code snippet at the moment but I suspect to reproduce the element has to be higher than the current browser's viewport height.

Actual element vs. Playwright's screenshot

<img width="424" alt="Screenshot at Apr 09 23-22-32 (1)" src="https://user-images.githubusercontent.com/17873445/162817176-735bb127-eb40-4ce7-bc4f-76992bc5a5e6.png"> <img src="https://user-images.githubusercontent.com/17873445/162817234-4f8f44ea-4f4d-46ea-920d-d8371ae6bfff.png" width="250"/>

**Comment by aslushnikov** [comment]
> I'm unable to provide a code snippet at the moment but I suspect to reproduce the element has to be higher than the current browser's viewport height.

@MindaugasMateika we'd appreciate if you can help us with a snippet to reproduce this!

**Comment by MindaugasMateika** [comment]
Repro - https://github.com/MindaugasMateika/pw-screenshot-repro

But I'm not confident it will work as expected. In my use case, it reproduces in the german website under user authentication. I added all the steps but there's a chance you might catch Cloudflare captcha or something else which will break the test.

**Comment by osiux** [comment]
We stumbled upon something similar to this at work. We generate storyshots (screenshots from storybook stories) for several components, and we got an error happening on CircleCI (but not GH actions) where a screenshot taken on CircleCI was shorter than it should be. Did some experimentation and the only story that failed needed some scrolling because it was longer than others. It's not using a locator, just `page.screenshot({ fullPage: true, animations: 'disabled' })`

**Comment by PawelWesolowski** [comment]
I am experiencing  a similar problem. Getting it only on a branch where I am updating from Playwright v16 to 21.
The screenshot of a full page needs to resize window (or scroll? I am not sure how it is implemented in Playwright). It resizes correctly but it does not wait for my footer to placed at the bottom. Result is that on the screenshot the footer covers other elements. The area where the footer should be drawn exists but it is empty.

**Comment by dgozman** [comment]
This issue is similar to #12685. Please read [this comment](https://github.com/microsoft/playwright/issues/12685#issuecomment-1111102326) with an explanation and a workaround for full-page screenshots.

---

For element screenshots, unfortunately there is no guaranteed way to always capture the whole content of the element. Sometimes, resizing the page to be large enough makes enough room for the element to show all the content. However, that is not a given and depends on the page layout and css. Here is a workaround that tries to resize the page to be large enough:

```js
async function resizePageAndScreenshotLocator(locator) {
  const page = locator.page();
  const box = await locator.boundingBox();
  const originalSize = page.viewportSize();
  if (box.width > originalSize.width || box.height > originalSize.height)
    await page.setViewportSize(box);
  const screenshot = await locator.screenshot();
  await page.setViewportSize(originalSize);
  return screenshot;
}
```

**Comment by MindaugasMateika** [comment]
Thank you for the workaround at least :>

![dfa](https://user-images.githubusercontent.com/17873445/165988485-23b9987d-1a57-4ef0-a430-6f073840547d.jpg)

**Comment by MindaugasMateika** [comment]
Curious though, why does a full-page (scrollable) screenshot works just fine but it's not guaranteed that the scrollable locator's screenshot will work?

**Comment by dgozman** [comment]
Full-page screenshot guarantees that the whole document is captured, but it does not change the layout of the page. For some random element on the page to be fully visible, you might need to change the layout, for example drag the resizer to expand some list. In fact, many elements on a lot of pages just cannot be made fully visible, for example they are covered by some sticky header.
