### ISSUE TITLE
[Question] toMatchSnapshot to tests objects

### ISSUE THREAD

**Issue by diego-s-lopez** [microsoft/playwright#13545]
Hi there! I'm trying to use "toMatchSnapshot" to test an object, but i receive "TypeError: file.slice is not a function".
Is there a way to accomplish this? It would be great to have the hability to do this, like with Jest, https://jestjs.io/docs/snapshot-testing#property-matchers

Thanks!

``` javascript
const { test, expect } = require("@playwright/test");

test("basic test", async ({ page }) => {
  expect({ a: 1, b: "Test" }).toMatchSnapshot();
});

```

**Comment by aslushnikov** [comment]
@diego-s-lopez right now you'll need to do `JSON.stringify` first:

```js
const { test, expect } = require("@playwright/test");

test("basic test", async ({ page }) => {
  expect(JSON.stringify({ a: 1, b: "Test" })).toMatchSnapshot();
});
```

But that's a neat feature to have.

**Comment by diego-s-lopez** [comment]
Hi there, thanks for your response!
Is there a way to use the "toMatchSnapshot()" function from Jest library?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
