### ISSUE TITLE
[Feature] Add ability to play actions in traces

### ISSUE THREAD

**Issue by cat-ninja** [microsoft/playwright#13577]
We use recordings of the automation tests to help our support team and for new team members onboarding.
Traces fit greatly but it would be very cool if you guys can add an ability to play them like a video or a GIF.
Also, a setting for the playback speed can be very useful. And a pause button, obviously.

Currently, we use this snippet on the page to run the playback:
```js
(async function play() {
    const actions = document.querySelectorAll('.action-entry');
    for (const action of actions) {
       await new Promise(p => setTimeout(p, 3000));
       action.click();
    }
})();
```

**Comment by aslushnikov** [comment]
(Speculatively assigning 1.22 as this seems to be a fun feature to have)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
