### ISSUE TITLE
[Docs] Migrate selenium to playwright 

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright#13608]
Having docs for migrating from selenium to playwright and handling common scenarios would be helpful
some scenarios:
- interacting with nested iframe elements
- handling tests interacting with multiple tabs
- handling popup's
- executing js script inside a page

**Comment by jameskip** [comment]
Agreed. I think a lot of people are making this switch. Something similar to the migrating from protractor [docs](https://playwright.dev/docs/protractor).

**Comment by emakaay** [comment]
We are using page object model with cucumber. I would like to see an example how to pass the page object between different page object models and steps. I can't seem to get that 'right'

I'm reading documentation to use DI to inject pages, but struggle to understand what that means because multiple pages can exist in a Browser &Browsercontext objects. 

A migration documentation would certainly help.

Most examples on the internet use selenium driver

**Comment by gauravgandhi1315** [comment]
Is there any update on this?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
