### ISSUE TITLE
[BUG]: css filter property is not parsed correctly when taking screenshots

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/playwright#13605]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Mac/Windows
- Node.js version: 16.x
- Browser: All

**Code Snippet**

When using the locator's `screenshot` method:
```javascript
elementHandler.screenshot({
		path: snapshotPath,
		fullPage: true
	});
```
On an element with `filter` and `overflow: hidden`:
```html
<div style="padding: 20px; 
		    background: white;
		    border-radius: 6px;
		    overflow: hidden; 
		    filter: drop-shadow(rgba(0, 0, 0, 0.1) 0px 2px 8px) drop-shadow(rgba(0, 0, 0, 0.05) 0px 2px 4px) drop-shadow(rgba(0, 0, 0, 0.05) 0px 4px 2px);">This is my div!</div>
```
The screenshot does not contain the shadow.

Here's a screenshot taken with `overflow:hidden;`:
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/6459899/163805138-f50b8d5b-f632-4fb2-9a91-d361896b49a3.png">

Here's a screenshot taken without `overflow:hidden;`:
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/6459899/163805209-4fee4c5b-ff35-48e3-b69a-af24d6b964ba.png">

Here's a screenshot from a headful browser of the same code with `overflow: hidden;`:
<img width="1653" alt="image" src="https://user-images.githubusercontent.com/6459899/163805296-54c8df31-96be-4626-a4b9-f107a65dfb5f.png">

**Describe the bug**

This bug results in bad snapshot images when it comes to how the browser presents the shadow using a filter.

When using `box-shadow` it does show the shadow:
_Code:_ 
```html
<div style="padding: 20px;
		    background: white;
		    border-radius: 6px;
		    overflow: hidden;
		    box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.05), 0px 8px 8px rgba(0, 0, 0, 0.05), 0px 2px 16px rgba(0, 0, 0, 0.1);"
									>This is my div!</div>
```
_Snapshot:_
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/6459899/163805841-bcecff25-269c-46fd-a74b-5058d2ebd8a2.png">

**Comment by YonatanKra** [comment]
Digging deeper seems like a webkit issue

**Comment by YonatanKra** [comment]
Reopening it after farther testing. It seems like looking at the same page with `filter` and `overflow` on local Safari works but snapshot doesn't work as shown in the image.

**Comment by kylemh** [comment]
Another reproduction that's pretty easy is using create-next-app and running against that.

Webkit:
![desktop-landing-page-webkit-darwin](https://user-images.githubusercontent.com/9523719/212023565-18b3cd6f-30a8-4101-b79b-95a4f9676b72.png)

Chrome:
![desktop-landing-page-chromium-darwin](https://user-images.githubusercontent.com/9523719/212023582-0284feb6-d62f-41c1-91d6-1501699a691e.png)

**Comment by affilnost** [comment]
Another case when css filter property is not parsed correctly (Safari):

```
<style>
  .myelement {
    height: 300px;
    background: red;
    -webkit-backdrop-filter: blur(1px);
    transform: translate3d(0, 0, 0);
    filter: invert(100%);
  }
</style>
<div class="myelement"></div>
```

Screenshot taken has red color (blue expected since `invert(100%)` filter is applied)

If we remove `-webkit-backdrop-filter` and `transform` css properties - it starts working correctly: screenshot taken has blue color (as expected).

It looks like `-webkit-backdrop-filter` and `transform` properties make `filter` not to be parsed correctly.

Tested with Playwright: 1.31.2, Node: 16.18.1, Mac.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
