### ISSUE TITLE
[metabug] msedge does not start with special enterprise policies and leads in a timeout

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#13631]
List of issues:

- https://github.com/microsoft/playwright/issues/13482
- https://github.com/microsoft/playwright/issues/13553
- https://github.com/microsoft/playwright-python/issues/1270

Current state:

- On Windows Edge / Chrome launching ends up in a timeout
- Our suspicion are enterprise policies

To be clarified:

- Is Chromium affected as well or only Chrome & Edge
- Which CDP call hangs and where it hangs

How to debug for affected users?

- Print the `chrome://policy` contents
- Start the msedge/chrome browser with the `DEBUG=pw:browser,pw:protocol,pw:api` environment variable and provide us the logs

**Comment by EightEggs** [comment]
![image](https://user-images.githubusercontent.com/72812416/164353238-5c6e3490-e459-49b0-a3d0-f61637374ef8.png)

It seems there is no policy with my Edge...

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
