### ISSUE TITLE
[Feature] Global setup to be able to reference playwright config projects information

### ISSUE THREAD

**Issue by TheChosenQA** [microsoft/playwright#13648]
I think it would be very beneficial to have the ability to be able to reference the current playwright config project information that is being executed via the global setup / teardown files.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
