### ISSUE TITLE
[Feature] Make all reporter functions asynchronous

### ISSUE THREAD

**Issue by AnnaSChabanova** [microsoft/playwright#13704]
Hi, team!
I wanna make an asynchronous custom reporter for my test management system.

**In my head it looks like this:**
`onBegin` reporter function - create an automation run
`onTestBegin` - create a test suite if it doesn't exist and create a run for the current test case
`onTestEnd` - post result for the test case

**Why:** it allows us to get results as soon as possible during regression and start analyzing failures without waiting until the run ends.

As I can see only `onEnd` function can return Promise, so I can't implement my approach.
Thanks!

Could be related to this issue #7343

**Comment by yury-s** [comment]
Inside your custom reporter you can chain promises from `onTestBegin` and `onTestEnd` so that the test suite is guaranteed to be created before its results are posted. You put all asynchronous actions into an array and then return Promise.all of that array from `onEnd` which will ensure that the runner waits for all your actions to complete before finishing the run.

Closing this request as we are not planning to change the methods to async.
