### ISSUE TITLE
[Feature] Add Cancel highlight API

### ISSUE THREAD

**Issue by luxuncang** [microsoft/playwright#13728]
Add Cancel highlight API

```
page.locator('#SomeID').highlight() #highlight
page.locator('#SomeID').removehighlight() #removehighlight
```

**Comment by pavelfeldman** [comment]
I'd rather be `page.hideHighlight` - no matter which selector was highlighted.

**Comment by pavelfeldman** [comment]
Would you be willing to contribute a patch?

**Comment by luxuncang** [comment]
> 你愿意贡献一个补丁吗？

I'd love to contribute, but I'm not familiar with Typescript.

**Comment by pavelfeldman** [comment]
Let's then wait for someone to pick it up!

**Comment by tmerse** [comment]
Until there is a better solution, a temporary hack could be:

```
const clearHighlights = async (page: Page): Promise<void> => {
  const highlights = page.locator("x-pw-glass");
  await highlights.evaluateAll((highlight) =>
    highlight.map((element) => {
      element.parentNode?.removeChild(element);
    })
  );
};

// ...some code

await clearHighlights(page)
```

if you want a js-only solution

```
const clearHighlights = async (page) => {
  const highlights = page.locator("x-pw-glass");
  await highlights.evaluateAll((highlight) =>
    highlight.map((element) => {
      element.parentNode.removeChild(element);
    })
  );
};

// ...some code

await clearHighlights(page)
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
