### ISSUE TITLE
[Feature] Ship docker image with dependencies to view headed browser

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#13729]
Official Docker images are shipped with `xvfb` to run headed browsers ([reference](https://playwright.dev/docs/ci#running-headed)) but it is not possible to see the browsers and follow test execution.

It would be helpful if the images are also shipped with `novnc` or similar dependency allowing to see the headed browser and test execution.

**Comment by rwoll** [comment]
Relates https://github.com/microsoft/playwright/pull/10260

**Comment by 1234Brian** [comment]
👍

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
