### ISSUE TITLE
[BUG] route.continue cannot remove origin header in WebKit

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#13886]
It is possible to set it to a new value but not to delete in WebKit. This was originally discovered in #13106

**Comment by 1234Brian** [comment]
👍

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
