### ISSUE TITLE
[Question] Is there a way to define global variables that is accessible anywhere in the project? 

### ISSUE THREAD

**Issue by autTestUser** [microsoft/playwright#13959]
Protractor framework provides something like browser.params.key which can be declared and assigned value and can be accessed anywhere in the project. Is there a similar solution in Playwright as well?

**Comment by autTestUser** [comment]
What if I want to change this value somewhere inside a function and the current changed value should be available for me everywhere?

**Comment by autTestUser** [comment]
For example, I might change a variable in onTestBegin every time or for each test and I want that current value somewhere else in the project. For some unknown reason, env variable is also not working for me. I added this value to process.env.Variable and later I'm trying to read it and it is not available.

**Comment by mxschmitt** [comment]
It's not recommended to share variables with other tests which change the value. Why? Because this makes test depend on each-other. If you have some tests which depend on each-other, then we recommend [test.describe.serial](https://playwright.dev/docs/next/api/class-test#test-describe-serial). Also keep in mind that if a test fails between your series when not using test.describe.serial the worker will restart, so the previous value will be reset. See here to learn more about worker restarts: https://playwright.dev/docs/next/test-parallel

**Comment by autTestUser** [comment]
Actually, I'm just trying to get the full name (test.title + test.parent.title ) in onTestBegin for the current running test to use later in my reports. It is not being passed from one test to another or there is no dependency as such.

**Comment by mxschmitt** [comment]
Sounds like creating a custom reporter for your scenario would fit better? https://playwright.dev/docs/test-reporters#custom-reporters

**Comment by autTestUser** [comment]
I have custom reporter. I'm already using **onTestBegin**  as mentioned earlier. All I'm saying is "I'm trying to assign a string variable a value of test.title + test.parent.title" . This variable is somehow getting the value of undefined later on when I use it somewhere else during execution of test. Instead of some variable, I have even tried to assign value to process.env.Variable in **onTestBegin** and later tried to use it, but getting the value as undefined. 

Actually, the main thing I'm trying to do is, whenever a test fails, I'll try to take a screenshot with page.screenshot() function. I'm trying to name this screenshot file with test.title + test.parent.title so that it would have the test as well as suite name. I'm able to get a test name anywhere I need with **testInfo.title**, but I want to get Suite name as well.

**Comment by dgozman** [comment]
- You cannot set variables in the reporter and read them in the test. The communication is the other way - from the test to the reporter. They even run in different processes, asynchronously against each other.
- To get the full title, use [`TestInfo.titlePath`](https://playwright.dev/docs/api/class-testinfo#test-info-title-path) in the test/fixutre/hook and [`TestCase.titlePath()`](https://playwright.dev/docs/api/class-testcase#test-case-title-path) in the reporter.
- For your particular usecase, take a look at the [`screenshot` config option](https://playwright.dev/docs/test-configuration#automatic-screenshots).
- Alternatively, something like this should work:
```js
test.extend({
  screenshotOnFailure: [async({ page }, use, testInfo) => {
    await use();
    if (testInfo.status !== testInfo.expectedStatus)
      await page.screenshot({ path: testInfo.titlePath.join('-'), timeout: 5000 });
  }, { auto: true }]
})
```

**Comment by autTestUser** [comment]
I only needed the full title, which I'm able to get with testInfo.titlePath. My requirement is fulfilled.

**Comment by Kolobamanacas** [comment]
@mxschmitt Sorry for bringing resolved topic back, but I can't find best practices for the particular scenario. I have a services which I start in `globalSetup`, which generates a string. There is no way to know the string in advance and pre-generate it. The string is constant for duration of all run tests and I wish to share it among all tests. What do I do in cases like this? How to share code, generated within `globalSetup` file with all the tests?

**Comment by mxschmitt** [comment]
process.env.YOUR_STRING = "foo" and then you can read it like that.

**Comment by wirmoreno** [comment]
I'm sorry to reopen this discussion, but when I use `process.env.YOUR_STRING = "foo"` and then, I try to access it from any test file, it says that the type of the variable in 'undefined': Type 'undefined' is not assignable to type 'String'

I cannot do something like this
`myDict[process.env.YOUR_STRING]`

I'm aware that I can do it to solve the problem:
`let myStringKey:string = process.env.LANG!;`
Then...
`myDict[myStringKey]`

But I'll need to do it in all test files, I'm trying to get a way to do it only once in the global-setup file, and then access it from anywhere in a shorthand variable.

Do you know how can I solve it in order to directly access the environment variable?
Also, it would be really helpful if I can use a shorthand name for the `process.env.YOUR_STRING`.
Insteado of using `myDict[process.env.YOUR_STRING]`, I would like to use `myDict[YOUR_STRING]`, some sort of shorthand way to get a global or environment variable?

Is there a way to solve it?

**Comment by mulder1628** [comment]
> I'm sorry to reopen this discussion, but when I use `process.env.YOUR_STRING = "foo"` and then, I try to access it from any test file, it says that the type of the variable in 'undefined': Type 'undefined' is not assignable to type 'String'
> 
> I cannot do something like this `myDict[process.env.YOUR_STRING]`
> 
> I'm aware that I can do it to solve the problem: `let myStringKey:string = process.env.LANG!;` Then... `myDict[myStringKey]`
> 
> But I'll need to do it in all test files, I'm trying to get a way to do it only once in the global-setup file, and then access it from anywhere in a shorthand variable.
> 
> Do you know how can I solve it in order to directly access the environment variable? Also, it would be really helpful if I can use a shorthand name for the `process.env.YOUR_STRING`. Insteado of using `myDict[process.env.YOUR_STRING]`, I would like to use `myDict[YOUR_STRING]`, some sort of shorthand way to get a global or environment variable?
> 
> Is there a way to solve it?

I believe @mxschmitt meant this: 
https://playwright.dev/docs/test-global-setup-teardown#option-2-configure-globalsetup-and-globalteardown

You set this in global-setup.ts.
