### ISSUE TITLE
[BUG] Select options not visible in Video

### ISSUE THREAD

**Issue by brettwinters** [microsoft/playwright#13994]
I have an requirement where I need to see the contents (i.e. the `option`s) of a `select` in **video**. 

```c#
await Page.ClickAsync("#mySelect");
await Page.WaitForTimeoutAsync(2000);
```

When I run test with `Headless = false`, I can see the `select` open and its options. But in the video, the select gets focus when it's clicked, but options are invisible. (i.e. 'select' remains closed)

When I manually toggle the select down it also doesn't show in the video. Which makes me wonder what's going on...

Note: No issues setting the select value using `Page.SelectOptionAsync`.

----------------------------------------------------------------
- Playwright Version: 1.21.0
- Operating System: Windows
- Browser: Chromium

**Comment by dgozman** [comment]
@brettwinters That's because selects are technically separate OS windows from the page. That's indeed a problem.

**Comment by brettwinters** [comment]
@dgozman thanks for your quick reply! 

I wasn't aware of this separation. This could also explain why I also can't seem to get `await Page.ClickAsync("#mySelect option:text-is('One')")` working either. Could you send me a link to where it's discussed?

It sounds like a major problem that can't be fixed quickly. That's what P3 means, right? 

Is there a workaround in the meantime?

**Comment by dgozman** [comment]
@brettwinters For selecting options, use [`SelectOptionAsync()`](https://playwright.dev/dotnet/docs/api/class-locator#locator-select-option) instead.

> It sounds like a major problem that can't be fixed quickly. That's what P3 means, right?

Yep.

> Is there a workaround in the meantime?

Unfortunately, there's no workaround for capturing selects on the video for now. You can try recording the whole screen with some external tool though.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
