### ISSUE TITLE
[Feature] Is there any plan to suport UI automation with WSL2 environment?

### ISSUE THREAD

**Issue by SilenceHe** [microsoft/playwright#13995]
Fow now, I'm trying to do UI automation with playwright-python on Win OS WSL2 environment, but when I try to run testcases with cmd: `pytest --headed`, it throws exception and shows "**Looks like you launched a headed browser without having a XServer running**", is there any plan to reuse local windows os browser's UI for UI automation on WSL2? if so, I will not need to do extra setting or install process, like XServer...

**see exception like below:**
![Snipaste_2022-05-06_23-12-25](https://user-images.githubusercontent.com/4414171/167161613-37c84490-08b2-4c18-8559-6aa9039eb70a.png)

**Comment by mxschmitt** [comment]
Playwright has no control on how a browser (chromium, firefox, webkit) launches its headed session - thats what the browser decides which xserver it uses. Seems like that Chromium does not work under WSL2 to expose its headed instance over to the Windows system.

I'll mark it as p3 for now to see how many people are interested in such a use-case.

**Comment by ltsuda** [comment]
Just adding my two cents here:

If using Windows 11, running playwright headed should open the browser present in the WSL2 environment because of WSLg (https://github.com/microsoft/wslg?msclkid=474d0e01cfb711ecab9448c0ffc4d5b6)

In Windows 10/WSL2, this package should work similar to the item above:
https://opticos.github.io/gwsl/?msclkid=49615e26cfb711eca0e50a8350f199e3

**Comment by mxschmitt** [comment]
Closing as per above.
