### ISSUE TITLE
[Feature] Show number of matching elements within Inspector

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#14017]
Hello, 

When I am using the Explorer within the Inspector tool I would like to see how many matching elements I have on the web page (as a number) . 

Right now after I type some xpath locator the matched elements are highlighted within the Web page, but this way does not show very clearly how many elements are matched with the expression. 

Playwright rocks, keep it going!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
