### ISSUE TITLE
[BUG] SharedArrayBuffer should work in WebKit

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#14043]
This popped up in https://github.com/microsoft/playwright/pull/13976, SharedArrayBuffer was reenabled in Safari https://webkit.org/blog/12140/new-webkit-features-in-safari-15-2/ but we disabled COOP handling in https://github.com/microsoft/playwright/pull/9185 as it broke some other functionality in WebKit. We should reenable COOP to match Safari and make SharedArrayBuffer work.

**Comment by tadd** [comment]
Hi all, thanks for the great tool. 

Why has this issue stopped for almost half a year? I don't think there is a major barrier since the fix is to undo one line, making it behave the same as the current real Safari.

My problem is not with `SharedArrayBuffer` but with `performance.now`; however, I think that the root cause is the same and lies in this issue.

Since developing a cross-browser JS library, I have been using Playwright and `performance.now` to detect performance degradation with all multiple engines. (This is not a serious performance measurement but a part of CI.) However, the time resolution is currently fixed at 1 second with plain Playwright. Then I have been waiting several months, with almost no possibility of checking for degradation with WebKit.

I have confirmed the problem was mitigated by the proper use of COOP/COEP on two other engines. I wish to be corrected to the same status as the others.

**Comment by tadd** [comment]
After a while, I realized that my measurement approach was fundamentally wrong.

I had called `performance.now()` within `page.evaluate(() => {...})`. But as a policy, to begin with, I think it was a mistake to make the accuracy of the data dependent on the observed objects. The responsibility should be on the observer, i.e., my code on the Node.js/Playwright side.

Through some trial and error, my problem is solved because I have found several ways independent of the browser's time resolution. Therefore, I am no longer in a hurry about this issue.

In any case, I think it is not desirable to behave differently from plain Safari, so I would appreciate it if you continued to consider fixing this problem.

**Comment by tadd** [comment]
A while ago, I realized I was fundamentally wrong about another thing. Not only had I checked the behavior at hand, but I also believed that the patch in browser_patches/webkit was up to date when I wrote [my first comment here](#issuecomment-1287827659) .

That was a mistake. The browser patch has been closed/proprietary since last August. #16845 #17556

Here is what I want to believe next.
> "Microsoft loves open source"
> Judge us by the actions we have taken in the recent past, our actions today and in the future
https://pulse.microsoft.com/nl-nl/transform-nl-nl/na/fa1-microsoft-loves-open-source/

**Comment by SamVerschueren** [comment]
Are there any plans to re-enabling SABs in WebKit? I'm looking at migrating from Puppeteer to Playwright because Playwright supports WebKit, and it doesn't look like WebKit support is coming anytime soon in Puppeteer. But at [StackBlitz](https://stackblitz.com/), we heavily rely on SABs.

**Comment by eatsjobs** [comment]
Hi! Just wanna ask if there's any chance to have this sooner or later. :) @yury-s

**Comment by swissspidy** [comment]
Is there any update on this?

**Comment by swissspidy** [comment]
Starting with Playwright 1.43.0, WebKit now seems to immediately crash when opening a page with cross-origin isolation enabled. Before that, the page could at least be opened and was functioning.

**Comment by IbrahimCSAE** [comment]
is this any updates on this? we are considering using playwright over at OHIF and CornerstoneJS.

**Comment by eatsjobs** [comment]
So it's possible to have crossOrigin in webkit from 1.46.1?

**Comment by swissspidy** [comment]
If you mean cross-origin isolation, then yes.

**Comment by eatsjobs** [comment]
For future readers: to enable crossOriginIsolation and SharedArrayBuffer also in workers I had to also force some configurations

```ts
import type { LaunchOptions, PlaywrightTestConfig } from "@playwright/test";
import { defineConfig, devices } from "@playwright/test";
import { baseURL } from "./constants";

import "dotenv/config";
import { isCI, isDebug, withCrossOriginIsolation } from "./env";

import type { TestOptions } from "./fixtures";

const serveCommand = withCrossOriginIsolation() ? "npm run serve" : "npm run serve-no-cross-origin-isolated";

const commonLaunchOptions: LaunchOptions = {
  devtools: isDebug(),
  slowMo: isDebug() ? 1000 : 0,
};

// Base launch options that are always needed
const commonLaunchOptionsArgs: LaunchOptions["args"] = [
  "--allow-file-access-from-files",
  "--disable-translate",
  "--mute-audio",
  "--use-fake-device-for-media-stream",
  "--use-fake-ui-for-media-stream",
  "--disable-dev-shm-usage",
];

// Add SharedArrayBuffer specific args only when needed
if (isWebAssemblyPthreadsBuild()) {
  commonLaunchOptionsArgs.push(
    "--enable-features=SharedArrayBuffer",
    "--disable-site-isolation-trials"
  );
}

const headless = !isCI();
const ignoreHTTPSErrors = true;
const bypassCSP = true;
let workers = undefined;

if (isCI() && withCrossOriginIsolation()) {
  workers = 1;
} else if (isCI()) {
  workers = 3;
}

const config: PlaywrightTestConfig<TestOptions> = {
  testDir: "./modules",
  retries: isCI() ? 4 : 0,
  workers: workers,
  fullyParallel: true,
  forbidOnly: isCI(),
  timeout: 60000,
  expect: {
    timeout: 10000,
  },
  reporter: [["list"], isCI() ? ["blob"] : ["html", { open: "always" }]],
  projects: [
    {
      name: "chromium",
      use: {
        headless,
        ignoreHTTPSErrors,
        bypassCSP,
        ...devices["Pixel 7"],
        launchOptions: {
          args: [...commonLaunchOptionsArgs],
          ...commonLaunchOptions,
        },
      },
    },
  ],
  webServer: {
    command: serveCommand,
    port: Number.parseInt(new URL(baseURL).port, 10),
    reuseExistingServer: !isCI(),
  },
  use: {
    trace: "on-first-retry",
    baseURL,
  },
};

// when emulating firefox seems we cannot
// redefine getUserMedia function
const fireFoxDevice = {
  ...devices["Desktop Firefox"],
  userAgent: devices["Pixel 7"].userAgent,
  viewport: {
    ...devices["Pixel 7"].viewport,
  },
};

config.projects?.push({
  name: "firefox",
  use: {
    headless,
    ignoreHTTPSErrors,
    bypassCSP,
    ...fireFoxDevice,
    launchOptions: {
      firefoxUserPrefs: {
        "media.navigator.streams.fake": true,
        "media.navigator.permission.disabled": true,
        "javascript.options.shared_memory": isWebAssemblyPthreadsBuild(),
        "dom.postMessage.sharedArrayBuffer.bypassCOOP_COEP.insecure.enabled": isWebAssemblyPthreadsBuild()
      },
      ...commonLaunchOptions,
    },
  },
});

config.projects?.push({
  name: "webkit",
  use: {
    headless,
    ignoreHTTPSErrors,
    bypassCSP,
    ...devices["iPhone 13"],
    ...(isWebAssemblyPthreadsBuild() && {
      launchOptions: {
        args: ['--enable-features=SharedArrayBuffer'],
      },
      contextOptions: {
        serviceWorkers: 'block'
      }
    })
  },
});

export default defineConfig(config);
```

and the server config to be

```
{
  "headers": [
    {
      "source": "**/*.*",
      "headers": [
        {
          "key": "Cache-Control",
          "value": "max-age=1"
        },
        {
          "key": "Cross-Origin-Opener-Policy",
          "value": "same-origin"
        },
        {
          "key": "Cross-Origin-Embedder-Policy",
          "value": "credentialless"
        },
        {
          "key": "Cross-Origin-Resource-Policy",
          "value": "cross-origin"
        }
      ]
    }
  ]
}
```
