### ISSUE TITLE
[Question]Why can't get the electron application window when using AppImage

### ISSUE THREAD

**Issue by dming4** [microsoft/playwright#14088]
**1. using main.js**
const electronApp = await electron.launch({ args: ['main.js'] });
const window = await electronApp.firstWindow();
The above code can start electron app normally and the window can return back normal.

**2. using AppImage**
const electronApp = await electron.launch({ executablePath: ’xxx.AppImage‘ });
const winCount=electronApp.windows().length;
const window = await electronApp.firstWindow();
The above code can start electron app normally, but can't get the window, and i the winCount variable is 0.

So I'm a little confused why can't get the window with AppImage？

**Comment by dming4** [comment]
@mxschmitt, is this the playwright api issue?

**Comment by dming4** [comment]
os: ubuntu 16.04 LTS

**Comment by mxschmitt** [comment]
> @mxschmitt, is this the playwright api issue?

We don't officially support it, so we marked it as p3 to wait if multiple users are interested in supporting it. If this is a Playwright issue - we don't know. Since I don't know what AppImage is.

**Comment by dming4** [comment]
Got it, thanks your reply @mxschmitt

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
