### ISSUE TITLE
[Feature] Update viewportSize when window gets resized

### ISSUE THREAD

**Issue by akblissweb** [microsoft/playwright#14091]
**Context:**
- Playwright Version: 1.17.3
- Operating System: Windows
- .NET version: 6
- Browser: Firefox
- Extra: NUnit

I have opened a second window and resized it with  resizeTo(100,100)

I can put in a delay and see that the resizing is working correctly 

When I look at the Viewport Size for the first and the second window they both show 1280x720

I would have expected the second window to report a size of 100x100

**Comment by akblissweb** [comment]
Makes sense.   What level of effort would be required to implement ?  and what parts of the code should I look at if I wish to attempt to implement this feature  ?

**Comment by davidgilbertson** [comment]
I have a site that resizes content with JavaScript when I resize the window (manually, using the mouse). When loaded with Playwright, the content doesn't resize. Is that the same issue as this? I assume it's the resize event not firing.

Is there a workaround? I have tried various browsers and even `executable_path` but none of them work.

**Comment by masonmark** [comment]
> Is there a workaround?

@davidgilbertson The only workaround I have found is to use `'webkit'` (apparently because WebKit doesn't itself support resizing the window without resizing the viewport).

I can see how resizing the window without resizing the viewport might be useful in a lot of E2E test contexts, but this is a problem for us too in some automation scenarios, so I would also really like to see some way to disable this feature in the Playwright config (and make it behave like a normal browser, resizing the viewport whenever the window itself is resized ).

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
