### ISSUE TITLE
[Question] Is there a way to group console logs via playwright Reporter?

### ISSUE THREAD

**Issue by aolanrewaju** [microsoft/playwright#14107]
Hello, I am trying to find a way to group all the console logs that come from a test suite so that they are labeled and print together in the console. I figured an easy way would be by using the reporter classes playwright already provides and just overriding onStdOut(). The issue is I'm unable to find a way to access these reporter classes in order to extend them and tweak them to my liking.

Is there any way to achieve this functionality or any advice on how to group console log? Thanks!

**Comment by rwoll** [comment]
The built-in reporters are not exposed in a way that allows for idiomatic extension programmatically. However, you can try:

1. Writing your own reporter: https://playwright.dev/docs/next/test-reporters#custom-reporters
2. Use the built-in HTML Reporter which will include per-test stderr/stdout as an attachment per-test.

Do one of those work for you? Can you elaborate more on your use case/workflow? Since Playwright Test is intended to run multiple tests in parallel, if you print in realtime to the console, it'll look interleaved. (However, the HTMl Report and others will have it all separated per-test for viewing after the fact.)

**Comment by rwoll** [comment]
Closing per above suggested workarounds. Feel free to comment/re-open if further follow-up is needed.
