### ISSUE TITLE
[Feature] page.queryobjects API from puppeteer

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#14134]
We're looking to automate memory leak detection using playwright. I see that puppeteer has a pattern using the page.queryobjects API.

It would be great if playwright users had access to this API even if it was only able on chrome.

Technique: https://media-codings.com/articles/automatically-detect-memory-leaks-with-puppeteer

RFE From Puppeteer: https://github.com/puppeteer/puppeteer/issues/304

**Comment by unlikelyzero** [comment]
@aslushnikov would this be straightforward to add? I saw that you made the original implementation in puppeteer!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by Alexander-Taran** [comment]
We do have a nice test suite using playwright.
Now when we hunt for memory leaks using [fuite](https://github.com/nolanlawson/fuite) we have to rewrite the test suite for puppeteer.
The dream: reuse existing test suite for playwright with fuite.
