### ISSUE TITLE
[Feature]  page.waitForLoadState extendable networkidle

### ISSUE THREAD

**Issue by rolandz83** [microsoft/playwright#14132]
Hey guys,
I have an use case for an extended networkidle, during a page load many times especially on slow responding servers scripts don't load in a timely manner and we have waterfall as below.

![image](https://user-images.githubusercontent.com/78881730/168154238-13a19ac3-fb3a-4721-a4a3-e90543bd3094.png)

here page.waitForLoadState('networkidle'); waits for 1.2 sec (which includes the default no network connections for at least 500 ms.) as it should but then more activity happens after that and test continues while the page is still loading inadvertently failing the test as it tries to read data fields that haven't been loaded yet.
We could use waitForResponse and point to the last call in some cases however if we had a way to extend networkidle I think it would be an useful feature to have.

Let me know what you think ? Thanks a lot.

**Comment by rwoll** [comment]
Label added to collect feedback. However, since `networkidle` is generally going to be flaky and actions auto-wait, it's unlikely we'd add this functionality.

You have a few options:
1. if you're immediatly clicking on something after this wait, just drop the waitForLoadState, and do something along the lines of:  `page.click('<element that will appear when the network is fully loaded>').click({ timeout: 1500 })`
2. use waitForResponse as you mention to wait on a specific response: https://playwright.dev/docs/next/api/class-page#page-wait-for-response
3. Implement a custom network idle check on top of page.route('**/*', () => {…})

**Comment by rwoll** [comment]
Folding into https://github.com/microsoft/playwright/issues/7856
