### ISSUE TITLE
[Feature] Built-in Angular selector engine

### ISSUE THREAD

**Issue by vitalics** [microsoft/playwright#14158]
As for [React/Vue](https://playwright.dev/docs/selectors#react-selectors) Selectors. I would like to propose selectors for angular, since Angular has a [dev tools](https://angular.io/guide/devtools) which can help to debug angular applications

### Match by component
`_angular=app-root` - Finds app-root angular element

### Match by component property

- case sensetive
`_angular=[title = "Steven King"]`
- case insensetive
`_angular=[title = "steven king" i]`

### Partial property matching (prefix/suffix):
`_angular=my-app[title $= "Steven"]` - suffix
`_angular=my-app[title ^= "Steven"]` - prefix

Devtools Example
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/8816260/168413671-9b287890-90fd-4522-9e8e-3358fed3a659.png">

``` ts
await page.locator('_angular=app-button').click();
await page.locator('_angular=app-root[title=my-app]');
```

**Comment by vitalics** [comment]
In addition. I assume that this propose can be difficult, so my suggesion to move propose to 1.24+ version. Or less, if someone has been develop such engine and covered by tests. 

I think when angular selectors is more complex  than you think at first glance, since angular is not attach at DOM as a react/vue via simple API like `mount/render` function. The possible issue here is about testing.

**Comment by vitalics** [comment]
Close this issue, as playwright team mentioned - they are not ready to implement such selectors. So Based on attached PR, custom engine is available by link: https://github.com/vitalics/playwright-angular-selectors

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
