### ISSUE TITLE
[Feature] playwright.request creates a new connection per request

### ISSUE THREAD

**Issue by tzbo** [microsoft/playwright#14155]
playwright.request is a very useful utility. But it creates a new connection per request. [Got](https://github.com/sindresorhus/got) exposes interface to create keep-alive agent. Can playwright as well?

**Comment by jvi-infare** [comment]
Hi @tzbo 

I think it's because Playwright's APIRequestContext is based on NodeJS HTTP agent which doesn't keep connection alive. I made some modifications on Playwright's side to use hpagent and now connection is being kept alive.

**Comment by tzbo** [comment]
That will be a greate feature. Thanks.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
