### ISSUE TITLE
[Feature] API tests codegen from swagger

### ISSUE THREAD

**Issue by szamacz** [microsoft/playwright#14171]
There are tools that allow to generation API clients, models, stubs and tests based on swagger documentation, ex [swagger Axios codegen](https://www.npmjs.com/package/swagger-axios-codegen). It would be great to add the ability to generate such things for the playwright.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
