### ISSUE TITLE
[Feature] Trace viewer: Detect local traces and list them in the UI

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [microsoft/playwright#14199]
I think it's a bit cumbersome to have to copy/paste the path to the zip file.

Personally, the way I would want it to behave is:
- No arguments: Look for traces in `test-results` and if there are any, they are listed in the main window. (Above the already existing manual file picker.)
- With argument: If the argument provided is a directory, same behavior as described above but using that directory instead of `test-results`.

That way, regardless of which test failed, the trace can be viewed using the same command, making the tool just a hint more accessible.

**Comment by rwoll** [comment]
Thanks for the suggestion! This is a great idea.

For the time-being, as a workaround/alternate flow, if you're using the [built-in HTML Reporter](https://playwright.dev/docs/test-reporters#html-reporter), if a test has an associated trace, it shows up as a link when you click on the test which can then open the trace-view for that specific test/run.

**Comment by s-h-a-d-o-w** [comment]
Thanks for mentioning that alternative! For one-off runs if something fails on CI, that definitely seems like a decent workflow.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
