### ISSUE TITLE
Adding a link to a text is not working using playwright

### ISSUE THREAD

**Issue by kdwlprerna** [microsoft/playwright#14205]
I am trying to add a link to a text, which makes it clickable and when clicked goes to the added link. I have used below code to achieve the same : 
        await this.page.locator('[title="Link"]').click();
        await this.page.fill('[name="link"]', 'https://www.google.com'); //set link
        await this.page.click('button:has-text("Apply")');

This code adds a link to the text but when I click on the link it redirects me to the same page rather than the expected url (which is google.com here)

Question is, is it supported on playwright? Or is there any issue with the above code block?

Please refer attached screenshot for your reference:-

<img width="754" alt="Screen Shot 2022-05-17 at 9 50 07 am" src="https://user-images.githubusercontent.com/102934575/168700655-997eb66f-a3d1-4fb4-bb03-b8ebf5561439.png">

**Comment by gauravgandhi1315** [comment]
i don't think you can add a link. to the text using Playwright. `page.fill` is used to add data to the text field, not to actually change the link to a text.

**Comment by rwoll** [comment]
Generally speaking, if you can interact with your Web App's UI manually in the browser, Playwright can do it, too. How specifically, will depend on how your UI is implemented. 

There's nothing inherently wrong with the code you've included, but without seeing the implementation of the UI that you've screenshotted, I'm unable to provide more precise help.

You can try:

```
$ npx playwright codegen <your site>
```

to generate the Playwright code or using the [debugging tools](https://playwright.dev/docs/debug) to inspect what's going on.

**Comment by kdwlprerna** [comment]
> Generally speaking, if you can interact with your Web App's UI manually in the browser, Playwright can do it, too. How specifically, will depend on how your UI is implemented.
> 
> There's nothing inherently wrong with the code you've included, but without seeing the implementation of the UI that you've screenshotted, I'm unable to provide more precise help.
> 
> You can try:
> 
> ```
> $ npx playwright codegen <your site>
> ```
> 
> to generate the Playwright code or using the [debugging tools](https://playwright.dev/docs/debug) to inspect what's going on.

Tried generating the code using codegen and then using the generated code in the script. But it dint work.

**Comment by rwoll** [comment]
Can you share a link to the site you are testing? The image in the description is not enough for us to debug as the page can be implemented in a variety of ways. Thanks!

**Comment by kdwlprerna** [comment]
> Can you share a link to the site you are testing? The image in the description is not enough for us to debug as the page can be implemented in a variety of ways. Thanks!

Please check this URL - https://easy-email-m-ryan.vercel.app/editor?id=977

**Comment by rwoll** [comment]
Thanks! The following works for me, BUT using `waitForTimeout` is not recommended. The app you've linked is sufficiently complicated that it's unlikely for me to understand where the suspected race is.

```ts
import { test, expect } from '@playwright/test';

test('it works', async ({ page }) => {
  await page.goto('https://easy-email-m-ryan.vercel.app/editor?id=977');
  await page.locator('text=Make it easy for everyone').nth(0).click();
  await page.locator('[title="Link"]').click();
  await page.waitForTimeout(500); // BAD: Don't do this. It's an anti-pattern and subject to flakiness
  await page.locator('[name="link"]').fill('https://example.com');
  await page.waitForTimeout(500); // BAD: Don't do this. It's an anti-pattern and subject to flakiness
  await page.locator('button:has-text("Apply")').click();
  await page.waitForTimeout(500); // BAD: Don't do this. It's an anti-pattern and subject to flakiness
  await page.locator('button', { has: page.locator('.icon-desktop') }).click();
  const [newPage] = await Promise.all([
    page.waitForEvent('popup'),
    page.locator('text=Make it easy for everyone to compose emails!').nth(1).click(),
  ]);
  await expect(newPage).toHaveURL('https://example.com');
});

```

**Comment by kdwlprerna** [comment]
> Thanks! The following works for me, BUT using `waitForTimeout` is not recommended. The app you've linked is sufficiently complicated that it's unlikely for me to understand where the suspected race is.
> 
> ```ts
> import { test, expect } from '@playwright/test';
> 
> test('it works', async ({ page }) => {
>   await page.goto('https://easy-email-m-ryan.vercel.app/editor?id=977');
>   await page.locator('text=Make it easy for everyone').nth(0).click();
>   await page.locator('[title="Link"]').click();
>   await page.waitForTimeout(500); // BAD: Don't do this. It's an anti-pattern and subject to flakiness
>   await page.locator('[name="link"]').fill('https://example.com');
>   await page.waitForTimeout(500); // BAD: Don't do this. It's an anti-pattern and subject to flakiness
>   await page.locator('button:has-text("Apply")').click();
>   await page.waitForTimeout(500); // BAD: Don't do this. It's an anti-pattern and subject to flakiness
>   await page.locator('button', { has: page.locator('.icon-desktop') }).click();
>   const [newPage] = await Promise.all([
>     page.waitForEvent('popup'),
>     page.locator('text=Make it easy for everyone to compose emails!').nth(1).click(),
>   ]);
>   await expect(newPage).toHaveURL('https://example.com');
> });
> ```

This worked for me too!! Thanks. Though I am not sure if I should add these many waitForTimeout(). Could you tell me why do we need them after these below lines as well:-

- await page.locator('text=Make it easy for everyone').nth(0).click();
- await page.locator('[name="link"]').fill('https://example.com');

**Comment by rwoll** [comment]
> Though I am not sure if I should add these many waitForTimeout().

😄 This is a great intuition. And you're correct, a good, stable, fast, non-flaky test will not include any explicit waits. So, while the above shows your test _could_ work under some conditions, you should replace the `waitForTimeout`s with something more specific. See next statement for more suggestions. 

> Could you tell me why do we need them after these below lines as well:-

Unfortunately, this depends on how your app is implemented. Since the sample app you've sent is quite complex, I'm unable to dive in to figure it out for your case specifically.

If the built-in [auto-waiting](https://playwright.dev/docs/actionability) of click/fill/etc. still yields flaky/broken tests[^1], you'll need to figure out another signal in the page/app that says the test is OK to continue from one action to the next.

This signal might be waiting for a network request, waiting for another element to show up, etc.

I suspect the issue currently is after you click, despite Playwright finding the input to then fill, you're app is not ready for the input to be filled due to some app-specific implementation detail.  

Does the above make sense? If you're able to provide a small, self-contained repro, we'll be able to help more.

[^1]: in your case since the test doesn't work without the timeouts, this is the scenario.

**Comment by kdwlprerna** [comment]
> 

I tried eliminating one of the waitForTimeouts as below,. However I am not able to do it at other places. Could you suggest if there is a way we could eliminate 2nd and 3rd waitForTimeout? 
await this.page.locator('[title="Link"]').click();
 // await this.page.waitForTimeout(500);
    await this.page.waitForSelector('[name="link"]');
    await this.page.fill('[name="link"]', 'https://www.google.com'); //set link
    await this.page.waitForTimeout(500);
    await this.page.click('button:has-text("Apply")');
    await this.page.waitForTimeout(500);

**Comment by rwoll** [comment]
> Could you suggest if there is a way we could eliminate 2nd and 3rd waitForTimeout?

The app you've linked is a complex React app, so I'm unable to to dig into its implementation to provide the exact answer for your case. But at the end of the day, it looks like the app you've linked takes some time to process events and reflect them to the user.

To help explain what I think is going on with your app, consider this small isolated example:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Async Updating App Example</title>
  </head>
  <body>
    <a id="link" href="https://example.com">click here to go to https://example.com</a>

    <form id="editor">
      <label for="destination">Destination</label>
      <input id="destination" type="text">
      <input type="submit">
    </form>

    <div id="status"></div>

    <script>
      const link = document.getElementById('link');
      const form = document.getElementById('editor');
      const status = document.getElementById('status');
      form.addEventListener('submit', (e) => {
        e.preventDefault();
        status.innerText = 'updating…'
        setTimeout(() => {
          const destination = document.getElementById('destination').value;
          link.href = destination;
          link.innerText = `click here to go to ${destination}`;
          status.innerText = 'saved!';
        }, 1000);
      });
    </script>
  </body>
</html>
```

It's a small "app" that allows you to edit a link on the page by filling in a form. Although, each time you click submit, it takes 1000ms to "save" the update. So if you click the link within one second of hitting submit, the link will take you to the old site.

Assuming I can't change the app, to make a robust test, I'd wait to click the link until I saw "saved" in the status div since that's what's supposed to indicate to a user the change is saved and reflected in the UI.

In your app's case it's likely not just a `setTimeout`, but I'd look for any async work that's done by your app between actions.

---

Sorry I cannot provide the specific thing to wait for in your app! I'm going to close this issue for now, but feel free to comment if you have questions on the example I've included here. When you do figure out a better "ready" signal for your specific case, feel free to comment as I'm curious as well! 😄
