### ISSUE TITLE
Linux VM instance is not getting opened in windows machine through playwirght with Remote-SSH

### ISSUE THREAD

**Issue by SB185579** [microsoft/playwright#14208]
Hi Team,
I have desktop application in my linux VM, I have created sample playwright JS browser script in windows VSCode and tried executing in Linux VM through remote-ssh, Could see script got executed successfully in linux VM in headless mode and while running with headed mode, Could see below error. Kindly help us fixing below issue.

<Error>
browserType.launch:
╔════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Looks like you launched a headed browser without having a XServer running. ║
║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║ ║

Note: I have installed XServer in windows machine, But still getting above error.

**Comment by rwoll** [comment]
Since you're using VSCode with Remote-SSH extension, the remote Linux VM is the machine where the browser is trying to run and open and failing, so you'll need an XServer there instead of on your Windows machine. See https://playwright.dev/docs/ci#running-headed for a link to Xvfb info and example commands to use to run your script.
