### ISSUE TITLE
[Feature] Add option to disable adding os name to the snapshot

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#14218]
it will be nice if we can pass an option to disabled appending os name to the taken snapshot, since when im running my test on my local machine on macos  "darwin" is appended to the snapshot name, but the test is failing since name will linux when running in pipeline

<img width="254" alt="Screenshot 2022-05-17 at 13 48 08" src="https://user-images.githubusercontent.com/32042806/168803988-0bbf8abb-7cac-4239-a284-685ae85969a7.png">

<img width="1303" alt="Screenshot 2022-05-17 at 13 48 45" src="https://user-images.githubusercontent.com/32042806/168804139-5e2513e8-43d8-482d-9b44-c428c885b4a5.png">

**Comment by amrsa1** [comment]
@dimkin-eu  so whats the proper approach to over come this issue ?

**Comment by vitalics** [comment]
@amrsa1 you can override `testinfo` object. As for me, this approach is not recommended since you cannot be sure about the screenshot function (e.g. in Linux can be different and your macos tests can be failed) 

https://github.com/allure-framework/allure-js/blob/master/packages/allure-js-commons/src/AllureRuntime.ts#L59
example
``` ts
import {test} from '@playwright/test';

test('demo', async ({page}, testinfo) => {
testinfo.snapshotSuffix = ''; // by default is `process.platform`

// your test
expect(page).toHaveScreenshot();
});
```

**Comment by amrsa1** [comment]
@ltsuda but if im updating the screenshot, it means that im taking screenshot then validating from the app itself.
i dont think this will be valid test if i got it correct

**Comment by dimkin-eu** [comment]
> @dimkin-eu so whats the proper approach to over come this issue ?

we are executing image comparison and updates only on CI
you can locally compare screens before and after changes, but local `.png` are in `.gitignore`

**Comment by amrsa1** [comment]
I think best approach in my case is to run them locally first inside a docker container then volume the snapshot directory to my root directory of my repo then push the code to the CI

**Comment by rwoll** [comment]
@aslushnikov Can you elaborate on some workflows you've found to work for you to update screenshots for CI? I believe it's something similar to what https://github.com/microsoft/playwright/issues/14218#issuecomment-1129020335 suggests.

This is an active area we're thinking about improving the experience of.

If you're running your screenshot tests on different platforms, you'll likely want to leave the platform suffix as is since they each can have subtle differences. This does, however, make managing your laptop screenshots vs. your CI screenshots a bit cumbersome.

If you really want to disable the suffix, see https://github.com/microsoft/playwright/issues/11226#issue-1095625280 for a recommended workaround.

**Comment by rwoll** [comment]
Closing as part of triage. This is a known area we'd like to improve in the future! Thanks all for sharing your current workflows in the interim!

**Comment by PsiKai** [comment]
> This is a known area we'd like to improve in the future!

@rwoll was there any future work or planning done on this feature?

**Comment by bitttttten** [comment]
I managed to work out a script here to help me out:

```sh
docker run -it -v $(pwd):/src --rm --ipc=host mcr.microsoft.com/playwright:v1.40.0-jammy /bin/bash -c \"cd /src; npm i; npx playwright test --update-snapshots\"
```

This should start a docker container with playwright and update the snapshots for linux 🥳 

The script assumes you are running it from the same place you would run "npx playwright test". So cd to where you would run that, then run this.
