### ISSUE TITLE
[Feature] Performance Metrics

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#14227]
Playwright users use a wide variety of the features of Playwright and Playwright Test to run anywhere from 10s to 1000s (?) of tests. These tests are run on a variety of hardware: laptops, CI machines, Serverless functions, etc.

Speed of execution and memory consumption is important (likely among other metrics).

To help ensure we stay objectively fast and performant and track how each feature impacts performance, we should add explicit perf testing as part of the CI. This might take many forms.

**Comment by khtan** [comment]
If we do a poll, please include some metric on flakiness. I know that there are numerous smart behavior in Playwright that is supposed to make it less flaky, but there is also a cooperative relationship between reliable tests by tuning the timeouts etc so that Playwright can do its best. So, a question of how flaky are the tests and whether they are surmountable through smart programming or are they still an issue despite all efforts.

**Comment by unlikelyzero** [comment]
@rwoll I think you should consider collaborating with https://github.com/krausest/js-framework-benchmark as he has recently moved from selenium to playwright/puppeteer benchmarks. 

I've always dreamed of being able to do some Performance Modeling/Budgeting of Test Frameworks, themselves. It's an interesting problem given the smaller resource footprint associated with CI Agents. I've been fortunate enough to do performance testing and modeling for Jenkins and Ansible.

For comparison, Test Framework Performance issues have come up with Cypress.io in the past. They were always identified in the field and fixed. I'm not aware of any internal performance testing that the team does. Not to say they don't do it. The two I dealt with were related to Firefox support and some diagnostic feature (can't remember offhand and the issue tracker isn't helping).

Second, I think you'll find it difficult to get an accurate view of performance using something like a GHA CI Agent just due to the way it's shared/virtualized with no SLA associated with resource performance. I know I have. I can imagine it would be a hard sell to use AWS ec2 machines in MS, but it might make sense to use an Azure equivalent to perform the following.

CI Agent Benchmark device: Azure Instance Size 2core 4GB RAM 10k IOPS. Something in between a CI Agent and Laptop.

Benchmark App: Co-located (Same Network/Hypervisor... even same node env on localhost?) React Demo Application with REST API (for route intercept testing)

Benchmark Test Cases
- With all Diagnostic Features Disabled (Tracing/Screenshot/Videos), how many concurrent tests (threads/shards) can be run simultaneously before hitting 100% CPU.
- With all Diagnostic Features Enabled, how many concurrent tests can be run simultaneously hitting 100% CPU. 
- With Diagnostic Features Disabled, how long does a given test suite running 100x of the same test take to finish.

Stress
- Overprovision CI Agent (80% CPU/Mem) and see how long it can survive
- Set up a test with `--repeat-each` set to <infinity> and see how many cycles can be performed before failure

Tracing Test Cases
- How long does it take to launch pw, launch chrome, connect to chrome, set Target, Download JS/CSS/HTML of Benchmark App, Close Browser/Connection, Generate Test Report
- Trace each individual stage
- This might be something that tests playwright/test more than playwright-core

Anyways, this sounds like an awesome opportunity and would be interesting to walk down your commit tree (1.22 -> 1.21 -> 1.20) to see how performance has changed over time.

**Comment by kallebjork** [comment]
I really think you should prioritise this. The Chrome tab memory footprint grows and grows during a test with Playwright and that should affect the speed of execution for a longer run (larger test).

Just navigating back and forth on a page will quickly end up with a tab size around 1GB - which does not happen when testing with other E2E test frameworks, nor when doing the same interaction manually.

We are hoping that you look into this issue:
https://github.com/microsoft/playwright/issues/16832

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
