### ISSUE TITLE
[Feature] Snapshots/Screenshots: Include Snapshot in HTML Report when Writing

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#14239]

**Comment by sgielen** [comment]
This would be great!

In the meantime, as a workaround, we can do it ourselves, too: https://stackoverflow.com/questions/73745790/include-screenshots-in-report-test-steps-with-playwright

```
  const screenshot = await page.screenshot();
  await testInfo.attach('screenshot', { body: screenshot, contentType: 'image/png' });
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
