### ISSUE TITLE
[BUG] Permissions: Sending MIDI Sysex causes Chrome to crash

### ISSUE THREAD

**Issue by lozjackson** [microsoft/playwright#14346]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac
- Node.js version: 16.13.2
- Browser: Chromium/Chrome
- Extra: [any specific details about your environment]

**Code Snippet**

Here is a link to a repo that reproduces the bug: https://github.com/lozjackson/plawright-midi-test

clone the repo
run `yarn` to install dependencies
run `yarn test` (or `npx playwright test`) to run the tests

You will see a message in the console saying "Chrome crashed, "Aw Snap" etc..." and the test will hang while it is waiting for the button element (that is not there because Chrome crashed).

If you remove the permissions that are being set [on this line](https://github.com/lozjackson/plawright-midi-test/blob/main/tests/midi.spec.ts#L18) and run the test in debug mode you can click the MIDI permissions prompt and the test will then pass

**Describe the bug**

If I add the `midi` and `midi-sysex` permissions in Playwright config, then Chrome crashes when sending MIDI sysex via the web-MIDI API and displays the "Aw Snap" page with the error code

```
Error code: RESULT_CODE_KILLED_BAD_MESSAGE
```

If I don't add the permissions in Playwright, then the MIDI permissions prompt gets displayed when I run the test, and if I click "Allow" then sending MIDI sysex works as expected.

Sending MIDI sysex also works as expected when running in Chrome without Playwright.

**Comment by lozjackson** [comment]
@yury-s do you know if anyone is actively working on this issue?

Our app's main purpose is communicating with MIDI hardware, and this issue is blocking us from fully adopting Playwright.  I would love to help debug this, or work towards a fix, if I could, but I wouldn't know where to start. Please let me know if there is anything I can do to help

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
