### ISSUE TITLE
[Question] Is Playwright Test using a custom CJS/ESM module system?

### ISSUE THREAD

**Issue by pkerschbaum** [microsoft/playwright#14398]
Hello!

I consider to use Playwright Test for unit&integration tests and I am currently reviewing what is missing compared to "traditional" unit test frameworks like Jest.  
One thing Jest provides is an API to mock CJS modules loaded by the subject under test, via `jest.mock(...)`. In essence, it is possible to replace the thing returned by `require` function calls.

Now I tried to set up [testdouble](https://github.com/testdouble/testdouble.js) in my Playwright Test setup to do the same thing, but I just can't get it to work.  
So what I wonder is: Does Playwright Test use some sort of custom loader for CJS/ESM modules that prevents such module-mock libraries (like `testdouble`, `proxyquire`, etc.) to work?

Related: #14268

**Comment by pavelfeldman** [comment]
We do some of that work that those mocking libraries do and we might clash.

- Typescript
  - We support TS w/o compilation, it means that we will transpile TS files on the fly. We would transpile them into the CJS form and use pirates to require/transpile recursively.
  - Typescript allows using aliases in config, in order to support those, we would [intercept module resolution](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/transform.ts#L98). You can see how we bail out while loading builtin modules, something mocking library would want to handle.
- ESM + Typescript
  - In order to support the above in the ESM environment, we would be similarly transpiling TS into the ESM-style modules. We would use Node's experimental ESM resolver/loader instead of pirates/require to achieve the same as above.

All it all, rephrasing this request "allow mocking third party and built-in modules" should not be too much work for us. We already have all the hooks to achieve that in place. I would imagine that aliasing is pretty much indistinguishable from mocking and we already have support for it.

**Comment by pkerschbaum** [comment]
Ok I see, thanks for the information!

I am working on a blog post comparing "traditional" test runners (like Jest) with Playwright Test, and I will note that "module mocking" (like `jest.mock(...)`, [jestjs.io/docs/manual-mocks](https://jestjs.io/docs/manual-mocks)), is not possible at the moment but might be added in the future.

From my point of view we can close this issue.  
Should I create a feature request as you suggested ("allow mocking third party and built-in modules") so that folks could upvote it?

**Comment by pavelfeldman** [comment]
> Should I create a feature request as you suggested ("allow mocking third party and built-in modules") so that folks could upvote it?

That would be awesome. Link this issue for context. It would also be great if instead of requesting "do what jest.mock does", you could paste concrete mock examples and use cases.

Closing this one as suggested above.

**Comment by pkerschbaum** [comment]
Issue created: #14572
