### ISSUE TITLE
[Question] Should apiRequestContext and browserContext share storageState?

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/playwright#14463]
Hello,
I have an API call for login that returns a cookie (during tests it returns `httpOnly: false and secure: false`), but this cookie is not automatically shared with the `page`/`context`. See the example below.

```js
import { test, expect } from '@playwright/test'

test.describe('My sample test', () => {

	test('accesses <url> as authenticated user', async ({ page, context, request }) => {
	        // here login is a utility function which only makes an API call like `await request.post('<url>', { data: nameID })` and returns a cookie
		await login(request, { nameID: 'john.doe@example.com' })
		console.log(await page.context().storageState())
		console.log(await context.storageState())
		console.log(await request.storageState())
		
    await page.goto('<url>')
		expect(await page.screenshot()).toMatchSnapshot()
	})
})

// Here is what I get from the console logs
{ cookies: [], origins: [] }
{ cookies: [], origins: [] }
{
  cookies: [
    {
      name: '<cookie-name>',
      value: '<cookie-value>',
      domain: '<domain>',
      path: '/',
      expires: 1654372852,
      httpOnly: false,
      secure: false,
      sameSite: 'Lax'
    }
  ],
  origins: []
}
```

1) Is this intended behavior?
2) What is the correct way of sharing the `storageState` (cookies), ideally without saving the `storageState` into a file since I want to authenticate just the single test? 
- Should I could create a completely new context with `context.browser().newContext({ storageState: await request.storageState() })`?

**Comment by mxschmitt** [comment]
1. yes, request is a dedicated own request instance. It does not share state because it would otherwise mean that if you use the `request` fixture a browser context gets started in the background
2. you can use either `await page.request.get('https://api.example.com');` or `await context.request.get('https://api.example.com');` which both are connected to the browser instance.

You don't need to, in theory you can but using the proposed page.request or context.request should work for your use-case. They are then "connected" with the context instance.

**Comment by alesmenzel** [comment]
Thanks!
