### ISSUE TITLE
[Question] Tests executed in NodeJS env and not browser?

### ISSUE THREAD

**Issue by jensenhertz** [microsoft/playwright#14469]
I'm trying to use playwright test for unit tests, but I'm having trouble getting it to run the tests in the browser context.

For example, if I do a simple `expect(window).toBeTruthy()`, I get `window is not defined` error. However, `global` does exist, so I'm guessing for some reason tests are executed in NodeJS environment.

I've tried `--browser chromium`, but doesn't seem to work.

Any ideas how can I get the browser env to work?

**Comment by Bessonov** [comment]
If I understand correctly, there is a difference. Your **tests** are executed inside a node environment, but **actions of your tests** are executed inside a real browser. Probably, [this will help you](https://playwright.dev/docs/evaluating) understand what's going on and how you can access `window`.

**Comment by jensenhertz** [comment]
@Bessonov Ok, that's truly unfortunate and makes me question the whole point of using Playwright. I'm currently trying to test code that has a dependency which checks `navigator.userAgentData`. The test doesn't even go to execution because it fails with `navigator is not defined` before that.

**Comment by Bessonov** [comment]
Like I sad, you can access it. But not like `expect(window).toBeTruthy()`. If your all use cases rely on browser execution environment, then look at cypress. But be aware of some cypress' gotchas, _because_ it runs inside a browser.

**Comment by pavelfeldman** [comment]
Looks like this can be closed. If you are looking for an in-browser test runner, you can refer to Karma.

**Comment by wakaztahir** [comment]
I think playwright should allow the ability to do this as well, Since most people prefer not to do `page.evaluate` everytime they need access to `document` , `karma` is deprecated , I am going to use cypress but as I have used playwright, its test results were in a good UI, playwright downloaded the browsers nicely

Playwright should have a simple toggle in its configuration like `"runAllInBrowserContext" : true` when set to true , it runs all tests in browser by default , or if a toggle like that is too simple, maybe `test.runEachWrapping((test)=> { page.evaluate(test) })`

I'd leave it to you guys to figure out the API but I think this would be a huge addition

I would also reference https://github.com/jestjs/jest/issues/139#issuecomment-592373354
https://github.com/jestjs/jest/issues/139#issuecomment-592288787

**Comment by wakaztahir** [comment]
I require this issue to be reopened, as a feature request, rename title to "Execute all tests in the browser by default"
