### ISSUE TITLE
[BUG] Assertions took very long in headless mode

### ISSUE THREAD

**Issue by loxinchi** [microsoft/playwright#14479]
## Context:
- Playwright Version: 1.21.1
- Operating System: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
- Browser: WebKit ...devices["iPhone 12"]

## System:
 - Memory: 6.38 GB / 11.53 GB
 - Container: Yes
## Binaries:
 - Node: 14.18.3 - /usr/local/bin/node
 - npm: 8.1.4 - /usr/local/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Repo**
[Link](https://github.com/loxinchi/ms-playwright-issue)

**Code Snippet**

```javascript
import { test, expect } from "@playwright/test";

test("test checkboxes and Radio buttons without placements", async ({ page }) => {
  const newSignUrl = "https://staging.scrive.com/s/9221714692412077704/9221932570715111975/e2d6e750aba8283a";

  await page.goto(newSignUrl, { waitUntil: "networkidle" });
  await expect(page).toHaveURL(/new\/sign/);
});
```

**Describe the bug**

It took extra long time to pass the test in headless mode.
The test report video is very confusing, look like UI is shaking all the time.

**Comparison**

For headed mode assertion timeout is 5s without any issue.
For headless mode assertion timeout it has to change to at least 10s for test to pass.

**Comment by loxinchi** [comment]
@aslushnikov  Thank you so much for your timely reply.

After took off `networkidle` call, `await expect(page).toHaveURL(/new\/sign/);` works fine.

I updated my repo to add the locator assertion.
I noticed that `toBeVisible()` doesn't seem to have auto wait because the global expect timeout, and I had to add `waitFor()` to pass the test.

What's the difference between `waitFor()` and  auto wait in [web-first assertion](https://playwright.dev/docs/release-notes#-web-first-assertions) ?

**updated repo:** [link](https://github.com/loxinchi/ms-playwright-issue)
```javascript
import { test, expect, Locator } from "@playwright/test";

test("test checkboxes and Radio buttons without placements", async ({ page }) => {
  const newSignUrl = "https://staging.scrive.com/s/9221714692412077704/9221932570715111975/e2d6e750aba8283a";

  await page.goto(newSignUrl);
  await expect(page).toHaveURL(/new\/sign/);

  const checkbox: Locator = page.locator("input[type=checkbox]");
  // await checkbox.waitFor();
  await expect(checkbox).toBeVisible();
});
```

**Result:**
```javascript
    Error: expect(received).toBeVisible()
    Call log:
      - expect.toBeVisible with timeout 5000ms
      - waiting for selector "input[type=checkbox]"


       9 |   const checkbox: Locator = page.locator("input[type=checkbox]");
      10 |   // await checkbox.waitFor();
    > 11 |   await expect(checkbox).toBeVisible();
         |                          ^
      12 | });
      13 |
```

**Comment by aslushnikov** [comment]
> What's the difference between waitFor() and auto wait in [web-first assertion](https://playwright.dev/docs/release-notes#-web-first-assertions) ?

@loxinchi [web-first assertions](https://playwright.dev/docs/release-notes#-web-first-assertions) are much more flexible then [`locator.waitFor()`](https://playwright.dev/docs/api/class-locator#locator-wait-for). That's a "Swiss knife" of Playwright Test!

**Comment by hex0cter** [comment]
@aslushnikov Do you mind elaborating a bit on the purpose of `.waitFor()`? When I looked at the documentation, the default behaviour for [waitFor](https://playwright.dev/docs/api/class-locator#locator-wait-for) seems identical to [toBeVisible](https://playwright.dev/docs/test-assertions#locator-assertions-to-be-visible). They both wait for an element to be visible. 

As @loxinchi mentioned in her last reply, she had to use`.waitFor`  in order to make the test pass. But why is that?

**Comment by aslushnikov** [comment]
> As @loxinchi mentioned in her last reply, she had to use.waitFor in order to make the test pass. But why is that?

@hex0cter Ah, sorry, I misread that comment.

In Playwright tests, the [`locator.waitFor()`](https://playwright.dev/docs/api/class-locator#locator-wait-for) has a [0 timeout by default](https://playwright.dev/docs/api/class-testoptions#test-options-action-timeout), so it'll wait long enough for test to pass.

The [web-first assertions](https://playwright.dev/docs/release-notes#-web-first-assertions) will wait for [5 seconds by default](https://playwright.dev/docs/test-timeouts#expect-timeout). 

So to make it work, you can extend the `expect().toBeVisible()` call timeout:

```js
  const checkbox: Locator = page.locator("input[type=checkbox]");
  await expect(checkbox).toBeVisible({ timeout: 20000 });
```

**Comment by hex0cter** [comment]
Hi @aslushnikov! Thanks for your reply. 

I did some more experiments on this. It turns out the problem is not really about the timeout value for expect. I tested iPhone 11 and iPhone 12 on MacOS and Ubuntu 20.04 (in docker). In fact the slowness only happens with iPhone 12 on Ubuntu. On MacOS both  devices always work like a charm.  But on Ubuntu, no matter what timeout I use (I tried up to 300000 ms), iPhone 12 always gives timeout (iPhone 11 still works fine).

The next thing I observed is, once I added `element.waitFor()`, iPhone 12 will work again in `expect(element).toBeVisible()`. It seems `element.waitFor` can affect `expect(element).toBeVisible()` somehow.

Last but not least, when the tests fails (iPhone 12, Ubuntu, and without `element.waitFor`), the video captured by Playwright seems to be shaking a lot.

I attached the whole logs from the tests for your information. The updated repo can also be find [here](https://github.com/hex0cter/playwright-slowness-issue). 

Any thoughts? 

[playwright-report.zip](https://github.com/microsoft/playwright/files/8843359/playwright-report.zip)

**Comment by pavelfeldman** [comment]
I can reproduce it, only in headless mode, the viewport is shaking.

**Comment by yury-s** [comment]
I cannot reproduce it on Ubuntu (neither in docker nor on a native hardware).

@hex0cter @loxinchi could you please check if it is still reproducible with playwright 1.23.2 ?

**Comment by hex0cter** [comment]
Thanks for looking into this everyone! As @loxinchi mentioned the issue is somehow gone even with the old version.
