### ISSUE TITLE
inspecting dynamic link

### ISSUE THREAD

**Issue by NajetMemmiche** [microsoft/playwright#14489]
Dear all,
I am trying to inspect a link wich is displayed only when i pass the mouse over it. How can i find this locator so i can make a clic.
Thank you in advance

**Comment by aslushnikov** [comment]
@NajetMemmiche is the link hidden via `visibility: hidden` css rule, or in some other way? It's hard to help here without an website we can look at and suggest something!

All in all, there are a few means you can use to solve this:
- use [`page.mouse.move()`](https://playwright.dev/docs/api/class-mouse#mouse-move) method to move the mouse where you want it to be. This requires `x` and `y` coordinates though
- find a good element and hover it using [`page.hover()`](https://playwright.dev/docs/api/class-page#page-hover). Notice there's a `position` option here that can offset relative to the element so that you have a fine control.

Hope this helps! If not, please re-file with a link to the website you try to test so that we can see your link ourselves and recommend something more specific. Thanks!
