### ISSUE TITLE
feature: collect CPU / memory stats when failing to launch browser

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#14553]

**Comment by sergioariveros** [comment]
This will be something great to have, we have some issues related to this but never dig in to much as are rare and not consistent failures

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
