### ISSUE TITLE
[Question] Clearing cache for electron app

### ISSUE THREAD

**Issue by mattd233** [microsoft/playwright#14613]
I wonder if there is a way to clear the cache of the electron app after you run each test.
The electron documented something like this, but I'm not sure how to access `app session` in playwright.

```js
const { BrowserWindow } = require('electron')

const win = new BrowserWindow({ width: 800, height: 600 })
win.loadURL('http://github.com')

const ses = win.webContents.session
ses.clearCache()
```

**Comment by aslushnikov** [comment]
@mattd233 From Playwright point of view, this is how you can evaluate in the main Electron process:

```js
// Launch Electron app.
const electronApp = await electron.launch({ args: ['main.js'] });

// Evaluation expression in the Electron main process.
const appPath = await electronApp.evaluate(async ({ app }) => {
  // This runs in the main Electron process, parameter here is always
  // the result of the require('electron') in the main app script.
  return app.getAppPath();
});
```

This should be enough to use various electron APIs. I can't comment on Electron specific API's though since I don't have much experience, so I'll close this for now. Please re-file if you think that we still can be helpful!
