### ISSUE TITLE
[BUG] Network interception breaks multipart requests

### ISSUE THREAD

**Issue by niranjan94** [microsoft/playwright#14624]
**Context:**
- Playwright Version: `1.22.2`
- Operating System: Mac
- Node.js version: `v16.13.0`
- Browser: Chromium & WebKit _(works as expected on firefox)_

**Code Snippet**

```typescript
import { chromium, Route } from 'playwright';

(async () => {
  const browser = await chromium.launch({
    headless: false,
  });

  const context = await browser.newContext();
  const page = await context.newPage();
  await page.route('**', async (route: Route) => {
    // Get the request
    const request = route.request();

    // Fetch the original response in the context of the page
    const response = await page.request.fetch(request);

    // Return the original response with
    await route.fulfill({ response });
  });

  await page.goto('https://cgi-lib.berkeley.edu/ex/fup.html');
  await page.locator('input[name="upfile"]').setInputFiles([
    {
      name: 'test-file.txt',
      mimeType: 'text/plain',
      buffer: Buffer.from('hello world'),
    },
  ]);

  await page.locator("input[type='submit']").click();
})().catch(console.error);
```

**Describe the bug**

- The code to reproduce is straightforward. All requests are intercepted and passed through without any modifications
- On chrome & webkit, I see that the final request being sent to server is missing the body for some reason
- On firefox, it works perfectly.

**Comment by aslushnikov** [comment]
I can repro on tip-of-tree.

**Comment by PawelWesolowski** [comment]
Probably related: https://github.com/puppeteer/puppeteer/issues/9106

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by younes-zeboudj** [comment]
This issue has several consequences. I mention an important use case I faced: 

Using proxy per request would be impossible due to lake of the post data when it comes to multipart requests. This makes puppeteer-page-proxy plugin for
