### ISSUE TITLE
Create selector engine for selecting input by typed text

### ISSUE THREAD

**Issue by PeterHevesi** [microsoft/playwright#14679]
Hi,
I have a problem, that it is not possible to select input based on text, that was just typed with neither xpath, nor css or not even any other selector engine in Playwright, because the value attribute of an input doesn't get updated when new text was typed... 
Only only property value is updated when text typed into input...
So to be able to select this input based on containing text, it is required to use javascript:
await Locator.EvaluateAsync<string>("input => input.value");

My understanding is, that css or xpath selectors can only work with attribute @value, but not property @value, which is only accessible by Javascript...

But Javascript is not something I can put into selector, because I am locating elements using Locators (or Selectors), so I can't use javascript...
Buut it is possible to define custom selector engine (which uses Javascript), so I guess this problem could be solved by creating new Selector engine that could be called like "typedText" for example, so I can then write something like this:
"typedText='some typed text' and it would locate input with that text...
or even combine it in css selector like this: 
"css=input:typedText('some typed text')"

I mean because there are these great Playwright selector engines like text, has-text and so on, but this one would also be useful :)

Thank you very much if you consider to implement it, as I think this feature is something very basic and many people would use this new selector engine :) Sometimes, there is a need to locate element based on typedText

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
