### ISSUE TITLE
[Question] Using Vue selectors with Vue component testing

### ISSUE THREAD

**Issue by nag5000** [microsoft/playwright#14680]
Should [Vue selectors](https://playwright.dev/docs/selectors#vue-selectors) work at the current stage of Component Testing? 
I can't locate any of the components. But I'm sure there are mounted, and the test passes if I use alternative css selector.

```
$ npm run test-ct

> playwright test -c playwright-ct.config.js

Running 2 tests using 2 workers
  1) [chromium] › foobar.test.ts:17:1 › foobar should work =================================

    Timeout of 10000ms exceeded.

    page.click: Target closed
    =========================== logs ===========================
    waiting for selector "_vue=text-editor"
    ============================================================
    > 30 |   await page.click('_vue=text-editor')
```

**Comment by pavelfeldman** [comment]
I suspect that the reason is that we use production build for testing components, while vue selectors rely upon dev one.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
