### ISSUE TITLE
[Feature] Skipped tests in HTML reporter could have a stronger visual indication

### ISSUE THREAD

**Issue by np-xavier** [microsoft/playwright#14703]
The default Playwright test report does not have an icon or clear indication that it has been skipped with `test.skip()`. Currently, a passed test and a failed test both have a nice green tick and red cross icon respectively, but the skipped test has no icon.

When I first ran my report I was a little confused about if the report had somehow "blipped out" and not rendered the report entry correctly for certain test cases, until I realised it was a few I'd marked as skipped (which is mostly my fault for forgetting).

At any rate, if you build three `test()`, `test.fail()` and `test.skip()` entries and see the report, I think it would be nice to have a corresponding icon for skipped tests to make this more apparent. I don't know if the HTML reporter is a third party solution, of course, but thought I'd bring it up that I think skipped tests could have a better visual indication. The same might be considered for flaky, but I haven't used that yet.

As an aside, on the filters at the top of the report, only "Failed" has its corresponding icon next to it, it seems it would be more consistent to add the green tick next to "Passed" as well. Anyway, just some personal thoughts - thanks for reading!

**Comment by loganromero** [comment]
On a similar note:

Is it possible to add a flag to remove/hide skipped in the report altogether?

Perhaps a test.hide()?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
