### ISSUE TITLE
[Feature] Add small customization how trace is displayed in html report

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#14708]
Usually CIs (in my case Jenkins) cannot serve HTML report like we do locally. Instead, a static page is served, and clicking on trace preview does nothing.

It would be nice to have some small configuration to decide how trace is displayed in HTML report:
- same as now
- no trace preview (image), trace attachment, link to trace page like `https://trace.playwright.dev/?trace=http%3A%2F%2Ffoo.com%2Freports%2Fc3e3aeb4-5a65-4789-b3d9-c1cc3d3f336f%2Fdata%2Fattachments%2F6c69d8c1ec9f0f9c.ZIP`
- only trace attachment

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
