### ISSUE TITLE
[Feature]Component testing: reuse the same vite server and same vite config file

### ISSUE THREAD

**Issue by stevez** [microsoft/playwright#14749]
Since my application already uses vite server, I wonder if we can use the same vite sever for both local development and component testing.
and It would be great if we can put the component test configuration in the same vite config file.

**Comment by pavelfeldman** [comment]
While we are considering your request, you can already require it from a shared file

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
