### ISSUE TITLE
[BUG] WebServerPlugin: some processes are not killed properly during cleanup

### ISSUE THREAD

**Issue by mmy97** [microsoft/playwright#14794]
**Context:**
- Playwright Version: 1.22.2
- Operating System: macOS 12.4
- Node.js version: 14.16.0
- Browser: Chromium
- Extra: We are using testConfig.webServer to start a java server via maven (openjdk version "17.0.1" / Apache Maven 3.8.4)

**Code Snippet**

```javascript
config: PlaywrightTestConfig = {
  webServer: {
    command: "mvn spring-boot:run",
    url: "http://localhost:9000",
    reuseExistingServer: true,
  },
```

**Describe the bug**

We are using testConfig.webServer to start a java server via maven, but it is never seems to be killed at the end of the test run or if the tests are cancelled half way through.

When we do this with an express server, the process is correctly killed strangely.

The way I am checking whether the server was killed is by running `lsof -i tcp:9000` and seeing whether there are any java processes left on that port.

Before we were using playwright, we wrote our own server setup / kill code and also had the exact same issue using the various nodejs APIs for killing processes. We switched to the [tree-kill](https://www.npmjs.com/package/tree-kill) library and that has worked flawlessly. 

Side note: There is another smaller inconsistency we've noticed between our express and java servers, which is that only the express server logs anything during startup. Setting DEBUG=pw:webserver makes the java server log stuff to console, but it's not ideal since it also logs playwright internals which we don't care too much about.

**Comment by ambiguous48** [comment]
@mmy97 `tree-kill` is a good shout, thanks. I'm wondering what strategy you use to determine if you should use `tree-kill`. Use case & illustration here: https://github.com/microsoft/playwright/issues/18041

**Comment by joerizz23** [comment]
## Windows-specific process tree leak with `webServer`

Adding a data point to this issue. On **Windows 11**, the `webServer` process cleanup consistently fails to kill child processes because `process.kill()` on Windows only terminates the single PID, not the process tree.

### Process chain

When using a typical Next.js dev server via pnpm:

```
pnpm → cmd.exe → cross-env → node next dev → node start-server.js
```

`process.kill()` kills the top-level `pnpm` process, but `start-server.js` (4 levels deep) survives as an orphan and continues holding the port.

### Impact

- Every Playwright test run leaks at least one `node.exe` process holding the port
- Subsequent runs fail with `EADDRINUSE`
- Zombie processes accumulate across sessions (observed 17 orphaned `node.exe` processes consuming ~25 GB RAM)
- `npx kill-port` also fails for the same reason — it uses `taskkill /PID` (single process)

### Root cause

- `process.kill()` on Windows doesn't support process groups ([nodejs/node#3617](https://github.com/nodejs/node/issues/3617))
- PR #34130 added `gracefulShutdown` but explicitly skips Windows
- `cross-env` doesn't forward signals ([kentcdodds/cross-env#139](https://github.com/kentcdodds/cross-env/issues/139))

### Working fix

The only reliable cleanup on Windows is `taskkill /T /F /PID` (the `/T` flag kills the entire process tree):

```typescript
// In globalTeardown:
execSync(
  `powershell -NoProfile -Command "Get-NetTCPConnection -LocalPort 3000,3001,3002 -State Listen -ErrorAction SilentlyContinue | Select-Object -ExpandProperty OwningProcess -Unique | ForEach-Object { taskkill /PID $_ /T /F }"`,
  { stdio: "ignore", timeout: 10000 }
);
```

### Suggestion

Could the `WebServerPlugin` teardown use `taskkill /T /F` on Windows (or the [`tree-kill`](https://www.npmjs.com/package/tree-kill) npm package) instead of `process.kill()`? This would fix the process leak for Windows users.

**Environment:** Windows 11, Playwright 1.57.0, Next.js 15.4.11, Node.js 22.x
