### ISSUE TITLE
[BUG] In some cases/websites, relative locator does not return value an end-user sees on the screen

### ISSUE THREAD

**Issue by suratdas** [microsoft/playwright#14807]
**Context:**
- Playwright Version: Java Playwright dependency 1.22.0
- Operating System: Mac
- Node.js version: NA. Using Java dependency com.microsoft.playwright:playwright:1.22.0
- Browser: All
- Extra: None

**Code Snippet**
```Java
//Using Java dependency com.microsoft.playwright:playwright:1.22.0
//Go to url https://www.ag-grid.com/license-pricing
//Below line returns "Per developer", expecting "$750"
playwrightPage.locator(":below(:text(\"Starting at\"))").first().textContent()

//Go to url https://www.google.com/search?q=abnb+share+price
//Below line returns "abnb share price - Google Search(function).....", expecting "Airbnb Inc"
playwrightPage.locator(":above(:text(\"NASDAQ: ABNB\"))").first().textContent()

//Go to url https://www.ag-grid.com/
//Below line returns "+299 684 841 0710", expecting "Vue"
playwrightPage.locator(":right-of(:text(\"React\"))").first().textContent()
//Below line returns "", expecting "Angular"
playwrightPage.locator(":left-of(:text(\"React\"))").first().textContent()
//Below line returns "React", We are good here. It matches expectation.
playwrightPage.locator(":right-of(:text(\"Angular\"))").first().textContent()
//Below line returns "", expecting "JavaScript"
playwrightPage.locator(":left-of(:text(\"Angular\"))").first().textContent()
//Below line returns "Contact", expecting ""
playwrightPage.locator(":left-of(:text(\"Demo\"))").first().textContent()
```

**Describe the bug**
The expected (based on how an end-user sees on the screen) and actual are given above. It is not returning a value based on visual layout from an end-user perspective. If it cannot be fixed for any technical reason, it will be helpful to update [documentation](https://playwright.dev/docs/selectors#selecting-elements-based-on-layout) on how to go about writing a good relative locator for some websites (examples above) where example samples don't work.

**Comment by dgozman** [comment]
> ```java
> //Go to url https://www.ag-grid.com/license-pricing
> //Below line returns "Per developer", expecting "$750"
> playwrightPage.locator(":below(:text(\"Starting at\"))").first().textContent()
> ```
In this case, '$750' is not an element, but instead some text inside a large element. Playwright only targets elements, not text nodes, so this is impossible to fix. Sorry for inconvenience.

> ```java
> //Go to url https://www.google.com/search?q=abnb+share+price
> //Below line returns "abnb share price - Google Search(function).....", expecting "Airbnb Inc"
> playwrightPage.locator(":above(:text(\"NASDAQ: ABNB\"))").first().textContent()
> ```
This works for me, returns "Airbnb Inc".

> ```java
> //Go to url https://www.ag-grid.com/
> //Below line returns "+299 684 841 0710", expecting "Vue"
> playwrightPage.locator(":right-of(:text(\"React\"))").first().textContent()
> ```
This is because there is an element in the list between "React" and "Vue". It is scrolled out from the list, but can be easily scrolled in. Same for other examples on this page.

--- 

Overall, the issue here is that there are multiple elements "to the right of React". Playwright chooses the closest one, while a human may expect the closest one that has some text or image or something else that catches the attention. However, there is no way for Playwright to know that.

In practice, layout selectors should be used as a form to differentiate between multiple suspects, an addition to some other selector. For example, `:right-of(text("Username"))` isn't a good selector, while `input:right-of(text("Username"))` is a good one. A rule of thumb would be "adding .first()" after a layout selector will not produce a great result.

Let me update the docs accordingly.

**Comment by suratdas** [comment]
Thanks. I had figured out during my test that it may not be possible to fix based on layout. Hence requested to update docs for such cases.  Thanks for updating the docs.
