### ISSUE TITLE
[Feature] Cloud mobile device support with  Browser stack

### ISSUE THREAD

**Issue by girishgl** [microsoft/playwright#14824]
Currently playwright does not support cloud mobile devices.

Pavel Feldman mentioned [here](https://github.com/microsoft/playwright/issues/1122#issuecomment-592229668
) about the technical feasibility of this feature.

We are willing to contribute to this project.  As we are new to this project so we do not know where we can start from?  
Can anyone help us how and where to start contributing?

**Comment by dimkin-eu** [comment]
https://github.com/microsoft/playwright/issues/1122

**Comment by dgozman** [comment]
@girishgl This is not an easy task. Playwright has [experimental support](https://playwright.dev/docs/api/class-android) for Chrome for Android, however other mobile browsers use a very different tech stack. I cannot just point at some easy contribution - this requires research and experimentation. Sorry!

Connecting to Android in the cloud is probably possible. This depends on what exactly the could provider exposes.

**Comment by dolechnowicz** [comment]
@dgozman is it plan to have such support somewhere on you roadmap?

**Comment by dgozman** [comment]
@dolechnowicz No immediate plans right now.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
