### ISSUE TITLE
[Feature] `playwright install` installs all default browser even if it is called from `playwright-chromium`

### ISSUE THREAD

**Issue by sapphi-red** [microsoft/playwright#14862]
`playwright install` installs not only chromium (firefox, webkit) even if the `playwright` command exists in `playwright-chromium`.
If `playwright-chromium` is installed instead of `playwright`, user will only use `chromium`. So I think it makes sense to only install chromium by default.

### To reproduce
```shell
cd /foo # an empty directory
npm i playwright-chromium
npx playwright install
```

**Comment by mxschmitt** [comment]
After a discussion with the team it is for now expected that all browsers get installed when not specifying a browser name.

We recommend passing chromium manually for now: `npx playwright install chromium` or migrating to the `playwright-core` package, so you don't have a postinstall step at all and can manually decide which browser you want to install.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
