### ISSUE TITLE
Unable to run tests on Selenium Grid with v1.22.1

### ISSUE THREAD

**Issue by shmikkil** [microsoft/playwright#14861]
Hi there, We set the env variables to point to the remote server - Selenium Grid 4.1.2 via the local and unable to run the Playwright tests. The current version we've is 1.22.1...Below is the screenshot: Does anyone have the same issue or any resolution for this error?

![image](https://user-images.githubusercontent.com/17186637/173633652-5b3d831d-afad-4298-a40c-0cc848961bf1.png)

**Comment by dgozman** [comment]
@shmikkil This looks like selenium server closes the socket, for whatever reason. I'd suggest to check your selenium logs to see what's happening.

**Comment by shmikkil** [comment]
@dgozman We can use it for other frameworks incl. Protractor, Playwright and Robot Framework but not for Playwright. Looks like there's an open case on this already which is a little diff. but the issue is similar. https://github.com/microsoft/playwright/issues/11692

**Comment by dgozman** [comment]
@shmikkil Try running with `DEBUG=pw:browser*` environment variable to see where Playwright tries to connect to. Most likely, CDP connection is not established because the node is not accessible to the hub and/or computer with playwright. Take a look at [this solution](https://github.com/microsoft/playwright/issues/11692#issuecomment-1149504322), it might work for you.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
