### ISSUE TITLE
[BUG] Clearing permissions has no effect on camera stream

### ISSUE THREAD

**Issue by PhilippSonntagORGADATA** [microsoft/playwright#14878]
# Context
- Playwright Version: 1.22.2
- Node.js version: v16.13.1
- Browser: Chromium
    - WebKit and Firefox don't start when the [camera permission](https://playwright.dev/docs/api/class-browsercontext#browser-context-grant-permissions) is provided.
 - OS: Windows 10 10.0.19044
 - Memory: 14.08 GB / 23.97 GB
 - Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
 - npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
 - Bash: 5.0.3 - C:\Windows\system32\bash.EXE
- Extra: 
     - Chrome has `--use-fake-device-for-media-stream` start argument
         - The issue is also reproducible when using a real camera.
     - Initially tried it in our .NET project. Reproduced it with a NodeJS project

# [Code Snippet](https://github.com/PhilippSonntagORGADATA/playwright-clear-perms-test)

I've created a **demo repository which is available [here](https://github.com/PhilippSonntagORGADATA/playwright-clear-perms-test)**

Also, a short look into the used test case is here:

```typescript
import { test } from '@playwright/test';

test.describe('Camera access', () => {
  test('Camera stream should be stopped when permissions are cleared', async ({ page, context }) => {
    await page.goto('https://cozmo.github.io/jsQR/');

    await new Promise(resolve => setTimeout(resolve, 3000));
    console.log("Clearing permissions...");
    await context.clearPermissions();
    console.log("Permissions should be cleared by now.");
    await new Promise(resolve => setTimeout(resolve, 3000));
    await page.pause();
  });
});
```

# Describe the bug

When a user revokes his camera access while using Chrome, the camera stream will end. This leads to a black screen where the camera video previously was.

When my automated test clears the permissions with Playwright, the camera stream _does not end_. It just keeps running.

**Comment by dgozman** [comment]
This needs a fix upstream in Chromium.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
