### ISSUE TITLE
[Question] Can I upload reports on Azure or send HTML report as notifications on Teams when running on docker?

### ISSUE THREAD

**Issue by arpitaggarwal-oyo** [microsoft/playwright#14914]
I am using docker to run all my test runs. And want to share the generated report **(Playwright report)** with stakeholders.
I kill my docker instance as soon as the run is complete. 

Is there any way to share playwright reports?

**Comment by dgozman** [comment]
@arpitaggarwal-oyo This is technically possible. For example, you can upload using Azure CLI from inside the docker, or send a request to the Teams webhook. There are no built-in features like that right.

Implementing a [third-party reporter](https://playwright.dev/docs/api/class-reporter) doing any of this is entirely possible. So far, we are not prioritizing these features, and rely on the community to create a reporter package.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
