### ISSUE TITLE
[Feature] globalSetup as function type

### ISSUE THREAD

**Issue by Forfold** [microsoft/playwright#14959]
I'm writing an internal tool for people writing tests that need to get past our OIDC system so they can get to testing their apps faster; I'm leveraging environment variables and am currently working through getting the login state to persist between tests.

I would like to be able to have my users import a `globalSetup` function from my package that accepts the login url page so less boiler plate is needed to get past auth on their ends. I was ideally thinking something along the lines of this:

```ts
// playwright.config.ts
import { globalSetup, defaultSessionPath } from 'playwright-auth'

const LOGIN_ROUTE = 'mywebsite.com'

const config: PlaywrightTestConfig = {
  globalSetup: globalSetup(LOGIN_ROUTE, { click: 'button[aria-label=Login]' }),
  use: {
    storageState: defaultSessionPath,
  }
}
export default config
```

But I'm marking this as a question in case there's already a good way to handle this!

**Comment by dgozman** [comment]
@Forfold This is not currently possible. You'll have to create a `globalSetup.ts` in each package for now. I'll leave this issue open as a feature request.

```ts
// globalSetup.ts

import { globalSetup, defaultSessionPath } from 'playwright-auth';
import { FullConfig } from '@playwright/test';

async function mySetup(config: FullConfig) {
  const LOGIN_ROUTE = 'mywebsite.com';
  await globalSetup(LOGIN_ROUTE, { click: 'button[aria-label=Login]' });
}
export default mySetup;
```

**Comment by Forfold** [comment]
Sounds good, thank you for the quick reply!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
