### ISSUE TITLE
[Question]How to detect  continuous  WebSocket  response 

### ISSUE THREAD

**Issue by yslion** [microsoft/playwright#14983]
def  filterWebsocket (websocket):
    print(websocket.url)

def run(pw):
    page.on("websocket", filterWebsocket)     
    page.goto(url)

this ‘filterWebsocket’  method runs only one time  ，  How to get all wss response from remote server

**Comment by ville-nvt** [comment]
"websocket" event happens when websocket connection is first opened that is why it is triggered only once. You have to add event handlers for_"framereceived"_ and _"framesent"_ for the websocket itself.


Something like this. Haven't actually used playwright with python hope you get the point though :) 
`
def filterWebsocket (websocket):
  websocket.on("framesent",  __Place handler here__)
  websocket.on("framereceived", __Place handler here_ )

def run(pw):
  page.on("websocket", filterWebsocket)
  page.goto(url)
`

**Comment by yslion** [comment]
> "websocket" event happens when websocket connection is first opened that is why it is triggered only once. You have to add event handlers for "framereceived" and "framesent" for the websocket connection.
> 
> Something like this. Haven't actually used playwright with python hope you get the point though :)
> 
> ```
> def filterWebsocket (websocket):
>   websocket.on("framesent",  __Place handler here__)
>   websocket.on("framereceived", __Place handler here_ )
> 
> def run(pw):
>   page.on("websocket", filterWebsocket)
>   page.goto(url)
> ```

Thanks !  it woks .  but .. 

> "websocket" event happens when websocket connection is first opened that is why it is triggered only once. You have to add event handlers for "framereceived" and "framesent" for the websocket connection.
> 
> Something like this. Haven't actually used playwright with python hope you get the point though :)
> 
> ```
> def filterWebsocket (websocket):
>   websocket.on("framesent",  __Place handler here__)
>   websocket.on("framereceived", __Place handler here_ )
> 
> def run(pw):
>   page.on("websocket", filterWebsocket)
>   page.goto(url)
> ```

thanks   && big help !   I cant find this way  in doc before
