### ISSUE TITLE
[Question] Is there a way to open browser in Non-Incognito mode without using open with persistent context?

### ISSUE THREAD

**Issue by Mosorathia** [microsoft/playwright#15011]
I want to open browser without persistent context but in non-incognito mode.. Is there any way i can do that?
I tried `LaunchOptions.ignoreDefaultArgs('--incognito')` but that's not working..

**Comment by mxschmitt** [comment]
It's not really an incognito window, its more like an in memory browser profile. If you want to have a persistent profile, you can use BrowserType.launchPersitentContext: https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context

what is your use-case for it?

**Comment by Mosorathia** [comment]
> It's not really an incognito window, its more like an in memory browser profile. If you want to have a persistent profile, you can use BrowserType.launchPersitentContext: https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context
> 
> what is your use-case for it?

I want to open browser in non-incognito mode.. When i use persistent context i have give the path of user dir where browser is installed and so it gets failed in Jenkins.

**Comment by mxschmitt** [comment]
I don't understand why it fails on Jenkins because of that. You can keep using the same one and the other times you launch the browser it still has the same state (cookies, localstorage etc.)

Are you using Playwright for testing? Then re-using the context might work for you, so that your session stays alive over the different tests?

We need more input to act on that, thank you!

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
