### ISSUE TITLE
[BUG] ENOENT: no such file or directory

### ISSUE THREAD

**Issue by NicoloLattanzio** [microsoft/playwright#15039]
ìHello, i'm having the title error since im trying to use setInputFiles(), when i do playwright-tests, and it comes to open the file manager, it isnt the same as the Computer or as the wsl i'm using(see the image)
So, i dont know in which folder i should put my file to let playwright-tests see them

![Immagine 2022-06-22 141912](https://user-images.githubusercontent.com/80640027/175045254-1af7c5e4-60ba-4465-85b5-9e3b13caf3fa.png)

**Comment by NicoloLattanzio** [comment]
What should i do to try the path out?

**Comment by NicoloLattanzio** [comment]
But, i know that the file exist, i just put it on the folder i wanted, the fact is that playwright somehow cant see that folder

**Comment by mxschmitt** [comment]
what does `file <your-path>` say? 

Playwright does not do magic, so the path which you specified is clearly wrong.

Using __dirname should help: https://github.com/microsoft/playwright/issues/15037#issuecomment-1163005916

**Comment by NicoloLattanzio** [comment]
There isn't any "file" function

**Comment by mxschmitt** [comment]
But you are using linux right? [`file`](https://en.wikipedia.org/wiki/File_(command)) is on any linux distribution as a terminal command.

**Comment by NicoloLattanzio** [comment]
yeah i have an ubuntu wsl

**Comment by NicoloLattanzio** [comment]
I went here with the wsl termina, ubuntu@DESKTOP-3ERT5GD:/mnt/c/windows$, but it doesnt find the file

**Comment by mxschmitt** [comment]
We discourage using absolute paths, and I'd use relative paths instead to upload your file. If you use absolute paths it depends. if you execute it on Windows or on WSL.

**Comment by mxschmitt** [comment]
Closing it for now, since this is not a Playwright bug and you are just passing a wrong path. For general linux support, we recommend asking questions on stackoverflow.

**Comment by tientaidev** [comment]
For anyone who has problem with the file path, if you're using VSCode, select the file -> right click -> copy relative path and paste it.

**Comment by gziebold71** [comment]
Just in case others get tripped up by this, I used the playwright debugger to record this action and later cut and paste into my code.  In the browser window I see that it opens to the "downloads" folder, however I could not just set the `setInputFiles` to something in the downloads folder (ie `setInputFiles('file.name')` because the code that later runs this test doesn't know about the "downloads" folder, and I wasn't using the entire file path (ie `setInputFiles('users/me/downloads/file.name')`.  As noted about using the entire file path is not recommended, so if you want to use just the relative path then the file needs to be within your playwright project (ie `setInputFiles('anotherfile.name')` where `anotherfile.name` is in `testing/your-project/tests` or whatever.
