### ISSUE TITLE
response.fromCache is missing in playwright

### ISSUE THREAD

**Issue by sheikalthaf** [microsoft/playwright#15132]
Is there any way to know whether the response is from cache?

**Comment by rwoll** [comment]
This is not currently exposed in Playwright (and enabling request interception can impact this).

Can you elaborate on your use case? Are you interested in this value in a testing context? Can you share a snippet that would show how you plan to use this information?

Thanks!

**Comment by rwoll** [comment]
Closing as part of triage due to inactivity. Please feel free to re-file with the answers to above. Thanks!

**Comment by sheikalthaf** [comment]
@rwoll  sorry for the delay. We scraping the websites and saving assets in cloud, so if the response is from cache on that time we are avoid saving the assets because it will be already saved.

We are planning to migrate from puppeteer to playwright so we see these are blockers for us

**Comment by rwoll** [comment]
Thanks for the additional information. As a workaround, you can compute (and track) a hash of the file before uploading to dedupe.

**Comment by vctqs1** [comment]
I also need this because i would like to trace `request` from `disk` or `network` because our VM hit a pef issue, so test cases fail alot because `can't load page in time`. so i'm try to `enable` reuse cache in headless mode. so i'd like to check the request from 

Do we have any way to trace this, maybe from `trace-view`?
