### ISSUE TITLE
[BUG] Can't type numpad digits with keyboard.press func.

### ISSUE THREAD

**Issue by hkfsc** [microsoft/playwright#15187]
**Context:**
- Playwright Version: Playwright 1.22.0
- Operating System: Windows
- Node.js version: 14.6
- Browser: Chromium

**Code Snippet**

```python
page.keyboard.press("Numpad5")
page.keyboard.press("NumLock")
page.keyboard.press("Numpad5")
```

**Describe the bug**
When I execute above code snippet, with my computer's Numlock on, I except that it will type digit 5 for me, but it just press the key 'Clear', which is not a key I want at all.

**Comment by ville-nvt** [comment]
On macOS it would make sense.

https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values#code_values_on_mac

```
Virtual keycode                           | Chromium
kVK_ANSI_KeypadClear (0x47) | "NumLock" 
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
