### ISSUE TITLE
[Question] How to get element position without padding?

### ISSUE THREAD

**Issue by hkfsc** [microsoft/playwright#15190]
I want to get the element true rect info without padding size, is it possible? `boundingBox` function can return the element rect info with position and size including the padding part, and when I click that `x,y` coordinate I got from this function, it just clicked the padding part of the element, so nothing happened after click event...
For `page.click` function, I know it can do the job by auto finding the "first visible point" to click, but I don't want to use this function now...
> If not specified, uses some visible point of the element.

And I wonder if we can get this "first visible point" info?

**Comment by rwoll** [comment]
Can you elaborate on your use case? Playwright Test discourages positioning/clicking the mouse explicitly, and instead works best with Locators like `page.locator('button >> text="foo"').click()` as this will perform actionability checks as well as scrolling into viewport etc.

**Comment by hkfsc** [comment]
@rwoll
Discourages? yes, I can see. But I just want to get this info an handle some clicks by myself, rather than use your `click()` function.
Its just a purpose, no specific usage, thanks.

**Comment by rwoll** [comment]
Playwright's built-in [`Locator.boundingBox`](https://playwright.dev/docs/api/class-locator#locator-bounding-box) will include the padding as  it will [use](https://playwright.dev/docs/api/class-locator#locator-bounding-box) [`Element.getBoundingClientReact`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect).

Since you need more specific layout information, you can use the Browser's [`Element.getClientRects`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects) inside a `await page.evaluate(…)`. See the examples on https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects for various usages. (NB: It's named similarly to the bounding variant). The bottom of the MDN page has a visual example: https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects.

Does this work for you? Unfortunately, without information about the particular use case, we will not be able to evaluate it as a feature request.

**Comment by rwoll** [comment]
Closing per the above suggested workaround/code. If additional information is added about the use case, we can consider re-opening and converting to a feature request. Without this information, it is hard to evaluate how useful it will be across all our users. Thanks!
