### ISSUE TITLE
[Feature] Add links for each tab with screenshot for opening image in new tab with cmd+click or Gif/Video tab

### ISSUE THREAD

**Issue by bezyakina** [microsoft/playwright#15193]
Could you add a feature where if you click (cmd+click) on any tab from the "tabbed-pane-tab-strip" class, the corresponding image would open in the new tab. This would be convenient in cases where we don't have a Diff tab (with quick switches between the Actual and Expected images in new tabs we can see the difference). 
Links that have already been implemented under the images have difficult access (it takes a long time to scroll if the screenshots obtained in the test are long).

Thanks for your attention:)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35337277/176254957-1e4e7f2a-f857-4a39-a077-5bd0f918b227.png">

**Comment by bezyakina** [comment]
I also thought it might even be better to make a separate tab with a gif, where images from Actual/Expected tabs will change quickly (with the Actual/Expected header on the images)

![gif](https://user-images.githubusercontent.com/35337277/176259579-359ff6d2-abc4-4c82-b0f4-792681e93dcb.gif)

**Comment by bezyakina** [comment]
There is also an example of an implementation called onion skin in github, this is another solution, but it will also be useful if the length and width of the screenshot will completely fit on the visible part of the screen (and if not, then you can make the onion slider accessible from any part of the screen)

https://user-images.githubusercontent.com/35337277/176404595-4ce69235-693f-4bbb-8e4d-6ee92352f3df.mov

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
