### ISSUE TITLE
[BUG] `click()` or `dblclick()` is not executing on 'path' tag for the DOM

### ISSUE THREAD

**Issue by RizwanMR** [microsoft/playwright#15271]
**Context:**
- Playwright Version: 1.23.0
- Operating System: Linux
- Node.js version: 14.17.3
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: electron application 
- Electron version: 18.0.1 also tested in 13.6.6

## System:
 - OS: Linux 5.14 Ubuntu 20.04.4 LTS (Focal Fossa)
 - Memory: 1.05 GB / 15.38 GB
 - Container: Yes
## Binaries:
 - Node: 14.17.3 - /usr/local/lib/nodejs/node-v14.17.3-linux-x64/bin/node
 - npm: 6.14.13 - /usr/local/lib/nodejs/node-v14.17.3-linux-x64/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

Here is the complete repo to reproduce the bug: https://github.com/RizwanMR/angular-electron

**Describe the bug**
Steps to reproduce:
1. clone the repo.
2. do npm i
3. run the script 'npm run e2e'

Expected result: Should click the element inside the playwright test('Click link')

Actual Result: Throws error as below for the path tag
locator.click: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "(//*[contains(@class,'path-elm')])[1]"
      selector resolved to hidden <path class="path-elm" _ngcontent-dbt-c4="" d="M 55 30…></path>
    attempting click action
      waiting for element to be visible, enabled and stable
        element is not visible - waiting...
    ============================================================

      61 |   test('Click link', async () => {
      62 |     const elem = firstWindow.locator(`(//*[contains(@class,'path-elm')])[1]`);
    > 63 |     const text = await elem.click();
         |                             ^
      64 |     expect(true).toBe(true);
      65 |   });
      66 |

        at /home/hi/Documents/angular-electron/e2e/main.spec.ts:63:29
        at /home/hi/Documents/angular-electron/node_modules/@playwright/test/lib/workerRunner.js:388:15

Add any other details about the problem here.

**Comment by stagefright5** [comment]
This is very important for our automation. We are stuck because of this. Please fix this ASAP.

Thanks

**Comment by ltsuda** [comment]
By the error message, you element is hidden or partially hidden. I tested here but I don't know if the app should be like this.

This element below is that blue line? If so, the black box in partially blocking it, that's why your test is failing.

```javascript
const elem = firstWindow.locator(`(//*[contains(@class,'path-elm')])[1]`);
``` 

See the blue line is half hidden.
![image](https://user-images.githubusercontent.com/3965277/176891072-0af43fec-f2e9-4fad-84d8-08a9b5a38965.png)

Using brower's dev tools we can find the element, so the xpath is correct.
![image](https://user-images.githubusercontent.com/3965277/176891048-9d7bf684-27b3-4fb0-89aa-80f9bb9276de.png)

Is this how the UI supposed to be?

**Comment by stagefright5** [comment]
@ltsuda ,

I think the black box (which is `rect` element) is there to demostrate that only `path` element has this issue. To test your theory,
1. I commented all the tests in `main.spec.ts` except for the below 2 tests:
    - "Launch electron app"
    - "Click link"
2. Removed all the extra html from `home.component.html` file. Now, that file only has the below code:
```html
<svg width="200" height="200">
    <path class="path-elm" d="M 55 30 C 92.5 30 117.5 30 155 30" style="stroke: rgb(103, 123, 252)"></path>
</svg>
``` 
So, the app screen looks like this:
![image](https://user-images.githubusercontent.com/15051871/176955829-b369fc3c-aad4-42fc-8285-f36f2e79bb14.png)

After these changes, I ran `npm run e2e` as suggested by the OP and the result I got was this - The `path` element could not be recognized:
![image](https://user-images.githubusercontent.com/15051871/176955240-60cf499a-50a3-4a74-9eac-6160645b9c91.png)

**Comment by RizwanMR** [comment]
Yes, as @stagefright5 mentioned it is also throwing the error keeping only the line element in the page.

**Comment by ltsuda** [comment]
Hi guys, I **think** I found the issue but we need someone from the Playwright team to confirm.

Inspecting the SVG, the height of the path-elm is **zero**, so I think the actionability that playwright's checks makes the test to fail.

From https://playwright.dev/docs/actionability#visible:
`Element is considered visible when it has non-empty bounding box`, as the height is zero, the issue occurs because of it.

![image](https://user-images.githubusercontent.com/3965277/177244307-9412ed03-c4cd-4e33-939b-50976932c712.png)

Passing `force: true` to ignore the actionabilities, the test passes

```javascript
  test('Click link', async () => {
    const elem = firstWindow.locator('.path-elm');
    const text = await elem.click({force: true});
    expect(true).toBe(true);
  });
```

![image](https://user-images.githubusercontent.com/3965277/177244371-974fcd44-a656-45fd-ac1e-33cfa57e0ae6.png)

Another point is, trying a SVG example from https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#b%C3%A9zier_curves, we can see that both height x weight is **non-zero**, so playwright's clicks without the `force` option

```html
<svg width="190" height="160" xmlns="http://www.w3.org/2000/svg">
  <path
    class="test-tsuda"
    d="M 10 10 C 20 20, 40 20, 50 10"
    style="stroke: rgb(103, 123, 252)"
    fill="transparent"
  />
</svg>
```

```javascript
  test('Click test-tsuda @tsuda', async () => {
    const elem = firstWindow.locator('.test-tsuda');
    await firstWindow.waitForSelector('.test-tsuda', { timeout: 60 * 1000 });
    const text = await elem.click();
    expect(true).toBe(true);
  });
  ```
I hope this helps :)

**Comment by ltsuda** [comment]
Just a suggestion, if you are using `@Playwright/Test`, you can remove the `playwright` package/library. All import statements are present in `@Playwright/Test` as you can see below:

![image](https://user-images.githubusercontent.com/3965277/177245050-ee7fa329-ccce-471f-a783-d9e5d3d44bcc.png)

**Comment by RizwanMR** [comment]
It worked, but expecting it to click the element as it is visible on the page, and forcing the element click will bypass so many checks on the element.

**Comment by ltsuda** [comment]
Agreed, forcing is not the better way but let’s wait to someone confirm that was not working because one of the dimensions are zero.

**Comment by aslushnikov** [comment]
> Agreed, forcing is not the best way but let’s wait to someone confirm that was not working because one of the dimensions are zero.

This is correct. Clicking something with 0 width or height is tricky – the click target is literally non-existent, so Playwright doesn't know where to aim. Application users will have troubles clicking too.

If you absolutely want to click something that's 0-width or height, you should do it on your own risk using `"force"`, but it might fail!

**Comment by stagefright5** [comment]
@aslushnikov , I think the problem or disconnect in this case is that, the "path" element is **visible** on the screen which doesn't make sense if it was of height 0.
So, expecting the "click" to work as expected is normal.

**Comment by aslushnikov** [comment]
The visibility is strictly defined in our documentation: https://playwright.dev/docs/actionability#visible

Overall, I don't think we need to change anything in how Playwright behaves in this situation. The 0-size elements that are click targets are very rare, so they deserve the `force` treatment for now.

With this, I'll close this issue. However, please re-file if you think that we can do something or if something doesn't work!
