### ISSUE TITLE
[Question] Parsing and Saving Information from URL

### ISSUE THREAD

**Issue by viveksuarez7** [microsoft/playwright#15281]
Hi Playwright Team , i wanted to extract a specific data from the response url and use it later in my code . I extracted the data out with the help of page.on('response', res => { if (res.url().includes('https://flowforce-dev.net/***/****/***/***/***') && res.status() === 200) { var1 = res.url().split('-')[res.url().split('-').length - 1]; } return var1; }); but outside this page.on() block code this var1 becomes undefined outside the scope of the block . how can i save this variable for further use

**Comment by viveksuarez7** [comment]
`page.on('response', res => { if (res.url().includes('https://flowforce-dev.net/***/****/***/***/***') && res.status() === 200) { var1 = res.url().split('-')[res.url().split('-').length - 1]; } return var1; });`

This is the block of code

**Comment by rwoll** [comment]
Here's a snippet that is hopefully helpful. The basic idea is:

1. start watching for your response _before_ you start taking actions that may trigger it
2. take your actions
3. wait for the Promise to resolve with your parsed result which you can then use

```ts
// start waiting (but do not `await`) for your response
const parsedDataPromise = page
  .waitForResponse(resp => resp.status() === 200 && resp.request().url().includes('foo')) // change this predicate hover you'd like for your matching logic
  .then(resp => resp.request().url().split('/')[2]) // change this to parse the url and return whatever value you need from it

// do your actions that trigger the request/response you're looking for
await page.goto('https://example.com');
await page.click();

// when you need your parse result wait for it to show up
const result = await parsedDataPromise;
// now do whatever with the result
console.log(result);
```

--- 

This snippet is recommend over the one you've included since it avoids races. `on` handlers fire in the background, so returning a value from them won't be useful—there's nowhere to return them to. You could define a variable outside your listener (like `let var1 = null`), and set it inside your `on` handler, but there's no way of knowing if it's been updated in time for you to use it.

The example you included is analogous to writing:

```js
let greeting = null;
setTimeout(() => greeting = 'hi', 10000);
console.log(greeting);
```

which would print `null` and not `hi`.

**Comment by viveksuarez7** [comment]
Thanks for the help . It works absolutely as expected
