### ISSUE TITLE
[npx install] Allow to be installed trough yarn dlx and pnpm dlx

### ISSUE THREAD

**Issue by gunta** [microsoft/playwright#15369]
Currently, running `npx playwright install` uses **npm**, but since `npx` == `pnpm dlx` == `yarn dlx` are basically the same, one would expect it works without problem when running `pnpm dlx playwright install` or `yarn dlx playwright install`. 

Here is the check to fix:
https://github.com/microsoft/playwright/blob/9e62cc4da970b2256b4ecf35a4485adc4c40dd33/packages/playwright-core/src/utils/index.ts#L215

**Comment by mxschmitt** [comment]
The difference which I see, is that npx does run you local package, with the right package version and `dlx` downloads the package in an isolated environment and has nothing to do with your local NPM packages. Since having the right version installed, npx seems still the right choice. I think tho `pnpm exec playwright --help` or `yarn playwright --help` works as well.

See here:

- https://pnpm.io/cli/dlx
- https://yarnpkg.com/cli/dlx
- https://docs.npmjs.com/cli/v7/commands/npx/

Is there a bug or use-case which you propose to fix?

**Comment by aslushnikov** [comment]
I'll close this for now since there's no action item for the Playwright team regarding this.

Please re-file if you think otherwise!
