### ISSUE TITLE
[Question] Why does it seem like playwright is leaking memory?

### ISSUE THREAD

**Issue by brendonzimmer** [microsoft/playwright#15400]
Hi! I was curious on why playwright does not seem to let some memory be garbage collected no matter how old it is.

As an easy replicable example:
1. With playwright launch chromium
2. Make a page and make it go to, say, google.com
3. Simply refresh the page every X seconds

If you do this and nothing else, just refreshing the page every second would end up taking over 400mb of memory in about 20 minutes. This would be the RSS or Heap Total for the node process, not including the children chrome processes (which hover around the same memory usage the entire time).

I believe that most of the time people will be doing more than just reload a page between every X seconds, and if you _do_ do more, node can take up to 1gb of memory in less than 20 minutes of running. Here is my example tracking the memory for about 18 mins (also not too sure what happened to the rss in my graph because I verified it did not actually go down like that) <img width="1840" alt="Screen Shot 2022-07-05 at 4 41 54 PM" src="https://user-images.githubusercontent.com/80555186/177463555-43a33e56-3780-4929-9cd7-28f678724db0.png">

Anyways, I really hope this is an issue. I'm just not sure, so here I am.

**Comment by unlikelyzero** [comment]
@brendonzimmer https://github.com/microsoft/playwright/issues/6319

**Comment by brendonzimmer** [comment]
@unlikelyzero Thanks for that. I see a workaround can be to close the context and reopen, but is that how it is supposed to be? In other words, is the fact that the memory will keep growing if we do not close the context an issue that will be fixed? Thanks again.

**Comment by aslushnikov** [comment]
> Thanks for that. I see a workaround can be to close the context and reopen, but is that how it is supposed to be? In other words, is the fact that the memory will keep growing if we do not close the context an issue that will be fixed?

@brendonzimmer Playwright is focused on testing scenarios, where contexts are constantly closed and re-opened on a per-test basis. We store some useful metadata inside the context to aid with test debugging, and destroy this metadata as the context is closed. If the context is not closed, then all the debugging metadata is piling up.

So far the best workaround for the issue is to close & re-create context every once in a while. State could be preserved using [`browserContext.storageState()`](https://playwright.dev/docs/api/class-browsercontext#browser-context-storage-state) API. 

Folding this into https://github.com/microsoft/playwright/issues/6319!

**Comment by Kane-Baden** [comment]
For anyone coming back to this... I continued to have memory issues for long-running processes, the TLDR is that context closures do not currently kill all the related browser processes.

The TLDR is killing Chromium / Firefox processes along with Node processes resolved it.

Using Resource Monitor locally I could see the following:
- When you create a context, it generates a number of firefox/chromium processes (this is expected browser behaviour)
- When you close a context, it only closes the primary firefox/chromium process (looking at my own Task Manager it was getting to between 500mb and 1.1gb for this particular site). The other 10ish processes remain alive, taking up betwwen 500kb and 35mb each.
- In addition to the browser processes, the node process also created remains alive forever, taking about 20mbs per context opened.

Some screenshots are attached to show the memory usage of the Azure Container Instance but the same was being seem locally, across both Chromium and Firefox. Disregard the figures, its about the trend line since the execution time / parallel execution count being used etc... don't match.

By closing and creating a new context I was able to delay but not prevent memory from going sky high. You can see the dips in memory as the contexts are closed, releasing the memory being consumed by the primary browser context.

![PlaywrightMemoryExhaustion ContextClosuresAdded](https://github.com/microsoft/playwright/assets/125303112/f7aee50f-e7fc-482f-b52a-41ab7f905848)


When I finally figured to kill all Firefox processes after closing the context it further delayed the seemingly inevitable. The size of the dips are bigger compared to context closures alone but memory consumption is still trending up and up.

![PlaywrightMemoryExhaustion FirefoxProcessKillsAdded](https://github.com/microsoft/playwright/assets/125303112/7053fc7c-bd19-4e97-ab6b-e61284f4855f)


At this stage I added killing the Node processes after the firefox kills, resulting in the process being able to inflate and then return to pretty much baseline consumption.

![PlaywrightMemoryExhaustion FirefoxAndNodeKillsAdded](https://github.com/microsoft/playwright/assets/125303112/0c5ad9a2-0637-407e-b555-c8d1767e17a0)

This particular process runs for up to 4hours at a time so i can't extend the runtime any further so its unclear whether it'd be able to run for days at a time but it seems to have resolved the issue at this scale.

**Comment by mpawelskipwc** [comment]
Authors, have you managed to take a glance at this issue? Doing workarounds with killing nodejs and browser procceses should not be suggested approach as we migitate playwright library memory issue by ourselves.
With a couple of hundreds tests, after 2 hours of test run (before it's finished), we get to the point where Playwright uses all available memory on the machine - in this case it's 16GB. It causes release and VM to crash, because Playwright keeps the trash in the memory and overflows it.
There are dozens, if not hundreds of node.exe and chrome.exe processes that should be removed by the playwright.
I'm using playwright 1.38 with .NET

**Comment by DavidCodesDev** [comment]
Bump, this is an extreme issue

**Comment by jankarres** [comment]
We see the exact same behaviour has @Kane-Baden shown in https://github.com/microsoft/playwright/issues/15400#issuecomment-1709261002 with the graphs. We also create and close contexts.

Since this issue (and https://github.com/microsoft/playwright/issues/6319 with a similar error) has been closed, we will unfortunately have to consider alternatives to Playwright for the time being, as productive operation with regular (external) process kills does not seem practicable. We would be pleased if this problem could be looked at again!

**Comment by DeLaphante** [comment]
@jankarres - This can't be resolved unless Playwright reverts to using the traditional HTTP which is stateless. Websockets are stateful and this very fact is what will be causing memory leaks especially when you start scaling the number of tests. 

This issue is again raised in the following ticket -> https://github.com/microsoft/playwright/issues/28942

**Comment by jankarres** [comment]
(Comment without added value for the problem debugging)

@DeLaphante Unfortunately, I would like to disagree with you. Websockets in itself is not a generally "broken standard" that must lead to memory leaks. However, websockets must be implemented and used correctly, just like any other standard.

Regarding this ticket, I do not assume that this is a problem with the websocket implementation, as you claim without concrete evidence, but as @Kane-Baden described and shows in his charts on not fully closed contexts in Chromium. This behavior was, as I wrote, exactly the same on my machine, so I did not attach any further evidence to his thesis. With my comment, I only wanted to point out that we are running into the same problem, even though this ticket was closed.

**Comment by DeLaphante** [comment]
@jankarres I didn't say anything about Websockets being "broken" or that it is inherently supposed to leak memory. My argument was that using Websockets as a protocol for a testing framework that will need to scale or have long running processes will cause memory leaks.

Websockets works fine for applications that use a small number of active connections on the client side and that is what generally happens in reality and its usually on the server side that needs to be designed and configured well to manage hundreds or thousands of these active client connections.

**Comment by FrenziedIM** [comment]
Have been this, but its not ideal:

```
def kill_node_exe_processes_older_than(minutes:int):
    while(True):
        current_time = time.time()
        for proc in psutil.process_iter(['pid', 'name', 'cmdline']):
            if proc.info['name'] == 'node.exe':
                process_age_seconds = current_time - proc.create_time()
                if process_age_seconds > (minutes * 60):
                    print(f"Killing node.exe process {proc.pid} because it is older than {minutes} minutes")
                    proc.kill()
        time.sleep(5)
```

Thought playwright async might fix the issue. Unfortunately, I spent a day of my life (due to big project) switching to async, and my problem was not solved.

Probably will go back to above solution, but really not happy. I cannot believe this is a thing in 2024.

**Comment by DavidCodesDev** [comment]
Anyone know good Playwright alternatives that can do Lighthouse queries that don't have this absolutely ridiculous issue?

**Comment by ldonjibson** [comment]
> Have been using this, but its not ideal:
> 
> ```
> def kill_node_exe_processes_older_than(minutes:int):
>     while(True):
>         current_time = time.time()
>         for proc in psutil.process_iter(['pid', 'name', 'cmdline']):
>             if proc.info['name'] == 'node.exe':
>                 process_age_seconds = current_time - proc.create_time()
>                 if process_age_seconds > (minutes * 60):
>                     print(f"Killing node.exe process {proc.pid} because it is older than {minutes} minutes")
>                     proc.kill()
>         time.sleep(5)
> ```
> 
> Thought playwright async might fix the issue. Unfortunately, I spent a day of my life (due to big project) switching to async, and my problem was not solved.
> 
> Probably will go back to above solution, but really not happy. I cannot believe this is a thing in 2024.

FOR LINUX USE 

def kill_node_exe_processes_older_than(minutes:int):
    while(True):
        current_time = time.time()
        for proc in psutil.process_iter(['pid', 'name', 'cmdline']):
            if 'node' in proc.info['name']:
                process_age_seconds = current_time - proc.create_time()
                if process_age_seconds > (minutes * 60):
                    print(f"Killing node.exe process {proc.pid} because it is older than {minutes} minutes")
                    proc.kill()
        time.sleep(5)

**Comment by wojtekKrol** [comment]
@Kane-Baden but my whole app is about running playwright, I cannot just kill it once in a while

**Comment by Kane-Baden** [comment]
> [@Kane-Baden](https://github.com/Kane-Baden) but my whole app is about running playwright, I cannot just kill it once in a while

I can appreciate that, didn't mean to suggest that my post was the solution. Just wanted to provide the workaround that I ended up using while providing as much detail to the maintainers incase it gets further consideration. 

Given its primary a testing framework I would imagine this issue isn't a high priority given most tests are short lived - hopefully you're able to find some way around it.

-Kane

**Comment by anggaaryas** [comment]
have you guys trying https://github.com/autoscrape-labs/pydoll ?

**Comment by squarewave24** [comment]
+1 here. 
using playwright to verify 32 pages to ensure they are up to date, and the process (python running in docker) blows past 9 gigs. 
Has anyone tried manually disposing pages or beautifulsoup objects?

**Comment by ScarletMcLearn** [comment]
Facing similar issue: https://github.com/microsoft/playwright/issues/36337

**Comment by ScarletMcLearn** [comment]
@brendonzimmer @unlikelyzero  @aslushnikov  @Kane-Baden  @mpawelskipwc  @DavidCodesDev  @jankarres  @DeLaphante  @FrenziedIM  @milad2golnia  @squarewave24  @milad2golnia  @squarewave24  @ldonjibson  @wojtekKrol  @anggaaryas  @yury-s   please do give it a look and suggest if you faced your issue under similar conditions!

**Comment by DavidCodesDev** [comment]
It's simple, I just ditched playwright lmao

**Comment by AlexGrinMitrix** [comment]
Facing the same issue. My code just connects to the browser OverCDP and closes it
<img width="1796" height="1252" alt="Image" src="https://github.com/user-attachments/assets/3a4b9c30-c685-4ab0-adae-9f6a7384b2e4" />

**Comment by DeLaphante** [comment]
@ScarletMcLearn @AlexGrinMitrix  - just as @DavidCodesDev said - you need to ditch playwright until they fix it

**Comment by ScarletMcLearn** [comment]
Yeah, sad there's no way to help them reproduce this

**Comment by yanpgwang** [comment]
Does this issue solved now?

**Comment by fiskolini** [comment]
2026, and this is still happening.

<img width="827" height="432" alt="Image" src="https://github.com/user-attachments/assets/5348d121-0b73-4f19-90b4-0d606571f796" />

1. Leaving a long-living browser;
2. Creating a new context and a new page on every usage;
3. Closing both context and page after execution.

```ts
@scoped(Lifecycle.ContainerScoped)
export class ThumbnailTakerService {
  public constructor(
    @inject(SharedTokens.EnvironmentName) private readonly environmentName: EnvironmentName,
    @inject(Tokens.Config) private readonly config: Config,
    @inject(Tokens.Chromium) private readonly browserPromise: Promise<Browser>
  ) {}

  /**
   * Captures a thumbnail screenshot for the given lesson.
   */
  public async screenshotLesson(lessonId: string): Promise<Buffer> {
    const context = await this.createContext();
    const page = await context.newPage();

    try {
      const url = this.buildUrl(lessonId);
      const { thumbnail: thumbnailConfig } = this.config;

      await page.goto(url, {
        waitUntil: 'networkidle',
        timeout: thumbnailConfig.timeouts.pageNavigationMs,
      });

      const locator = page.locator(thumbnailConfig.elementSelector);

      await locator.waitFor({
        state: 'visible',
        timeout: thumbnailConfig.timeouts.elementVisibilityMs,
      });

      return await locator.screenshot({ type: 'png', omitBackground: true });
    } finally {
      await page.close();
      await context.close();
    }
  }

  /**
   * Builds the URL to capture the thumbnail from.
   */
  private buildUrl(lessonId: string): string {
    const { pageSecret } = this.config.thumbnail;
    const { search: searchBaseUrl } = environmentToAppUrlMap(this.environmentName);
    const normalizedSearchUrl = searchBaseUrl.replace(/\/+$/, ''); // strip trailing slash
    const url = new URL(`${normalizedSearchUrl}/${lessonId}`);

    return url.toString();
  }

  /**
   * Builds a new browser context with the appropriate settings for thumbnail capture
   */
  private async createContext(): Promise<BrowserContext> {
    const browser = await this.browserPromise;
    const { thumbnail } = this.config;

    return browser.newContext({
      viewport: {
        width: thumbnail.viewportSettings.width,
        height: thumbnail.viewportSettings.height,
      },
      javaScriptEnabled: true,
      deviceScaleFactor: thumbnail.scaleFactor,
    });
  }
}
```

Disabling features didn't help that much.

```ts
container.register<Promise<Browser>>(Tokens.Chromium, {
  useFactory: instanceCachingFactory(async () => {
    return chromium.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-gpu',
        '--disable-dev-shm-usage',
        '--disable-background-networking',
        '--disable-background-timer-throttling',
        '--disable-renderer-backgrounding',
        '--disable-extensions',
      ],
    });
  }),
});
```

**Comment by DavidCodesDev** [comment]
Since the start of this issue I have travelled to 10 different countries, got married, did a honeymoon in the Maldives and I'm intentionally not having a child to make this github issue not look more ridiculous

**Comment by ScarletMcLearn** [comment]
Yup. Can still say this issue is still there. Sad.

**Comment by DeLaphante** [comment]
If anyone is interested I previously created a Linkedin post of why you should choose "determinism" (Selenium) over "convenience" (Playwright). Hopefully this will enlighten you with a bit more detail and develop an understanding of why this issue continues to exist and why it can't be fixed. Enjoy 🙂
👇🏾
https://www.linkedin.com/posts/christian-delaphante-855067254_testautomation-selenium-engineeringdiscipline-activity-7427630063665315841-n4fi?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD6oGgEBbTHg0U2BfE0cm7MyZ7Z3oexWAeU

**Comment by moaddib666** [comment]
OMG... 41 recycles fired but each one reaped only 2 processes ([2089, 2090], [2147, 2148], [2203, 2204]…). Meanwhile our snapshot showed 8+ chrome
  processes alive. The recycles are killing only the immediate playwright driver pair — not the chromium browser tree. PID 2413 (the 1.32 GB leaker)
  survived multiple recycles ang frowing.... 
As a workeround i can just kill them. but this is so annoing... And it take so much time to figure it out, before i reach this post that confirm the issue exist not only on my env...

**Comment by laztheripper** [comment]
Fixed it, might break other stuff but for my uses, it was fine.
`playwright/_impl/_sync_base.py:97`
```python
  def _sync(self, coro):
      ...
      task = self._loop.create_task(coro)
      setattr(task, "__pw_stack__", inspect.stack(0))                 # <-- leak
      setattr(task, "__pw_stack_trace__", traceback.extract_stack(limit=10))  # <-- leak
      task.add_done_callback(lambda _: g_self.switch())
      while not task.done():
          self._dispatcher_fiber.switch()
      asyncio._set_running_loop(self._loop)
      return task.result()
```
replace the two lines with
```python
      setattr(task, "__pw_stack__", [])
      setattr(task, "__pw_stack_trace__", [])
```
These two are preventing the tasks from cleaning up, causing a (massive) memory leak.

**Comment by moaddib666** [comment]
I have already switched to selenium so can't test the fix, but please give some feedback about this.

Interesting note on selenium I use avg 400mb while on pw 1.5g for the same tasks

**Comment by DavidCodesDev** [comment]
Lol so funny Claude Fable is out and it's finally fixed

**Comment by moaddib666** [comment]
> Lol so funny Claude Fable is out and it's finally fixed

Nothing to add here ;)

**Comment by laztheripper** [comment]
> Lol so funny Claude Fable is out and it's finally fixed

I post a fix and people say it's claude -_-. To be clear, I have never used Fable. And I found this via profiling, not AI.

**Comment by moaddib666** [comment]
> > Lol so funny Claude Fable is out and it's finally fixed
> 
> I post a fix and people say it's claude -_-. To be clear, I have never used Fable. And I found this via profiling, not AI.

IMO: Great work! Nothing to add here !)
