### ISSUE TITLE
playwright How do I connect to an open browser？

### ISSUE THREAD

**Issue by jiangyijin** [microsoft/playwright#15519]
My code is like this

u = 'https://www.baidu.com/'
sy = sync_playwright()
qd = sy.start()
bo = qd.chromium.connect(“ws://localhost:9222”)
pg = bo.new_page()
pg.goto(u)
bo.close()
qd.stop()

But I will report such a mistake
“websocket.connect: server rejected WebSocket connection: HTTP 404”

How to solve this? Please, everyone！

**Comment by rwoll** [comment]
Based on the 9222 port, it looks like you have a Chromium CDP address. Try [`connect_over_cdp`](https://playwright.dev/python/docs/api/class-browsertype#browser-type-connect-over-cdp) instead of `connect`. 

- [`browserType.connect`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-connect) is different from [`browserType.connectOverCDP`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-connect-over-cdp)
- `browserType.connectOverCDP` is used to connect to a remote **_Chromium_** CDP Session/Endpoint.
- `browserType.connect` is used to connect to a remote **_Playwright_** Server launched via [`browserType.launchServer`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-launch-server).

(Related https://github.com/microsoft/playwright/issues/15265#issuecomment-1172860134)

**Comment by mxschmitt** [comment]
Closing as per above.

**Comment by jiangyijin** [comment]
> 根据 9222 端口，您似乎有一个 Chromium CDP 地址。请尝试[`connect_over_cdp`](https://playwright.dev/python/docs/api/class-browsertype#browser-type-connect-over-cdp)而不是 。`connect`
> 
> * [`browserType.connect`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-connect) 不同于 [`browserType.connectOverCDP`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-connect-over-cdp)
> * `browserType.connectOverCDP`用于连接到远程 **_Chromium_** CDP 会话/终结点。
> * `browserType.connect`用于连接到通过 [`browserType.launchServer`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-launch-server) 启动的远程**_剧作家_**服务器。
> 
> （相关 [#15265 （评论）](https://github.com/microsoft/playwright/issues/15265#issuecomment-1172860134))

Thank you for your help, but unfortunately, it still failed. According to your method, a new error is reported. The error information is as follows:
playwright._impl._api_types.Error: WebSocket error: Unexpected server response: 404
=========================== logs ===========================
<ws connecting> ws://localhost:9222
<ws error> [object Object]
<ws connect error> ws://localhost:9222 Unexpected server response: 404
<ws disconnected> ws://localhost:9222 code=1006 reason=
============================================================

I started a browser by adding such an instruction to the shortcut:--remote-debugging-port=9222 --user-data-dir="E:\playwright"
After adding this instruction, I opened the browser in the form of double-click shortcut on my computer.
