### ISSUE TITLE
[BUG] Support for the experimental syntax 'decorators-legacy' isn't currently enabled

### ISSUE THREAD

**Issue by MattGson** [microsoft/playwright#15524]
**Context:**
- Playwright Version: 1.22
- Operating System: Mac
- Node.js version: 16

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript

import { test, expect } from '@playwright/test';

test.describe('CustomDecorator', () => {
    class TestClass {
    
	    @CustomDecorator()
	    public async a(): Promise<string> {
		    return 'test'
	    }

    }
    
    test('Works', async () => {
	    const testInstance = new TestClass();
    
	    const result = await testInstance.a();
    
	    expect(result).toBe('test');
    });
});


```

**Describe the bug**

```
 Support for the experimental syntax 'decorators-legacy' isn't currently enabled
```

I cannot find a way to test code that contains Typescript decorators.
I have seen several issues around this all closed without a solution.

**Comment by mxschmitt** [comment]
If you need advanced TS feature / Babel stuff, you can compile the tests yourself with source-map, then Playwright Test will figure it out correctly to map the files back to its origin, see here how it works: https://playwright.dev/docs/next/test-typescript#manually-compile-tests-with-typescript

Since they are legacy, we most likely don't want to support them, as written in https://github.com/microsoft/playwright/issues/12105#issuecomment-1074548033.

**Comment by MattGson** [comment]
Ok, thanks. I will do that instead.
