### ISSUE TITLE
[BUG] firefox's `node.scrollIntoView({behavior: 'instant'})` is not instant :(

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#1552]
This is investigation for the failing firefox test: 
https://github.com/microsoft/playwright/blob/b24262b46f8bda581b5a82038be2b47a80c20ec4/test/elementhandle.spec.js#L303

1. Looks like Firefox doesn't support `'instant'` behavior in `scrollIntoView()` argument.
2. It was noticed before: https://bugzilla.mozilla.org/show_bug.cgi?id=1570605

The following snippet demonstrates that `window.scrollTo(0, 0)` doesn't actually scroll to (0, 0).. And the `element.scrollIntoView()` command continues working after we scroll window.

```js
const {firefox, chromium} = require('.');

(async() => {
  const browser = await firefox.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.setContent(`
    <style>
      * {
        margin: 0;
        padding: 0;
        position: absolute;
      }

      body, html {
        width: 100%;
        height: 100%;
      }

      button {
        width: 100px;
        height: 20px;
        right: -20px;
        top: 50px;
      }
    </style>
    <button>yo</button>
  `);

  console.log(await page.evaluate(async () => {
    const measures = [];
    document.querySelector('button').scrollIntoView({behavior: 'auto'});
    measures.push({
      'window.scrollX': window.scrollX,
      'window.scrollY': window.scrollY,
    });
    await new Promise(x => setTimeout(x, 30));
    window.scrollTo(0, 0);
    measures.push({
      'window.scrollX': window.scrollX,
      'window.scrollY': window.scrollY,
    });
    for (let i = 0; i < 15; ++i) {
      await new Promise(x => requestAnimationFrame(x));
      //await new Promise(x => setTimeout(x, 30));
      measures.push({
        'window.scrollX': window.scrollX,
        'window.scrollY': window.scrollY,
      });
    }
    return measures;
  }));
  await browser.close();
})();
```

Compare output results between Chromium and Firefox browsers. On Chromium, all measurements after `window.scrollTo(0, 0)` end up to be (0, 0). On Firefox, they return to (20, 0) for me.

**Comment by pavelfeldman** [comment]
I think Yury foxed it

**Comment by catamphetamine** [comment]
I also encountered this bug with the latest versions of `playwright` and Firefox.

Steps to reproduce:

* Clone the repo: https://github.com/catamphetamine/navigation-stack/
* `npm install`
* `npm test` — This will download the latest browsers and run "Web Test Runner" with Playwright
* See how the tests pass
* Go to `ScrollPositionRestoration.test.js`
  * Uncomment line: `// window.NAVIGATION_STACK_DEBUG_ENABLED = true`
  * Find line `it('should emulate browser scroll behavior', (done) => {` and change `it(` to `it.only(`
  * Search for `if (isFirefoxBrowser)` line and comment out the `if` block
* `npm test`
* See how one test starts throwing an error in Firefox: `expected 107.76667022705078 to be close to 108.43334197998047`
* Go to `WebBrowserScrollPosition.js` and change `anchorElement.scrollIntoView()` to `anchorElement.scrollIntoView({ behavior: 'instant' })`
* `npm test`
* See how nothing has changed

The tests were passing in Firefox fine when it was using Karma, but this weekend I migrated it to "Web Test Runner" + Playwright and that one test started erroring, which has then been pinpointed to this specific bug: a late scroll event arrives when no one expects it to, due to the "smooth" scrolling instead of "instant" one, which distorts the expected picture.
