### ISSUE TITLE
[BUG] inspector highlights all elements instead of child elements of the `ElementHandle` when using `ElementHandle.$`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#15548]
**Context:**
## System:
 - OS: Windows 10 10.0.19044
 - Memory: 1.52 GB / 15.78 GB
## Binaries:
 - Node: 18.0.0 - C:\Program Files\nodejs\node.EXE
 - npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
## npmPackages:
 - playwright: ^1.23.0 => 1.23.0

**Code Snippet**

```ts
test('basic test', async ({ page }) => {
    await page.goto('https://google.com/')
    await page.fill('input[aria-label="Search"]', 'asdf')
    const center = await page.$("//center[input[@class='gNO89b']]")
    const button = await center?.$('input')
    await button!.click()
})
```

**Describe the bug**

when running the above code, the inspector highlights all `input`s on the screen. however that selector is only matching inputs that are children of the `//center[input[@class='gNO89b']]` element, as it's using `center.$`.

the inspector should match what the selector actually does and only highlight the child `input`s of the `center` element

![image](https://user-images.githubusercontent.com/57028336/178377143-1396c9cc-87b5-4f6d-98a6-34fedc381a3a.png)

related: https://github.com/microsoft/playwright/issues/12201#issuecomment-1046420386

**Comment by yury-s** [comment]
The highlighter doesn't take the element handle into account  and indeed matches all element in the page currently. On the other hand element handles are discouraged and unless you have a good reason to use handles we recommend you use locators which are not susceptible to this issue:

```js
test('basic test', async ({ page }) => {
    await page.goto('https://google.com/')
    await page.fill('input[aria-label="Search"]', 'asdf')
    const center = page.locator("//center[input[@class='gNO89b']]")
    const button = center.locator('input')
    await button.first().click()
})
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
