### ISSUE TITLE
[Question] Is it possible to get props of a react component in a react app?

### ISSUE THREAD

**Issue by Kranael** [microsoft/playwright#15669]
So for example I have a react app that has some components (p, ke, i)

```
let component = page.locator("_react=i[key='profile']").locator("_react=p[key='1']")
````
So this component has some props like "surname", "lastname", "adress" and so on.

How can i get the values of this props?

In react it would be:

```
<p>{props.surname}</p>
```

but how i get the values so i can test it?
i thought about `component.getAttribute('surname')` but that doesn't work :/

I have not found anything to get props only to search locator based on props for example:
https://playwright.dev/docs/selectors#react-selectors

Thanks for help

**Comment by yury-s** [comment]
You can do it when running react in dev (which is probably the case since `_react` selectors only work in dev mode) but it's not trivial and depends on the react version used. You can have a look at how `_react` selector implementation does it for inspiration: https://github.com/microsoft/playwright/blob/0a01a9456a77fcef8266118b109d141cf529a69b/packages/playwright-core/src/server/injected/reactSelectorEngine.ts#L182-L188
