### ISSUE TITLE
[Feature] Customize HTML reports with project meta-data

### ISSUE THREAD

**Issue by napsta32** [microsoft/playwright#15671]
We want to show html reports with the project information like:
- Build number
- Build version
- Project name
- Pull request id/link

Ideally we would like to modify the report using a handlebars template. Currently I am using a `patch-package` to modify the `index.html` in `playwright-core` to do this.

**Comment by rwoll** [comment]
Relates https://github.com/microsoft/playwright/issues/11319

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
