### ISSUE TITLE
[Feature] Experimental Service Worker Network Events 

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#15684]

**Comment by joshbrooks** [comment]
I tried this, our use case is in being able to mock 404's and 500's from service worker requests, to test an offline-first experience handling both GET and PUT/POST requests from service workers. Using the "experimental" flag "PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS" from Python with `1.25.2` seems to have no effect:

```python
os.environ["PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS"] = "1"
```
```python
  route.fulfill(
      status=HTTPStatus.INTERNAL_SERVER_ERROR,
      content_type="text/plain",
      body="not found!"
  )
```

This still returns a 200 from the service worker. Other (non-service-worker) requests return a 500 though

As a workaround, for some tests it's sufficient just to block service workers

`context = browser.new_context(service_workers='block')`

**Comment by wentokay** [comment]
Thanks for adding this experimental feature. I'm using it when testing a chrome browser extension.

Network requests are made from the background script (which is a serviceworker due to [manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/) requirements) 

It seems to be doing what I need right now but will report back if there are any issues.

**Comment by smokir** [comment]
@wentokay could you please share some configuration examples? I've been doing the same thing (chrome extension on v3 manifest) and using `playwright` with `jest-playwright-preset` for e2e testing. But got no luck mocking API requests coming from a service worker.

**Comment by damienforster** [comment]
Interested in this also for Playwright testing a manifest v3 extension.  Currently I'm not seeing requests from the service worker getting picked up, even with the PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS flag

**Comment by smokir** [comment]
@damienforster I had the same problem because I was using `jest-playwright-preset` instead of `@playwright/test`

**Comment by MSOwnExperiment** [comment]
> Thanks for adding this experimental feature. I'm using it when testing a chrome browser extension.
> 
> Network requests are made from the background script (which is a serviceworker due to [manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/) requirements)
> 
> It seems to be doing what I need right now but will report back if there are any issues.

I also have the same use case. I could fetch the background page for Manifest V3. However, this part is not working for me. 
const [request] = await Promise.all([
            background.waitForRequest(request => request.postDataJSON().)
])

**Comment by rjones-sw** [comment]
Thanks for adding this experimental feature! Like wentokay I'm also using it when testing a chrome browser extension (which is similarly using service workers due to manifest v3 requirements)

**Comment by orenyomtov** [comment]
This is not working for me trying to intercept/log requests originating from a chrome extension's background page using manifest v3, using `playwright v1.29.1` and setting env var `PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS=1`

It seems that it worked for @wentokay @smokir @rjones-sw , but didn't work for @joshbrooks @damienforster @MSOwnExperiment 

Any suggestions would be welcome

**Comment by MSOwnExperiment** [comment]
> This is not working for me trying to intercept/log requests originating from a chrome extension's background page using manifest v3, using `playwright v1.29.1` and setting env var `PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS=1`
> 
> It seems that it worked for @wentokay @smokir @rjones-sw , but didn't work for @joshbrooks @damienforster @MSOwnExperiment
> 
> Any suggestions would be welcome

I could resolve this. I did not have to use background page for manifest V3 and I could read events from context.

**Comment by orenyomtov** [comment]
Found a solution!
You must explicitly set `serviceWorkers: "allow"`, although `allow` is the default value!

**Comment by akaltar** [comment]
Thanks for this experimental feature.
I'm using this to test that a service worker fetch handler can be turned on/off with feature flags reliably, and that it can reconstruct range requests from the cache. Also planning to test what happens in case of IndexedDB errors and performance/memory usage in various network conditions

**Comment by adrienbrault** [comment]
I am testing a browser extension that makes http requests within a service worker. I am using `context.routeFromHAR` to be able to play my tests offline. However, http requests made by the service worker are not included in the HAR file.

Using `PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS=1` fixes this: requests made by the service worker are correctly saved to the HAR file. When `update: false` it also works as expected and the service worker requests use the HAR file.

Support for Microsoft Edge would be nice!

**Comment by anirudh1713** [comment]
Thanks for this experimental feature! We want to use it for testing browser extension. (We make requests from background service worker).

**Comment by tikolakin** [comment]
Hi there,
there seem to be a regression issue with registering service worker interception on new context.
I have notices that the [v1.37.0](https://github.com/microsoft/playwright/releases/tag/v1.37.0) introduces this issue likely due to a greater chromium version `116.0.5845.82`. Previous versions 1.36 and 1.35 are free of the bug

Browser context is created in fixture as shown on the screenshot. Note it is a persistent context with loaded browser extension, worker scope.
<img width="950" alt="image" src="https://github.com/microsoft/playwright/assets/5860505/600572d4-2c88-41ee-b529-a85159ec00d9">

here is a routing handler
<img width="822" alt="image" src="https://github.com/microsoft/playwright/assets/5860505/5e9fe167-aafa-4f70-9156-bd2b62d7500d">

I added `await page.pause()` at the very beginning of a page to skip not relevant things down the line

If you have a look at the `pw:channel:event` logs (attached below)
and search for `https://localhost:10584/api`
you will find that v1.37.0 is missing service workers events.
In contrast you can find service workers interception events in the 1.36.2

[v1.36.2.txt](https://github.com/microsoft/playwright/files/12423428/v1.36.2.txt)
[v1.37.0.txt](https://github.com/microsoft/playwright/files/12423429/v1.37.0.txt)

The behaviour is the following
when a first test runs - no interceptions of service worker request happens, all requests just fails as there is no response from an intercepted endpoint.
However, when second tests runs - interception of the service worker request begin working.
Interception continue to work for the rest of the tests in a given worker.

It would be great to find out a root cause of the issue.

Thanks

**Comment by vbolshutkin** [comment]
A lovely feature! Really looking forward to get it available in Java API.

We use Service Worker as a backend for offline-enabled app

**Comment by jojobii-arks** [comment]
Thank you! Using this to test browser extension service worker network requests as well 👍

**Comment by CiaranMn** [comment]
I would like to use this feature to inspect websocket messages sent from a service worker (an extension background script). 

I can see other network requests the service worker sends via `context.on("request")` and `context.route` – which is great! – but not websocket activity from the service worker. Is there an equivalent to `page.on("websocket")` for service workers, or other way of achieving this? The websocket is being opened and messages sent to the API during the test.

**Comment by davidstrouk** [comment]
I am using this feature in order to mock requests in Chrome extension with manifest v3. Thank you for letting us use this experimental feature!

**Comment by mnholtz** [comment]
We are using this feature in order to support testing our browser extension; it has satisfied our needs so far! The support is much appreciated.

**Comment by turt2live** [comment]
Dropping in to say we tried using the experimental support, but it ended up not working out for us. Our use case was to use the service worker to append `Authorization` headers to requests in `<img />` tags, with credentials being stored in IndexedDB. This means we very quickly ran into https://github.com/microsoft/playwright/issues/11164 because service workers cannot access localstorage, making the mock/shim unusable.

**Comment by GorvGoyl** [comment]
Here's what worked for me to intercept api calls from chrome extension (head as well as headless):

fixture.ts:
```js
export const test = base.extend<{ context: BrowserContext; extensionId: string[] }>({
    context: async ({context}, use) => {
        const chatGptWriterExtensionPath = resolve(process.cwd(), './build/chrome-mv3-prod');
        const browserContext = await chromium.launchPersistentContext('', {
            headless: false,
            args: [
                `--headless=new`, //can comment this line to see browser
                `--disable-extensions-except=${chatGptWriterExtensionPath}`,
                `--load-extension=${chatGptWriterExtensionPath}`,
                `--disable-blink-features=AutomationControlled`,
                `--disable-dev-shm-usage`,
            ],
        });
        await use(browserContext);
        await browserContext.close();
    },
    extensionId: async ({ context }, use) => {
        let [background] = context.serviceWorkers();
        const serviceWorkers = context.serviceWorkers();
        const extensionIds = serviceWorkers.map((worker) => worker.url().split('/')[2]);
        if (!background) {
            background = await context.waitForEvent('serviceworker');
        }
        await use(extensionIds);
    },
});

export const expect = test.expect;

```

test:
```js
// https://playwright.dev/docs/service-workers-experimental

process.env.PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS = '1';

test('is request body ok', async ({ page, context, extensionId }) => {

    let [background] = context.serviceWorkers();
    if (!background) {
        background = await context.waitForEvent('serviceworker');
    }

    context.on('request', (worker) => {
        if (worker.url().includes('api/ai/generateStreamingResponse')) {
            apiBody = worker.postData();
            expect(apiBody).toBe(expectedApiBody);
        }
    });

    await performActionOnExtension(page);

});

```

**Comment by denniscual** [comment]
Im using this feature to set custom headers to all requests, including service worker, made by app to a list of servers.

**Comment by BrunoBernardino** [comment]
I'm using this feature to test if a service worker registers successfully (confirming it doesn't throw any error on setup).

**Comment by awerchniak** [comment]
I would like to use this feature to monitor network events from a chrome extension running within my test environment. Unfortunately I don't believe that it's possible with playwright Python today, but if it is please let me know!

**Comment by fsebalien** [comment]
Thanks for adding this experimental feature ✌️ I'm using it in our Angular web application, where we rely on a service worker to cache user data for offline use. I simulate the browser going offline and check how the UI responds when it’s offline. I also validate that the service worker is activated since it's crucial for loading the cached user data on the UI in offline mode.

We use a web manifest in our app (https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Manifest) which includes the service worker setup. So fortunately Playwright experimental feature helps me to ensure that the service worker behaves as expected when the network is offline.

So far it’s working nice for me, but I’ll definitely report back if I encounter any issues.

**Comment by zmorrisCB** [comment]
Any chance we can get this feature for webkit as well? It works on chrome, but we also need to run our webkit tests against mock service workers. Thanks!

**Comment by getchardy** [comment]
This is great! Using it for testing manifest 3 Chrome web extension.

**Comment by vladutjs** [comment]
I am looking to use this feature while testing a chrome extension.
Settings `PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS` is not helping me though intercept all HTTP requests done by the extension service worker.

**Comment by kujo4pm** [comment]
Definitely using this. It's super important for qualified and complex PWAs. Without this support I would have moved to another framework. Thankyou.

**Comment by Georgegriff** [comment]
I've been investigating this issue https://github.com/mswjs/msw/issues/2589, where msw doesn't work if you use `page.route` for network interception because msw/browser uses a service worker, and so Playwright doesn't see those requests.
I'm not a maintainer of either the packages, but a consumer of msw who is unable to use these tools together because of this playwright limitation, but works if i turn on the flag and switch the vitest code to context.route too

https://github.com/mswjs/msw/issues/2589#issuecomment-3358126693

https://github.com/vitest-dev/vitest/blob/c347487e676eb62378e17f051a40b4c09cd718f1/packages/browser-playwright/src/playwright.ts#L256


So another potential use case, commenting as it mentions to in the docs site
