### ISSUE TITLE
[Feature] Add view for all console.logs and network in the Trace Viewer

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#15712]
It would be cool to list all network activity and all browser console.logs at once (including not completed and routed), not just what happened during the current action. So, in general, I want to see what happened in the browser Devtools → Network tab during the test, as is. That is not a good practice, but sometimes we have >300 actions per test, so it is hard to collect all the network activity of just one test.

![image](https://user-images.githubusercontent.com/2929442/179234182-a28e99c1-7738-4660-8645-aecbb0121397.png)

Originally discussed here https://github.com/microsoft/playwright/issues/15567

**Comment by Diokuz** [comment]
Will you add version label on this issue?)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
