### ISSUE TITLE
page.fill or page.type clears previous inputted values

### ISSUE THREAD

**Issue by vivekVells** [microsoft/playwright#15734]
playwright: 1.23.3 (pretty much installed playwright from scratch and started)

In a login form, somehow previously inputted element values are getting cleared automatically. steps: 

1. open login form
2. input values in `Username` input field (using await page.fill(..))
3. now, inputting values in `Password` input field (using await page.fill(..))

issue: values inputted in `Username` is cleared

similar issue when doing page.type;

any thoughts?

_Originally posted by @vivekVells in https://github.com/microsoft/playwright/discussions/15655_

**Comment by vivekVells** [comment]
thanks for responding @dgozman; that didn't work; but, it did gave me an idea on what's going on. 

looks like the auto page waiting is not working like we'd expect. after adding delay for like 5 seconds and then inputting the text values of username and password worked. 

so, the flow is: 

1. click 'Login' button that loads the login page
2. introduce delay for 5 seconds
3. input username 
4. input password (when inputting this, username value is not cleared)

introduced delay by using this: 
```typescript
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
delay(5000)
```

Quick question: 
why is auto page (https://playwright.dev/docs/actionability) wait feature not working like we'd want? 

can you please confirm if i am missing something?

**Comment by dgozman** [comment]
@vivekVells Auto wait works for specific cases, like element not being enabled and similar things described in the documentation. This case seems to be different.

My guess it that the page is not ready for the user during the first 5 seconds, so you can enter value in the input but it will be cleared. In this case you have just found a bug in the page your are testing! You have two options here:
- Fix the bug in the page so that it does not ignore user input. For example, make the input disabled until it is ready to accept the value. Auto waiting will pick it up and just work.
- Workaround the bug in the test by waiting until the input is ready like you do with a timeout.

**Comment by vivekVells** [comment]
Thanks @dgozman. was rechecking few things again and looks like the login page is rendering twice. so, on the 1st page load, values are being inputted properly while on the 2nd page re-load, previous input are being cleared. 

I will close this issue 😀 

thank you for the swift response and directions; this helped.
