### ISSUE TITLE
[Question] How can I extend window object with TypeScript code?

### ISSUE THREAD

**Issue by maximpn** [microsoft/playwright#15759]
I have quite a simple task which just create some mock object in TypeScript with some code and external dependencies and extend window global object (add a field) for each/set of/all tests in a convenient way.

I checked `page.addInitScript()` but it accepts either a path or raw content. This way I need to transpile my TS code and bundle it after with some bundler like Webpack or Rollup to be able to inject as an init script. It looks manageable but far away than straightforward. Playwright supports TS so uses tsc under the hood but I need a completely separate from that process.

Do I understand everything right or maybe some simpler way exists to extend the window object per test? It looks like relatively popular task and the current approach fits for third party libraries but complex for some custom code.

**Comment by dgozman** [comment]
@mpalenov Luckily, `page.addInitScript()` can accept a function that it will execute in the page, so you can have arbitrary TypeScript code there. Make sure that function doesn't use anything from the outside context like a constant or a variable, because those won't be available in the page.

Here is an example:

```ts
// example.spec.ts

import { test, expect } from '@playwright/test';

test('example', async ({ page }) => {
  await page.addInitScript(() => {
    window['foo'] = 1;
  });
  await page.goto('https://playwright.dev');
  expect(await page.evaluate(() => window['foo'])).toBe(1);
});
```

Let me know whether this works for you.

**Comment by mpalenov** [comment]
@dgozman thank you for the answer.

In my case I need to use an external library to build up a mock. That's why I posted a question here since it's not so trivial.

As far as I can see in the source code functions are transformed into strings so basically it's JS code inside a TS file treated as TS code which makes it tricky to comprehend but it's convenient for simple cases. And it also means there is no transform applied.

I ended up using rollup (which is a bit simpler than set up webpack) to bundle my mock written in TS and provide a path to the bundle to `page.addInitScript()` so it works as expected.

Generally it would be nice to have some way to bundle complex mocks (or have a recommended way to do that in the docs) since it's as minimum useful for apps which interacts with browser extensions and one wants to mock extensions. A good example is DeFi Dapps with Crypto wallets installed as extensions.

**Comment by dgozman** [comment]
@mpalenov I see, thanks for the explanation. Indeed, the current solution is to use a rollup or some other bundler. I will see about adding this to the docs. Maybe at some point we'll help with automatically bundling for you as a part of a test runner, but that's a stretch goal.
