### ISSUE TITLE
[Question] How to handle context menu dialog with right click to save an image - Playwright

### ISSUE THREAD

**Issue by souleonardo** [microsoft/playwright#15849]
I'm trying to do an automation that downloads an image from a website.

My use case requires me to right click and choose the "save as" menu and choose a location on my computer to save the file.

But using the code below I can't make the menu appear to continue with the automation, do you know any way to do this? maybe a plugin..

I couldn't make the menu (dialog) appear with the code:

       await page.mouse.click(1180, 160["right"]) or,
       await page.keyboard.press('Ctrl+S'),

May you help me?

**Comment by dgozman** [comment]
@souleonardo Playwright does not automate browser UI, including the right-click menu.

You can try to get the `href` attribute from the link using [`locator.getAttribute()` method](https://playwright.dev/docs/api/class-locator#locator-get-attribute) and download it manually.

Alternatively, try clicking with the `'Alt'` keyboard modifier - in most browsers this usually downloads the link instead of opening it.

**Comment by souleonardo** [comment]
Thank you so much @dgozman
