### ISSUE TITLE
[Feature] Control what order test items are printed to console during test runs 

### ISSUE THREAD

**Issue by jimpriest** [microsoft/playwright#15848]
Current when I run my tests I get a very long string printed to console:

```
[Chromium] › features/foo-112-foochecks.spec.ts:16:3 › FOO-112 Pen Test - Fix FOO Issues @foo-112 › I should be able to submit a new contact with valid FOO token (2s)
```
Would it be possible to make this configurable? As you can see in the preview above the important bits are usually off the screen. Especially in our CI environment.

I only use Chrome so [Chromium] is useless, and I don't really care about  the directory either.    In any case I'd rather have the test name first, then the directory and then maybe the browser.

Maybe something in the config?
```
outputOrder: { testDuration, testName, testDirectory, testBrowser }
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
