### ISSUE TITLE
[BUG] using playwright inside electron window with nodeIntegration option

### ISSUE THREAD

**Issue by a7medmo7med9** [microsoft/playwright#15895]
**Context:**
- Playwright Version: [1.24.0]
- Operating System: [Windows]
- Node.js version: [v16.16.0]
- Browser: [Chromium]
- Extra: [I'm using electron-react-boilerplate]

**Code Snippet**

code for frontend react js

```javascript
import { chromium } from 'playwright';

export default function App() {
  const createBrowser = async () => {
    const browser = await chromium.launch({ headless: false });

    const context = await browser.newContext();

    const page = await context.newPage();

    const element = await page.waitForSelector('.products', {
      state: 'visible',
      timeout: 5,
    });
  };

  return (
    <>
      <button type="button" onClick={createBrowser}>
        CreateBrowser
      </button>
    </>
  );
}

```

![1](https://user-images.githubusercontent.com/34967435/180603900-c4265670-2b25-434d-b111-793485893cd9.PNG)

**Describe the bug**

I'm using this template for electron [Electron-React-boilerplate](https://electron-react-boilerplate.js.org/)
in electron options  i'm using **nodeIntegration** option to run node js in frontend and it works find with node js api

```javascript
 mainWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    },
  });
```

but when i try to use time out for **page.waitForSelector** thorw this error how can i get playwright fully working with react js at fronted I don't want to use ipcMan to send request to nodejs from frontend to run test

**Comment by pavelfeldman** [comment]
It might be that we don't work with the nodeIntegration well.

**Comment by a7medmo7med9** [comment]
> It might be that we don't work with the nodeIntegration well.

Is there any way to get it work

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
