### ISSUE TITLE
[Feature] [python] Option to choose single quotes for codegen

### ISSUE THREAD

**Issue by jfp1992** [microsoft/playwright#15893]
See the below example locator generated by the code generator
```
    page.locator("button:has-text(\"Accept all\")").click()
```
I find myself having to change all of these to single quotes

I propose to have an option where this will also generate using single quotes as they are already supported in the selector engine:
https://github.com/microsoft/playwright/pull/1902

The alternative option for generated code would be:
```
    page.locator("button:has-text('Accept all')").click()
```
To be clear, I'm not suggesting to change the current implementation, just to have a toggle to switch to single quotes.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
