### ISSUE TITLE
[BUG] Playwright Documentation Website | Search functionality appears to be broken

### ISSUE THREAD

**Issue by vijaydubber** [microsoft/playwright#15915]
**Describe the bug**

Visit
https://playwright.dev or https://playwright.dev/docs/intro

Use search bar on the top right.

Search for any known keyword, such as `Selector `, or `Electron`, or `Page`

Expected:
Documentation relevant to the keyword to be displayed

Actual
No results

![image](https://user-images.githubusercontent.com/107010980/180738821-b7a6bf5a-2cad-4381-8ff3-b5022af72e08.png)

Tested in Edge / Chrome

**Comment by mxschmitt** [comment]
We are currently regenerating the search index, should be back in 15-30 minutes. Sorry for the inconvenience!

**Comment by vijaydubber** [comment]
Hi @mxschmitt ,
Assuming there is b/g deploy / release. Is it possible to do DNS cutover after index rebuild.

**Comment by mxschmitt** [comment]
No, it's because we changed from having the index based on the versions to having only a single `stable` version + (meta information since when a version was available). And since the index is connected to the version (`1.24`, `1.23`...) there were no entries for the new `stable` index. Thats why the search returned 0 results.

The index has been re-generated, closing by that.
