### ISSUE TITLE
[BUG] electron.launch behaves differently locally vs CI

### ISSUE THREAD

**Issue by has-n** [microsoft/playwright#15911]
**Context:**
- Playwright Version: 1.23.4
- Operating System: MacOS
- Node.js version: 16.16.0
- Browser: Electron
- Extra: [any specific details about your environment]

## System:
 - OS: macOS 12.0.1
 - Memory: 806.64 MB / 8.00 GB
## Binaries:
 - Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
 - npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
electronApp = await electron.launch({
    executablePath: "/Applications/app_name.app/Contents/MacOS/app_name"
})
```

Or even
```javascript
electronApp = await electron.launch({
    args: ['src/main/index.js'],
    env: process.env["ELECTRON_IS_DEV"] = 0,
});
```

**Describe the bug**

My MacOS app requires the microphone permission. When I launch it using the above snippets locally, the app is able to request for and receive microphone permission. 

When the same command is called from a CircleCI pipeline, the app is not able to request for and receive microphone permission. 

I'm investigating if CircleCI is causing this issue but opening this to start a conversation.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
