### ISSUE TITLE
[Question] Is there any possibility to filter test cases before runner is started?

### ISSUE THREAD

**Issue by ennjin** [microsoft/playwright#15981]
I've read the docs and seems that `grep` (with specific tags) and `only` not that I need.
It would be nice to have some API (or hook) to filter test cases. For example:

```ts
// playwright.config.ts
{
  testMatch: [
    'tests/**/*.spec.ts' // parse test cases by pattern
  ],
  include: (tests: TestInterface[] /* Flat array or tree */) => {
    return tests.filter(filterBytTestPlan);
  }
  // or exclude
}
```

The suggest above will add ability to run tests by 3d party test plans (allure for example)

**Comment by pavelfeldman** [comment]
There is no such feature. I'll leave it open to collect upvotes.

**Comment by angelfx** [comment]
It looks like very useful for allure integration.
I think this feature will help to integrate playwright tests with test plans.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
