### ISSUE TITLE
[Question] Different global setup per project

### ISSUE THREAD

**Issue by mariaceo** [microsoft/playwright#16008]
I know it's been asked before in #14513, but reopening this question since it would really help us.
We want to split our tests in separate projects per teams. And each team has different setup, that we can't do separately per project at the moment, although that would be super useful. Because then we could run all the test of a team or all tests of all teams and have a single report for all results.
At the moment, we tried to add different configs and global-configs for each team, but the problem is running the tests for all of them together. And even if we find a solution to run all the tests now, the reports are still separate.
So please consider adding global-setup for each project, things would get tidier and easier for many!

**Comment by dgozman** [comment]
The fix was reverted, reopening.

**Comment by rwoll** [comment]
Likely solved by https://github.com/microsoft/playwright/issues/14895#issuecomment-1207665459

**Comment by GP-QA** [comment]
We currently have two projects, one with Electric for E2E tests and one with a browser for integration tests with mocked API calls. Because you currently can only have one global setup with playwright, we have two package.json files which contain the same dependencies. This is not handy and makes projects cluttered.  It would be great if this issue finally be picked up! 

Thanks in advance,

Geoffrey

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/12084
