### ISSUE TITLE
Page Object Model [Question]

### ISSUE THREAD

**Issue by tomern** [microsoft/playwright#1604]
Hi, I would like to know how can you implement POM design pattern with playwright.
Thanks.

**Comment by arjun27** [comment]
Hi @tomern, you can use the [`page`](https://github.com/microsoft/playwright/blob/master/docs/api.md#class-page) object in Playwright and wrap it in a Page Object Model. For example:

```js
class CheckoutPage {
  constructor(page) {
    this.page = page;
  }
  
  async clickSubmit() {
    return this.page.click('text=Submit');
  }
}
```

Feel free to reopen if you have a follow-up question.

**Comment by randomactions** [comment]
Arjun, thanks for your response!

How do I use functions declared in one page object in another page object?

**Comment by arjun27** [comment]
Hi @randomactions, the best approach would depend on your use-case. Couple of approaches to consider:
* Use class inheritance and create base page classes that define common methods
* Define utility methods separately and import them inside page objects

**Comment by randomactions** [comment]
Thanks, Arun!

**Comment by tymfear** [comment]
@randomactions I would strongly recommend against usage of inheritance - that may lead to circular dependencies.
The better approach would be a set of helper methods combined with Page Element pattern.
E.g.

```javascript
// Page element class
class ConfirmDialog {
    constructor(page) {
       this.page = page;
  }

  async confirm() {
     return this.page.click('text=Confirm')
  }
}
```

```javascript
// Page object class
class CheckoutPage {
  constructor(page) {
    this.page = page;
    this.confirmDialog = new ConfirmDialog(page);
  }
  
  async clickSubmit() {
    return this.page.click('text=Submit');
  }
}
```

```javascript
//test 
const checkoutPage = new CheckoutPage(page);
await checkoutPage.clickSubmit();
await checkoutPage.confirmDialog.confirm();
```

**Comment by randomactions** [comment]
@tymfear thank you!

**Comment by vrknetha** [comment]
```javascript
import {Page, BrowserContext} from 'playwright';

export default class FacebookUtilities {
	page: Page;
	context: BrowserContext;
	constructor(page: Page, context: BrowserContext) {
		this.page = page;
		this.context = context;
	}

	TxtBxLogin = `xpath=//input[@id='email']`;
	TxtBxPassword = `xpath=//input[@id='pass']`;
	BtnLogin = `xpath=//button[@id='loginbutton']`;
	BtnProfileCancel = `xpath=//button[@id='u_0_0']`;
	BtnProfileContinue = `xpath=//button[@name='__CONFIRM__']`;
	BtnGroupsNotNow = `xpath=//button[@name='__SKIP__']`;
	BtnGroupsOk = `xpath=//button[@name='__CONFIRM__']`;
	LinkChooseWhatToAllow = `xpath=//a[@id='u_0_19']`;

	//Login
	login = async (email: string, password: string) => {
		await this.page.fill(this.TxtBxLogin, email);
		await this.page.fill(this.TxtBxPassword, password);
		await this.page.click(this.BtnLogin);
		await this.page.waitForNavigation({waitUntil: `domcontentloaded`});
	};

	//Profile Page
	profilePopupClickCancel = async () => {
		await this.page.waitForSelector(this.BtnProfileCancel);
		await this.page.click(this.BtnProfileCancel);
		await this.page.waitForNavigation({waitUntil: `domcontentloaded`});
	};

	profilePopupClickContinue = async () => {
		await this.page.waitForSelector(this.BtnProfileContinue);
		await this.page.click(this.BtnProfileContinue);
		await this.page.waitForNavigation({waitUntil: `domcontentloaded`});
	};

	//Groups Page
	groupsPageClickOnNotNow = async () => {
		await this.page.waitForSelector(this.BtnGroupsNotNow);
		await this.page.click(this.BtnGroupsNotNow);
		await this.page.waitForNavigation({waitUntil: `domcontentloaded`});
	};

	groupsPageClickOnOk = async () => {
		await this.page.waitForSelector(this.BtnGroupsOk);
		await this.page.click(this.BtnGroupsOk);
		await this.page.waitForNavigation({waitUntil: `domcontentloaded`});
	};
```

This is how I have implemented. This would expose the selectors too just in case if you want to assert them in a page.

**Comment by randomactions** [comment]
Thank you for all the answers!

How would this all look like with TypeScript? Did anyone tried doing it in TS?

**Comment by SalmonMode** [comment]
I ended up here after a random google search, but thought I would add my 2 cents for anyone else that comes across this, in case it helps.

I made [my own page object framework](https://pypcom.readthedocs.io/en/latest/) a while back in Python, and intend to port it over to JS/TS when I get a good amount of time and figure out a nice, idiomatic way to do it in those languages (I used descriptors in Python, and JS has a heavy focus on async stuff, so it doesn't translate perfectly).

The term "Page Object Model" was, historically, very overloaded and misused, and led a ton of people to less-than-effective and complex implementations. The "Model" part of that is also meant to indicate that the term represents a design pattern, so an individual implementation would _adhere to/follow_ that model, and the implementation would just be a "page object". To help clear this up, new terminology was established (beyond just the model vs object thing), and now, "page component objects" are an explicit thing in the "Page Object Model".

My framework is neither a model, nor an object (although it does have objects, and adheres to the Page Object Model), i.e. it is a framework that you can use to build individual page component objects and page objects around. The terminology can help a lot when trying to figure something out.

These components are basically just objects, where each one:
1. Knows how to locate/retrieve the web element it represents (and contains that logic internally so you don't have to deal with it once the object is made)
2. Provides methods that let you leverage the actual element's functionality (e.g. filling out and submitting a login form)
3. Allows references to other components for other elements inside it (e.g. a login form component having username and password components)

(Keep in mind, that neither the page object nor the component objects should have any idea that they're running in a test. The goal is to separate concerns, not conflate them)

This is called "object composition", and helps _immensely_ by compartmentalizing logic, making things reusable, and avoiding circular dependencies, like @tymfear mentioned.

You could make each component/page ad hoc, having all the code contained therein, with no inheritance, but I strongly recommend against it. Instead, if you can't find an already existing framework, I recommend making your own. Mine took me a while to make, but that's only because I wanted to be super fancy with it. But really, something just as effective, albeit less fancy shouldn't take much time. I'm thinking something like this:

```js
class Page {
  constructor(driver) {
    this.driver = driver;
  }
  async waitUntil(callback, timeout) {
    let endTime = new Date()).getTime() + timeout;
    let result = await callback(this).catch( err => false);
    while (!result && new Date()).getTime() < endTime){
      new Promise(resolve => setTimeout(resolve, 500));
      result = await callback(this).catch( err => false);
    }
    if (result) {
      return result;
    }
    throw new TimeoutError();
  }
}

class PageComponent {
  constructor(driver, parent) {
    this.driver = driver;
    this.parent = parent;
  }
  async getElement() {
    return await this.driver.findElement(this._locator);
  }
  async sendKeys(keys) {
    await this.getElement().sendKeys(keys);
  }
  async waitUntil(callback, timeout) {
    let endTime = new Date()).getTime() + timeout;
    let result = await callback(this).catch( err => false);
    while (!result && new Date()).getTime() < endTime){
      new Promise(resolve => setTimeout(resolve, 500));
      result = await callback(this).catch( err => false);
    }
    if (result) {
      return result;
    }
    throw new TimeoutError();
  }
}
```

and then you could have:

```js
class UsernameField extends PageComponent {
  _locator = By.CSS("#username");
}
class PasswordField extends PageComponent {
  _locator = By.CSS("#username");
}
class LoginForm extends PageComponent {
  _locator = By.CSS("form#login");
  constructor(driver, parent) {
    super(driver, parent);
    this.username = new UsernameField(this.driver, this);
    this.password = new PasswordField(this.driver, this);
  }
  async fillOut(user) {
    await this.username.sendKeys(user.username);
    await this.password.sendKeys(user.password);
  }
  await submit() {
    await this.getElement().submit();
  }
}

class LoginPage extends Page {
  constructor(driver) {
    super(driver);
    this.loginForm = new LoginForm(driver, this);
    // make responsible for knowing how to wait for the DOM to finish updating when the page is first loaded
    this.waitUntil(page => await page.loginForm.getElement().isDisplayed());
  }
  async login(user) {
    await this.loginForm.fillOut(user);
    await this.loginForm.submit();
  }
}
```

I have no idea if that'll work as is, but hopefully that gets the idea across.

With this approachh, Playwright, Puppeteer, Selenium, whatever; it doesn't really matter. The browser-driving agent is just that: an interface that your page objects can use to tell the browser what to do/get. In regards to implementing page objects, the difference between the agents is like the difference between a brick and a rock when it comes to hammering a nail; it really just affects the particulars of how exactly you smack the nail with it.

In this case, it's just a few pieces of the framework that would need to be adjusted depending on the API of the particular API you're using. My examples used my rough recollection of Selenium's JS API, but as an example for getting the associated element, for Playwright, instead of `return await this.driver.findElement(this._locator)`, it would be `return await this.page.$(this._locator)` (the locator would also need to change for Playwright's needs, but you get the idea).

Hopefully this helps!

**Comment by akapitoha** [comment]
hi all,

I would to use page object model and using playwright docs I added (just an example):
```js
class LoginPage {
    constructor(page) {
        this.page = page
    }
    async doSmth() {
        await this.page.waitForSelector('selector')
    }
}
module.exports = { LoginPage }
```
and in a test file I want to import `LoginPage` once and use it across several tests (using `it` , mocha runner).
but what only works for me is doing in each test/hook:
```js
const loginPage = new LoginPage(page)
await loginPage.doSmth()
```
@arjunattam maybe you could advice smth.
thanks in advance

**Comment by SalmonMode** [comment]
@akapitoha if you're looking to run multiple assertions against a page when it's in a particular state, without having any of those assertions prevent any of the others from running should they fail, then you can bundle all your `it`s together in a `describe` block, and use a `before` to set everything up, instead of a `beforeEach`. Then you can have as many assertions as you want by putting them in their own `it`s. But be careful not to make any state changing calls in those `it`s, as that can make your tests problematic as they'll be dependent on executing in a very specific order, and won't be able to be run on their own.

**Comment by arjunattam** [comment]
Thanks @akapitoha. @SalmonMode's suggestion is excellent, and I would recommend this approach for Mocha.

We are experimenting with a different approach in [playwright-test](https://github.com/microsoft/playwright-test) with which you can provide your tests with a `loginPage`. This is called fixtures -- [full syntax here](https://github.com/microsoft/playwright-test/blob/master/docs/setup-teardown.md#fixtures). We are collecting feedback on playwright-test and working towards making it stable.

```js
// In fixtures.ts
builder.loginPage.init(async ({page}, runTest) => {
  // get built-in page and wrap with POM
  const loginPage = new LoginPage(page);

  // pass this to your test
  runTest(loginPage);
}); 
```

```js
// In your test
it('should login', async ({ loginPage }) => {
  // use loginPage in your test function
});
```

**Comment by akapitoha** [comment]
@SalmonMode @arjunattam thanks a lot for your quick replies.
guess I already try to implement suggestion with `describe` block (if I understood it correctly), like
```js
const { LibraryPage } = require("../pages/libraryPage.js")

for (const browserType of ["chromium", "webkit"]) {
  describe("login", async () => {
    let browser
    let page
    const loginPage = new LoginPage(page)

    before(async () => {
      browser = await playwright[browserType].launch({ headless: true })
      page = await browser.newPage()
      await page.setDefaultTimeout(15000)
      await page.setDefaultNavigationTimeout(30000)
    })

    it(`(${browserType}): test 1`, async () => {
      await loginPage.navigate()
    })

    it(`(${browserType}): test 2`, async () => {
      await loginPage.navigate()
    })
  })
}
```
in both tests I try to call a function from PO, but get `TypeError: Cannot read property 'goto' of undefined` 
(`goto` is used in `navigate()`

**Comment by SalmonMode** [comment]
I'm guessing `loginPage.navigate()` is a state changing call, so I wouldn't use it in the `it`. I'd have to see the rest of the code to know what's fully going on though.

**Comment by akapitoha** [comment]
it jus opens a login page
```js
class LoginPage {
	constructor(page) {
		this.page = page
	}
	async navigate() {
		await this.page.goto("login_page_url")
	}
}
module.exports = { LoginPage }
```

**Comment by SalmonMode** [comment]
Ohhh, I see what's going on. It's undefined, because you passed in `undefined` when you first made the page object. My bad. 

Try instantiating your page object in the `before` right after you assign a value to `page`.

**Comment by akapitoha** [comment]
yeah, works now across all `it`s after adding `loginPage = new LoginPage(page)` in `before` hook. thank you so much!

**Comment by d4niloArantes** [comment]
I was looking for page object models pattern when I found this discussion. There is an implementation on the Playwright documentation here: https://playwright.dev/docs/pom

**Comment by navedanjum** [comment]
One can also extend playwright fixture for initialization and then use it directly in tests as fixtures 
```
import { test as baseTest } from '@playwright/test';
import { LoginPage } from '../pages/LoginPage';
import { ModelPage } from '../pages/ModelPage';

const test = baseTest.extend<{
  loginPage: LoginPage;
  modelPage: ModelPage;

}>({
  loginPage: async ({ page }, use) => {
    await use(new LoginPage(page));
  },
  modelPage: async ({ page }, use) => {
    await use(new ModelPage(page));
  },
});

export default test;

```

```
test.describe('Login to App', () => {
  test('Login invalid', async ({ loginPage }) => {
    await loginPage.goToLoginPage();
    await loginPage.login('XXXX@test.com ', 'XXXX');
    const isErrorMsgDisplayed = await loginPage.isMessageDisplayed('Invalid username or password.');
    await expect(isErrorMsgDisplayed).toBeTruthy();
  });

// Can use directly page fixture or any fixture on top of page from Pages constructor class
test('Login invalid', async ({ loginPage, page  }) => {
     // Do your stuff on loginPage and directly on any page in current context

});

```

**Comment by nicojs** [comment]
Hi 🙋‍♂️, an interesting discussion you have here 🤗. Pitching in with my findings after a few weeks of playwright experience.

## General PageObject rules

1. All interaction with the page should be done via page objects. I.e.: No selectors in your `.spec` files. No page internals should leak to the `.spec` files.
2. All assertions should be done in your tests. I.e. no `expect...` in your page objects.
3. Page objects can contain other page objects, but should always work with a designated `host` (i.e. a `Locator` or a `Page`)

## Playwright additional rules

1. Favor locators over element handles.\
    use `page.locator` over `page.$` or `page.$$`. Locators are less brittle because of automatic waiting. No need for custom "wait for" logic
2. Favor `await expect(locator)...` over `expect(await locator....)...`.\
   This breaks the first rule a bit. For example: `await expect(page.header).toContainText('Title')`. This leaks the header abstraction a bit to the test file (namely: that there is an element that contains text content). But the advantage outways the downside here: your tests will be far less brittle, because of automatic waiting.

## Example:

I generally create 2 small abstract base classes: `Page` and `PageObject`. A `Page` wraps a Playwright [`Page`](https://playwright.dev/docs/api/class-page) object. A `PageObject` wrapts a Playwright [`Locator`](https://playwright.dev/docs/api/class-locator). 

```ts
export abstract class PageObject {
  constructor(public readonly host: Locator) {}
}
export abstract class Page {
  constructor(public readonly page: PlaywrightPage) {}
  async close() {
    await this.page.close();
  }
}
```

Then I use that to create `Page` classes. Each `Page` class can contain locators and `PageObject`s. Both `Page`s and `PageObject`s can contain methods to help with interaction. For example:

```ts
export class Homepage extends Page {
  public readonly h1 = this.page.locator('h1');
  public readonly accordion = new Accordion(this.page.locator('.accordion'));
}
```

An example of the `Accordion` page object can be:

```ts
export class Accordion extends PageObject {
  public getCard(cardHeader: string): AccordionCardPageObject {
    const cardHost = this.host.locator(
      `:has(.card-header:has-text("${cardHeader}"))`
    );
    return new AccordionCard(cardHost);
  }
}
```

```ts
export class AccordionCard extends PageObject {
  public readonly body = this.host.locator(".card-body");
  public readonly header = this.host.locator(".card-header");
  
  public async activate(): Promise<void> {
    await this.host.locator(".card-header button").click();
  }
}
```

An example of a test:

```
test.describe('Homepage', () => {

  let sut: Homepage;

  test.beforeEach(async ({ page: p }) => {
    sut = new Homepage(p);
    await sut.navigate();
  });

  test('should have title "Welcome to the page"', async () => {
    await expect(sut.page).toHaveTitle('Welcome to the page');
  });

  test('should show an explanation "Welcome"', async () => {
    const card = sut.accordion.getCard("Welcome");
    await expect(card.body).toBeVisible();
  });
});
```

**Comment by digpulls** [comment]
> ```ts
> PlaywrightPage
> ```

Hi, @nicojs  thanks for sharing this. 
Could you share where `PlaywrightPage`  type is coming from in your example?

**Comment by nicojs** [comment]
> Could you share where `PlaywrightPage`  type is coming from in your example? 

Ah sorry, it wasn't clear before. It's the playwright Page class:

```ts
import { Page as PlaywrightPage, Locator } from 'playwright';
```

I've updated the example.

**Comment by vit-ganich** [comment]
@nicojs, thanks a lot for the example, it's really useful.
Have you ever considered creating a kind of default PageObject and using it for every page element without a specific element type?
For example, _Accordion_ for accordions, and _Default_ for buttons, textboxes, etc. Just for the consistency.

Thanks!

**Comment by nicojs** [comment]
I'm not sure I follow you. Do you mean 1 singleton instance of a page object?

**Comment by jordan-paz** [comment]
@nicojs Thank you so much for sharing this, it has been incredibly helpful 🙏 . If I got this right, the main benefit of instantiating a `PageObject` with a `Locator` rather than a `PlaywrightPage` is to keep the scope of the `PageObject`'s selectors to the `PageObject`'s subtree. Is there anything else I'm missing?

**Comment by nicojs** [comment]
That's exactly right @jordan-paz 🙏

**Comment by gajus** [comment]
You can always use Proxy for this, e.g.

```ts
import { test as base, type Page, type Locator } from '@playwright/test';

type MyPage = Page & {
  findByRole: (role: string, name: string) => Locator;
};

export const test = base.extend<{ page: MyPage }>(
  {
    page: ({ page }, use) => {
      use(
        new Proxy(page, {
          get(target, property, receiver) {
            if (property === 'findByRole') {
              return (role: string, name: string) => {
                return target.locator(`role=${role}[name="${name}"]`);
              };
            }

            return Reflect.get(target, property, receiver);
          },
        })
      );
    },
  }
);
```

and now in tests I can do things like:

```ts
await expect(page.findByRole('link', 'Explore Other Projects')).toBeVisible();
```

**Comment by stkevintan** [comment]
Hi, Thanks @nicojs , I've use the locator like what you did. but I found that the locators will be unusable after the page navigated.
since the call `page.locator('xxx')` is a shorthand for `page.mainFrame().locator('xxx')` . the main frame will be changed after page navigated. so the locator will point to the old (disposed) frame, will cannot be use again.

The only remedy I came over is to turn the property to a getter like:
```diff
class PageA extends PageObject {
-     public readonly body = this.host.locator(".card-body");
+    public get body() {
+        return this.host.locator('.card-body');
+    }
}
```

But this approach seems a bit tedious, do we have any better alternative ?

**Comment by WemansG90** [comment]
> But this approach seems a bit tedious, do we have any better alternative ?

Given that ChatGPT is doing it's thing, I tried asking this prompt and it actually collated some stuff out of the docs that forms 
 an alternative:

> One way to avoid this issue is to use the page.mainFrame().locator() method instead of the page.locator() shorthand. This method returns a selector that is bound to the page's main frame, but it does not dispose of the main frame when the page navigates, allowing the selector to continue to be used.

>Another way to handle this issue is to use the Selector method's withAttribute and withText options to create selectors that are not tied to a specific frame. These options allow you to create selectors that match elements based on their attributes and text content, rather than their location in the page's DOM.

Now if that is actually cleaner than just making a nice set of getters, not sure. I feel like that's more of a stylistic choice

**Comment by godon019** [comment]
@nicojs thanks for the detailed example. but why having assertions in POM is not recommended?

**Comment by Tornadoes** [comment]
> @nicojs thanks for the detailed example. but why having assertions in POM is not recommended?

If you're not familiar with the code, it will take longer to understand what the assertions are doing. 
Also wrapping one liners like an assertion in the POM class doesn't make too much sense.

**Comment by squareloop1** [comment]
> Hi 🙋‍♂️, an interesting discussion you have here 🤗. Pitching in with my findings after a few weeks of playwright experience.
> 
> ## General PageObject rules
> 1. All interaction with the page should be done via page objects. I.e.: No selectors in your `.spec` files. No page internals should leak to the `.spec` files.
> 2. All assertions should be done in your tests. I.e. no `expect...` in your page objects.
> 3. Page objects can contain other page objects, but should always work with a designated `host` (i.e. a `Locator` or a `Page`)
> 
> ## Playwright additional rules
> 1. Favor locators over element handles.
>    use `page.locator` over `page.$` or `page.$$`. Locators are less brittle because of automatic waiting. No need for custom "wait for" logic
> 2. Favor `await expect(locator)...` over `expect(await locator....)...`.
>    This is in conflict with the first general PageObject rule a bit, as it leaks page details to the expectations. For example: `await expect(page.header).toContainText('Title')` leaks the detail that the header contains the title as text content. But the advantage outways the downside here: your tests will be far less brittle, because of automatic waiting.
> 
> ## Example:
> I generally create 2 small abstract base classes: `Page` and `PageObject`. A `Page` wraps a Playwright [`Page`](https://playwright.dev/docs/api/class-page) object. A `PageObject` wraps a Playwright [`Locator`](https://playwright.dev/docs/api/class-locator).
> 
> ```ts
> import { Page as PlaywrightPage, Locator } from 'playwright';
> 
> export abstract class PageObject {
>   constructor(public readonly host: Locator) {}
> }
> export abstract class Page {
>   constructor(public readonly page: PlaywrightPage) {}
>   async close() {
>     await this.page.close();
>   }
> }
> ```
> 
> Then I use that to create `Page` classes. Each `Page` class can contain locators and `PageObject`s. Both `Page`s and `PageObject`s can contain methods to help with interaction. For example:
> 
> ```ts
> export class Homepage extends Page {
>   public readonly h1 = this.page.locator('h1');
>   public readonly accordion = new Accordion(this.page.locator('.accordion'));
> }
> ```
> 
> An example of the `Accordion` page object can be:
> 
> ```ts
> export class Accordion extends PageObject {
>   public getCard(cardHeader: string): AccordionCardPageObject {
>     const cardHost = this.host.locator(
>       `:has(.card-header:has-text("${cardHeader}"))`
>     );
>     return new AccordionCard(cardHost);
>   }
> }
> ```
> 
> ```ts
> export class AccordionCard extends PageObject {
>   public readonly body = this.host.locator(".card-body");
>   public readonly header = this.host.locator(".card-header");
>   
>   public async activate(): Promise<void> {
>     await this.host.locator(".card-header button").click();
>   }
> }
> ```
> 
> An example of a test:
> 
> ```ts
> test.describe('Homepage', () => {
> 
>   let sut: Homepage;
> 
>   test.beforeEach(async ({ page: p }) => {
>     sut = new Homepage(p);
>     await sut.navigate();
>   });
> 
>   test('should have title "Welcome to the page"', async () => {
>     await expect(sut.page).toHaveTitle('Welcome to the page');
>   });
> 
>   test('should show an explanation "Welcome"', async () => {
>     const card = sut.accordion.getCard("Welcome");
>     await expect(card.body).toBeVisible();
>   });
> });
> ```

Trying to implement this as it would make life alot easier, but I always get a `Error: Locators must belong to the same frame.`. Is it because my page is injected as a fixture in my test?

**Comment by msmith1114** [comment]
So this is a bit older of a issue, but I wanted to give my thoughts on it:

In general my page objects look like the below:

```
//Base Page
import type { Page } from "@playwright/test";

export abstract class BasePage {
  constructor(public readonly page: Page) {}

  /**
   * navigates to url
   * @param path - url path
   */
  async open(path: string) {
    await this.page.goto(path);
  }
}
```

Then some page object:

```
import { BasePage } from "@pages/base.page";
export default class LoginPage extends BasePage {
  public readonly loginEmailInput = this.page.getByRole("textbox", {
    name: "Username",
  });
  public readonly loginPasswordInput = this.page.getByRole("textbox", {
    name: "Password",
  });
  public readonly loginButton = this.page.getByRole("button", {
    name: "Log in",
  });


  /**
   * Logs the user in with a login name and password
   * @param {string} email - login email/username 
   * @param {string} password - login password (
   */
  async login(
    email = "default@email.com",
    password = "defaultPassword",
  ) {
    await this.loginEmailInput.fill(email!);
    await this.loginPasswordInput.fill(password!);
    await this.loginButton.click();
  }

  /**
   * Navigates to the login page
   */
  async open() {
    await super.open("Login");
  }
}
```

Some general just notes (I am not saying they are right or wrong):

1. I like using a base page object for navigations (like "Open") or if I need to add logging or abstract methods that each "Page" should have (such as a `ValidatePage` method for example that may validate a bunch of key elements exist on a page for instance). Also good if all your pages contain a header or footer or something (Although one could argue preferring composition over inheritance so I have shied away from this recently)
2. I _personally_ do not like passing host locators to components. Right now im working on an older website so there is less re-usable components but even If I were doing a more component based page/page objects I am not sure I would do this. Since in the end you are separating the locator essentially (or the "total/absolute" full locator) for the component between the page and the page object/component. I think this makes it a bit more difficult to follow and gets even worse if you have multiple of the same components on a page for example. It's easier to just pass the full locator to the component IMO. I think this is one of the reasons unless components are re-used a lot I still favor using the "old fashioned" page object model (and less component based). Either way in general I keep my component locators "whole dom" based instead of some sub-tree parent/host based. 
3. I keep assertions out of page objects _generally_, I will sometimes have a `IsLoaded` method that I call as a sort of "smoke" check on the page for key elements and this will have assertions on it. Each page object will have this method (Im still not sure if this is the "correct" way however)
4. I tend to keep any routes/constants separated from page objects in their own folder/file specifically just for ease of updating.

**Comment by Anand-M-Cherian** [comment]
Hello, I am  new to Playwright and even test automation for that matter. I have been assigned to develop a framework for our ecommerce website in my office. 

We had already developed a framework in Java Selenium a while back and the same was used the same to develop a starting draft framework in Playwright. I have to work on top of it and complete the entire thing.

The one thing that I am simply not able to comprehend is that the framework extends every page from an abstract base page and the actual location of an element is done INSIDE the base page and NOT the actual page. Let me give you a code sample below:

```typescript
// Parent Base Page class

export default abstract class BasePage {
  protected readonly page: Page;
  constructor(page: Page) {
    this.page = page;
  }
  async open(appUrl: string) {
    await this.page.goto(appUrl);
  }
  async isElementVisible(selector: string) {
    console.log(selector);
    const element = this.page.locator(selector);
    try {
      await element.waitFor({ state: "visible" });
      expect(element).toBeVisible();
    } catch (error) {
      throw new Error(selector + " =>Element not visible");
    }
  }
  async waitAndClickFirstByTestId(selector: string) {
    return await this.page.getByTestId(selector).first().click();
  }
}

// Page Object Class

import { expect, Locator, type Page } from "@playwright/test";

import BasePage from "../base/BasePage";
import { appUrl } from "../../config";

import {
  dummySelector1,
  dummySelector2,
} from "../pageobjects/Homepage";

export default class Homepage extends BasePage {
  constructor(page: Page) {
    super(page);
  }
  async open() {
    await super.open(appUrl);
    return await super.waitForPageLoad();
  }
  async isDummySelector1Visible() {
    return await this.isElementVisible(dummySelector1);
  }
  async waitAndClickByTestId() {
    return await this.waitAndClickFirstByTestId(dummySelector2);
  }
}

// Then there is another class which provides just the selectors for the HomePage --> HomePage.ts
export const dummySelector1= '#link1';
export const dummySelector2='#link2';
``` 

I seriously feel this will definitely give problems in the long run. Whenever I need to add a new page, I am limited to the methods available in the base page and if I can't find any I find myself modifying the base page which kind of defeats the purpose right? 

I think the actual location of elements can be done in the actual page using the playwright recommended ones like getByRole() and all. Any elements which are common like headers, footers can be located in the base page. 

Come to think of it, I am getting more and more confused of what is the actual role that base page should play. Can someone please help me out on this?

PS: I don't mean to sound arrogant by going against a framework that has been built by more experienced people. It's just that I keep on digging deeper and deeper until I actually find the real meaning or benefit of something. The explanation that I got was it will be easier for new members to contribute to the code by just writing some high level code. I have been going down many reddit, stack overflow rabbit holes with this issue and finally came here.

@arjunattam @nicojs @tymfear @SalmonMode

**Comment by SalmonMode** [comment]
@Anand-M-Cherian don't sweat it. In general, the base page serves to contain the stuff that's common to your website. For example, the general logic for locating any element (this way subclasses can feed it info like the specific locator to use). Then you would add more functionality in the subclasses of the base page class wherever relevant. 

The general idea, though, is that if you use good programming practices (e.g. composition, KISS, DAMP, SOLID, etc) then you'll arrive at something akin to the page object model. 

I've noticed a lot of people believe having a common framework like the page object model would somehow save time in regards to collaboration/onboarding/automating verification/documentation. But your frustrations here highlight how that won't necessarily happen (as everyone and their grandma is still gonna have their own variation/flavor/subjective preferences/etc and checking things at this level is exponentially more expensive than pretty much any other level in many ways).

I would say the most important things to focus on are:

- figuring out how you want your usage of the code to look (like with Test Driven Development)
- making sure that whatever you _do_ implement under the hood can be easily replaced/modified
- making sure your code throws very helpful errors when it should and has decent logs (so you can more easily and quickly figure out what went wrong, where, and when)
- and only checking what you absolutely must (e.g. if it can login, find the right form, fill it out, submit it, and confirm something that roughly looks like the right results shows up on the next page, then other problems either should've been found at a lower level or will likely be found with exploratory testing)

As long as you give these a decent effort, then it won't really matter if you aren't sticking to what people say is the "true page object model" as you'll still get whatever benefits you'd get from using the model. Focus on what works for you and your team given the constraints that you have.

**Comment by ey3Craft** [comment]
H
