### ISSUE TITLE
[Feature] In the HTML report, Make the tabbed pane for the screenshot comparison sticky

### ISSUE THREAD

**Issue by muhammad-saleh** [microsoft/playwright#16069]
Related to:
https://github.com/microsoft/playwright/issues/15802

![image](https://user-images.githubusercontent.com/1510608/181863894-4bd888ff-674c-4397-9be0-08b39b7981f3.png)

Since the diff tab might not always be visible and I would like to compare the Actual vs Expected images, It would be nice to make this bar sticky while you scroll down. Even better to maintain the page scroll position when you switch between Actual and Expected to make comparison easier.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
