### ISSUE TITLE
[Feature] Add Locator.parent()

### ISSUE THREAD

**Issue by 304NotModified** [microsoft/playwright#16155]
> You know you can get to the parent by doing
> ```
> page.locator("#locator").locator("..").locator("div").nth(0)
> ```

_Originally posted by @sgreener in https://github.com/microsoft/playwright/issues/15234#issuecomment-1170212273_

**Comment by 304NotModified** [comment]
While I also like to suggest adding parant method, i still thing we needs the docs for ..  

Or isn't a feature?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
