### ISSUE TITLE
[Feature] Trace domain configuration

### ISSUE THREAD

**Issue by badsyntax** [microsoft/playwright#16158]
Hi there. I've got traces enabled and the log I received for a failing test is:

```console
npx playwright show-trace test-results/Vehicles-VehiclesListScreen-VehiclesListScreen-906c8-filter-correctly-when-choosing-multiple-filters-Chromium/trace.zip
```

This is a very useful log for local development, but not so much for build pipelines, as traces are uploaded out of the build server to blob storage.

It would very convenient if we could configure the "show-trace" domain so that the log would output: 

```console
npx playwright show-trace https://my.blob.domain.com/test-results/Vehicles-VehiclesListScreen-VehiclesListScreen-906c8-filter-correctly-when-choosing-multiple-filters-Chromium/trace.zip
```

What do you think?

**Comment by mxschmitt** [comment]
Very interesting idea, I'll mark it as a feature request!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
