### ISSUE TITLE
[Question] How to add a listener to Autofill CVC Verification Model Dialog?

### ISSUE THREAD

**Issue by sanjoyghosh** [microsoft/playwright#16266]
Hello,

I am trying to add a simple listener to my Playwright script to listen for the Chrome Autofill CVC Verification Modal Dialog.  Here is the code.  Unfortunately, even though the Modal Dialog is surfacing, the "on dialog" is not firing.

Any suggestions, ideas greatly appreciated.

```
  page.on('dialog', async dialog => {
    console.log(dialog.message());
    await dialog.accept();
  });
  await page.keyboard.press('ArrowDown');
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
