### ISSUE TITLE
[Question] (Playwright+JS) How to write a reusable methods in Playwright to return a value? 

### ISSUE THREAD

**Issue by amit1791** [microsoft/playwright#16295]
Hi,

I'm trying to create a reusable method to retrun a value but I'm getting a expection when I call it in my test. I'm using Playwright with JavaScrtipt.

Below is my code for your reference.

//Method to generate 6 digits number
async generateRandomSixDigitNumber(){
        const randomNum = Math.floor(100000 + Math.random() * 900000);
        return randomNum; 
  }

//using generateRandomSixDigitNumber() to concat with my email address
async getUniqueNewEmailAddress(){
        const email = "amit.saini+"+this.generateRandomSixDigitNumber()+"@gmail.com";
        console.log(email);
        return email.toString();
    }

When I'm printing this custom email address then its printing like "amit.saini+[object Promise]@gmail.com" and test case throwing expection as "Expected String but got object".

I'm new to Playwright, please guide me how can I write such methods to return a value. Thank you!

**Comment by mxschmitt** [comment]
I recommend going through a getting started course for JavaScript to understand especially how async/await and Promises are working. e.g. [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function).

In your case `[object Promise]` is a Promise object, which you need to await to get the value. Alternatively remove the "async" from generateRandomSixDigitNumber since its not performing any async stuff internally anyway.
