### ISSUE TITLE
[Feature] Make clickable URL's in HTML report title

### ISSUE THREAD

**Issue by DmitryMakhnev** [microsoft/playwright#16303]
Could you please make clickable URL's in HTML report title. It'll be helpful for opening page immediately from report.
![photo_2022-08-05 15 57 34](https://user-images.githubusercontent.com/895560/183093641-b5c9fa6e-db8f-4785-b7ab-8502c7e45991.jpeg)
Thanks 🙏

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
