### ISSUE TITLE
[Feature] Add custom selector engine for SAP UI5 framework

### ISSUE THREAD

**Issue by gemelgb** [microsoft/playwright#16332]
In a similar way as you support custom technologies as: https://playwright.dev/docs/selectors#react-selectors or vue selectors. I would like to extend playwright to support UI5 framework, is there any documentation or API available to do that?

Any support very appreciated,

Cheers!

PS: If the answer is yes does that also means that it supports also any custom attributes finding? This part of documentation is not very clear here: http://cuketest.com/playwright/docs/selectors/index.html#id-data-testid-data-test-id-data-test-selectors, does this means that for example:  "div data-my-attribute='a'". For **data-my-attribute** can I use normal css and xpath selectors?

**Comment by jfgreffier** [comment]
You can create your own selector engine if needed https://playwright.dev/docs/extensibility#custom-selector-engines

**Comment by mxschmitt** [comment]
It's all open source, the React selector engine code is here: https://github.com/microsoft/playwright/blob/607910f6aae8d5182d6e271f9256f47a61ceee4b/packages/playwright-core/src/server/injected/reactSelectorEngine.ts

**Comment by DetachHead** [comment]
i created a selector engine for ui5 https://github.com/DetachHead/playwright-ui5

**Comment by KotlinIsland** [comment]
@detachhead Now you just need to publish it for Python, Java and .NET 🤣

**Comment by KotlinIsland** [comment]
@mxschmitt The process for selector engine developers seems highly redundant? Could there be some kind of functionality where an `npm` package can be used in the different language targets?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
