### ISSUE TITLE
[Question]: Proper usage of Expect().Not.ToHaveAttributeAsync()

### ISSUE THREAD

**Issue by abdushaj** [microsoft/playwright#16374]
Curious to know if the Assertions.Expect(locator).Not.ToHaveAttributeAsync("expanded", string.Empty) works as it should be.

Scenario is with a collapable accordion element with attribute `expanded` without any value

- when exapanded element will have `expanded` attribute
- when collapse element will not have `expanded` attribute 

And am I using it right - to check if element is collapsed?

`Assertions.Expect(locator).Not.ToHaveAttributeAsync("expanded", string.Empty)`

Exception log :
`Microsoft.Playwright.PlaywrightException: Locator expected not to have attribute 'expanded' ''
But was: ''`

Currently I'm ensuring this by having an extra check with 
`Assertions.Expect(locator).ToHaveAttributeAsync("expanded", string.Empty);
locator.GetAttributeAsync(attributeName).Result.Should().BeNull($"Attribute '{attributeName}' is expected not to be present!");`

**Comment by rwoll** [comment]
Next to each assertion, can you past the DOM/HTML you are running this assertion against, and include what you expect the assertion to do? (Either pass or error).

This will help ensure we are understanding the scenario properly. Thanks!

In general, I'd try to match on whether the content of the accordian is there—not an attribute since an attribute is an implementation detail.

I might write a test that looks like:

```
const accordian = page.locator(…);
await expect(accordian).toContainText("my item in the accordian", { useInnerText: true });
await accordian.locator("text=Close").click();
await expect(accordian).not.toContainText("my item in the accordian", { useInnerText: true });
```

This has two advantages over the attribute:

1. it's not dependent on some attribute that could change if you alter the accordian's implementaion
2. we first check if the content is visible, take an action, and then check it's NOT visiible. For `not` clauses, checking for the transition is more robust than solely check for `not`.

**Comment by rwoll** [comment]
Closing per-above as part of triage. If you're still facing an issue, please file a new issue referencing this one!

Thanks!
