### ISSUE TITLE
How do I run multiple test in the same browser ?

### ISSUE THREAD

**Issue by Abhishek-Neg17** [microsoft/playwright#16399]
Hello , 
           I am unaware about how to run multiple tests sequentially in PlayWright without the browser closing. 
     

Thanks in advance :)

**Comment by unickq** [comment]
You can run tests in `serial` mode.  But every new test is a new browser session.
https://playwright.dev/docs/next/api/class-test#test-describe-configure

you may use `test.step` if you want to split test logic into logical chunks
https://playwright.dev/docs/api/class-test#test-step

**Comment by TimeInvestor** [comment]
Instead of using the page fixture for each test, you can create a Page from BrowserContext. Then, use the Page to load and test your website.
Btw, don't forget to close the Page at the end of testing.

**Comment by rwoll** [comment]
It's discourage to share `page`s across tests, so https://github.com/microsoft/playwright/issues/16399#issuecomment-1210479189

> you may use test.step if you want to split test logic into logical chunks
https://playwright.dev/docs/api/class-test#test-step

is solid advice.

However, if you still want to share a page across multiple **tests in the same file**, you can add:

```ts
import { Page, test, expect } from '@playwright/test';

test.describe.configure({ mode: 'serial' });

let sharedPage: Page
test.beforeAll(async ({ browser }) => {
  sharedPage = await browser.newPage();
});

test('should …', async () => {
  await sharedPage.goto("https://example.com");
});

test('should do another thing …', async () => {
  await expect(sharedPage).toHaveURL("https://example.com");
  await sharedPage.goto("https://playwright.dev");
});

test.afterAll(async () => {
  await sharedPage.close();
})
```

However, doing this will slow down retries (since all have to be run again), can cause flakiness, and makes for a worse debugging experience so it's discouraged.
