### ISSUE TITLE
[Feature] Record Video with Transparent Background - omitBackground

### ISSUE THREAD

**Issue by buptzwl** [microsoft/playwright#16401]
sorry, please forgive my poor English. This is my code.
```javascript
const playwright = require('playwright');
const timer = require('timers/promises');

(async () => {
const browser = await playwright.chromium.launch();
const page = await browser.newPage({
        viewport: {
            width: 1920,
            height: 1080,
        },
        recordVideo: {
            dir: 'C:\\Users\\dlee\\Desktop\\temp',
            size: { width: 1920, height: 1080 },
        }
    });
await page.goto('https://www.google.com');// this url is just an example.
await timer.setTimeout(5 * 1000)
await browser.close();
})()
```
I want to record a video without the chrome background (the background is transparent and **_the alpha channel is 0_**). How could I do it? Thank you.

**Comment by rwoll** [comment]
This isn't supported today, or if it is, it's by coincidence. Can you elaborate on your use case?

**Comment by buptzwl** [comment]
> This isn't supported today, or if it is, it's by coincidence. Can you elaborate on your use case?

Ok. My use case is an  SVG (with CSS animation) URL.
`http://source.wengegroup.com/mam2/62ccec0de4b0fa6f5607e8bc.svg`
How could I record the video without the browser's default white background? I want the video's alpha channel to be zero. Just like the picture below.
![test](https://user-images.githubusercontent.com/12728397/184076944-5084bc9c-5c0d-4af0-b6e8-c42ad792d396.png)
（This picture used the page.screenshot() and the config of omitBackground is **true**）

**Comment by rwoll** [comment]
Thanks—I've converted to a feature request. Would you be interested in contributing a PR?

**Comment by buptzwl** [comment]
> Thanks—I've converted to a feature request. Would you be interested in contributing a PR?

Thanks for your offer. I am very interested in contributing a PR. But I'm a rookie in Javascript. I don't know which fragment of code is about recording video. Where could I get some information about this question? Thanks for your invitation again.

**Comment by xopr** [comment]
So for Chromium, I think it might be as simple as an extra `ffmpeg` parameter in ([VideoRecorder.ts#L101](https://github.com/microsoft/playwright/blob/d4053abd2972cb7168b31478b160c5bc3bf05b90/packages/playwright-core/src/server/chromium/videoRecorder.ts#L101))
If this [stackoverflow](https://stackoverflow.com/questions/65434905/how-to-preserve-transparency-when-scaling-png-with-ffmpeg) post is correct, it might be sufficient to add `format=rgba` to the `-vf` param.
This patch should do the trick, but I'm too clumsy to install/test the local npm package, my video outputs are always 0 bytes:
```patch
diff --git a/packages/playwright-core/src/server/chromium/videoRecorder.ts b/packages/playwright-core/src/server/chromium/videoRecorder.ts
index c41a11cd9..5880216ad 100644
--- a/packages/playwright-core/src/server/chromium/videoRecorder.ts
+++ b/packages/playwright-core/src/server/chromium/videoRecorder.ts
@@ -98,7 +98,7 @@ export class VideoRecorder {
 
     const w = options.width;
     const h = options.height;
-    const args = `-loglevel error -f image2pipe -avioflags direct -fpsprobesize 0 -probesize 32 -analyzeduration 0 -c:v mjpeg -i - -y -an -r ${fps} -c:v vp8 -qmin 0 -qmax 50 -crf 8 -deadline realtime -speed 8 -b:v 1M -threads 1 -vf pad=${w}:${h}:0:0:gray,crop=${w}:${h}:0:0`.split(' ');
+    const args = `-loglevel error -f image2pipe -avioflags direct -fpsprobesize 0 -probesize 32 -analyzeduration 0 -c:v mjpeg -i - -y -an -r ${fps} -c:v vp8 -qmin 0 -qmax 50 -crf 8 -deadline realtime -speed 8 -b:v 1M -threads 1 -vf format=rgba,pad=${w}:${h}:0:0:gray,crop=${w}:${h}:0:0`.split(' ');
     args.push(options.outputFile);
     const progress = this._progress;
 
```
Could anyone confirm this?
It would also unlock html stinger video transitions, for example.

**Comment by xopr** [comment]
I had another stab at this, and I figured that it needs something else than jpeg/mjpeg (due to its need of the apha channel).
This would mean that for the calls to `_startScreencast` in [packages/playwright-core/src/server/chromium/crPage.ts](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/chromium/crPage.ts), the `format` needs to be changed from `jpeg` to `png` as well (next to the ffmpeg parameters).
All combinations of ffmpeg parameters I tried have failed (I'm assuming it errors out; no file is generated).

Someone comfortable with ffmpeg might be able to pull it off.

Also, I'm not sure about the performance impact since mjpeg is presumably less CPU intensive than png.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
