### ISSUE TITLE
[Question] How to get the initial url of new page?

### ISSUE THREAD

**Issue by dlc9113** [microsoft/playwright#16403]
A button open a new page for vendor website, then it redirect to another url.
I use the code from official document [pages](https://playwright.dev/docs/pages) but I can only get the final url. Is there any way to get the initial url?
```typescript
const [newPage] = await Promise.all([
	page.context().waitForEvent('page'),
	page.locator(selector).click()
]);
console.log(await newPage.url());
```

**Comment by rwoll** [comment]
No, but see a possible workaround below. It's for inspiration rather than verbatim copying as you'll need to play around to get it to work:

```ts
  const pagesToFirstNavigationRequest = new Map();

  page.context().on("request", (request) => {
    // customize this to your needs and or capture all requests
    if (request.isNavigationRequest() && request.frame() === request.frame().page().mainFrame() && !pagesToFirstNavigationRequest.has(request.frame().page())) {
      pagesToFirstNavigationRequest.set(request.frame().page(), request.url());
    }
  })

  // …

  const req = pagesToFirstNavigationRequest.get(myNewPage)
  // You might need to look at request.redirectedFrom() chain
```

NB: If you were using `goto`, you could use the [returned Response ](https://playwright.dev/docs/api/class-page#page-goto-return) and walk its request+redirection fields, but this does not look applicable in your use case.

Alternatively, if you don't need the URL chain in the moment, but only need it later, you can use Playwright's recordHar feature and walk the HAR file. This is outside the scope of PW issues/help though.

**Comment by dlc9113** [comment]
Thank you so much! I changed that code to output the url list, then  I can see the initial url now.

**Comment by dimaBondarenko** [comment]
Hi @dlc9113 
Sorry for bothering you.

Could you please share your code snippet?
I've got the same case and am struggling to test it properly.

**Comment by dlc9113** [comment]
@dimaBondarenko sure, then point is using [BrowserContext class](https://playwright.dev/docs/api/class-browsercontext)

```typescript
	async startMonitorNavigation() {
		this.page.requestUrls = [];
		await this.page.context().on('request', request => {
			if (request.isNavigationRequest()) {
				this.page.requestUrls.push(request.url());
			}
		})
	}

	async stopMonitorNavigation() {
		await this.page.context().on('request', () => undefined);
		return this.page.requestUrls;		
	}
```
