### ISSUE TITLE
[Feature] [html report] Open another screenshot after click on screenshot in diff mode

### ISSUE THREAD

**Issue by ya111** [microsoft/playwright#16455]
We have long screenshots in html report, so sometimes to see diff I need to scroll through 2-3 pages.

Then I wanna to use slider to see what's going on and I need to scroll up, then again scroll down.

I suggest to add a feature:
If u click on screenshot in diff mode than report should open screenshot in slider mode.

Example attached:

Screenshot 1: Default state and then click here
Screenshot 2: Enabled diff slider mode

Doesn't matter what state the slider will be in, but it looks like a good feature

<img width="948" alt="Screen Shot 2022-08-11 at 15 44 26" src="https://user-images.githubusercontent.com/15036205/184136008-398b3d16-7236-4230-8ca4-ddf11c7bcb04.png">
<img width="1274" alt="Screen Shot 2022-08-11 at 15 45 03" src="https://user-images.githubusercontent.com/15036205/184136114-1f78f5f2-50ea-4ab2-b134-0f95de7ec98b.png">

**Comment by rwoll** [comment]
Is the idea, click where the red arrow is pointing, and then a new window opens with just the screenshot slider of for the image you clicked?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
