### ISSUE TITLE
[Question] How do I verify that page sends the correct amount of requests of a type (JS/TS)?

### ISSUE THREAD

**Issue by randomactions** [microsoft/playwright#16462]
How can I verify that the page sends only one request of the type and doesn't send more than that on a user's action?

I can verify a single request using this:
```
// Subscribe to 'request' and 'response' events.
await page.on('request', request => {
console.log('>>', request.method(), request.url())
})
```

But how do I check if the page is only sending a certain amount of requests of a type and not less or more?

**Comment by rwoll** [comment]
This is a bit tricky since proving a "not" condition is unsatisfiable to some degree. Consider the following button click handler:

```js
myButton.addEventListener("click", (evt) => {
   evt.preventDefault();
   setInterval(() => fetch('/todos'),  10_000);
});
```

When I click the button, it's easy to assert/wait for one request:

```ts
const [request] = await Promise.all([
    page.waitForRequest(/todos/),
    page.locator("text=Get Todos").click(),
]);
```

However, since I mistakenly used `setInterval` instead of `setTimeout` in my handler, the page will make a second request after 10 seconds. So, I could assert we get _at least_ 1 request, but when do I wait until to make sure there's not a second request? There's unfortunately no good answer, but this isn't limited to PW, it's present in any general testing scenario.

Does this make sense?

The best you could do is make a best effort attempt doing something like the following:

At the start of your test, do:

```
const requests = [];
await page.on('request', request => {
    requests.push(request);
});
```

and then at the end of your test you can walk that array and make sure the counts of things are expected, although this won't catch everything since Playwright doesn't know the future :)

**Comment by rwoll** [comment]
Closing per-above as part of triage. If you're still facing an issue, please file a new issue referencing this one!

Thanks!
