### ISSUE TITLE
Project actionTimeout does not work

### ISSUE THREAD

**Issue by MihirModiAC** [microsoft/playwright#16478]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Mac
- Node.js version: 18.3.0
- Browser: Chrome
- Extra: BrowserStack execution 

**Code Snippet**

```
   projects: [
        {
            name: 'chromium',
        },
        {
            name: 'chrome',
            use: { ...devices['Desktop Chrome'] },
        },
        {
            name: 'chrome@latest:Windows 10@browserstack',
            use: { ...devices['Desktop Chrome'] },
        },
        {
            name: 'chrome@latest:OSX Monterey@browserstack',
            timeout: 240000,
            expect: {
                timeout: 30000
            },
            use: {
                browserName: 'chromium',
                channel: 'chrome',
                actionTimeout: 60000,
                navigationTimeout: 60000,
            },
        },
        {
            name: 'firefox',
            use: { ...devices['Desktop Firefox'] },
        },
        {
            name: 'webkit',
            use: { ...devices['Desktop Safari'] },
        },
    ],
```

**Describe the bug**
Updated actionTimeout in the project but the test case still fails after waiting for 30 seconds for Click action. It does not wait 60 seconds as updated in Project -> chrome@latest:OSX Monterey@browserstack -> use 
![Image 2022-08-11 at 11 50 53 AM](https://user-images.githubusercontent.com/58085288/184220503-4241eea5-396f-4ec0-89c1-fb1374fb0162.jpg)

**Comment by rwoll** [comment]
Running the following with Playwright 1.25

, the timeout behaves as expected:

<img width="780" alt="Screen Shot 2022-08-11 at 3 17 13 PM" src="https://user-images.githubusercontent.com/11915034/184251981-8be695a1-5e85-43a5-ae5c-630ae1677570.png">

```
import type { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  timeout: 120_000,
  projects: [{
    name: "example",
    use: {
      actionTimeout: 60_000,
    }
  }]
};

export default config;

```

```
import { test, expect } from '@playwright/test';

test('homepage has Playwright in title and get started link linking to the intro page', async ({ page }) => {
  await page.locator("foo").click();
});
```

Note some differences:

1. sets `timeout: 120000` at top-level of config
1. No browserstack
1. Recent version of 1.25 compared to the 1.18 you report with
1. `page.locator(…).click()` instead of `page.click(…)`

I recommend performing the following changes in order, running in between each change, to see if any of the following fixes it:

1. set `timeout: 120000` at top-level of config
1. does not use browserstack
1. uses locator.click
1. uses a recent version of PW

Let us know what you find!

**Comment by aslushnikov** [comment]
Looks like this has been responded to, so I'll close the issue. Please **re-file** if you think we still can be helpful to you!
