### ISSUE TITLE
[Feature] WebView2 Desktop testing support with Playwright

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#16545]
Hello Folks, is there any guidance on how to perform testing on Playwright for standalone WebView 2 desktop applications?

We have been able to connect to via `connectOverCDP` BUT!

I am running into an issue where there are no pages in the browserContext and I cannot create a new page or a new context, leaving me unable to test various parts of the application. What can I do to resolve this issue?

OR is there any Webview2 documentation or examples for a standalone application?

The same exact application setup works for Selenium.

---

Open tasks:

- [x] Make sure that we work with webview2, add test infra on our repo to guarantee, that we work overtime and don't regress (run essentially page tests inside it, like we do for Android and Electron) https://github.com/microsoft/playwright/pull/16827
- [x] Add a guide for it on our documentation site (all the language bindings) https://github.com/microsoft/playwright/pull/17190
- [ ] Add a guide on the msedge documentation site: https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver

**Comment by aslushnikov** [comment]
We should add some docs for this!

**Comment by mastrzyz** [comment]
Appreciate the work so far on this!

**Comment by mxschmitt** [comment]
Starting in the next release, we'll have [a dedicated doc](https://playwright.dev/docs/next/webview2) for it.

If you encounter any issues with the doc, or things which don't work, I recommend filing them in separate issues.

[This](https://playwright.dev/docs/next/webview2) doc explains the manual approach using CDP and connecting to webview2 controls, for having an easier integration, I filed this feature request: https://github.com/microsoft/playwright/issues/17617

Since the Playwright part is done by that, I'm closing it.
