### ISSUE TITLE
[BUG] Docker container gives this error: "Can not execute 'start-crawl': Exec format error"

### ISSUE THREAD

**Issue by jpbrightwave** [microsoft/playwright#16610]
**Context:**
- Playwright Version: Docker mcr.microsoft.com/playwright:focal

**Describe the bug**
Running the docker container in Scary Cloud gives the following error:

_"Can not execute 'start-crawl': Exec format error"_

**Comment by aslushnikov** [comment]
There's no `start-crawl` command in `mcr.microsoft.com/playwright:focal`. So as far as you don't install the command, it errors out correctly.

But it does look like you didn't share many important details; please re-file with exact steps for me to follow so that I can reproduce the issue locally and see the error for myself!
