### ISSUE TITLE
[Feature] Give trace output its unique file extension so that file associations can be used

### ISSUE THREAD

**Issue by khtan** [microsoft/playwright#16625]
The trace output is very useful. I would like to change its file extension from the generic .zip to something
more unique like .pwzip so that I can create a file association between .pwzip and 'npx playwright --show-trace'.
That way, clicking on the .pwzip automatically opens the trace instead of opening 7Zip etc.

Also, when my reporter output is set to 'html', the default behavior on clicking the .zip is to download it. I hope that by using .pwzid, the PW trace window will also be invoked from the browser.

This will make the Playwright trace a lot more convenient to use.

Originally, I thought that a configuration option to specific the extension might be good. However, it would just result in confusion as different people use different extensions. 

So it would be better if Playwright decides a unique extension so that everyone can then add the file associations in a consistent way.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
