### ISSUE TITLE
[BUG] Media Stream Flags for Fake UI and Fake Device aren't working for electron.launch()

### ISSUE THREAD

**Issue by sstuden1115** [microsoft/playwright#16621]
**Context:**
- Playwright Version: 1.23.4
- Operating System: MacOS
- Node.js version: 16.16.0
- Browser: Electron
- Extra: [any specific details about your environment]

**Code Snippet**

```javascript
let electronApp = await electron.launch({
          args: [
         '--use-fake-ui-for-media-stream',
         '--use-fake-device-for-media-stream',
         ],
          executablePath: "/Applications/app_name.app/Contents/MacOS/app_name"
        });
```

**Describe the bug**

Our MacOS Electron app requires microphone permissions. When attempting to launch the app for testing using the  --use-fake-ui-for-media-stream and  --use-fake-device-for-media-stream flags, the app is not given microphone permissions and still prompts the user to accept/deny microphone permissions.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
