### ISSUE TITLE
[Feature] allow `fill` and `type` to accept `number` as parameter

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#16660]
Both `fill` and `type` only accept `string` as their type. 

It would be nice if `number` was also accepted, as getting typescript errors when your input is a number is a bit annoying, i.e.

Have to do this: `locator.fill(12.toString())`

![Screen Shot 2022-08-19 at 2 24 49 pm](https://user-images.githubusercontent.com/20273647/185543234-0c4b5a38-242f-4896-8a96-6a35f9b27801.png)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by 4ekki** [comment]
+1 for this. It's incredibly frustrating to convert numbers into strings just to type them into text inputs.
