### ISSUE TITLE
[Question]: css connected as a link should be considered an XHR request?

### ISSUE THREAD

**Issue by AntonGsv** [microsoft/playwright#16673]
### Your question

The request executed because of the tag
```<link rel="stylesheet" href="/1/dist/desktop/common.css">``` in the resource_type has an XHR value and is not filtered out as expected, is this expected behavior for this connection case?

**Comment by aslushnikov** [comment]
> The request executed because of the tag
<link rel="stylesheet" href="/1/dist/desktop/common.css"> in the resource_type has an XHR value and is not filtered out as expected, is this expected behavior for this connection case?

@AntonGsv I'd speculate that there's some javascript on the page that actually does the XHR to the URL. But it's hard to tell with this much information!

If you absolutely sure we misattribute stylesheet loading requests as XHR requests, than please re-file with a repro that we can run locally and debug!
