### ISSUE TITLE
[Feature] lifecycle hooks for instrumenting core objects / plugin architecture

### ISSUE THREAD

**Issue by tnolet** [microsoft/playwright#16690]
As a SaaS provider, we run Playwright workloads and add "out of the box" features that users do not have to think about. They just work. This includes tracking response times, snapping screenshots on errors, recording web vitals per page etc.

Right now, we have implemented this by monkey patching methods on the `Page` object and the `BrowserContext` object. It works, but downsides are:

- it's dirty and hard to maintain
- it's implicit instead of explicit
- it prohibits sharing these features as community contributions.

# Feature suggestion

Enable users to hook into the `Browser`, `BrowserContext` and `Page` creation / destruction lifecycle to instrument these objects explicitly. At the lower level this would mean a `onPageCreation()` hook that can be implemented by the user. At the higher level this could be a plugin framework that bundles and packages this into a coherent whole.

**Comment by uchagani** [comment]
Also interested in this for other language bindings!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
