### ISSUE TITLE
[Feature] custom selectors registered with a `path` should support content that isn't an expression

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#16705]
if i have a custom selector engine defined in a separate file:

```js
// main.js
const foo = 1;
module.exports = {
    query: (root, selector) => {},
    queryAll: (root, selector) => {}
}
```

what's the best way to register this file? i've tried several things such as:
```js
await selectors.register("foo", {path: "./main.js"})
await selectors.register("foo", {content: await readFile("./a.js", "utf8")});
```

but they all seem to expect an expression:
```
SyntaxError: Unexpected token 'const'
```

imo if i use `path`, it should allow any js file, and use its default export or something.

here's the workaround i came up with, but surely there's a better way to do it:
```js
await selectors.register("foo", {content: `(() => {${await readFile("./main.js", "utf8")};return module.exports.default})()`});
```

**Comment by DetachHead** [comment]
on a related note, what's the recommended approach to publishing custom selector engines? [here's mine](https://github.com/DetachHead/playwright-xpath), i kinda winged it though since i haven't seen anyone publish one before

**Comment by mrmckeb** [comment]
We've just hit this too, and used the same approach for now.

It feels like the problem here is that the selectors run entirely in a browser context. It would be great if instead, custom selectors could be a middleware that produced a query selector. That feels like it would solve the main usability issues around custom selectors.

```ts
// my-selector.ts
import { myFn } from './my-fn';

export default (selector) => {
  const processedSelector = myFn(selector);
  return `[data-xyz=${processedSelector}]`
}
```

**Comment by DetachHead** [comment]
> It feels like the problem here is that the selectors run entirely in a browser context.

i don't think that's necessarily the issue because non-expressions can easily be sent to the browser context. though it certainly does cause confusion especially since i don't think that's mentioned anywhere in the documentation. i've just raised #16915 regarding this.

> It would be great if instead, custom selectors could be a middleware that produced a query selector.

idk, [my selector engine](https://github.com/DetachHead/playwright-xpath) for example benefits from being executed in the browser as it has access to the `root` object. though perhaps it's possible to serialize and send it to the nodejs context?

though a selector engine that just produces a query selector can easily just be written as a regular function. eg:

```ts
const xyz = (selector) => {
  const processedSelector = myFn(selector);
  return `[data-xyz=${processedSelector}]`
}
page.click(xyz("foo"))
```

**Comment by KotlinIsland** [comment]
The process for selector engine developers seems highly boilerplated? Could there be some kind of functionality where an npm package can be used in the different language targets, so that if I'm using Python, I am still able to use selector engine packages from npm.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
