### ISSUE TITLE
[Question] What is history id?

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#16721]
You wrote https://github.com/microsoft/playwright/releases/tag/v1.25.0

```
https://playwright.dev/docs/api/class-testcase#test-case-id

Unique test ID that is computed based on the test file name, test title and project name. Test ID can be used as a history ID.
```

but what is `history ID`?)

Also, you wrote

```
New 'interrupted' test status.
```

When this status is actually used? When I close the browser manually during debugging the test? Or there could be more situations for that status?

**Comment by yury-s** [comment]
> but what is `history ID`?)

See discussion in https://github.com/microsoft/playwright/issues/14310, you can use that id to track history of the test between runs. The documentation can be improved.

> When this status is actually used? When I close the browser manually during debugging the test? Or there could be more situations for that status?
It is when the entire harness run was aborted because of e.g. fatal error and some tests were still running and could have passed but we don't know if they would as they didn't have chance to complete.

**Comment by Diokuz** [comment]
cool, thanks!
