### ISSUE TITLE
[Question]: Is that a way modify request cookies before it perform?

### ISSUE THREAD

**Issue by Yxue-1906** [microsoft/playwright#16773]
### Your question

I try to register a handler by page.on("request")
the handler like below:
``` python
def handleRequest(route):
    for key in route.request.headers:
        if key.startswith("cookie"):
            route.request.headers[key] = re.sub(<regex_pattern>, repr, headers[key])
        print(key + ": " + route.request.headers[key]
    route.continue_()
```
but it not work...

**Comment by rwoll** [comment]
Repro test case added: https://github.com/microsoft/playwright/pull/16774

Per the prior issue (https://github.com/microsoft/playwright/issues/7999), cookie and other headers with security-related implications, may not be overridable due to constraints of the browser network stack's themselves. Added P3-collecting-feedback to collect feedback on this limitation.

@Yxue-1906 Can you elaborate on your use case? We'd like to better understand when this issue surfaces for you? Is this in a testing context or a general scripting/scraping or automation context?

Thanks!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
