### ISSUE TITLE
[Question] Loading extensions in non-persistent contexts

### ISSUE THREAD

**Issue by charxhit** [microsoft/playwright#16798]
Going over the documentation of [chrome extensions](https://playwright.dev/python/docs/chrome-extensions), it implies that loading extensions in non-persistent contexts is not possible. I wanted to check whether this is an oversight? I have detailed a solution which makes it possible to load extensions in non-persistent contexts [here](https://stackoverflow.com/a/73450949/16310741), with emphasis on point 5 in the answer.

**Comment by yury-s** [comment]
Looks like an oversight, we should update the docs.

**Comment by yury-s** [comment]
@charxhit would you be interested in updating playwright docs with the instructions how to test extensions in ephemeral contexts?

**Comment by charxhit** [comment]
@yury-s sure, I'll make time to submit a PR.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
