### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by masaplecas** [microsoft/playwright#16801]
Hi, is it possible to add feature to be able to add video recording to browser context after it has been created?
Use case is making video recording optional, so I can create browser context and set recording based on bool parameter.

**Comment by yury-s** [comment]
There is no such API, the only way to enable video recording is to pass [recordVideo](https://playwright.dev/docs/api/class-browser#browser-new-context-option-record-video) option while creating a browser context (so this is the last moment when you can decide if the videos should be recorded). Each video is recorded from the moment a page is created and until it is closed.

Closing this issue since there are no plans to extend that API.
