### ISSUE TITLE
[Question] How to retrieve a selector text from a locator?

### ISSUE THREAD

**Issue by jkalandarov** [microsoft/playwright#16807]
Hi folks!

Thanks for the awesome framework (spoiler alert: my favorite one)!

I was wondering how to retrieve a selector text of the locator as a string.
For example:
```
const button = this.page.locator('#button-submit');
const selector = button.getSelector(); // => '#button-submit'
```

Thanks in advance!

**Comment by thomaschaplin** [comment]
You might benefit from using [Page Object Model](https://playwright.dev/docs/test-pom) but maybe in a different way such as below... that way you can use the string in your `page.selector` and as a string by itself.

```ts
// playwright-dev-page.ts
import { Page } from '@playwright/test';

export class PlaywrightDevPage {
  readonly page: Page;
  readonly myButton: String;

  constructor(page: Page) {
    this.page = page;
    this.myButton = '#button-submit';
  }
  
  ...

  async doSomething() {
    await this.page.selector(this.myButton).click();
    console.log(this.myButton) // this would result in "#button-submit"
  }
  
  ...
}
```

Instead of having a way to "get" the selector, declare it as a variable and then use it throughout your code.

**Comment by yury-s** [comment]
As suggested above there is no API to get selector from a locator. If you want to reuse a selector it can be saved to a variable and later used to construct multiple locators. 

Relevant feature request: https://github.com/microsoft/playwright/issues/12553

Closing this issue as we're not planning to expose the selector at the moment.

**Comment by v-mwalk** [comment]
Having an optional string property (or even a general-use object property!) in a Locator _would_ be really nice.  When a Locator fails for any reason (element doesnt exist, etc), within a framework I present a 'human-readable' error (So, instead of 'Error: some-non-human-readable-selector not found' I have 'Error: Plan [Energy: Gas, Name: Flexible] not showing'.  At the moment, I have to wrap a Locator in an object with the Playwright locator, original selector string and human-readable description.  Would be easy to add to a Locator with no impact, but would enable 'advanced' framework designers ability to really enrich Locators....
