### ISSUE TITLE
[Question] Playwright + Electron + Sandboxing + CI = "electron.launch: Timeout 30000ms exceeded."?

### ISSUE THREAD

**Issue by eliw00d** [microsoft/playwright#16814]
I have the following in my main.js:

```javascript
app.enableSandbox()
```

I have a playwright test like so:

```javascript
electronApp = await electron.launch({ args: ['main.js'] })
```

And if I run the following locally:
```sh
yarn package
yarn playwright test
```

Everything works fine. However, if I run the same in CI I get:

```sh
electron.launch: Timeout 30000ms exceeded.
--
13 | > 29 \|     electronApp = await electron.launch({ args: ['main.js'] })
```

If I wrap the main.js code like so:

```javascript
if (!isCI) {
  app.enableSandbox()
} 
```

It works again in CI. 

I guess I'm confused as to why it would work locally with sandbox on but not in CI. Is this a bug? Granted, `CI="true"` in my CI, but even if I add that to my local command it still works with sandbox.

**Comment by yury-s** [comment]
The CI probably runs your tests in a container which prevents chrome sandbox from starting, we've seen this problem in the past when it required passing custom `seccomp` profile to docker (see e.g. https://github.com/microsoft/playwright/pull/1161) but disabled the sandbox later since it caused many problems in containers and CI while having sandbox is not crucial in test 
environment. We currently don't support running with sandbox enabled, you can debug the issue by running with `DEBUG=pw:browser` but I'd suggest you just disable (not enable?) the sandbox in the test environment. Does it make sense?

**Comment by eliw00d** [comment]
> The CI probably runs your tests in a container which prevents chrome sandbox from starting, we've seen this problem in the past when it required passing custom `seccomp` profile to docker (see e.g. #1161) but disabled the sandbox later since it caused many problems in containers and CI while having sandbox is not crucial in test environment. We currently don't support running with sandbox enabled, you can debug the issue by running with `DEBUG=pw:browser` but I'd suggest you just disable (not enable?) the sandbox in the test environment. Does it make sense?

It does! Thank you for the explanation. I will just keep the `!isCI` check in place.

**Comment by yury-s** [comment]
Closing as there is a workaround and no further planned action on playwright side.
