### ISSUE TITLE
[Question] Is it possible to pause all workers when 1 worker is running a specific test?

### ISSUE THREAD

**Issue by Doug-Bowen** [microsoft/playwright#16852]
**Situation**: 
I'm automating an app that requires us to refresh our authenticated sessions every 15 minutes.  We're using a reusable storage state and beforeEach that checks to see if it has been 13 minutes.  If so, we refresh the storage state. 

**Challenge**:
Unfortunately, all 6 workers will detect that they need to refresh their state and they will all attempt to refresh the same state, causing collision.  Fortunately, our test suite recovers ONLY because we have a generous retry policy in place.  

**Question**:
Is it possible that, when a single worker has identified the need to re-authenticate, to pause all existing workers and allow 1 worker to update the shared stored state?  If not,  what alternative do I have in this situation?

**Comment by yury-s** [comment]
> Is it possible that, when a single worker has identified the need to re-authenticate, to pause all existing workers and allow 1 worker to update the shared stored state?

There is no builtin mechanism that would allow to pause the workers, it's up to the test runner in which order and on what workers it runs the tests.

> If not, what alternative do I have in this situation?

You could synchronize current status of storage refresh request between worker processes (e.g. by bring up a local server in globalSetup)  and ensure that there is at most one active request to the server at any given moment. The server would be the only process that can refresh storage state, keep track of last refresh timestamp and then in beforeEach you can ask the server to refresh the state if 13 mins have past.

But instead of that I'd recommend you use different sessions (accounts?) per worker. You can create a session in beforeAll based on e.g. [worker parallel index](https://playwright.dev/docs/api/class-workerinfo#worker-info-parallel-index) to ensure no two workers connect to the same account at the same time.

Does any of those options work for you?

**Comment by Doug-Bowen** [comment]
Yes.  I think so.  Thank you!
