### ISSUE TITLE
[Question] Access vue 2 instance of component

### ISSUE THREAD

**Issue by oliver-freudrich-packwise** [microsoft/playwright#16889]
Hey there, is there currently a way to access eg. the data, methods or anything of a mounted component or in general the vue instance of the component in the tests?

Something like this (I know this would return the component, not the vue instance but just to illustrate it a bit):

Test.vue

```vue
<template>
  <div></div>
</template>

<script>
export default {
  data() {
    return {
      myValue: 'test',
    };
  },
  methods: {
    test() {
      return true;
    },
  }
}
</script>
```

test.spec.jsx

```javascript
import {
  test,
  expect,
} from '@playwright/experimental-ct-vue2';
import Test from './Test.vue';

test('my test', async ({ mount }) => {
  const component = await mount(<Test />);
  console.log(component.myValue);
  expect(component.test()).toBeTruthy();
});
```

**Comment by pavelfeldman** [comment]
We can consider `component.evaluate` that would have the component as this.

@sand4rt wdyt?

**Comment by sand4rt** [comment]
Exposing the component instance _(for any framework)_ leads to testing implementation details. I would instead resemble the tests the way the software is used. This will eventually lead to better tests that won't break as quickly if you refactor something and helps preventing false negative and false positive test results. I **highly** recommend reading [this article](https://kentcdodds.com/blog/testing-implementation-details) from the creator of [testing library](https://testing-library.com/docs/guiding-principles), which explains this in more detail. 

@oliver-freudrich-packwise Can you share the code of a real use case you are trying to test? Then i can help you with an example of what the test should look like.

**Comment by oliver-freudrich-packwise** [comment]
Hey @sand4rt and thanks for the anwer and sharing the article, that is really interesting! Well my idea was more about the mixins in Vue 2, which I want to test more like a "unit" test to ensure the functionality in general and then check normal components, which are using the mixin, in the non implementation details way. Something like this (with the suggested function of @pavelfeldman and the same principle we are currently using in our app):

userMixin:

```vue
<script>
export default {
  methods: {
    async getUser() {
      const user = (await axios.get('/user')).data;
      this.$store.commit('setUser', user);
    }
  },
}
</script>
```

userMixin test:

```javascript
test('should try to load a schema', ({ mount }) => {
  const component = await mount(<UserMixin></UserMixin>);
  await component.evaluate(async () => this.getUser());
  expect(await component.evaluate(() => this.$store.getters.user)).toBeDefined();
});
```

component:

```vue
<template>
    <div>
      <button id="get-user" @click="getUser" />
      <div v-if="user" id="user">{{ user }}</div>
    </div>
</template>

<script>
export default {
    ...
    computed: {
      user() {
        return this.$store.getters.user;
      }
    },
    mixins: [userMixin],
    ...
}
</script>
```

component test:

```javascript
test('should try to render the schema as items', ({ mount }) => {
  const component = await mount(<Component></Component>);
  await component.click('#get-user');
  await expect(component.locator('#user')).toBeVisible();
});
```

But according to the article you send, we could just skip the mixin "unit" test and only test the component, because it is also covering the mixin test by ensuring a working component right?

**Comment by sand4rt** [comment]
Yes that's right. The component test is the test you need in that case. You don't need to test the mixin as you have already covered it by mimicking the user behaviour inside the component test _(which is a good thing)_. Defining the tests this way opens the possibility to migrate the Vue3 without effecting the tests much as well.

Note that the component test makes a real API call which i personally would avoid. You could mock this API call with [Playwright's API mocking feature](https://playwright.dev/docs/api/class-route#route-fulfill). 

Also i would avoid using `id` for the DOM selectors and use accessibility, text or `data-testid` instead. IDs and test selects have a different reason to change. For example, changing the `id` for styling reasons should not break your tests.

As last, you are verifying if the div exists instead of checking if the user is shown. The latter would imo be better as it is closer to mimicking user behaviour.

The test for the first use case could look like this:

```typescript
test('render a user when the get user button is clicked', ({ mount }) => {
  await page.route(`/user`, async (route) => {
    await route.fulfill({
      contentType: 'application/json',
      body: 'Admin'
  });
  const component = await mount(<Component></Component>);
  await component.click('data-testid=user-button');
  await expect(component.locator('data-testid=user')).toHaveText('Admin');
});
```

Could you provide the associated HTML for the second test case?

**Comment by sand4rt** [comment]
I see where you come from and i've been there as well. IMO people in the Vue community aren't that advanced when it comes to testing best practices because they are used to Vue Test Utils and VTU takes similar approaches as enzyme which is talked about in the article i sent earlier. Enzyme was the default library for testing react apps and is almost dead now. Most projects are migrated to testing library _(where this philosophy of testing comes from)_. In addition there is a adaption of the testing library philosophy for other frame works. For example Solid and Svelte frameworks only support testing library for good reasons.

I see where you come from and I've been there as well. IMO folks in the Vue community are not that advanced when it comes to testing best practices as they are used to Vue Test Utils and VTU takes the same approaches as enzyme _(which is talked about in the article I sent earlier)_. Enzyme was the standard library for testing react apps and is now as good as dead. Most projects migrated to the test library _(where this philosophy of testing comes from)_. In addition, there is an adaptation of the test library philosophy for other frameworks as well. For example, Solid and Svelte frameworks only support the test library _(for good reasons)_.

It could makes sense for your situation right now, but generally speaking i would try to avoid that. You could test for this with end to end tests and or API tests _(if you are using typescript)_.

Without going into too much detail, IMO there are _(some minor)_ cases where pure unit testing makes sense, for example for performance optimizations. Then what you could do is extract that logic out of your modules/components test it in isolation. But i would try to avoid that as much as possible.

**Comment by oliver-freudrich-packwise** [comment]
True words and thanks for that explaination. I mean it's hard to decide about the way to test when there are "standard librarys" which are the basically using an outdated way of testing. But I like this "new" way without the implementation detail way more, because it's maybe more initial work, maybe not event that, but in general less maintanance to do for the tests. Maybe those info would be great on the component testing page of playwright to spread those information about modern testing and prevent further issues like this (or at least link some articles like you've send me).

Thanks again for clarifying a cleaner way of writing tests and for your time!

**Comment by sand4rt** [comment]
Keep in mind that i'm not a core member of Playwright and i'm not sure if they are on the same page with this. Well, Vue Test Utils works okay, they just added features that will send you down the wrong path if you're not careful.

This is the documentation we currently have on component testing: https://playwright.dev/docs/test-components. I agree that this is not very comprehensive yet. Not sure if possible but maybe [debs-obrien](https://github.com/debs-obrien) can help out with this?😁

Would be good to read the other blog posts from Kent as well: https://kentcdodds.com/blog?q=testing. I find them extremely helpful.

No problem!

**Comment by segevfiner** [comment]
We are passing props and event handles to the component... How would you test exposed values which are similar without access to the component instance? They are still part of the public facing API of a component.

**Comment by sand4rt** [comment]
@segevfiner apparently Vue test utils also has a piece of documentation this topic: https://test-utils.vuejs.org/guide/essentials/easy-to-test.html. Let me know if this helps!

**Comment by segevfiner** [comment]
Playwright isn't based on VTU. In VTU this can be done by accessing `wrapper.vm`. Of course, you should only test exposed stuff that are part of the component's public API and not random data or methods.
