### ISSUE TITLE
[Question] Having trouble using adjacent sibling combinator

### ISSUE THREAD

**Issue by mikefirefly** [microsoft/playwright#16896]
Is it possible to combine locators in this manner, in order to extract text from an element following another element? I have trouble doing that. Here's my code:

```
const username = await page
      .locator('div[data-testid="MessagesList.UserCard"]')
      .nth(5) // there are multiple UserCards on the page
      .locator(' + div[data-testid="MessagesList.SystemMessage"']
      .locator('div[class="MessageContent"]')
      .textContent()
```

**Comment by pavelfeldman** [comment]
I don't think it works that way, you can only use "+" within css selector. I'm not sure I understand what you are trying to select, but you can try using `has`. That way you can select a parent that has certain child and query text of the descendant of that child. I'll leave this as a feature request for a `locator.sibling`.

**Comment by mikefirefly** [comment]
Thanks. This is what I want to get: [image](https://i.imgur.com/yi3S6jG.png), I'm not sure if `has` will help.

**Comment by dgozman** [comment]
@mikefirefly As a workaround for now:

```js
page.locator(':nth-match(div[test-id="MessagesList.UserCard"], 5) + div[test-id="MessagesList.SystemMessage"]')
```

**Comment by jarnovanrhijn** [comment]
How would you always select the last element with 'nth-match'

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
