### ISSUE TITLE
[Question] Using Playwright with DRM content

### ISSUE THREAD

**Issue by sky-brunoteixeira** [microsoft/playwright#16897]
Hi, I'm doing a POC using playwright and the two most important requirements are being able to play DRM content, and being able to use Chrome, Firefox and Safari.
From what I saw until now, for Safari, I can use the default WebKit configuration, for Chrome I can use Chromium with `channel: chrome` to use instead.
```
{
  name: 'chromium',
  use: { browserName: 'chromium', channel: 'chrome' },
},
```
The issue I'm having is with Firefox, I'm unable to play DRM content on Nightly. 
Can I configure Playwright to use Firefox instead?
Is there any configuration, either using NIghtly or Firefox, that would allow me to play DRM content?

I've tried this so far, without success:
```
{
  name: 'firefox',
  use: {
    browserName: 'firefox',
    launchOptions: {
      firefoxUserPrefs: {
        'media.gmp-manager.updateEnabled': true,
      },
    },
  },
},
```

![image](https://user-images.githubusercontent.com/85165496/187703982-2463389f-70ff-4d04-a401-d41fef6e7a0e.png)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
