### ISSUE TITLE
[BUG] Print the URL browser is downloaded from

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#16926]
Often times browser can't be downloaded due to proxy / firewall / security system on the client machine. Printing the url of the browser would help clients fetching it manually and would help them talk to the security departments while explaining the issue.

**Comment by aslushnikov** [comment]
Note for self: use `npx playwright install --dry-run` to print URLs and paths of the related browsers.

**Comment by aswatsankar** [comment]
Hi @aslushnikov Still no luck with the command. Not sure If I am missing anything here. Can we manually install drivers and map with playwright to get rid of this problem. Also it would be great if you provide commands for java instead of nodejs. Thanks in advance. 
![image](https://user-images.githubusercontent.com/24888082/187555757-79d3d84e-77b9-4326-9dca-8d6ec000ab3c.png)

**Comment by pavelfeldman** [comment]
Let's address this as requested!
