### ISSUE TITLE
[Question] page.waitForTimeout is added to traces 

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#16940]
Hello Playwright team,

in my tests I have on one or two places a code that poll for element to be visible and click it.

```java
public void pollForElementToBeVisible(Locator locator, Integer seconds) {
        Instant start = Instant.now();
        while (!locator.isVisible() && Duration.between(start, Instant.now()).getSeconds() < seconds) {
            page.waitForTimeout(50);
        }
    }
```
    
   As you can see I am using page.waitForTimeout(50);, which I can see also in the traces as a step with screenshots.
   
Sometimes this polling of element is taking a long time, which means all that waitForTimeout is logged with screenshots and in the end I get a trace file over 300 MB.
    
Maybe this should not be logged in with screenshots in the traces.
    
    
![image](https://user-images.githubusercontent.com/94455079/187559106-993a2fac-1909-455e-8c1d-ab8d18e67a1e.png)

**Comment by pavelfeldman** [comment]
Playwright will wait for the element to be visible before it clicks it, so you can delete all this code!

**Comment by NikkTod** [comment]
Hi @pavelfeldman, the thing is that this element may or may not appear. I just need to wait for 2 seconds and only if it apper to click it.

**Comment by pavelfeldman** [comment]
I see. It is not like 2 seconds are going to make your test stable though.

You can try

```js
page.locator('/button[contains(...)]').click({ timeout: 0 }).catch();
```

that way it hangs there forever and when the element appears, it clicks it. Notice how I am not awaiting the call so that the execution could go further. Use with caution though.

**Comment by NikkTod** [comment]
I like it, will definitely try it. Thankss Pavel.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
