### ISSUE TITLE
[Feature] Integrate the HTML report

### ISSUE THREAD

**Issue by baptisteArno** [microsoft/playwright#16958]
Hey guys,

It would be amazing if we can check the generated `playwright-report` after the tests, like a button or a auto-open.

Right now, I need to navigate to the report directory, serve the files using `npx serve` and click on the HTML file.

What do you think?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
