### ISSUE TITLE
[Feature] Javascript generation in vscode extension

### ISSUE THREAD

**Issue by sahmeepee** [microsoft/playwright#16967]
Currently the vscode extension generates typescript straight into the editor in a similar fashion to codegen. Codegen, however, can generate JavaScript as well as typescript.

It would be useful for people writing their tests in JavaScript if the vscode extension had an option to generate JavaScript as well.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
