### ISSUE TITLE
[Feature] Show DEBUG=pw:api output

### ISSUE THREAD

**Issue by np-xavier** [microsoft/playwright#16963]
With the latest version of the extension (my framework is on 1.19.2 at the moment), I can't seem to get the log of actions Playwright is performing. In previous versions (IIRC), there was a button in the lower status bar along the lines of "Enable Playwright Debug" which would then output all the actions the browser was performing to the debug log. Right now I only get "Running 1 test ... " in the Debug Console window which is where I believe the detailed logs appeared last time.

How can I enable / see this in the latest version? Many thanks!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
