### ISSUE TITLE
Extension doesn't work with projects that don't install node modules in the root folder

### ISSUE THREAD

**Issue by remusa** [microsoft/playwright#16965]
The extension doesn't detect Playwright and tests if dependencies aren't installed in the root folder. 

For a bit of background, I'm using Elixir/Phoenix in a project and node dependencies typically go into the `assets/` folder.

I didn't find an option to change the installation folder, but maybe I missed something.

[Installation — Phoenix v1.5.13](https://hexdocs.pm/phoenix/1.5.13/installation.html#node-js)

` ` `
/
      assets/
                 node_modules/
                 package.json               
      other_elixir_or_phoenix_folders/
` ` `

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
