### ISSUE TITLE
[Question] can we generate test with with custom setup

### ISSUE THREAD

**Issue by kspolam** [microsoft/playwright#16964]
for example i want to launch recorder with below setup
--viewport-size=800,600

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
