### ISSUE TITLE
Allow configuring docker runner

### ISSUE THREAD

**Issue by nickofthyme** [microsoft/playwright#16960]
I develop on a mac but run all playwright tests inside a docker container using `mcr.microsoft.com/playwright:vx.x.x-focal`.

It would be great if this extension was able to run in docker instead of the local browser executables, and lookup the `@playwright/test` version to select the correct docker image.

Reference ➡️ https://playwright.dev/docs/docker

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
