### ISSUE TITLE
Can we add support for custom commands within the extension?

### ISSUE THREAD

**Issue by loganromero** [microsoft/playwright#16968]
I leverage env files to house my baseURL and user/pwd information. Currently I use a different env file based on whether or not I'm in my TEST or UAT environment (which I call with a yarn command - uat-env or test-env).

Perhaps the addition would be to have another option in the dropdown for environments or allow for us to change the command that is called for triggering a test?
![image](https://user-images.githubusercontent.com/50672017/155587011-76784deb-d6a7-46c0-8d14-4fc02937b90a.png)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
