### ISSUE TITLE
Run debug in headless mode

### ISSUE THREAD

**Issue by bennettdams** [microsoft/playwright#16961]
I would like to run the tests that I start via VS Code in headless mode.
In my case, I'm running VS Code with WSL 2 (Ubuntu) and a devcontainer, so I can't/won't start a browser for the debugger run - I rather want to be able to stop at breakpoints in the editor, so I don't "need" the browser.

The `headless: true` option from my `playwright.config.ts` is ignored, so:

Is there a way to start the debugger in headless mode right now?

Additionally: I don't need the debugger all the time, but rather want to use the normal "run". But, `console.log`s are not shown via the normal "run", as the output is not shown anywhere. Only the "debug" run will show output in VS Code's "DEBUG CONSOLE" UI. Is this expected or should I create a new issue?

**Comment by JakubKoralewski** [comment]
More support for WSL, Remote-SSH would be great. In the mean time this launch.json configuration worked for me:

```json
        {
            "command": "pnpm playwright test ${file}",
            "name": "Playwright test",
            "request": "launch",
            "type": "node-terminal",
            "cwd": "${workspaceFolder}/web_app",
        },
```

**Comment by bennettdams** [comment]
@JakubKoralewski I don't know if anything has changed for VS Code/Playwright in this regard since I created this issue, but your `launch.json` works great! The debugger stopps at a breakpoint as expected. Thanks!

Not sure if this issue should be closed then?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by simensol** [comment]
For those seeking a solution to run Playwright tests in headed mode within a devcontainer, this guide is effective: https://www.oddbird.net/2022/11/30/headed-playwright-in-docker/
