### ISSUE TITLE
support other languages (vscode extension)

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#16971]
i know playwright test is only available for nodejs, but some of the features in this extension would be useful when using playwright with other languages, such as the "Enable Playwright Debug" button

**Comment by StefanIGit** [comment]
Would be really nice to have this extension for python (pytest)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by joegiglio** [comment]
I was surprised to see this not gained any traction yet.  Is this on any future roadmap we know of?

**Comment by Zippycz3ch** [comment]
Why its this closed?
