### ISSUE TITLE
[BUG] The text's difference is not highlighted in the Preview Test Failure Message

### ISSUE THREAD

**Issue by elaichenkov** [microsoft/playwright#16979]
**Context:**
- Playwright Version: 1.20.0
- Browser: all
- Playwright Test for VSCode: v0.2.2

```sh
  System:
    OS: macOS 11.6.2
    Memory: 381.47 MB / 16.00 GB
  Binaries:
    Node: 15.12.0 - ~/.nvm/versions/node/v15.12.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v15.12.0/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Description:**
I'd expect the same output as we have in the Debug console/Terminal.

Actual:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/29764053/160132478-71a6bf63-cd74-4108-8132-00989e73ed6d.png">
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/29764053/160132569-41eeeeae-c3d7-4c46-a305-962c2e42f614.png">

Expected:
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/29764053/160132685-04ac22d9-5d56-405a-b9b3-4864109c9538.png">

**Test example:**

```typescript
import { test, expect } from '@playwright/test';

test.describe('Google', async () => {
  test('should work', async ({ page }) => {
    await page.goto('https://google.com');
    await page.type('input[name=q]', 'playwright');
    await page.keyboard.press('Enter');

    await expect(page).toHaveURL('https://www.google.com/search?q=playwright');
  });
});

```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
