### ISSUE TITLE
syntax highlighting/validation for playwright selectors

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#16972]
like in webstorm (though they don't support playwright selectors, only css selectors and xpath separately)
![image](https://user-images.githubusercontent.com/57028336/134434488-867b4e2b-b761-482e-954d-3a5ee0500fcd.png)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
