### ISSUE TITLE
Support snapshot previews on mouse hover

### ISSUE THREAD

**Issue by schickling** [microsoft/playwright#16973]
Would be great if this VSC extension could also enable snapshot previews similar to this tool: https://github.com/asvetliakov/typescript-snapshots-plugin

<img width="733" alt="image" src="https://user-images.githubusercontent.com/1567498/133894425-0161b7eb-f65e-49b1-b327-b82a394d2a65.png">

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
