### ISSUE TITLE
Unable to filter by tag 

### ISSUE THREAD

**Issue by 1RossFisher1** [microsoft/playwright#16988]
When filtering by "@" tag, all tests are shown. 

Only one test should be shown.
![image](https://user-images.githubusercontent.com/109974928/185767829-dbfc6c28-9d7c-4d45-a3b1-2ba20e40c2aa.png)

Tag is able to be searched for without "@".
![image](https://user-images.githubusercontent.com/109974928/185767849-116812a7-a5cc-41e5-8e11-cf81b82eb71d.png)

**Comment by pavelfeldman** [comment]
It looks like VS Code has its own treatment for @. I'll file it against them, you can use #smoke for now to work around it.

**Comment by pavelfeldman** [comment]
Filed as https://github.com/microsoft/vscode/issues/159708

**Comment by WorikQCI** [comment]
I am having the same problem.

```
Version: 1.72.2 (Universal)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:30.254Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```

In my case I think it may be a problem with the Flutter extension.

As far as I can tell the test filter has no useful effect except for @executed, @hidden, etcetera.

**Comment by executed** [comment]
what's up? 😂

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
