### ISSUE TITLE
[Feature] API to filter tests for run

### ISSUE THREAD

**Issue by baev** [microsoft/playwright#17037]
Request from Allure Team (approved by @pavelfeldman , please do not close)

Allure has a [selective run](https://docs.qameta.io/allure-testops/integrations/com/runjob-selective/) feature. In order to support it we need to have a possibility to filter Playwright tests before run. 

The usually flow looks like this:

1. User adds a Allure Reporter & Allure Filter to tests configuration
2. Allure Reporter collects `fullName`, `internal test selector` (test id that used by test framework as unique id for test, if any, the good example is unique id from JUnit 5) and additional metadata such as tags or annotations
3. Allure processes the metadata to extract `ALLURE_ID` from it (by using naming convention)
4. `fullName`, `testSelector` and `ALLURE_ID` are stored in database per test case. 
5. During the run request if user want to run particular test cases Allure generates `testplan.json` that contains list of tests to run (`fullName`, `testSelector` and `ALLURE_ID` if specified)
6. Allure Plugin for CI makes sure that `testplan.json` is placed in workspace and `ALLURE_TESTPLAN_PATH` environment variable is set
7. Test Framework filter tests using AllureFilter (configured by user at step 1). If `ALLURE_TESTPLAN_PATH` env var is set, filter only runs the tests, that specified in `testplan.json` file

Related issue https://github.com/microsoft/playwright/issues/15981

PS we have multiple requests for such feature from our paid customers

**Comment by pavelfeldman** [comment]
Open to reviewing the PR!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
