### ISSUE TITLE
[Feature] Step-scoped attachments

### ISSUE THREAD

**Issue by baev** [microsoft/playwright#17038]
Request from Allure Team (approved by @pavelfeldman , please do not close)

Related issues: https://github.com/microsoft/playwright/issues/14364 and https://github.com/microsoft/playwright/issues/11592

PS we have multiple requests for such feature from our paid customers, for us this issue is really high priority as it makes attachments feature unusable in most cases

**Comment by pavelfeldman** [comment]
Open to reviewing a PR!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
