### ISSUE TITLE
[Question] Property 'customMatcher' does not exist on type 'MakeMatchers<void, Locator>'.

### ISSUE THREAD

**Issue by zeekrey** [microsoft/playwright#17142]
Hey there 👋🏻

I followed [the docs](https://playwright.dev/docs/test-advanced#add-custom-matchers-using-expectextend) on custom matchers but still have a Typescript error: `Property 'customMatcher' does not exist on type 'MakeMatchers<void, Locator>'.`

It feels like the global.d.ts is not picked up by Typescript. 

Here is an example: https://stackblitz.com/edit/jfgreffier-try-playwright-test-pn1wap?file=tests/example.spec.ts

**Comment by mxschmitt** [comment]
You had some typos in your code (called the wrong matcher and brackets were broken) and in the `global.d.ts` was an [export {} missing](https://stackoverflow.com/a/59499895/6512681), we'll update the docs accordingly.

With the following it works, I also added a Promise<R> since your new matcher is most likely async.

```ts
export {};

declare global {
  namespace PlaywrightTest {
    interface Matchers<R, T> {
      toBeWithinRange(a: number, b: number): Promise<R>;
    }
  }
}

```
