### ISSUE TITLE
[Feature] Sign Windows browser binaries

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#17165]
This issue is about signing Windows executables (`.exe`) files, if you are interested in having it, please upvote it.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by DipakTated** [comment]
Any update as its blocking our project which is dependent on signing of browsers, else we will have to look back to revert to some other tools like playwright?

**Comment by mxschmitt** [comment]
I recommend to continue to sign the files yourself as [it was working previously](https://github.com/microsoft/playwright-dotnet/issues/3070#issue-2694103206) or talk to your IT for further information. Maybe they can allow-list them.

**Comment by DipakTated** [comment]
problem is that playwright is part of our installer and installer is used in various customer machines.  We cant sign every customer downloaded chrome manually .  is there a way then, we have offline downloaded package of chrome, so we sign that and send it with our installer if Playwright is not willing to solve it at their end?

**Comment by DipakTated** [comment]
@mxschmitt  ?
