### ISSUE TITLE
[BUG] Component Testing: Unable to select from an unordered list dropdown

### ISSUE THREAD

**Issue by kk250571** [microsoft/playwright#17164]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Windows
- Node.js version: 16.11.33
- Browser: All

**Code Snippet**

Component Test Snippet: (.tsx)
```
    await this.stateDropdown.click();                                                         // clicking to open the dropdown
    await this.page.locator('li', {hasText:'California'}).first().click();             // finding state California in dropdown and selecting
```
How the dropdown is setup:  (.ts)
```
    <AutocompleteElement
      label='State'
      required
      name='state'
      textFieldProps={{ variant: 'standard', id: 'state-textfield' }}
      options={...listOfStates}
    />
```
**Describe the bug**

It seems like the component test is unable to see the opened list of options from the dropdown. Therefore, it is impossible to select a list item from the dropdown.

**Comment by dgozman** [comment]
@kk250571 Perhaps the select element uses native `<select>/<option>` elements? If so, you should use the [`locator.selectOption()`](https://playwright.dev/docs/api/class-locator#locator-select-option) method.

If that's not the case, could you please share the repro we can run locally? Otherwise, we won't be able to help.
