### ISSUE TITLE
[Question] Can I remove and add media devices?

### ISSUE THREAD

**Issue by hanagejet** [microsoft/playwright#17183]
I use `--use-fake-device-for-media-stream` to get a list of devices.
I am trying to write a test where devices are connected or removed. But I can't write it because there is no `--use-fake-device-for-media-stream` to connect or remove devices.

Can I solve this?

**Comment by dgozman** [comment]
@hanagejet There is no such functionality in Playwright today. As a workaround, you can mock some web APIs in the page, see [this guide](https://playwright.dev/docs/mock).

Let's leave this issue as a feature request.

**Comment by morsh** [comment]
@hanagejet Did you manage to find a workaround to this issue?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
