### ISSUE TITLE
[Feature] First class support for SharedWorkers

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#17197]
Our project is using [sharedworkers](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker) as we have the need to subscribe to changes with many open tabs.

Playwright has great first-class support for [web workers](https://playwright.dev/docs/api/class-worker) and [Service Workers](https://playwright.dev/docs/api/class-browsercontext#browser-context-event-service-worker).

I would like to request the same support for sharedworkers.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by paralin** [comment]
I also need thsi!
