### ISSUE TITLE
[Question] How to view fetch request priority?

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#17220]
We've implemented https://developer.mozilla.org/en-US/docs/Web/API/Request/priority which a relatively recent improvement to the fetch API.

We're able to find the attribute on the html element with playwright without issue.

We're more interested to see how the order of requests happen in real world user flows and therefore would like to see this property on the requests themselves. The test would look like this:

Load a common page which would trigger ~30 fetch requests and inspect the order of the requests and priority.

We don't see anything on the request object when using the `page.waitForRequest()` API. However, when we open the devTools tab on the running playwright session, we can clearly see the priority in the network tab.
<img width="630" alt="Screen Shot 2022-09-09 at 8 23 09 AM" src="https://user-images.githubusercontent.com/12446869/189387986-75d99391-fbd0-47dc-a5bf-e1553832c1de.png">

Do you have a recommendation on how we could access this property?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
