### ISSUE TITLE
[Feature] Allow component testing of yew (and other wasm frameworks)

### ISSUE THREAD

**Issue by WorldSEnder** [microsoft/playwright#17221]
:wave: I'm trying to create a playwright component testing framework for [yew](https://github.com/yewstack/yew).

In the progress, I'm using the https://github.com/wasm-tool/rollup-plugin-rust plugin for importing rust code. The major hurdle now is, that wasm is always loaded asynchronously. That is,

```
import { YewComponent } from '../Cargo.toml'; // Not possible, initialization is async
```

will not work, instead the transformation exposes an `init` function, that asynchronously initializes the wasm part:

```
import wasm from '../Cargo.toml';
const { YewComponent } = await wasm(); // Uh-oh, this is not recognized as a tested component
```

The problem with the latter is of course, that it is not found by playwright's "components under test" algorithm (which, honestly, sounds a bit brittle anyway, but that's not the point here). In the course of trying to fix this on my side, I've also tried writing a shim for the wasm module, but there is no way to know which components will be exported before (async) loading the wasm.

**Comment by Pauan** [comment]
The primary reason why this doesn't work is because playwright doesn't support top-level `await`.

Top-level `await` is a part of the JS standards (at [stage 4](https://github.com/tc39/proposal-top-level-await)), it is [implemented in all modern browsers](https://caniuse.com/mdn-javascript_operators_await_top_level), and it is also [implemented in NodeJS](https://www.stefanjudis.com/today-i-learned/top-level-await-is-available-in-node-js-modules/).

If playwright adds in support for top-level `await`, then this issue should be fixed (in addition to fixing other issues as well, since top-level `await` is useful in many situations).

**Comment by mxschmitt** [comment]
Seems like the issue was addressed in https://github.com/wasm-tool/rollup-plugin-rust/issues/35 so this issue is not relevant anymore?

---

Supporting top level await is a different story and not directly related to that, so I recommend filing a separate issue to address your requests in a feature request.

**Comment by Pauan** [comment]
Unfortunately the `synchronous` mode only works with Workers and NodeJS, so I suspect it will still break in various testing situations. So top-level `await` is still needed to correctly handle loading Wasm files.

**Comment by WorldSEnder** [comment]
I agree with Pauan. The `synchronous` mode for the rollup-plugin is a workaround that I don't expect to work in all situations. I hope to get at least a small repo up to showcase the issues soon.

What would also help is additional documentation about the syntactic rewriting that's taking place. From what I understand there's two processes/bundles, one loaded into the browser, that's taking care of mounting the components and running the assertions and one running locally that's running the test cases and communicating to the browser process which components to mount and which assertions to do. And it seems that the derivation the former bundle is what's problematic here, since it has to include the code for all the relevant components, whereas the latter, "native", bundle doesn't actually have to render anything, so it could be fine with fake ids. The section in <https://playwright.dev/docs/test-components#under-the-hood> doesn't really explain how this rewriting/collecting is achieved.

**Comment by mxschmitt** [comment]
@Pauan @WorldSEnder we support top-level-await in ESM mode, make sure that you have `"type": "module"` as required by spec inside your package.json. File bugs if it does not work for your use-case.

**Comment by mxschmitt** [comment]
Closing since its answered, if it does not work for you, please re-file with a repro! Happy to take a look then.
