### ISSUE TITLE
[Feature] allow emulating navigator.doNotTrack

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/playwright#17263]
I have some tests that should expect masked data produced in case do not track is enabled in the browser.
I could monkeypatch navigator to set the doNotTrack value, but was wondering if there is some playwright option that would allow me to do that in a more elegant way?

**Comment by mxschmitt** [comment]
There is no way as of today, I'll convert it to a feature request if its ok?

**Comment by Smrtnyk** [comment]
sure, thank you

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
