### ISSUE TITLE
Chromium install bar breaking in CI

### ISSUE THREAD

**Issue by CKReiff** [microsoft/playwright#17290]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `playwright-core@1.25.2` for the project I'm working on.

It breaks on this line when deploying in CI. With this error msg:
Downloading Chromium 105.0.5195.19 (playwright build v1019)...
/node_modules/playwright-core/lib/server/registry/download.js:165
console.log(`|${'■'.**repeat**(row * stepWidth)}${' '.repeat((totalRows - row) * stepWidth)}| ${percentageString}% of ${toMegabytes(totalBytes)}`);
RangeError: Invalid count value
ERROR: Something went wrong in run-commands - Command failed: npx playwright install chromium

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/playwright-core/lib/server/registry/download.js b/node_modules/playwright-core/lib/server/registry/download.js
index 78d5c53..a10aa32 100644
--- a/node_modules/playwright-core/lib/server/registry/download.js
+++ b/node_modules/playwright-core/lib/server/registry/download.js
@@ -162,7 +162,7 @@ function _getBasicDownloadProgress(progressBarName) {
       lastRow = row;
       const percentageString = String(percentage * 100 | 0).padStart(3); // eslint-disable-next-line no-console
 
-      console.log(`|${'■'.repeat(row * stepWidth)}${' '.repeat((totalRows - row) * stepWidth)}| ${percentageString}% of ${toMegabytes(totalBytes)}`);
+      // console.log(`|${'■'.repeat(row * stepWidth)}${' '.repeat((totalRows - row) * stepWidth)}| ${percentageString}% of ${toMegabytes(totalBytes)}`);
     }
   };
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by mxschmitt** [comment]
Is this reproducible all the time for you? We have this download progress bar since year and you are the first one who run into this bug. Would appreciate if you could debug that further and log maybe the value of `row`, `downloadedBytes`, and `totalBytes` since we'd like to understand what happens.

So somehow the value which gets passed into repeat is negative.

**Comment by CKReiff** [comment]
Unfortunately it's really flaky and hard to reproduce. It seems to happen only when CI is a bit loaded.
Might be some kind of race condition.
I tried reproducing it 10 times today without any luck.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
