### ISSUE TITLE
[Feature] How to specify channel/context options for record in vscode extension

### ISSUE THREAD

**Issue by mvolkert** [microsoft/playwright#17330]
When I try to use features like "Record new" of VS-Code extension I always get the prompt to install browsers. In playwright.config.ts I configured channel='chrome' such that playwright uses the installed browser, and not its own bundled browsers. That works well, when I execute tests, but it does not work with the features of VS-Code plugin. Is there any way to get the VS-Code plugin also working with an installed browser ? (I cannot let playwright install any browsers, as my system blocks that kind of requests.)

**Comment by mxschmitt** [comment]
Which version of Playwright are you using? I remember we fixed an issue which did not take `channel` into consideration when using the Playwright extension. Make sure to use for that 1.25.2 or newer.

What I see what's not possible is `Record new` - then it will choose Chromium, since its not knowing which Playwright Test project it should use. As a workaround for that, you can first run a test, have the `Show browser` turned on, then from that point on you can click on `Record new` and it will use the browser configured in the project - the browser which is already opened - aka. Chrome if you set there `channel: 'chrome'`.

I think we should still keep this as a feature request to make it configurable or fallback to Chrome if no chromium exists.

**Comment by mvolkert** [comment]
Thanks, I had 1.25.0 installed with 1.25.2 it now works fine. Except the inconvience with `Record new` which you had described, nice that this is kept as a feature request to make it configurable. :)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
