### ISSUE TITLE
[REGRESSION]: expect(locator).toContainText() doesn't read string arrays properly anymore

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#17350]
**Context:**
- GOOD Playwright Version: 1.22.2
- BAD Playwright Version: 1.25.2
- Operating System: Manjaro Linux

**Description**
We have a test where we check the imprint address in the website footer. The address consists of three lines and that hasn't changed (I checked).
But we just updated to 1.25.2 yesterday and now this test is failing, because PW somehow misinterprets the 3 lines in the footer as 5 lines.

Another user reported the same issue after upgrading to 1.25.2 on the [PW Slack](https://playwright.slack.com/archives/CSUHZPVLM/p1663193945264399) as well. 
In his case the expected and received number of strings is both 3.

It also is inexplicable for me why this would even fail. It is supposed to assert that 3 strings are contained, which should pass even if there were actually 5 lines (strings) on the page, because the strings are still contained in there.

I see in the [release notes](https://playwright.dev/docs/release-notes#version-123) that `toContainText()` and `toHavetext()` were updated in v1.23, so maybe that's what broke them?

**Code Snippet**

The variables containing the expected strings:
```
this.imprintAddressTextLine1 = "Text in Line 1";
this.imprintAddressTextLine2 = "Text in Line 2";
this.imprintAddressTextLine3 = "Text in Line 3";
```

The assertion:
```
await expect(this.imprintAddress).toContainText([this.imprintAddressTextLine1, this.imprintAddressTextLine2, this.imprintAddressTextLine3]);
```

The fail reported by PW:
```
Error: expect(received).toContainText(expected)

- Expected  - 3
+ Received  + 5

  Array [
-   "Text in Line 1",
-   "Text in Line 2",
-   "Text in Line 3",
+   "
+             Text in Line 1 
+             Text in Line 2 
+             Text in Line 3 
+           ",
  ]
```

**Comment by mxschmitt** [comment]
The previous behavior was actually a bug on our side, the new implementation behaves how it should be. In your case it should be:

```ts
await expect(this.imprintAddress).toContainText(this.imprintAddressTextLine1)
await expect(this.imprintAddress).toContainText(this.imprintAddressTextLine2)
await expect(this.imprintAddress).toContainText(this.imprintAddressTextLine2)
```

why? Because (I assume in your case) that the `this.imprintAddress` is a single DOM node and not a list. Passing multiple strings to toContainText will assert a list of locators to it. But in your case you want to assert a single DOM node to a text, and do that multiple times.

See here for more information including examples: https://playwright.dev/docs/test-assertions#locator-assertions-to-contain-text

For @GunjanSheth you are talking about extracting text, this is different from asserting (via expect) what this issue is about.

**Comment by azad-derakhshani-GS** [comment]
Ah I see, thank you for the explanation Max! I wasn't aware that the previous implementation was a bug. It was quite convenient though. :D 
But that's fine, then I'll adjust our tests in the suggested way.
