### ISSUE TITLE
[Feature] Ability to interact with tool bar

### ISSUE THREAD

**Issue by lancelodliu** [microsoft/playwright#17352]
We are developing features in Edge and add a new button in the toolbar which will render a flyout with a Web UI inside when user clicks the button in the toolbar(like Favourites). But I don't find any interfaces that playwright provide to make this happen.
![image](https://user-images.githubusercontent.com/19603852/190296860-8b4f020b-a3e9-400e-b94b-ff090f2844ee.png)

**Comment by ltsuda** [comment]
Hi, please see if this is similar.

https://github.com/microsoft/playwright/issues/17321#issuecomment-1246455576

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
