### ISSUE TITLE
[Question] Can we perform db testing using playwright?

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#17397]
question 1: I would like to validate if the db results(table values) match to what get displayed on the UI? - end to end testing validating both the backend and validate if db table values match to what User views on the UI.

question 2: Also, I do have a distinct scenario to test. the UI that i test , supports edit and save functionality, however after user validates edit and save, the initial data should need to be restored. is there a way to remember the initial values on the UI, so that after testing edit and save, the initial values can be reset back on the UI? Does playwright support restoring the db values?

**Comment by mxschmitt** [comment]
answer 1: Playwright runs inside Node.js, you can use any NPM / Node.js library to connect to your DB and make assertions, there are no limitations. Pick your favourite, connect and make requests!

answer 2: Playwright knows nothing about your DB, but you can do e.g. DB snapshots and load them inside the globalSetup, something like that should definitely work!

**Comment by InduKrish** [comment]
> answer 2: Playwright knows nothing about your DB, but you can do e.g. DB snapshots and load them inside the globalSetup, something like that should definitely work!

when you say that we can load DB snapshots inside the global setup, how playwright makes use of them to restore the values on the UI? do i have to read the values from global setup and assign db values manually in the web table for each locator?
or can you please help me with an example as how to make use of db snapshots from the globalSetup, to restore the values in the web tables in the UI?

**Comment by mxschmitt** [comment]
> how playwright makes use of them to restore the values on the U

Playwright does make any use of them, it just executes the global setup before running the tests and the global teardown after running the tests.

It totally depends on your application, which you are testing, so I can't help with that, sorry!

There is also global teardown, which runs after all the tests: https://playwright.dev/docs/test-advanced#global-setup-and-teardown

Since we can't act on that, closing for now and I'd refer to the NPM library of the database you are using to load/make snapshots,
