### ISSUE TITLE
[Question] Is there a way to hook into the custom webServer logs?

### ISSUE THREAD

**Issue by mkilpatrick** [microsoft/playwright#17416]
I'm using a custom webServer that I'd like to hook into its console logs. What I'm trying to do is load up a custom ViteDevServer and verify that HMR is working properly, both visually on the page and by checking the hmr test coming back from the server.

**Comment by unlikelyzero** [comment]
@mkilpatrick we're seeing issues with hmr and waitfornetwork idle events FWIW and decided to disable it for playwright tests.

**Comment by mxschmitt** [comment]
If you want to have custom "wait for webserver to start" logic, then we recommend putting this into your global setup. Would that work for you? There you can create a sub process, wait until the stderr or http endpoints return the satisfied results and then resolve the Promise so the tests will run.

**Comment by mkilpatrick** [comment]
Actually, upon further testing, I am able to see hmr changes being reflected and I can capture the change via screenshots. I still can't hook into the webserver logs, but it might not be necessary. Could be a useful feature though. Unsure if it's out of scope for what Playwright's purpose is.

**Comment by mxschmitt** [comment]
> @mkilpatrick we're seeing issues with hmr and waitfornetwork idle events FWIW. We decided to disable it for playwright tests.

Networkidle is generally discouraged, since this is exactly what HMR breaks since it's doing often polling in the background. Playwright's auto-wait functionality should make networkidle unnecessary. 

> I'm looking to make a change to a template file and checking that both the page is updated and that the server logs an HMR event (which is just console.out).

This sounds like you want to start your server inside a [worker fixture](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures), so you have access to the server logs during the test execution. 

Since this is a very custom scenario, I recommend digging into worker fixtures which should work for your use-case. This requires that you manually create your child process and wait for the server to be ready, but then you have the full control about it. Sniffing the webServer logs during the test execution seems out of scope as you said, since this is not a common scenario.
