### ISSUE TITLE
[Feature] .toHaveValue should consider custom combobox elements

### ISSUE THREAD

**Issue by hornta** [microsoft/playwright#17464]
Currently the `.toHaveValue()` assertion only works for native input component but I believe they should work for custom combobox elements as well. What do you think?

Example: https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-list.html

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
