### ISSUE TITLE
[Feature] Frame screenshot

### ISSUE THREAD

**Issue by jswale** [microsoft/playwright#17497]
Would you think it could possible to implement the screenshot feature into the _Frame_ element the same way it's done in the _Page_ with a similar interface to `PageScreenshotOptions`

Examples
```
frame.screenshot({ path: 'path/to/file.png' });
frame.screenshot({ path: 'path/to/file.png', fullPage: true });
```

`page.screenshot` using Iframe (dont blame me) with a scrollable content will not scroll because it's not the page that is scrollable, but the Iframe.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by ankur-lt** [comment]
@pavelfeldman , I am also facing a similar issue. It would be great if we can have screenshots of a frame too similar to how we have it for page.
