### ISSUE TITLE
[Feature] Expose determined mimeType

### ISSUE THREAD

**Issue by JannisBush** [microsoft/playwright#17502]
Sometimes one needs to have access to the browser determined [mimeType](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-Response) of a response.

With CDP this is possible:
```python
client = page.context.new_cdp_session(page)
client.send("Network.enable")
client.on("Network.responseReceived", lambda r: print(r["response"]["mimeType"]))
```
However, this does not work with all non-chromium browsers. 
It would be nice, if this information would directly be exposed by playwright.

**Comment by JannisBush** [comment]
I want to figure out which is the actual mimeType used by a browser when confronted with dubious responses (e.g., several content-type headers, header and body do not agree). Thus, I cannot rely on the headers or other mime-sniffing packages.

For top-level documents, I can run `document.contentType`, however this does not work for embedded resources.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
