### ISSUE TITLE
[Feature] Assertion to test the selected option of a select element is as expected

### ISSUE THREAD

**Issue by AndyGBC** [microsoft/playwright#17510]
Can we have an assertion to check the selected option of a selement is as expected please?

Similar to asserting the value of an input field using .toHaveValue(`foo`) etc.

I would suggest:
```
await expect(page.locator('select[name=mySelect]').toHaveSelectedText('foo');
await expect(page.locator('select[name=mySelect]').toHaveSelectedValue('foo123');
```

Where the html is:
```
<select name='mySelect'>
  <option value='foo123'>foo</option>
  <option value='bar123'>bar</option>
  <option value='baz123'>baz</option>
</select>
```

and I have selected the first option and saved, then returned to the page to check the values saved correctly.

I have seen the following on this but really don't like using eval if an assertion method is available.
https://github.com/microsoft/playwright/issues/7645

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
