### ISSUE TITLE
[BUG] Playwright Inspector Not Recording anything when we Firstly Right Click on Web page when the Tab only accept Right Click

### ISSUE THREAD

**Issue by Rohit18k** [microsoft/playwright#17592]
**Context:**
- Playwright Version: [1.25.0]
- Operating System: [Windows]
- Node.js version: [v16.17.0]
- Browser: [ All]

**Code Snippet**

```java
package Playwright_Automation.WCG_Playwright;
import com.microsoft.playwright.*;
import com.microsoft.playwright.BrowserType.LaunchOptions;
import com.microsoft.playwright.options.*;
import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;
import java.util.*;

public class Alert_ScreenShot_Using_PlayWright {
	
	
  public static void main(String[] args) {
	  Playwright playwrite = Playwright.create();
		
		LaunchOptions lp = new LaunchOptions();
		
		lp.setChannel("chrome");
		lp.setHeadless(false);
		
		Browser browser = playwrite.chromium().launch(lp);
		
		BrowserContext context = browser.newContext();
		

	Page page = context.newPage();
	page.navigate("https://demo.guru99.com/test/simple_context_menu.html");
	
	page.pause();


    }
  }

```
**Describe the bug**

Playwright Inspector Not Recording anything when we Firstly Right Click on Web page when the Tab only accept Right Click.

https://user-images.githubusercontent.com/114156949/191748335-a9becb1c-5ed2-4d5b-a9f1-f27747e27c05.mp4

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
