### ISSUE TITLE
[Feature] Add Playwright.WebView2.launch()

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#17617]
Playwright can connect to WebView2 controls already, see this guide: https://playwright.dev/docs/next/webview2

It requires setting the port number and user data dir manually. Playwright could add `Playwright.WebView2.launch({ executablePath: 'example.exe' })` which would take care of that and automatically adds recommended browser arguments as well.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
