### ISSUE TITLE
[Feature] Allow expect.soft to create a screenshot for each fail

### ISSUE THREAD

**Issue by marko-simic** [microsoft/playwright#17664]
It would be great for us to have created, and to the report attached, a screenshot for each failed soft assertation.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by dandoris33** [comment]
I'm wondering if this would be handy for a screen shot, why not all the info necessary to see what was happening at the time?  Sure could see one assert "Just use the trace viewer and be done with it...."   Might be a fair assertion while it might be nice to have what would be effectively bookmarks to easily go to the point an except.soft() failed...   One other thought might be to have a global setting to allow even hard errors from expect to not end the test?  Completely different issue but my point i think would still be valid?  Back to the idea for the book mark, when opening the trace viewer, say i have 'x' soft errors, would be nice to click on a link and have it take me to that error?    

Sorry for the slow input, only stumbled on this in the PW discord.   No problem opening a new issue...
