### ISSUE TITLE
[BUG] Missing proxy in websocket connection

### ISSUE THREAD

**Issue by wodyjowski** [microsoft/playwright#17792]
**Context:**
- Playwright Version: v1.26.1
- Operating System: Linux
- Node.js version: 16.13.1
- Browser: Chrome
- Extra: Selenium Grid 4

**Describe the bug**

When connecting to Selenium Grid there is possibility to use proxy by specifying HTTP(S)_PROXY environment variable. This only affects HTTP trafic - websocket connection in `transport.ts` doesn't include proxy (in any form, even WS(S)_PROXY).
This makes the proxy feature unusable, as for e.g. in my project we use playwright inside a kubernetes cluster and we have a strict rule that any outgoing traffic has to go through egress proxy (for security and observability purposes).
I'm 99% sure that limiting proxy to HTTP is not something we want.
I've created a [PR](https://github.com/microsoft/playwright/pull/17791) with a "hacky" solution where I check HTTP(S)_PROXY based on ws endpoint.
I'm not sure if this shoud use WS(S)_PROXY variable or if it would be better to introduce separate "PLAYWRIGHT_PROXY" variable (I'm voting for this one).
There is also a possibility that could be a breaking change for someone somewhere - squd proxy for e.g. doesn't allow websocket connections without TLS by default.

Let me know what do you think. I would much prefer to give you a PR with proper solution but I have another code to fix right now 🙂

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
