### ISSUE TITLE
[Feature] Add APIResponse.headerValue()

### ISSUE THREAD

**Issue by Meemaw** [microsoft/playwright#17805]
1. This API exists on the `Response` class, so `APIResponse` could/should have it as well: https://playwright.dev/docs/api/class-response#response-header-value
2. `headerValue` is case insensitive, while `.headers()["value"]` is not and will crash if wrong casing is specified which makes the usage annoying

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
