### ISSUE TITLE
[REGRESSION]: toHaveURL passes in 1.25 but fails in 1.26

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#17809]
**Context:**
- GOOD Playwright Version: 1.25
- BAD Playwright Version: 1.26
- Operating System: Mac
- Extra: [any specific details about your environment]

**Code Snippet**

```javascript
import { test, expect } from "@playwright/test";

test("test", async ({ page }) => {
  test.slow();
  await page.goto("https://nordicjs.com/2022");

  await page.locator('nav[role="navigation"] >> text=Speakers').click();
  await expect(page).toHaveURL("https://nordicjs.com/2022/speakers");

  await expect(page.locator('h3:has-text("Speakers")')).toBeVisible();

  await page.locator("text=Sponsors").click();
  await expect(page).toHaveURL("https://nordicjs.com/2022/#sponsors--270766"); // throws here
});

```

**Describe the bug**

The code above did work in 1.25 but after upgrading to 1.26 it breaks at the toHaveURL assertion. Even when setting the expect timeout quite high, it fails with

Call log:
  - expect.toHaveURL with timeout 15000ms
  - waiting for selector ":root"

and it gets reflected as 97ms inside the html report (step).

It seems firefox only and load event changes related, cc @dgozman

**Comment by mxschmitt** [comment]
Sometimes I also get `TypeError: Cannot read properties of undefined (reading 'childFrames')` there and sometimes its passing for me.

**Comment by kblok** [comment]
I think I'm getting the same issue. But I wasn't able to isolate it yet.
It looks like a `click` that triggers navigation is being resolved earlier than before. I have some legacy code that was doing something like:

```
await page.locator("text=Sponsors").click();
await page.waitForLoadState("networkidle"); // I don't like that `waitForLoadState` either. 
```

That code is working on 1.25, it waits for the navigation and then for the networkidle, but on 1.26, `waitForLoadState` resolves immediately because the navigation didn't occur yet.

**Comment by janosh** [comment]
Having the same problem as @kblok. [This line](https://github.com/janosh/svelte-toc/blob/ace69b882b9fb8ca81ec364ed347d0e774e64721/tests/toc.test.ts#L6) no longer waits for `networkidle` in 1.26.

**Comment by mxschmitt** [comment]
I can repro on 1.27 which is already in the bug tracker for https://github.com/microsoft/playwright/issues/9840:

```
TypeError: Cannot read properties of undefined (reading 'childFrames')
    at FrameManager.removeChildFramesRecursively (/Users/max/development/tmp/pwtest1/node_modules/playwright-core/lib/server/frames.js:395:31)
    at FrameManager.frameCommittedNewDocumentNavigation (/Users/max/development/tmp/pwtest1/node_modules/playwright-core/lib/server/frames.js:194:10)
    at FFPage._onNavigationCommitted (/Users/max/development/tmp/pwtest1/node_modules/playwright-core/lib/server/firefox/ffPage.js:212:30)
    at FFSession.emit (node:events:520:28)
    at /Users/max/development/tmp/pwtest1/node_modules/playwright-core/lib/server/firefox/ffConnection.js:248:41
```

```
pw:protocol [0m◀ RECV {"method":"Page.navigationCommitted","params":{"frameId":"frame-4294967306","navigationId":"131110319161580","url":"https://js.stripe.com/v3/m-outer-3437aaddcdf6922d623e172c2d6f9278.html#url=https%3A%2F%2Fnordicjs.com%2F2022%2F%23sponsors--270766&title=Nordic.js%20-%206-7%20October%202022%20-%20Stockholm&referrer=https%3A%2F%2Fnordicjs.com%2F2022%2Fspeakers&muid=NA&sid=NA&version=6&preview=false","name":"__privateStripeMetricsController7890"},"sessionId":"a738c776-3059-4ca8-a1cf-a40e7ba3a0f5"}
```

tries to access to access the frame here:

https://github.com/microsoft/playwright/blob/bac6df30e0b941c2090b938b7ca1028ff4898450/packages/playwright-core/src/server/frames.ts#L211

but it's null, since before another `Page.navigationCommitted` to about:blank happened which cleared the sub-frames.

so:

```
Page.frameAttached frame 1
Page.frameAttached frame 2 (child frame of 1)
Page.navigationCommitted frame 1
 -> it removes all child frames of 1 -> 2 gets cleared and detached
Page.navigationCommitted frame 2
-> tries to use frame 2, but it's already disposed
```

Note: this describes `Cannot read properties of undefined (reading 'childFrames')` but not the main issue of this issue.

**Comment by mxschmitt** [comment]
I can verify that this issue is fixed on `npm i -D @playwright/test@next` or wait for 1.28.

Please try to repro on `@next` or wait for 1.28.
