### ISSUE TITLE
No websocket requests saved in HAR 

### ISSUE THREAD

**Issue by mohitt** [microsoft/playwright#17848]
**Context:**
- Playwright Version: 1.25.2
- Operating System: linux
- Node.js version: using python (pytest-playwright)
- Browser: chrome
- Extra: [any specific details about your environment]

## System:
 - OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - Memory: 51.81 GB / 62.53 GB
 - Container: Yes
## Binaries:
 - Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
 - Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
 - npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```python
        str_start_time = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        har_path = f"{request_hars}/{str_start_time}_{request.node.originalname}.har"
        page = await browser.new_page(
            no_viewport=True,
            record_video_dir=f"./{videos}",
            record_video_size={"width": 1920, "height": 1080},
            record_har_path=har_path,
            record_har_mode="full",
        )

```

**Describe the bug**

I turned on har recording with `record_har_path` and `record_har_mode` = full . I still cant see any wesocket request's inside my har. Where as if I save the har using chrome dev tools I see websocket requests in har

**Comment by yury-s** [comment]
Yes, websocket requests are not saved to har. As a workaround you can inspect them using ['websocket'](https://playwright.dev/docs/next/api/class-page#page-event-web-socket) event and corresponding methods on [WebSocket](https://playwright.dev/docs/api/class-websocket)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
