### ISSUE TITLE
[Feature] Manually update execution lines in the VSCode plugin

### ISSUE THREAD

**Issue by ChillyBots** [microsoft/playwright#17934]
We've structured our tests into snippets, as we have lots of user actions we need to chain together into different orders for our test:
```
 await utils.login()
 await utils.user.create()
 await utils.user.delete()
 await utils.logout()
 expect(someCondition)
```
That sort of thing. We mix our expect logic into these snippets as well as at the top level which helps make things more resilient. However, the Playwright VSCode plugin only adds execution line highlighting & time reporting etc to first-class Playwright APIs. So in the example above, only the last 'expect' would be highlighted. 

Execution line functionality also works inside the snippets; however, I would like the ability to manually report back to VSCode which snippet is running. For example:
```
const doAwesomeThing = async () => {
    PlaywrightLogger.start()
    ...Silky smooth testing goes here
    PlaywrightLogger.stop()
}
```

**Awesome** tool btw. Thank you very much

**Comment by pavelfeldman** [comment]
We can mark these lines as executed without the explicit markup, but reporting time would require structural instrumentation like the one you are suggesting. I'm marking it as P3 to suggest that it won't be high in our priority list, but others can still comment and upvote it.

**Comment by ChillyBots** [comment]
@pavelfeldman - I can imagine everyone will see this as pretty low on the priority list, and probably rightly so ;-)

Can you let me know how to mark a line as executed, or have I misunderstood?

Thanks for getting back to me

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
