### ISSUE TITLE
[Feature] Add dynamic interceptors to apiRequestContext

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#17946]
This is useful to replace axios wtih Playwright api request context, so you can dynamically change the (node context) response or request.

**Comment by pavelfeldman** [comment]
:wave: Tally! Could you paste and end-to-end usage scenario?

**Comment by Tallyb** [comment]
I use it for creating data fixtures. 
I currently use 2 interceptors: 
1) add a request ID to requests (so I can find them in the logs)
2) Strip the data from the response body, and add the request-id in case of an error. 

```
  server.interceptors.response.use((res)  => res.data, // return only the data from the response
    async (err) => { // add a request id to the error
      err.message += `\nx-request-id: ${err.request.getHeaders()['x-request-id']}`;
      throw new Error(err);
  });
```
Axios has this capability, and I wanted to replace Axios with PW API context. Sadly, due to the above, I have to stick with Axios.

**Comment by pavelfeldman** [comment]
So this would be instead of wrapping the request methods and patching all of the their responses. If you only use get and post, those wrappers would not look that bad btw!

**Comment by Tallyb** [comment]
I agree, but I prefer looking good, rather than not look bad...

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by Tallyb** [comment]
@Skn0tt - api improvement. I can understand why i t was  dismissed 2 1/2 years ago. Maybe now it is  the time...
