### ISSUE TITLE
[Feature] Maybe `Locator` API should have an optional way to find the element when `page.locator()` called?

### ISSUE THREAD

**Issue by imaxwen** [microsoft/playwright#17962]
Let us know what functionality you'd like to see in Playwright and what your use case is.

Since `Locator` has such powerful and convenient APIs, I use `page.locator` to find my dom elements much more than `page.query_selector`.  But recently in my project,  we created `Page Model` classes to describe our webpages and found this makes our project super easy to maintain,  And Here comes the problem, we have to check if an element exists frequently so that we could decide what's next:

```python
from playwright.sync_api import TimeoutError as PwTimeoutError

# login page model
class LoginPage(BasePage):
    url = 'https://example.com/login'

    def navigate(self):
        self.page.goto(self.url, wait_until=self.EVENT_DOMContentLoaded)

    def username_input(self):
        return self.page.locator('input#username')

    def password_input(self):
        return self.page.locator('input#password')

    def post_login_btn(self):
        return self.page.locator('btn#submit-login')

    def error_alert(self):
        try:
            return self.page.locator('div#login-error')
        except PwTimeoutError:  # fake code, this will never happens currently
            return None
```

```python

# in test cases:

login_page = LoginPage()
login_page.navigate()
login_page.username_input.fill('my-username')
login_page.password_input.fill('my-password')
login_page.post_login_btn.click()

# fake code, just demo for what we want
if error_alert := login_page.error_alert():
    print("Login Failed with: {}".format(error_alert.inner_text()))
else:
    # ...
    pass

```

In fact, `Locator` captures the logic of how to retrieve an element, not the element directly, In this case we may use `page.query_selector/wait_for_selector`, But we won't have powerful `Locator` API any more :(

So is there any suggestions to solve this case by `Locator` API, or maybe it should have an optional way to find the element when `page.locator()` called, or adding a new API like `page.locator_exists(timeout=30000ms)`?

Do you think others might benefit from this as well?
Of course Yes !!😆

**Comment by mxschmitt** [comment]
Generally speaking you should never use query_selector, see here: https://playwright.dev/docs/locators#locator-vs-elementhandle

The locator class has already a bunch of methods which might help for your use-case:

locator.count() - returns the amount of elements on the page with the specific selector
[locator.wait_for()](https://playwright.dev/python/docs/api/class-locator#locator-wait-for) - waits until the page is visible or hidden (you can specify it as an arg)

In general we recommend using [expect()](https://playwright.dev/docs/test-assertions) instead, since it will automatically retry until the condition is met.
expect(locator).is_visible()
expect(locator).is_hidden()

Also all the Playwright actions, e.g. click, fill will wait until the element is on the dom, visible etc. see here: https://playwright.dev/docs/actionability

Let us know if this would work for you!

**Comment by imaxwen** [comment]
> Generally speaking you should never use query_selector, see here: https://playwright.dev/docs/locators#locator-vs-elementhandle
> 
> The locator class has already a bunch of methods which might help for your use-case:
> 
> locator.count() - returns the amount of elements on the page with the specific selector [locator.wait_for()](https://playwright.dev/python/docs/api/class-locator#locator-wait-for) - waits until the page is visible or hidden (you can specify it as an arg)
> 
> In general we recommend using [expect()](https://playwright.dev/docs/test-assertions) instead, since it will automatically retry until the condition is met. expect(locator).is_visible() expect(locator).is_hidden()
> 
> Also all the Playwright actions, e.g. click, fill will wait until the element is on the dom, visible etc. see here: https://playwright.dev/docs/actionability
> 
> Let us know if this would work for you!

thanks in advice, this solved my case perfectly.
