### ISSUE TITLE
Should isVisible fail if a React Error Boundary is active and the element is not in the DOM? 

### ISSUE THREAD

**Issue by danmolitor** [microsoft/playwright#17973]
Hi there,

Quick question.

I had this basic assertion here:

`await page.locator("data-testid=some-test-id]").isVisible()`

and I was curious how this would work with a React Error Boundary. 

I threw an error in my JSX so that the Error Boundary would activate. 

If I run the test in debug mode, I see that the error boundary is active. 

However, the test still passes. 

Is this the correct behavior? 

I can get a failed test by doing something like:

`await expect(await page.locator("[data-testid=some-test-id]").count()).toEqual(1);`

I just wanted to throw this out there though. It seems like since the error boundary is up, and the element is not in the DOM, it should not be "visible", and therefore isVisible should fail. 

Furthermore, if `isVisible` returns true, shouldn't page.locator("[data-testid=some-test-id]").count()` at _least_ equal one?

Thanks!

**Comment by pavelfeldman** [comment]
Both these calls are discouraged because they probe dom in a non-deterministic manner (at some random point in time), so they'll sometimes return 0, sometimes would return 1. You can't really test their consistency because the checks are made at different points in time. The correct calls would be:

```js
await expect(locator).toBeVisible();
```

and 

```js
await expect(locator).toHaveCount(1);
```

These are going to wait for the element to become visible. As for the error boundary, Playwright does not know anything about it, it only operates against the actual DOM.
