### ISSUE TITLE
export to pdf adding an extra blank page

### ISSUE THREAD

**Issue by srikantyasam** [microsoft/playwright#17987]
### Discussed in https://github.com/microsoft/playwright/discussions/17986

<div type='discussions-op-text'>

<sup>Originally posted by **srikantyasam** October 11, 2022</sup>
Hi All,
<p>

I am exporting the page content to pdf using playwright. 
My requirement is to export the content in the letter format, so I have added few additional lines for this purpose.
<p>
eg:   opts.setFormat("LETTER");
        opts.setScale((8.5*96)/(page.viewportSize().width));
        page.pdf(opts);
<p>
While it is working fine for the formats like A4,A5 etc.., Its always adding an extra blank page to the pdf though all the content is fitting properly in the first page.
<p>
Please let me know if someone faced similar issue in playwright? appreciate any help in this regard.</div>

**Comment by srikantyasam** [comment]
Hi Playwright Team , @pavelfeldman,

 Can I expect any response/solution/workaround on this issue please??

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
