### ISSUE TITLE
[Question] What's the deal with `folio`?

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/playwright#18019]
What's the status of the [`folio`](https://github.com/microsoft/folio) repository?

- It looks like commits ceased in July '21, and the `folio` package was [last published](https://www.npmjs.com/package/folio) around the same time.

- Issues and discussions are both turned off, and the [final commit](https://github.com/microsoft/folio/commit/fac29d08324599943db53e33e136d2cfecdb8a56) was a link to Playwright Test.

- The repository has not been archived.

- The `README` still says it is "under active development", and "We welcome your feedback".

- While searching for an explanation, I found [this issue](https://github.com/microsoft/playwright/issues/6857), which says "Bring Folio source to the monorepo".

Did the package name change? Did the library migrate into `@playwright/test`?

And how does this change or affect the role of the framework? The `folio` repository had the following description:

> A customizable test framework to build your own test frameworks

I loved that idea.

Did you abandon that idea and instead integrate the test-library into Playwright?

If so, why?

(And if so, you probably should flag both the repository and npm package as abandoned?)

**Comment by pavelfeldman** [comment]
I archived the folio repo. Our focus has always been on Playwright, but we were lacking a powerful-enough e2e test runner. We created folio first, but we did not have the large non-Playwright customers at the time and rolling the dependencies was too much effort.

You can use @playwright/test instead of folio for you general-purpose testing - it does not pull the browsers unless you ask it to, so it should be fairly lightweight. Just stay away from the page, context, etc fixtures and create your own fixtures.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
