### ISSUE TITLE
[Feature] Selenium Grid - Support Authentication / Custom Headers

### ISSUE THREAD

**Issue by dylanlive** [microsoft/playwright#18035]
When connecting to Selenium Grid using Playwright, there is no ability to pass custom headers to the selenium server. An example would be the [Authorization header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization), which must be supplied when a Selenium Grid [requires authentication](https://github.com/SeleniumHQ/selenium/blob/702b3aae7385adf331d75cdeacd79720cf6b9c84/java/src/org/openqa/selenium/grid/router/httpd/RouterFlags.java#L52-L57).

Perhaps there could be a line in the config that allows to define a map of headers to pass along to every Selenium Grid Request. Maybe [testOptions.extraHTTPHeaders](https://playwright.dev/docs/api/class-testoptions#test-options-extra-http-headers), though that seems designed for setting headers in the browser itself and not the server.

Example of the code where the Selenium Grid connection is made:
https://github.com/microsoft/playwright/blob/639b28db3bc6ac4c3fa2d2ad8960b361b1021808/packages/playwright-core/src/server/chromium/chromium.ts#L191-L199

[fetchData()](https://github.com/microsoft/playwright/blob/639b28db3bc6ac4c3fa2d2ad8960b361b1021808/packages/playwright-core/src/common/netUtils.ts#L95) does support [headers](https://github.com/microsoft/playwright/blob/639b28db3bc6ac4c3fa2d2ad8960b361b1021808/packages/playwright-core/src/common/netUtils.ts#L37), but none are passed with the Selenium Grid connection

Note: These headers should be supplied on every http request to Selenium Grid (Session creation and deletion). It doesn't appear yet that CDP requires the authentication header.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
