### ISSUE TITLE
[BUG] Cannot test components defined in test file

### ISSUE THREAD

**Issue by theisgroenbech** [microsoft/playwright#18057]
**Context:**
- Playwright Version: 1.27.0
- Operating System: Mac and Linux
- Node.js version: 16
- Browser: All

**Code Snippet**

```javascript
import React from 'react'
import { test } from '@playwright/experimental-ct-react'

function ComponentDefinedInFile() {
  return <button />
}
test.only('mounts component defined in file', async ({ mount }) => {
  await mount(<ComponentDefinedInFile />)
})
```

**Describe the bug**
I would have expected this test to pass. However, it fails with:
```
undefined: Error: Unregistered component: ComponentDefinedInFile. Following components are registered:
```
I am unsure whether this is intended behaviour or a bug. It would however be really nice to be able to create test-helper components in the test files.

**Comment by sand4rt** [comment]
Related to: https://github.com/microsoft/playwright/issues/14345

**Comment by pavelfeldman** [comment]
This is a current limitation of cross-process component testing. Read more at https://playwright.dev/docs/next/test-components#under-the-hood. We might consider alternative approaches, but for now that's what it is.

**Comment by pastelsky** [comment]
@pavelfeldman do you mean expanding on why this limitation exists, and how can one go about contributing to remove this? This limits the usefulness for component testing for a lot of projects.

**Comment by pavelfeldman** [comment]
It is pretty fundamental, we keep testing environment isolated from the browser environment. That's the only way we can deliver reliable and parallelized testing. It comes at a cost though, we can pass live objects (sync functions) between the tests and browser contexts. This link I provided above is explaining it in greater detail.

**Comment by pastelsky** [comment]
@pavelfeldman I understand the reasoning behind it, but I think it effectively fails with a lot of simple cases, which makes the whole approach feel "magical" when it does work.

For example, simple cases like this will blow up with errors that make little sense.

1. Any variable assignment for an mounted component blows up —

```ts
import Component from './component-file'
const ComponentAlias = Component // <---- Doesn't like this

test('something', () => {
    const component = await mount(<Component />); // <-- Even though I'm using Component not ComponentAlias
    await expect(component).toHaveScreenshot();
})
```

Fails on line 2 with —

```
ReferenceError: Component is not defined
```

2. Any aliasing blows up —

```ts
import Component from './component-file'
const ComponentAlias = Component

test('something', () => {
    const component = await mount(<ComponentAlias />);
    await expect(component).toHaveScreenshot();
})
```

blows up with —

```
/component-file.js
  return <_react.default.Fragment>
         ^

SyntaxError: Unexpected token '<'
```

3. Local component definitions blow up —

```ts
const Component = () => <h1>Hello world</h1>;

test('something', async ({ mount }) => {
  const component = await mount(<Component />);
  await expect(component).toHaveScreenshot();
});
```

```
Error: Unregistered component: Example2. Following components are registered: 
```

These are just few simple examples, but I'm sure there are more. In essence this requires me to understand the internals of playwright to be able to write tests (since it doesn't really follow JS semantics).

In my opinion, rather than figuring out the automatically trying to guess the component and blowing up in a lot of cases, it would be better if playwright is explicit and provides a `registerComponent` function so that there is no ambiguity.

**Comment by pavelfeldman** [comment]
Thank you for a thoughtful comment. We were looking for the right balance between the magic and ergonomics and we landed where we are. We did try registerComponent, but it was too manual and did not relay the typing information for the components. Your comments are very valid thought, and we'll keep looking for a better mode!
