### ISSUE TITLE
[Feature] Provide source URL as part of pageerror event data

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#1806]
Hey team. I have a use case where a third-party script sometimes throws errors that I want to ignore, but I want to know if my first-party scripts throw an error. Would it be possible to provide the source URL of the error along with the message? That would make it simple to match against each error URL and decide whether or not to ignore it.

Thanks!

**Comment by dgozman** [comment]
Sounds reasonable. If we provide the [Error.stack](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack) property from the page context, will that work for you?

**Comment by celeryclub** [comment]
@dgozman I think so. I'm not sure I 100% understand the MDN docs here. Looks like `stack` does provide the `sourceURL`, but I don't see that in the examples. Is `sourceURL` easy to access?

**Comment by dgozman** [comment]
`sourceURL` should be used instead of a real script url (if any) in the `error.stack`. This is currently the case for Chromium and Firefox, but not WebKit. I have added a test for this, so we'll fix it in WebKit eventually.

Now you should get the proper error message and stack in `pageerror` event, exactly as they are reported in the browser.
