### ISSUE TITLE
[Feature] Emulating multiple present pointer input devices.

### ISSUE THREAD

**Issue by klarstrup** [microsoft/playwright#18061]
I really need a way to test devices that have both `coarse` and `fine` pointers(i.e. `matchMedia("((any-pointer: coarse) and (any-pointer: fine))").matches === true`), and I couldn't find any way to do this after poring over the docs and the code.

`TestOptions` only has `hasTouch` with no accompanying `hasCursor` and `emulateMedia` does not provide a way to force a `pointer`/`any-pointer` behavior.

If this is already supported, please let me know and if not let's figure out how to get there 😁

**Comment by yury-s** [comment]
This is not supported yet. For the list of media features that can be emulated see [this doc](https://playwright.dev/docs/api/class-page#page-emulate-media).

**Comment by klarstrup** [comment]
Let's make it happen then 🤙

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
