### ISSUE TITLE
[Feature] Web app to load and view html reports

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#18205]
Given that reports can contain multiple traces it would be useful to have a website where you can drop whole reports folder (or zipped folder) to load and view it (it would load traces too). Similarly like https://trace.playwright.dev but for whole html reports.

Would you consider making it happen? Or perhaps you could give some pointers on how to implement it? Perhaps there is https://trace.playwright.dev public repository?

My use case: I download reports from CI and it is a bit inconvenient to run `npx playwright show-trace <path-to-report` each time.

**Comment by pavelfeldman** [comment]
> npx playwright show-trace

I assume you meant npx playwright show-report

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
