### ISSUE TITLE
[Question] What's the correct usage of setTestIdAttribute?

### ISSUE THREAD

**Issue by viraxslot** [microsoft/playwright#18203]
Hi, team.
I have a custom test id attribute and I don't understand the right place to set it (where to call `selectors.setTestIdAttribute`). I tried to do it in `global-setup` script, but alas. I don't really want to wrap `getByTestId` function and set the test id before it, but that's the only way I see right now.

It would be nice:
- add configuration parameter for custom test id;
- update the docs and provide more examples.

Related articles:
https://playwright.dev/docs/api/class-locator#locator-get-by-test-id
https://playwright.dev/docs/api/class-selectors#selectors-set-test-id-attribute

Thanks in advance!

**Comment by pavelfeldman** [comment]
```js
        use: {
          testIdAttribute: 'data-pw',
        }
```

I'll update the docs...

**Comment by viraxslot** [comment]
@pavelfeldman Could you please check this logic working with fixtures? Looks like it doesn't work.

I've added 2 simple tests
```javascript
  test.only("test", async ({ page }) => {
    console.log(page.getByTestId(LOGIN_LOCATORS.username));
  });

  test.only("test 2", async ({ loginPage }) => {
    console.log(loginPage.page.getByTestId(LOGIN_LOCATORS.username));
  });
```

The result is:
```
Running 2 tests using 1 worker
[chromium] › login.spec.ts:96:8 › Login suite › test
Locator@internal:attr=[data-autotest-id="lgn-username"]
[chromium] › login.spec.ts:100:8 › Login suite › test 2
Locator@internal:attr=[undefined="lgn-username"]
```

I've set testId to `config.use.testIdAttribute`

Fixture described in a simple way:
```javascript
const test = base.extend<CustomFixtures>({
  basePage: async ({ page }, use) => {
    await use(new BasePage(page));
  },
  loginPage: async ({ page }, use) => {
    await use(new LoginPage(page));
  },
});
```

Please let me know if it's needed to create a separate bug.

**Comment by pavelfeldman** [comment]
I just ran this:

```js
const myTest = test.extend({
  loginPage: async ({ page }, use) => {
    await use({ page });
  },
});

myTest.only("test", async ({ page }) => {
  console.log(page.getByTestId('a'));
});

myTest.only("test 2", async ({ loginPage }) => {
  console.log(loginPage.page.getByTestId('b'));
});
```

and it worked for me. Could you share a self-contained repro?

**Comment by pavelfeldman** [comment]
> I've set testId to config.use.testIdAttribute

What did you mean by that btw? You aren't supposed to set anything to `config.use.testIdAttribute`, just define `testIdAttribute` in your config.

**Comment by viraxslot** [comment]
I mean the playwright config path, so it wasn't in a project.use, but in general "use" section. I'll try to create a repo.

**Comment by viraxslot** [comment]
@pavelfeldman you're right, it works if set up from the scratch. I'll try to investigate a bit later, this task can be closed I guess.

**Comment by sagrawal-code** [comment]
I think docs should be updated on following page too.

- https://playwright.dev/docs/locators#define-explicit-contract-and-use-data-test-id (This statement is false? Playwright has dedicated support for id, data-test-id, data-test and data-testid attributes.)

**Comment by martynaol** [comment]
@pavelfeldman I am encountering an issue with the `testIdAttribute` configuration in Playwright when extending the base test for authenticated testing.

Here is the scenario:

1. I have set the testIdAttribute in playwright.config.ts. In standard tests, it works as expected.
2. However, when I extend the base test to create an authenticated test (where I set up login steps using a pre-defined function that works in other tests), Playwright fails to recognize certain elements defined using the getByTestId selector.

To illustrate, I have a LoginPage class with the following locators:
`this.emailInput = this.page.locator('[data-qa="login-email"]');
this.passwordInput = this.page.getByTestId('login-password');
`

In my fixture:
`export const authTest = base.extend<Fixture, { workerStorageState: string }>({
  storageState: ({ workerStorageState }, use) => {
    use(workerStorageState);
  },
  workerStorageState: [
    async ({ browser }, use) => {
      // Authenticate user
      const page = await browser.newPage({ storageState: undefined });
      const loginPage: LoginPage = new LoginPage(page);

      await loginPage.goto();
      await loginPage.fillEmailInput(user.email); // Works
      await loginPage.fillPasswordInput(user.password); // Element not found
    },
    { scope: 'worker' },
  ],

  loginPage: async ({ page }, use) => {
    await use(new LoginPage(page));
  },
});
`
While the emailInput locator works without issues, the passwordInput (defined using getByTestId) is not found during execution.

Additionally, I tried logging testIdAttribute and I got `undefined`, and I observed the following error:
`Property 'testIdAttribute' does not exist on type 'PlaywrightTestConfig<{}, {}>'.`

Could you confirm if this behavior is intentional or if I might be misconfiguring something? Any guidance on resolving this issue would be greatly appreciated.

**Comment by alexander-vershinin** [comment]
@martynaol Hi, I'd suggest to create a new issue, because this one is closed. You can tag this issue in the new one if needed.
