### ISSUE TITLE
[Feature] Allow to skip tests by their name and file path

### ISSUE THREAD

**Issue by Luc45** [microsoft/playwright#18222]
- I need to skip the test `foo.spec.js: › Some Describe › Assert something happens`
- I only know whether I need to skip it or not at runtime, when I execute `.bin/playwright`, therefore I don't have skip annotations on that file.
- To do that, I append `--grep-invert "Assert something happens"`.
- Playwright enforces that test titles are unique inside `foo.spec.js`, but not on `bar.spec.js`.
- Assuming I have a test in `bar.spec.js: › Some Other Describe › Assert something happens` with the same name, it will also skip this test, which is unwanted in this scenario.

What I wanted: A way to skip a test by name and file.

```
./bin/playwright
    --skip "foo.spec.js|Assert something happens" \
    --skip "bar.spec.js|Some other test"
```

Expected result: 
- Will skip test with name "Assert something happens" only in `foo.spec.js`.
- Will skip test with name "Some other test" only in `bar.spec.js`.

Question: Is there a reserved character that we can use as a separator instead of a pipe? So that we can reliably explode that string into two pieces.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
