### ISSUE TITLE
[Feature] How to send multipart request with duplicated keys

### ISSUE THREAD

**Issue by dtyunegov** [microsoft/playwright#18247]
For send array "data[product]" I write 
"data[product][]:18
data[product][]:55"

In postman it looks like this:
![image](https://user-images.githubusercontent.com/83776173/197211761-40c4d320-8463-4217-8158-f9628dfd8275.png)

How to make similar array to playwright?
![image](https://user-images.githubusercontent.com/83776173/197219628-c3ae290a-6f26-410a-881e-e623951bf8eb.png)

The following method is not working properly:
"data[product_ids][]": [18, 55]

**Comment by dgozman** [comment]
@dtyunegov Do I understand you correctly that you want to send two values for the same key in `multipart`? If so, this is currently not supported, but I can leave it as a feature request for prioritization.

**Comment by dtyunegov** [comment]
@dgozman Yes, this is it. Too bad it's not supported. It would be nice if they add it in the future.
Thanks for the answer

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
