### ISSUE TITLE
[BUG] After globalTimeout, incomplete tests are not indicated

### ISSUE THREAD

**Issue by pbiggar** [microsoft/playwright#18250]
**Context:**
- Playwright Version: 1.26.1
- Operating System: Linux
- Node.js version: 14.20.1
- Browser: Chromium

Playwright config [publicly available](https://github.com/darklang/dark/tree/01b55134b2404142ed9675e1435f6e3819bf4647/integration-tests)

**Code Snippet**

```jsonc
// Config file for integration tests
import { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
  testDir: ".",
  testMatch: "tests.ts",
  expect: {
    timeout: 5000,
  },
  // If nothing is printed for 10m, then CircleCI times us out, which means we don't
  // find out which test hung. So timeout here first so that it tells us what hung.
  globalTimeout: 600000,
  // in ms. 30000 = 30s
  timeout: 30000,
  use: {
    actionTimeout: 5000,
    headless: true,
    trace: "retain-on-failure",
    screenshot: "off",
    video: "on",
  },
  reporter: [
    ["list"],
    ["json", { outputFile: "rundir/test_results/integration_tests.json" }],
    ["junit", { outputFile: "rundir/test_results/integration_tests.xml" }],
  ],
};

export default config;
```

**Describe the bug**

When the globalTimeout is hit, incomplete tests are not indicated, when using the list reporter.

For example:

https://app.circleci.com/pipelines/github/darklang/dark/4283/workflows/59ac7d0e-36d7-44a9-8ebf-e947dd9ee268/jobs/44444/parallel-runs/0/steps/0-109

In this CI run, the globalTimeout kicks in after 10 minutes. It indicates that a test was skipped (which I presume is the test that was running), but does not say which test it was.

**Comment by dgozman** [comment]
@pbiggar That's right, terminal reporters do not print the list of skipped tests, because that could be too many. I think this is more of a feature request, I'll leave it open for prioritization.

**Comment by pbiggar** [comment]
Yeah, I would classify this as a failed test rather than a skipped one. I don't really see why it would be considered skipped

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
