### ISSUE TITLE
[Feature] Spawn browser process with different user and/or group

### ISSUE THREAD

**Issue by xrip** [microsoft/playwright#18287]
Sometimes it might be usefull to launch browser process with different User/Group, e.g. we need application proccess to be launched as root for some reason and want to browser process will be launched as restricted user.

Proposall to add ``uid`` and ``gid`` options to ```browserType.launch```
NodeJS spawn support that on all system by it's own without any problems: https://nodejs.org/api/child_process.html#child_processspawncommand-args-options

The solution is to pass down ``uid`` and ``gid`` options from ```browserType.launch``` to inner spawn process function:
https://github.com/microsoft/playwright/blob/5b1e4e08a5f3d9999c94874be9401caeace2bd67/packages/playwright-core/src/utils/processLauncher.ts#L65-L78

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
