### ISSUE TITLE
[Feature] Reporters should print full error object information

### ISSUE THREAD

**Issue by PSanetra** [microsoft/playwright#18292]
When an error is thrown in a playwright test, the error object is only partially reported although other object properties might be necessary to debug the error.

Example:
We are using sequelize in our tests to setup some state in a database.

When sequelize throws an error, some additional information like the original SQL query and a cause is included in the Error type. See https://github.com/sequelize/sequelize/blob/ff43e8d32d8069f4071df2ca57931c74f6556a2e/src/errors/database-error.ts#L22-L47

When playwright catches an error like this, _only_ the stacktrace information is printed by the reporter without any kind of error message.

Example report from a sequelize error:

```
  2) ../../mytest.test.ts:329:12 › [...]

    Error: 

        at Query.run ([...]/node_modules/sequelize/src/dialects/postgres/query.js:76:25)
        at [...]/node_modules/sequelize/src/sequelize.js:641:28
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at PostgresQueryInterface.select ([...]/node_modules/sequelize/src/dialects/abstract/query-interface.js:1001:12)
        at Function.findAll ([...]/node_modules/sequelize/src/model.js:1816:21)
        at Function.findOne ([...]/node_modules/sequelize/src/model.js:1982:12)
        [...]
```

This error report is useless. It would be better to print out all information that is included in the error object.

**Comment by mxschmitt** [comment]
Since we are not familiar with Sequelize we would appreciate if you could provide us a small repro/snippet which we can run locally. Happy to dig into it and improve the development experience by that!

**Comment by PSanetra** [comment]
@mxschmitt I have put an example project to reproduce this issue into this repository: https://github.com/PSanetra/reproduce-playwright-reporter-issue

Note: This is just an example using sequelize. The same issue might occur with any other custom error type.

**Comment by mxschmitt** [comment]
Thanks! Minimal repro is the following:

```ts
test('should use error.message as a fallback when no message is in the stack', async ({ runInlineTest }) => {
  const result = await runInlineTest({
    'a.spec.ts': `
      const { test } = pwt;
      test('foobar', async ({}) => {
        const error = new Error('my-message');
        error.stack = new Error('').stack;
        error.name = 'FooBarError';
        throw error;
      });
    `
  }, {}, {
    FORCE_COLOR: '0',
  });
  expect(result.exitCode).toBe(1);
  expect(result.failed).toBe(1);
  expect(result.output).toContain('FooBarError: my-message');
});
```

Sounds like something we can workaround but also something sequelize could do better!

**Comment by PSanetra** [comment]
@mxschmitt I think your proposal in that reproduction would already help to resolve the sequelize error in a better way, but it would also be nice to print out the other custom fields, like `sql` and `parent`, too, if that is possible. Those fields might contain some useful information for debugging.

**Comment by rendmath** [comment]
This is also an issue when debugging errors throwm by other libraries, likes Axios for example. The message of an AxiosError only contains the failure status code. Currently there does not seem to be a way to access the initial error from a reporter, like the validation error that might be present in the response body.

In order to provide a good debugging experience for the developer, the best solution we found so far is to wrap any potentially offending code in try-catch-rethrow and log from the test execution context instead of the reporter.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
