### ISSUE TITLE
[BUG] window.navigator.webdriver is false in Firefox

### ISSUE THREAD

**Issue by chenba** [microsoft/playwright#18307]
**Context:**
- Playwright Version: 1.27.1
- Operating System: macOS 12.6
- Node.js version: 16.15.0
- Browser: Firefox

**Describe the bug**

`window.navigator.webdriver` is false in Firefox.  (It is true in chromium.)

**Comment by hitsthings** [comment]
Just a datapoint since I don't have insight to why this was fixed but not merged:

We tried using `navigator.webdriver` to set our shadow DOM to `open` instead of `closed` so that it would work with Playwright. Obviously that's not working due to this bug, so we'll ahve to find a workaround or override navigator.webdriver ourselves.

Would love to see that fix merged! Cheers!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by hitsthings** [comment]
So...more noisy +1 comments is what you're looking for?

This was actually already fixed in the past as you can see in the issue history. Would be great to at least understand why that was reverted.

 It's a one line Boolean that would make Firefox the same as every other browser for targeting playwright.
