### ISSUE TITLE
[Question]Similar to how we grant permission to camera and microphone is there a way to select an option in Choose what to share dialog in case of Screen Recording

### ISSUE THREAD

**Issue by RoopaaaS** [microsoft/playwright#18370]
I am trying to write a playwright test for our screen recording feature. So wanted to know if similar to how we grant permission to camera and microphone is there a way to select an option in Choose what to share dialog in case of Screen Recording.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
