### ISSUE TITLE
[Feature] JUnit reporter: optionally embed links instead of encoded files for attachments.

### ISSUE THREAD

**Issue by raulparada** [microsoft/playwright#18379]
A bit of background on https://github.com/microsoft/playwright/issues/9348#issuecomment-1293387867

The JUnit report generated with embedded attachments (option `embedAttachmentsAsProperty: "testrun_evidence"`, described on https://playwright.dev/docs/test-reporters#junit-reporter, thought mostly for Xray integration) easily creeps in the hundreds of MBs for regular runs with a few failures. Though one may try to keep artifacts to a minimum, it's difficult to limit this, and the size will likely affect the transport, import, usage, etc. of the report.

It would be ideal having an **option** to include URLs/paths to the attachments **instead** of the base64-encoded version of them. If done, further having an easy way to pass a base URL to be prepended to each attachment URL would be imo very user-friendly. This would allow Test Management frameworks (e.g. Xray) to consume light, portable reports that link to this evidence where stored on a CI server.

Not aware of appropriate workarounds using annotations.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
