### ISSUE TITLE
[BUG] page.isVisible() passing when element does not exist

### ISSUE THREAD

**Issue by PaRadd** [microsoft/playwright#18394]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Windows 10
- Node.js version: 16.14.2
- Browser: Chromium,Firefox,Webkit

**Code Snippet**

```javascript
await page.isVisible(".somenonexistingelementhere")
await page.waitForSelector(".somenonexistingelementhere")
```

**Describe the bug**

Seems like **page.isVisible** is marked as passed even when the element does not exist, same does not happen for **page.waitForSelector** and its failing as expected.
![1](https://user-images.githubusercontent.com/19188706/198543617-c31af4a7-4a87-4fce-8dcb-1c4c6d6a308c.PNG)

**Comment by mxschmitt** [comment]
`page.isVisible` is **not** an assertion. `isVisible` does just return the visibility state in form of a boolean rather than throwing when the condition is not met.

What you are looking for is: `await expect(page.locator('.somethingdoesnotexist')).toBeVisible()` see [here](https://playwright.dev/docs/test-assertions).
