### ISSUE TITLE
[Feature] Decouple Playwright from the browsers it used

### ISSUE THREAD

**Issue by testgitdl** [microsoft/playwright#18469]
I want to be able to use Playwright with older browsers and at the moment this does not seem to be possible as I must use Playwright with the browsers that it is shipped with.

**Comment by dgozman** [comment]
@testgitdl This is by design. Playwright comes with built-in browsers, and is also tested against some stable browser channels, that you can see in the [release notes](https://github.com/microsoft/playwright/releases).

If you need older browsers, use an older Playwright version. You can find the matching Playwright version by looking at [releases](https://github.com/microsoft/playwright/releases) page.

**Comment by testgitdl** [comment]
@dgozman Understood but there are some use cases when this is needed.
Let's take an example that I have experienced recently: there is a bug in the webkit coming with playwright version > 1.22.1 and the fix is scheduled in Playwright version 1.28. In this case I have to remain on a way lower version until I get the webkit fix. In case of decoupling this would not be needed. 
Another example would be that we also need to test with older browser versions. 

So this feature is needed and I don't think I'm the only one requesting it. Please give it more thought.

**Comment by laviniaSer07** [comment]
I have also faced a similar situation where I would need this feature! It would be really helpful!

**Comment by cherrygithub1805** [comment]
This feature is important and useful for my project as well!
Our web applications should support multiple browsers, and we need to test as many browser versions as possible!
