### ISSUE TITLE
[Feature] add Locator.waitForClass(options)

### ISSUE THREAD

**Issue by abjerstedt** [microsoft/playwright#18477]
Right now we handle animations in a format like:
```
async clickButton(): Promise<void> {
  const transition = this.page.locator('[data-test-id="blah"].collapsing'); 
  OR
  const transition = this.page.locator(`${this.page.element}.collapsing`);
  await Promise.all([
    transition.waitFor(state: { 'visible' }),
     button.click()
   ]);
   await transition.waitFor(state: { 'hidden' });
 }
 ```
 
 While this works, it means we can't store the reference as a locator. I would prefer to do something like:
 ```
 async clickButton(): Promise<void> {
  await Promise.all([
    container.waitForClass('collapsing'),
     button.click()
   ]);
   container.waitForClassGone('collapsing')
 }
 ```

**Comment by dgozman** [comment]
@abjerstedt Perhaps [`expect(locator).toHaveClass()`](https://playwright.dev/docs/test-assertions#locator-assertions-to-have-class) will work for you? Behind the scenes, it waits for the element to have a class.

Note that your second snippet is not practical, because it is very much timing-dependent, and will most likely fail on CI sometimes. It could miss the `collapsing` class being added.

**Comment by abjerstedt** [comment]
> @abjerstedt Perhaps [`expect(locator).toHaveClass()`](https://playwright.dev/docs/test-assertions#locator-assertions-to-have-class) will work for you? Behind the scenes, it waits for the element to have a class.

This was discussed as an option, but it feels wrong to use an assertion in action handling.
 
> Note that your second snippet is not practical, because it is very much timing-dependent, and will most likely fail on CI sometimes. It could miss the `collapsing` class being added.

Considering collapses take 300ms to occur, and we are starting the listener before the action - this is exceedingly unlikely (and has never once occurred in CI).
