### ISSUE TITLE
[Feature] HTML reporter sort by spec line number when running on serial mode

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#18494]
It would be great it we sorted the HTML results by line number instead of test outcome when running tests in `.serial` mode.

![2022-11-02_12-43-10](https://user-images.githubusercontent.com/50574915/199383450-b90769b7-da24-4e6b-b5c8-2dec1ec9f6a2.png)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
