### ISSUE TITLE
VSCode Extension feature request: Skip beforeAll hook if playing an individual test

### ISSUE THREAD

**Issue by jpike88** [microsoft/playwright#18541]
See screenshot. I have that whole test file do a seed/reset of the DB on the beforeAll hook.

But when writing new tests, I want the option of skipping the hook, as the test may not have changed application state. This means I don't have to wait for the seed/reset to take place through the preceding tests in order to see what my changes did.

![Screenshot 2022-11-03 at 7 41 38 pm](https://user-images.githubusercontent.com/9585787/199722962-9c579ad7-443c-4d80-8a16-b9bbbc8dfe26.png)

**Comment by yury-s** [comment]
We currently consider globalSetup / beforeAll / beforeEach to be essential parts of the test and always run them with the test even if it runs in isolation. We may add an option to skip the setup in the future but there is no immediate plan for that so I'm closing this issue.

**Comment by yury-s** [comment]
If calling beforeAll hook on every test run is impractical would it make sense to cache the results, e.g. inside `beforeAll` hook check if the database already has the data and skip the step if it does. Would that work for you?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
