### ISSUE TITLE
[Question] multiple route.continue and route.fulfill in a test report

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#18543]
Hi there)

We have a lot of this stuff in our test reports (html and allure). It doesn't help us to debug autotest or to understand testcase. Can we do something with this?) Like remove it, or add urls, or some explanations what exactly happening beyond route.continue and route.fulfill.

<img width="447" alt="Screenshot 2022-11-03 at 16 23 37" src="https://user-images.githubusercontent.com/2929442/199732187-2e733bf7-c755-48a7-9444-c2c8d4a2d05d.png">

<img width="441" alt="Screenshot 2022-11-03 at 16 29 13" src="https://user-images.githubusercontent.com/2929442/199733466-7652dc4a-594b-4a16-bfa7-ca4e4b93f4ae.png">

**Comment by Diokuz** [comment]
Looks like that is our network mocker. We add test.step and solve our problem!

```
    await context.route(trueFn, async (route) => {
      await test.step(`403 for ${route.request().url()}`, async () => {
        await route.fulfill({ status: 403 })
      })
    })
```

Probably route.fulfill should have better report, but if not – just close the issue, we fix it on our side)

**Comment by xyngfei** [comment]
@Diokuz how about I have the method in the class, no really under the playwright test method?

```
  async setExtraHTTPHeaders(page: Page): Promise<void> {
    await page.setExtraHTTPHeaders({ "token": "", "secret": "" });
    await page.route(/(https:\/\/(.*)/, (route) => {
      const headers = route.request().headers();
      headers["token"] = process.env.token ?? "";
      headers["secret"] = process.env.secret ?? "";
      route.continue({ headers });
    });
  }
```

**Comment by CTMarius** [comment]
I'm seeing the same issues in my tests, it's causing the reports to be flooded with route.continue logs and burying the test steps in redundant logging.

**Comment by emil-simeonov-se** [comment]
I can confirm this issue is pretty much happening also in 2025 with Playwright version `1.51.1`. You will find yet another code snippet causing the abundant logging for `route.continue(...)` below. Is there any way to work around this issue on our side?

Troubleshooting simple tests has become a huge pain ever since we introduced this code to pass a custom header with just some of the HTTP requests, i.e. pre-flight requests are filtered out.

```
export async function onRouteChanged(page: Page) {
  await page.route('**/*', route => {
    const request = route.request();

    // Exclude preflight (OPTIONS) requests
    if (request.method() === 'OPTIONS') {
      return route.continue();
    }

    const headers = {
      ...request.headers(),
      'some-header': 'value',
    };

    route.continue({ headers });
  });
}
```

```

```

**Comment by emil-simeonov-se** [comment]
Are there any plans for resolving this issue? Is there a way to bypass the abundant logging?

It's crucial for our testing needs to be able to pass custom HTTP headers. However, our tests often produce 1000+ logged Playwright commands and the majority of them are due to the usage of `route.continue(...)`. This makes troubleshooting a real nightmare. We waste too much time to pinpoint a failing command.

Sometimes, though, commands wouldn't fail at all and a test would finish in a weird state. It's not failed, it's not passed. In such cases it's a huge challenge to reconstruct the test execution flow.
