### ISSUE TITLE
[Question] Browser cookie is not being injected

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#18551]
hello,
I have been trying to set the cookie in my `global-setup` but some reason it is not working for me.

```
const page = await browser.newPage();
  const context = await browser.newContext();
  await page.goto(baseURL);
  await page.fill(username, 'test_user');
  await page.fill(passLocator, 'password'));
  await context.addCookies([{name: "tokentest", value: "cookieHere", domain: "myDomainHere", path: "/"}]);
  await page.pause(); //using this to check cookie in the browser
```

Can someone please help?

**Comment by gauravgandhi1315** [comment]
Is there any way in Playwright to set cookie like `document.cookie=`

**Comment by aslushnikov** [comment]
@gauravgandhi1315 from the limited information here: are you sure your domain is correct?.. also, what does it mean it doesn't work?

Overall, this looks more like a programming error somewhere in your code rather then a Playwright issue. I'll close this for now since it doesn't look like there's a problem inside Playwright that requires some action from the team.

I'd recommend asking this kind of questions on Stack overflow or on our slack - https://aka.ms/playwright/slack

**Comment by gauravgandhi1315** [comment]
@aslushnikov Look at the above code. Am I doing anything wrong? Cookie is not being set in the browser. When I use `document.cookie` in the browser console, it works fine. Can you please help?

**Comment by gauravgandhi1315** [comment]
Is there anything wrong with me code above?

**Comment by aslushnikov** [comment]
Looking closely, you should set cookies to the same context as your page:

```js
  const context = await browser.newContext();
  await context.addCookies([{name: "tokentest", value: "cookieHere", domain: "myDomainHere", path: "/"}]);
  const page = await context.newPage();
  await page.goto(baseURL);
  await page.fill(username, 'test_user');
  await page.fill(passLocator, 'password'));
  await page.pause(); //using this to check cookie in the browser
```
