### ISSUE TITLE
[Question] Please help on Playwright official support for Google chrome and Microsoft edge

### ISSUE THREAD

**Issue by athulds** [microsoft/playwright#18594]
Thanks in advance for the support.

Background: We are in the process of  revamping the engines of our automation platform and came across playwright. We were using selenium at the  core (of our web automation engine) for many years now and are kind of ok with it. But as we all know, there are a lot of custom code to make sure everything goes well and even then there can be some surprises. It looks like playwright has solved many of the selenium stability/reliability issues and hence we are planning to replace selenium with playwright. Since our platform is used to automate browsers (Google chrome & Microsoft edge)installed at customer's windows workstations, we are expecting playwright to do the same.

 After going through the official documentation and online forums , (https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) , It is clear that playwright primarily targeting the browser engines and not the actual branded browsers. But at the same time technically it supports these browsers. But I can see at many places the disclaimer saying -"Use at your own risk" just like below : 

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/17561591/200131023-27d6864f-e7de-4558-808d-bc4dff4b5ba4.png)

   Playwright is using CDP (chrome dev tools protocol) something which is stable , properly versioned and backward compatibility is (almost) ensured by the vendors - at the back end. I would like to understand why there is a "chromium" or "dev"/"canary" channel dependency in playwright and why is it discouraging the use of Google Chrome or Microsoft Edge browsers. 
 Can I go ahead and replace selenium in our engine with playwright for automating these browsers?

**Comment by yury-s** [comment]
> Playwright is using CDP (chrome dev tools protocol) something which is stable , properly versioned and backward compatibility is (almost) ensured by the vendors - at the back end. I would like to understand why there is a "chromium" or "dev"/"canary" channel dependency in playwright and why is it discouraging the use of Google Chrome or Microsoft Edge browsers.

The CDP protocol is not completely stable, sometimes it changes behavior of existing commands and sometimes Playwright relies on certain features we add to CDP upstream which may not be available in older Chrome/Edge versions. This is the main reason why we have this disclaimer. For each playwright version we run our test harness with certain version of Chromium/Google Chrome/MS Edge and can guarantee that everything works with those versions. If playwright version runs ahead and the browser version stays behind some feature might break. With that said, Playwright will most likely work even with older versions of Chrome/Edge/other Chromium based browsers but since we don't run tests with all those versions we cannot guarantee that all features work there.

> Can I go ahead and replace selenium in our engine with playwright for automating these browsers?
I would say yes. If you update playwright regularly keeping up with about monthly release cycle and keep Chrome/Edge versions up-to-date you should not see any issues.

**Comment by athulds** [comment]
@yury-s Thanks for the detailed response. 
 The primary case we are going to face is a fixed version of Playwright (that we package with the product and release) and the browsers installed in the user's desktop will be getting updated based on these browsers release cycle.
So an older version of Playwright can support the newer versions of these browsers ? ( Agree, we will be missing out new features. But looking towards the immunity of existing functionality/test flows towards these browser upgrades.)
