### ISSUE TITLE
[Feature] Enable extra data on configuration

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#18607]
Let us know what functionality you'd like to see in Playwright and what your use case is.

I would like to have a free format object with extra data on the configuration, so you can set it per project / global config and access it in fixtures, tests and global setups / teardown. Ideally - you will be able to setup the variable in the globalSetup file. 

In my case, I needed to calculate the coverage path, but I guess there are a lot of other scenarios. I am not sure if there are limitations on such an object (e.g. serializing)? 

Do you think others might benefit from this as well?
I think this request is showing up as the underlying need in multiple questions / issues. Not sure if everyone that needs it will be able to find the issue. (Maybe I will find a PW Ambassador to promote it on slack...)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
