### ISSUE TITLE
[BUG] record button defaults to target library when in debug mode

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#18619]
**Context:**
- Playwright Version: 1.28.0-alpha-nov-7-2022
- Operating System: Mac
- Node.js version: v16.16.0
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

Run the example test or any test in debug mode and then click the record button in the inspector

**Code Snippet**

`npx playwright test --debug`

**Describe the bug**

When running tests in debug mode and you click on the record button it defaults to recording test in Library format. Consider having it default to test runner or auto detect lang used or disable record button when debugging

<img width="868" alt="Screenshot 2022-11-07 at 20 33 03" src="https://user-images.githubusercontent.com/13063165/200398374-fce663d6-41a9-4047-9e8d-ae0327649621.png">

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
