### ISSUE TITLE
[Feature] Add ability to change testInfo?.project._expect?.timeout parameter in method currentExpectTimeout() for custom test runner

### ISSUE THREAD

**Issue by ibrayevabay** [microsoft/playwright#18634]
We are using mocha-based runner. And we started to use **expect** from @playwright/test lib. 

Main Issue: We are not able to change default timeout from 5000ms to 30000ms. 

Feature request: Could u please provide ability to change not only from PlaywrightTestConfig? 

PlaywrightTestConfig - works only with pw test runner (so provide **expect.timeout** here not working for us)

**Comment by yury-s** [comment]
**expect** from @playwright/test is supposed to be used only within Playwright Test runner. Making it a standalone library is not a goal for playwright and we have no plans changing that.

Is there a reason you cannot use playwright test runner?

**Comment by ibrayevabay** [comment]
ok, got it, it's sad but thanks anyway. Unfortunately, our test framework have a lot of dependencies from mocha runner across all project, so it's a big task for us switching to pw test runner :c

**Comment by topolanekmartin** [comment]
I am struggling with same problem right now. I am using cucumber-js with playwright and I need increase except timeout. But I can't because cucumber-js ignore playwright.config.ts file. Can somebody tell me if there is some workarround please?

I don't want to write function which rewrite file `packages/playwright/src/common/globals.ts` in node_modules directory in order to increase timeout 🙈  But I don't see any other solution.
