### ISSUE TITLE
[BUG] Global Setup fails to apply

### ISSUE THREAD

**Issue by coryhouse** [microsoft/playwright#18676]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: 16.13.1
- Browser: Chromium at least, but likely all.
- Extra: On M1 Mac Ventura

**Code Snippet**

[Small repo that shows the issue](https://github.com/coryhouse/playwright-demo)

**Describe the bug**

I have global setup configured in playwright-config.ts:

```
  globalSetup: "./global-setup",
  use: {
    // Tell all tests to load signed-in state from 'storageState.json'.
    storageState: "storageState.json",
  },
```

This global setup fails to apply. The test in `login.spec.ts` fails to "see" the localStorage info that is persisted in storageState.json. As a workaround, I can add this to the top of login.spec.ts, and it works:

```
test.use({
  storageState: "storageState.json",
});
```

But that shouldn't be necessary per these docs: https://playwright.dev/docs/auth#reuse-signed-in-state

**Comment by dgozman** [comment]
@coryhouse So the problem is that `playwright.config.ts` has two `use` properties, and the first one is ignored, like in any JavaScript object with duplicated properties:
- https://github.com/coryhouse/playwright-demo/blob/main/playwright.config.ts#L15
- https://github.com/coryhouse/playwright-demo/blob/main/playwright.config.ts#L40
The fix would be to merge the two `use` blocks.

When I open this file in VSCode, it highlights the "duplicated object property" error. Alternatively, type-checking the source would prevent similar issues in the future.

Let me know if this helps.

**Comment by coryhouse** [comment]
Ah! 🤦‍♂️ - I didn't realize the default had a `use` property, thanks for the quick help! I agree strongly typing the config would be a nice way to avoid this in the future. Thanks! :)
