### ISSUE TITLE
[Question] How can I get scrollbars in Safari on Windows?

### ISSUE THREAD

**Issue by jez9999** [microsoft/playwright#18683]
I'm using Playwright to check my site's CSS using the install via NPM, documented at: https://joyofcode.xyz/test-your-site-in-every-browser

When I open my site in Safari using `npm run test:safari` in the console, there are no scrollbars rendered.  They are rendered for Firefox and Chrome but not Safari.  How can I get scrollbars?

**Comment by yury-s** [comment]
They are hidden in our build of webkit (for reference https://github.com/microsoft/playwright/pull/10300 is the PR where it was done). We hide scrollbars in other browsers too via command line flags but on windows it is hardcoded as of today. This is to avoid flakiness in screenshots caused by different scrollbar styling etc. Does the lack of scrollbars cause a problem in your tests?

**Comment by jez9999** [comment]
Well, yeah.  I want to see how they look in my overflowing content that gets scrollbars.

**Comment by yury-s** [comment]
Folding this issue into https://github.com/microsoft/playwright/issues/4295 (even thought the title says firefox it actually tracks all the requests for displaying scrollbars).
