### ISSUE TITLE
[BUG] Playwright is not auto-waiting

### ISSUE THREAD

**Issue by eatonjl** [microsoft/playwright#18698]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac OS (M1 Pro)
- Node.js version: 16.16.0
- Browser: WebKit
- Extra:

**Code Snippet**

I have a demo repo, but it isn't in Github or anything. I can send it through wetransfer.

**Describe the bug**
This issue is being open in response to this [closed issue](https://github.com/microsoft/playwright/issues/18552). It was determined that an action is being taken before the page is ready. It was concluded that our application had a bug. However, I was told that one of the main features of Playwright was its ability to auto wait. 
Also, the demo repo I have passes when webkit runs headed and in Chromium either headed or headless. In the closed issue it was noted that the page gets redirected to a blank page. This is not the function of the application, as it would fail in any browser whether headless or not. I assume the test is getting a blank page because the target is being prematurely closed (hence the ""locator.check: Target closed" error). 
I would like someone to take a closer look at it. If the action truly is happening too quick, then I would like an explanation why the auto waits are not occurring. If the target is getting closed, I would like to have it looked at to see why it is crashing. Thank you!

**Comment by yury-s** [comment]
> However, I was told that one of the main features of Playwright was its ability to auto wait.

Playwright does indeed auto-wait for certain conditions, see [this page](https://playwright.dev/docs/actionability). But there are limits to it, e.g. it cannot wait until an event listener is added to a button via some asynchronous javascript code as it doesn't know anything about the application logic and wether any listeners will be added at all. The moment an element is actionable (as described in the document) Playwright will attempt to click it. Basically it behaves as a very fast user - the moment it sees the element on the screen it will perform the click. To avoid the in the original report the app could either make sure that the element is not actionable (visible) until all event handlers are ready or the test code could be adjusted to wait for an application-specific condition that would indicate that it is a good time to click the button.

> In the closed issue it was noted that the page gets redirected to a blank page. This is not the function of the application, as it would fail in any browser whether headless or not. 

The dialog is certainly created by the code of the page, you can intercept that by modifying the code of the test as below. You can also listen to [framenavigated](https://playwright.dev/docs/api/class-page#page-event-frame-navigated) events to see that the page does navigate to about:blank after the dialog is closed.

```js
test('Send Document To Review', async ({ browser }) => {
  // Setup
  const documentOwnerOneContext = await browser.newContext({
    storageState: 'documentOwnerOneStorageState.json',
  });
  const documentOwnerOnePage = await documentOwnerOneContext.newPage();
  documentOwnerOnePage.on('dialog', d => {
    console.log(d.type() + ' ' + d.message());
  })
  documentOwnerOnePage.on('framenavigated', f => console.log('navigated ' + f.url()))
  const policyTechDocumentPage = new PolicyTechDocumentPage(
    documentOwnerOnePage
  );
```

It doesn't happen on always / on all browsers because most likely the behavior is racy.

> I would like someone to take a closer look at it.

We can have another look at it. The app is pretty big and we don't have resources to debug it in its entirety so it'd be very helpful if you could come up with a minimal repro which demonstrates that there is a problem in playwright. So far from what I see you are getting `locator.check: Target closed` error because the app navigates away to about:blank before the action completes.

**Comment by eatonjl** [comment]
Thank you for that information. With that debugging you have added into the code, I will have my team take a look at that. Please keep this open until I report back. 


> It doesn't happen on always / on all browsers because most likely the behavior is racy.

I did think about that. However, it ALWAYS fails on Webkit headless and has yet to ever fail on any of the other browsers or Webkit headed.

**Comment by pavelfeldman** [comment]
We have a policy of closing the issues we can't act upon in a timely manner. Please link to this issue as you file the one with the repro!
