### ISSUE TITLE
[Question] What is the best method to automate the react-select package?

### ISSUE THREAD

**Issue by xyngfei** [microsoft/playwright#18726]
1. How can I use a more effective method to click on the Orange selection from the dropdown list? Especially the dropdown list is a callbacks example

>  await page.goto("https://react-select.com/home");
> await page.locator("//*[@id='react-select-10-input']").fill("Orange");
> const select = await page.waitForSelector(
>  "//*[contains(@id,'listbox')]//div//div[1]"
> ); `
>
> const text = await page
> .locator("//*[contains(@id,'listbox')]//div")
>  .allTextContents();
> console.log(text);
> await select.click({ delay: 3000 });
>
> await page.locator("//*[@id='react-select-10-input']").press("Tab");
> await page.locator("//*[@id='react-select-11-input']").click();

2. How can I randomly select any dropdown value from react-select?

**Comment by yury-s** [comment]
> How can I use a more effective method to click on the Orange selection from the dropdown list? Especially the dropdown list is a callbacks example

We have experimental support for [react-selectors](https://playwright.dev/docs/selectors#react-selectors) which may come in handy.

> How can I randomly select any dropdown value from react-select?

You can use [locator.selectOption](https://playwright.dev/docs/api/class-locator#locator-select-option) to select options in an html dropwdown list.

If this doesn't work for you please file a new bug with a reproducible example that demonstrates what is not working so that we could run it locally and could give a better advice.

**Comment by xyngfei** [comment]
@yury-s 

Possible to give an example of how to select the react selectors? I would get it work even read through the documentation. 

Meanwhile, [locator.selectOption](https://playwright.dev/docs/api/class-locator#locator-select-option) is not supported bcos the HTML element is not the select component.
