### ISSUE TITLE
[BUG] Timing values aren't always showing

### ISSUE THREAD

**Issue by jpike88** [microsoft/playwright#18729]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: 16.4.1
- Visual Studio Code version: 1.73.1
- Playwright for VSCode extension version: 0.2.15
- Browser: Chrome

I have two files, let's call them `A` which contains the actual test, and `B` which contains reusable functions that help consolidate the playwright commands.

I see a couple of bugs here:

**Refactored functions do not show the sum of timing next to them**

This is from file `A`, showing a function that was exported from file `B`, it has no timing value next to it.
<img width="944" alt="Screenshot 2022-11-11 at 1 40 11 pm" src="https://user-images.githubusercontent.com/9585787/201279323-1c398fb8-45db-4dbf-b41d-8ca300ab36b2.png">

This is the function in file `B`. The timing values are showing for the individual lines which is good.
<img width="722" alt="Screenshot 2022-11-11 at 1 50 05 pm" src="https://user-images.githubusercontent.com/9585787/201280528-7b7e4749-3c8c-4b84-9dc4-57fa2abd6e7e.png">

The sum of the timing should be extracted out next to the `switchUser` function in file `A`, as it's confusing/misleading to not see any value next to it, it may indicate there's a problem/stuck even though the function is successfully completing.

**Switching files clears timing values**

See recorded video:

[demo.webm](https://user-images.githubusercontent.com/9585787/201281277-c82c09b0-f301-4ef7-b9b0-f027c960e49d.webm)

There is strange behaviour how the values are appearing/disappearing while tests are running, this issue is triggered by switching from one file to another.

**Comment by yury-s** [comment]
> Refactored functions do not show the sum of timing next to them

The timing is only shown next to the playwright API methods, so this is an expected behavior.

> Switching files clears timing values

This looks like a bug to me, switching between editor panels could preserve the decorations.

**Comment by jpike88** [comment]
> The timing is only shown next to the playwright API methods, so this is an expected behavior.

Why omit those values? If I end up doing more refactoring, I won’t be seeing any timing values at all on my tests unless I visit the individual functions. That seems like a hindarance to me.

**Comment by pavelfeldman** [comment]
> Why design it that way?

It is more of a feasibility rather than an intentional design question. Imagine there are no Playwright calls in the method you called (switchUser). You would probably still expect to see the time annotation for it. Now let's make the next logical step and figure out if this feature has anything to do with Playwright. Not really, it does not. So it looks like you are looking for a general purpose NodeJS feature that would annotate your source code with the timers. We don't provide this generic capability, all we do is we should how long certain API call took. We also don't re-render these annotations on the tabs activity or source modifications to keep highly transient.
