### ISSUE TITLE
[Feature] typesafe assertions

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#18760]
Can the matcher/assertion functions be generic and typesafe as in Jasmine?: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine/v3/index.d.ts#L792. There is also a ticket for this at Jest: https://github.com/facebook/jest/issues/13334 and https://github.com/facebook/jest/pull/13444#pullrequestreview-1143148241.

```typescript
expect(true).toBe('') // type error: the expect prop type is not equal to the matcher prop type
```

This might also be useful for API testing:

```typescript
// ProductDto.ts
export type ProductDto = {
  id: string;
  name: string;
}
```

```typescript
import { ProductDto } from '@shared-package';

test('API response matches the ProductDto', async ({ request: http }) => {
  const response = await http.get<ProductDto>('/product/1337');
  const data = await response.json(); // data is typeof ProductDto
  expect(data).toEqual({ id: 1337, name: 'John' }); // error property 'id' is not a string
});
```

**Comment by mrazauskas** [comment]
Similar change was made in `@types/jest` some time ago and had to be reverted. For discussion see https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62128

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
