### ISSUE TITLE
[Question] Intercept api calls of service worker

### ISSUE THREAD

**Issue by rony-arnac** [microsoft/playwright#18762]
Hi,

How do I intercept API calls of a service worker? I assumed `context.route` covered everything contained in context, service workers included.
Was I wrong? If so, how do I intercept their apis as well?

Thanks!

**Comment by pavelfeldman** [comment]
There is an experimental mode for this: https://playwright.dev/docs/next/service-workers-experimental. It is a rare request, so if you'd like to see it promoted to the default mode, please describe your use case here in greater detail!

**Comment by rony-arnac** [comment]
Hi @pavelfeldman 
I'm using playwright to test our chrome extension mv3 solution.
Currently we are not able to mock the API requests sent by the background service worker, since they are not intercepted by the routes defined on the browser context.
I'd like a way to either include the api requests made by the service worker to be part of the browser context, or define the interceptors specifically for the service worker.
First option is best since it will reduce duplication between website APIs and extension APIs.
Thx!

**Comment by pavelfeldman** [comment]
Ok, please try using the experiment above and tell us if it worked for you. With the env variable set, SW requests are emitted on the browser context.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
