### ISSUE TITLE
[BUG] `codegen` does not open proper page for recording

### ISSUE THREAD

**Issue by alex4200** [microsoft/playwright#18776]
**Context:**
- Playwright Version: 1.27.1
- Operating System: MacOS 12.6
- Node.js version: v14.15.0
- Browser: ?

## System:
 - OS: macOS 12.6
 - Memory: 20.41 MB / 8.00 GB
## Binaries:
 - Node: 14.15.0 - /usr/local/bin/node
 - npm: 8.19.1 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

`npx playwright codegen https://courseware.epfl.ch/login
`

**Describe the bug**

I expect the above command let me record some webpage actions, but instead it just shows the first "screen"

<img width="252" alt="Screenshot 2022-11-14 at 09 59 57" src="https://user-images.githubusercontent.com/12729291/201619579-59e1441f-131f-4ce5-9b2b-d0659cfe8fbb.png">

and it does not "continue" as it does when you open the same page in a normal browser.

**Comment by pavelfeldman** [comment]
I can reproduce the problem. For how you can run
```sh
npx playwright open https://courseware.epfl.ch/login
```

and then click 'Record' button in the Playwright Inspector window.

**Comment by pavelfeldman** [comment]
Investigation node: this page evaluates JavaScript that clicks a hidden button `button button-primary button-oa2-edx-oauth2 login-provider login-oa2-edx-oauth2` that results in a navigation. Recorder thinks that the user clicked the button, so it intercepts it for recording and performs the automated click, which fails since the button is hidden.
