### ISSUE TITLE
If files are in one directory, flatten or open up the tree

### ISSUE THREAD

**Issue by jpike88** [microsoft/playwright#18840]
Every time I open VSCode and go to the tests panel, I have to manually expand the tests, and then the src folders in the tree to view/access the tests. This is not ergonomic, should just display them all if they're located in a single path
![Screenshot 2022-11-16 at 1 22 20 pm](https://user-images.githubusercontent.com/9585787/202100165-b2881a0a-3041-4a3b-ae4b-2ee6f49c4eed.png)

**Comment by guido-visser** [comment]
Any progress on this? There's a _Collapse All Tests_ in the meatball menu. Could an option be added to expand all tests? Or expand all underlying layers of a folder as suggested by OP?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
