### ISSUE TITLE
[BUG] Screenshot cannot be captured correctly

### ISSUE THREAD

**Issue by refcpu** [microsoft/playwright#18851]
**Context:**
- Playwright Version: 1.27.1(playwright-core)
- Operating System: Windows
- Node.js version: 18.12.1
- Browser: Chromium

**Code Snippet**

```javascript
const context = await chromium.launchPersistentContext(userDataDir, {
    channel: 'msedge',
    headless: false,
    viewport: null,
    ignoreDefaultArgs: ['--enable-automation']
});
const page = await context.newPage();
await Promise.all([
     page.waitForLoadState(),
     page.goto('https://playwright.dev/')
]);
const screenshot = await page.screenshot({ fullPage: true });
const imgData: NativeImage = nativeImage.createFromBuffer(screenshot);
clipboard.writeImage(imgData);
```

**Describe the bug**

Right and bottom of the screen cannot be captured correctly. Is there a solution?

_**Right: be cut off**_
_**Bottom: have a white space**_
![image](https://user-images.githubusercontent.com/27007235/202226132-e203710e-cec0-4922-8a7d-bc4a563f1475.png)

**expect:**
![image](https://user-images.githubusercontent.com/27007235/202225883-06e960df-5105-4f82-8aae-8fe08e3be7c2.png)

**Comment by pavelfeldman** [comment]
It is unclear why you expect images to be the same, could you provide steps to reproduce?

**Comment by refcpu** [comment]
> It is unclear why you expect images to be the same, could you provide steps to reproduce?

I did not expect the images to be exactly the same, and decided that the right side was not fully captured and that the extra space at the bottom was not a normal capture.

![image](https://user-images.githubusercontent.com/27007235/202334947-0d141ea4-5ea1-47ab-a9d3-48bda6c28886.png)
![image](https://user-images.githubusercontent.com/27007235/202335194-f3e4aa40-1b17-46a3-9919-11248d5e055c.png)

All you need to do is run Code Snippet code for reproduction.

**Comment by pavelfeldman** [comment]
Got it!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
