### ISSUE TITLE
[Feature]: tracing enabled with REST API request context

### ISSUE THREAD

**Issue by jnjgomez10** [microsoft/playwright#18891]
### Your question

How can I get tracing=on to work with  REST API request context.  Tracing works with Browser context but I could not get it to work with playwright.request.new_context.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
