### ISSUE TITLE
[BUG] Viewport change in Chrome (crPage.js) when taking screenshot triggers animations

### ISSUE THREAD

**Issue by NVolcz** [microsoft/playwright#18934]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Linux
- Node.js version: v14.19.1
- Browser: Chrome

## System:
 - OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - Memory: 6.13 GB / 15.36 GB
 - Container: Yes
## Binaries:
 - Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
 - Yarn: 1.22.5 - /usr/bin/yarn
 - npm: 8.10.0 - ~/.nvm/versions/node/v14.19.1/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash

Here is some code that sometimes triggers the issue.
```javascript
const { chromium } = require('playwright');
const { test, expect } = require('@playwright/test');

test("Animations may get triggered in Chrome", async () => {
  await page.goto('https://www.springflod.se/')

  const ref = await page.screenshot({
    animations: "disabled",
    fullPage: true,
    scale: "css",
    path: "ref.png"
  });

  const test = await page.screenshot({
    animations: "disabled",
    fullPage: true,
    scale: "css",
    path: "test.png"
  });

  expect(test, "should in many cases match reference").toMatchSnapshot("ref.png", {
    maxDiffPixelRatio: 0,
    maxDiffPixels: 0,
    threshold: 0
  });
})

```

**Describe the bug**

Taking a full page screenshot in Chrome may trigger animations that are triggered based on the viewport since it is changed before taking the screenshot.

```
await page.screenshot({
  animations: "disabled",
  fullPage: true,
  scale: "css",
});
```

**Comment by dgozman** [comment]
@NVolcz `animations: 'disabled'` only stops CSS animations, CSS transitions and Web Animations. I looked at the page, and it seems to be doing some JavaScript-based animation instead. Unfortunately, Playwright cannot stop those.

I'd recommend to use [`expect(page).toHaveScreenshot()`](https://playwright.dev/docs/test-assertions#page-assertions-to-have-screenshot-1) instead, because it waits for screenshot stability. The following snippet works reliably for me.

```ts
import { test, expect } from '@playwright/test';

test('example test', async ({ page }) => {
  await page.goto('https://www.springflod.se/');

  await expect(page).toHaveScreenshot('ref.png', {
    maxDiffPixelRatio: 0,
    maxDiffPixels: 0,
    threshold: 0,
    animations: 'disabled',
    fullPage: true,
    scale: 'css',
  });
});
```

Let me know if this helps.

**Comment by NVolcz** [comment]
Thanks for suggestion. I still see this as a bug since the behaviour is a bit unexpected and also not consistent between browsers. My workaround was to manually set the viewport and wait for stability before taking the screenshot but this duplicates what `fullPage: true` is supposed to handle.

**Comment by dgozman** [comment]
@NVolcz `fullPage` does not really change the viewport, so I don't think that's the problem.

Most likely, the key here is "waiting for stability", because that's exactly what `toHaveScreenshot()` offers over just `page.screenshot()` and it helped. Playwright cannot guarantee that your page does not change while you call `page.screenshot()`, but it uses smart strategy in `expect(page).toHaveScreenshot()` to "wait for stability".

**Comment by NVolcz** [comment]
You are correct, it seems that I took a wrong turn somewhere when
debugging. Will go back to debugging the issue again so we can close
this issue as a false positive.
