### ISSUE TITLE
[Feature] vs code: support monorepos

### ISSUE THREAD

**Issue by ivanhofer** [microsoft/playwright#18960]
The VS Code extension should not just look for `playwright.config.ts` files at the root to pick up test files. Also subfolders should be taken into account.

**Comment by dgozman** [comment]
@ivanhofer VSCode extension does look into folders. For example, in Playwright's own repo there are many configs, [some](https://github.com/microsoft/playwright/blob/main/tests/components/ct-react/playwright.config.ts) of them [pretty deep](https://github.com/microsoft/playwright/blob/main/tests/library/playwright.config.ts) in the tree.

Do you mind sharing a repro where things do not work, so that we can debug the issue locally?

**Comment by ivanhofer** [comment]
Today it works flawlessly!
I have restarted VS Code several times yesterday. I didn't see any play button on my tests and the testing panel in VS Code was empty. Only when I moved the config to the root level VS Code picked up my tests.
It seems restarting my computer fixed it.
