### ISSUE TITLE
[Question] How do i block the location pop-up

### ISSUE THREAD

**Issue by harshith-aimyth** [microsoft/playwright#18964]
Hi,

I want to block the location popup in my test function in playwright how do I do that?

![image](https://user-images.githubusercontent.com/107207855/203096170-1afce67f-2b6d-414f-a691-f0ed2adf594f.png)

```
test('Test123', async ({ page }) => {
        page.goto('google.com');
}
```

**Comment by jameskip** [comment]
https://playwright.dev/docs/api/class-browsercontext#browser-context-grant-permissions

**Comment by dgozman** [comment]
Also, [here is a guide](https://playwright.dev/docs/emulation#geolocation) for geolocation.

**Comment by dgozman** [comment]
@harshith-aimyth Oh, sorry, I misunderstood. So you'd like not to `Allow`, but to `Block` with Playwright? This is not supported today. I'll leave this as a feature request.

**Comment by jameskip** [comment]
Is it possible to deny this prompt at the context level by passing this: `--deny-permission-prompts` to chromium?

**Comment by dgozman** [comment]
@jameskip `--deny-permission-prompts` chromium flag works across all contexts, but Playwright will take that into account if you specify `launchOptions.args` for a single file:


```ts
test.use({ launchOptions: { args: ['--deny-permission-prompts'] } });

test('no prompts', async ({ page }) => {
});
```

Alternatively, just specify it once in the config to disable all prompts in all tests:
```ts
export default {
  projects: [
    {
      name: 'chromium',
      use: {
        ..devices['Desktop Chromium'],
        launchOptions: { args: ['--deny-permission-prompts'] },
      },
    }
  ],
};
```

**Comment by autonationIssues** [comment]
Hi, any update on geolocation issue? Grant permission or dialog is not working for me

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
