### ISSUE TITLE
[Feature] Allow selecting textareas by text value

### ISSUE THREAD

**Issue by fzembow** [microsoft/playwright#18970]
In the documentation for [Selectors](https://playwright.dev/docs/selectors#text-selector), it is written

> Input elements of the type button and submit are matched by their value instead of text content. For example, text=Log in matches <input type=button value="Log in">.

Could this also be extended to match `<textarea />` elements as well?

I've noticed that if you have multiple textareas, it is not possible to query them using the text selector, which seems like an omission? My use case is a simple TODO style app where each task is in a textarea - I'd like to select them as an end user might, by reading the text within them.

**Comment by debs-obrien** [comment]
Hi @fzembow 

Have you tried updating to the latest version of Playwright and using the new [Locator API.](https://playwright.dev/docs/locators#quick-guide) The selectors doc is now outdated so we highly encourage you to use the new [Locators](https://playwright.dev/docs/locators#quick-guide) one. 

You can use [codegen](https://playwright.dev/docs/codegen-intro) to help you find the right locators
```npx playwright codegen```

if using VS Code I highly encourage you to check out the [Extension](https://playwright.dev/docs/getting-started-vscode).

Here is a [list of all release videos](https://playwright.dev/community/release-videos) incase you missed the latest release video which talks about the new locators

Let me know if that helps

**Comment by dgozman** [comment]
@fzembow I think this is a valid feature request. There is a similar API in the DOM Testing Library called [`ByDisplayValue`](https://testing-library.com/docs/queries/bydisplayvalue).

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
