### ISSUE TITLE
[BUG] Why do issues get closed so easily.....

### ISSUE THREAD

**Issue by gselsidi** [microsoft/playwright#19001]
Noticing a lot of issues get closed haphazardly with bogus reasons no repro. People providing full repo's asking to ping for sensitive info, and just closing it.

I provided literally a 2 step repro, such as .goto .screenshot, closed...... like what? I'm supposed to create a whole repo with a brand new framework, for me to upload a repo for a 2 step test???? 

Seems very haphazard, or downright laziness, or malicious to close issues....

I understand there are a bunch of issues, but continuing down this path will just lead to a dead framework down the line, if nobody cares to investigate issues that literally take 5 seconds.... 

https://github.com/microsoft/playwright/issues/18406

Literally set height on body 100% or go to provided website
Goto
take screenshot fullpage

I literally provided the bug and the reason why it's happening, as we debugged it, yet get's thrown closed because can't copy paste 2 lines of code....

**Comment by pavelfeldman** [comment]
> Why do issues get closed so easily...

We get roughly an issue per hour filed. In order to be efficient, we are only accepting the issues that have clear steps to reproduce, clearly stated expected and actual states. Your did not offer that, we need to read the thread and guess what is it about. We would rather prioritize the issues with the clear description (actionable) that are likely to affect broader audiences (impactful).
