### ISSUE TITLE
[BUG] React selector doesn't work with higher-order components

### ISSUE THREAD

**Issue by hanayashiki** [microsoft/playwright#19042]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: Mac
- Node.js version: 1.28.0
- Browser: Chromium
- Extra: Non

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```tsx
import { observer } from 'mobx-react';

export const CookiePolicy = observer(() => {
  return (
    <div>
      Please read our cookie policy.
      <button>Agree</button>
    </div>
  );
});
```

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  await page.locator('_react=CookiePolicy >> button:text("Agree")').click(); // Times out
})();
```

**Describe the bug**

Playwright's react selector seems doesn't work with higher-level components. This might be caused by the fact that the outer name of the component is not preserved. I would suggest using a wrapper component or `test id` for this scene to work around it.

**Comment by dgozman** [comment]
@hanayashiki You are right - if the name of the higher-order component is not preserved in debug build of React, there is no way to locate based on it. Unfortunately, I don't think Playwright can do something here. Your workarounds with a wrapper or `data-testid` attribute are great.

Unless I misunderstood the issue, I am inclined to close it, since it's not actionable.
