### ISSUE TITLE
[BUG] Incorrect click position calculation on WebKit on Windows with custom scale factor

### ISSUE THREAD

**Issue by alvkN** [microsoft/playwright#19044]
**Context:**
- Playwright Version: 1.27.1 and 1.28.0
- Operating System: Windows 10
- Node.js version: v18.12.1
- Browser: WebKit
- Extra: Custom display scale factor: 115%

**Code Snippet**

```csharp
await page.Locator("button:has-text('Войти')").ClickAsync();
```

**Describe the bug**

Playwright's webkit calculates click position incorrectly on Windows with custom display scale, and it makes debugging impossible
![image](https://user-images.githubusercontent.com/78173939/203730803-64f9b3b7-78e4-4dd7-8eda-a632eb34e892.png)

I tested the same code with 100% scale and all is working.

**Comment by mxschmitt** [comment]
Can you provide us a repro which we can run locally?

**Comment by alvkN** [comment]
Sorry, I can't send you project because it's work project. I should clarify: windows offers standard scaling options like 125%, 150%, etc., but the problem only appears when scaling is user defined, e.g. 115%

**Comment by alvkN** [comment]
I just created an ASP.NET Core MVC app (using default template) and it has the same problem, so I'm sure the problem is not with project or tests

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
