### ISSUE TITLE
[BUG] toHaveText() includes display:none elements

### ISSUE THREAD

**Issue by darabos** [microsoft/playwright#19072]
**Context:**

- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: 18.3.0
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

```javascript
const { chromium, expect } = require('@playwright/test');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.setContent(`
    <div>
      hello <span style="display: none">world</span>
    </div>
  `);

  await expect(page.locator('div')).not.toHaveText('hello world');
})();
```

**Describe the bug**

It's surprising to me that `toHaveText()` picks up text from hidden (`display: none`) elements. I really don't care about their contents and just want to make assertions about what is visible. Is there a way to do that?

**Comment by dgozman** [comment]
@darabos Text content on the web generally includes hidden text as well. Perhaps you want the [`useInnerText` option](https://playwright.dev/docs/test-assertions#locator-assertions-to-have-text-option-use-inner-text) that would take the visibility, and more, into account?

```ts
await expect(page.locator('div')).not.toHaveText('hello world', { useInnerText: true });
```

**Comment by darabos** [comment]
> @darabos Text content on the web generally includes hidden text as well.

You mean in the `.textContent` sense? Yeah, but do tests generally want to make assertions about invisible text?

> Perhaps you want the [`useInnerText` option](https://playwright.dev/docs/test-assertions#locator-assertions-to-have-text-option-use-inner-text) that would take the visibility, and more, into account?

This is perfect, thank you! Maybe we could have a config setting to make this the default?

How important this is probably depends on the framework used in the application. For me it's an Angular.js application with lots of `ng-show` logic to hide/display things.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
