### ISSUE TITLE
[Feature] Do not skip test if shard has no tests to run, generate an empty report instead

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#19073]
Use case:

I'm statically sharding tests and that works well if there are more tests than shards. However, if you're rerunning a failed test on CI and you have 2 shards then end result looks like:
```
Running 1 test using 1 worker, shard 1 of 2
  1 passed
Running 1 test using 0 workers, shard 2 of 2
  1 skipped
```

It's a bit confusing. Would it be possible to shards that have no tests to run to not skip the test and produce just an empty report?

**Comment by unlikelyzero** [comment]
We regularly have empty shard executions like @MindaugasMateika . For us, the outcome is wasted CI minutes in spinning up a shard to assign it zero "work" to do.

I think we could recast the enhancement as: Prevent shards from executing totally skipped tests. If I had to guess, this would require that sharding pre-calculates if a test is set to skipped before dividing up the total number of tests to shard.

Instead of `Total # of Tests / Shards`, the calculation would be `Total # of non-skipped tests / Shards`

**Comment by dgozman** [comment]
How do you mark tests as skipped? If you are using top-level syntax and not inline syntax, perhaps we can implement @unlikelyzero's proposal.

```ts
// Top-level syntax
test.skip('top-level skipped test', async () => {
  // ...
});

// Inline syntax
test('inline skipped test', async () => {
  test.skip();
  // ...
});
```

**Comment by MindaugasMateika** [comment]
I'm not skipping tests at all, CI always shards tests and sometimes if I'm rerunning a single test so playwright skips the test itself. So if you have 10 shards and you run a single test then you end up with one test passing and 9 skips.

```
npx playwright test --grep 'one test' --shard=1/2
npx playwright --grep 'one test' --shard=2/2
...
``` 

```
Running 1 test using 1 worker, shard 1 of 2
  1 passed
Running 1 test using 0 workers, shard 2 of 2
  1 skipped
```
