### ISSUE TITLE
[Question] Adding an if condition to Promise.all

### ISSUE THREAD

**Issue by marijana-rukavina** [microsoft/playwright#19134]
I am trying to do the following:
When I am on the cart page and click the CHECKOUT button, then there are 2 things that can happen:
I am redirected to the checkout page
I am asked sometimes to log in again => this is a bug in the app since I am already logged in but it asks me to log in again for some reason.
I need to write a Playwright test for the checkout process. And in this test, I need to support that buggy behavior since there is no indication it will be resolved any time soon (or whatsoever).

This is what I got so far:
```Typescript
async clickCheckoutBtn() {
    if (this.#isGuest) {
      // redirects to the login page, so we don't have waitForURL like when we are logged in
      await this.#checkoutBtn.click();
    } else {
      // TODO add here somehow to login again if required after clicking the checkout button
      await Promise.all([
        this.page.waitForResponse(
          (response) =>
            response.url().includes('/my-account/addressform') &&
            response.status() === ResponseCode.SUCCESS
        ),
        
        this.#checkoutBtn.click(),
        this.page.waitForURL(/.*\/delivery-address\/add$/),
      ]);
    }
  }
```

Now, this is what I would like to do:  
```Typescript
    await page.getByRole('button').click();
    if(await page.getByPlaceholder('login').isVisible()) {
      await loginPage.login(username, password);
    } 
    await page.waitForURL(/.*\/delivery-address\/add$/),  
```  
But in the case when I am redirected to the checkout I also need to waitForResponse to the `/my-account/addressform.` (so after logging in I need to wait for it, but also after direct redirect to the checkout page, I need to wait for it as well)
So I would like to do this somehow inside the `Promise.all,` but I don't how to do it.
Can you please help?

**Comment by dgozman** [comment]
@marijana-rukavina Unfortunately, I didn't really understand the question. In your second snippet, it seems like we can add `waitForResponse` right after `loginPage.login()` call. Is there a problem with that? I guess we'll need a more detailed description to be able to help here.

**Comment by mareru** [comment]
@dgozman So, I am trying to implement my checkout test in a way it can handle this buggy issue (the fact that it asks the user to log in again even though he was already logged in).  
This is what happens:  
- I am already logged in to the shop
- I am on the cart page
- I click on the checkout button
At this point, 2 things can happen
1. I get redirected to the checkout page
2. sometimes I am redirected to the login page so I need to log in again and after clicking the login button, I am again redirected to the checkout page.

The tricky part here is that I am facing when I am redirected to the checkout page (either directly after clicking the checkout button or indirectly by first filling out the login form and clicking the login button) is:  
in order to be able to continue filling out forms on the checkout page I need to wait for 2 things:  
This endpoint to return 200 OK:
```Typescript
this.page.waitForResponse(
          (response) =>
            response.url().includes('/my-account/addressform') &&
            response.status() === ResponseCode.SUCCESS
        ),
```
And wait for this navigation to the URL: 
```Typescript
this.page.waitForURL(/.*\/delivery-address\/add$/)
```
That is how my test looks like currently (without the tackling log in buggy issue) - as mentioned above: 
```Typescript
async clickCheckoutBtn() {
    if (this.#isGuest) { // YOU CAN IGNORE THIS PART WITH THE GUEST USER - just focus on the else part which is the one for the logged in user
      // redirects to the login page, so we don't have waitForURL like when we are logged in
      await this.#checkoutBtn.click();
    } else {
      // here are my necessary waits that need to happen after clicking the checkout button
      await Promise.all([
        this.page.waitForResponse(
          (response) =>
            response.url().includes('/my-account/addressform') &&
            response.status() === ResponseCode.SUCCESS
        ),
        
        this.#checkoutBtn.click(),
        this.page.waitForURL(/.*\/delivery-address\/add$/),
      ]);
    }
  }
```
Now, I don't know how to handle the login part in the test, since I need to do these waits when I am on the checkout page, and here I have it bundled to the `Promise.all`.  
This is the idea in progress with which I am still struggling to wrap my head around (I would put this in the else part of the above code):  
``` Typescript
try {
    await Promise.all([
      this.page.waitForNavigation({ url: '**/login' }),
      this.#checkoutBtn.click(),
    ]);
    const credentials = await Utils.getCredentials(this.#context);
    await this.#loginPage.email.fill(credentials.username);
    await this.#loginPage.password.fill(credentials.password);

    await Promise.all([
      this.page.waitForResponse(
        (response) =>
          response.url().includes('/my-account/addressform') &&
          response.status() === ResponseCode.SUCCESS
      ),
      this.#loginPage.loginBtn.click(),
      this.page.waitForURL(/.*\/delivery-address\/add$/),
    ]);
  } catch (error) {
    console.log('USER WAS NOT LOGGED OUT');
    await Promise.all([
      this.page.waitForResponse(
        (response) =>
          response.url().includes('/my-account/addressform') &&
          response.status() === ResponseCode.SUCCESS
      ),
      // this.#checkoutBtn.click(), => maybe I don't need this one since I already clicked it in the try block :/
      this.page.waitForURL(/.*\/delivery-address\/add$/),
    ]);
  }
```  
But I don't know how to say in the catch part to wait for my 2 guys (endpoint and navigation to the URL) since I already clicked on the checkout button before and I fear that waiting for those things in the catch block might be pointless since there is no triggering action with them (which is clicking the checkout button that happened already in the try block).  

I hope I make sense of all of this, I tried to explain as best as I can but if you have any more questions please feel free to ask.
Thanks in advance for any shot or idea you can provide :)

**Comment by marijana-rukavina** [comment]
@dgozman  do you need more details? Is there something still unclear:D

**Comment by aslushnikov** [comment]
> But I don't know how to say in the catch part to wait for my 2 guys (endpoint and navigation to the URL) since I already clicked on the checkout button before and I fear that waiting for those things in the catch block might be pointless since there is no triggering action with them (which is clicking the checkout button that happened already in the try block).

IIUC you can just extract those promises and use them in both parts of your program:

```js
let promises = [];
try {
    await Promise.all([
      this.page.waitForNavigation({ url: '**/login' }),
      this.#checkoutBtn.click(),
    ]);
    const credentials = await Utils.getCredentials(this.#context);
    await this.#loginPage.email.fill(credentials.username);
    await this.#loginPage.password.fill(credentials.password);

    const promises = [
      this.page.waitForResponse(
        (response) =>
          response.url().includes('/my-account/addressform') &&
          response.status() === ResponseCode.SUCCESS
      ),
      this.page.waitForURL(/.*\/delivery-address\/add$/),
    ];
    await Promise.all([
      ...promises,
      this.#loginPage.loginBtn.click(),
    ]);
  } catch (error) {
    console.log('USER WAS NOT LOGGED OUT');
    await Promise.all(promises);
  }
```

So this would be my recommendation if I understood you correctly.

However, this is not a Playwright issue - more of a programming challenge. I'd recommend asking this elsewhere - StackOverflow, or maybe even https://aka.ms/playwright/slack. I'll close this since this doesn't require attention from the Playwright team specifically.

**Comment by mareru** [comment]
@aslushnikov Thanks for the help, it was very useful in the end. 
Sorry, sometimes I cannot distinguish what should go where - is it Typescript I am wrestling with or Playwright, or just my stupidity?
Thanks anyways for the help, I really appreciate it. 
People like you make a difference :*
