### ISSUE TITLE
[BUG] 'show browser' forces single threaded test execution

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#19149]
When `show browser` is on all tests unconditionally run on a single worker. This is very confusing, we should either print a message to the console (or notify the user some other way) or allow multiple browser windows.

**Comment by pavelfeldman** [comment]
Let's collect upvotes.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
