### ISSUE TITLE
In experimental-ct-svelte, is it possible to pass a component as a prop

### ISSUE THREAD

**Issue by obgibson** [microsoft/playwright#19151]
I have a `Button` component that accepts a prop that is an icon. e.g. `<Button leadingIcon={ChevronLeft}/>`

I am trying to write a unit test with `@playwright/experimental-ct-svelte`.

I have not been able to pass a component as a prop.

```
import { test, expect } from '@playwright/experimental-ct-svelte';
import Icon from '../icons/chevronleft.svelte';
import Button from '../Button.svelte';

const buttonText = 'Click me';

test('Button shows leading icon', async ({ mount }) => {
	const IconComponent = await mount(Icon);
	const component = await mount(Button, {
		props: { leadingIcon: IconComponent },
		slots: { default: buttonText }
	});
	expect(component);
});
```

Is this possible?

**Comment by mxschmitt** [comment]
Marking it as a feature request

**Comment by sand4rt** [comment]
related to: https://github.com/microsoft/playwright/issues/15620

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
