### ISSUE TITLE
[BUG] [webkit] page.route does not work well with css background:url

### ISSUE THREAD

**Issue by andresusanto** [microsoft/playwright#19158]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Mac
- Node.js version: v16.17.0
- Browser: WebKit
- Extra: N/A

**Code Snippet**

```ts
import { test, expect } from "@playwright/test";

test.only("testing", async ({ page }) => {
	await page.route(`**/*`, async (route, request) => {
		console.log(request.url());
		const headers = await request.allHeaders();
		route.continue({
			headers: {
				...headers,
				"x-custom-auth": "value",
			},
		});
	});

	await page.goto("https://zip.co/au"); // <-- this page has images loaded via CSS --background:url( URL )
});
```

**Describe the bug**

- Running the above snippet will result in `page.route` handler being called indefinitely causing `page.goto` being timed out.
- Only happens in `webkit`, `chrome` and `firefox` does not have the same issue.
- Looks like the affected resources are the ones that are loaded from CSS, for example: `<div style="--background:url(/static-assets/derived.row2@1x-13829144bfd179fbebbf-1.webp)" class="HVHMq jM2_2"></div>`. Other resources are not affected.

**Comment by dgozman** [comment]
@andresusanto Thank you for the issue, I can repro.

**Comment by yury-s** [comment]
The issue is that in webkit when network interception is enabled it disables caching for such css resources and the .webp file ends up being repeatedly loaded. This sounds wrong and we should fix it so that the resource is loaded only once. What I don't understand is why the navigation times out in your case. To my understanding it should complete but just slower.

I cannot reproduce such timeout with this example:

```html
<style>
      @keyframes JNDzq {
        0% { background-position: 0 0 }
        to { background-position: 100 0 }
      }
      div {
        --background: url(/background.png);
        background-image: var(--background);
        animation: JNDzq 1s linear infinite;
      }
 </style>
 <div>Yo!</div>
```
@andresusanto do you have an idea on why you app navigation can be timing out in such case? It also does not timeout if I abort all *.webp requests in the interceptor.
