### ISSUE TITLE
[Feature] Test tag annotation

### ISSUE THREAD

**Issue by mramos360** [microsoft/playwright#19160]
Instead of putting a test tag inside a test name, can we put it above a test declaration like:

```
@smoke
test('a test name', async() => {
});
```

instead of 

```
test('a test name @smoke', async() => {
});

```

It's a bit cleaner I reckon and no noise in the test name.

**Comment by dgozman** [comment]
@mramos360 Thank you for the issue! Playwright does not adopt decorators, because there is no real consensus about JS decorators between various parties like TC39, Typescript, Babel, etc. Once decorators are standardized, we'll consider features like this. For now, [decorators are in stage 3](https://github.com/tc39/proposal-decorators). Let me close this issue for now, and we can reopen or file a new one once decorators arrive.
