### ISSUE TITLE
[BUG] GitHub Authentication example doesn't work

### ISSUE THREAD

**Issue by leovarmak** [microsoft/playwright#1916]
**Context:**
- Playwright Version:  0.13.0 
- Operating System: Mac

**Describe the bug**
The Github authentication example that is provided in this repository does not work. I have attached a screenshot of the issue.

![image](https://user-images.githubusercontent.com/14135553/79990462-b602fd00-84ce-11ea-9644-ba4f2f9282cf.png)

**Comment by arjun27** [comment]
Thanks for reporting this @leovarmak. The example currently expects you modify the script for account credentials, and this error is thrown if you use the default empty credentials. Is that what happened? Having said that, you raise a good point and having examples that run out of the box is a valuable goal to have.

**Comment by leovarmak** [comment]
@arjun27 I get that error even when I provide the correct credentials. I have verified that I indeed login by turning off headless mode.

**Comment by arjun27** [comment]
Thanks for checking! What does it look like when you run the script in headful mode with `headless: false` as args to the `launch()` method calls?

**Comment by leovarmak** [comment]
This is what it looks like:

![image](https://user-images.githubusercontent.com/14135553/80004866-7ba25b80-84e0-11ea-924f-bd85be8ded79.png)

**Comment by arjun27** [comment]
Thanks for sharing - super helpful! The demo account that I've been using does not have any repositories, and so the script is using "Create repository" [to verify login](https://github.com/microsoft/playwright/blob/master/docs/examples/authentication.js#L53). This is not working for you since the GitHub UI looks different. Let me update the script for a better check.

![Screen Shot 2020-04-22 at 9 03 44 AM](https://user-images.githubusercontent.com/284612/80005244-2cc0db80-8478-11ea-8fc9-a9b804c4d61b.png)

**Comment by leovarmak** [comment]
Aha. Got it! I think we need to change the script so that it supports the majority of the people i.e already existing users. Totally up to you.
Let me know if you want a PR 😄
