### ISSUE TITLE
[Feature] Missing Assertion: toBeRequired()

### ISSUE THREAD

**Issue by JamShady** [microsoft/playwright#19194]
The [listed assertions](https://playwright.dev/docs/test-assertions) contain a number of boolean based attributes, e.g. disabled, checked, etc.

However, `required` is missing? There appears to be no way to test for whether an input field is required or not, just by virtue of a `required` attribute being present. The `toHaveAttribute()` assertion requires a second parameter for the value, and empty strings will still fail the test because Playwright will see a null, coersce it to an empty string (and affirm it matches) but still throw an error.

**Comment by mikeybinns** [comment]
`await expect(input).toHaveAttribute("required", "");` does work for me when the DOM looks like this: `<input type="text" required />`

However, I do agree that having a `toBeRequired` helper would be good, especially as other use cases for inputs like disabled and checked are covered.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
