### ISSUE TITLE
[Feature] Update docs for PNPM etc. users

### ISSUE THREAD

**Issue by fjeldsoe** [microsoft/playwright#19201]
Hi.

I just spent a couple of hours debugging why I got the "browserType.launch: Executable doesn't exist at ..." error.
I tried following the suggestion from the docs: "npx playwright install", but that didn't work.
Finally I remembered PNPM has it's own syntax for npx --> pnpm dlx, and then it all worked again.

It could be nice if the docs were updated to include other package managers.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
