### ISSUE TITLE
[Feature]: browser.currentPage() or similar way to access Pages

### ISSUE THREAD

**Issue by Taoli96** [microsoft/playwright#19232]
Get current page with Playwright is very important。Many users want this feature. example: user open many pages and  switch them。page.bringToFront() brings page to front (activates tab)。I want  to know what current page is page to front (activates tab) after user open many pages and  switch them .   
I find many people want this feature. Can you do it? Thank you!

**Comment by mxschmitt** [comment]
All the pages in Playwright are considered as active from a web api point of view. What is the end-to-end testing use-case of it?

**Comment by Taoli96** [comment]
> All the pages in Playwright are considered as active from a web api point of view. What is the end-to-end testing use-case of it?

yeah,I know All the pages in Playwright are considered as active. but  example  at a website, user may open many page,i want to test on front page, beacuse test need user participate in. I want to know what page is front  that user want to test. 
I think   context.currentPage() is very important.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
