### ISSUE TITLE
[Feature] Refreshing the page when in debug mode should re-start the test

### ISSUE THREAD

**Issue by pastelsky** [microsoft/playwright#19251]
Currently, when iterating on an integration test or a component test, it is natural to run playwright in `--debug` mode.

When doing so, if I hit a reload on the debug browser screen that loads the component / webpage, playwright runs into an inconsistent state.

1. For component tests, hitting reload means that the page after reload is blank as component mount is never called again.
2. For normal integration tests, I noticed that execution isn't reset.

Neither of these are great. Ideally, playwright might want to capture reload, and re-start the test. A similar behaviour is seen in other frameworks like cypress and is quite helpful for quick iteration.

I'm happy to submit a fix, in-case there's some guidance on where the fix will lie.

**Comment by aslushnikov** [comment]
@pastelsky we discussed this on a team meeting and we found this proposal very interesting, yet not a high priority for now.

**Comment by pastelsky** [comment]
Thanks for taking a look! I think this is a part of the larger story to make authoring and iterating on tests as fun as running it is, as stated by some of the other suggestions —

https://github.com/microsoft/playwright/issues/15014
https://github.com/microsoft/playwright/issues/7035

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
