### ISSUE TITLE
[Question] Java Playwright to return MutationRecord

### ISSUE THREAD

**Issue by anoop-qasolve** [microsoft/playwright#19345]
Hello, 

I have a requirement in a project where I need to return the Mutation Record to Java code. I have been trying to figure out how I can achieve this in java playwright. Here is code snippet. 

`String mutation = "var mutationObserver = new MutationObserver(function(mutations) {\n" +
					"  mutations.forEach(function(mutation) {\n" +
					"    console.log(mutation);\n" +
					"  });\n" +
					"});\n\n" +
					"mutationObserver.observe(document.documentElement, {\n" +
					"  attributes: true,\n" +
					"  characterData: true,\n" +
					"  childList: true,\n" +
					"  subtree: true,\n" +
					"  attributeOldValue: true,\n" +
					"  characterDataOldValue: true\n" +
					"});";
			
page.evaluate(mutation);`  

Above code dumps the MutationRecord object in console. Please let me know if there a way I could get the MutationRecord to Java from playwright. Also let me know if there is any better way to do it.

**Comment by anoop-qasolve** [comment]
I tried using BrowserContext.exposeFunction callback but couldn't get it up and running.

Also please let me know if this is right forum to ask these implementation queries.

**Comment by aslushnikov** [comment]
> Also please let me know if this is right forum to ask these implementation queries.

I'd recommend asking these kind of questions on either stackoverflow.com or https://aka.ms/playwright/slack. 

Answering your question here, you can't just get the MutationRecord from browser world to java world - you'll need to serialize mutation command to some simple javascript object first.

I'll close this for now since there's no action from Playwright team!
