### ISSUE TITLE
[Feature] Absorb @jscutlery/playwright-ct-angular

### ISSUE THREAD

**Issue by yjaaidi** [microsoft/playwright#19380]
Hi, we just created a new library to add Angular support for Playwright Component Testing.
Cf. [https://github.com/jscutlery/devkit/tree/main/packages/playwright-ct-angular](https://github.com/jscutlery/devkit/tree/main/packages/playwright-ct-angular)

We'll be happy to merge it in this repo.

**Comment by pavelfeldman** [comment]
Nice! Would you be willing to keep it up-to-date and consistent with the other frameworks? @sand4rt does a great job gardening other frameworks. If yes, please feel free to send a PR and CC me and @sand4rt !

**Comment by sand4rt** [comment]
Awesome! Let me know if there's anything i can do to help!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
