### ISSUE TITLE
[BUG] Firefox doesn't emulate the screen

### ISSUE THREAD

**Issue by Sue9445** [microsoft/playwright#19401]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Linux
- Node.js version: 16.6
- Browser: Firefox

**Code Snippet**

https://try.playwright.tech/?l=javascript&s=4sapx1j

**Describe the bug**

Firefox doesn't emulate the screen when the screen size is explicitly set and also window.matchMedia api doesn't return expected matches.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
