### ISSUE TITLE
[Question] Is it possible to run parallel tests on a Github action workflow?

### ISSUE THREAD

**Issue by lorinerosenberg1** [microsoft/playwright#19408]
When running my tests locally they by default run in parallel with 5 workers. However, on my Github Action Test build it automates to 1 worker and when explicitly setting to 5 workers on the playwright config the tests in CI fail.
I using the webServer to run my app in CI.
I am getting a timeout error when running the tests with explicitly set workers on CI.
Looking at the screenshots of the failures the screen is not loading so maybe the webserver is not up? Only 1 test passed.

Is it possible to run parallel tests with more than one worker in a Github Actions workflow using the webserver config?

This is my config with the explicitly set workers: 

    const config: PlaywrightTestConfig = {
      reporter: 'html',
      webServer: {
        command: 'yarn dev',
        url: 'http://localhost:8080',
        reuseExistingServer: !process.env.CI,
      },
      use: {
        headless: true,
        viewport: { width: 1440, height: 900 },
        ignoreHTTPSErrors: true,
        storageState: 'storageState.json',
        baseURL: 'http://localhost:8080',
        screenshot: 'only-on-failure',
        video: 'retain-on-failure',
      },
      workers: 5,
    }

**Comment by jfgreffier** [comment]
Do you have a CI env variable set to `true` ? It should be set to deactivate `reuseExistingServer`

**Comment by yury-s** [comment]
> However, on my Github Action Test build it automates to 1 worker and when explicitly setting to 5 workers on the playwright config the tests in CI fail.
> I using the webServer to run my app in CI.
> I am getting a timeout error when running the tests with explicitly set workers on CI.

You are pushing the github actions VM beyond its capacity with 5 workers. A hosted runner has only 2-core CPU (see [this page](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)) and playwright by default spawns roughly (# CPU cores) / 2 workers which in this case would be 1 worker. Spawning 5 workers is likely too much as it means starting 5 browsers in parallel. If you absolutely need to run them in parallel with such hardware configuration you should increase the test timeout to accommodate slower execution. We in general discourage that because running above capacity will inevitably lead to degrade performance with unpredictable delays and hence test timeouts.

If you want a better parallelism on a single github actions machine, you should consider running on [a larger runner](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners). Alternatively, you can split your tests into [shards](https://playwright.dev/docs/test-parallel#shard-tests-between-multiple-machines) and run them on a few standard machines but with 1-2 workers each.
