### ISSUE TITLE
[Feature] Global mask for images

### ISSUE THREAD

**Issue by gselsidi** [microsoft/playwright#19417]
Allow to global mask elements in config and inside test in test.use 

Sometimes it's useful while there are changes being made to the site to mask new elements ect, that you can update in the future, instead of masking elements at each individual snapshot step.

Then we can just call update-snapshots to update the baseline images with the new global masking we want applied.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
