### ISSUE TITLE
[Question] Why is running `playwright test --debug` pausing on page.goto? 

### ISSUE THREAD

**Issue by alexbjorlig** [microsoft/playwright#19425]
I'm running my playwright tests with `--debug`.

I would expect the playwright inspector to stop at `page.pause()`.

But it also seems to stop at `page.goto(...`.

Is this intended behavior?

<img width="1289" alt="Screenshot 2022-12-13 at 12 47 14" src="https://user-images.githubusercontent.com/9967422/207309800-b71d62f1-6359-4f0e-9e3f-b8bb2ed4942d.png">

**Comment by yury-s** [comment]
With --debug inspector will pause on the first Playwright API call (which happens to be page.goto in your case). You can do step-by-step execution after that or resume execution to make it continue all the way until the next page.pause().

**Comment by dgmp88** [comment]
Is there any way to turn this behaviour off? I use the command line and `page.pause()` a lot when creating tests, and sometimes with multiple contexts, so end up having to press 'resume' a couple of times with lag every time to get to my nearest `page.pause()`. Minor gripe, but would be great to skip through. Or maybe my workflow is strange?

Thanks for the awesome work, Playwright's fantastic!

**Comment by kingtaj** [comment]
I'd also appreciate the ability to disable the automatic pause at first API call.

**Comment by JenH11** [comment]
Yep. It's super annoying. I just want it to run to the page.pause or the VS Code breakpoint I've placed.

**Comment by sahilrajput03** [comment]
Yes, its annoying. I wish there was a way to disable this.

**Comment by kvart714** [comment]
@yury-s this question is still relevant...

**Comment by tbrodbeck** [comment]
+1 why is this closed? 🙈

**Comment by JontyMC** [comment]
> With --debug inspector will pause on the first Playwright API call (which happens to be page.goto in your case). You can do step-by-step execution after that or resume execution to make it continue all the way until the next page.pause().

@yury-s can you reopen this? it's really annoying

**Comment by msorens** [comment]
Another vote to re-open please!

**Comment by Westermann** [comment]
Yes, please.

**Comment by lolmaus** [comment]
This is a real problem to me that is killing Playwright's BDD experience.

Please reopen!

**Comment by cksstg** [comment]
Adding my vote.

**Comment by PiotrSiatkowski** [comment]
Quite often I run tests and go for a coffee if they take more time just to return and see it didn't even start :(

**Comment by chrift** [comment]
Cant believe this is still open! Can we remove this behaviour please! It's so strange.

**Comment by mscuthbert** [comment]
As a new-to-playwright from selenium user, I was super frustrated by this as well until Skn0tt's answer on #33353 let me know that `--debug` and `--headed` are similar but different interfaces into the same system, and that --headed is what we are all wanting.  

The reason there are probably so many of us in this camp is that when we're starting Playwright, there's a lot of docs pointing to setting PWDEBUG=1... before running a command, and then suddenly we're in beautiful headed+pausing mode. Where everything is great except the pausing.  How to switch from that command-env setting to passing --headed to Playwright is more of a mystery especially if the distance from the command line to the browser setup is far in your testing system (the way my Django setup was working, for instance).

It seems like it's a "clarify user understanding and add documentation" issue rather than a "add feature" issue (but these can be just as hard or harder to fix!).

### Python/Django Implementation

For anyone else using Django I had playwright set headless by reading django settings:

```python3
# my_app.playwright_test_base.py
from django.conf import settings

# add to the .launch() call:
sync_playwright().start().launch(
    headless=not getattr(settings, 'HEADED_TEST', False)
)
```

Set up a new test runner that can change settings.HEADED_TEST based on command line presence of
`--headed` or not (e.g. `python manage.py test my_app.tests --headed`)

```python3
# my_app.test_runner.py
from django.conf import settings
class HeadableDiscoverRunner(DiscoverRunner)
    @classmethod
    def add_arguments(cls, parser) -> None:
        super().add_arguments(parser)
        parser.add_argument(
            '--headed',
            action='store_true',
            help='Run Playwright tests in headed mode'
        )
    def __init__(self, *, headed: bool = False, **kwargs):
        super().__init__(**kwargs)
        self.headed = headed
        settings.HEADED_TEST = headed
```

and lastly in your config/settings.py file add:

```python3
TEST_RUNNER = 'my_app.test_runner.HeadableDiscoverRunner'
```

Hope this helps at least someone, and people using other languages and test runners can share their solutions.
