### ISSUE TITLE
Capturing ScreenShot using Page or Locator?

### ISSUE THREAD

**Issue by jpEngProd** [microsoft/playwright#19447]
f I want to capture screenshot of an element within the page using Xpath as selector.
Then which is the best option among these two?

```
//Using page.ScreenShotAsync()
var rect = await Locator("xpath={element_xpath}").BoundingBoxAsync();
var clip =  new Clip { X = rect.X, Y = rect.Y, Width = rect.Width, Height = rect.Height };
var options = new PageScreenshotOptions
{
FullPage = false,
Clip = clip
};
await Page.ScreenshotAsync(options)
```

Or 
```
//Using Locator.ScreenShotAsync()
await Locator("xpath={element_xpath}").ScreenShotAsync()

```
Which of them is more recommended in terms of consistent results[considering the page is getting rendered via a request]?

Asking this again as this was closed https://github.com/microsoft/playwright/issues/19432

**Comment by yury-s** [comment]
> Which of them is more recommended in terms of consistent results[considering the page is getting rendered via a request]?

Since you need to capture a single element (which can be identified with an xpath locator) the recommended way is to use [Locator.ScreeshotAsync](https://playwright.dev/dotnet/docs/api/class-locator#locator-screenshot):
```csharp
await page.Locator("xpath={element_xpath}").ScreenShotAsync()
```

Using `page.ScreenshotAsync()` with a `clip` would make sense if you want to capture an area which belongs to several DOM elements.

Does this answer your question?

> Asking this again as this was closed https://github.com/microsoft/playwright/issues/19432

Thanks for refiling and apologies that my original answer was not quite clear.

**Comment by jpEngProd** [comment]
Yes, It helps.
Thanks
