### ISSUE TITLE
[Question] Playwright with java vs with c#

### ISSUE THREAD

**Issue by fredericL-sigma** [microsoft/playwright#19494]
I need to follow some course with Playwright, as our company is using c# .net, I want to know if I follow a Playwright course with java, will the transition to c# be difficult.

Thank you

**Comment by yury-s** [comment]
The biggest difference between the two is that java API is synchronous while in C# it is asynchronous and you will need to use `await` in many places, other than that the functionality available in the languages is the same and difference are mostly due to different language syntax, so it should not be hard to transition from one to the other (all the main concepts like auto-waiting, locators etc will be the same).
