### ISSUE TITLE
[BUG] Test filter checks the entire path for matches

### ISSUE THREAD

**Issue by dudanian** [microsoft/playwright#19522]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Linux
- Node.js version: v16.17.1
- Browser: All
- Extra: [any specific details about your environment]

**Code Snippet**

```bash
npx playwright test home # all tests run because /home is in the path
```

**Describe the bug**
 
The cli test filter seems to be matching tests using the entire path, not the subset of the path starting from the `testDir` as I would expect. If I put any word in the path up to the `testDir`, like `home`, my username or the repository name, all tests are run.

**Comment by yury-s** [comment]
We've evaluated pros and cons of https://github.com/microsoft/playwright/pull/19900 and decided that without additional heuristics it will break some important scenarios. E.g. similar to `git log` it should work if you pass an absolute path as an argument and changing the matching login simply to match against relative path will break that.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
