### ISSUE TITLE
[BUG] document.referrer is empty in firefox if redirecting to a subdomain via location.href within page.evaluate

### ISSUE THREAD

**Issue by DerGernTod** [microsoft/playwright#19565]
**Context:**
- Playwright Version: 1.25.0
- Operating System: Windows
- Node.js version: 16.17.1
- Browser: Firefox

**Code Snippet**

```javascript
await page.goto("https://some.domain/some-path.html");
await page.evaluate(() => {
  location.href = "https://other.some.domain/some-path.html";
});
// wait until the page finished loading
const referrer = page.evaluate(() => {
  return document.referrer;
});
// due to referrer policy defaulting to strict-origin-when-cross-origin, path is stripped away
expect(referrer).toBe("https://some.domain/");
```

**Describe the bug**

For chromium and webkit, this test succeeds as you'd expect. For firefox, the `document.referrer` is just an empty string. When running the browser manually, it works fine in both normal and private mode.

Note that calling `page.goto(...)` sets the referrer _always_ to an empty string - imho this is working as expected, as it's like opening a new tab.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
