### ISSUE TITLE
[Feature] Expose request feature globally

### ISSUE THREAD

**Issue by Meemaw** [microsoft/playwright#19587]
Would be great if some fixtures (e.g `request`) would be exposed globally. Currently, one has to pass it around the [POM](https://playwright.dev/docs/pom) and utility functions to call it which complicates the method/class signatures.

Would be nice if we could do something along these lines from anywhere in the code:

```js
import { getRequestFixture } from `@playwright/test`

const request = getRequestFixture()
request....
```

**Comment by pavelfeldman** [comment]
Fixtures are deeply integrated with the test lifecycle. They operate on the test-scoped entities such as context, page, etc. There is a global request object that you can use though, it is a part of the Playwright library, so you can use it anywhere you like:

```js
import { request } from '@playwright/test'
```

See https://playwright.dev/docs/next/auth#sign-in-via-api-request for the example.

**Comment by Meemaw** [comment]
Ah, missed that. Is this global request object also traced so the requests are seen in the playwright trace viewer?

**Comment by pavelfeldman** [comment]
You would need to start/stop tracing yourself on this request context, because testing harness does not do it for you, you are now operating on the library level. Unfortunately, we did not expose tracing object on the request context and did not document it. I'll do it now, as a workaround you could do context._tracing.start() context._tracing.stop(), this tracing object is of type https://playwright.dev/docs/next/api/class-tracing.

**Comment by Meemaw** [comment]
Yeah, main reason for using it in our case would be the tracing that the `request` fixture provides out of the box. I would hope there would be an our of the box way for the global `request` object to do that as well.

**Comment by yury-s** [comment]
>  Yeah, main reason for using it in our case would be the tracing that the request fixture provides out of the box. I would hope there would be an easy for the global request object to do that as well (hopefully without having to trace it ourselves).

The global request does pickup tracing settings from the test config today. So if you set `trace: 'on'` in your playwright.config.ts, the following request will show up in the trace:

```ts
import { test, expect, request } from '@playwright/test';

test('test', async ({ }) => {
  const req = await request.newContext();
  const r = await req.get('https://playwright.dev/');
  expect(r).toBeOK();
  expect(1).toBe(2);
});
```
Does it work for you?

**Comment by Meemaw** [comment]
@yury-s should we create a new context for each request?

**Comment by Meemaw** [comment]
Ping @yury-s on the above question 🙏

**Comment by jquinterot** [comment]
Good day first I want to say thanks for the awesome work!, I only have two suggestions or desired features, the first one is that would be nice to have a way to run our tests matching a test pattern, for example inside the tests folder I could have other folders like component1/test.ts and other like component2/test.ts having this would be great that playwright can run the tests located on these folders by something like tests/**/*.ts or a patttern that recognize the tests on the folders having this we can organize our tests even better that have all the tests on the tests folder and start looking what is doing everyone, and the other will be about the visual comparison, to have a way to recognize that if there is no base image create it but not fail, just say base line created and  if there is already a image just do the comparison, having this the tests wont fail on a ci/cd pipeline each time and id there is already images will just do the comparison, well this is the only thing I can think so far, thank you for reading this and hope the test match can be a reality some day due to test runners like jest and mocha have it but is sad to try to use other runners and lose awesome features like the UI mode, code gen  and all usefull things from playwright runner. thank you again and have a nice day :D

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
