### ISSUE TITLE
ERROR: Playwright does not support chromium on mac13-arm64

### ISSUE THREAD

**Issue by sevenyang129** [microsoft/playwright#19586]
I encountered an error in trying to install chromium on MacOS 13.1, so the follow-up content cannot be carried out. Is there any solution now?
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/42111030/208617927-60ac145a-fe48-4991-a48d-c236630855bc.png">

**Comment by mxschmitt** [comment]
Which Playwright version are you using?

**Comment by sevenyang129** [comment]
> Which Playwright version are you using?
> 
> 你用的是哪个版本的剧作家？

playwright@1.29.0

**Comment by mxschmitt** [comment]
There is no Playwright 1.29 for Python. How can that be?

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by uksurd88** [comment]
I have the same problem, did fresh install many times and it finished successfully. I can create a new issue, if that works better. Thanks

`npm playwright --version
8.19.2`

Trace
`2023/02/03 15:21:07 Downloading browsers...
Failed to install browsers
Error: Failed to download chromium, caused by
Error: ERROR: Playwright does not support chromium on mac13-arm64`

**Comment by mxschmitt** [comment]
Please file a new issue @uksurd88
