### ISSUE TITLE
[BUG] copy paste working locally but not in the official docker image

### ISSUE THREAD

**Issue by monika-ibovnik** [microsoft/playwright#19611]
**Context:**
- Playwright Version: 1.29.0
- Operating System: Mac
- Node.js version: 16
- Browser: Chromium

**Code Snippets**
This code sandbox is more or less what our page does: 
[sandbox](https://codesandbox.io/s/reverent-mayer-4qpn52?file=/src/App.tsx)

This is the repo with an exemplary test that fails in docker:
[repo](https://github.com/monika-ibovnik/playwright-copy-paste-test)

**Description**

I ran into a problem with the clipboard events in chromium in the docker image. In our application, we use keyboard shortcuts Meta+C and Meta+V (or with Control for the docker image). It looks like the chromium in docker doesn't allow my page to access clipboard. Could you please give me a hint how to fix it?

What the page does is: on copy keyboard shortcut it sets some data to the clipboard. On paste it will be read from the clipboard and inserted. An element with selector `[data-test=pasted-text]` should appear.

The url to the sandbox is already hardcoded in the configs, you can just pull the github repo and run the test.
If I run it locally it works with no problems, but in the docker the `clipboard.getData()` returns nothing and the test fails.

We also have some tests in which we write mocked copy data directly into navigator using page.evaluate(). Those work with no problem, that's why we assume it's an issue with chrome permissions in the image for the page itself and not playwright.

Thank you for your help!

**Comment by romankryzhevskykh** [comment]
any news on the problem or maybe you have some workaround?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by monika-ibovnik** [comment]
Update from my side: I revisited the issue after 2 years. After updating playwright to latest version (at this point it's 1.44.0) the copying and pasting in docker image works. I updated my example repo, the test passes now.
