### ISSUE TITLE
[BUG] Only click actions are saved in trace when using codegen

### ISSUE THREAD

**Issue by xiang-deng** [microsoft/playwright#19735]
**Context:**
- Playwright Version: python playwright==1.29.0
- Operating System: Linux
- Node.js version: [e.g. 12.22, 14.6]
- Browser: Chromium

**Code Snippet**

```bash
playwright codegen \
    --save-trace .. \
    --save-har .. \
    --save-storage .. \
    --output .. \
    --target python-pytest \
    ${URL}
```

**Describe the bug**

When saving trace with codegen, only clicks are saved in the list of actions. But the output script is correct and contains other actions such as fill input fields.

**Comment by dgozman** [comment]
I can repro - not seeing `fill` actions in the trace.

**Comment by xiang-deng** [comment]
Noticed another inconsistency between the generated code and the recorded trace. On [imdb.com](https://www.imdb.com/chart/top/?ref_=nv_mv_250), clicking on one list item will generate a goto action in the code, but the recorded trace is correct with the click action.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
