### ISSUE TITLE
[BUG]Getting error in Webkit when running from VS code Extension

### ISSUE THREAD

**Issue by soumya-kar** [microsoft/playwright#19789]
**Context:**
- Playwright Version:1.29.1
- Operating System: Windows
- Node.js version:v16.13.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] WebKit
- Extra: [any specific details about your environment]

Pre-requisites:
Create a copy of example.spec.ts and just rename the test name
Create another test in second file (I have just copied the same test and updated the test name)
![image](https://user-images.githubusercontent.com/57455260/209997864-2f223bce-64da-467c-8475-0de8f72cb1fe.png)

Steps to reproduce:
1. Select Default Profile as Webkit
![image](https://user-images.githubusercontent.com/57455260/209997232-242b8caa-47e4-4641-9a38-79d4c32993aa.png)
2. Click on Run all icon
3. Notice that, first test passed but second and third tests failed
![image](https://user-images.githubusercontent.com/57455260/209997639-771df1c5-4e24-4164-8b55-881eae417ca5.png)
Error details:
![image](https://user-images.githubusercontent.com/57455260/209997697-dfe1172d-7f0b-49a6-abda-e962545cbfae.png)

**Comment by mxschmitt** [comment]
I'm unfortunately not able to reproduce. Could you provide a step-by-step guide to reproduce it and test after that if it occurs for you again? You can use this boilerplate:

1. `npm init playwright@latest mypwtest1` (all defaults, just press enter)
2. `code mypwtest1` (this opens Visual Studio Code)
3. ...

**Comment by debs-obrien** [comment]
I was able to reproduce following steps above by duplicating example spec file, you can call it anything and then duplicating the test within that file.

simplifying the test to just first two lines and problem persists.  If you switch to chrome tests run fine. sometimes running one test works but after a while you get the same error if running one test or both tests in that file.

Clicking close all browsers fixes it and then re running tests works fine however after a while error happens again (only on webkit)  and then sometimes clicking close all browsers doesn't fix it and test fails yet passes if you run them individually. changing test content also makes it fail

sometimes this error is given: browser._newContextForReuse: Target closed

seems to be a bug only on vs code extension as tests pass on cli.

<img width="695" alt="Screenshot 2023-01-03 at 19 50 24" src="https://user-images.githubusercontent.com/13063165/210430754-79e004fa-e593-4afc-b4f1-319a24f4867c.png">
<img width="721" alt="Screenshot 2023-01-03 at 19 58 18" src="https://user-images.githubusercontent.com/13063165/210431956-01b6e3ef-eb9a-415e-95b6-d584f2bece16.png">

**Comment by debs-obrien** [comment]
repro to reproduce. make sure you run tests from the run all tests button in vscode and run more than once

https://github.com/debs-obrien/reproduce-bug-webkit

**Comment by dgozman** [comment]
Investigation notes:

- service worker calls `importScripts('...script.js')`;
- server returns `script.js` with `content-length` longer than the actual content;
- browser waits for more bytes, while we call `ServiceWorkerRegistration.unregister()`;
- while `importScript` is in progress, unregistration does not happen, because [it is queued](https://w3c.github.io/ServiceWorker/#schedule-job-algorithm);
- Chromium stops waiting for more bytes after 5 seconds and resolves;
- Firefox stops waiting for more bytes after 5 seconds and resolves;
- Webkit keeps waiting for more bytes for at least 3 minutes, so we timeout after 30 seconds.

Overall, seems like an upstream issue in WebKit. However, Chromium/Firefox behavior is also not ideal for us, because each reuse takes 5/6 seconds between tests.
