### ISSUE TITLE
[Question] How do I store a dynamic value from a specific column inside a table using playwright?

### ISSUE THREAD

**Issue by MikaTsur** [microsoft/playwright#19787]

**Comment by aslushnikov** [comment]
@MikaTsur you should use locators to locate the element on the page, and then fetch it's text using the [`locator.textContent()`](https://playwright.dev/docs/next/api/class-locator#locator-text-content) method!

All in all, though, this sounds more like a general programming question rather than playwright-specific stuff. I'd recommend asking this on StackOverflow, or on our discord channel - https://aka.ms/playwright/discord
