### ISSUE TITLE
[Question] maxFailure doesn't work as expected

### ISSUE THREAD

**Issue by kamelbou** [microsoft/playwright#19821]
Hi everyone,

I set the maxFailure params to 40 `maxFailures: process.env.CI ? 40 : 0` in my config file and in my report, run stops at 20 failed runs.
Am I doing something wrong ?

Thanks a lot

**Comment by mxschmitt** [comment]
Can you share your full config with us? The best would also be a small project which we can run locally.

**Comment by kamelbou** [comment]
Below our config file:

```js
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';
import dotenv from 'dotenv';

const path = require('path');
//path.join(__dirname, '/tests')

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
//require('dotenv').config();
dotenv.config({override: false});
/**
 * See https://playwright.dev/docs/test-configuration.
 */

const config: PlaywrightTestConfig = {
  testDir: './e2e',
  /* Maximum time one test can run for. */
  timeout: 30 * 1000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 5000
  },
  /* Run tests in files in parallel */
  fullyParallel: false,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 1 : 0,
  /* If we reach 40 fails playwright stops the run as we have too many fails*/
  maxFailures: process.env.CI ? 40 : 0,
  /* Run parallel tests on CI. */
  workers: (process.env.CI && !Number.isNaN(Number(process.env.PLAYWRIGHT_WORKERS))) ? Number(process.env.PLAYWRIGHT_WORKERS) : 1,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    ['dot'],
    ['html', {open: "never"}],
    ['json', {  outputFile: './playwright-report/test-results.json' }]
  ],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    launchOptions: {
      slowMo: 200,
    },
    trace: 'retain-on-failure',
    ignoreHTTPSErrors: true,
    headless: true,
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://localhost:3000',
  },
  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },

    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
      },
    },

    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
      },
    },
  ],
  /* Folder for test artifacts such as screenshots, videos, traces, etc. */
  // outputDir: 'test-results/',
};

export default config;
```
Results summary:
All 252 Passed 158 Failed 21 Flaky 0 Skipped 73

In two other project with a similar config file, Failed is equal to 20.

As we handle sensitive data, I'm not able to share the project.

**Comment by pbielenda** [comment]
What happend if you change retries value - for example to 0?

**Comment by JonahKK** [comment]
It is because of the retry. If one test is retried and fails for the second time it is counted as 2 fails. So with retry: 1 and maxFailures: 40 the execution will stop at 20 failed tests.

**Comment by mxschmitt** [comment]
Looks like its answered, so closing for now.

**Comment by zeptonaut** [comment]
This... doesn't seem like a terribly sensible behavior. It makes it so that no matter how many failures you set this to, that number is likely to become obsolete as you write more tests. ("10 failures" with a retry count of 2 is a lot if you have 10 tests: it's not very many once your app hits 1000 tests).

In my opinion, this should either:

- Count each test as at most one failure or
- Allow some sort of percentage setting (like CPU count) - e.g. "25%" to say "if 25% of tests fail, bail out"

**Comment by Kristoffer88** [comment]
I would like to stop the test if any test uses all it's retries.

**Comment by cgutierrezpa** [comment]
I agree with @Kristoffer88, that would be the ideal scenario. Any way we can achieve that behavior? @mxschmitt 
I wouldn't want the retries to add up to the `maxFailures` because we don't consider a test as "broken" until all retries are exhausted, as we want to assume there would be some level of flakiness within the test suites

**Comment by Kristoffer88** [comment]
This is still a issue for us, our azure devops pipelines are running 50+ unnessasary tests, if the first test fails all it's 3 retries.

**Comment by cgutierrezpa** [comment]
@mxschmitt any chance of re-opening the issue? I think this configurability of counting retries or not is worth considering, as for example, let's say that we want to stop running tests when one of them fails, but there are some flaky tests, and we provide 2 retries per test. This means that a flaky test can fail once and pass in the first or second retry, but setting `maxFailures: 1` would stop the whole run without retrying even once, which is undesired

As a workaround, I've seen that we can control these failed reruns with the information that is passed to the hooks of a custom reporter, like
```javascript
async onTestEnd(test: TestCase, result: TestResult) {
  // Continue only the test exhausted all retries
  if (result.retry < test.retries) return;
  ...
}
```
Any way we can stop/control the execution of playwright within a reporter so that we provide this lower-level control of the fail-fast functionality ourselves?

**Comment by lewis-jackson-bots** [comment]
It looks like this was fixed in https://github.com/microsoft/playwright/pull/32533, but wasn't mentioned in the release notes?
