### ISSUE TITLE
[BUG] Component tests should append to ctViteConfig instead of overwriting

### ISSUE THREAD

**Issue by WesleyYue** [microsoft/playwright#19829]
Playwright overwrites [entire sections of ctViteConfig](https://github.com/microsoft/playwright/blob/b695478840390a3974196c7578775d05fbc87a15/packages/playwright-test/src/plugins/vitePlugin.ts#L98) without warning, which leads to [non-obvious behaviour](https://github.com/microsoft/playwright/issues/14295#issuecomment-1149124559) as to why these configs don't work when set.

Instead, it should merge with the user provided ctViteConfig (and possibly warn about conflicts?)

[Current workaround](https://github.com/microsoft/playwright/issues/14295#issuecomment-1369306887) is to write your own plugin that modifies the config instead of feeding into ctViteConfig directly.

**Comment by sand4rt** [comment]
Related to: https://github.com/microsoft/playwright/pull/19693#pullrequestreview-1231074693

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
