### ISSUE TITLE
[Feature] Add .allInputValues() function to Locator

### ISSUE THREAD

**Issue by ipatalas** [microsoft/playwright#19832]
Hi, we have a scenario when we need to read multiple input values. There is an easy way to do that for text contents (`.allTextContents()` or `. allInnerTexts()` depending on use case) but there is no good counterpart for input fields available.

Thanks to `.all()` added in 1.29 this can be either done in a loop or using something like this:
```ts
const allValues = await Promise.all((await page.getByRole('...').all()).map((item) => item.inputValue()))
```

This however is not very friendly. Of course this could still be `.evaluateAll<string[], HTMLInputElement>((item) => item.map((i) => i.value))` but then we have to fall back to "low-level" DOM API which I'd rather avoid.

A simple helper like `.allInputValues()` could do the trick and make this operation super simple. `.inputValue()` is good but only works for a single input.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
