### ISSUE TITLE
Should Playwright support sources with the mts extension?

### ISSUE THREAD

**Issue by doberkofler** [microsoft/playwright#19834]
Should Playwright support sources with the mts extension? I am using the new TypeScript esm support in the test pipeline but cannot switch the overall project to esm.

**Comment by mxschmitt** [comment]
If it works with TypeScript out of the box, then we should also add support for it. Since importing e.g. helper functions should work out of the box.

**Comment by mxschmitt** [comment]
What do you tests look like? Are you migrating your tests from CJS to ESM or do you have non-test related files which keep you from migrating?

**Comment by doberkofler** [comment]
I'm basically unable to to switch the package.json flag to ESM and migrate to ESM on a file by file basis.
I can work around this restriction and was mostly interested to understand if Playwright should support this.
PS: After intensive testing, I'm now slowly migrating a very large test suite from selenium to Playwright and it is an absolute pleasure to work with Playwright.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by ryan-mcginty-alation** [comment]
Also would like to see support for this
