### ISSUE TITLE
[Question] expect().toBeTruthy may cause false positive test results

### ISSUE THREAD

**Issue by denkorz** [microsoft/playwright#19860]
```typescript
class SomePageWithTable{
   async isRowAwailableCustomMethod(col1Val: string, col2Val: string): Promice<boolean>{
      let rowFound = false;
      // await logic
      return rowFound;
   }
}
```
```typescript
expect(await somePageWithTable.isRowAwailableCustomMethod(column1Value, column2Value)).toBe(true); // works fine

expect(await somePageWithTable.isRowAwailableCustomMethod(column1Value, column2Value)).toBeTruthy(); // works fine

expect(somePageWithTable.isRowAwailableCustomMethod(column1Value, column2Value)).toBe(true)(); // fails as we got a promise object instead of TRUE (that is expected behavior)

expect(somePageWithTable.isRowAwailableCustomMethod(column1Value, column2Value)).toBeTruthy(); // false positive result!!
```

So if `await` is forgotten, `toBeTruthy()` might be dangerous. Especially because it looks similar to a simple true check from another test frameworks, which is not suppose something except boolean true to be true.

**Comment by mxschmitt** [comment]
Playwright uses [expect](https://jestjs.io/docs/expect#tobetruthy) from the Jest framework as foundation and extends it with some additional matchers. If you don't use `await`, its just a `Promise` which by definition is truthy. I totally understand that this might be confusing for users, but we can't change it since it would a breaking change and we would then be different to normal expect library.

You should anyways never do manual isVisible() checks, and always use [web-first assertions](https://playwright.dev/docs/test-assertions) or [toPass ](https://playwright.dev/docs/test-assertions#retrying) since they auto-retry.

**Comment by denkorz** [comment]
> You should anyways never do manual isVisible() checks, and always use [web-first assertions](https://playwright.dev/docs/test-assertions) or [toPass ](https://playwright.dev/docs/test-assertions#retrying) since they auto-retry.

In this exact case column values are inputs without value on DOM so I have to iterate rows and call `inputValue()` on cell. Is there a better way here?

**Comment by mxschmitt** [comment]
Wrapping it inside toPass would be the best to make it more reliable: https://playwright.dev/docs/test-assertions#retrying

**Comment by mxschmitt** [comment]
Closing as per above, please re-file for further questions.
