### ISSUE TITLE
[Question] How :text-matches should works ?

### ISSUE THREAD

**Issue by kamelbou** [microsoft/playwright#19911]
Hi All,

I have the following element:

```html
<svg class="label" width="185.7001953125px" height="65.0999755859375px">
<rect class="label__handle" width="181.7001953125" height="65.10000228881836" style="fill-opacity: 0; cursor: move; pointer-events: all; stroke: none; min-width: 16px; min-height: 14px;" transform="translate(2, 0)">
</rect>
<text class="label__content-text" fill="#EF983C" style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;" x="8" y="18.5">
<tspan x="8" dy="0em">My measure</tspan>
<tspan x="8" dy="1.2em">Mean: 986.66 s</tspan>
<tspan x="8" dy="1.2em">Area: 1402.62±63.90 mm2</tspan>
</text>
</svg>
```

I can have multiple elements in the DOM and I want to check that one of them contains Area: 1402.62±63.90 mm2.

I did something like that:

```js
measurementSelector = ` .label text.label__content-text :text-matches("/^Area.*mm2$/")`;
expect(page.locator(measurementSelector)).toBeTruthy();
```

To be sure that it is working as expected I tried to replace `mm2` by `toto`:

```js
measurementSelector = ` .label text.label__content-text :text-matches("/^Area.*toto$/")`;
expect(page.locator(measurementSelector)).toBeTruthy();
```

I was expecting to have `false` as we don't have toto in the DOM but the test is Pass.

How it can be possible ? Something wrong in how I'm using `:text-matches` ?

Thank you

**Comment by mxschmitt** [comment]
`page.locator('...')` is always true, since it always returns a Locator which is truthy. This does not do any calls to the browser, only assertions, click, fills, etc. do calls to the browser and actually check or do something.

What you want to have instead is the following:

```js
await expect(page.locator('.label text.label__content-text')).toHaveText(/^Area.*mm2$/);
```

See here: https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-text

This also retries automatically what reduces flakiness.
