### ISSUE TITLE
waitForNavigation is not working. Have wrapped it around Promise without success

### ISSUE THREAD

**Issue by raghou** [microsoft/playwright#19922]
Hi Team...Below code does not wait for the page to navigate completely. No error is thrown as blank array is assumed for the last statement. 

```ts
const {test,expect}=require('@playwright/test');

test('locatorsTest', async({browser})=>
{
const brw = await browser.newContext();
const pg = await brw.newPage();

await pg.goto('http://XYZ/Tenant1LCMConsole/#/login');
await pg.locator("[name='UserName']").type('XYZ');
await pg.locator("[type='password']").type('XYZ');


await Promise.all([
    pg.waitForNavigation({ timeout: 5000 }),
 pg.locator("[value='Login']").click(),
])


console.log(await pg.locator(".campaign-title span").allTextContents());
}
)
```

**Comment by raghou** [comment]
Thanks for the response.  There are 4 elements matching the locator provided. As there are more than 1 element as the expected result, toHaveText will error out.

**Comment by mxschmitt** [comment]
You can do .first() to get the second or could you elaborate more on which of the elements you want to assert?

```ts
const locator = page.locator('.campaign-title span');
await expect(locator).toHaveText(['welcome', 'to', 'the', 'platform']);
```

You can also do something like this, which would compare each of the elements to the matching elements of the page (4).

**Comment by raghou** [comment]
There are 4 elements matching locator ('.campaign-title span'). Lets say they are Red Blue Green White. And this could dynamically change. So if i use toHaveText, i would be hard coding to check of specific values. Once i login, i just want to print all the elements which match the locator ('.campaign-title span'). Today it is 4 elements and tomorrow it could be 5. Hence tried waitForLoadState with value 'networkidle' but it did not help. Then used Promise.all as described above. But that too is not working.

**Comment by raghou** [comment]
const locator = pg.locator('.campaign-title span').nth(0);
await expect(locator).toBeVisible();
console.log(await pg.locator(".campaign-title span").allTextContents());

The above code works without any hard coded values. But i am trying to understand why Promise.All did not work. It would be of help if you can guide me on it.

**Comment by aslushnikov** [comment]
> The above code works without any hard coded values. But i am trying to understand why Promise.All did not work.

@raghou the `promise.all` pattern you'd like to understand is this one from your first comment:

```ts
await Promise.all([
  pg.waitForNavigation({ timeout: 5000 }),
  pg.locator("[value='Login']").click(),
]);
```

As you say in the first comment, you want this snippet to wait for the page to "complete navigation":

> Below code does not wait for the page to navigate completely.

However, your notion of "complete navigation" assumes there are some elements on the page. Whereas the `waitForNavigation` will complete once the [`"load"` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) is fired. In the modern web, pages are highly dynamic, so they do lots of work after the "load" event, and thus the elements you expect to see appear some time later.

In fact, this whole behavior is the reason why we recommend using locators with built-in auto-waiting instead of relying on `"load"` event.

I hope my answer clarified things for you! Feel free to file new issues if you think we still can be helpful.

**Comment by raghou** [comment]
Thank you for the response aslushnikov.
