### ISSUE TITLE
[BUG] Test Explorer filter does not work with un-opened files

### ISSUE THREAD

**Issue by andschub-ms** [microsoft/playwright#19972]
**Context:**
- Playwright Version: "@playwright/test": "^1.29.2"
- Operating System: Windows 10
- Node.js version: v18.13.0
- Browser: All
- Extra: Latest VS Code 1.74.2

## System:
 - OS: Windows 10 10.0.19044
 - Memory: 7.02 GB / 15.93 GB
## Binaries:
 - Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD  
 - npm: 3.9.0 - C:\Program Files\nodejs\npm.CMD   

**Setup**

I copied the example.spec.ts file 1000 times, so each is named example.1.spec.ts, example.2.spec.ts, etc... pasting the first 10 records for example:
```
copy example.spec.ts example.1.spec.ts
copy example.spec.ts example.2.spec.ts
copy example.spec.ts example.3.spec.ts
copy example.spec.ts example.4.spec.ts
copy example.spec.ts example.5.spec.ts
copy example.spec.ts example.6.spec.ts
copy example.spec.ts example.7.spec.ts
copy example.spec.ts example.8.spec.ts
copy example.spec.ts example.9.spec.ts
copy example.spec.ts example.10.spec.ts
```

**Describe the bug**

When you go to the test explorer tab, and try to filter by a test keyword, such as "link," it returns no results unless you either open the file manually in VS Code, or example the tree view manually. 

![image](https://user-images.githubusercontent.com/19399310/211408083-84f96468-686d-4c58-8cd0-b1db485f3d61.png)

After clicking one file manually:

![image](https://user-images.githubusercontent.com/19399310/211409077-22c22bf5-64ca-46d6-ac9c-7bf4cffd3b16.png)

This bug makes the test explorer not useful if you have a large codebase and would like to filter specifically by a test by its name rather than by its file. The behavior to filter by test name is supported in Visual Studio test explorer.

**Comment by aslushnikov** [comment]
I can repro; we discussed this on a team meeting and it looks like we can try fixing this. Thanks for filing!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
