### ISSUE TITLE
[Doc/feature request] Installing trace viewer on static host

### ISSUE THREAD

**Issue by jakajancar** [microsoft/playwright#20008]
It would be great if it was supported/documented how to install the trace viewer to a static host like `trace.playwright.dev`.

It appears copying `node_modules/playwright-core/lib/webpack/traceViewer` kinda works, but `manifest.webmanifest` is missing, and perhaps some other things.

**Comment by aslushnikov** [comment]
@jakajancar what would be the use case? Why doesn't `https://trace.playwright.dev` cover your needs?

**Comment by LongLiveY96** [comment]
> @jakajancar what would be the use case? Why doesn't cover your needs?`https://trace.playwright.dev`

Deploying trace viewer locally is a way to boost efficiency, in our company, a lot of scripts are executed on virtual machines and there is a mechanism to move the generated report files to a static resource server so that users can implement online viewing of the report files, overall it is good to use, however it is not as good as viewing scripts locally via npx playwright show- report view script, however, it is not possible to view the report from the report via a path like this: http://ip:9323/trace/index.html?trace=http://ip:9323/data/11f755e0ea915d5f8c09eff8d11d1977819e965b.zip Jumping to the trace viewer in the report, the console displays the following error and nothing on the page.

![image](https://user-images.githubusercontent.com/23394317/211699093-e16b65e7-57c7-44e9-9dac-bad3fa7ba99d.png)

I would like to know how to achieve local access to the trace file on the server.
This screenshot may help locate the problem.
![image](https://user-images.githubusercontent.com/23394317/211699529-291e90c2-db36-47ee-a9ec-33b2d0eb8528.png)

**Comment by aslushnikov** [comment]
Thank you all for the comments.

We discussed this on a team meeting today and decided that this falls outside of the scope for the project.

**Comment by aslushnikov** [comment]
> Out of curiosity, how do you guys deploy and run trace.playwright.dev?

I won't disclose any details regarding the process & deployment since these are internal. However, as a workaround, you can scrape the trace.playwright.dev and re-deploy its sources as you wish.
