### ISSUE TITLE
[BUG] When launching with debug, "Pick locator" should work

### ISSUE THREAD

**Issue by baptisteArno** [microsoft/playwright#20003]
When launching a test in debug mode, with "Show browser" off. Pick locator should still work.

**Comment by segevfiner** [comment]
It would definitely be nice to be able to pick a locator in a browser opened from debug mode.

**Comment by segevfiner** [comment]
Actually... it seems to work with "Show browser" ticked even when running tests in debug. It doesn't work with it unticked and the headed browser from debugging a test.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
