### ISSUE TITLE
Tests fails whenever there is a new version out there.

### ISSUE THREAD

**Issue by devnigam24** [microsoft/playwright#20010]
I have been getting these errors whenever there is a. new version released.

```
Running 1 test using 1 worker
  1) [chromium] › end-to-end.spec.ts:167:5 › test ==================================================

    browserType.launch: Executable doesn't exist at /Users/dnigam/Library/Caches/ms-playwright/chromium-1040/chrome-mac/Chromium.app/Contents/MacOS/Chromium
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝

  1 failed
    [chromium] › end-to-end.spec.ts:167:5 › test ===================================================

  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.
```
Moreover, I have been running the tests in CI pipelines as well, and that also fails for the same reason

```
Running 1 test using 1 worker

  1) [chromium] › team-hub.spec.js:6:7 › TeamHub page  › should load team hub correctly ============

    browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1041/chrome-linux/chrome

    ╔══════════════════════════════════════════════════════════════════════╗

    ║ Looks like Playwright Test or Playwright was just updated to 1.29.2. ║

    ║ Please update docker image as well.                                  ║

    ║ -  current: mcr.microsoft.com/playwright:v1.28.1-jammy               ║

    ║ - required: mcr.microsoft.com/playwright:v1.29.2-jammy               ║

    ║                                                                      ║

    ║ <3 Playwright Team                                                   ║

    ╚══════════════════════════════════════════════════════════════════════╝

```

I have various packages and plugins roaming around In my domain that get affected by it. I want to use version `1.29.0` for all of them. How can I make the test runner ignore these checks.

Thanks!

**Comment by mxschmitt** [comment]
Looks like you are running inside Docker, do you have your Docker image pinned? Which one are you using?

See here for more information: https://playwright.dev/docs/docker

**Comment by aslushnikov** [comment]
@devnigam24 also, have you tried running the `npx playwright install` as the error suggests?

**Comment by irharrier2** [comment]
We experience the exact same issue with our docker image. Each Playwright has a pinned version of browser, which makes it not compatible with any other Docker image version except the exact one. 

A fix would be nice from Playwright team but that seems very unlikely (unfortunately they are dismissing a lot of issues and feature request)

so the next best thing is that before you run the test, make sure you run npm install playwright@latest (or the exact version). This way you can avoid the version mismatch.

**Comment by aslushnikov** [comment]
@irharrier2 We recommend everybody to pin docker container version and update docker container whenever the Playwright gets updated. 

https://www.youtube.com/watch?v=6vV-XXKsrbA&list=PLQ6Buerc008fTzmUIPkPo3Eis0vjx7ykn&index=10&t=21s

**Comment by irharrier2** [comment]
@aslushnikov that solution won’t work with a lot of scenarios in an enterprise. 

For us for example, it is not possible to use Playwright Docker directly in project configuration but is defined as agent label.  That means that this method that you are mentioning needs to be communicated to the whole organisation each time there is a Playwright update.  
So we are using the latest + npm install playwright@latest

In reality, organisations are using your product in a different way that you expect due to restrictions and processes.

**Comment by aslushnikov** [comment]
> In reality, organisations are using your product in a different way that you expect due to restrictions and processes.

@irharrier2 fair enough.

> A fix would be nice from Playwright team but that seems very unlikely

@irharrier2 What kind of a fix would work for you then?

**Comment by irharrier2** [comment]
@aslushnikov 
A flag that allow Playwright to ignore browser version and use the browser that is already present in the ms-playwright folder.
For example:
/ms-playwright/chromium-XXXX/chrome-linux/chrome

**Comment by aslushnikov** [comment]
> A flag that allow Playwright to ignore browser version and use the browser that is already present in the ms-playwright folder.

@irharrier2 you can organize this yourself by passing the [`executablePath`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-executable-path) option to launch whatever browser you'd like.

However, we **strongly advise against this approach** since there's no guarantee that new Playwright works with the old browser versions. (If you're curious to learn why, feel free to check out the [playwright internals overview](https://youtu.be/PXTspGn1im0?t=54))

So all in all, the approach you're currently taking (e.g. `npx playwright install --with-deps`) is a proper way to solve it.

**Comment by irharrier2** [comment]
@aslushnikov yes, I am very much aware of executablePath options, but that doesn't solve the problem as I need to still orchestrate a change within organization whenever I want to update the Docker image. 

> However, we strongly advise against this approach since there's no guarantee that new Playwright works with the old browser versions. (If you're curious to learn why, feel free to check out the [playwright internals overview](https://youtu.be/PXTspGn1im0?t=54))

This is the way many organization are using setting up their project, due to one of the following reasons:
- to organization policies (not to download unapproved version of Chrome browser for example) 
- running Playwright in on a CICD agent that they don't have access to install browsers and Playwright can't recognize the default browser. 
- many engineers prefer not to download browser every time they run their tests in CICD

so adding a flag to ignore the browser version in ms-playwright folder, is something that is actually useful for many, even if it goes against your ideal scenario.

> So all in all, the approach you're currently taking (e.g. npx playwright install --with-deps) is a proper way to solve it.

No, it is a workaround. It increases the time of pipeline execution as Playwright has to be always re-installed on a Docker that comes with Playwright pre-installed.

**Comment by aslushnikov** [comment]
> @aslushnikov yes, I am very much aware of executablePath options, but that doesn't solve the problem as I need to still orchestrate a change within organization whenever I want to update the Docker image.

No need to orchestrate anything; you can discover a proper `executablePath` in the very beginning of the test run in either config or global setup, by listing browsers under `/ms-playwright` in docker container.

All in all, closing this as per https://github.com/microsoft/playwright/issues/20010#issuecomment-1378487834

**Comment by irharrier2** [comment]
@aslushnikov it is so frustrating that in every comment, you assume that I have no idea what I am talking about.

as I mentioned I have to setup Playwright docker image as an agent due to the policies in our company. Around 80 teams use that image, so if I want to use executablePath, then I have send an email to everyone asking them to change the path in their project. 

Will continue using my workaround to reinstall Playwright each time

**Comment by devnigam24** [comment]
Thanks all for your inputs.

**Comment by billyliuschill** [comment]
In your package.json file, make sure to upgrade "@playwright/test": "^1.37.1" to the new version it says it wants, like so: "@playwright/test": "^1.40.1".

Then do a `npm install` to get update to latest and it should fix the issue. Make sure any instance of playwright for browsers is updated accordingly.

**Comment by billyliuschill** [comment]
> In your package.json file, make sure to upgrade "@playwright/test": "^1.37.1" to the new version it says it wants, like so: "@playwright/test": "^1.40.1".
> 
> Then do a `npm install` to get update to latest and it should fix the issue. Make sure any instance of playwright for browsers is updated accordingly.

My error is this:
```
Looks like Playwright Test or Playwright was just updated to 1.37.1. ║
    ║ Please update docker image as well.
```

**Comment by andreas942** [comment]
I have a similiar problem,  we run in our Jenkins CI/CD pipeline some test within docker image 
playwright/dotnet:v1.39.0-jammy
But now I'm getting.

 Error Message:
   Microsoft.Playwright.PlaywrightException : Executable doesn't exist at /ms-playwright/chromium-1091/chrome-linux/chrome
╔════════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just updated to 1.40.0.              ║
║ Please update docker image as well.                            ║
║ -  current: mcr.microsoft.com/playwright/dotnet:v1.99.99-jammy ║
║ - required: mcr.microsoft.com/playwright/dotnet:v1.40.0-jammy  ║
║                                                                ║
║ <3 Playwright Team                                             ║
╚════════════════════════════════════════════════════════════════╝
  Stack Trace:
     at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwnerBase object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 209
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.BrowserType.LaunchAsync(BrowserTypeLaunchOptions options) in /_/src/Playwright/Core/BrowserType.cs:line 63
   at Microsoft.Playwright.NUnit.BrowserService.CreateBrowser(IBrowserType browserType) in /_/src/Playwright.NUnit/BrowserService.cs:line 55
   at Microsoft.Playwright.NUnit.BrowserService.<>c__DisplayClass5_0.<<Register>b__0>d.MoveNext() in /_/src/Playwright.NUnit/BrowserService.cs:line 45
--- End of stack trace from previous location ---
   at Microsoft.Playwright.NUnit.WorkerAwareTest.RegisterService[T](String name, Func`1 factory) in /_/src/Playwright.NUnit/WorkerAwareTest.cs:line 55
   at Microsoft.Playwright.NUnit.BrowserTest.BrowserSetup() in /_/src/Playwright.NUnit/BrowserTest.cs:line 46
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)


I updated to v1.40.0-jammy, but then I noticed that this supports only .NET 8.0.
But we want to work with .NET 6.0 further.
How can I fix this?

**Comment by vid** [comment]
This is really crummy of Microsoft. People should be able to use a library without it breaking whenever there's an update, especially when an app uses a library that uses Playwright. This behaviour is completely abnormal. Microsoft is using its weight in this and other cases to force people down their path, even though it would be easy to support normal operations.
