### ISSUE TITLE
[Question] How to disable 'Save password' (credentials service/password manager) on running persistent context?

### ISSUE THREAD

**Issue by AndrewEgorov** [microsoft/playwright#20025]
Sorry if it's duplicate, but i wasn't able to find similar question, but: how to disable 'Save Password' popup which appear then you enter some creds on launching persistent context?

![image](https://user-images.githubusercontent.com/7087798/211773620-bc4fca3f-3752-487a-bf12-4d016651a2c9.png)

If I remember it's 'credentials_enable_service' and 'profile.password_manager_enabled' pref settings. but wasn't able to pass it to playwright.

**Comment by aslushnikov** [comment]
@AndrewEgorov not sure how to set the preference you'd like to, however: why would you like to set it? Does the popup break your test?

**Comment by AndrewEgorov** [comment]
No, @aslushnikov :) just annoying thing which showing during all my tests on every enter of user/pwd.

**Comment by AndrewEgorov** [comment]
If it's not possible now, I'm fine with it, just asking. But would be nice in future to have an ability to disable password manager (as it's configured in browser settings)

**Comment by aslushnikov** [comment]
> no :) just annoying thing which showing during all my tests on every enter of user/pwd.

@AndrewEgorov Ah I see :)

> If it's not possible now, I'm fine with it, just asking. But would be nice in future to have an ability to disable password manager (as it's configured in browser settings)

I spent some time googling yesterday. In 2017, the `--enable-automation` flag was hiding the bubbles: https://github.com/GoogleChrome/chrome-launcher/issues/32

Is it not the case any more, or do you happen to remove the flag? Also, there are some policies you can probably setup, but I don't exactly recall the names. You can also try setting some chromium preferences or policies: https://www.chromium.org/administrators/configuring-other-preferences/

I'll close this since it doesn't affect testing scenarios and there's no action from the team regarding this, but feel free to update the issue if you find something. It'd help future generations :)

**Comment by AndrewEgorov** [comment]
@aslushnikov , thanks for help and link. You are right `--enable-automation` flag works, but here are some notes:
* If you use it in `ignoreDefaultArgs` it will show 'Save Password' but not show 'Chrome is being controlled...' info bar (this is how I used it before)
* If you use it in args `--enable-automation=false` then it will not show 'Save Password' but will show 'Chrome is being controlled...' 
I tried different combinations but seems it either show one or another and can't hide both :/ . But ok for me.

Thanks.

**Comment by niranjan94** [comment]
@aslushnikov thanks for your responses here. I'm trying to understand why there is a difference in behaviour when launching  chrome via `chromium.launchPersistentContext` vs `chromium.launch`. For example, this specific issue does not occur when launching why `chromium.launch`. 

Would it be possible for you to point me to some documentation if any regarding the differences in behaviour b/w these two launch methods ? I'm unable to make sense of it
