### ISSUE TITLE
[Feature] Make the Playwright Inspector open next to browser window

### ISSUE THREAD

**Issue by alexbjorlig** [microsoft/playwright#20031]
This might be a 1 world problem - but I use a lot of time testing 🤓

When I run Playwright with the `--debug` flag, the Inspector opens.

But it opens "under" the browser window - so every time I have to move the window 😂

<img width="1605" alt="Screenshot 2023-01-11 at 13 48 09" src="https://user-images.githubusercontent.com/9967422/211810239-c6fdb1ad-2d97-4936-a603-f44280e90e1c.png">

I'm running Mac OS, with the studio display 27-inch (5120x2880) (in case you don't have this issue)

**Comment by ambiguous48** [comment]
One way to work around it might be to set the browser position to a fixed place on your screen using [launchOptions](https://playwright.dev/docs/api/class-testoptions#test-options-launch-options).

```typescript
// playwright.config.ts

launchOptions: {
  args: ['--window-position=0,0'], // chromium flag
},
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
