### ISSUE TITLE
[Question] How to quit the run while running playwright from command prompt without using ctrl+c on a failure?

### ISSUE THREAD

**Issue by s-sivasubramaniam** [microsoft/playwright#20066]
How to quit the run while running playwright from command prompt without using ctrl+c on a failure?

**Comment by aslushnikov** [comment]
> How to quit the run while running playwright from command prompt without using ctrl+c on a failure?

@s-sivasubramaniam You can set the [`maxFailures`](https://playwright.dev/docs/next/api/class-testconfig#test-config-max-failures) option in config or just run tests with `npx playwright test --max-failures 1`

Hope this helps; please do not hesitate to file new issues if you have questions and you think we can be helpful to you!

**Comment by shellscape** [comment]
@aslushnikov  I have `maxFailures` set to 1 in the config file, I'm using `-x` on the CLI, and I'm still presented with the prompt to `Press Ctrl+C to quit`. Looks like y'all have a bug there.

**Comment by sfc-gh-pshah** [comment]
Same here

**Comment by ronbravo** [comment]
@sfc-gh-pshah @shellscape I agree, this seems to be a bug. It might be related to how playwright will by default open the html reporter on error? https://github.com/microsoft/playwright/issues/9702

I set the reporter to `"line"` on my project and this seems to fix playwright waiting for `ctrl+c` in order to exit.

**Comment by RopoMen** [comment]
I feel that way how Playwright currently works with this matter is troublesome. How I expect e2e tests to be run in CI? I want that all tests are run and after all tests are completed (success/failure) I get report and test runner exits 0 on success and 1 on failure(s).

If I have 200 e2e tests and I set `maxFailures` to 1 my feedback loop for all tests is extremely long because I cannot get visibility into all tests at once. If the first test fails then 199 tests are not run and then team fixes that first test ~1h of work taking all PR process etc. to see that also the second test had issues causing again ~1h of work. Just stupid.

I also tested setting `reporter: [['html', { open: 'never' }]]` with no effect. Nor did help `export CI=1`. Meaning that runner will keep process up --> container running in CI pipeline? for how long?
