### ISSUE TITLE
[Question] How to decrypt the Azure pipeline variables in Playwright script?

### ISSUE THREAD

**Issue by yash-lohakare** [microsoft/playwright#20091]
Currently I've set 2 environment variables i.e. USER_NAME & PASSWORD in Azure pipeline variables and utilizing them in test file as below -  
let username = process.env.USER_NAME;
let password = process.env.PASSWORD;

This works for non encrypted one. But how to get those variables when they are encrypted in azure pipeline?

**Comment by aslushnikov** [comment]
@yash-lohakare this question is more about Node.js and Azure rather than about Playwright. I'd recommend asking these kind of questions in a azure-specific forum or on StackOverflow.

I'm sorry we can't help you! I'll have to close this. But please do not hesitate to file more issues if you think Playwright team can be useful to you.
