### ISSUE TITLE
[BUG] Screenshot comparison fails in Chrome because of font render differences on two machines with same specs

### ISSUE THREAD

**Issue by lkaisers** [microsoft/playwright#20097]
**Context:**
- Playwright Version: 1.27.1
- Operating System: macOS Ventura 13.1
- Node.js version: 16.18.0
- Browser: 109.0.5414.87, .../Library/Caches/ms-playwright/chromium-1041/chrome-mac/Chromium.app/Contents/MacOS/Chromium

**Code Snippet**
```javascript
import { expect, test } from '@playwright/test';
import { getComponentTestPageUrl } from '../../helper/utils';

test('Button', async ({ page, headless }) => {
	await page.goto(getComponentTestPageUrl('Button'));
	await expect(page).toHaveScreenshot();
});
```

**Describe the bug**

We experience a very strange bug when using screenshot comparison on Chome. My colleague and me both use Playwright on macOS and when he updates the snapshots the test succeeds for him, but not for me, and the other way round. The snapshot comparison works fine on both machines with the devices `Desktop Safari` and `iPhone 12`.

We checked that everything is even on the same version: Node.js, macOS, the browser specs and so on.

Take a look at the snapshot diff:
![snapshot-comparison-diff](https://user-images.githubusercontent.com/34108423/212293091-ef29b5d9-a09f-45bf-a6f2-6d6cca7ef5fb.png)

```javascript
{
    name: 'Chromium',
    use: {
        ...devices['Desktop Chrome'],
        channel: 'chrome',
    },
},
```

**Comment by aslushnikov** [comment]
Hey @lkaisers! Thank you for the report, and may I ask you for a few favors?

1. Could you please share the expected and actual screenshots with me so that I can generate this diff locally? Either here, or privately on my email (anlushni[at]microsoft[dot]com)
2. Could you please try adding the following options in your chromium launch configuration and check if it fixes things for you?
    ```ts
    {
      name: 'Chromium',
      use: {
          ...devices['Desktop Chrome'],
          channel: 'chrome',
          launchOptions: {
            args: [
              '--font-render-hinting=none',
              '--disable-skia-runtime-opts',
              '--disable-font-subpixel-positioning',
              '--disable-lcd-text',
            ]
          }
      },
    },
    ```
3. Finally, instead of adding arguments in (2), could you please update to Playwright 1.29 and try using an experimental `_comparator` option in your `toHaveScreenshot` call, like this:
    ```ts
    import { expect, test } from '@playwright/test';
    import { getComponentTestPageUrl } from '../../helper/utils';

    test('Button', async ({ page, headless }) => {
      await page.goto(getComponentTestPageUrl('Button'));
      await expect(page).toHaveScreenshot({ _comparator: 'ssim-cie94' });
    });
    ```

**Comment by lkaisers** [comment]
Hey @aslushnikov, we tried both of your approaches but unfortunately none of them fixed the issue. Here are the both screenshots that you can compare.

![actual](https://user-images.githubusercontent.com/34108423/212708593-c68f3f53-2bfe-4a8c-a5ab-bc10bfb38c83.png)
![expected](https://user-images.githubusercontent.com/34108423/212708597-6c3efd57-e899-4900-bb25-fdb66b12acc1.png)

@SpiderZZZ We also tried to leave out channel: 'chrome' but this also didn't make any difference to our results. But it seems that you have the same issue as we got!

**Comment by PawelWesolowski** [comment]
I had the same problem a while ago with my own pixelmatch-based compare method. 
In my case the CI job (Docker based) was creating slightly different screenshots than dev machine(s) did. 
You can try setting `{threshold: 0.7}`. It helps in some cases. Sometimes the whole div is slightly off - then it won't help.
But... I ended up creating a separate CI job with branch name as a param, to record the screenshots and commit them back to git. I enable picture comparison only in CI because I know there is always the same docker image used for producing and for comparing. Default is to skip picture comparison so local test runs always pass. Downside is that I need to push to git to check if screenshot-tests are OK. Nice thing is that when the PRs do not pass I have a separate "updated screenshots by CI agent" commit where I can see what exactly in UI have changed in this particular PR.
I am aware that my solution is a workaround but it works quite stable for over a year now.
Proper solution here IMO would be an AI based compare but I didn't have time to look into it (yet). 
Looking forward to see how will this issue be solved and how others have solved it.

**Comment by aslushnikov** [comment]
@lkaisers thank you for the information!

Looking closer at your screenshots, it looks like one text is positioned 1 pixel higher than the other; thus the difference. 
So the website does render differently on these machines, so screenshot difference is reported as it should.

I wonder what can cause this difference between machines though. A few guesses:
- what kind of macbooks are these? Could it be that one is Apple M1, and the other is x86_64?
- do these machines have the same monitors with the same DPI?
- could you please check the "computed styles" panel in Chrome DevTools to make sure the "rendered font" for the element is the same?
<img width="472" alt="image" src="https://user-images.githubusercontent.com/746130/213083955-6ef0e8f6-68b7-4b55-8fbf-6e4c0162922f.png">

**Comment by lkaisers** [comment]
@aslushnikov You're right, it's just about the vertical positioning of the font. To answer your questions:

1. Yes, we do have different chips as my colleague works on a **MacBook Pro 15-Inch, 2018** and me on a **MacBook Pro 16-Inch, 2021**
2. The DPI should be irrelevant due to the headless mode, isn't it?
3. We checked the `Computed` section but there's no difference in styles, most of them aren't even active

Here are two more insights I can share with you:
1. We already took screenshots of our test page from within our daily-used Chrome browser, and both browsers render the page exactly the same way (compared via https://www.diffchecker.com/image-compare/)
2. The font positioning bug doesn't appear in our headline font (Carnero), only in blocks of Roboto.

Hope you can make sth out of the information I gave you :)

**Comment by pratheeshp007** [comment]
+1

**Comment by pratheeshp007** [comment]
We are facing a similar issue. What I have observed is when we are running the test on a external monitor vs  macbook screen the snapshots are having similar mismatch

**Comment by ukdas** [comment]
We are also facing the same issue.

**Comment by aslushnikov** [comment]
> The DPI should be irrelevant due to the headless mode, isn't it?

@lkaisers This is unfortunately not the case on Mac. Overall, it is relatively hard to build an exact host environment for browser tests on MacOS.

I'd recommend running tests inside a docker container - this should provide a consistent environment for your screenshot tests.

**Comment by SpiderZZZ** [comment]
> > The DPI should be irrelevant due to the headless mode, isn't it?
> 
> @lkaisers This is unfortunately not the case on Mac. Overall, it is relatively hard to build an exact host environment for browser tests on MacOS.
> 
> I'd recommend running tests inside a docker container - this should provide a consistent environment for your screenshot tests.

@aslushnikov what about problem in https://github.com/microsoft/playwright/issues/20097#issuecomment-1383953252 ? It's reproducing at docker contaner.

**Comment by aslushnikov** [comment]
@SpiderZZZ It very well could be a separate issue. Do you have a small repro that I can run locally to reproduce the issue? If you do, then could you please file separately?

**Comment by SpiderZZZ** [comment]
> @SpiderZZZ It very well could be a separate issue. Do you have a small repro that I can run locally to reproduce the issue? If you do, then could you please file separately?
[simple-pw-screenshot-problem-main.zip](https://github.com/microsoft/playwright/files/10578331/simple-pw-screenshot-problem-main.zip)
may be create new issue ?

**Comment by aslushnikov** [comment]
@SpiderZZZ Yes please, file a new issue for this! its not clear what you do and what's not working, and how do I reproduce this. So please, make sure to fill in issue template!

**Comment by aslushnikov** [comment]
To sum up: different hosts might indeed yield different rendering. Even if your OS version is the same, there are still many factors that affect browser rendering on different machines, including hardware & OS configuration.

So far, the only reliable way to get identical screenshots is to use identical hosts, or VMs with the same image, or containers.

**Comment by uke5tar** [comment]
Hey @PawelWesolowski,
Would you be able to share the code about how you created that separate git job that makes the screenshot and commits them?

**Comment by PawelWesolowski** [comment]
> Hey @PawelWesolowski, Would you be able to share the code about how you created that separate git job that makes the screenshot and commits them?

We use Jenkins. We have a separate job that you start manually when you need to re-record screenshots. You need to provide the branch name as a param to the job - SNAPSHOTS_SOURCE_BRANCH. The actual "code" is just something like:
```bash
playwright test --update-snapshots
git add uitest/**/screenshots/*.png
git diff --staged --quiet || (git commit -m 'update snapshots from jenkins' && git push origin ${SNAPSHOTS_SOURCE_BRANCH})
```
Here's the workflow:
1. You have a failing test - it's green on main branch but red on yours. The test fails because of a screenshot.
2. You check if you have introduced a bug or if it is an intended change to the UI.
3. If the change was intended, you re-record by running the job manually and passing your branch's name.
4. Jenkins commits changed screenshots and as a result the next build on your branch is green.

**Comment by harry-atk** [comment]
This issue was very rare for awhile but started failing when adding middleware to a next.js app, probably showing up more now because of speed differences. I want to say its something happening during hydration. But it seems like something that's browser rendering specific. Its not difference between devices for us since test will be flakey whether or not its run locally or if screenshots are updated by a github action

**Comment by tomaskikutis** [comment]
I'm having a similar issue where font rendering differs based on whether tests are ran from a VS code extension or headless mode on the same machine. One workaround I found to work is setting font to Arial only for tests. (Roboto was the one not working well)
