### ISSUE TITLE
[BUG] Page Object created in global-setup not transferred to script 

### ISSUE THREAD

**Issue by MehseinJohan** [microsoft/playwright#20108]
**Context:**
- Playwright Version: 9.2.0
- Operating System: Windows
- Node.js version: 18.12.1
- Browser: [All]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
//global-setup.ts
async function globalSetup(config: FullConfig, page) {
      const workingPage = new LoginPage(page);
      await workingPage.login();

//test
let workingPage;

test('bulk_item_presence', async ({baseURL, page}) => {
      await workingPage.testBulk();
```

**Describe the bug**

Hello team, I would like to create a page object in the global-setup, use the storageState on it (to avoid relogging at each test),  and reuse it in my scripts in order to avoid creating new ones everytime a new script is launched (unuseful and time/resources consuming). I've done global-setup above and done an import of the created object (workingPage) thanks to "let workingPage" but the object is not recognized.

Could you please let me know what I have missed ?

Thank you in advance,

Regards,

Johan

**Comment by aslushnikov** [comment]
> Hello team, I would like to create a page object in the global-setup, use the storageState on it (to avoid relogging at each test), and reuse it in my scripts in order to avoid creating new ones everytime a new script is launched (unuseful and time/resources consuming).

@MehseinJohan The last part - "and reuse it in my scripts in order to avoid creating new ones everytime a new script is launched" - is not possible. You can assume that `globalSetup` and test scripts are being executed in different processes. Moreover, if the test fails, its worker process will be re-created, so everything required for a test to pass should be re-initialized. (read more about this here: https://playwright.dev/docs/next/test-parallel#worker-processes)

As a result, you'll have to re-create a POM for your tests. I'd recommend to shape your POM as a fixture so that it's easy to use in tests; see an example of this here:  https://playwright.dev/docs/next/test-fixtures#creating-a-fixture 

Hope this helps! Please do not hesitate to file new issues if you think we can be helpful!
