### ISSUE TITLE
[Question] When to expect the latest Node.js LTS (v18) version in docker image?

### ISSUE THREAD

**Issue by SimonGolms** [microsoft/playwright#20133]
In my CI/CD setup, I use the Docker image provided by playwright [`mcr.microsoft.com/playwright:v1.29.2-focal`](https://mcr.microsoft.com/en-us/product/playwright/about). Now, with the release of the latest major version ([`v20.0.0`](https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0)) of [semantic-release](https://semantic-release.gitbook.io/semantic-release/), it is now the first package in my app that requires Node.js v18 and I assume that more will follow soon.

With the Node.js LTS change as of [2022-10-25](https://github.com/nodejs/release#release-schedule), I had been looking forward to the fast adaptation in Docker Image (#18334). But the change was reverted before the next playwright release (#18791). Since this was over 2 months ago, I wanted to kindly ask if a corresponding change is planned soon?

**Comment by mxschmitt** [comment]
We had [this](https://github.com/microsoft/playwright/issues/18790) as a blocker since Node.js 18 introduced a breaking change which would affect our customers.

We'll release happy eyeballs as part of version 1.30 and upgrade to Node.js 18 in version 1.31.

If you want to upgrade earlier, you can upgrade your node by simply doing: 

```bash
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
sudo apt-get install -y nodejs
```

see here: https://github.com/nodesource/distributions/blob/master/README.md#debinstall

**Comment by mtt87** [comment]
👋 Came across this issue while looking if there are Docker images that support node20 😄 
@mxschmitt Is there an official plan to support node20 now that it's the active LTS? 🙏

**Comment by mxschmitt** [comment]
> 👋 Came across this issue while looking if there are Docker images that support node20 😄 
> 
> @mxschmitt Is there an official plan to support node20 now that it's the active LTS? 🙏 

Yes starting from 1.40 we have Node 20
