### ISSUE TITLE
Add CLI support to keep the browser opened

### ISSUE THREAD

**Issue by DamienCassou** [microsoft/playwright#20130]
Sometimes, understanding why my application isn't working as expected requires adding a few breakpoints to the application's code. Unfortunately, each time Playwright starts the browser for a given test, a new browser profile is created and my precious breakpoints are not in the new browser profile.

In #19915, @mxschmitt says that this feature is supported in VS Code. It seems like there is no documentation or options to be passed to the command line to do the same using the playwright command line interface directly.

Looking at the code, it seems like the environment variables `PW_TEST_REUSE_CONTEXT` and `PW_TEST_CONNECT_WS_ENDPOINT` are used. Documenting them would be a good starting point in my opinion.

**Comment by yury-s** [comment]
Is there a reason why using this feature inside VSCode is not an option for you? Also could explain what using it from command line would look like step by step?

**Comment by DamienCassou** [comment]
> Is there a reason why using this feature inside VSCode is not an option for you?


In our team, we let developers pick their tooling. We are currently using Cypress and developers can code in the editor they want and debug from it or from the web browser. We are not going to impose any text editor so Playwright is not an option currently.


> Also could explain what using it from command line would look like step by step?

As a first step, some documentation about the environment variables needed to make playwright reuse the browser would be awesome.

**Comment by emakaay** [comment]
+1

**Comment by vbyjsue** [comment]
This is also the only way I found to use the test-runner instead of manually setting up a session when connecting to Aerokube Moon browser cluster.
`process.env.PW_TEST_CONNECT_WS_ENDPOINT=wss://moon.yourcluster/playwright/${config.projects[0].name}`
Documenting it would have saved me a few hours of searching  and guessing. According to my search results it's not known even to services that offers remote playwright browsers?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
