### ISSUE TITLE
[Question] test.skip() still creates separate thread

### ISSUE THREAD

**Issue by mstepin-edt** [microsoft/playwright#20156]
Hi,
Is there a good reason why tests skipped with `test.skip()` still get allocated a separate worker thread?
I get that the test gets marked as skipped in the report, but that feels like a post run activity that updates the test results rather than an action requiring a separate worker thread.

This becomes very apparent, and very inefficient, if you have a spec file with, for example:
```
test('test1', () => {})
test.skip('test2', () => {})
```

And then execute it with `--repeat-each`. If you repeat it 6 times, you end up with 12 worker threads. So this grows (linearly) as the number of repeats increases.

This may turn into a feature request or bug ticket.

**Comment by mxschmitt** [comment]
How do you obtain that you get 12 worker threads? I did the following and I got only 6 workers which is expected if you do repeat-each 6:

```ts
import { test } from '@playwright/test';

test('test1', async ({ }, testInfo) => {
  console.log(testInfo.workerIndex)
});

test.skip('test2', async () => {
});
```

**Comment by mstepin-edt** [comment]
Which version are you testing with? I have `1.27.1`.
Can you confirm whether you still get 6 for 6 in that version? If so that would confirm it is fixed and I need to upgrade.
I'm literally doing what you are doing:
```
const { test } = require('@playwright/test')
test.skip( 'my test description @tag', async ({  }, testInfo) => {
    console.log('IN HERE 1')
})

test( my test description 2 @tag', async ({  }, testInfo) => {
    console.log('IN HERE 2')
})
```

I use `yarn` to execute the tests

Gives me this output:
```
yarn run v1.22.19
$ playwright test ./scenarios/my-scenarios/ --repeat-each 3

Running 6 tests using 6 workers
…/scenarios/my-scenarios/testfile.spec.js:47:1 › 'my test description 2 @tag
IN HERE 2
…/scenarios/my-scenarios/testfile.spec.js:47:1 › 'my test description 2 @tag
IN HERE 2
…/scenarios/my-scenarios/testfile.spec.js:47:1 › 'my test description 2 @tag
IN HERE 2
                                                                                                                                                                        
  3 skipped
  3 passed (552ms)

To open last HTML report run:
  npx playwright show-report
Done in 0.95s.
```

**Comment by mstepin-edt** [comment]
Just also tested without using yarn and get the same issue

**Comment by mstepin-edt** [comment]
have the config setting:
`fullyParallel: true`

When I comment that out, I get:
`Running 6 tests using 3 workers`

Unsure if that should be `Running 3 tests` instead but perhaps this is a bug with that setting?

**Comment by yury-s** [comment]
I can reproduce it:

```
$ npx playwright test --repeat-each 2 --fully-parallel

Running 4 tests using 4 workers
[chromium] › example.spec.ts:7:5 › my test description 2 @tag
IN HERE 2
[chromium] › example.spec.ts:7:5 › my test description 2 @tag
IN HERE 2

  2 skipped
  2 passed (294ms)
```

Looks like just a problem with reporting. Also note that the number of workers is still capped by #Cores / 2 by default and will not grow indefinitely. We should fix it but I believe it should not cause any issues in practice.

**Comment by mstepin-edt** [comment]
It causes issues in practice for us because we use testInfo.parallelIndex for things, and this literally doubles the count for anything reliant on it.

**Comment by yury-s** [comment]
Can you elaborate on what is the observed effect of that and why it matters? Does it increase the time significantly or what? If you have enough enabled tests it should be just a rounding error in terms of performance.

**Comment by mstepin-edt** [comment]
For some tests we need to have things prepared that aren't necessarily automated. I suspect others do too. Ie. we need to set up, say, 3 of something to start with. We then run a spec file containing the tests with `--repeat-each 3` in parallel, and make the assumption that we are able to run it as many times as we have stuff prepared for it. They can then access said resources, for example via `someArray[tesetInfo.parallelIndex]`. Obviously it will fail if it tries to get `someArray[6]` and it doesn't exist.

**Comment by yury-s** [comment]
> For some tests we need to have things prepared that aren't necessarily automated. I suspect others do too. Ie. we need to set up, say, 3 of something to start with. We then run a spec file containing the tests with --repeat-each 3 in parallel, and make the assumption that we are able to run it as many times as we have stuff prepared for it. They can then access said resources, for example via someArray[tesetInfo.parallelIndex]. Obviously it will fail if it tries to get someArray[5] and it doesn't exist.

I still don't understand how skipped tests cause any problems here. If you run the tests in fully parallel mode with more than 3 [workers](https://playwright.dev/docs/api/class-testconfig#test-config-workers) some of them (with parallelIndex > 2) will access non existing elements, so you have to run with 3 workers in this case. If you do `npx playwright test --repeat-each 3 --workers 3` all your tests including the skipped one will run on this 3 workers according to the playwright's scheduling algorithm. Unless your tests depend on each other they should not fail because of skipped tests and if they do depend on one another you should not run them in parallel.

> For additional context, we have to work around this problem by making one test() and the other test.only() but this is a very limiting workaround since we cannot then run it in conjunction with other tests without having to put the .only() everywhere else manually.

Can you share an example, I'm not following how test.only() helps you? Are you trying to tune playwright test scheduling logic with these calls?

**Comment by mstepin-edt** [comment]
I'll try my best.
We have manually created resources, eg:
`[resource1, resource2, resource3]`

We have tests that use said resource, but in the same spec file we also have a similar tests that dont require the resources but don't usually execute at the same time as those requiring said resources, and so are skipped with `test.skip()`

```
const resources = [resource1, resource2, resource3]
test( 'I need a specific preexisting resource @tag', async ({  }, testInfo) => {
    functionUsingTheResource(resources[testInfo.parallelIndex])
})

test.skip( 'I DO NOT need a specific preexisting resource @tag', async ({  }, testInfo) => {
    console.log('I do stuff that doesnt require the resource, so I'm turned off most of the time, but sometimes I'm still needed')
})
```

test gets executed with:
`npx playwright test ./path/to/file --repeat-each 3`

Playwright allocates 6 parallel workers to the run, even if 3 are eventually skipped.

now when the actual running test accesses the resources, `testInfo.parallelIndex` will range from `0` to `5` (zero index)

Thus, since the workers are not allocated TO A TEST in any specific order (ie. not guranteed), the running test which isn't skipped might end up with index `1`, `3` and `4`. 
Meaning our assumed reliable pattern expectation of repeating 3 times resulting in 3 worker threads breaks the code.

I am fully aware that there are code mitigations in Javascript that one can apply to jump over this hurdle, but it feels like exactly that - a workaround.

**Comment by yury-s** [comment]
If you want to run a single test 3 times in fully parallel manner you can use `test.only()` or pass `file:line` filter in the command line. In this case other tests will not even be loaded. Otherwise relying on some tests being skipped (and not having other test cases in the same suite) is brittle and will break as the number of test cases grows.

> Meaning our assumed reliable pattern expectation of repeating 3 times resulting in 3 worker threads breaks the code.

`--repeat-each 3` is not supposed to restrict max number of workers running in parallel. It's true that if you have only one test and run with `--repeat-each 3` and have enough CPU cores playwright will allocate exactly 3 workers, but if you add another test later the number of workers will change. It will happen regardless of wether the new test is skipped or not. Fixing the problem just for the skipped tests won't help you. The only way to guarantee that playwright allocates at most 3 workers it to pass `--workers 3`. My understanding is that you want to ensure that 'I need a specific preexisting resource @tag' never runs on more than 3 workers in which case you need to set the number of workers explicitly, and that, in turn, eliminates the problem of skipped tests. Does it make sense?

**Comment by pavelfeldman** [comment]
The issue looks clear, we should create 3 worker, but we create 6 workers
