### ISSUE TITLE
[Question] How to Use JSON Object as input variables.

### ISSUE THREAD

**Issue by FranGomezVenegas** [microsoft/playwright#20186]
Hi,

I'm new in this forum and playing with playwright.

I read that we can add environment variables and even csv files for passing input variables to the tests. Is it possible the same with a JSON Object? If so, where I can see an example? 

Thanks

**Comment by OShalaby** [comment]
I have testData.js it contains:
`{
username: 'foo',
password: process.env.password
}`

and a .env file containing:
`password = 'bar'`

I use the above structure because I do not want to include a password in the test data, also .json files do not accommodate env variables but .js do.

Then in my test case:
`data = require('./testData.js');`

**Comment by yury-s** [comment]
You can also read the file and parse it manually like this in your tests:

```js
const json = JSON.parse(fs.readFileSync('test.json').toString());
```

Closing the issue per the response above and this one. Please file a new bug if you have further questions.
