### ISSUE TITLE
[BUG] The method 'isChecked' return incorrect value

### ISSUE THREAD

**Issue by Sapendo** [microsoft/playwright#20190]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Windows
- Node.js version: 16.15.0
- Browser: WebKit

**Code Snippet**
```javascript
expect(await page.locator('stj-checkbox-demo').locator('stj-checkbox').nth(0).locator('input').isChecked()).toBe(true);
```

**Describe the bug**

There is a checkbox that has both a checked and an indeterminate state. Before updating the version of the playwright to version 1.29.2 the test worked correctly and returned the value as 'true' if we checked with 'locator.isChecked()'. After updating returned value is 'false'. However, if we look at the state of the element in devtools we see that the checked state equals 'true'.
This happens only if the checkbox has both states as 'true'. If, for example, the indeterminate state equals 'false' and the checked state equals 'true' the test will pass.

![image](https://user-images.githubusercontent.com/24610132/213172270-e1ad6695-2b76-4cf8-a07d-6c10c839a872.png)

**Comment by yury-s** [comment]
According to the accessibility tree the element's state is `checked: mixed`:

![image](https://user-images.githubusercontent.com/9798949/213331339-a35d6926-b5de-44e1-b452-feff819fc46e.png)

So the current behavior is actually correct.

**Comment by Sapendo** [comment]
According to the accessibility tree the element's state is `checked: true`:

![image](https://user-images.githubusercontent.com/24610132/213385156-c238fc2e-66f4-4a30-bfab-a57ba0540305.png)

**Comment by yury-s** [comment]
I wonder why we see different value in devtools, can you share a repro so that we can try it locally?

> Moreover, I do not understand why the method isChecked look at the accessibility property. If you take value from the accessibility property, the method isChecked should return one of the next values: 'checked (true)', 'unchecked (false)', or 'mixed'.

If isChecked returned 3-state value we'd return mixed in this case. Since indeterminate element is a grey area, we consider everything that is not true to be false. What you suggest is basically consider everything that is not false in the ax tree to be true.

**Comment by yury-s** [comment]
> I wonder why we see different value in devtools, can you share a repro so that we can try it locally?

@dgozman pointed out that if you are inspecting the element in the trace then it most likely doesn't have indeterminate property as we don't restore it.

**Comment by Sapendo** [comment]
Unfortunately, I cannot share a repo, but you can see the same situation on [Angular Material](https://material.angular.io/components/checkbox/examples). So if you mark the checkbox as checked and 
indeterminate the checkbox state will be `checked: true`

![image](https://user-images.githubusercontent.com/24610132/213651891-8cd9c216-b3b3-4eaa-90fb-f7fe16255388.png)

**Comment by Sapendo** [comment]
Hello) Do you have any updates?

**Comment by dgozman** [comment]
Investigation notes:
- Material produces `<input checked aria-checked="true">`, but sets `input.indetermined = true`. This seems to be an a11y bug in Material, because checkbox renders as "mixed", but marked for aria as "checked". [This looks like the relevant source](https://github.com/angular/components/blob/main/src/material/checkbox/checkbox.ts#L314-L320).
- Chromium prioritizes `aria-checked` over the native `checked`/`indeterminate` properties, and reports "checked" in the a11y panel.
- Firefox prioritizes native properties in this case and reports "mixed".
- Safari prioritizes native properties, but seems to have a bug around "mixed" state, so reports "checked". Safari Technology Preview properly reports as "mixed".
-  [ARIA spec here](https://www.w3.org/TR/core-aam-1.2/#mapping_conflicts) is vague, but looks like it suggests to prioritize the native properties.

Overall, the browsers disagree. Perhaps Playwright should behave differently depending on the browser in runs in?
