### ISSUE TITLE
[Question]..... Have I lost my mind or have the query selector gone poof??

### ISSUE THREAD

**Issue by RudiSygoDanGi** [microsoft/playwright#20205]
Hi, awesome dev team of Playwright and Community. 
I haven't used playwright for about a year now, bad, I know but the reason why I am saying this is because last I was playing around with capturing text with the query selector but now even googling it comes up with nothing like it has never existed?? 

Have I lost my mind?

Thanks, Guys
Rudi

**Comment by yury-s** [comment]
We recommend using [locators](https://playwright.dev/docs/locators) in all new code. [Query selector](https://playwright.dev/docs/api/class-page#page-query-selector) method is still there though. You probably couldn't find it because it is  called `$` and `$$` in Node.js version and [querySelector](https://playwright.dev/java/docs/api/class-page#page-query-selector) in java.
