### ISSUE TITLE
[Question] Playwright-chromium is freezing

### ISSUE THREAD

**Issue by munrocket** [microsoft/playwright#2030]
Hello, recently I am tried to migrate three.js library from puppeteer to playwright, we used it in WebGL testing. But for some reason it freezes on some of the screenshots (at least in linux). I will appreciate if you help me with it, because I am stuck.

**Steps to reproduce a problem**
```shell
git clone https://github.com/mrdoob/three.js
cd three.js
npm un puppeteer && npm i -D playwright-chromium
curl https://pastebin.com/raw/UjYAKxAN --output playwright.js
cp playwright.js ./test/e2e/puppeteer.js
npm run test-e2e
```

**Expected result**

All examples are tested with screenshot without freezing

**Actual result**
```
diff: 0.002, file: css2d_label
diff: 0.000, file: css3d_molecules
diff: 0.000, file: css3d_orthographic
diff: 0.000, file: css3d_panorama
<freezing here>
```

**Comment by yury-s** [comment]
Looks like a bug in how you pass eval parameters in https://pastebin.com/raw/UjYAKxAN. Note that in Playwright you can pass at most [one argument](https://github.com/microsoft/playwright/blob/master/docs/api.md#pageevaluatepagefunction-arg) to the function in eval, otherwise you need to wrap parameters in an object and then destructure it.

Try applying the following patch on top of your changes, it fixed the problem for me:
[fix.txt](https://github.com/microsoft/playwright/files/4555266/fix.txt)

Typescript compiler would have caught that, we should probably do a better job catching this in runtime in playwright and throw when there is more than one parameter.

**Comment by arjun27** [comment]
If you're using VS Code, you can add `//@ts-check` to the beginning of the file to see errors from the TS compiler in the editor.

**Comment by munrocket** [comment]
@arjun27 found another error with it, interesting.
@yury-s Thank you very much! Closing issue.
