### ISSUE TITLE
[BUG] Request does not go through proxy when testing https localhost with Webkit

### ISSUE THREAD

**Issue by chrisbreiding** [microsoft/playwright#20328]
**Context:**

- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: 16.16.0
- Browser: Webkit
- Extra: N/A

**Code Snippet**

Reproduction: https://github.com/chrisbreiding/playwright-webkit-https-localhost-proxy-issue

**Describe the bug**

I'm running my site locally on https. I have a proxy configured that works fine with Chromium, but when I run tests with Webkit, requests don't seem to go through the proxy.

**Comment by pavelfeldman** [comment]
This is a known cfNetwork (macOS network stack) limitation, we have it filed upstream. Same would happen for regular http.

**Comment by mxschmitt** [comment]
Linking the upstream reports to it:

- https://github.com/mxschmitt/cfnetwork-localhost-proxy
- https://developer.apple.com/forums/thread/681009

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
