### ISSUE TITLE
[Feature] function "page-screenshot-option-mask" for automatic screenshots

### ISSUE THREAD

**Issue by frankaigner** [microsoft/playwright#20375]
For screenshots there is the option "mask" to mask sensitive data.
See: [page-screenshot-option-mask](https://playwright.dev/docs/api/class-page#page-screenshot-option-mask)

Unfortunately, this option is not available for "automatically capture a screenshot after each test" function. It would be helpful if you can activate "automatically capture a screenshot after each test" with "on" or "only-on-failure" and then give a regex as a parameter to mask sensitive data.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
