### ISSUE TITLE
[Question] Vitest and Playwright configuration

### ISSUE THREAD

**Issue by fab-mindflow** [microsoft/playwright#20390]
We are using Vitest as a global test runner on a large project and we would like to know how to setup and fine-tune the configuration as it is done when using Playwright as the test runner. 

The [playwright-vitest documentation](https://playwright.dev/docs/test-runners#vitest) is fairly simple and does not point to anything. We haven't also found any hint how to do it.

For example, how to set properties like `actionTimeout` or `expect { timeout: 5000 }` that are usually found in `playwright.config.ts` ?

**Comment by mxschmitt** [comment]
We recommend the Playwright test-runner @playwright/test since it gives you a config, HTML report, sharding, tracing+video+screenshot on/off/on-first-retry, retries, VSCode integration with Playwright utilities, handy assertions like toHaveText, toHaveScreenshot etc. see [here](https://playwright.dev/docs/library#key-differences) and much more.


If you want to use a different test-runner, then you need to setup everything manually like tracing, and timeout handling.

**Comment by fab-mindflow** [comment]
Thanks. That makes lot of sense.
It may help to indicate the limitations in the documentation too.
