### ISSUE TITLE
[BUG] downloads in Electron application not handled

### ISSUE THREAD

**Issue by ajafff** [microsoft/playwright#20445]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows 10
- Node.js version: 16.18.0
- Browser: Electron 22.1.0

**Code Snippet**

```javascript
// index.js
const {app, BrowserWindow, session} = require('electron');
const path = require("path");

app.whenReady().then(() => {
    // uncomment this to bypass the save file picker
    //session.defaultSession.on('will-download', (_, item) => {
    //    item.setSavePath(path.join(app.getPath('downloads'), item.getFilename()));
    //});

    const win = new BrowserWindow();
    win.loadFile('./index.html');
});
```

```html
<!-- index.html -->
<a href="data:text/plain,foo" download="foo.txt">click!</a>
```

```js
// test.js
const {_electron: electron} = require('playwright');

(async () => {
    const app = await electron.launch({
        args: ['index.js'],
        acceptDownloads: true,
    });
    const win = await app.firstWindow();
    const [download] = await Promise.all([
        win.waitForEvent('download'),
        win.click('a'),
    ]);
    console.log(download.suggestedFilename());
    await app.close();
})();
```

**Describe the bug**

Running `node ./test.js` should log "foo.txt" to console and exit. Instead it times out waiting for the download event.

Note that you need to manually pick the download path. I would like Playwright to handle that for me. But even if I manually confirm the download or uncomment the code that bypasses the save file picker, it still times out.

Running a similar script with Chromium works as expected. This leads me to believe that this functionality is not yet implemented for Electron.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
