### ISSUE TITLE
[Feature] Restrain sending http credentials on a specific hostname

### ISSUE THREAD

**Issue by SebastienRichert** [microsoft/playwright#20464]
Let's consider doing a navigation on a page that requires HTTP authentication. From the browser, this would typically show a dialog prompting for user credentials.

With Playwright, this pair of string "username" and "password" can be set on the browser context with the code below: 

`const context = await browser.newContext({httpCredentials: { username: 'user', password: 'pass' }`

That allows Playwright to use these credentials when any servers respond with HTTP 401 unauthorized, in order to secure the connection. This works fine regardless of the HTTP authentication mecanism: basic, ntlm, kerberos...

However, we have a concern in terms of security, about these credentials being sent to any servers, other than the one we specified the credentials for. 

In order to restrain sending HTTP credential to only the expected server, we would like to have the ability to specify a hostname, additionaly to the current pair username/password set on the browser context. So when an authorization response is received from servers, the credentials are sent only if the server hostname in the request matches case insensitive the specified hostname. Otherwise, if the hostname does not match, then the credentials wouldn't be sent, same as if no credentials were configured (likely causing the server to fail the authorization and return 401 HTTP status). 

Also, in order to not break the compatibility with previous project, that additional parameter for the hostname needs to be optional. When not present, it should behave exactly the same way as before, namely always sending the credentials to any server.

We submitted a PR for that matter: #20374. We could also consider a more advance matching algorighm if you prefer (such as regexp on full request path), but we thought doing a simple string compare of the full hostname could be enough as a first step. Later, we are also interested into improving the Java wrapper.

**Comment by dgozman** [comment]
Chromium [caches http credentials](https://source.chromium.org/chromium/chromium/src/+/main:net/http/http_auth_cache.h;l=26-33;drc=cc67230216085a28c28177f5601fb3079198f774) per `origin + realm + scheme`, where:
- `origin` is scheme+host+port of the request;
- `realm` is the auth realm;
- `scheme` is the auth scheme.

See [WWW-Authenticate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate#directives) for realm/scheme descriptions.

We should do the same with our API - specify `origin` instead of `hostname`. If it is easy to add optional `realm`/`scheme` fields for all browsers, we can also do that.

**Comment by pavelfeldman** [comment]
@SebastienRichert: looks like we need to use origin instead of the hostname as per @dgozman , pleas ack!

**Comment by SebastienRichert** [comment]
@pavelfeldman: Completely agree ! We'll update the PR to have the parameter "origin" as optional string, and comparing it with the auth origin along the 3 fields (scheme + host + port).
