### ISSUE TITLE
[BUG] List reporter: { printSteps: true } option doesn't work 

### ISSUE THREAD

**Issue by ausievich** [microsoft/playwright#20534]
**Context:**
- Playwright Version: 1.28.1
- Operating System: macOS Monterey
- Node.js version: v14.21.2
- Browser: Chromium

**Code Snippet**

```
reporter: [
        ['list', { printSteps: true }]
]
```

**Describe the bug**

Hi, when I set up reporter in my `playwright-ct.config.ts` file `['list', { printSteps: true}]` acts the same as just `['list']`. Please, check if this is a bug, or maybe I am doing something wrong. Thanks

https://playwright.dev/docs/test-reporters#list-reporter

**Comment by dgozman** [comment]
@ausievich This works for me with v1.28.1:

```js
const config = {
  reporter: [ ['list', { printSteps: true } ] ],
};
```

```
  ✘  1 example.spec.ts:8:5 › Example Test (9.8s)
     1.1 Example Test › step 1 (3.3s)
     1.2 Example Test › step 2 (3.1s)
     1.3 Example Test › step 3 (3.0s)
```

If you could share a repro that we can run locally, we'd take a look.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.

**Comment by acidoxee** [comment]
@bobrosoft thanks, I was just wondering why this didn't work in CI 😕

Is there any way to force the display of steps anyway? This is IMHO the best (and also the only?) alternative to adding `DEBUG=pw:api` to all Playwright calls, otherwise you have almost no feedback during test execution of what's going on for long-lived tests. Since the debug option is _extremely_ verbose, it's clearly not ideal.
