### ISSUE TITLE
How to use playwrite to log in as various users in another ntlm domain?

### ISSUE THREAD

**Issue by danpoleary** [microsoft/playwright#2053]
The concept of whitelist does not apply.

I have a Dynamics CRM application that has various teams with roles. We created one test account for each role. Since where we work does not allow development/test workstations in the same domain, how do I navigate the ntlm popup window when in headless mode. 

I can navigate the popup using JavaScript when using full browser UI, but nothing seems to work in headless.

Thanks

**Comment by arjun27** [comment]
Thanks @danpoleary. I don't have experience with ntlm domains, but have you considered using [the `popup` event](https://github.com/microsoft/playwright/blob/master/docs/api.md#event-popup) to interact with the popup windows? Since you're also using multiple accounts, it might be also worth exploring using [separate browser contexts](https://github.com/microsoft/playwright/blob/master/docs/core-concepts.md#browser-contexts) for each account. Feel free to let me know if these help/don't help and if you have any feedback on our docs.

**Comment by danpoleary** [comment]
Hi @arjun27, That popup works for browser popups that are HTML, but NTLM is a system popup handled by the browser. I can navigate it using javascript when in full UI mode, but cannot while headless. 

It can be done using whitelist and browser profiles if in same domain, but this does not work in different domain.

**Comment by yury-s** [comment]
@danpoleary how do you handle the system popup in headful mode, can you attach a snippet?

**Comment by aslushnikov** [comment]
(Closing this as a part of summer cleanup since the discussion stalled here)
