### ISSUE TITLE
[BUG] channel: 'chrome' in a config is not working, ERROR: Playwright does not support chromium on ubuntu18.04

### ISSUE THREAD

**Issue by xblurx** [microsoft/playwright#20533]
**Context:**
- Playwright Version: 1.29.0
- Operating System: ubuntu 18.04
- Node.js version: 14:alpine
- Browser: Chromium
- Extra: 
OS: Linux 4.18 Ubuntu 18.04.5 LTS (Bionic Beaver)
Memory: 34.65 GB / 62.89 GB
Container: Yes
Binaries:
Node: 14.17.2 - /usr/bin/node
Yarn: 1.22.11 - /usr/bin/yarn
npm: 6.14.13 - /usr/bin/npm
 Languages:
Bash: 4.4.20 - /bin/bash
npmPackages:
playwright-testing-library: 2.7.2 => 2.7.2 
all of this ^ is from docker image mcr.microsoft.com/playwright:1.13.0-bionic (I know it's very old, and maybe I should't be using it if I'm installing the browsers via `npx install playwright` anyway, but that's what we have in a repository.

**Code Snippet**

the config:

```javascript
const config: PlaywrightTestConfig = {
    testDir: './src/__tests__/e2e',
    testMatch: /.*.ts/,
    timeout: 30 * 1000,
    expect: {
        timeout: 5000,
    },
    fullyParallel: true,
    forbidOnly: !!process.env.CI,
    retries: process.env.CI ? 2 : 0,
    workers: process.env.CI ? 1 : undefined,
    use: {
        browserName: 'chromium',
        actionTimeout: 0,
        trace: 'on-first-retry',
        channel: 'chrome',
    },

    /* Configure projects for major browsers */
    projects: [
        {
            name: 'chromium',
            use: {
                channel: 'chrome',
                ...devices['Desktop Chrome'],
            },
        },
    ],

};

```

**Describe the bug**
Hi, although I set `channel: chrome` in the config which was suggested in https://github.com/microsoft/playwright/issues/19548 wherever possible, the ci fails when executing `npx install playwright` which should install the required browsers.
ci output: 
Failed to install browsers
Error: ERROR: Playwright does not support chromium on ubuntu18.04

**Comment by mxschmitt** [comment]
First of all, I'd strongly recommend upgrading to Ubuntu focal or yammy, your Docker image which you are using should always match to the Playwright version you are using, otherwise browsers and dependencies have to be downloaded again.

If we look at this Ubuntu 18 bionic scenario, I just tried it out and Firefox & Chromium was working for after installing browser and deps (`npx playwright install --with-deps`).

If you use `channel: 'chrome'` inside your config, this means that you are using the Google Chrome Stable channel, so you need to install it manually with `npx playwright install chrome`. I tried this is as well and it was working for me.

**Comment by mxschmitt** [comment]
`npx playwright install chrome --with-deps` should be enough.

**Comment by xblurx** [comment]
thanks a lot, have a great day
