### ISSUE TITLE
PDF generation converts relative links to absolute

### ISSUE THREAD

**Issue by nickbelling** [microsoft/playwright#20582]
When a page contains a relative link to a file, the resultant link seems to be converted to an absolute (e.g. `file://`-prepended) link in the final PDF output, even if the link inside the HTML itself is relative.

For example:

```cs
// "page.html" contains "<a href="./some-other-file.pdf">"
using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync(
    new BrowserTypeLaunchOptions
    {
        Headless = true,
        Channel = "chrome"
    });
await using var context = await browser.NewContextAsync();
var page = await context.NewPageAsync();
await page.GoToAsync("/path/to/page.html", new PageGotoOptions { WaitUntil = WaitUntilState.NetworkIdle });
await page.PdfAsync(
    new PagePdfOptions
    {
        Path = "/path/to/page.pdf"
    });
// page.pdf has absolute link to file://path/to/some-other-file.pdf, meaning the resultant PDF isn't portable
```

**Comment by dgozman** [comment]
@nickbelling Here is the upstream Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=931511. When Chromium provides an option, we can use that in Playwright. I'll leave this issue open for now.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
