### ISSUE TITLE
[Feature] dragTo across pages/browsers

### ISSUE THREAD

**Issue by Blitzlord** [microsoft/playwright#20714]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows 10 / WSL -> Ubuntu 22.04
- Node.js version: 16.17.1
- Browser: Chromium, Firefox

**Code Snippet**

``` 
// Browser 1
const browserA = await playwright.chromium.launch();
const contextA = await browserA.newContext();
const pageA = await contextA.newPage();

// Browser 2
const browserB = await playwright.chromium.launch();
const contextB = await browserB.newContext();
const pageB = await contextB.newPage();

await Promise.all([
  pageA.goto('https://example.com/drag-source'),
  pageB.goto('https://example.com/drag-target'),
]);

const source = await pageA.$('#drag-source');
const target = await pageB.$('#drop-target');

 await source.dragTo(target , {
      targetPosition: { x: 100, y: 100},
 });

```

**Description**
`.dragTo()` doesn't work when dragging elements **to a different `page`** (Different browser context).

As a result, the dragTo operation is being applied to the source page. 
In this example the `source` is being dropped inside the `pageA` context at position x:100,y:100
I would expect the `source` to be dropped inside the `pageB` context, because thats where the `target` is located.
The W3C Drag & Drop API allows dragging between different browsers/pages/applications. 
So it would be great to test those scenarios.

**Comment by infinigis** [comment]
Chiming in to state that this would be a useful feature for us.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
