### ISSUE TITLE
[Feature] use the proxy environment variables by default

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#20741]
https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-option-proxy

if `proxy` is not specified, it should check to see if the `https_proxy` and `no_proxy` environment variables are set instead. i just spent all day trying to figure out what was wrong with my proxy config only to realize that playwright for some reason does not respect these variables.

**Comment by mxschmitt** [comment]
We'll fallback to browser behavior as of today and how they deal with it. In their case most of they respect the following env variables:

```go
fmt.Sprintf("http_proxy=%s", workerProxy),
fmt.Sprintf("HTTPS_PROXY=%s", workerProxy),
// Firefox needs it currently in lower-case. See
// https://github.com/microsoft/playwright/issues/6094
fmt.Sprintf("https_proxy=%s", workerProxy),
```

that's what I'm using with [Try Playwright](https://github.com/mxschmitt/try-playwright/blob/5a7eb101d7dd164c4700deae1dfef566128d84a2/internal/worker/worker.go#L90-L94) and it works. Would that work for you?

**Comment by DetachHead** [comment]
i think my issue may have been that it was respecting `https_proxy` and `http_proxy` but not `no_proxy`

also, i think most things use the lowercase variables https://unix.stackexchange.com/a/212972

**Comment by mxschmitt** [comment]
Sounds like more a feature requests to browsers rather than a feature request to Playwright to me. if you want to have it implemented, you can just do the following in the user-land: 

```
{ server: process.env.HTTPS_PROXY || process.env.http_proxy || process.env.https_proxy, bypass: process.env.no_proxy }
```

I think the issue is that there is no standard and everyone implements [what](https://unix.stackexchange.com/questions/212894/whats-the-right-format-for-the-http-proxy-environment-variable-caps-or-no-ca/212972#212972) [they](https://github.com/microsoft/playwright/issues/6094#issuecomment-817392472) [want](https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/#background).

**Comment by DetachHead** [comment]
Imo browsers are more user facing so theyre less likely to respect these environment variables when both windows and MacOS have their own proxy config menus. 

Playwright on the other hand is developer facing which is why I'd expect it to respect these variables

**Comment by aslushnikov** [comment]
> imo browsers are more user facing so theyre less likely to respect these environment variables when both windows and MacOS have their own proxy config menus.
> Playwright on the other hand is developer facing which is why I'd expect it to respect these variables

Ironically, we kinda follow this rule:
- Playwright is a library, so Playwright itself respects `HTTP_PROXY` and `HTTPS_PROXY` (e.g. when downloading browser builds)
- Playwright provides means to change browser behavior as you wish, while keeping defaults reasonably intact.

Let's mark this as P3 to gauge interest.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by dajose** [comment]
> > imo browsers are more user facing so theyre less likely to respect these environment variables when both windows and MacOS have their own proxy config menus.
> > Playwright on the other hand is developer facing which is why I'd expect it to respect these variables
> 
> Ironically, we kinda follow this rule:
> 
> * Playwright is a library, so Playwright itself respects `HTTP_PROXY` and `HTTPS_PROXY` (e.g. when downloading browser builds)
> * Playwright provides means to change browser behavior as you wish, while keeping defaults reasonably intact.
> 
> Let's mark this as P3 to gauge interest.

@aslushnikov did you also check for NO_PROXY?
