### ISSUE TITLE
[Feature] APIRequestContext to be able to modify the configuration

### ISSUE THREAD

**Issue by MichalFidor** [microsoft/playwright#20750]
Hi there. In our company we've decided to use Playwright also to testing the backend. During creating the PoC of this framework as a solution for our needs it went pretty good. But one thing comes out during creating the context for different users. 

As an example in the documentation, you are creating the context with the Bearer token taken from the environment variables. But in my usage I can get this token only by sending a proper auth request and later on creating a new context and injecting this token from first context, to the new one. So I need to create two different contexts.

Second thing is, that I need to create also a different context if baseUrl will change. In my project I have shared token for two different baseUrls. So in this way I need to create a two different context with two different baseUrls but with the same token.

So as a summary - It would be great if we could have possibility to modify the existing context by updating its configuration. So for example having it in this way:

```
const requestContext = await request.newContext();
const { access_token } = (await requestContext.post(`<url_token>`, { form: <some_data> })).json();
requestContext.updateHeaders('add', { "Authorization": "<access_token>" });
requestContext.updateUrl('<new url>');
... etc
```

It will be beneficial, because at the moment if we would like to have context modified we need to create a new one and use it.

**Comment by mxschmitt** [comment]
Sounds not of a big hassle to maintain two contexts, you can also just have a single one and pass the values (absolute URL + headers) manually to one if its e.g. only about one request. From our side we'd try to avoid things like this, since most of our APIs allow only on creation to set some options, they cannot be changed later on.

**Comment by MichalFidor** [comment]
Maybe it's not a big issue for maintaining two different context, but it's useless to create multiple contexts just for update one header or some other parameter. Also in the code it's more 'messy'. In my case, it's not only one request which need to have different params. But okay, if you would like to avoid things like this, then it's fine I'll find some other way to not create more contexts than one. ;)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
