### ISSUE TITLE
[BUG] Not able to install the Playwright latest version - Error is displayed for Browser webkit installation

### ISSUE THREAD

**Issue by Dharsana-k-Gupta** [microsoft/playwright#20775]
**Context:**
- Playwright Version: Trying to install first time
- Operating System: Windows
- Node.js version: 18.14.0
- Visual Studio Code version: [e.g. 1.65]
- Playwright for VSCode extension version: v1.0.7
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:
![image](https://user-images.githubusercontent.com/42764355/217799145-766b5dba-d2fa-4a92-89d2-f21d67a1a85d.png)

Add any other details about the problem here.
When the command is executed via Terminal or Using Test extensions, installation of webkit fails- please refer the attached screenshot.

**Comment by mxschmitt** [comment]
Looks like your proxy which is configured is blocking the access and putting a self signed certificate in the response. You can try to manually open the URL in the browser or try to curl it to find out more about this issue.

This is not a Playwright issue, its caused by the configuration on your end.

**Comment by mxschmitt** [comment]
We unfortunately cannot act on this, since this is not a Playwright issue and more a configuration issue on your environment. I recommend trying out https://playwright.dev/docs/browsers#install-behind-a-firewall-or-a-proxy or looking on StackOverflow how this is done with Node with your proxy configuration.

If you have any findings, feel free to reply here or send a patch to update the docs.
