### ISSUE TITLE
[Feature] Locator based on image matching

### ISSUE THREAD

**Issue by MikeGalyen** [microsoft/playwright#20794]
For cases where standard locators are not relevant because standard selectors like class, element, id, x-path, etc are not accessible,  it would be great if there was a locator that would take a png file as an argument to create an object based on an image. This way you could click or perform other actions on an element or area based on image matching.

This would be useful for lots of people doing visual regression testing.

**Comment by MikeGalyen** [comment]
Being able to say:
if (image exists) {do this thing}
would be a great way to use this feature if it existed.

**Comment by andreabisello** [comment]
I totally agree.
in the meanwhile if you are using python you can mix playwright with PyAutoGui using the locateOnScreen method

**Comment by MikeGalyen** [comment]
@andreabisello I'll try that. Thanks!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by mofojed** [comment]
This would be very handy, as some elements like an interactive `canvas` element, it's easier to locate using an image for where to click rather than figure out the coordinates within the canvas.
