### ISSUE TITLE
[BUG] selection tests fail after last WebKit roll

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#20820]
WebKit upstream changed the default value of this preference from `false` to `true` in https://github.com/WebKit/WebKit/commit/1226d38de5c750fc736ce7075e86e248674ee430.

The tests which were broken, see https://github.com/microsoft/playwright-browsers/pull/262#issuecomment-1425592143.

This got discussed on Slack see https://playwright.slack.com/archives/G013Z9QND41/p1676027021400889?thread_ts=1675978738.312799&cid=G013Z9QND41.

**Comment by yury-s** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=252281 upstream, let's see if it's expected change in the behavior.

**Comment by yury-s** [comment]
Discussed this in the meeting today. Looks like we are building with [unstable](https://github.com/WebKit/WebKit/blob/ccfd01b632764a159c85d87820010fe7a0f9fc12/Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml#L28-L30) features and we should try switching to [preview](https://github.com/WebKit/WebKit/blob/ccfd01b632764a159c85d87820010fe7a0f9fc12/Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml#L34-L36) or even 'stable' to better match upstream. In that case we'd not have this problem at all because the feature is still in an earlier (testable) state.
