### ISSUE TITLE
execute Script for click element in Playwright Java

### ISSUE THREAD

**Issue by habsyi03** [microsoft/playwright#20890]
Hi, I has used selenium java before using playwright java.

I have one question about click using javascript code.

in selenium the code is like below:
```
String script = "arguments[0].click();";
JavascriptExecutor.executeScript(script, driver.findElement(locator));
```

I have tried using code below:
`page.locator("//mat-label[contains(text(),'Mata Uang')]/span").click();`
And also I have tried using evaluate like below code:
`page.evaluate("arguments[0].click()","//mat-label[contains(text(),'Mata Uang')]/span");`
but the code can't interact with that element.

Btw, the element is also can't interact with selenium, but with javascriptExecutor it's running properly.

Kindly need help how to handle element for click by using javascript in Playwrigt java. Thanks

**Comment by imartinflores** [comment]
@habsyi03 have you tried something like:

`await page.evaluateHandle(()=>document.getElementsByClassName('locator')[0].click());`

**Comment by aslushnikov** [comment]
@habsyi03 this looks more like a general programming question rather than a "something's wrong with playwright!" issue.

I'd recommend reading https://playwright.dev/java/docs/locators to learn all about locators and how to use them in Playwright.

If things still don't work, then please engage in a discussion on our discord: https://aka.ms/playwright/discord

if you do think that Playwright is misbehaving, than please, file a new issue following the issue template. It should have a good reproduction that we can run locally to debug.

Thanks!
