### ISSUE TITLE
[BUG] Entering pointer lock triggers a DOM Exception in Chromium

### ISSUE THREAD

**Issue by guillaumebrunerie** [microsoft/playwright#20956]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Mac OS Ventura
- Node.js version: 19.6.0
- Browser: Chromium
- Extra: 
### System:
 - OS: macOS 13.0.1
 - Memory: 408.24 MB / 16.00 GB
### Binaries:
 - Node: 19.6.0 - /usr/local/bin/node
 - npm: 9.4.0 - /usr/local/bin/npm
### Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

```javascript
import {test, expect} from "@playwright/test";

test("should be able to use pointer lock", async ({page}) => {

	// Fail on exception
	page.on("pageerror", (event) => {
		expect(true, event.message).toBe(false);
	});

	await page.evaluate(() => {
		const input = document.createElement("input");
		input.addEventListener("pointerdown", () => {
			input.requestPointerLock();
		});
		input.addEventListener("pointerup", () => {
			document.exitPointerLock();
		});
		document.body.appendChild(input);
	});
	await page.locator("input").click();
});

```

**Describe the bug**

I'm trying to test a page that uses pointer lock and when running it with Playwright in Chromium, I get a DOM exception `Error: The root document of this element is not valid for pointer lock.`.
Firefox and Safari seem to work (at least for this extremely simple test case, I haven’t tested yet if the functionality of pointer lock actually works).

**Comment by dgozman** [comment]
For the record: `RenderWidgetHostVewMac` prohibits pointer lock because the view is not focused.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by bbowman** [comment]
@pavelfeldman I am also encountering this now, any chance it can be reopened?

**Comment by lukehb** [comment]
@pavelfeldman I am also hitting this.

**Comment by bschlenk** [comment]
I am hitting this as well. Even if it did work, does playwright have an api to send _relative_ mouse movement? It looks like all mouse apis take in absolute coordinates, which don't really make sense once you're in pointerlock.
