### ISSUE TITLE
[Question] How to remove the geo location Error for particular website

### ISSUE THREAD

**Issue by testandlearnforlife** [microsoft/playwright#21044]
**Context:**
- Playwright version[1.26]
- Operating System: [e.g. Windows]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]

I get geo complay location Error which is specfic to the website, I am runing in my Local machine and the website needs the geo location  to be installed to complay the location check.
Is there any way I can by pass the location geo complay Error ?

**Comment by yury-s** [comment]
You can emulate custom geo location as described in [this document](https://playwright.dev/docs/emulation#geolocation), will that work for you?

**Comment by testandlearnforlife** [comment]
I tried using below
await context.setGeolocation({ longitude: 21, latitude: 21 });
It does not work for this website as It has a model to be downloaded and installed.

when I try to download the modal, It gets saved in AppData/Local/Temp folder, is there any way to download the model and use It for automation.

when I run manually in my machine, it works fine as the modal is installed in my machine.

thanks , let me know if my explaination was clear.

**Comment by yury-s** [comment]
Can you elaborate on what you mean by "It has a model to be downloaded and installed." ? How does the app save the model and how does it install it?

> when I run manually in my machine, it works fine as the modal is installed in my machine.

What exactly is not working when it's running under playwright, is the model not loading? Sorry, but I'm not following what it has to do with the current geolocation returned by the browser, can you explain.

It would be the easiest if you could share the code and the web app so that we could try that locally.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
