### ISSUE TITLE
[BUG] Playwright Android not working in Oppo & Xiaomi devices

### ISSUE THREAD

**Issue by Archish27** [microsoft/playwright#21049]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Mac OS X
- Node.js version: 16.16.0
- Browser: Chrome
- Extra: [any specific details about your environment]

```shell
DEBUG='pw:*' node server.js >> server.log 2>&1
DEBUG='pw:*' node client.js >> client.log 2>&1
```

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { _android } = require('playwright');
const testFn = async () => {
  const before = Date.now();
  const device = await _android.connect(`ws://127.0.0.1:56531/032b62332e0d72e20a5970a24dc3143f`);
  const after = Date.now();
  console.log('connected in ', (after - before) / 1000);

  console.log(device.model());
  console.log(device.serial());
  await device.shell('am force-stop com.android.chrome');
  console.log('here1');
  console.log('here2');
  const context = await device.launchBrowser();
  console.log('here3');
  const page = await context.newPage();
  console.log('here4');
  await page.goto('https://duckduckgo.com/')
  console.log('here5');
  await context.close();
  await device.close();
}
testFn();

```

**Describe the bug**

Unable to run playwright android session in Oppo & Xiaomi devices. `launchBrowser` command gets stuck which can been seen in client logs
Sharing playwright client & server logs.
[client.log](https://github.com/microsoft/playwright/files/10792031/client.log)
[server.log](https://github.com/microsoft/playwright/files/10792036/server.log)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
