### ISSUE TITLE
[BUG] Unable to click an element within frame

### ISSUE THREAD

**Issue by aziizpc** [microsoft/playwright#21054]
**Context:**
- Playwright Version: v1.30.0
- Operating System: Windows
- Node.js version: v18.14.1
- Browser: All

**Code Snippet**
await page.goto("https://rahulshettyacademy.com/AutomationPractice/");
const frame_1 = page.frameLocator("#courses-iframe");
await frame_1.locator("li a[href*='lifetime-access']:visible").click();

**Describe the bug**
The element within the frame 'frame_1' is not getting clicked.

**Comment by yury-s** [comment]
It seems that the iframe is being throttled while it's not on the screen. As a temporary workaround you can call `  await page.locator("#courses-iframe").scrollIntoViewIfNeeded();` to reveal the iframe before doing the click.

Long-term we should fix the issue so that manual scrolling is not required. Debugging notes: [ThrottleDisplayNoneAndVisibilityHiddenCrossOriginIframes](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/common/features.h;l=939;drc=08e345a4de7e4fa2077fad13f53b4aa2d24cb65e) might be relevant.

**Comment by aziizpc** [comment]
Thanks! It's working fine with the above workaround.
