### ISSUE TITLE
[BUG] URLs opened via Chrome Extension API are not intercepted

### ISSUE THREAD

**Issue by db-dblank** [microsoft/playwright#21061]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Mac
- Node.js version: 16.13.0
- Browser: Chromium
- Extra: Running on Chrome Extension MV3

**Code Snippet**

```javascript
await context.route('**/*', (route) => {
  console.log('url', route.request().url());
  return route.continue();
});

// This is not intercepted
await chrome.tabs.create({ url });

// This is not intercepted
await chrome.windows.create({ url });

// This is intercepted
window.open(url, '_blank');
```

**Describe the bug**

URLs opened via Chrome Extension API are not intercepted.

**Comment by yury-s** [comment]
Looks like it's not currently instrumented upstream in Chromium.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
