### ISSUE TITLE
[Feature] Add Edge to the command line browser option

### ISSUE THREAD

**Issue by jwerre** [microsoft/playwright#21186]
When you try to run Playwright from the command line in Edge this is the result:

```
playwright test --headed --browser=msedge

Error: Unsupported browser "msedge", must be one of "all", "chromium", "firefox" or "webkit"
    at runTests (/Users/jw/Work/surveyplanet/svelte_components/node_modules/@playwright/test/lib/cli.js:122:79)
    at ji.<anonymous> (/Users/jw/Work/surveyplanet/svelte_components/node_modules/@playwright/test/lib/cli.js:71:7)
```

... come on Microsoft :)

**Comment by yury-s** [comment]
Browser [type](https://playwright.dev/docs/api/class-browsertype) and [browser channel](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) are conceptually different in Playwright and controlled by different entities in the API. We'd actually like to remove the `--browser` parameter altogether and recommend `--project` instead but we cannot do this because of the existing clients. Usually one already has a separate [project](https://playwright.dev/docs/api/class-testproject) configured for running MS Edge tests and when starting from command line you can just pass the project name in `--project`. Note that for the commands like `codegen` and `open` that don't require playwright.config.ts we support --channel parameter that does what you are asking for but for `playwright test` we recommend using `--project`.

Closing the issue as we are not planning to support this due to the reasons described above.
