### ISSUE TITLE
[Feature] New headless chrome

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/playwright#21194]
Is it already possible to use new headless chrome with playwright?
https://developer.chrome.com/articles/new-headless/

**Comment by yury-s** [comment]
You can give it a try today, most of the stuff will work but we don't run our tests with it yet and some tests are know to fail, so be prepared for some functionality working in the current headless mode but failing in the new one:
```ts
  projects: [
    {
      name: 'chromium',
      use: {
        launchOptions: {
          ignoreDefaultArgs: ['--headless'],
          args: ['--headless=new']
        }
      },
    },
```

We'll announce separately when the new mode is fully supported.

**Comment by Smrtnyk** [comment]
tnx, I gave it a try, but it is spamming the playwright inspector windows being open, while browser was still in headless mode, and I had to press play all the time in order for tests to actually continue.
I guess I will wait for an official support.

**Comment by cunhabruno** [comment]
Why do we need to set ` ignoreDefaultArgs: ['--headless']`?

**Comment by mirao** [comment]
@yury-s I think the correct option is `ignoreDefaultArgs: ['--headless=old']` instead of `ignoreDefaultArgs: ['--headless']`

Just tested it in CodeceptJS + Playwright.

- When I use `ignoreDefaultArgs: ['--headless']`, Chromium will start with both options `--headless=old` and `--headless=new`. The new headless mode works in such case, but passing of both parameters is ambiguous.
- When I use `ignoreDefaultArgs: ['--headless=old']`, Chromium will start without the option `--headless=old`, but with `--headless=new` enabled which is what I expect

**Comment by mirao** [comment]
> @yury-s I think the correct option is `ignoreDefaultArgs: ['--headless=old']` instead of `ignoreDefaultArgs: ['--headless']`

I guess it might change by time. Maybe the older Chromium versions used `--headless`.
I'm testing it with Playwright 1.46.1 with Chromium 128
