### ISSUE TITLE
[Feature] When we pass to headless='new'  parameter?

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#21216]
https://developer.chrome.com/articles/new-headless/#whats-new-in-headless

As we know,google chrome introduced headless='new' .

When we pass this mode?

**Comment by Smrtnyk** [comment]
I already asked this
https://github.com/microsoft/playwright/issues/21194
however, for me it doesn't work because it spam opens playwright inspector windows in headless mode
so will just wait until they officially support it

**Comment by pavelfeldman** [comment]
We will switch to it eventually, but at this point it is 30-50% slower than the stock headless. If you'd like this option to be enabled, please file a request explaining what you'd like and why you need headless=new to achieve it. We need to understand how many users need this new behavior and why in order to enable it.

**Comment by YusufOzt** [comment]
@pavelfeldman if speed decrease about 30-50 ,no need, thanks for response. Closing

**Comment by kapouer** [comment]
I'm also seeing that new headless runs at 40% the speed of legacy headless, using official chrome stable 113.
