### ISSUE TITLE
[BUG] Trace Viewer not presenting timeout interval when element not located 

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#21224]
**Context:**
- Playwright Version: 1.31
- Operating System: Windows 11
- Node.js version: v18.14.1
- Browser: Chromium
- Extra: Base on default project after running `npm init playwright@latest`

**Test**
Config modification: `trace: 'on'`
Below test has intentionally broken `name: 'Get started-x'`
```typescript
import { test, expect } from '@playwright/test';

test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started-x' }).click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});
```

**Describe the bug**
After running above test, the report is presented with clear information: `Test timeout of 30000ms exceeded.`  
But In Trace Viewer there is no information about **timeout interval** and only short description `Action was interrupted`.

![obraz](https://user-images.githubusercontent.com/72373858/221540917-a4cda185-fdb2-4dfb-84f7-3d074a636c66.png)

Timeline ends at 700ms time what is misleading to.

**Expected**
Full timeline of test with timeout interval in Trace Viewer.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
