### ISSUE TITLE
Using the webServer config with a Vite dev server?

### ISSUE THREAD

**Issue by coreybyrum7** [microsoft/playwright#21227]
### Discussed in https://github.com/microsoft/playwright/discussions/18873

<div type='discussions-op-text'>

<sup>Originally posted by **alexbjorlig** November 17, 2022</sup>
I'm trying to use playwright with a [Vite](https://vitejs.dev/) dev server.

In my config I have 
```
webServer: {
        command: 'npm run dev -- test',
        url: 'http://localhost:3000/',
        timeout: 10 * 1000,
        reuseExistingServer: !process.env.CI,
    },
```

But it does not seem to actually work. It simply times out. </div>

**Comment by pavelfeldman** [comment]
Could you share a minimal project we can try it with?

**Comment by thomascullen** [comment]
Not entirely sure but using `127.0.0.1` instead of localhost seems to work for me.

```
webServer: {
    command: 'npm run dev -- test',
    url: 'http://127.0.0.1:3000/',
    timeout: 10 * 1000,
    reuseExistingServer: !process.env.CI,
},
```

**Comment by pavelfeldman** [comment]
> Having a similar issue. Not entirely sure why, but using 127.0.0.1 instead of localhost seems to work for me.

Since Node 18, localhost is resolved to ipv6 by default. If your vite server is listening on ipv4, it won't be discovered.

**Comment by yury-s** [comment]
This was fixed in https://github.com/microsoft/playwright/pull/21104. It will be released in 1.32, you can give it a try in @next

**Comment by pavelfeldman** [comment]
Will be fixed in 1.32.2

**Comment by lxfu1** [comment]
[Same question](https://github.com/antvis/G2Plot/actions/runs/4507404190/jobs/7935153769?pr=3501) !

**Comment by coreybyrum7** [comment]
> Will be fixed in 1.32.2

Thanks for the reply @pavelfeldman. I see this was marked as fixed. Is the original config expected to work in 1.32.2 (with Vite GHA deploy)?

```javascript
webServer: {
   command: 'npm run dev -- test',
   url: 'http://localhost:3000/',
   timeout: 10 * 1000,
   reuseExistingServer: !process.env.CI,
},
```

**Comment by SgtPooki** [comment]
FYI, this was breaking for me too until I switched my config from:

```json

  webServer: {
    command: `npx vite --port ${port}`,
    timeout: 10 * 1000,
    url: `http://127.0.0.1:${port}`,
    reuseExistingServer: !process.env.CI,
  },
```

into


```json
  webServer: {
    command: `npx vite --port ${port}`,
    timeout: 10 * 1000,
    port,
    reuseExistingServer: !process.env.CI,
  },

**Comment by n1k1t0ss** [comment]
Using the port instead of url might be a bad idea. The difference that port could be open much earlier, than server really goes up. https://github.com/microsoft/playwright/issues/11811#issuecomment-1028174490 For example, in angular app, after port opens, angular still requered to build bundels, and after that starts http. So some of my tests was started too earlier.

So, in my case, the problem was in the name of index.html file. It looks like playwright is waiting exactly "index.html" file, and if you deploy it with different name, like "index.test.html" it won't work. Even if you define it corectly in nx configuration, like that - https://github.com/nrwl/nx/issues/2935#issuecomment-858507879 it would work in serve mode, but not for a playwright tests! So I just placed this file in another folder and replaced original file to exact "index.hml"

**Comment by rben01** [comment]
My playwright tests all time out when using a Vite dev server, but succeed when using the preview server.

Fails: ``command: `npx vite --port ${port}` ``

Succeeds: ``command: `npx vite build && npx vite preview --port ${port}` ``

When using my app “by hand”, there is no different between the dev and preview servers. It's only playwright that observes a difference.
