### ISSUE TITLE
[BUG] VSCode debugging restart button doesn't restart test

### ISSUE THREAD

**Issue by stoneman** [microsoft/playwright#21230]
**Context:**
- Playwright Version: 1.31.1
- Operating System: Mac
- Node.js version: 18.13
- Visual Studio Code version: 1.75.1
- Playwright for VSCode extension version: 1.0.7
- Browser: Chromium (not tested others)
- Extra:

**Describe the bug**

When using the restart button in the debugging controls, the test does not restart:
![image](https://user-images.githubusercontent.com/741710/221610699-7fe15020-328a-4bc2-a2bc-19bbf655e9d6.png)

Steps to reproduce:
1. Set a breakpoint and debug any test.
1. When the breakpoint is hit, click the restart button in the debugging controls:
1. The test terminates but does not restart.

When using the restart button in Test Explorer, the test does restart.

**Comment by ATARARHRB** [comment]
yup, this happens to me too, I get around it in the meantime by going back to the Test tab and starting the debugging from there again, but being able to restart it from the drag-around vscode bar would be great.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by tansaku** [comment]
since this issue has been reported and closed twice, I have re-opened it linking back to this issue https://github.com/microsoft/playwright/issues/32655 - I love VSCode, but this gets in the way of my workflow over and over again (almost as much as the limited size in the terminal windows)
