### ISSUE TITLE
[Feature] hotkey for 'Explore' during debug

### ISSUE THREAD

**Issue by canbax** [microsoft/playwright#21249]
Is there any keyboard shortcut for "Explore"? 
![Screenshot 2023-02-18 at 10 53 11](https://user-images.githubusercontent.com/8426741/219848757-eb22ff8a-b6a7-4fc5-8a41-224811718469.png)

When I click on that the focus on the page I'm testing goes away.

**Comment by pavelfeldman** [comment]
Leaving this open, we should make sure we emulate focused page while debugging.

**Comment by pavelfeldman** [comment]
Ok, I thought I could repro it, but I could not. Please provide exact steps that I can follow to reproduce this! We seem to be forcing focused state on the page alright.

**Comment by canbax** [comment]
I observed this when I have 2 screens. On one screen there is the Chromium browser. On the other there is Playwright. In the browser, I hover over an element. On hover, we show a tooltip. I want to use the 'Explore' feature for the tooltip. If I click to 'Explore' the tooltip goes away. So I couldn't find a way.

**Comment by pavelfeldman** [comment]
Ah, so it was not about the focus, it was about the hover. It makes sense that the hover effect will disengage as you move mouse away. Since Playwright Inspector is not in focus, it can't process the explore shortcut w/o injecting key handlers into the target page. We'll think about implementing it.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
