### ISSUE TITLE
[Feature] Give different options than "click" when using codegen

### ISSUE THREAD

**Issue by mickael-h** [microsoft/playwright#21301]
Right now, when you record actions with codegen, it's always translated into a click.
It would be much more versatile to propose different actions to the user instead of assuming a click.
Maestro is a good example of this:
![image](https://user-images.githubusercontent.com/7953005/222138071-9b8158b2-81c1-49a0-ae5d-aab9ed6d1990.png)

In this example, when I clicked "The lastest configuration", Maestro gave me a list of actions to generate for me to choose from.
It would be great to have the same feature in Playwright.

**Comment by MartinB134** [comment]
Even better would be no overlay and just Shift + Click = Assert Visibility, Alt + Click = Assert Element Text for Example. This would make fine-tuning afterward much more efficient. Currently, I use right-click to save elements for assertions. A new context menu there would be even better.

**Comment by chenshuichao** [comment]
A new context menu there would be even better.
+1

**Comment by csterritt** [comment]
Alternatively, add one or more icons to the codegen ui -- for example, an eye-icon for Assert Visibility, a "T" icon for Assert Element Text, others as we see fit. Click the eye, click the item you want to verify existence, done. Perhaps shift-click on the eye "locks" it, so all the next clicks are Assert Visibility until you click the eye again.

**Comment by nikita-kramarovsky** [comment]
I think it would be great if there's a context menu added with some actions and verifications.
This is something that Katalon Studio and Katalon Recorder does fairly well and it makes recording tests a lot easier for less technical QAs.
<img width="500" alt="Screenshot 2023-10-17 at 2 18 23 AM" src="https://github.com/microsoft/playwright/assets/15635841/9d261ca8-bed4-41e5-b9cf-038ce5610079">

They accomplish this by injecting their own chrome extension during the recording session.

<img width="500" alt="Screenshot 2023-10-17 at 2 18 05 AM" src="https://github.com/microsoft/playwright/assets/15635841/c502c970-8ab6-47a4-80b8-5f56ed31f092">

I did some work on a POC extension for playwright that would accomplish something similar 
but there are some issues with getting it to work in playwright codegen. 
the extension is loaded but it fails to active in chromium during test recording (likely because the session starts in incognito mode)

<img width="500" alt="Screenshot 2023-10-17 at 2 59 29 PM" src="https://github.com/microsoft/playwright/assets/15635841/86943392-ed4f-4f68-bffd-611a3fd34694">

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
