### ISSUE TITLE
[REGRESSION]: Firefox is not returning the url of object tags

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#21302]
**Context:**
- GOOD Playwright Version: 1.30
- BAD Playwright Version: 1.31
- Operating System: MacOS
- Extra: No extra details needed

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { test, expect } from '@playwright/test';

test('switch to object', async ({ page }) => {
  await page.goto(
    "https://storage.googleapis.com/public-dev-test-lab/object/index.html"
  );
  const locator = page.mainFrame().childFrames()[0];
  expect(locator.url()).toContain("object_one.html");
});
```

**Describe the bug**

I was able to get the URL of an object element loading an HTML page on firefox using PW 1.30. That stopped working on 1.31.0. This works on Chromium on 1.31.0.

**Comment by pavelfeldman** [comment]
I can repro. Keeping it P3 as objects are not frames strictly speaking, so I don't think our behavior is specified when it comes to treating or not treating them as frames with urls.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
