### ISSUE TITLE
[Question].click not working (working on puppeteer)

### ISSUE THREAD

**Issue by Jordhan-Carvalho** [microsoft/playwright#2135]
Hey there!
While i was converting some of my old puppeteer code to playwright i got stuck... the code snippet is self explanatory

**Code Snippet**

Puppeter code
```javascript
...
      await instagram.page.goto("https://www.instagram.com/explore/tags/dog/");
      await instagram.page.waitFor(1000);
      // Save posts on the recent tab
      const posts = await instagram.page.$$(
        'article > div:nth-child(3) img[decoding="auto"]'
      );
      // click on the post
      await posts[0].click();
...
```
The same code on Playwright 
```javascript
...
      await instagram.page.goto("https://www.instagram.com/explore/tags/dog/");
      await instagram.page.waitForTimeout(1000);
      // Save posts on the recent tab
      const posts = await instagram.page.$$(
        'article > div:nth-child(3) img[decoding="auto"]'
      );
      // click on the post
      await posts[0].click();
...
```
and i'm getting the error
```TimeoutError: Waiting for element to be displayed and not moving failed: timeout exceeded.```
Not sure if its a bug or i'm doing something wrong

**Comment by pavelfeldman** [comment]
When user hovers over an image, Instagram adds an overlay that intercepts the click. Puppeteer simply clicks there, it does not assert what happens as a result. But Playwright's actionability [criteria](https://github.com/microsoft/playwright/blob/master/docs/input.md#mouse-click) (see bullet 5) does not pass since user wants to click one element, but another, completely unrelated element intercepts the click. It is indistinguishable from a bug where a stray element covers the one you are trying to click. To work around the actionability check, pass `force: true` to the click. See the parameter docs [here](https://playwright.dev/#version=v1.0.0&path=docs%2Fapi.md&q=pageclickselector-options--options-force).

```js
await posts[0].click({ force: true });
```

Btw, drop the `await instagram.page.waitForTimeout(1000);` - Playwright waits for the element to be in the DOM anyways, so you should not need it. On a slow network it'll fail and 1 second won't save it.

**Comment by Jordhan-Carvalho** [comment]
Thank you so much for explaining in detail.
