### ISSUE TITLE
[BUG] test.afterAll will return error if test.skip at the last test

### ISSUE THREAD

**Issue by xyngfei** [microsoft/playwright#21363]
### System info
- Playwright Version: v1.27.1
- Operating System: 13.2.1 (22D68)
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

or

**Test file (self-contained)**

```js
import { test } from "@playwright/test";

test.describe.serial("demo", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("https://demo.applitools.com/index_v2.html");
  });

  test.afterAll(async ({ page }, testInfo) => {
    console.log("test: " + testInfo.title.indexOf("@api"));
    await page.close();
  });

  test("111 @demo", async ({}) => {
    console.log("111 test");
  });

  test("222 @demo", async ({}) => {
    console.log("222 test");
  });

  test.skip("333 @demo", async ({}) => {
    console.log("333 test");
  });
});

```

**Steps**
- [Run the test]
- [...]

**Expected**

It should skip the test without any issue
<img width="898" alt="image" src="https://user-images.githubusercontent.com/17619539/222626068-6670f5b4-734b-46cb-bb80-c39a871503c6.png">

**Actual**

![image](https://user-images.githubusercontent.com/17619539/222624280-977b98ba-aab7-4bf8-834a-b405bec531a4.png)

**Comment by pavelfeldman** [comment]
As stated in the error message, you error is that the `{ page }` fixture is used in `afterAll`. Each test has its own `page`, so you don't need to close it after all. `afterAll` can't have any pages, because it runs after all tests.

If you are looking for a serial mode where the page is reused (anti-pattern), you should copy the example from https://playwright.dev/docs/next/test-retries#reuse-single-page-between-tests. Notice that `page` fixture is not used there.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
