### ISSUE TITLE
[Feature] Event when Page is about to get closed and block it from closing

### ISSUE THREAD

**Issue by iustinpericica** [microsoft/playwright#21381]
I would like to be able to get notified in playwright that a page is going to get closed and have a way to block the event of closing.
The existing "close" event on page.on just notifies that page got closed.

My context:

I have CDP (Chrome DevTools Protocol) sessions opened ( `page.context().newCDPSession(page).then(async cdp => {})` ) on each page that gets opened during a test, because I need to take coverage from each.

If the pages wouldn't get closed during the test, it would be easy to go at the end of the test with page.context().pages() and get coverage from all.

The problem is when a page closes during a test, thus the CDP session gets lost, so the coverage.
So, if there would be a way to get notified that a page is going to get closed and ability to pause execution in web app, it would be possible to get coverage before the page closes.

Thank you!

**Comment by pavelfeldman** [comment]
Since you either call page.close yourself or it is closed from the test fixture, you can put your code that collects the coverage before the page is closed. If you are using @playwright/test, this can be achieved via overriding the page fixture and saving coverage in the tardown:

```js
  page: async ({ page }, use) => {
    await use(page);
    // save coverage here.
  },
```

See https://playwright.dev/docs/next/test-fixtures#overriding-fixtures

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
