### ISSUE TITLE
[Question] How to handle dialog boxes opened by an electron application?

### ISSUE THREAD

**Issue by tdNelsonPires** [microsoft/playwright#21432]
Hi team,

I'm not able to interact with a dialog box that is opened by an electron application. The app displays a dialog box when the user tries to quit/force-quit the app like the following image:
<img width="416" alt="Screenshot 2023-03-06 at 16 49 12" src="https://user-images.githubusercontent.com/55986785/223176578-4df2d110-26e7-41ae-a744-b520a9e688ff.png">

In this case, I want to quit or dismiss this dialog but I can't make it work the same way as it was a dialog window opened by a browser page (for example by using a listener). I wonder if this is supported. If so can you give me a hint on how to handle this?

Thank you!

**Comment by mxschmitt** [comment]
I think as of today there is no way to test it, mocking might be the only plausible workaround.

**Comment by tdNelsonPires** [comment]
Thank you @mxschmitt

**Comment by rafael-anachoreta** [comment]
Can this issue be re-opened? This would still be a nice feature to have.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
