### ISSUE TITLE
[BUG] Sharding is not dividing the tests number equally for each shard

### ISSUE THREAD

**Issue by ukdas** [microsoft/playwright#21497]
### System info
- Playwright Version: [v1.31.2]
- Operating System: [Windows 11]
- Browser: [All, Chromium, Firefox, WebKit]

**Steps**
Let's suppose we have 10 test files - 

Test File 1 - 2 tests
Test File 2 - 10 tests
Test File 3 - 10 tests
Test File 4 - 1 tests
Test File 5 - 1 tests
Test File 6 - 2 tests
Test File 7 - 1 tests
Test File 8 - 1 tests
Test File 9 - 1 tests
Test File 10 - 1 tests

Now if we are executing the tests using 3 / 4 shards, ~equal number tests are not getting executed for each shard and it's causing a huge problem for us as we are having 1000+ cases across ~180 files. We are currently using 6 shards, but we see huge number of tests difference for each shard when using latest playwright 1.31.2.

Observed the comment from #21226 that, with new playwright version sharding will be performed on test files.

But I believe, it may cause a big problem for existing projects / new projects, where some feature may have more number of tests than other features. And every time, it will be very difficult for maintaining the count of tests in the test files from user side and instead I believe it should be automatically handled by the playwright framework itself as maintaining / re-factoring tests numbers for each test file will be a big challenge, where multiple users will be working on the repository.

**Expected**

Playwright sharding should divide the tests ~equally for each shard by the playwright framework itself and user don't need to maintain the framework seperately.

**Actual**

Playwright sharding is not dividing the tests ~equally for each shard when using 1.31.2.

**Comment by mxschmitt** [comment]
As per https://github.com/microsoft/playwright/issues/21226#issuecomment-1446693629.

We used to shard tests and now we shard entire files. This improved users' expectations and made the use of beforeAll hooks more efficient, but if you have small number of files and unbalanced numbers of tests in these files, it'll hurt you. The solution would be to balance the file.

So this is an expected change in the last release.

**Comment by garybernhardt** [comment]
We just hit this problem as well. Our suite runtime **more than tripled** after upgrading from 1.30.0 to 1.31.2, because we have one file with hundreds of tests in it. Those tests are created in a loop calling `test(...)` repeatedly to define each test based on some data, so we can't simply split the tests into separate files.

IMO, performance and better sharding are a huge benefit of Playwright over e.g. Cypress, which we switched from. Looking at engagement numbers on my various tweets about Playwright, it seems like the performance aspect also resonates with other people more than the other benefits that I've tweeted about. For example, [this](https://twitter.com/garybernhardt/status/1605633110451683328) tweet about Playwright vs. Cypress performance has been viewed 93,000 times. It starts: "Since porting from Cypress to Playwright, our CI times are down from ~4 minutes to ~2.25 minutes." If I wrote that tweet today, it would say "**Since porting from Cypress to Playwright, our CI times are up from ~4 minutes to ~7.5 minutes**." This change, which isn't even mentioned in the release notes AFAICT, turns one of Playwright's biggest benefits into a serious drawback vs. competing tools.

**Comment by garybernhardt** [comment]
On idea for mitigation: our use case would be fully addressed if we could set a flag saying "please shard this file at the test level rather than at the file level".

**Comment by ukdas** [comment]
Hi @garybernhardt , thanks for more detailed info.


> As per [#21226 (comment)](https://github.com/microsoft/playwright/issues/21226#issuecomment-1446693629).
> 
> We used to shard tests and now we shard entire files. This improved users' expectations and made the use of beforeAll hooks more efficient, but if you have small number of files and unbalanced numbers of tests in these files, it'll hurt you. The solution would be to balance the file.
> 
> So this is an expected change in the last release.

Hi @mxschmitt ,

I do understand that it's modified and expected behaviour in the latest playwright release.

Created this issue to re-consider the approach and provide a way (May be a flag) so that playwright sharding can divide the tests ~equally for each shard to make sure each shard sharing the tests ~equally and also test executions are getting completed fast with the similar test execution time. I beleive, others will also face this issue now.

**Comment by pavelfeldman** [comment]
@ukdas, @garybernhardt thank you for your feedback!

@ukdas I understand that you have 1000+ cases across ~180 files and you run them in 6 shards. Do you use --fully-parallel more when you run locally? Do you have `beforeAll` hooks in these files / describes?

@garybernhardt your tweet hints that you have a generated file with 700 tests. Does this file contain `beforeAll` hooks? I assume you do, otherwise you would generate multiple files.

One of the reasons we 'simplified' sharding was to give users better control over the parallelism overhead. When distributing the load between the shards, we don't know how expensive it is to shard the file that has `beforeAll` in it. Per-file sharding allows advanced users achieve predictable sharding overhead via balancing their files.

Our assumption was that the typical sharding user operates big numbers of files and that the change won't be even noticed. At a smaller scale, one slow test compromises the shard efficiency the same way. Your feedback is a good signal for us to reconsider this assumption.

**Comment by ukdas** [comment]
Hi @pavelfeldman ,

Thank you providing the more info on this.

Yes, we have `beforeAll` in some of the test files.

We have seperate test files based on different features in the product.

Let's consider below scenario -

Feature 1 has 50 cases
- Based on some sub-features or modules, divided the cases into three test files and having 20, 15, 15 cases respectively.

Feature 2 has 20 cases
- It has only one test file with 20 cases

Feature 3 has 2 cases
- It has only one test file with 2 test case

Feature 4 has 1 case
- It has only one test file with 1 test case

Feature 5 has 6 case
- It has 2 test files with 4, 2 test cases respectively

Feature 6 has 1 case
- It has only one test file with 1 test case

Feature 7 has 1 case
- It has only one test file with 1 test case

Feature 8 has 2 case
- It has only one test file with 2 test cases

Now if we use sharding, as per latest playwright shard, shard 1 will be having the more number of cases and for other shard's it will be having very less cases.


Coming to fully parallelism, we are currently not using as the tests are having dependencies and we will get more failures if we use parallelism using multiple workers.

**Comment by garybernhardt** [comment]
@pavelfeldman No, no codegen for the suite in question. This is a single test file with just a `for` loop that loops over every lesson in [Execute Program](https://www.executeprogram.com)'s course catalog, defining two tests per lesson to verify that all lessons actually work. There's no `beforeAll`. It looks like this:

```typescript
test.describe('Course lessons', () => {
  test.beforeEach(() => test.slow())

  for (const course of curriculum.releasedCourses) {
    for (const lesson of course.releasedLessons) {
      test(`Lesson: ${course.id}/${lesson.id}`, async ({page}) => {
        /* Test body goes here. */
      })
    }
  }
})
```

Until this change in Playwright, we parallelized the tests in this file across 20 VMs. With the change, we could theoretically have 20 nearly-identical files, each defining 1/20th of the tests by using `%` or something. But that's very tedious and awkward, especially when it worked perfectly prior to this change.

Understood about the sharding cost of `beforeAll`; I can see that that makes sense for most test suites. For this particular suite it doesn't help at all unfortunately; it only hurts. Just to reiterate, a "parallelize this file at the per-test level" flag would make this problem go away!

**Comment by Kristoffer88** [comment]
This is massive problem for us and increased the test time by a factor 4

**Comment by mxschmitt** [comment]
We reverted the change to the previous behaviour, you can try out [Canary](https://playwright.dev/docs/canary-releases) or wait for the next stable release.

**Comment by garybernhardt** [comment]
@mxschmitt We updated to the latest release and we're back to the same speed we saw before this change was made. Thanks for resolving this!
