### ISSUE TITLE
GBoard support available using Playwright?

### ISSUE THREAD

**Issue by jpEngProd** [microsoft/playwright#21518]
Hi,

I am using Playwright for automated testing purposes. During mobile tests, is it possible to test interactions on GBoard/Mobile Keyboard . On a desktop, when changing the device simulation to mobile mode on a browser, the Gboard does not appear. How can we test such scenarios using Playwright?

**Comment by jpEngProd** [comment]
I am trying to test a scenario where Android user is pressing enter button on a mobile browser & facing some issues, & the same is not happening on mobile mode device simulation in a desktop browser. 
Here the difference is between (keyboard interactions in mobile-simulation on a desktop browser) and (keyboard interactions on mobile device when Android user has installed some keyboard).

Rephrasing the question - Can we perform testing in mobile mode for specific Android keyboard?

**Comment by mxschmitt** [comment]
Pressing Enter on an android Keyboard is from the web application point of view the same as pressing enter from a Desktop Keyboard. (Except `ev.sourceCapabilities.firesTouchEvents` is `true`). Maybe its related to the viewport or maybe your application takes other things into consideration when you click enter on a mobile device.

So to answer your question, no this is not possible, since an android keyboard acts like a normal keyboard. I'd ask your developers that they check the code path and find out why what is behaving differently on a mobile device with such a keyboard to learn more about the reasoning.

**Comment by mxschmitt** [comment]
Closing as per above, please re-file for further questions.
