### ISSUE TITLE
[Feature] support midi in Firefox

### ISSUE THREAD

**Issue by chrisguttandin** [microsoft/playwright#21583]
Using `context.grantPermissions(['midi'])` currently only works with Chromium browsers. But the Web MIDI API is now supported in Firefox (since v108), too. It is integrated with the Permissions API but I'm not sure if that permission can be toggled remotely.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
