### ISSUE TITLE
[Feature]performance log for wss capture

### ISSUE THREAD

**Issue by lanyuer** [microsoft/playwright#21615]
I want to capture the URL of a wss request from a target website in headless mode using the performance log of Selenium, which can be found in 'Network.webSocketCreated'. With Playwright, the required wss link can only be obtained through page.on('websocket', on_web_socket) when headless=False. I don't know if there are any other ways to solve this problem.

**Comment by dgozman** [comment]
@lanyuer Could you be more specific in what information you would like to get?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
