### ISSUE TITLE
[BUG] locator.all() does not work as expected

### ISSUE THREAD

**Issue by kamelbou** [microsoft/playwright#21628]
Hi all,

If there is only one element matching in DOM and I try to access the element using `all()` function, it returns an empty array instead of returning an array containing one element.

Case 1 (doesn't work):
```html
...
<div id=toto></div>
...
```
```js
const locators = await page.locator('#toto').all()
```
locators is **empty**

Case 2(works):
```html
...
<div id=toto></div>
<div id=toto></div>
<div id=toto></div>
...
```
```js
const locators = await page.locator('#toto').all()
```
locator returns an array with the three elements.

Am I using it in the right way ?

Thanks a lot.

**Comment by Nav-2d** [comment]
The following works for me:

```
test('test', async ({ page }) => {
    await page.setContent(`
        <div id=toto></div>
    `);
    const locators = await page.locator('#toto').all();
    console.log(locators.length); //This prints 1
  });
```

**Comment by dgozman** [comment]
@kamelbou This is most likely a timing problem. When you call `locator.all()`, it returns you all the elements that are present at this particular moment, so that could be zero elements if your timing is unfortunate.

If you still believe there is a bug in Playwright, please fill in the bug template and provide a repro we can run locally.
