### ISSUE TITLE
Incognito chromium not truly Incognito - Does not block third-party cookies even though browser setting says "Block third-party cookies in Incognito"  

### ISSUE THREAD

**Issue by vinayjames5** [microsoft/playwright#21720]
My application uses okta verification. If I open in incognito I can use enter username and password where as opposed to in normal browser it automatically takes login username and only option to enter password. 
For automating,  playwright opens browser in Incognito but devices['Desktop Chrome'] and Mobile Chrome devices['Galaxy Tab S4'] behaves differently, desktop chrome ureses the login username and  mobile chrome does uses login user but gives option to enter username..

The difference between the Incognito browser opened manually and open by playwright - one opened manually has icon next to url bar and it says "1 third party cookie is blocked" but for Incognito open by playwright does not have this icon or message.

Due to this I have facing two issues 1) I am not able to run my script in ['Desktop Chrome']  and I am not able to use storageState to reuse authentication as recording or setup run on Desktop Chrome'.

**Comment by dgozman** [comment]
@vinayjames5 There indeed could be a difference between cookies behavior, because it varies a lot between different setups. That said, you should be able to reuse the authentication between two browsers/contexts created by Playwright. Could you please provide a repro that we can run locally that would illustrate the non-reusable storageState issue?
