### ISSUE TITLE
[BUG] elementHandle.scrollIntoViewIfNeeded() doesn't work in Webkit on Linux

### ISSUE THREAD

**Issue by denniskrol** [microsoft/playwright#2179]
**Context:**
- Playwright Version: 0.18.0-next.1588787041098
- Operating System: Ubuntu 18.04
- Node version: 12.16.1
- Browser: WebKit
- Extra: --

**Code Snippet**

```javascript
const browser = await playwright['webkit'].launch();
const context = await browser.newContext({...playwright.devices['iPhone 11']});
const page = await context.newPage();
await page.goto('https://www.google.com/?hl=en', {timeout: 60000});
var element = await page.$('text="About"'); // The 'About' text is just outside the viewport on an iPhone 11
let box = await element.boundingBox(); // It does get the x-y- coordinates
element.scrollIntoViewIfNeeded();
await element.click();
```

**Describe the bug**

When trying to click an element that is currently not visible in Webkit on Ubuntu I get an exception: `UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement`
The same code works in Webkit on Windows, headless or non headless. 
When I take a screenshot with `fullPage: true` I do see the element I'm trying to click on.
`boundingBox()` gets the coordinates of the element. 
Adding `{force: true}` to the `click()` function doesn't help.

**Comment by aslushnikov** [comment]
This reproes for me on v1.0.1 on Linux; doesn't repro on mac though.

Repro script: 
```js
const playwright = require('playwright');

(async () => {
  const browser = await playwright['webkit'].launch({headless: false});
  const context = await browser.newContext({...playwright.devices['iPhone 11']});
  const page = await context.newPage();
  await page.goto('https://www.google.com/?hl=en', {timeout: 60000});
  const element = await page.$('text="About"');
  await element.click();
  await browser.close();
})();
```

**Comment by yury-s** [comment]
Looks like scrolling is broken on GTK in fixed layout mode, i.e. when we create a context with `'isMobile': true`. If I scroll using mouse wheel the page content doesn't move but gets partially covered with a blank overlay.

**Comment by pavelfeldman** [comment]
@JoelEinbinder

**Comment by JoelEinbinder** [comment]
@yury I think your bug is different. We successfully scroll the page, but we don't render it correctly and we click incorrectly.

I believe this issue has nothing to do with scrolling, considering that the we say the element is invisible. I expect the element selected by $ being removed from the DOM by the time we try to click it.

**Comment by yury** [comment]
@JoelEinbinder wrong Yury

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
