### ISSUE TITLE
[BUG] Playwright Chromium based tools don't work in WSL

### ISSUE THREAD

**Issue by fdgonthier** [microsoft/playwright#21813]
### System info
- Playwright Version: 1.x, or master
- Operating System: Windows 10
- Browser: Chromium
- Other info:

Playwright generally works on WSL but, in some case, the Chromium-based GUI tools might end up like this:

![image](https://user-images.githubusercontent.com/557555/226434337-c6cbbc5a-7832-4da0-8c43-ba4a3ddce815.png)

If this is the case, it's likely all Chromium based applications are likely broken and will have the same goth appearance.  This means that your GPU is not properly supported in WSL. You can solve this on a per-app basis by passing the _--disable-gpu_ flag to Chrome applications but Playwright does not allow that.

**Comment by mxschmitt** [comment]
I don't have this config file and it works on my machine with WSL2 out of the box using Ubuntu 20. Maybe you have something else configured which is non-default?

Happy to mention something about WSL, but only if it affects default setups.

**Comment by fdgonthier** [comment]
I'm make very extensive use of WSL so I have a few settings changed in .wslconfig. I was 99% sure that this was not working when I got that computer but I did clear the .wslconfig file anyway to test it and make sure. This is the result...

![image](https://user-images.githubusercontent.com/557555/226622589-b3ea2227-384f-4645-9d0a-f28f16559be0.png)

With .wslconfig gone, all the defaults, all I get are transparent windows.  With WSLg disabled, the Windows become black instead.

**Comment by rgripper** [comment]
I confirm having the same issue. Fixed by disabling GPU through that config.
I didn't have `.wslconfig` initially on my system.
Windows 11 Home 22H2
WSL 2
Ubuntu 22.04.2 LTS. 
playwright 1.35.1

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by k1sul1** [comment]
> Your understanding and cooperation are greatly appreciated

I'd have more understanding if real issues weren't closed with a copypasta response, esp. when the issue _could be mitigated_ by mentioning it in the documentation.

https://learn.microsoft.com/en-us/windows/wsl/troubleshooting <-- Not one word about GPU problems.

I guess it's not _that_ important since this issue is literally the 3rd thing that comes up when I search for "playwright wsl".

**Comment by krukonshedul** [comment]
It's 2am, I'm 12h into trying to get Playwright (but not only Playwright - it's been the last one to surrender it's misgivings and start working)  to behave on my brand new PC (Win11 + WSL2 + Ubuntu22 + intel CPU), right after setting it u and the
`
[wsl2]
gpuSupport=false
`
was what got it working. I've never had any similar problems on any of the machines I interacted with, including my previous setups (Win10 + WSL2 + Ubuntu22 & another Win10 + WSL2 + Ubuntu22, both with dedicated GPUs & MacOs & various CI systems).

I'll try to sort out all of my actions here later on for any1 looking, but I had exactly the same symptoms (the border of the window displayed, but transparent and without any content) on any of the Ubuntu apps more complex than xapps, such as playwrightless google-chrome and all the other browsers I've tried.

**Comment by Lewiscowles1986** [comment]
to build on @krukonshedul answer https://stackoverflow.com/a/78759159/1548557 captures all the requirements, from editing to shutting down the vm and rebooting. I know it may be obvious to some, but I do also find that explaining interstitial steps can be very helpful.

**Comment by Lewiscowles1986** [comment]
ah and should have linked to https://github.com/microsoft/WSL/issues/8931
