### ISSUE TITLE
[BUG] setExtraHTTPHeaders breaks CORS headers in Chromium

### ISSUE THREAD

**Issue by Georgegriff** [microsoft/playwright#21811]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [Chromium]
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
]
});
```

No custom config but the bug is also present if you set, there is a full test below which reproduces it so no need to modify config unless you want to also try to setting the headers in the config once reproduced.

```
use: {
extraHTTPHeaders: {
      "x-my-custom-header": "test",
}
}
```

**Test file (self-contained)**

This test uses test-cors to make a cors request to playwright.dev site for `https://playwright.dev/img/playwright-logo.svg` which has  `access-control-allow-origin: *` set

When setExtraHTTPHeaders is used test fails, when it is not, test passes.

```js
import { test, expect } from "@playwright/test";

test.describe("extraHTTPHeaders bug", () => {
  test.only("cors errors", async ({ page }) => {
    await page.setExtraHTTPHeaders({
      "x-my-custom-header": "test",
    });

    page.on("request", async (r) => {
      if (r.url().includes("playwright")) {
        const headers = await r.allHeaders();
        console.log(r.url(), "request headers", Object.keys(headers).length);
      }
    });
    page.on("response", async (r) => {
      if (r.url().includes("playwright")) {
        const headers = await r.allHeaders();
        console.log(r.url(), "response headers", Object.keys(headers).length);
      }
    });
    page.on("requestfailed", async (request) => {
      console.error("ERROR", request.url() + " " + request.failure().errorText);
    });
    await page.goto(
      "https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fplaywright.dev&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote"
    );
    await page.click("#btnSendRequest");
    await expect(page.getByText("XHR status: 200")).toBeVisible();
  });
});

```

You can comment out extraHTTPHeaders and this test will pass.

**Steps**
- Use setExtraHTTPHeaders to set a custom header, in my case it was for setting a WAF headers
- Go to a site which relies on CORS. See requests fail.

**Expected**
- Extra header is added

**Actual**
- Extra header is added BUT it also removes other headers such as CORS headers.

## Screenshots
![image](https://user-images.githubusercontent.com/9056958/226428906-521ef9f2-d56a-4910-901b-5f799fc21766.png)
Sorry about terrible quality video, github wouldnt let me do more than 10 MB
https://user-images.githubusercontent.com/9056958/226429554-af9b4f5c-0c0b-4a78-a7e3-5cdb209612b2.mov

**Comment by Georgegriff** [comment]
For some comparison with setting extra http headers:

# Chromium
![image](https://user-images.githubusercontent.com/9056958/227186213-005a9232-ea40-4b78-8fc7-2064e78ea28f.png)

# Webkit
![image](https://user-images.githubusercontent.com/9056958/227186056-2c07d701-e252-4848-92a2-34fca8430286.png)

# Firefox
![image](https://user-images.githubusercontent.com/9056958/227186118-d245f227-da70-48da-9910-239ed4c86bd1.png)

**Comment by aslushnikov** [comment]
@Georgegriff so this actually works as expected in Chromium (and kinda broken in other browsers).

CORS requests consist of two parts:
1. CORS pre-flight `OPTIONS` request. We should **not** add extra HTTP headers to this request.
2. Actual request, if the pre-flight succeeded. We'll add extra HTTP headers to this request.

Now, since we add extra headers in the actual request, the pre-flight request is sent with the extra header:
```
Access-Control-Request-Headers: x-my-custom-header
```

This header notifies server that the actual request will have that extra header. Server must respond with a `Access-Control-Allow-Headers` header, explicitly stating, which extra headers are allowed. For example, we can allow all extra headers:
```
Access-Control-Allow-Headers: *
```

However, since the playwright server doesn't respond with the header, the CORS request is considered to be prohibited. 

In case of Firefox and WebKit, the `Access-Control-Request-Headers: x-my-custom-header` is not set at all in the preflight request, thus the difference in behavior.

So the summary is:
- works as expected in Chromium
- not working as expected in Firefox & WebKit

**Comment by Georgegriff** [comment]
Thank you! That's interesting!  This would explain why in my old tests with testcafe I didn't hit this problem with my server because testcafe proxies all traffic, so no cors. But since moving to playwright it didn't work.

It sounds like to me I could potentially fix this in our infras by making it behave correctly.

**Comment by aslushnikov** [comment]
@Georgegriff to further clarify the issue, setting extra HTTP headers is the same as adding them to the `fetch` request.

The following correctly throws in Chromium:
1. Open chromium page, navigate to https://example.com
2. Open DevTools Console
  - Regular fetch works: 
    ```ts
    await fetch('https://playwright.dev/img/playwright-logo.svg')
    ```

  - Fetch with extra header doesn't:

      ```ts
      await fetch('https://playwright.dev/img/playwright-logo.svg', { headers: { 'x-my-custom-header': 'test'}})
      ```

All in all, this is the same as https://github.com/microsoft/playwright/issues/19904 - merging there!

**Comment by Georgegriff** [comment]
Sorry i've been away on vacation. I think I know know what's going on for us.

Our internal Infra blocks all requests unless it sees a specific header, playwright isn't adding the header for options requests as you say here

```
CORS pre-flight OPTIONS request. We should not add extra HTTP headers to this request.
```

A tricky one, your comments have helped us to try to uncover a potential fix though, so thank you

**Comment by michael42** [comment]
@aslushnikov
> setting extra HTTP headers is the same as adding them to the fetch request

But is this actually intended and consistent/useful? `extraHTTPHeaders` is pretty great because it allows to easily set headers for *all kinds* of requests: 

- document navigations
- document navigations inside `<iframe>`s
- `POST`ing `<form>`s
- loading `<script>`s and `<link rel="stylesheet">`s
- preloading config files

None of those types of requests are currently getting the same security protections against custom headers (that regular browsers would never do). I don't see the point in playwright enforcing CORS header whitelisting for `extraHTTPHeaders` headers, since anyone that can set `extraHTTPHeaders` can also just make all kinds of requests anyway.

In my view, checking the explicitly added `extraHTTPHeaders` against the CORS header whitelist pretty much negates the main benefit of `extraHTTPHeaders`. To make it actually work, some workarounds are needed:
 - Request interception can fix the headers, but then you could also just set the header directly via request interception and don't have to mess with CORS at all. But it completely bloats the playwright-trace and breaks caching, which are the reasons I wanted to switch to `extraHTTPHeaders` in the first place.
 - Then there's `--disable-web-security`, which works fine, but unfortunately disables the whole same-origin policy (not just CORS), makes the tests much more unrealistic and isn't even available in Playwright's WebKit wrapper.

So I think not requiring CORS approval for `extraHTTPHeaders` (as it's apparently working that way for Firefox and WebKit) would make the flag (and playwright) much more convenient and usable.

**Comment by Gby56** [comment]
Hi @michael42 I'm currently hitting the same issue, of CORS breaking due to extra HTTP headers.
So far I haven't been able to setup interception to rewrite OPTIONS requests to clean them up and avoid breaking requests.
I've stopped using disable-web-security because it will also break sessions in some cases, for example it is removing the `Origin` header.
Have you had any luck in self-patching the OPTIONS requests ?

Also quoting @Georgegriff , your comment mentions infrastructure, I assume it's a separate proxy that rewrites OPTIONS requests ?

**Comment by michael42** [comment]
Hi @Gby56, I had to stop using `extraHTTPHeaders` due to this issue. You can use `browserContext.route(...)` to define the headers, too (but it breaks https caching).

**Comment by Gby56** [comment]
@michael42 I did find maybe a way through pure CDP, apparently OPTIONS requests are seen, and I think they could be modified, according to this old release https://developer.chrome.com/blog/new-in-devtools-113/
