### ISSUE TITLE
[Feature] Add ability to change har file without closing the context

### ISSUE THREAD

**Issue by damies13** [microsoft/playwright#21896]
I would like to have the option to change the context's har file without closing the context, referring to the documentation from [browser.new_context()](https://playwright.dev/python/docs/api/class-browser#browser-new-context) for `record_har_path` I can see that you can specify the har path when creating a context, and that you need to close the context to save the har file, but there appears to be no way to change the har file without closing the context.

In my use case I would like to record a separate har file for each portion of a business process to be able to clearly identify and separate them from other parts of the business process, I can't simply close the context because the first part of the process involves logging in, so closing the context or page will cause the next portion of the process to need logging in again.

Ideally I'd like a function something like an context.update_context() which had all the same arguments as browser.new_context(), on changing the the value for record_har_path with an context.update_context() would cause the previous har file to be written to disk (the same as when close context is called) and a new har file started, but the context should remain open.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by damies13** [comment]
I thought I had clearly explained why it was needed, no clarification was sought? I would have been happy to answer any questions asked,

I just thought the delay in action on this request was normal for a open source project with limited resources which is why I have not been pushing for a quick resolution, I don't want to be disrespectful.

Dave.
