### ISSUE TITLE
[BUG] Iphone 12 element is outside of the viewport even if element is found

### ISSUE THREAD

**Issue by alhell** [microsoft/playwright#21905]
This issue is only ocuring in [Iphone 12].

### System info
- Playwright Version: [v131.1]
- Operating System:  Ubuntu
- Browser: DEVICE_TYPE=iPhone12
- Other info:

```js
    it("renders the component", async () => {
      await page.click("text=Go to page");
      await expect(page).toHaveSelector(`.gotopage`);
    });

```

**Steps**

[Describe actual behavior]
  locator resolved to ...
       attempting click action
        waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
        done scrolling
        element is outside of the viewport

**Comment by mxschmitt** [comment]
This snippet looks like its not following Playwright Best Practises. In particular:

- Use the [Playwright test-runner](https://playwright.dev/docs/intro) to write the e2e tests.
- Use [Locators](https://playwright.dev/docs/locators) to click, otherwise it might end up clicking wrong elements.
- Using Playwright's [web-first assertions](https://playwright.dev/docs/api/class-locatorassertions): [toBeVisible](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-visible).

After that if you think its a Playwright bug, we need a clear repro how to reproduce this issue. `toHaveSelector` is no Playwright API method, so we don't know what it does.

Please re-file with more details and follow the bug template.
