### ISSUE TITLE
[Feature] Hooks for record/open HAR-files with routeFromHAR

### ISSUE THREAD

**Issue by Avol-V** [microsoft/playwright#21906]
Sometimes we need to modify HAR entry somehow, but currently we don't have any way to do that.

For example, I would like to remove some secret cookies from headers before they are written to disk.  
Or, I would like to replace page URL with the actual baseURL, like it's described in this request: https://github.com/microsoft/playwright/issues/18185

I'm currently doing this with monkey-patching of some of the playwright-core classes.

To add a modification to the entry before it is added to the HAR, I wrap `HarRecorder.prototype.onEntryFinished`. In my wrapper I remove some headers and replace the current (write-time) baseURL in `request.url`, `response.redirectURL` and all headers with some placeholder.

To apply the current baseURL, I wrap `LocalUtilsDispatcher.prototype.harOpen`. For each entry in `harFile.log.entries` I'm replacing the baseURL placeholder with the actual baseURL.

This works fine, but can be broken with future changes in playwright.

It would be great if there were some official hooks to making changes to the HAR file before writing it and after reading it.

**Comment by Avol-V** [comment]
I also needed to modify the response body (updating some parts of HTML) and I could only do this by creating a wrapper over `LocalUtilsDispatcher.prototype.harLookup`.

**Comment by samratluintel2** [comment]
@Avol-V How to do monkey patching in react?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
