### ISSUE TITLE
[Feature] Add git lfs to the Docker image

### ISSUE THREAD

**Issue by thewilkybarkid** [microsoft/playwright#21920]
I've previously tried to run my tests in [GitHub Actions directly in the Playwright container](https://playwright.dev/docs/ci#github-actions-via-containers) to try and speed them up. I had to [back out](https://github.com/PREreview/prereview.org/commit/7d29c5f19ea82179d035dae08ad373acf9fa5054) as I ran into trouble setting up Git LFS so my snapshots could be checked out.

Would it be possible to add Git LFS to the image?

**Comment by mxschmitt** [comment]
You can manually install it afterwards which takes just a few seconds:

```bash
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
apt-get install -y git-lfs
```

Would that work for you? See [here](https://github.com/git-lfs/git-lfs/blob/main/INSTALLING.md).

Since not a lot of users are using Git LFS, we are often are waiting first for a lot of requests before adding new software to the Docker image, to make it not unnecessary big size wise.

**Comment by aslushnikov** [comment]
I'll close this per Max's response. Git LFS is not widely used by our clients, so we'd like to avoid adding it to the container.

**Comment by Bilb** [comment]
For others with the same question, there is an issue with the `--user=1001` argument, and the need to install git-lfs as root.
Here is what I think should work https://github.com/git-lfs/git-lfs/issues/4134#issuecomment-1635204943
