### ISSUE TITLE
[Feature] Let user configure trace window look

### ISSUE THREAD

**Issue by Neophos** [microsoft/playwright#21955]
The trace viewer recently changed the placement of the boxes from this:
![image](https://user-images.githubusercontent.com/8988315/227530747-d9b00cca-9f13-44f9-806d-5c9455314fe4.png)
To this:
![image](https://user-images.githubusercontent.com/8988315/227531736-faa34a66-be9b-4d44-832f-50618d39bb3b.png)

I believe this is much worse for working on a wide monitor, where horizontal space is much cheaper than vertical. I would prefer to be able to choose myself where the different tabs are located, if possible, and if not, to at least choose the style between the old and new.

**Comment by pirem** [comment]
We are in the same situation and have decided for the moment to stay in 1.31.1

**Comment by jaktestowac** [comment]
@aslushnikov can be closed - it is implemented

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
