### ISSUE TITLE
Creating a cookie programatically

### ISSUE THREAD

**Issue by JoseArostegui** [microsoft/playwright#22019]
Hi experts,

I'm using playwright 1.32 against a web application developed with Oracle Apex 20.2.

I'm testing to bypass the login process in order to increase the speed of tests.

In Oracle Apex, you can get 2 values from an already started and authenticated session using a SQL:

```
SELECT id AS app_session
      ,cookie_value
      ,username
  FROM apex_200200.wwv_flow_sessions$
 WHERE username = 'JOSE.AROSTEGUI'
   AND workspace_user_id IS NULL;
```

Then, you have to use the value from "app_session" in the URL and set a cookie in the browser with value in "cookie_value".

I'm setting the cookie using this code, but the login is not bypassed. What am I doing wrong?

```
import { test, expect } from '@playwright/test';

test('bypass Apex login', async ({ page, browser }) => {

  const context = await browser.newContext();

  await context.addCookies([
    {
      "name": "APPLICATION_PORTAL",
      "value": "ORA_WWV-cb9FNbB1X--O39S7OdWHYlGrqRoTTHiU",
      "url": "https://apextest.josearostegui.com/ords/",
    }
  ]);

  await page.goto('https://apextest.josearostegui.com/ords/f?p=500:1:3979603549329'); //3979603549329 is the value read from the SQL

  await context.close();
  await browser.close();

});

```
Thanks,
Jose.

**Comment by mxschmitt** [comment]
The reason why it does not work is because you create a new context. A context is isolated from other contexts, and in your case you use a page instance which belongs to a different context. To solve this you should do:

```ts
import { test, expect } from '@playwright/test';

test.beforeEach(async ({context}) => {
  await context.addCookies([
    {
      "name": "APPLICATION_PORTAL",
      "value": "ORA_WWV-cb9FNbB1X--O39S7OdWHYlGrqRoTTHiU",
      "url": "https://apextest.josearostegui.com/ords/",
    }
  ]);
});

test('bypass Apex login', async ({ page }) => {
  await page.goto('https://apextest.josearostegui.com/ords/f?p=500:1:3979603549329'); //3979603549329 is the value read from the SQL

  await context.close();
  await browser.close();

});
```

Why beforeEach and not beforeAll? Because each test gets its own context, so you need to set it for every test. If you want to set it for an individual test, you can do the following:

```ts
import { test, expect } from '@playwright/test';

test('bypass Apex login', async ({ page, context }) => {
  await context.addCookies([
    {
      "name": "APPLICATION_PORTAL",
      "value": "ORA_WWV-cb9FNbB1X--O39S7OdWHYlGrqRoTTHiU",
      "url": "https://apextest.josearostegui.com/ords/",
    }
  ]);
  await page.goto('https://apextest.josearostegui.com/ords/f?p=500:1:3979603549329'); //3979603549329 is the value read from the SQL

  await context.close();
  await browser.close();

});
```

See here: https://playwright.dev/docs/test-fixtures

And the reason why there were no colors was because you did not pass a language over to your code block: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by JoseArostegui** [comment]
Working as charm. Thanks a lot for the quick support!
