### ISSUE TITLE
[Question] states for waitForSelector

### ISSUE THREAD

**Issue by sagrawal-idrc** [microsoft/playwright#2202]
Thanks for the amazing library. It has made e2e testing enjoyable!

I have couple of queries regarding `state` parameter for `page.waitForSelector`.

1. I have found that `page.waitForSelector` with `state` as `hidden` works even when the element isn't present in DOM. Is that expected? In my opinion, `hidden` should work if the element though present in DOM isn't visible (empty bounding box or `visibility:hidden` as mentioned in docs).
2. For a single page application (SPA), what should be the approach to test for an element which should be hidden, but actually isn't (so the test should fail)? The problem with SPAs is that most DOM elements get loaded dynamically. So `state` with `hidden` eg. awaits successfully, but the element appears almost immediately after.

**Comment by aslushnikov** [comment]
> Thanks for the amazing library. It has made e2e testing enjoyable!

@sagrawal-idrc  Thank you for the warm words! ❤️

> I have found that page.waitForSelector with state as hidden works even when the element isn't present in DOM. Is that expected?

Yes, this is expected. Let me clarify our docs to make this more clear (#2208). 

>  In my opinion, hidden should work if the element though present in DOM isn't visible (empty bounding box or visibility:hidden as mentioned in docs).

This would be a valid treatment as well. Our motivation was to make sure that `'hidden'` is synonymous to "unclickable", so it does include detachment from DOM. Does it bother you?

> For a single page application (SPA), what should be the approach to test for an element which should be hidden, but actually isn't (so the test should fail)? The problem with SPAs is that most DOM elements get loaded dynamically. So state with hidden eg. awaits successfully, but the element appears almost immediately after.

These are pretty hard to test. The problem here is that you assert page's DOM state too early, before it actually stabilized. 
I'd recommend picking a reliable signal from webpage that corresponds to a stable state. Figuring out this signal is an art though, it might be a completion of an XHR request, or maybe existence of some specific DOM element.

Things are way easier if you control website code and can change it to aid testing. I'd recommend adding test hooks that will notify testing harness of reliable states, e.g. using `console.debug()` messages from-inside web page.

For example, if your website has a form and you want to test form submission, you can change website to emit `console.debug("form submitted");` once the form submission is complete and write a test like this:

```js
await Promise.all([
  page.click('button#submit'),
  page.waitForEvent('console', msg => msg.type() === 'debug' && msg.text() === 'form submitted'),
]);
// Assert DOM state
expect(await page.$('form#success')).toBeTruthy();
expect(await page.$('form#failure')).toBeFalsy();
```

**Comment by sagrawal-idrc** [comment]
> Our motivation was to make sure that 'hidden' is synonymous to "unclickable", so it does include detachment from DOM. Does it bother you?

Not as much, now that it's clarified. :-)

Though, IMHO, following treatment might be better (to further distinguish `hidden` from `detached`).

- 'attached' - wait for element to be present in DOM.
- 'detached' - wait for element to not be present in DOM.
- 'visible' - wait for element to have non-empty bounding box and no visibility:hidden. Note that element without any content or with display:none has an empty bounding box and is not considered visible.
- 'hidden' - wait for element to be present in DOM, and have an empty bounding box or visibility:hidden. This is opposite to the 'visible' option.
