### ISSUE TITLE
[Feature] Add 'delay' and 'steps' options to Locator.dragTo API

### ISSUE THREAD

**Issue by jonaszb** [microsoft/playwright#22058]
The Locator.dragTo() API doesn't work if draggable element has drag activation constraints, such as requiring the element to be moved by x pixels before drag is activated or x ms between pressing down on it and dragging.

I've managed to work around the distance constraint by using the Mouse and specifying the number of steps:
```typescript
    await mouse.move(draggable.x, draggable.y);
    await mouse.down();
    await mouse.move(droppable.x, droppable.y, { steps:  10 });
    await mouse.up();
```

Is it feasible to add similar options to the dragTo API?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
