### ISSUE TITLE
[BUG] Problem with file download from recorded HAR

### ISSUE THREAD

**Issue by Avol-V** [microsoft/playwright#22087]
### System info
- Playwright Version: v1.32.1
- Operating System: All
- Browser: All
- Other info:

It looks like when reading from HAR Playwright thinks that downloading the file is an error, and it should open, but I'm checking the file download.

Here's what the test looks like:

```ts
import { test, expect } from '@playwright/test';

test('Download test', async ({ page }) => {
    await page.context().routeFromHAR('/tmp/test-har.zip', { update: false });

    await page.goto('https://github.com/microsoft/playwright/releases');

    const link = page.getByRole('link', { name: 'Source code (zip)' }).first();

    await expect(link).toBeVisible();

    const downloadPromise = page.waitForEvent('download');

    await link.click();

    const download = await downloadPromise;
    const filePath = await download.path();

    await expect(filePath).not.toBeNull();
});
```

When I change `update` to `true`, everything works without any problem. But when it's changed to `false`, I've got an error.

In Chrome I get the following error:
```
Error: net::ERR_ABORTED at https://codeload.github.com/microsoft/playwright/zip/refs/tags/v1.32.1
Test timeout of 30000ms exceeded.
```

In my real test I also get the following error in Firefox and Safari:
```
Error: Download is starting
Test timeout of 30000ms exceeded.
```

But I can't reproduce it on this example for these browsers, the problem only happens on Chrome.

And in fact, there is no timeout, it fails quickly.

What's wrong with my test? How can I tell Playwright that the file is being downloaded?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
