### ISSUE TITLE
[Feature] Trace Files with expressive names

### ISSUE THREAD

**Issue by mohalsherif** [microsoft/playwright#22153]
Currently when we run tests, we get multiple zip files (2 to 5) depending on our test. We are usually interested in one of those zip files that contains the actual UI. What we need to do (to find out why the test failed) is run playwright trace on each zip and hope we find the correct one and our Trace Viewer then shows the Browser and we could debug the issue.

We also run playwright in our pipelines and get the traces locally to check the errors. We can never find out which trace zip file is the one we need. For that we always used to get the biggest file in size, hoping that would return the correct zip. Lately (maybe in the new playwright versions), it is sometimes the issue that it is not the biggest trace zip file that we need.

To avoid all of that, it would be great if the trace files have names other than "trace.zip"  , "trace-1.zip" ,"trace-2.zip" etc.
This way we could query the exact name of the file. 
For example "trace-browser.zip" and "trace-requests.zip" etc.

**Comment by pavelfeldman** [comment]
Could you tell us more about the traces you generate? Do you only need to distinguish between the browser and api test traces?

**Comment by mohalsherif** [comment]
To be honest, we are only interested in the browser traces. We are not sure which trace file generates what data. We did not find any documentation about that and were only ever interested (till now) in the browser trace file

**Comment by pavelfeldman** [comment]
By default, each test will only have one trace archive though, why do you have several traves? Do you use multiple contexts in each test?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Comment by neighborhoodhacker** [comment]
I would like this to be reopened. We have traces generated on failures in our pipeline. They are all named trace.zip, since we use the test runner. We utilized Allure Reports and host those reports using GitHub Pages and don't want the zip files hosted in the same directory as those are easier to manage separately. I would like to be able to have a test.use option or something similar that I can pipe the current test name to (or something relevant and obvious) that would allow us to download the traces on their own and identify which test they belong to.
