### ISSUE TITLE
[Feature] Retry to run in the same main process

### ISSUE THREAD

**Issue by kms-sonnguyen** [microsoft/playwright#22207]
Context:
Our application allows one session per user only, so if the user tries to login in another browser the first session will be terminated.
Using Playwright we have to set `workers: 1` in our configuration, however when one of our tests fails, Playwright will trigger a second worker process to rerun the failing test. That's nice but it'll break our current test execution.

To avoid that and still be able to use retry, I think Playwright should respect `worker` configuration and rerun the failing test in the same process.

**Comment by pavelfeldman** [comment]
> To avoid that and still be able to use retry, I think Playwright should respect worker configuration and rerun the failing test in the same process.

The `workers` option is saying how many concurrent workers we are allowed to run. If you way `workers: 1`, no more than 1 worker will be executed *at the same time*. Based on your description, it should work for you. You are saying:

> if the user tries to login in another browser the first session will be terminated

Which sounds fine, since by this time, the first worker is terminated and there is no first session.

**Comment by kms-sonnguyen** [comment]
Thanks for clarifying!
