### ISSUE TITLE
[Feature] Is there any chance to make "playwright-test" as a standalone test runner for NodeJS?

### ISSUE THREAD

**Issue by Ernst-D** [microsoft/playwright#22239]
Hi Playwright team! I was wonder is there any chance to make Playwright Test as a standalone test runner? 

There are a lot of good modern options in term of test runners when things comes to NodeJS: Jest, Vitest, Mocha and etc. But Playwright-Test has rich API in term of test observability (steps, info, test information, integrated reporting) and, what is really cool, - fixture concept. 

So why do we need Playwright Test as a standalone package instead of Jest, Vitest, Mocha and etc? All of these test runners doesn't have complete "out-of-box" tooling which will make developers think of _what else they can do_ instead of _how we can do that_. I know that these foregoing test runners has some of the features of Playwright Test one way or another, but non of these has this much of integrated features as Playwright Test.

And yet, is there any possibility to make Playwright Test as a standalone test runner?

**Comment by pavelfeldman** [comment]
Under the hood, Playwright Test and Playwright Library are properly layered. This means that you can use Playwright Test w/o Playwright fixtures, rather create your own fixture file and import it from your tests. No browsers will be downloaded or started. You can create new fixtures, configure them under `use` in config - you'll see how everything Playwright-specific is already under `use` and instead of Playwright, you can have your own configuration there.

We do have a couple of 'auto' fixtures (that should be noop in your case) and also we'll pollute your fixture namespace with 'page', 'context' built-in fixtures, but this should not prevent you from using Playwright Test as a general-purpose runner.

**Comment by Ernst-D** [comment]
Well, I did try a little proof of concept with webdriverio and appium - this worked flawlessly. Plus, support of VS Code extension makes this solution pretty perspective for mobile UI testing. 

I'm going to dive deep into possibilities of such solution. Thanks for the answer!

**Comment by pavelfeldman** [comment]
Sounds good! 
Closing as per above, please feel free to open a new issue if this does not cover your use case.
