### ISSUE TITLE
[Feature] Allow FrameLocator to be converted to Frame

### ISSUE THREAD

**Issue by gladykov** [microsoft/playwright#22279]
I'm using `FrameLocator` heavily to access series of nested iframes:
https://playwright.dev/docs/api/class-framelocator

When I wanted to reuse it, just to get HTML content of whole frame, I discovered I need to have Frame object first:
https://playwright.dev/docs/api/class-frame

Since `FrameLocator` could be considered address for the `Frame` , feature request here is, to return `Frame` object from `FrameLocator`
It could be done the other way around as well.

**Comment by pavelfeldman** [comment]
Would this work for you?

```js
await page.frameLocator('iframe').locator(':root').evaluate(() => document.documentElement.outerHTML)
```

**Comment by gladykov** [comment]
Wow, this is very nice solution and it works. Thank you!

Anyway, I would still suggest rethinking relation between both classes, as this could be useful in other scenarios as well.

**Comment by pavelfeldman** [comment]
You should not use Frames unless you are in a narrow set of use cases where your page is static. In that case you can fetch frames by name/id/url. Frames are from the deprecated Handles world, like ElementHandle your test will be racy and hence flake if you use the frame handles. FrameLocators on the other hand are auto-wairing and solid!

**Comment by gladykov** [comment]
I understand assumption here, but that's and ideal world which never exists :D I have an iframe in iframe in iframe, with names being big json strings :) Iframes coming from our code / service provider code / 3rd plugin code. Leaving just as a reminder, that such situations exist in nature and flexibility is important.

**Comment by JamesPaceOnTailwind** [comment]
I also have a bit of a niche use case, where I need to "print" an iframe to PDF. Only the `Page` object has the `pdf` method, so I need to find the correct frame which doesn't have a name, grab the URL and navigate to it. Now the page is displaying what the iframe was and I can call the `pdf` method to "print" it.

**Comment by VasanthVJ** [comment]
Hi, Is there an wait for Iframe? I have been working on a custom method to find the iframe. since our application deals with different iframes which are not nested. I have designed a function to find the iframe based on the locator. Basically fetching all the iframes by name present in the DOM and iterate frame until the count returns 1. In a ideal world it worked fine for me but when I try to open a certain menu, it takes a while to load the page. In that instance, it is not satisfying my locator count condition(though it was able to get all the iframe name). I have tried default waitForLoadState() as well with timeout but nothing worked in favour. However, it worked fine with waitForTimeout but that is being discouraged and increases my execution time.

sample syntax below:
const allFrames = this.page.frames(); // returns all the iframes in the dom
for(const frame of allFrames){
const count = await this.page.frame(frameName).locator(locator).count(); // will be iterate with each iframe until it returns 1.
if(){ //if greater than 0
// perform action
}
}

**Comment by doglex** [comment]
Somtimes,  have to wait for iframe  many times if nested lazy-loaded iframe

``` js
let theFrame = ""   // the Frame object 
for (let i = 0; i < 50; i++) {
    // wait for multiple iframes to load, max 50 seconds
    await new Promise(resolve => setTimeout(resolve, 1000))
    let frames = page.frames()
    for (let frame of frames) {
        if (!!theFrame) break
        if (frame._name === "some frame id") {
            theFrame = frame
        }
        // wait for lazy-loaded content to load
        // await frame.content().then((res)=>{
        //     if (res.toString().includes("some string")) {
        //         theFrame = frame
        //     }
        // })
    }
    if (!!theFrame) break
}
console.log("got iframe:", theFrame)
await theFrame.getByRole('button', {name:'some text'}).click()
```
