### ISSUE TITLE
[Feature] - Watch mode > Only watch for changes *within* the watched test(s)

### ISSUE THREAD

**Issue by JeroenSormani** [microsoft/playwright#22287]
First of all, let me say the UI/Watch mode is great!

An improvement I've love to see is that the watched tests are only ran when there's a change in said watched test. 

Right now if there is any change in the file, even unrelated to the watched tests, it will run them anyways.
(I'm watching an individual test, not a file/all tests)

**Comment by pavelfeldman** [comment]
There is no general solution to that (think a constant outside of the scope of the test that the test uses, or a helper method). So we can't guarantee it, sadly.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
