### ISSUE TITLE
[Feature] Ability to perform the same expect validation on locators resolved to multiple elements

### ISSUE THREAD

**Issue by vshevchenk** [microsoft/playwright#22317]
# Use case

For example, consider the following list:

```
<ul>
  <li>Text 1</li>
  <li>Text 2</li>
  <li>Text 3</li>
</ul>

```

The desired behavior is to have an ability to validate all elements in the list matching the same expectation at once

```
import re

from playwright.sync_api import expect

expect(page.locator("ul > li")).to_have_text(re.compile("Text")) # pass
expect(page.locator("ul > li")).to_have_text(re.compile("1")) # fail - only the first element matches the condition
```

# Difference from current capabilities

1. This solution requires to know exact number of elements and doesn't fit use cases when number of items could change (like filtering lists of tables)
```
expect(page.locator("ul > li")).to_have_text([re.compile("Text"), re.compile("Text"), re.compile("Text")])
```

2. This solution is detaching locators from playwright engine so it could resolve to non-exitent element
```
for element in page.locator("ul > li").all():
      expect(element).to_have_text(re.compile("Text"))
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
