### ISSUE TITLE
[BUG] Platform name when running with docker on a mac is darwin

### ISSUE THREAD

**Issue by hsn-nxt** [microsoft/playwright#22337]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [macOS 13.2.1]
- Browser: [Chromium]
- Command: docker run --ipc=host --rm --network host -v $(pwd):/work/ -w /work/ -it mcr.microsoft.com/playwright:v1.32.3-focal /bin/bash & npx playwright test

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should have a screenshot name ending with linux when running with the docker image mcr.microsoft.com/playwright:v1.32.3-focal', async ({ page }) => {
      await expect(await page).toHaveScreenshot('test.png');
});
```

**Expected**

test-chromium-linux.png

**Actual**

test-chromium-darwin.png

**Comment by mxschmitt** [comment]
This is expected, since the snippet you gave does simplified the following:

```
docker run debian:11 /bin/bash & hostname
```

The `hostname` command is not executed in the Docker container because you have used the `&` operator at the end of the command, which puts the command into the background and allows the shell to continue running other commands.

To fix this, don't use & and remove the /bin/bash invocation.
