### ISSUE TITLE
[BUG] 'Test finished within timeout of...' message gets printed under wrong condition

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#22379]
```ts
import { test, expect } from '@playwright/test';

test('asdf', async ({ page }) => {
  page.locator('li').count()
  expect(new Promise(() => null)).toBe(2)
})
```

If you execute the test above you get the following:

```
    Test finished within timeout of 30000ms, but tearing down "context" ran out of time.
    Please allow more time for the test, since teardown is attributed towards the test timeout budget.
```

it fails under a second, so it should have enough time to close the context.

Expected: This message does not get printed

**Comment by mxschmitt** [comment]
I can verify that this is already fixed on ToT.

Good: 1.33.0-alpha-mar-25-2023
BaD: 1.33.0-alpha-mar-24-2023

**Comment by subabu-cmc** [comment]
hi @mxschmitt Good Morning, I face this issue after updating playwright version 1.32. Thanks for fixing this issue. Now I have updated playwright version to 1.33.0 still I am getting this error on second run.  I am using typescript. It fail in After Hooks.
Error message : Test finished within timeout of 120000ms, but tearing down "context" ran out of time.
Please allow more time for the test, since teardown is attributed towards the test timeout budget.

**Comment by bheemreddy181** [comment]
Seeing similar issues probably better, we open a new issue
