### ISSUE TITLE
[Feature] Versioned documentation

### ISSUE THREAD

**Issue by pas2al** [microsoft/playwright#22386]
Switch between different versions in the documentation on https://playwright.dev/

We already have the documentation for canary releases on https://playwright.dev/docs/next but is hard to find the correct documentation for older releases. Especially if your team stays on an older release and tries to migrate from one version to the next one. When did the playwright team introduce change x and how does it work on that release? The release notes do not cover every single detail.

Suggestion: Easily switch between released versions using a dropdown in the navigation, similar to https://material.angular.io/

**Comment by mxschmitt** [comment]
Playwright versions are all backwards compatible except very rare cases, for that we recommend checking out the release notes. Generally speaking we strongly recommend staying on the latest version, to be able to test on modern browsers and have access to the most recent features and bugfixes. We had versions on our docs site until we introduced "since" on a per attribute and per method basis and decided that this is enough.

Closing per above.
