### ISSUE TITLE
[Question] Why it's not possible emulate device in page but only while creating new browserContext?

### ISSUE THREAD

**Issue by adragich** [microsoft/playwright#2239]
I see there is an option for emulating plenty of devices in Playwright, but all of them can be used only if you create a new context for browser. 

I cannot emulate devices in page, also it's not possible to emulate device in the same context of browser, which is adding a friction in dev experience and running tests in different devices. 

Are there any plans for adding `emulate` for Page class, something like Puppeteer's https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pageemulateoptions?

**Comment by pavelfeldman** [comment]
Yes, we had `Page.emulate` in Puppeteer, but stepped away from it in Playwright because it did not work as advertised. The major factors were:

- You need to reload the page if you change anything other than the viewport size
- Unlike Puppeteer, Playwright's emulation also applies to windows opened from the page

As a result, instead of reloading the page for the emulation purposes, we recommend that you create a new context. We consider testing scenarios using regular `launch` and browser contexts as our primary use case and if that adds friction to your workflow, we would love to know why!

Could you share more about your use case? I can guess that you are using `launchPersistent` and would like to iterate over the devices? Do you reload the page when you change emulation?

-------
Device is basically a collection of the following flags:
  - **viewport** - can be changed dynamically, already has a setter on the page
  - **userAgent**: - is typically checked on page load
  - **deviceScaleFactor** - can be changed dynamically, but does not exist on page yet, can be added
  - **isMobile** - can't be changed on the fly, adjusting it reloaded the page in Puppeteer
  - **hasTouch** - same as above

**Comment by adragich** [comment]
Thanks for the explanation, now I understand the reasoning for playwright way of device emulation.

What I meant by 'friction' is a need to create new browser context twice in the case I'd like to switch between devices(desktop/iPhone) on the same page URL (using `launch`). My test case runs but I have concerns about performance - is device emulation faster with playwright or puppeteer?

**Comment by dgozman** [comment]
Note that switching between devices on the same page URL without reloading could be error-prone. You'll need to reload to pick up viewport meta tags, update feature detection in modern libraries or refresh anything else that's done during page load.

Both Playwright and Puppeteer use the same backend implementation for the Chromium browser, so there should not be any difference in device emulation performance.

**Comment by dgozman** [comment]
@adragich Did we address your concerns? Any other issues with emulation? I am happy to help if something does not work or has any surprises.

**Comment by adragich** [comment]
This one can be closed, thank you!
