### ISSUE TITLE
[BUG] xray-report does not provide evidence data types

### ISSUE THREAD

**Issue by LisBerndt** [microsoft/playwright#22396]
### System info
- Playwright Version: v1.31.2
- Operating System:  Windows 10

I configured my test system as described here; https://docs.getxray.app/display/XRAYCLOUD/Testing+web+applications+using+Playwright

I noticed that in the xray xml-report the data types are not provided (e.g. ".png", ".webm"). So I have to edit the xml content beforehand to be able to open the evidence in the browser. 
In the default junit reports on the other hand the data types are apparently provided.

**Comment by mxschmitt** [comment]
Could you elaborate where they should be provided inside the XML? This would help a ton!

What is the default junit reports vs. xray xml-report? Do you mean with default is by us?

**Comment by LisBerndt** [comment]
Not able to reproduce the issue your default junit reports in the moment.

But for the xray reports it would simply to the trick when the data types are added in the marked points  ![image](https://user-images.githubusercontent.com/43057926/232037053-c3d9961f-7f17-4540-b1af-9436db4d6239.png)

**Comment by mxschmitt** [comment]
**Investigation notes**: We always add the attachments with their name only, see [here](https://github.com/microsoft/playwright/blob/6c3d35fa5825c5c2f1ff4b5e30b9a8cc3f6fc943/packages/playwright-test/src/reporters/junit.ts#L211). Xray expects that the name field has the file extension it, see e.g. [here](https://github.com/Xray-App/xray-junit-extensions/blob/c3361c3a04e243606dd2677f125d77e721cd484c/src/test/java/app/getxray/xray/junit/customjunitxml/wip/TestingExperiments.java#L254).

**Comment by zachrburke** [comment]
I'm using the following configuration when running playwright tests:

```js
use: {
    video: 'on',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
}
```

This will create a video for each test and embed it as base64 to the xray-report.xml file under a node that looks like `<item name="video">`.  

I've been searching for a way to change the default playwright behavior of calling this "video" to "video.webm" so that I can view it easily in the test execution in xray.  

After seeing this line [here](https://github.com/microsoft/playwright/blob/6b487ff49d7d52f72eca9150315d54a1076f036c/packages/playwright-test/src/index.ts#L528), I don't think it can be changed, but I could be missing something.  

Since I'm uploading to xray via api in node, I can modify the xml before uploading it with the following:
```js
xrayContent = xrayContent.replace(/item name="video"/g, 'item name="video.webm"');
xrayContent = xrayContent.replace(/item name="screenshot"/g, 'item name="screenshot.png"');
xrayContent = xrayContent.replace(/item name="trace"/g, 'item name="trace.zip"');
```

I think it would be ideal if the extension was included in the attachment name for files that playwright produces and attaches for you.

**Comment by Iv3x** [comment]
actually facing the same issue only when i capture a screenshot manually with the file ending and type I can actually view it in xray 
`  const path = testInfo.outputPath('tmp_screenshot.png');
  await page.screenshot({path});

  testInfo.attachments.push({name: 'screenshot.png', path, contentType: 'image/png'});`
  
![Bildschirm­foto 2023-04-26 um 16 53 08](https://user-images.githubusercontent.com/8173194/234622753-d99ed7e6-936b-4c0a-a840-5f5c955f8fed.png)

**Comment by LisBerndt** [comment]
Btw. I use this Python script as a temporary workaround:

```Python
import fileinput
import re
for line in fileinput.input('.//test-results//xray-report.xml', inplace=1):
    line = re.sub(r'"screenshot"', r'"screenshot.png"', line.rstrip())
    line = re.sub(r'"trace"', r'"trace.zip"', line.rstrip())
```

**Comment by bitcoder** [comment]
To clarify, perhaps with the help of the Playwright team,  in Playwright:
1. screenshots are always taken as .PNG images correct?
2. videos are always taken as .WebM ?
3. traces are always ZIP files?

**Comment by mxschmitt** [comment]
1+2+3 is correct.

A user can in theory create own screenshots and push them into the attachments object, so I'd always use the contentType which we pass in the attachment object to add the corresponding file extension.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
