### ISSUE TITLE
[Feature] Full screen customization from CLI

### ISSUE THREAD

**Issue by eshk12** [microsoft/playwright#22400]
Hello, 
I would like to know if there is an option to run tests with full screen from CLI.

For example: `npx playwright test test.spec.js --headed --fullscreen`

**Comment by mxschmitt** [comment]
This is not possible, running tests full screen is discouraged, since you then get different behaviour when you have different screens attached to your machine. 

See here for related feature requests where I'll fold it into. https://github.com/microsoft/playwright/issues/10337 for custom CLI options and https://github.com/microsoft/playwright/issues/1086 for running it full screen.
