### ISSUE TITLE
[REGRESSION]: Certain tests using AddInitScript are flaky in 1.31 and beyond

### ISSUE THREAD

**Issue by ozyx** [microsoft/playwright#22410]
**Context:**
- GOOD Playwright Version: 1.30.0
- BAD Playwright Version: 1.31.x - 1.32.x
- Operating System: playwright docker container
- Extra: [any specific details about your environment]

**Code Snippet**

[Repro repo](https://github.com/ozyx/playwright-addInitScript-flake)

**Describe the bug**

Apologies in advance as I will be mostly describing symptoms here, but we have a set of tests which are flaky after upgrading to 1.31 and beyond (tested up until 1.32.3). 

Open MCT is a modular, plugin-based app, so we [make use of AddInitScript](https://github.com/ozyx/playwright-addInitScript-flake/blob/main/e2e/addNonDefaultPlugin.js) in some [test suites](https://github.com/ozyx/playwright-addInitScript-flake/blob/main/e2e/test.e2e.spec.js#L7) to add in non-default plugins for testing. This pattern has worked well for us so far, but in 1.31.0 plugins added via AddInitScript are failing to install completely before the page is loaded. This failure only happens on chrome-- tests run on firefox or safari are stable and passing.

I have assembled a [less-than-minimal repro](https://github.com/ozyx/playwright-addInitScript-flake) (as I so far have only been able to replicate this issue in the context of Open MCT). In the repro you can see that if using 1.31.0, the tests run on chrome completely fail. In 1.32.3, the tests fail less, but are still extremely flaky.

I'd be interested if you have any recommendations on how to better debug this issue. I'm not sure if this is completely a Playwright issue, or a Chrome issue, but one thing I have noticed is that CPU matters (removing the CPU restriction on the docker container causes less flake). 

Any guidance you can provide would be greatly appreciated. Right now this is unfortunately blocking us from upgrading to the latest Playwright (and we want that UI mode! 😄). Thanks!

**Comment by mxschmitt** [comment]
BAD  v1.32.3 112.0.5615.29 1109224
GOOD v1.30.0 110.0.5481.38 1084008
Bisect range: https://chromium.googlesource.com/chromium/src/+log/e841e60be2cf00e92cc02822666ea6f19ad2e2d1..33b919d98dd63bfa7cd419fcd08e212b3c58055f

I fits a bug or not, is to be clarified. The main question there is `openmct.install()` needs to be called before `openmct.start()`. I assume it should be and thats why the tests are failing sometimes. If it caused by a Chromium regression or a Chromium fix thats the question.

After making the following changes it was working for me:

```diff
diff --git a/index.js b/index.js
index 291a9d4..2489acb 100644
--- a/index.js
+++ b/index.js
@@ -2,11 +2,8 @@ const express = require('express')
 const app = express()
 const port = 8080
 
-app.use(express.static('node_modules/openmct/dist'))
 app.use(express.static('public'))
-app.get('/', (req, res) => {
-  res.sendFile(`${__dirname}/public/index.html`)
-})
+app.use(express.static('node_modules/openmct/dist'))
 
 app.listen(port, () => {
   console.log(`App listening on http://localhost:${port}`)
diff --git a/public/index.html b/public/index.html
index 70e2f64..d08504a 100644
--- a/public/index.html
+++ b/public/index.html
@@ -5,7 +5,7 @@
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Open MCT</title>
-    <script src="../node_modules/openmct/openmct.js"></script>
+    <script src="openmct.js"></script>
     <script src="init.js"></script>
 
     <link rel="icon" type="image/png" href="/node_modules/openmct/dist/favicons/favicon-96x96.png" sizes="96x96" type="image/x-icon">
diff --git a/public/init.js b/public/init.js
index ffe3d29..eb82e2f 100644
--- a/public/init.js
+++ b/public/init.js
@@ -137,5 +137,7 @@ const ONE_DAY = ONE_HOUR * 24;
   openmct.install(openmct.plugins.Timelist());
   openmct.install(openmct.plugins.BarChart());
   openmct.install(openmct.plugins.ScatterPlot());
-  openmct.start();
+  document.addEventListener('DOMContentLoaded', function () {
+    openmct.start();
+});
 }());
```

- The changes inside the `index.js` I did so that the `index.html` of the `dist` folder gets used
- The changes inside `index.html` I did because it wasn't working before
- The changes inside `init.js` I did so that the event order was making sense. So now the plugin gets queued in with the DOMContentLoaded event first, executed and then after that at a later stage openmct gets queued in and executed when the plugin is already loaded.

I will re-check with my team, but for me this sounds logical and more luck that it was working before.

**Comment by ozyx** [comment]
@mxschmitt 

Thanks so much for taking the time to look at this (my apologies for the malfunctioning repro!). I'll dig into this a bit further today with the information you've provided and update in this thread.

**Comment by ozyx** [comment]
@mxschmitt: 
Thanks again for your help here. I was able to get our CI suite passing with 1.32.3 using your change. I'll go ahead and close this for now. I'll re-open if anything crops up in the future that points to an underlying Playwright issue.
