### ISSUE TITLE
[Feature] Reuse and adjust the built-in reporters (JUnit)

### ISSUE THREAD

**Issue by anastasiia-petrenko** [microsoft/playwright#22478]
Version: 1.30

For reporting purposes, we use the JUnit report format. Such an approach requires additional logic of sending results (reports) to 3rd-party. Your junit reporter seems to be quite comprehensive which provides a lot of useful information and lets users not worry that something may be missing.

I am wondering whether it is possible to extend the JUnit reporter class to include additional logic in the onEnd() method without the need to reinvent the wheel

The current workaround is to use 2 reporters - junit and a custom one which does only 1 thing - send results. 

```
	reporter: [
		['junit', { outputFile: '../TestResults/testReports.xml' }],
		['./jUnitInCiReporter.ts']
	],
```
That can behave differently if there is a direct dependency between junit report generation and sending that report, but the logic is separated between 2 files

If there are any recommendations on how it can be improved, I am open to communication.

That feature could allow others to benefit from built-in reporting options and add some custom logic on top

**Comment by dgozman** [comment]
@anastasiia-petrenko I don't think we'll provide an API for extending existing reporters, because that's involved for little benefit. That said, Playwright is open source, so you can always copy built-in junit reporter and modify it to your liking. 

Alternatively, if you need some features that would benefit many users, we could consider adding them to the built-in reporter.

**Comment by anastasiia-petrenko** [comment]
I haven't realized the fact that it is an open source project...
Thank you for highlighting that. Definitely will take a look into your implementation and adjust for my need
