### ISSUE TITLE
[Feature] new locator `getByExactText`

### ISSUE THREAD

**Issue by Zerotask** [microsoft/playwright#22572]
I have a lot of cases, where I'm using the getByText locator together with exact: true, because there are other texts on the same page which contain the same text.

```ts
await page.getByText("Customer", { exact: true }); // current
await page.getByExactText("Customer"); // suggestion
```

**Comment by sand4rt** [comment]
Hey @Zerotask, it is not exactly what you asked for but, it is possible to use custom locators https://playwright.dev/docs/test-fixtures#overriding-fixtures: 

```javascript
import { test as base } from '@playwright/test';

const test = base.extend({
  page: async ({ page }, use) => {
    await use(Object.assign(page, {
      getByExactText: (text) => page.getByText(text, { exact: true }),
    }));
  },
});

test('custom locator', async ({ page }) => {
  await page.getByExactText('Customer');
});
```

**Comment by aslushnikov** [comment]
Related: https://github.com/microsoft/playwright/issues/19235

**Comment by klhex** [comment]
@sand4rt Nice self-service solution. Is it possible to define that custom locator in a central place in a repo so that it's automatically available in all test files and doesn't need to be imported or defined in every test file?

**Comment by sand4rt** [comment]
Yes, see example below:

```ts
// test-utils.ts
import { test as base } from '@playwright/test';

const test = base.extend({
  page: async ({ page }, use) => {
    await use(Object.assign(page, {
      getByExactText: (text) => page.getByText(text, { exact: true }),
    }));
  },
});
```

```ts
// some-test.test.ts
import { test } from 'test-utils';

test('custom locator', async ({ page }) => {
  await page.getByExactText('Customer');
});
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
