### ISSUE TITLE
[Feature] Drag between two pages (or, how to get drag metadata?)

### ISSUE THREAD

**Issue by Exoow** [microsoft/playwright#22587]
Probably a less common use case, but anyway:
the application (a planning board) can open a separate window with a list of plannable items.
The users can drag these plannable items (from the new window) onto the planning board (original window).

I've tried various drag-and-drop methods (the one on Page, Locator and with mouse actions) but none seem to work.
An alternative solution would be to verify the "metadata" of what is being dragged - if that is somehow possible?

![image](https://user-images.githubusercontent.com/18096566/233942998-66123a94-e3b3-4d1d-b08c-3241cf033ce0.png)

**Comment by Mallikarjunkrs** [comment]
We are also waiting for this feature, in our teet scenario - we have to drag and drop between iframes

**Comment by chensce** [comment]
+1

**Comment by tommymorgan** [comment]
My company shares this need.  In our application there's an important scenario where items can be dragged from one window or tab and dropped on another.  I also tried everything I could think of to get a test working for this scenario to no avail, so I'd love to see support for drag and drop between pages.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
