### ISSUE TITLE
[Question]: 在中国使用playwright install安装过程很慢 / slow download in China region

### ISSUE THREAD

**Issue by ZeroBugHero** [microsoft/playwright#22593]
### Your question

您好,在中国使用playwright install安装过程很慢,有没有中国的cdn下载的链接呢.
Hello, the installation process of using playwright install in China is very slow. Is there a link to download cdn in China?

—-

**Edit by maintainers**

Please upvote if you are affected.

**Comment by aslushnikov** [comment]
I'll speculatively assign to Max; maybe we can do something there.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
