### ISSUE TITLE
[Feature] Auto close browser when launcher process exits

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#2261]
It would be nice if the browser would automatically close when the parent process closes. When you are running a test and want to kill it early with CTRL+C, it will leave a hanging browser.

**Comment by aslushnikov** [comment]
@jperl I just tried and it does close for me. Do you launch browser with `handleSIGINT: false`?

**Comment by jperl** [comment]
It works with a regular node script, but not inside a Jest test.

https://github.com/jperl/pw-close-repro

This works: `node ./example.script.js` + `CTRL+C`
This closes the page but leaves the browser process: `npx jest` + `CTRL+C`

Mac OS 10.15.4

**Comment by aslushnikov** [comment]
@jperl Ah! Awesome repro, thank you! I didn't understand it's jest-related. This issue was originally fixed in 2018 back in Puppeteer days: https://github.com/puppeteer/puppeteer/pull/2428

So if you use something like jest v20, it'll work (verified).

However, jest v26 doesn't dispatch SIGINT anymore, so simple scripts like this won't work:

```js
// this is `example.test.js`

// this will never be called
process.on('SIGINT', () => console.log('SIGINT!'));

test("demo", async () => {
  console.log('running test');
  await new Promise(() => {});
});
```

Is there any tear down hook that jest calls when terminating process?

**Comment by jperl** [comment]
Thank you for investigating 🙏

**Comment by pavelfeldman** [comment]
Let's move this issue to the jest-related repo.
