### ISSUE TITLE
[Question] Automatic fixture example is not clear

### ISSUE THREAD

**Issue by yogeshgadge** [microsoft/playwright#22630]
### Motivation

I would like to create certain objects and have them available to every test in beforeAll/beforeEach scope.

I would use it like this https://playwright.dev/docs/test-fixtures#using-a-fixture

```Typescript
import { test, expect } from './my-test'; /// <--- except this line

test.beforeEach(async ({ settingsPage }) => {
  await settingsPage.switchToDarkMode();
});

test('basic test', async ({ todoPage, page }) => {
  await todoPage.addToDo('something nice');
  await expect(page.getByTestId('todo-title')).toContainText(['something nice']);
});
```

But I would like them to be to "automatic". 
i.e. `import { test, expect } from './my-test';` I don't want to import in every test file.

Following https://playwright.dev/docs/test-fixtures#automatic-fixtures it shows my-test.ts

But how is my-test.ts "registered" i.e. how does playwright know that where to find auto fixtures when then are not imported ?

**Comment by mxschmitt** [comment]
The way how adding custom fixtures are working is that you are essentially extending the Playwright base fixtures (the default `test` export) and then exporting it inside your own project and using this everywhere instead of Playwright's `test` export.

You need to change all your imports if you want to leverage them, there is no way such as registering and using them globally as of today. If I understood your question correctly.

**Comment by aslushnikov** [comment]
Closing as per above
