### ISSUE TITLE
[Feature] specify ms page.waitForLoadState('networkidle') waits for

### ISSUE THREAD

**Issue by ahmednkhan24** [microsoft/playwright#22661]
We are using PlayWright on an existing React SPA.

Our SPA has a debounced text box for filtering by a search term.
The text box wait's 500 ms before the API request to fetch the filtered item's is fired.

The [waitForLoadState](https://playwright.dev/docs/api/class-page#page-wait-for-load-state) documentation states `networkidle` waits until there are no network connections for at least 500 ms, and as far as I can tell there's no way to change this value which is resulting in the inability to truly write an automation test for this feature.

I am requesting to add an additional `waitTime` property to the optional `options` parameter to the `waitForLoadState` function that will let us configure how long to wait.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/7856.

**Comment by josephwynn-sc** [comment]
#7856 was closed so I will add my use case here: we use Playwright to test our analytics library, and there are several scenarios where our analytics beacon is not sent within the 500ms idle timeout.

Web assertions do not work for this, because we are using request interception to capture the beacons and run assertions against their payload. `Page#waitForRequest` also does not work, because in some cases there is an unknown number of beacon requests that we must wait for.
