### ISSUE TITLE
[Feature] (Docs) Explain "Opt out of parallel tests on CI"

### ISSUE THREAD

**Issue by matthias-ccri** [microsoft/playwright#22666]
Hi! I noticed the default config file says this:
```
    /* Opt out of parallel tests on CI. */
    workers: process.env.CI ? 1 : undefined,
```
But I can't find any documentation explaining why. I'd expect to find it on the [CI page](https://playwright.dev/docs/ci) or the [Best Practices page](https://playwright.dev/docs/best-practices).

Side note: my motivation to use workers in CI is because I'm using GitLab self-hosted and I tried using the `parallel` keyword but it turns out that for my few tests, the overhead of starting jobs negated the potential speed benefits of `parallel`. So I'm wondering _if it would even work_ to enable workers on CI.

**Comment by aslushnikov** [comment]
@matthias-ccri when running on CI, a common priority is stability & reproducibility. Running tests sequentially helps with that - this way, each test uses 100% of available computational resources and network bandwidth, without fighting for the available resources with other tests. Instead of local parallelization, one usual way to parallelize CI jobs is via sharding.

If, however, your CI machines have plenty of power, and I assume this is your case since you use self-hosted runner, you can safely enable parallel tests like you do for local runs.

(cc'ing @debs-obrien for the docs)
