### ISSUE TITLE
[BUG] re-filed: Adding custom header via page.route not working as expected

### ISSUE THREAD

**Issue by wingardl** [microsoft/playwright#22692]
Re-filing of https://github.com/microsoft/playwright/issues/22318 with added info on that thread

**Comment by aslushnikov** [comment]
Hey @wingardl,

Your new example is very involved; we'll need to debug your website to see what's going on. 

For example, if you are in control of the website's server, then you can probably trace the exact reason why it refuses to load the page with the extra header. If you're not in control of the website's server, then you might need to dig into it's source code and slowly reduce it (using e.g. MITM proxy) until we can understand what's going on. 

In our experience, these debugging sessions often discover server specific behaviors that gets uncovered by website automation, so the fix is usually either on the server side, or in your automation script to workaround this server behavior.

Now, I'd like to ask you to do this debugging and maybe come back to us once you arrive at a shorter repro that would be publicly accessible to us.

Thank you for filing though!

P.S. The whole idea of re-filing an issue is for us to avoid skimming through long discussions and starting fresh from the advanced state. We will appreciate if you fill in the new issue template properly. Do not hesitate to copy code snippets from old bugs if necessary; this saves us time. Thanks!
