### ISSUE TITLE
[BUG] visibility check on nested inline elements failed in safari 

### ISSUE THREAD

**Issue by stkevintan** [microsoft/playwright#22703]
### System info
- Playwright Version: [v1.32]
- Operating System: [macOS 13.2]
- Browser: [WebKit]
- Other info:

### Issue
Playwright will fail at `isVisible` or `waitFor` because safari wrongly reports the `DOMRect.width` of some nested inline elements:
```html
<inline-element-A>
      <inline-element-B>
          <div style="width: 10px; height: 20px"></div>
      </inline-element-B>   
</inline-element-A>
```
1. `B.getBoudningClientRect()` will return `{width: 10px, height: 20px}`
2. `A.getBoundingClientRect()` will return `{width: 0, height: 20px}`

Live repro demo: https://codesandbox.io/s/nested-inline-elements-23rj6i

In Safari: 
![23abffd7b1ff5e8922ed91c57aa65ac9](https://user-images.githubusercontent.com/5887203/234773387-c0c1f909-8a90-4f33-a78c-890876e4cc48.jpg)

In Chrome:
![4d43dbd3a3e8ce14811c414f4c67cd34](https://user-images.githubusercontent.com/5887203/234773564-3834d305-150a-4824-950c-3bd929ebbe6b.jpg)

As I observed, the issue occurs ONLY in:
1. `width` property
2. nested inline elements 
3. Safari (mac) 

### Possible Solution
Recursively check the children's visibility of inline elements for such scenario.

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/microsoft/playwright/blob/eceaee7a581c0d9dc7c1aff73107f7631d594ffc/tests/page/locator-is-visible.spec.ts#L90

**Steps**
- Run test in safari

**Expected**

Element should be visible

**Actual**
Test failed with element not visible

**Comment by pavelfeldman** [comment]
> Live repro demo: https://codesandbox.io/s/nested-inline-elements-23rj6inested-inline-elements

I get "Sandbox not found"

**Comment by stkevintan** [comment]
Sorry, here is the link: https://codesandbox.io/s/nested-inline-elements-23rj6i

**Comment by dgozman** [comment]
@stkevintan Thank you for the sandbox! It looks like the example is the same artificial one. Could you please share the real example, so that we better understand the intent? We don't want to reimplement native browser APIs for the edge cases where browser vendors disagree, so trying to understand the issue better to figure out a good solution.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
