### ISSUE TITLE
[BUG] Possible to infinitely hang a test with while(true)

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#22724]
### System info
- Playwright Version: 1.33
- Operating System: Windows 11
- Browser: All
- Other info:

### Source code

```ts
import { test, expect } from "@playwright/test";

test("get started link", async ({ page }) => {
  while (true) {
    const i = 2;
  }
});

```

- [ x] I provided exact source code that allows reproducing the issue locally.

**Steps**
- yarn playwright test --timeout 5000 example

**Expected**
Test will timeout after 5s

**Actual**
Test never times out and stays in the while(true)loop

This reproduces in jest as well ,  it would be good to provide a message to the user or CI/CD that `testcase foo is hanging!` or a watchdog timer for tests?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
