### ISSUE TITLE
[Feature] Support TypeScript project references

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/playwright#22761]
For reference, [here are the docs for TypeScript's project references](https://www.typescriptlang.org/docs/handbook/project-references.html).

Full reduced test case: https://github.com/OliverJAsh/playwright-ts-paths-issues/tree/project-references

`tsc --build tsconfig.json --verbose` reports no errors, yet when we run `playwright test` we get this error:

```
Error: Cannot find module 'helpers/other'
Require stack:
- /Users/oliverash/Development/playwright-ts-paths-issues/app/app.ts
```

This is because Playwright isn't consulting `tsconfig.app.json` to resolve the imports in `app/app.ts`.

This also came up here: https://github.com/microsoft/playwright/issues/12829#issuecomment-1343483232

**Comment by dgozman** [comment]
Note: supporting `references` also requires interpreting `include`, `exclude` and `files` options, so that we can understand which of the referenced configs to apply to each of the files.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by fungairino** [comment]
This is a big deal for us - we use playwright in a monorepo with project references. This makes it very difficult to get our e2e project tsconfig working

**Comment by dgozman** [comment]
@fungairino Please file a new issue with a repro by filling in the "Bug Report" template.

**Comment by kleinfreund** [comment]
> Please file a new issue with a repro by filling in the "Bug Report" template.

Why is a reproduction required for a feature request? My understanding is that Playwright doesn't currently resolve `references` in tsconfig so there isn't really anything to reproduce here as that's the currently expected behavior.

I think this issue is perfectly fine to re-open.
