### ISSUE TITLE
[BUG] 'React is not defined' on a shared package after updating to 1.33.0

### ISSUE THREAD

**Issue by gabriel-pq** [microsoft/playwright#22789]
### System info
- Playwright Version: [v1.33.0]
- Operating System: [macOS 13.3.1]
- Browser: N/A
- Other info: React version 18.2.0; Node version 16.13.1

### Source code
The situation is quite simple:
I have a package with playwright tests `my-playwright-e2e-tests` and as part of the dependencies(package.json) I'm using `util-react`.

`util-react` is a local, shared react package, tested with jest and it's completely independent. I'm using this package just for importing some functions that are handling various strings based on some rules and nothing more!

I used Playwright v1.32.1 before the upgrade and everything was fine. After upgrading I get this error:
`ReferenceError: React is not defined` on a particular file within the `util-react` package. This is strange!

The file contains:
```
export type ErrorType = {
  code: number;
  ErrorText: JSX.Element;
  IncludeHomeLink: boolean;
  pageTitle: string;
};

export const errors: ErrorType[] = [
  {
    code: 500,
    pageTitle: 'Something went wrong',
    ErrorText: <p>Please try again.</p>,
    IncludeHomeLink: true,
  }
]
```

The solution was to add at the top of the file `import React from 'react';`. This is weird! One because the tests within the `util-react` passes without problems AND because in newer versions of React (since version 17), you no longer need to import React to use JSX syntax. This means that you can use JSX syntax and return JSX elements without importing React explicitly.

What's the catch?

**Expected**

Playwright test code should run without modifying unused code from a shared package that is working perfectly and the tests written for it passes.

**Comment by yury-s** [comment]
@gabriel-pq can you share a sample project where this happens?

**Comment by yury-s** [comment]
@sand4rt any clue why this may happen?

**Comment by gabriel-pq** [comment]
@yury-s @sand4rt  - Please checkout [this sample project](https://github.com/gabriel-pq/my-bug-playwright) I just made.

It should work without the import because of the React version used.

Please let me know if you have any questions.

Without import:
![image](https://user-images.githubusercontent.com/85311517/235991649-4d4550f0-6c2f-4b54-82bb-1998e4b7b461.png)

With import:
![image](https://user-images.githubusercontent.com/85311517/235991805-228a9b58-d528-4ee5-bedb-17c96a7194c8.png)

**Comment by sand4rt** [comment]
Thank you for providing the example, @gabriel-pq! I encounter the same error, unfortunately.

@yury-s It appears that the unused `.tsx` files are not ignored/tree shaken during the transpile/transform process. Initially, i thought this issue was related to component testing, but it turns out not to be the case. I have not worked on this part of the codebase before, so it may takes me some time to become familiar with it. Perhaps it would be more efficient if someone else to look at this.

**Comment by yury-s** [comment]
@gabriel-pq thats for the repro! and @sand4rt thanks for looking into this!

**Comment by pavelfeldman** [comment]
> @yury-s @sand4rt - Please checkout [this sample project](https://github.com/gabriel-pq/my-bug-playwright) I just made.

Your source code:

```js
export const errors: ErrorType[] = [
  {
    code: 500,
    pageTitle: 'Something went wrong',
    ErrorText: <p>Please try again.</p>,
    IncludeHomeLink: true,
  }
];
```

is transpiled into

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.errors = void 0;
const errors = [{
  code: 500,
  pageTitle: 'Something went wrong',
  ErrorText: /*#__PURE__*/React.createElement("p", null, "Please try again."),
  IncludeHomeLink: true
}];
exports.errors = errors;
```

Playwright has no knowledge about the component framework you are using, so its defaults to the 'React classic' syntax as per https://babeljs.io/docs/babel-plugin-transform-react-jsx's defaults. We are not expecting is that you start building your Browser UI in the tests that run in Node.js. Usually components are built in the functional components that aren't supposed to be called automatically when you require helpers.

We can switch into the 'automatic' imports mode where you can give transpiler hints about the framework used, but if we do that, we are likely to mask the problem that you have in the code (creating components inside tests).

**Comment by pavelfeldman** [comment]
As a workaround, changing your code to following will make it work:

```js
export const errors: ErrorType[] = [
  {
    code: 500,
    pageTitle: 'Something went wrong',
    ErrorText: () => <p>Please try again.</p>,
    IncludeHomeLink: true,
  }
];
```

As a rule, always opt for functional components (or class components, if needed) when working with React, as they follow the guidelines and best practices of the library. Otherwise you end up with non-modular, sub-optimal code with unnecessary re-renders that does not follow the React component architecture.

**Comment by gabriel-pq** [comment]
@pavelfeldman Thanks for investigating this!

The workaround you mentioned works, but it has ramifications in all places, e.g. tests and files where is being used. Another workaround I mentioned above is adding one line `import React from 'react';` at the beginning of the file and it works.

In my example, I included the bare minimum to generate that error. (the original code has a bunch of config files and stuff).

I do get the fact that I should consider only the files needed as shared and not the entire package - but Is still a bug, isn't it? as if I revert to the previous version of Playwright I won't get any errors.

**Comment by pavelfeldman** [comment]
> I do get the fact that I should consider only the files needed as shared and not the entire package - but Is still a bug, isn't it? as if I revert to the previous version of Playwright I won't get any errors.

I don't think it is a bug. Playwright does not know if you are using React, Preact or Vue. JSX is a universal syntax, but only your bundler knows what to do with your JSX constructs.

If I add one line to your example:

```js
console.log(errors.ErrorText);
```

it would be clear that you want JSX element to be instantiated at the import time. But that's an impossible task since we don't know which framework you are using.

We can try stubbing out entire JSX to support your scenario, but as I said, we would be masking a bug that way since we don't have a way of knowing what the value of `errors.ErrorText` is. And if your code relies on that value, your tests will break.
