### ISSUE TITLE
[Feature] Support custom plugins

### ISSUE THREAD

**Issue by DudaGod** [microsoft/playwright#22798]
Hello guys. In [my team](https://github.com/gemini-testing) we are interested in implementing custom plugins for playwright.  Moreover we are ready to contribute core implementation. But first we want to discuss with you whether you are interested in such an opportunity and future support. And if you are interested and ready to give us the green light for implementation, then we need to discuss the desired API.

## Use cases

Ability to write plugins which will:
- save test execution statistics in the database in order to define flaky tests that will be disabled by the plugin before running the tests (this means that the plugin needs access to read tests)
- reporter with gui (web server under the hood). It will gives opportunity to save screenshot references by clicking on the button from the report. Or run tests from the gui
- change config dynamically (for example change grid url by some condition)
- make some preparation before tests (for example hide scrollbars for some browsers)
- save/read network requests/responses to the dump file in order to increase tests stability
- and so on ...

## Benefits for other users

We believe this feature will allow users to implement many useful plugins that can be shared with the community.

Looks like that these issues are good examples demonstrating community interest:
- https://github.com/microsoft/playwright/issues/13362
- https://github.com/microsoft/playwright/issues/16690

## Possible implementations

- create pwt events for which plugins will subscribe and do their job
- create lifecycle hooks (like for custom reporters - https://playwright.dev/docs/test-reporters) on which plugins will do their job

**Comment by yury-s** [comment]
So far all mentioned use cases can be implemented with the existing capabilities:

> * save test execution statistics in the database in order to define flaky tests that will be disabled by the plugin before running the tests (this means that the plugin needs access to read tests)

Test run status can be written to the database by a [custom reporter](https://playwright.dev/docs/test-reporters#custom-reporters).

You can introduce an [auto-fixture](https://playwright.dev/docs/test-fixtures#automatic-fixtures) that would read the data from the database and decide whether current test should be skipped:
```js
import { TestInfo, test as base } from '@playwright/test';

function shouldSkip(info: TestInfo): boolean {
  // Decide based on the historical data if the test should be skipped based on info.title, info.titlePath, info.testId etc.
}

export const test = base.extend<{ saveLogs: void }>({
  saveLogs: [async ({}, use) => {
    if (shouldSkip(test.info()))
      test.skip();
    await use();
  }, { auto: true }],
});

export { expect } from '@playwright/test';
```

Alternatively, before running the tests you can run `npx playwright test --list` and for each test in the list decide wether it should run. Then pass filtered list of the tests to `npx playwright test` so that no flaky tests are executed. If you face any command line length limitations we can support reading arguments from a file.

> * reporter with gui (web server under the hood). It will gives opportunity to save screenshot references by clicking on the button from the report. Or run tests from the gui

This should be implementable with the existing [reporter API](https://playwright.dev/docs/api/class-reporter).

> * change config dynamically (for example change grid url by some condition)

The config can be preprocessed to your liking as a separate step before running tests and then passed to playwright via `-c` option. We don't support dynamic modifications of the config after it has been loaded, but so far there was no good use case for it. Do you have one?

> * make some preparation before tests (for example hide scrollbars for some browsers)

This should be achievable with [fixtures](https://playwright.dev/docs/test-fixtures) or beforeAll/beforeEach hooks.

> * save/read network requests/responses to the dump file in order to increase tests stability

This can be done today with [routeFromHar](https://playwright.dev/docs/api/class-browsercontext#browser-context-route-from-har). Some of the requests can be served from prerecorded HAR file, others [fulfilled](https://playwright.dev/docs/network#handle-requests) dynamically  while rest is served from the network.

> and so on ...

We are not opposed to the feature but given the complexity and maintenance cost it entails, there have to be compelling use cases which can't be solved without plugins.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by DudaGod** [comment]
Sorry for the long reply (i was on vacation) and thanks for the very detailed answer. 

> The config can be preprocessed to your liking as a separate step before running tests and then passed to playwright via -c option. We don't support dynamic modifications of the config after it has been loaded, but so far there was no good use case for it. Do you have one?

For example, we want to write fixture which will dynamically increase the number of retries for a test that crashed with some infrastructure error.

> We are not opposed to the feature but given the complexity and maintenance cost it entails, there have to be compelling use cases which can't be solved without plugins.

I tried the fixtures you suggested and they really cover most of our cases. I found some problems, but I will start a separate issue about them. Thank you.
