### ISSUE TITLE
[BUG]Playwright is taking more than 30 to 50 seconds to launch on browser

### ISSUE THREAD

**Issue by abdulsajidgsits** [microsoft/playwright#22815]
### System info
- Playwright Version: 1.33.0
- Operating System: windows 10 pro
- Browser: Chromium, Firefox, WebKit
- node version:18.16.0

The playwright is taking more than 30 seconds to open the browser, We have tried a lot and seen many solutions for this but still, we are facing this issue. We are trying to get a solution for this but are not able to find what we can do to resolve this issue. I am from a software company and we want to use Playwright to test our web portal.
We have tried different versions along with stable browsers, and now we have changed all to the latest versions.
Any help in this regard would be highly appreciated.

![time](https://user-images.githubusercontent.com/132567268/236186127-724e20e1-2b9f-46a3-a13b-02fa449cd8f1.JPG)

**Comment by yury-s** [comment]
Can you share minimal project where you observe the slowness so that we could try it locally? If you run with a branded browser it may be caused by some enterprise [policies](https://playwright.dev/docs/troubleshooting#incompatible-microsoft-edge--google-chrome-policy-settings). You can try launching the same browser manually and see how much time it takes (run with DEBUG=pw:browser to see the command line that Playwright uses to launch the browsers).

Does it reproduce with all browsers?

**Comment by abdulsajidgsits** [comment]
We are trying to run on basic after doing a setup for the playwright. even it is taking time to run an example code.

**Comment by abdulsajidgsits** [comment]
The issue is resolved now, It was a problem related to a network drive. Thanks for the response. Much appreciate

**Comment by vlokesh09** [comment]
> The issue is resolved now, It was a problem related to a network drive. Thanks for the response. Much appreciate

Hey abdul, I am running into similar issue . Can you expand little bit on what the network drive issue is ?

**Comment by abdulsajidgsits** [comment]
hi, try to check if your playwright file is saved on network drive. If it is on network drive(server) so change the file location to your local system

**Comment by mikhail-g** [comment]
I had a simlar issue: it took 1-2 minutes from the starting tests in CLI to showing the first line in the terminal "running 1 test" 
The issue was in having to little RAM on the machine
