### ISSUE TITLE
[BUG] Install stuck on downloading chromium

### ISSUE THREAD

**Issue by bonpur** [microsoft/playwright#22878]
### System info
- Playwright Version: [v1.33]
- Operating System: [Windows 10]
- Browser: [All]
- Other info:

### Source code

playwright install 
Downloading Chromium 113.0.5672.53 (playwright build v1060) from https://playwright.azureedge.net/builds/chromium/1060/chromium-win64.zip

stuck for hours. but can download the chromium manually in less than 60 seconds

what should i do?

**Comment by pavelfeldman** [comment]
Are you downloading them from the same machine?

**Comment by bonpur** [comment]
> Are you downloading them from the same machine?

Yes

**Comment by pavelfeldman** [comment]
Could it be that your browser is using some http proxy? If so, refer to the https://playwright.dev/docs/next/browsers#install-behind-a-firewall-or-a-proxy docs.

**Comment by bonpur** [comment]
> Could it be that your browser is using some http proxy? If so, refer to the https://playwright.dev/docs/next/browsers#install-behind-a-firewall-or-a-proxy docs.

No proxy

**Comment by pavelfeldman** [comment]
We don't have any other reports like this and we are seeing millions of weekly browser downloads. As long as we can't repro it we can't act on it. We would appreciate if you could try debugging it locally, but there isn't much we can do from here.

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this. As long as we can't repro it, we can't act on it.

**Comment by kachkaev** [comment]
Same issue here on macOS. The download gets stuck towards the end of the process. 

```sh
❯ pnpm exec playwright install               
Removing unused browser at /Users/me/Library/Caches/ms-playwright/chromium-1071
Removing unused browser at /Users/me/Library/Caches/ms-playwright/firefox-1420
Removing unused browser at /Users/me/Library/Caches/ms-playwright/webkit-1872
Downloading Chromium 120.0.6099.28 (playwright build v1091) from https://playwright.azureedge.net/builds/chromium/1091/chromium-mac-arm64.zip
131 Mb [=================== ] 96% 1.9s

[ctrl+c]




❯ pnpm exec playwright install
Downloading Chromium 120.0.6099.28 (playwright build v1091) from https://playwright.azureedge.net/builds/chromium/1091/chromium-mac-arm64.zip
131 Mb [=================== ] 97% 2.1s

[ctrl+c]


❯ rm -fr ~/Library/Caches/ms-playwright

❯ pnpm exec playwright install
Downloading Chromium 120.0.6099.28 (playwright build v1091) from https://playwright.azureedge.net/builds/chromium/1091/chromium-mac-arm64.zip
131 Mb [=================== ] 96% 1.8s
```

Not sure how to debug this.

**Comment by kachkaev** [comment]
OK, I _might_ have an explanation and a workaround. Download progress bar seems to be stuck because of this chunk of code: https://github.com/microsoft/playwright/blob/888f4965bfd87ef59d463286c88c4a658605d92e/packages/playwright-core/src/server/registry/oopDownloadBrowserMain.ts#L86-L88

We send progress messages to the upstream process via `onData`, but if `response` fails, there is no propagation of the error. So the progress bar gets stuck waiting for more messages forever. I added these extra lines locally and ran `pnpm exec playwright install chromium`:

```diff
  response.pipe(file); 
  response.on('data', onData);
+ response.on('aborted', payload => console.log('response aborted', payload))
+ response.on('close', payload => console.log('response close', payload))
+ response.on('error', payload => console.log('response error', payload))
  response.on('close', () => { 
 ```

This is what I got in the ‘stuck’ output:

```txt
131 Mb [====================] 97% 1.6sresponse aborted undefined
response error Error: aborted
    at connResetException (node:internal/errors:787:14)
    at TLSSocket.socketCloseListener (node:_http_client:455:19)
    at TLSSocket.emit (node:events:526:35)
    at node:net:337:12
    at TCP.done (node:_tls_wrap:657:7) {
  code: 'ECONNRESET'
}
response close undefined
```
(had to press Ctrl+C as before)

This change allowed me to propagate the error and get an adequate exit code:

```diff
  response.pipe(file); 
  response.on('data', onData);
+ response.on('error', error => promise.reject(error));
  response.on('close', () => { 
 ```

Output:

```txt
Downloading Chromium 120.0.6099.28 (playwright build v1091) from https://playwright.azureedge.net/builds/chromium/1091/chromium-mac-arm64.zip
131 Mb [=================== ] 97% 2.3sError: aborted
    at connResetException (node:internal/errors:787:14)
    at TLSSocket.socketCloseListener (node:_http_client:455:19)
    at TLSSocket.emit (node:events:526:35)
    at node:net:337:12
    at TCP.done (node:_tls_wrap:657:7) {
  code: 'ECONNRESET'
}
Downloading Chromium 120.0.6099.28 (playwright build v1091) from https://playwright-akamai.azureedge.net/builds/chromium/1091/chromium-mac-arm64.zip
131 Mb [====================] 97% 1.6sError: aborted
    at connResetException (node:internal/errors:787:14)
    at TLSSocket.socketCloseListener (node:_http_client:455:19)
    at TLSSocket.emit (node:events:526:35)
    at node:net:337:12
    at TCP.done (node:_tls_wrap:657:7) {
  code: 'ECONNRESET'
}
Downloading Chromium 120.0.6099.28 (playwright build v1091) from https://playwright-verizon.azureedge.net/builds/chromium/1091/chromium-mac-arm64.zip
131 Mb [====================] 97% 1.7sError: aborted
    at connResetException (node:internal/errors:787:14)
    at TLSSocket.socketCloseListener (node:_http_client:455:19)
    at TLSSocket.emit (node:events:526:35)
    at node:net:337:12
    at TCP.done (node:_tls_wrap:657:7) {
  code: 'ECONNRESET'
}
Failed to install browsers
Error: Failed to download Chromium 120.0.6099.28 (playwright build v1091), caused by
Error: Download failure, code=1
    at ChildProcess.<anonymous> (/path/to/project/.pnpm/playwright-core@1.40.0/node_modules/playwright-core/lib/server/registry/browserFetcher.js:94:16)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

I was on Node 18.18.2 so I thought it could be a bug like https://github.com/nodejs/node/issues/50403 etc. After switching to Node 20.10.0, the same error remained.

I checked `playwright-core/lib/utils/network.js` to make sure it did not [`rejectOnTimeout`](https://github.com/microsoft/playwright/blob/888f4965bfd87ef59d463286c88c4a658605d92e/packages/playwright-core/src/utils/network.ts#L84), but that was unrelated. Downloads often took more than 30 seconds (default timeout value), but they only failed _just_ before the completion, seemingly during the transfer of the last data chunk. Docs for `ECONNRESET` say that this error occurs when the _peer_ decides to terminate the connection. My knowledge is not deep enough to understand why.

When I click on links like `https://playwright.azureedge.net/builds/chromium/1091/chromium-mac-arm64.zip` archives get successfully downloaded via the browsers. That’s not very useful for fixing `playwright install` though.

![Screenshot 2023-11-25 at 19 28 49](https://github.com/microsoft/playwright/assets/608862/2db002c8-edbf-46d6-8eb4-40af6ccbb4d0)
![Screenshot 2023-11-25 at 19 29 02](https://github.com/microsoft/playwright/assets/608862/215c6e58-c82c-480a-a8cf-abae572cb3f1)

So `ECONNRESET` might be specific to how Playwright Core deals with request streams.

---

Interestingly, when I tried two different VPNs, browser downloads worked 🤔. One connection was faster than my default ISP speed, another one was slower, but both worked. So `ECONNRESET` was a function the request’s IP address & user agent 🤯

**Comment by kachkaev** [comment]
Also found https://github.com/microsoft/playwright/issues/28189 and https://github.com/microsoft/playwright/issues/28329. These issues were closed on `main` via https://github.com/microsoft/playwright/pull/28278
