### ISSUE TITLE
[Question| Slight documentation clarification for "networkidle"

### ISSUE THREAD

**Issue by jhyot** [microsoft/playwright#22897]
The documentation on https://playwright.dev/docs/navigations#navigation-lifecycle says:

> networkidle is fired when no new network requests are made for 500 ms

Does the event wait for all network requests to be finished, and only then fires, or only that no new requests are started within the last 500ms?

Maybe a slightly clearer wording could be used for the docs to make it unambiguous.

**Comment by petroslamb** [comment]
Reached here also looking why `networkidle` is discouraged. It looks promising for pages that i can not make any assumptions for and other strategies fail.

**Comment by SeanDuignan82** [comment]
> `networkidle` is [discouraged](https://playwright.dev/docs/next/api/class-frame#frame-goto-option-wait-until). You can only use `networkidle` in the controlled setting (lab testing), it will pretty much never work against any production page. Rely upon web assertions instead of waiting for the network.

I've encountered this issue and discovered only one workaround... deploy it in a Docker container. I've can confirm it works. So please don't remove this option in a future release.

If anyone is interested, the issue is caused by active network connections held open by other applications... for me it was GIT. GIT held open an active connection (possibly a websocket ) for the duration of my git hooks execution.

**Comment by samyismaiel** [comment]
Why is networkidle discouraged? It definitely solved flakiness. Can I rely on this option to be supported?
