### ISSUE TITLE
[BUG] browserContext userAgent seems not working in playwright webkit after 1st Page

### ISSUE THREAD

**Issue by Kingkhan14** [microsoft/playwright#22917]
### System info
- Playwright Version: [v1.33]
- Operating System: [Windows 11]
- Browser: [WebKit]

i set userAgent in browsercontext using launchPersistentContext as 
`Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1`

but when opening new window and checking in webkits console its showing as 
`Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/605.1.15 (KHTML, like Gecko)`

![image](https://github.com/microsoft/playwright/assets/108714133/2ac571a5-3dda-4b6c-b4f8-c6afcd781ad6)

below code used for test

### Source code
```
const { webkit }    = require('playwright');

(async () => {
    const context = await webkit.launchPersistentContext('my-data', {
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604',
      headless: false
    });
    const page = await context.newPage();
    page.goto('https://www.whatismybrowser.com/detect/what-is-my-user-agent/');
  })();

```

**Comment by Kingkhan14** [comment]
Below is the code used to test

`const { webkit }    = require('playwright');

(async () => {
    const context = await webkit.launchPersistentContext('my-data', {
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604',
      headless: false
    });
    const page = await context.newPage();
    page.goto('https://www.whatismybrowser.com/detect/what-is-my-user-agent/');
  })();`

**Comment by pavelfeldman** [comment]
> but when opening new window and checking in webkits console its showing as

If you are opening this window via UI instead of calling context.newPage(), this is expected.

**Comment by Kingkhan14** [comment]
does this related to webkit only issues ?
because same code with chromium doesn't seems to be an issue

![image](https://github.com/microsoft/playwright/assets/108714133/bc445a76-80e9-4a9e-8352-e48f31ed3520)

**Comment by pavelfeldman** [comment]
As long as you are opening those windows by hand, there are no emulation guarantees. Only programmatically opened pages have all the emulated bits enabled, including the user agent!

**Comment by Kingkhan14** [comment]
for webkit??

**Comment by MelonAnthony** [comment]
I also encountered a related issue where I set the UA in the context, but it didn’t work on Chromium. Could you give me your demo for reference? Also, which version are you using?

**Comment by dathacky** [comment]
+1 error

**Comment by aphex** [comment]
@pavelfeldman Just coming across this as well. Not great the context doesn't stay from window to window, but I am trying to do something even more basic, just open devtools to work through some issues. 

The issue seems with webkit just opening devtools and refreshing the current page loses the context information.

To recreate this just launch a new page with playwright webkit and in the context pass in a new `userAgent`. For example I am using the `Desktop Safari` device preset. Then visit `https://www.whatismybrowser.com/detect/what-is-my-user-agent/`

I get `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15
` as expected. 

Then right click and inspect element, do nothing in devtools just click reload on the page, you will see the `userAgent` switches back. This is making it impossible to use devtools to work through some issues that are userAgent specific. 

Any thoughts?
