### ISSUE TITLE
[BUG] PDF preview is not disabled on webkit using the file protocol

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#23003]
### System info
- Playwright Version: v1.33
- Operating System: macOS 13.2
- Browser: WebKit
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/kblok/playwright-troubleshooting](https://github.com/kblok/playwright-troubleshooting)

```js
import { test } from '@playwright/test';

test('pdf in iframe', async ({ context, page }) => {
  await page.goto(`file://${__dirname}/pdfInFrame.html`); // In the repo
  await page.waitForTimeout(5_000);
  await page.goto(
    "https://hardkodeddemos.z13.web.core.windows.net/pdfInFrame.html"
  );
  await page.waitForTimeout(5_000);
});
```

**Steps**
- Run test using `npx playwright test pdf-in-iframe --browser webkit`
- Look at the iframe being loaded or not

**Expected**

According to https://github.com/microsoft/playwright/pull/15462 and https://github.com/microsoft/playwright/pull/20551 the PDF viewer should be disabled in Webkit.

**Actual**

I get to see the viewer on iframes, but only with the `file://` protocol. I don't know whether that's because of that protocol or not.
<img width="848" alt="Screenshot 2023-05-12 at 18 49 20" src="https://github.com/microsoft/playwright/assets/2198466/821b78ea-d1aa-4155-8370-7ed79667cd43">

<img width="888" alt="Screenshot 2023-05-12 at 18 49 15" src="https://github.com/microsoft/playwright/assets/2198466/6d44f0c0-b94c-4cc9-a938-d3d00be072f3">

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
