### ISSUE TITLE
[BUG] electron launch timeout 3000ms after update playwright to 1.33.0

### ISSUE THREAD

**Issue by painttw07** [microsoft/playwright#23033]
### System info
- Playwright Version: 1.33.0
- Operating System: Windows 11
- Browser: electron
- Other info: 

Before I update playwright today (May, 15), this error didn't happen. I tried to run the same script last week and was running ok. Didn't happen any update in my electron app that could possible break.

**Test file (self-contained)**

```js
test.beforeEach(async ({ page }) => {
        electronApp = await electron.launch({ executablePath:  '< my electron path >' });
        window = await electronApp.firstWindow();
```

**Expected**

Expect to open the electron app and run the test script.

**Actual**

Appears the error: 
 1) test_LoginNGMT.spec.js:26:5 › Try to Sign In › login field ────────────────────────────────────
    Test timeout of 30000ms exceeded while running "beforeEach" hook.

**Comment by dgozman** [comment]
@painttw07 Your test times out with 30 seconds. There are two possibilities:
- Your test timeout is too small. Look at [this timeouts guide](https://playwright.dev/docs/test-timeouts) for help.
- There is a bug somewhere, and either `launch()` or `firstWindow()` hangs. In this case, providing a repro that we can run locally would be very helpful. Otherwise, it's unlikely we'll be able to fix the issue.
