### ISSUE TITLE
[BUG] Bypass CSP bit can be cached on Firefox

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#2316]
Added a failing capabilities test

**Comment by aslushnikov** [comment]
My investigation:
- removing all our bypasscsp-checks (the `docShell.bypassCSP`) from firefox doesn't change anything
- csp actually works if trying to navigate to `assets/csp.html`
- csp actually works when trying to call `page.addScriptTag`

This happens since we currently disable CSP checks when running `evaluate`:

https://github.com/aslushnikov/juggler/blob/6bbb629c469c5c636efffe54cdd107f44dfb0092/js/src/debugger/Object.cpp#L2389-L2392

We might have a bug since the value might be cached:

https://github.com/aslushnikov/juggler/blob/6bbb629c469c5c636efffe54cdd107f44dfb0092/js/src/vm/GlobalObject.cpp#L834
