### ISSUE TITLE
[Feature] Improve exceptions handling 

### ISSUE THREAD

**Issue by Rafiot** [microsoft/playwright#23293]
First of all, let's make it very clear: the way I use playwright isn't the intended one, but I still think it would be useful for others.

Right now, Playwright will raise two types of exceptions: `Error` and `TimeoutError` (which is a subclass of `Error`). But in practice, many different types of exceptions are raised, and they are all pretty nicely described in the `message` field. The issue I have is that it is hard to programmatically figure out what went wrong during the run because this message is multi-line and somewhat free text.

I did some [pretty dirty](https://github.com/Lookyloo/PlaywrightCapture/blob/eef99ec72f675957d56300ef065bc4dc439bcc4b/playwrightcapture/capture.py#LL583C17-L583C17) error parsing and try to keep the (relevant part) of the first line of the `message` as an error `name` I can handle down the line, depending on what wrong and what I consider being a recoverable error and re-run the capture accordingly.

What I would love is either more exceptions types, or what I use as a `name` being accessible from the exception class directly, in a similar way I implemented it, minus parsing and splitting the first line of the message.

**Comment by mxschmitt** [comment]
There are all Chromium error codes, since browser errors are highly specific to the browser and change over time, we don't plan to add any kind of standardisation or parsing to them.

See here for all the Chromium error codes: https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:net/base/net_error_list.h;drc=50061fdd60b62a7c022a12a04e14d6e10b81bf19;l=581

We recommend that you continue to parse the exceptions in the user land.
