### ISSUE TITLE
[BUG] SVG <text> element is classed as visible, despite it's parent being hidden

### ISSUE THREAD

**Issue by jdwholmes** [microsoft/playwright#23300]
### System info
- Playwright Version: [v1.33.0]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [Chromium, WebKit] (Seems to work correctly in Firefox)
- Other info:

### Source code

```html
<svg>
<g style="display:none;" opacity="1"><path d="M187.056 22.934 L 220.861 22.934 220.861 44.934 187.056 44.934Z" stroke="none" fill="none"></path><text style="font:12px Roboto;white-space:pre;" x="182.45833333333337" y="37.933930488983336" stroke="none" fill="#105674" fill-opacity="1">530,311</text></g>
</svg>
```

**Test file (self-contained)**

```js
test('display nth', async ({ page, baseURL }) => {
    const dashboardFixture = 'BasicColumnChartIncomePeople';
    await dashboardPage.dashboardFromFixture(
      dashboardFixture,
      apiContext,
      page,
      baseURL,
      dashboardPage
    );

    await expect(page.getByText('530,311')).toBeHidden();          
});
```

**Steps**
I have setup an example using try.playwright.tech here (https://try.playwright.tech/?l=playwright-test&s=y4vck1q)

**Expected**

I would expect the element containing 530,311 to be hidden, as the parent g tag has display none.

**Actual**

Test will fail as it classes the element as visible. I am currently using the below workaround.

```js
let parentDisplay = await page
            .getByText('530,311')
            .evaluate((node: SVGElement) => node?.parentElement?.style?.display);
          expect(parentDisplay).toBe('none');
```

**Comment by aslushnikov** [comment]
@jdwholmes Thank you, I can repro on Chromium and Webkit. Works as expected on Firefox. 

```ts
// a.spec.ts
import { test, expect } from '@playwright/test';

test('should work', async ({ page }) => {
  await page.setContent(`
    <svg>
      <g style="display: none">
        <text x="100" y="100">hello</text>
      </g>
    </svg>
  `);
  await expect(page.getByText('hello')).toBeHidden();
});
```

**Comment by dgozman** [comment]
Investigation notes: `text.getBoundingClientRect()` returns non-empty rect. Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=336530. Haven't found WebKit issue yet.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
