### ISSUE TITLE
[Feature] Need for a Mobile device variant for Firefox browser in playwright devices

### ISSUE THREAD

**Issue by Jamesj001** [microsoft/playwright#23323]
- We have started with a project for Visual regression tests using playwright we have currently taken in consideration : 6 variants i.e 

1. DESKTOP CHROME
2. DESKTOP FIREFOX
3. DESKTOP SAFARI
4. MOBILE CHROME - a mobile device with default browser as Chrome
5. MOBILE SAFARI - a mobile device with default browser as Safari 
6. MOBILE FIREFOX - a mobile device with default browser as Firefox

For 1 to 5 we have devices under : https://github.com/microsoft/playwright/blob/c5c0b9a78bf14c2022e0395c157b9e6997a76d42/packages/playwright-core/src/server/deviceDescriptorsSource.json

But for 6th Variant i.e. Mobile Firefox we currently don't see any default device from playwright end so we wanted to understand for testing on this 6th variant : 

- Do we need to explicitly create a device from our end only by manipulating userAgent and defaultBrowserType  like : 
   ```
   "Pixel 3": {
    "userAgent": "Mozilla/5.0 (Android 13; Mobile; rv:109.0) Gecko/113.0 Firefox/113.0",
    "viewport": {
      "width": 393,
      "height": 786
    },
    "deviceScaleFactor": 2.75,
    "isMobile": true,
    "hasTouch": true,
    "defaultBrowserType": "chromium"
  }
  ```
- Is there any other way we should achieve this if not  by the above  way

And probably this ask might be helpful to other users of playwright too if they want to focus on testing on multiple browsers and multiple devices.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
