### ISSUE TITLE
[Feature] Consider update to docs on fixtures

### ISSUE THREAD

**Issue by jeremy-daley-kr** [microsoft/playwright#23397]
Can someone help consider if editing [the fixtures documentation page](https://playwright.dev/docs/test-fixtures#creating-a-fixture) might be a good idea or not?

It seems like a poor design decision to recommend that developers alias `test`, and then export their own "extended" `test`... If not at least a poor decision to recommend directly exporting `expect`. I honestly don't understand the sense of doing that, but maybe there's a very good reason for it?

Thanks.

**Comment by jeremy-daley-kr** [comment]
@mxschmitt Thank you for the response.

I kind of figured those were the reasons, but they honestly seem like questionable design choices, that potentially cause confusion and/or an unnecessary level of abstraction. One might now think that in order to start using the other exports from `@playwright/test` that they need to keep adding to the export list where a fixture was implemented.

Do you keep that practice going when the exports start to look like the following, and the fixture is 3 folders deep in a workspace package?

```javascript
export {
  chromium,
  firefox,
  expect,
  devices,
  request,
  defineConfig,
  selectors,
  Cookie,
  Dialog,
  Download,
  Electron,
  Fixtures,
  Frame,
  Metadata,
  Request,
  Response,
  VideoMode
} from '@playwright/test';
```

I'm not always such a stickler for documentation, but I've learned that this is being taken to mean THE official, recommended way to implement fixtures.

**Comment by mxschmitt** [comment]
> Do you keep that practice going when the exports start to look like the following, and the fixture is 3 folders deep in a workspace package?

No, only for these two, since all the others are types or functions which are not actively used inside tests.

export {
  // you never need since Playwright launches the browser for you
  chromium,
  firefox,
  // we re-export
  expect,
  // not needed, only in the config 
  devices,
  // we expose it as a fixture
  request,
  // only needed in the config
  defineConfig,
  // rarely used inside beforeAll or an auto worker fixture
  selectors,
  // types
  Cookie,
  Dialog,
  Download,
  Electron,
  Fixtures,
  Frame,
  Metadata,
  Request,
  Response,
  VideoMode
} from '@playwright/test';

Closing as per above

**Comment by jeremy-daley-kr** [comment]
@mxschmitt I think you're missing the point, but I digress.
