### ISSUE TITLE
[BUG] Playwright installs wrong version of Firefox

### ISSUE THREAD

**Issue by rnicholus** [microsoft/playwright#23396]
### System info
- Playwright Version: 1.34.3
- Operating System: MacOS
- Browser: Firefox
- Other info:

### Source code

N/A

**Steps**
- Install Playwright/test
- Look for downloaded FF version in `~/Library/Caches/ms-playwright/`

**Expected**

Stable version of Firefox downloaded.

**Actual**

Nightly version of Firefox downloaded. This is at odds w/ [the official docs](https://playwright.dev/docs/browsers#firefox):

>Playwright's Firefox version matches the recent [Firefox Stable](https://www.mozilla.org/en-US/firefox/new/) build.

**Comment by mxschmitt** [comment]
Each Playwright version is related to a fixed Chromium/Firefox/WebKit version. In case of 1.34.3 Firefox [was version 113](https://github.com/microsoft/playwright/releases/tag/v1.34.3). The way we compile Firefox might confuse you, since it looks like Nightly, but in reality the code its executing is stable.

Does this make sense?

**Comment by rnicholus** [comment]
Thank you for the quick reply. This is indeed quite confusing, especially since the downloaded binary is named `Nightly.app` and while open it indicates that it is a Nightly build in multiple places in the UI. But it is indeed a stable version 😕.

I'll close this, thanks again.
