### ISSUE TITLE
[BUG] 'Retries' is not considered if test is started from VS Code extension or UI mode

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#23407]
### System info
- Playwright Version: [v1.34.3]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
      retries: 1,
    },
});
```

**Steps**
- Install playwright
- Add 'retries: 1' for a project in the config file
- Make intentionally one of the example test to fail
- Run the test from VS code extention or UI mode

**Expected**

Because test is failing I would expect to be retried one more time as set in the config file.

**Actual**

Test is failing and retry is not triggered.

If I run the test via terminal 'npx playwright test' then the retry is triggered.

Maybe this is done intentionally, to work only from terminal, but I want to add a retry on my login dependency, so even if I run tests locally from VS Code extention or UI mode to be able to retry that login when it is failing for some reason.

**Comment by mxschmitt** [comment]
Exactly, this is done intentionally, because we expect that retries is not something people need to rely on locally. If they experience a failing test locally we instead want them to fix it. In VSCode or UI Mode it would be weird to retry, since we only have one test result to surface on.

Why is your login sometimes failing? Instead of relying on test-runner retries, you could add it inside the test, and wrap it e.g. with toPass: https://playwright.dev/docs/test-assertions#expecttopass

Would that work for you?

**Comment by NikkTod** [comment]
Sometimes because I am working from virtual machine, which does not have sufficient resources the browser crashes or I receive some status access violation, but you are right I would need to fix this by requesting more ram and cpu power or maybe with toPass. 

I get your point, we can close the ticket, thanks @mxschmitt
