### ISSUE TITLE
Ability to merge video recording from two browser/page context

### ISSUE THREAD

**Issue by rohit-walia** [microsoft/playwright#23522]
I have a test where at some point it clicks on a link which opens a new tab. This ends up producing two video recordings because there are two page contexts in play here: the main page and the new tab that opens.

It would be nice to have a flag or parameter added to WaitForPopupOptions object that doesn't split the video recording. Archiving/sharing 1 single video file per test is more ideal vs per page context.

Peusdo code for example:
```
    newTabPage = mainPage.waitForPopup(new Page.WaitForPopupOptions().setPredicate(p -> {
      // wait for page
      return true;
    }), () -> mainPage.locator("id=idSelector").click());
```

**Comment by dgozman** [comment]
See also #13380, #3916 and #7459.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
