### ISSUE TITLE
[Question]: Wait for Splashscreens

### ISSUE THREAD

**Issue by greuelpirat** [microsoft/playwright#23543]
### Your question

After a login we have a splashscreen which triggers a new navigation. Currently we use `Frame.WaitForNavigationAsync` for splashscreen, but this is deprecated.

What is the proper way to await the second navigation since this is not triggered by an user action? 

Because the redirect URL after the login can be anything we can not use `Frame.WaitForUrlAsync`

**Comment by aslushnikov** [comment]
@greuelpirat the best way is to find some a set of locators that exist after the second navigation. You can use the new
[`locator.or()`](https://playwright.dev/docs/next/api/class-locator#locator-or) method to await for some of the locators to appear:

```ts
const newEmail = page.getByRole('button', { name: 'New' });
const dialog = page.getByText('Confirm security settings');
await expect(newEmail.or(dialog)).toBeVisible();
```

This would be the only way to reach a certain state reliably. 

Note that you can still use the `waitForNavigation` - it's not going anywhere. We suggest against using it since it's notoriously hard to use correctly; however, if it works for you, there's no need to migrate off it. 

Hope this helps!
