### ISSUE TITLE
[Feature] With soft assert don't call afterAll, beforeAll after each failed soft assert test

### ISSUE THREAD

**Issue by apis3445** [microsoft/playwright#23586]
I was checking this bug https://github.com/microsoft/playwright/issues/8472 Playwright test.beforeAll hook executes more than once in a test suite if any test fails/throw error

With soft assert we can continue executing the tests, but beforeAll, and afterAll is executed as beforeEach and afterEach. 

Would it be possible that with soft assert the afterAll and BeforeAll would not be executed in each test?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
