### ISSUE TITLE
[Feature] Integrate Safe Area for iOS Devices

### ISSUE THREAD

**Issue by AmitMY** [microsoft/playwright#23611]
In iOS, the browser (and PWAs) have a safe area, set in the environment as `safe-area-inset-*` properties.

For example, for the iPhone 13, the areas are:
- Safe Area Insets (portrait): top: 47, bottom: 34, left: 0, right: 0
- Safe Area Insets (landscape): top: 0, bottom: 21, left: 47, right: 47

(See [here](https://useyourloaf.com/blog/iphone-13-screen-sizes/) for more devices)

Currently, you provide [device descriptors](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/deviceDescriptorsSource.json):
```
type DeviceDescriptor = {
  viewport: ViewportSize;
  userAgent: string;
  deviceScaleFactor: number;
  isMobile: boolean;
  hasTouch: boolean;
  defaultBrowserType: 'chromium' | 'firefox' | 'webkit';
};
```

Where I think these safe areas should also be written, as well as the native resolution and scaling factor.
Then, when creating a `newContext`, it should apply these environment variables.

This is very important for visual testing - to make sure everything does fit in the available viewport, and if the offsets are handled correctly on every page of the website, etc.

**Comment by AmitMY** [comment]
All of the values are available in https://github.com/sign/apple-device-information

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
