### ISSUE TITLE
[Feature] Add option to specify an amount of steps to the mouse wheel event

### ISSUE THREAD

**Issue by ghost** [microsoft/playwright#23628]
Just like how we can currently specify an arbitrary amount of intermediary `mousemove` events that get sent when calling `page.mouse.move()`, it would be interesting to have something similar on `page.mouse.wheel()`, example below:

```javascript
await page.mouse.wheel(deltaX, deltaY, { steps: 10 })
```

This would help creating a more natural navigation flow that better reflect the behavior of a real user, and consequently, making some parts of web applications react more appropriately, for instance, elements that transition into visibility once inside the viewport

The total delta value for both axes could be divided by the amount of steps to get the delta of each step, those can be constant, as i believe reproducing human-like behavior would be out of scope of the project and it's up to the implemented by the project making use of playwright

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
