### ISSUE TITLE
[Feature] Set "DEBUG=pw:api" functionality on test retry

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#23620]
The verbose logging normally is too noisey to have always enabled in CI/CD, but on retry it would be super useful.

Playwright trace is fine majority of times but when we have very unexpected behavior like the product crashing or infra not working correctly and the trace isn't saving. It would be really beneficial to have a fallback verbose logging.

Can we have an option to enable this on test-retry in the runner?

**Comment by aslushnikov** [comment]
@mastrzyz You can hack it in like this:

```ts
import { test, expect } from "@playwright/test";
import { debug } from 'playwright-core/lib/utilsBundle';

test.beforeEach(({}, testInfo) => {
  if (testInfo.retry > 0)
    debug.enable('pw:api')
});

test('Error', async ({ page }, testInfo) => {
  await page.goto('https://example.com');
  expect(testInfo.retry).toBe(1);
});
```

**Comment by mastrzyz** [comment]
Thanks, that could be used in the short term but would it be possible to push some sort of functionality like this in Playwright?


Even the `debug` object if it could be part of the regular `@playwright/test` package?

**Comment by Smrtnyk** [comment]
would it be possible to store the pw debug output to a file, in the test results along with other artifacts?
to not clutter console output in CI if there are many tests retrying

**Comment by dgozman** [comment]
@mastrzyz I've added `tracesDir` option to `electron.launch()`. Once v1.36 is out, you can do the following:
1. Specify a unique `tracesDir` directory for each launch. In Playwright test runner, we would use `TestInfo.outputDir` which is under `test-results`.
2. When you call `tracing.stop()` and it fails because electron has already crashed (or for any other reason), just zip that folder instead. Trace viewer should be able to open such a zip and show the trace.
3. Let me know whether that worked for you.

**Comment by dgozman** [comment]
@Smrtnyk

> would it be possible to store the pw debug output to a file, in the test results along with other artifacts?

This is possible from the command line, but there is no specific support in the test runner. Logs from all tests will be mixed up.
```
DEBUG=pw:api DEBUG_FILE=log.txt npx playwright test
```

**Comment by aslushnikov** [comment]
Closing as per above. Please let us know if it works for you!
