### ISSUE TITLE
[BUG] Playwright can't recognize [contenteditable] element inside a <button>

### ISSUE THREAD

**Issue by Dinh246** [microsoft/playwright#23652]
### System info
- Playwright Version: [v1.34.3]
- Operating System: Window 11
- Browser: All
- Other info:

I've met this error when fill to contenteditable element inside a button:
    
![image](https://github.com/microsoft/playwright/assets/71114633/d2042f4c-6471-4b4f-9f7b-0d8c709b8931)

We even test with this site and codegen: 
https://play.vuejs.org/#eNq1kLFuwzAMRH/lqsXtUAtdCyVAt3YP0EWLEjO2AVkiZDpoYPjfS8dp/yAABx3vkSdwNh/M9WUi827ceCo9C0aSifc+9QPnIphR6IwF55IHVIpWPvl0ymkUDGOL3eo/V58UY8Z3LrF5ql58cnZbp4tUCA0cg5AqwHVv+3m+DS+Ls6pu3T7xJLi8DrmhuPNGfW8261hg769JJCfIlUmRTd0pdRn6LyGtppdwjCsjZSIlDl0/QiuAQwltCdzV+JK19QfXOJQrJOPUhdQSZB0R+pHa2fUgGmC3xE08Ns3Z/6OZ5ReROJF6
**Steps**
- Record edit contenteditable element inside a button.
- Record edit normal contenteditable element

**Expected**

Should record both fill actions in spec file

**Actual**

Only record the fill action with the last contenteditable element

DOM: 
![image](https://github.com/microsoft/playwright/assets/71114633/bd881fd7-b521-4f86-b7d9-07620fccb804)

### Source code

```async editTabsAccordionTitle(block: Locator, tab: number, title: string): Promise<void> {
const inputField = this.frameLocator.locator("[contenteditable]");
    await block
      .getByRole("button")
      .or(this.page.locator("[class*=accordion__item]"))
      .nth(tab - 1)
      .dblclick();
    await inputField.waitFor();
    await this.page.keyboard.press("Control+A");
    if (typeof title !== undefined) {
      await inputField.fill(title);
    }
    await this.titleBar.click();
    await this.quickSettingsText.waitFor({ state: "hidden" });
    }

**Comment by aslushnikov** [comment]
Thank you, I can repro with the following snippet: 

```ts
import { chromium } from '@playwright/test';

const browser = await chromium.launch();

const page = await browser.newPage();
await page.setContent(`
  <button>
    <div contenteditable="true">foo</div>
  </button>
`);
await page.fill('[contenteditable]', 'bar');
await browser.close();
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
