### ISSUE TITLE
[Question]: How do I get information about a request sent through the request API

### ISSUE THREAD

**Issue by gcil125** [microsoft/playwright#23782]
### Your question

The request I sent through the APIRequestContext cannot be retrieved using the `on("request", f)` method
```python
from playwright.sync_api import sync_playwright


// At this point, on is working normally
page = sync_playwright().start().chromium.launch().new_page()
page.on("request", lambda request: print(request))
page.goto("http://example.com/")
```

```python
from playwright.sync_api import sync_playwright

// At this time, on is not giving me the results I want to print in the console
page = sync_playwright().start().request.new_context(base_url="http://example.com/")
page.on("request", lambda request: print(request))
page.get("/")
```

How do I listen for requests sent by invoking the APIRequestContext API

**Comment by yury-s** [comment]
> I used the APIRequestContext API to test the interface, but the APIResponse object I got has no record of the request. I don't know what my request is carrying.

The request is carrying whatever you pass as arguments to the corresponding [`fetch`](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-fetch) method (or its more specific counterparts `get`, `put` etc). The response you get corresponds 1-1 to the APIRequestContext call, so there is no ambiguity.  Since you have full control over the request there is no API for getting the request object from APIResponse. You can record trace or run with `DEBUG=pw:api` to get some logs regarding the network interaction.
