### ISSUE TITLE
[BUG] `route.fulfill` discards request headers overrides from previous `route.fallback` calls

### ISSUE THREAD

**Issue by olivierbeaulieu** [microsoft/playwright#23793]
### System info
- Playwright Version: v1.35
- Operating System: All
- Browser: All
- Other info:

### Source code

I used the test suite at `tests/library/har.spec.ts` to reproduce the issue, so you can run it with `npm run ctest -- --grep "should record request overrides on fulfill"`. Here is the failing test:

```js
it('should record request overrides on fulfill', async ({ contextFactory, server }, testInfo) => {
  const { page, getLog } = await pageWithHar(contextFactory, testInfo);

  await page.route('**/foo', async route => {
    await route.fulfill({
      status: 200,
      json: {
        fulfilled: true
      },
    });
  });

  await page.route('**/foo', route => {
    void route.fallback({
      headers: {
        'fallback-request-header': '1'
      },
    });
  });

  await page.goto(server.PREFIX + '/foo');
  const log = await getLog();

  const request = log.entries[0].request;
  expect(request.headers).toContainEqual({ name: 'fallback-request-header', value: '1' });
});
```

**Steps**
- `npm run ctest -- --grep "should record request overrides on fulfill"`

**Expected**

- `'fallback-request-header': '1'` should be part of the request headers

**Actual**

- All request headers overrides are discarded

**Comment by dgozman** [comment]
@olivierbeaulieu Just to double-check that I understand this issue correctly: this is only observed in the recorder har, because no actual network request to the server is made. Is that the problem you are facing?

**Comment by olivierbeaulieu** [comment]
The response provided through `fulfill` actually gets added to the HAR (even though no request is actually made), however the headers added through `fallback` are missing from the same request in the HAR.

**Comment by dgozman** [comment]
Investigation notes:

When request interception is not engaged, HAR content is straightforward: all network information as seen by the page and by the server, since they are exactly the same without any modifications in the middle. However, intercepting requests changes the network seen by the page compared to what's seen by the server. Below, assume request interception is enabled.

Currently there are four uses for the HAR in Playwright, and each requires different HAR content:
- Serving snapshots in the trace viewer. Ideally, the HAR would contain network as seen by the page - without request overrides, with fulfilled responses.
- Tracing network panel. Ideally, the HAR would contain all network details - original request, request overrides, fulfilled responses, aborted requests, etc.
- `routeFromHAR` method. Ideally, the HAR would contain network as seen in the middle of the interception chain. For example, if there was a request override that executes before `routeFromHAR` - it would end up in the HAR, but if there was a fulfill/override that executes after `routeFromHAR` - it would not end up in the HAR. This is somewhat tricky to implement with the current architecture. Code example:
   ```ts
   await page.route('**/api/foo', route => route.fulfill({ body: 'foo content' }));  // should not be in the HAR
   await page.routeFromHAR('har.zip', { url: '**/api/**' });
   await page.route('**/*', route => route.fallback({ headers: { ...request.headers(), 'x-foo': 'bar' } }));  // should be in the HAR
   ```
- `recordHar` option. There is no single answer as to what information should end up in the HAR in this case. Each use of `recordHar` has different purposes.

As of today, HAR contains fulfilled responses without request overrides, or real network responses with request overrides. 

Conclusion: HAR with request interception is ambiguous, and there is no right answer. Status quo is somewhere in the middle, not exactly matching any HAR scenarios. Changing HAR implementation would certainly break some usecases.

**Comment by florea-g** [comment]
Hello i have the same issue wit the headers but i'm not using routeFromHar
With this code i get the header: 
```
await route.fulfill(
        {
          status: 200,
          headers: {
            "Content-Type": "application/custom"
          },
          body: bodyText
        })
```
but this one i get null for header:
```
await route.fulfill(
        {
          status: 200,
          headers: {
            "My-Header": "customHeader"
          },
          body: bodyText
        })
```

**Comment by florea-g** [comment]
I have found the solution if can help someone 
When i lunch with embeded browser i can't set headers but if i lunch with a custom browser (in my case chrome)
which is instald on my computer i can set my custom headers

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
