### ISSUE TITLE
In parallel run logs are not printing sequentially as per testcase 

### ISSUE THREAD

**Issue by rphacker1618** [microsoft/playwright#23804]
Hello Team,
We have an implementation of log4js for logging in our playwright framework. But we are facing some issue while printing the logs. For single test-case run logs are printing properly, but when we try to run test-case in parallel then logs are not printed sequentially as per test-case run 

Please help me in finding solution for implementing below mentioned expected behaviour.

**Troubleshooting** :There is similar bug https://github.com/microsoft/playwright/issues?q=3109 , I tried implementing the solution mentioned here but it is not working for me.

For example:
**Actual** :
PID1 Message1
PID2 Message1
PID2 Message2
PID1 Message2
PID1 Message3
PID2 Message3
PID1 Message4
PID2 Message4

**Expected**:
PID1 Message1
PID1 Message2
PID1 Message3
PID1 Message4
Test-case 1 complete here and then test-case 2 printing start
PID2 Message1
PID2 Message2
PID2 Message3
PID2 Message4

### System info
- Playwright Version: 1.31.2
- Operating System: Windows
- Browser: Chrome/Chromium
- Log4js Version: 6.7.1

**Comment by dgozman** [comment]
@rphacker1618 This is the expected behavior of the default terminal reporter - to print output as soon as it is produced.

You can use [the `html` reporter](https://playwright.dev/docs/test-reporters#html-reporter) that will show output for each test at the end, as an attachment.

Alternatively you can implement [a custom reporter](https://playwright.dev/docs/test-reporters#custom-reporters) that would handle [`onStdOut()`](https://playwright.dev/docs/api/class-reporter#reporter-on-std-out) to your liking.
