### ISSUE TITLE
[BUG] New fixture steps are displayed outside of the Before Hooks section

### ISSUE THREAD

**Issue by juniorerico** [microsoft/playwright#23835]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [macOS 13.0]
- Browser: [Chromium]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

I put the reproducible code in a gist - https://gist.github.com/juniorerico/181e82e4ee79e0e06eaf6b8656300462

**Steps**
- Run the test
- Open the HTML Report

**Expected**

All fixture steps should be inside the Before Hooks section.

**Actual**

After running the test, the fixture step is displayed as a normal ste, outside the **Before Hooks** section.

It would be good also if there was a way to hide the fixture steps at all. My real project uses a lot of fixtures and it is not relevant to have them as step in the report, even inside the Before Hooks section. In the previous playright version we were logging the ones we care using the `test.step` function and it was working as expected for us. I noticed that in the code there is a `hideStep` logic, but it is not able to implement on our fixtures.

<img width="1030" alt="image" src="https://github.com/microsoft/playwright/assets/2073848/13c0a811-7e76-41cb-a9b3-748f3de27d3b">

**Comment by dgozman** [comment]
Investigation notes:

- (bug) "testFixture teardown step" gets "testFixture setup step" as a parent, because that's last on the stack.
- (not a bug) dispatcher cannot find "textFixture setup step" among ongoing steps, because setup has already finished, so assigns "top-level" as a parent.

**Comment by mstepin** [comment]
This is a problem for us too. Have had to revert back to version 1.32 (not idea) to circumvent this excessive noise in our reports. Please fix asap.

**Comment by mstepin** [comment]
Any further discussion on this one. It is the one issue that is blocking us from upgrading to a higher version and getting a whole pile of other nice new features.

**Comment by dgozman** [comment]
@juniorerico @mstepin Could you please share your use case? Sometimes wee see that using text fixtures in `beforeAll` is not the best solution, so it would be really helpful to know some use cases.

**Comment by mstepin** [comment]
@dgozman
We have a lot of tests that setup up data and entities for a scenario such that it can start in a given state. It does so using APIs which have a lot less overhead. These steps happen in our fixtures and we are not interested in their outcome for every single test scenario (if they failed, we'd have much bigger problems than a failing e2e scenario).

Here's a screenshot of the output report of one of smaller tests in Playwright v1.32:
![version_1_32](https://github.com/microsoft/playwright/assets/22974324/7551b9bf-6a34-4fa4-ad0d-1d11e4a1ddb1)

The API calls, and other setup actions, were neatly tucked away, inconsequentially, within the "Before Hooks" parent.

Now here is a screenshot of the report output for the exact same test in Playwright v1.35:
![version_1_35](https://github.com/microsoft/playwright/assets/22974324/8f9fab29-547e-4cde-9e80-665b911b7f49)

Notice now how all things that happen in fixtures live outside of the "before Hooks" parent. The above is a small test. We have tests that require 5 to 10 different fixtures and each fixture can have multiple API calls and so total to more than 30 API calls. This means we have to spend time just hunting for where the fixtures end and the actual test starts in the report.

The best outcome we could possibly even have in v1.35 is that we wrap the entire fixture code for each fixture in a step wrapper, however that still leaves us with at least 1 report entry per fixture, which is still far from ideal.

Why was this change made? or was it unintentional? if the latter shouldn't it be fixed asap given it is broken existing functionality (ie a regression)?

**Comment by dgozman** [comment]
@mstepin This makes sense, thank you.

> Notice now how all things that happen in fixtures live outside of the "before Hooks" parent

The intentional change was reporting the fixtures inside "Before Hooks". The fact that fixtures are shown outside of it is a bug. 

However, I suspect that these fixtures you see were not used in the `beforeAll` hook, but rather in a test? If so, could you please share a repro that produces such a report? If it was indeed a fixture from a `beforeAll` hook, we would be really interested in your use case to understand why do you use test fixtures in a hook, which is a very unusual scenario.

**Comment by mstepin** [comment]
@dgozman unfortunately due to the nature of the domain we work in, I cant share any repos.

The fixtures we have all get used in the test itself, and for the most we are intentionally moving away from `beforeAll` in favour of fixtures. Most fixtures are worker scoped fixtures but there are some (especially those relating to session, context, login etc) that are test scoped fixtures. 

however I have looked a bit deeper into the issue and it seems that the items that get published in the report outside of the "before hooks" section, are asynchronously run code. As mentioned these previously still got published inside the before hooks section.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
