### ISSUE TITLE
[BUG] Missing `received` value in error message for `not` assertion

### ISSUE THREAD

**Issue by Materix** [microsoft/playwright#23897]
### System info
- Playwright Version: 1.35.1

### Source code

```js
    test('expect 1 not to be 1 missing received', async ({ page }) => {
      expect(1).not.toBe(1);
    });

    test('expect 1 to be 2 show received', async ({ page }) => {
      expect(1).toBe(2);
    });
```

**Expected**
To show received value in error message

**Actual**

There is no received value in error message for `not` assertion

![image](https://github.com/microsoft/playwright/assets/6151485/98903d6b-0d3d-4dca-87fe-4eaf32a8303b)
![image](https://github.com/microsoft/playwright/assets/6151485/78879db4-2244-4d6e-8661-94bbd6403d14)

**Comment by mxschmitt** [comment]
I can reproduce via `npx playwright test` on ToT.

**Comment by mxschmitt** [comment]
I was able to reproduce this with normal plain expect, I recommend filing upstream [here](https://github.com/jestjs/jest/issues) since we rely on Expect from Jest and extend it with Playwright as assertions.

```js
const expect = require('expect');

try {
  expect.default(1).not.toBe(1);
} catch (e) {
  console.log(e.message)
}
```

Expected: Contains actual value
Actual: Does not contain actual value

**Comment by dev-jonghoonpark** [comment]
Hi. @Materix

I left a comment on the issue(https://github.com/jestjs/jest/issues/14430) by @mxschmitt

> I'm not sure if this is absolutely necessary.
>
> If expect(SOMETHING).not.toBe(A) fails,
> it suggests that SOMETHING must be A since there is no other possibility.
> Therefore, I think not including the output for Received is intentional.
>
> By the way, I found that it is possible to modify the matches.ts file to include output for Received.

What are your thoughts on this opinion?"

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
