### ISSUE TITLE
[Bug] UI Mode via browser does not run worker teardown on CTRL + C

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#23907]
See https://github.com/microsoft/playwright/pull/23876#discussion_r1242443903.

**Comment by marcin-bojar** [comment]
Hi @mxschmitt, thanks for creating this issue.

I just realised that I have 247 users left in AWS Cognito due to not running global teardown when closing UI mode (chromium, macOS Ventura). But for me global teardown is also not run when closing the UI mode via context menu (Chromium --> Quit Chromium). 

I'm using `global-setup` file, which returns teardown function. How do I close UI mode, so the global teardown is run? I can't see any way to do that at the moment. Thanks in advance!
