### ISSUE TITLE
connectOverCDP ask to download browser

### ISSUE THREAD

**Issue by tepmehatop** [microsoft/playwright#23920]
Hello!

I use connectOverCDP to connect to an external browser like selenoid.
All connection setup of connectOverCDP happens through fixtures.
```
browser: async ({ }, use) => {
        const sessionID = await createBrowser();
        const browser = await chromium.connectOverCDP(
            'ws://bla bla bla' + sessionID + '/'
        );
        await use(browser);
        await deleteBrowser(sessionID);
    },
```

But the problem is I run the tests on a clean machine / docker, they still ask to download the browser. How to avoid it?
For example, a clean machine where I install a playright without a browser:

`PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npm i @playwright/test@1.34.3 --with-deps`

Then I do installation of other dependences.
`npm install`

And I run the entire scope of tests.
`npx playwright test`

Then i get error:
`
Looks like Playwright Test or Playwright was just installed or updated. 
Please run the following command to download new browsers:
`

**Comment by mxschmitt** [comment]
Most likely you are still referencing a `page` or `context` instance somewhere in your code which does not use the overridden browser instance. Or launching a browser manually. Without seeing your other tests / source code its hard to find the cause from our side. Can you provide us more of your source code?

Unrelated to that, you don't have to do `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npm i @playwright/test@1.34.3 --with-deps`, since `@playwright/test` does not install any browsers by default. Only the `playwright` package does it (some of your dependencies might install it). You are also specifying the `--with-deps` argument to the `npm install` command, while it only works if you specify it to the Playwright CLI (`npx playwright install --with-deps`).

Keep also in mind that overriding the browser fixture and connecting to your own CDP endpoints might have other side effects, like not working tracing, screenshot, video etc. on-failure etc. This isn't something we support. We support only [connectOptions](https://playwright.dev/docs/api/class-testoptions#test-options-connect-options) which works with a [Playwright server](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server).

**Comment by tepmehatop** [comment]
> Most likely you are still referencing a `page` or `context` instance somewhere in your code which does not use the overridden browser instance........

@mxschmitt thank you very much! Indeed, sometimes you don’t notice simple things, the problem was that the browser was created separately in global-setup.ts to receive an Authorization Token before starting and saving it for the entire session.
🤝
About connectOptions I know and have previously used it with Moon on another project. connectOverCDP is a temporary option until Moon is purchased.

The main option I use is a regular docker image from Playwright, but it's not so easy to build it yourself when dependencies and browsers can only be taken from the internal Artifactory repository.

Thanks again for your help.
