### ISSUE TITLE
[Feature] Emulate Lockdown Mode

### ISSUE THREAD

**Issue by chrisguttandin** [microsoft/playwright#23990]
Apple devices support something called a ["Lockdown Mode](https://support.apple.com/en-us/HT212650)". It also affects Safari.

> Certain complex web technologies are blocked, which might cause some websites to load more slowly or not operate correctly. In addition, web fonts might not be displayed, and images might be replaced with a missing image icon. 

I think it would be nice to emulate this mode when testing a page to be sure it doesn't break in unexpected ways.

There is a section in Safari's v16.4 release notes which lists [new restrictions in Lockdown Mode](https://webkit.org/blog/13966/webkit-features-in-safari-16-4/#new-restrictions-in-lockdown-mode). As of [v16.5](https://webkit.org/blog/14154/webkit-features-in-safari-16-5/) WebCodecs was added to the list.

**Comment by pavelfeldman** [comment]
I'll mark it as p3 to collect the feedback, but I'd like to set the expectations right away that it is unlikely to gain enough priority to be addressed.

**Comment by chrisguttandin** [comment]
Thanks for letting me know. At least one can hope. :-)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by alxndrsn** [comment]
> If you disagree with this closure, please open a new issue and reference this one.

Done - new issue at https://github.com/microsoft/playwright/issues/38094

@chrisguttandin @marko-simic @haywirez please like & subscribe if you're still interested.
