### ISSUE TITLE
[BUG] HTTP headers in HAR files are sorted instead of the original order from the response

### ISSUE THREAD

**Issue by adulau** [microsoft/playwright#24025]
### System info
- Playwright Version: 1.35.0
- Operating System: All
- Browser: chromium 115.0.5790.24
- Other info:

### Source code

- [ X] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/ail-project/lacus](https://github.com/ail-project/lacus)

**Steps**

- All capture that we are running with Playwright
- Check the HAR JSON response header in entries

**Expected**

The response headers should not be sorted by Playwright and should be the order given by the server response

**Actual**

The response headers are sorted by Playwright

**Comment by Rafiot** [comment]
Update on that: I played a bit with 1.36.0 and the HTTP headers are only sorted by name in the list of the HAR export when the browser used is chromium, not if it is Firefox or Webkit.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
