### ISSUE TITLE
[Feature] Automating browser based 'Screen Share' Capabilities

### ISSUE THREAD

**Issue by DeeptiSaxena09** [microsoft/playwright#24047]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Hi,

In my application, we have provided a functionality where user can 'Start Sharing' screen (Just like how gmeet has provided this functionality).

I do not want to use '--use-fake-ui-for-media-stream' and '--use-fake-device-for-media-stream' args at the time of browser launch but wants to automate the complete real time steps involved in this.

Is there any possibility to automate such case through playwright?

Many Thanks,
Deepti Saxena

**Comment by pavelfeldman** [comment]
There is no way to implement this w/o using fake media stream and performing browser-specific steps atm.

**Comment by DeeptiSaxena09** [comment]
@pavelfeldman Could you please share documentation where the browser-specific steps are mentioned which you are suggesting in your message.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
