### ISSUE TITLE
[Feature] Support for AWS Lambda / Serverless environments

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#2404]
A lot of users try to use Puppeteer and Playwright in special environments like on Vercel (formerly ZEIT) which is based on Amazon Linux 2 / Lamda or directly on AWS Lamda. Also there are quite a few interesting use cases for Google Cloud Functions / Azure Functions.

Would be good to investigate into them, if separate browser binaries can be provided for that or an official buildpack for Heroku.

Probably it does not make sense to support all the browsers there, only Chromium would be already a big win.

(also userspace is possible)

Ref:
- https://stackoverflow.com/questions/62062976/playwright-error-failed-to-launch-browser
- https://github.com/microsoft/playwright/issues/634
- https://github.com/microsoft/playwright/issues/1568
- https://github.com/microsoft/playwright/issues/1887
- #626

For AWS Lambda / Google Cloud / Vercel functions this works currently: https://github.com/alixaxel/chrome-aws-lambda#usage-with-playwright

**Comment by zedd3v** [comment]
+1

**Comment by osmenia** [comment]
any news?

**Comment by mxschmitt** [comment]
Closed, since for AWS Lambda based systems [this](https://github.com/JupiterOne/playwright-aws-lambda) can be used and for Heroku [this](https://github.com/mxschmitt/heroku-playwright-buildpack) buildpack should now work too.

**Comment by jan-osch** [comment]
Hi @mxschmitt -first of all, **thanks for the awesome library**! 😄 

The current support for AWS Lambda is partial (only chromium works). As far as I know, porting Firefox and Webkit to Lambda would require static compiling all the missing libraries + applying the playwright patches. 

Since the playwright team is already preparing other browser images, could you also prepare Lambda compatible binaries for Webkit and FF? That would be enormously helpful. Even some suggestions on how to tackle this problem would be great. The     `playwright-aws-lambda` project does not seem very active.

**Comment by mxschmitt** [comment]
@jan-osch I full agree. I reopened it to keep track on solutions to run Firefox and WebKit in serverless functions. Having this out of the box would be great.

**Comment by CyberV** [comment]
> Closed, since for AWS Lambda based systems [this](https://github.com/JupiterOne/playwright-aws-lambda) can be used and for Heroku https://github.com/mxschmitt/heroku-playwright-buildpack buildpack should now work too.

What about Azure support? I'm currently running into the same 'failed to launch browser' error while trying to launch browser from an Azure App Service. Same for an Azure Function with dockerized container.

**Comment by mxschmitt** [comment]
@CyberV for Azure Functions, you can follow this example by @arjun27: https://github.com/arjun27/playwright-azure-functions

**Comment by arjun27** [comment]
@CyberV, thanks for the comment. This is the current state of running Playwright on Azure Functions:

* Azure Functions Linux: Chromium can run on the Linux consumption (basic) plan, without any additional dependencies. Firefox and WebKit require the Linux premium plan, with a custom docker setup. @mxschmitt has shared an example above.
* Azure Functions Windows: running headless browsers is not supported, due to missing Windows libs.

Are you running on Windows?

**Comment by paya-cz** [comment]
The [playwright-aws-lambda](https://github.com/JupiterOne/playwright-aws-lambda) package mentioned earlier as a solution for AWS Lambda users seems to be abandoned. Last release 8 months ago. Bundled Chromium was last updated 11 months ago.

It would be great to have officially supported playwright package for AWS Lambda and updated with the same cadence as other playwright packages.

**Comment by mxschmitt** [comment]
The original project has now also added some documentation to its project how to use Playwright with it. This project has quite recent builds: https://github.com/alixaxel/chrome-aws-lambda#usage-with-playwright

**Comment by ycjcl868** [comment]
+1

**Comment by pavelfeldman** [comment]
This is not something Playwright team is actively looking at, so closing it to manage the expectations.

**Comment by mdw123** [comment]
FWIW, chrome-aws-lambda now appears to be abandoned.

**Comment by b5414** [comment]
@mdw123 not abandoned one: 

- https://github.com/Sparticuz/chrome-aws-lambda
