### ISSUE TITLE
[Feature] External cancellation of `...WaitFor...` methods where feasible

### ISSUE THREAD

**Issue by maw136** [microsoft/playwright#24083]
Add external cancellation of `...WaitFor...` methods where feasible.

Reasoning:
Wait for style methods have a timeout, but there are circumstances where external events could be the cause to cancel specific waits.
The current solution doesn't provide any cancellation except default/custom timouts.

**Comment by mxschmitt** [comment]
We discussed this feature in our team and came to the conclusion that this change might confuse users. While event handlers, aka. WaitFor* methods can be cancelled, the code you have inside, can not. Often these are clicks, evaluates, etc. To keep a clear boundary about this, we decided to not go forward with this API proposal.

I apologise for being slow on this PRs/issues, since some of our coworkers were out of office. Thank you!

**Comment by maw136** [comment]
But it's all about cancelling the wait/listen for event, not the action. There is no way for early cancel of any `WaitFor...` waiter

**Comment by mxschmitt** [comment]
The code inside the callback still continues to run and does not follow .NET's rule of periodically checking if the [cancellation was requested](https://learn.microsoft.com/en-us/dotnet/standard/threading/how-to-listen-for-cancellation-requests-by-polling). This is a fundamental feature which Playwright does not offer and yield in unexpected behaviour.

We recommend Task.WhenAny() instead.

**Comment by maw136** [comment]
So more spaghetti code instead. :( 
In all meaningful scenarios the 'callback' as you called it is an action that triggers the request/response dialog with backend.
A cancellation would not cause any unexpected behaviour/side effects, as the action have already run to completion either way.
