### ISSUE TITLE
[Feature]Playwright Documentation - Certification's/ Accreditations  

### ISSUE THREAD

**Issue by ramam-v** [microsoft/playwright#24092]
Hi , 
I work for a company in HealthCare industry. My company is currently validating playwright. Can you please confirm Playwright being a Microsoft Open Source project do the Microsoft Certification's/ Accreditations  such as  e.g., ISO 9001, ISO 27001, SOC2  apply for Playwright Open Source project as well?
This information will be helpful for other validated industries  - Health Care, Pharma and Banking/Finance

Regards,
Bhaskar

**Comment by pavelfeldman** [comment]
ISO 9001, ISO 27001, and SOC2 are standards and certifications that apply to the organizations and their processes rather than to individual projects or software. While they apply to the management systems, procedures, and infrastructure that we use, they don't necessarily span to the individual software products.

Playwright is an open source project, and as such, its source code is freely available for review and contribution. If an organization wants to use Playwright, or any other software and is concerned about ISO 9001, ISO 27001, or SOC2 compliance, the organization would need to consider how it uses that software within its own processes that are subject to these standards.

**Comment by ramam-v** [comment]
Thanks for the reply. I will pass this on to our validation team.

**Comment by mxschmitt** [comment]
Closing as per above.
