### ISSUE TITLE
[Feature] Playwrights Estimated End-of-Support Timeline for Node Versions

### ISSUE THREAD

**Issue by hawenger** [microsoft/playwright#24103]
Our team needed to update Node as our version reached end-of-life. While evaluating the effects of various node versions on our dependencies, one of our engineers posed a great question, 

> _"Does Playwright plan to support all Node versions until the version's end-of-life?"_

Playwright's documentation on _System Requirements_ was helpful for understanding present minimum Node Version requirements. The information in future focused documentation like an _Estimated End-of-Support Plan_ for Node could present teams with the opportunity to perform valuable analysis _(cost/benefit analysis, evaluate effort, etc)_ and could be especially effective when combined with a team's operational & ecosystem data, ultimately reducing technical debt.

While this type of analysis is valuable to many, I think it especially beneficial to teams that:
- work with legacy systems
- implement a mono-repo
- are small or resource strapped
- are part of a large organization
- work in highly dependent/dependency-coupled environment(s)
- work with critical technology _(health, financial, government, infrastructure, logistics, etc)_

I can also understand that such a feature may not make sense for Playwright to implement in present moment. 
That being said, if the time isn't now or nigh, I think it could be of value in the future.

[Discord Question](https://discord.com/channels/807756831384403968/1126896644319871016)

**Comment by pavelfeldman** [comment]
We intend to support Node version until it is past its maintenance phase (https://nodejs.dev/en/about/releases/). Note that security considerations might trigger accelerated deprecation, for example see https://github.com/microsoft/azure-pipelines-agent/issues/4239. Playwright does not work in isolation, so if the major CI/CD providers like GitHub Actions choose to accelerate the deprecation due to security concerns, we are likely to align with their timelines.

**Comment by mxschmitt** [comment]
Closing as per above.
