### ISSUE TITLE
[BUG] type() method doesn't work properly with non-Latin characters (python library)

### ISSUE THREAD

**Issue by VieMichelle** [microsoft/playwright#24107]
Context:

playwright version: 1.33.0
Operating System: Linux
pytest-playwright: 0.3.3
Python version: 3.10
Browser: Chromium

When using the type() method with non-Latin characters (e.g. Greek) then I don't get the expected response
If I use Latin characters then type() works correctly

it is indeed stated in the documentation

NOTE
For characters that are not on a US keyboard, only an input event will be sent.

But the world is multilingual and is unacceptable to be restricted with the US language only
Furthermore the rest of the library works fine with other languages and most importantly the type() method in the typescript library supports non US languages 

Please fix this or provide a workaround

PS. The insert_text() method does not emit the keydown, keyup or keypress events which are necessary and can’t be used as a workaround

**Comment by chvetochek** [comment]
the same for method pressSequentially()

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
