### ISSUE TITLE
[BUG] Angular uploader cannot be opened manually in playwright webkit

### ISSUE THREAD

**Issue by romankhomitskyi** [microsoft/playwright#24156]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [MacOs Ventura 13.2.1]
- Browser: [WebKit]
- Other info:

I have run these commands

```
yarn playwright install-deps webkit
yarn playwright install
```

And open webkit browser using this command

`npx playwright-webkit wk`

So on the left playwright webkit on the right default safari browser

https://github.com/microsoft/playwright/assets/57874507/f5f28212-99dc-428b-9192-dbf4148cb9d9

**Expected**

I should be able to open uploader in playwright webkit

**Actual**

Can't use uploader

**Comment by mxschmitt** [comment]
Minimal repro: `npx playwright wk https://ps.uci.edu/~franklin/doc/file_upload.html`

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
