### ISSUE TITLE
[BUG] Test finished within timeout of 60000ms, but tearing down "context" ran out of time.

### ISSUE THREAD

**Issue by ElliottDevlinPA** [microsoft/playwright#24210]
### System info
- Playwright Version: v1.35
- Operating System: macOS 11.6.1
- Browser: Chromium

**Config file**

```
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  reporter: 'html',
  timeout: 60000,
  use: {
    baseURL: 'https://pressreleasehub-staging.pa.media/',
    trace: 'retain-on-failure',
    headless: false,
    browserName: 'chromium',
    viewport: { width: 1680, height: 1050 },
    video: 'retain-on-failure',
    screenshot: 'only-on-failure',
    actionTimeout: 30000,
    launchOptions: {
      slowMo: 300,
    },
  },
  workers: 4
});
```

**Test file (self-contained)**

```
import { test, expect } from '@playwright/test';

test.describe('Verify Press Release Hub Contributor Pages', () => {

  test.only('Verify Contributor Pages', async ({ page }) => {
    await page.goto('https://pressreleasehub-staging.pa.media/');

    // Open the Contributors menu
    await page.click('#navbar-contributors');

    // Get all menu links within the Contributors menu
    const allLinks = await page.locator('.NavigationBar_subMenuColumns__fN1Rt > li > a').all();

    // Assert 37 menu links are present
    expect(allLinks.length).toBe(37);

    for(let i = 0; i < allLinks.length; i++) {
      const contributorName = (await allLinks[i].innerText()).toLowerCase();
      await allLinks[i].click();

      const contributorHeading = page.locator('.SectionHeader_sectionHeader___3ygo ').getByRole('heading', {name: contributorName.toLowerCase()});
      await contributorHeading.waitFor();

      await page.goBack();
      await page.click('#navbar-contributors');
    }
  });
});
```

**Steps**
- Run the test

**Expected**

All stages of the test should complete successfully

**Actual**

The test itself does actually seem to pass, however, instead of completing successfully it hangs until the timeout value of 60 seconds is reached and then fails with the following error:

```
Test finished within timeout of 60000ms, but tearing down "context" ran out of time. Please allow more time for the test, since teardown is attributed towards the test timeout budget.
```

However, the test is completing well before that 60 second timeout.

**Comment by mxschmitt** [comment]
When I try to navigate to the URL from above I get "https://pressreleasehub-staging.pa.media/". Is this a temporary outage or is your site not public?

**Comment by ElliottDevlinPA** [comment]
Hi @mxschmitt, it was a temporary outage - the site goes offline outside of business hours (UK time). I forgot to mention that - apologies.

**Comment by mxschmitt** [comment]
My guess is the following. You have configured `trace: 'retain-on-failure',` which means we always record a trace, which in your scenario means for all the pages you visit, it will record DOM snapshots, network requests/responses etc. (takes time, CPU -> resources).

We instead recommend `trace: 'on-first-retry'` which for the first test run is fast, since no trace is recorded and for the second test run its slower, since we record with a test. This means you should configure `retries: 1` or `retries: 2`.

We save the trace when we teardown the context, thats why its saying `tearing down "context" ran out of time`.

See here for our best practise configuration, which gets created with [create-playwright](https://github.com/microsoft/create-playwright/blob/main/assets/playwright.config.ts#L30) or VSCode by default and [here](https://playwright.dev/docs/trace-viewer-intro#recording-a-trace) docs for the Trace Viewer.

**Comment by ElliottDevlinPA** [comment]
Thanks @mxschmitt  - I turned off trace completely and now the test runs as expected. Thanks for your help.
