### ISSUE TITLE
[Feature] Expose the stacks of test steps

### ISSUE THREAD

**Issue by hbenl** [microsoft/playwright#24283]
At [Replay](https://www.replay.io/) we want to improve our support for recordings of Playwright tests. In particular we'd like to be able to show a test step's stack and its locations in the test's source, similar to Playwright's trace viewer. To do that we need Playwright to send the test step's stack to our reporter.

**Comment by pavelfeldman** [comment]
Could you give us a better idea on how it is used? Maybe a stack of step locations is sufficient for you?

**Comment by hbenl** [comment]
Jason explained this in the Loom linked in https://github.com/microsoft/playwright/pull/24284#issuecomment-1640403860

**Comment by pavelfeldman** [comment]
It isn't clear from the video what the stack has to do with it.

**Comment by hbenl** [comment]
With Replay you can make a recording of a Playwright test running in the browser. Furthermore, we have a [Playwright reporter](https://www.npmjs.com/package/@replayio/playwright) that will add information about the test steps to the recording. `TestStep.location` lets us show you where in your sources Playwright was called. However, very often that location is not in the test itself but in a helper function called by the test. In that case, we can only show where the helper function called Playwright but not where the test called the helper function. To do that, we would need not just the location of the top frame (i.e. `TestStep.location`) but of the entire stack of user frames.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
