### ISSUE TITLE
New assertion API to wait for frameLocator to have URL -- expect(frameLocator).toHaveURL()

### ISSUE THREAD

**Issue by ajssd** [microsoft/playwright#24377]
Today we have `contentFrame.waitForURL()` but this does not work with Frame Locators.  Instead, we would like to see an API like `expect(frameLocator).toHaveURL()`.

See discussion here:
https://github.com/microsoft/playwright/issues/24316#issuecomment-1643602889

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
