### ISSUE TITLE
[Feature] export @playwright/test expect matchers 

### ISSUE THREAD

**Issue by vigneshshanmugam** [microsoft/playwright#24501]
+ `@playwright/test` has great set of assertions built in top of some of the built in asserts from `jest mactchers` which can be consumed from the library via `import {expect} from "@playwright/test"`. Examples are https://playwright.dev/docs/test-assertions#list-of-assertions

+ Would it be possible for exporting the `expect` matchers from Playwright test to be consumed by other test runners like `jest, @elastic/synthetics, etc..`. I am a maintainer on the later package and would be interested in swapping the jest expect matchers with the one from the PW test. 

+ Even if not a standalone package which might require structural change in the PW library itself, would it possible to add the `lib/matchers` to the export list on `playwright/test/package.json` ? https://github.com/microsoft/playwright/blob/d92fe16b76272afb19e7af5a2496f7efce45441d/packages/playwright-test/package.json#L11
```ts
exports: {
 "./lib/expect": "./lib/matchers/expect.js"
}
```

I am not sure if there are consequences in doing so, Since PW test relies on some of the functionalities associated with the PW-core. If this PW team thinks this approach is good enough, I am happy to do a PR.

**Comment by vigneshshanmugam** [comment]
I did end up sending a PR since exposing it did not break and I was able to use it in other projects seamlessly except for some matchers like `snapShot` match which might depend on file path but so far looks good. 

Would it be possible to get this on the next release? Thanks!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
