### ISSUE TITLE
Error: Requiring @playwright/test second time

### ISSUE THREAD

**Issue by v5zz** [microsoft/playwright#24564]
when click Run Test then show , Error: Requiring @playwright/test second time

**Comment by mxschmitt** [comment]
Can you share a reproduction in form of a small GitHub repository? Otherwise we are not able to act on it, thanks for your understanding.

**Comment by v5zz** [comment]
Hello @mxschmitt , I used the playwright of VS Code extension before, then by clicking the Run Task button,and  then have a Error: Requiring @playwright/test second time;but now i open the command panel and type: Install Playwright, then the Error has fixed。
Perhaps it is because the Name of your Tests folder configuration is different？

**Comment by v5zz** [comment]
@mxschmitt,hi,I have uploaded the demo,[github repository](https://github.com/v5zz/playwright-test)

**Comment by dgozman** [comment]
@v5zz You have multiple copies of `@playwright/test` in multiple `node_modules` directories - probably misconfigured monorepo? Playwright needs your config and tests to only ever use a single copy of it, otherwise it won't be able to communicate between test workers and main test runner process.

For example, `internal/playwright-config/src/index.js` imports its own copy of playwright, and then `example/e2e/playwright.config.js` imports both the internal file and a different copy of playwright. 

You need to configure your repro to only have a single copy of `@playwright/test` inside, or at least not to mix them in a single testing project. Let me know whether this helps.

**Comment by v5zz** [comment]
but, I plan to use in multiple repos ,so I want `internal/playwright-config` as a single  package,  I've created the above repo playwright-test acting as my auth package. e2e package dependencies `internal/playwright-config `

**Comment by dgozman** [comment]
@v5zz I'd recommend making your `internal` package not depend on playwright, for example make it a peer dependency.

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further questions.
