### ISSUE TITLE
How to make page bring to front

### ISSUE THREAD

**Issue by phileba** [microsoft/playwright#2603]
Do we have a method to make to browser page on top likes `page.bringToFront()` or something like that?

**Comment by yury-s** [comment]
Each page created in Playwright behaves as if it was focused active page so bringToFront would be noop. Can you share more details about the use case where you need such method?

**Comment by phileba** [comment]
I have the context it the browser opening more than one page, then I can get all pages by this method `page.context().pages()`, so if I want to bring to a front specific page of that list, how can I do?

**Comment by phileba** [comment]
@yury-s do you have any updates?

**Comment by yury-s** [comment]
In your snippet even if you had `page.bringToFront()` calling it would make no difference to the pages' because all of them are already active and focused. Note that it's not obvious in the headful mode because OS usually doesn't allow multiple focused windows but otherwise from what could be detected in the page's javascript the page is already 'top' page.

Does your page somehow depend on 'document.visibilityState' or how would it detect that it's brought to top? For the `visibilityState` there is an easy way to mock it in the client code which is described in https://github.com/microsoft/playwright/issues/1290, would that work for you?

**Comment by dgozman** [comment]
Playwright 1.3 now has [`page.bringToFront()`](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=pagebringtofront) method.

**Comment by tuanvhit** [comment]
Still fails on firefox
