### ISSUE TITLE
[BUG] [WebKit] WebSocket connections occasionally hang in WebKit when using an HTTP proxy

### ISSUE THREAD

**Issue by jbaldassari** [microsoft/playwright#26323]
Occasionally, WebSocket connections seem to hang when running Playwright tests on WebKit with an HTTP proxy configured.  I have not been able to reproduce this behavior _without_ Playwright.  Everything seems to work fine on Safari, Epiphany, and vanilla WebKit built from source.  However, when the same website is accessed in a Playwright test on Webkit, the WebSocket connections will sometimes get "stuck."  No errors are visible in the console or Network tab of devtools, but the WebSocket connection never appears to become established, and it does not process any messages.  In order to trigger this issue it also seems necessary to be using an HTTP proxy, and the only way I've been able to reliably reproduce it is when the browser and proxy are on different hosts.

I found a strange work-around for this issue.  Once the WebSocket gets stuck, if you open a new tab and then visit any website (I like to use [http://neverssl.com](http://neverssl.com)), the WebSocket connection in the original tab immediately becomes "unstuck" and starts functioning normally.  We've had to use this strategy of opening a new tab and visiting a website in the new tab in order to get our tests passing reliably.  Here is a video demonstrating this behavior:

[WebKit WebSocket hang.webm](https://github.com/microsoft/playwright/assets/307312/a3cf2b4b-3077-4087-88ce-182b3b7f772f)

The issue is somewhat difficult to reproduce.  We have an app that can reproduce the issue nearly 100% of the time, but it requires login credentials that I'm not authorized to give out.  I have been been able to reproduce the issue using the public site [SocketsBay](https://socketsbay.com/test-websockets), but it sometimes requires running multiple iterations of the test before the bug manifests.  I've created a Playwright test with instructions on how to reproduce the issue here: [jbaldassari/playwright-webkit-websocket-hang](https://github.com/jbaldassari/playwright-webkit-websocket-hang).

### System info
- Playwright Version: v1.36.2
- Operating System: Multiple Linux distributions e.g. Ubuntu 22.04.2 LTS
- Browser: WebKit
- Other info: Requires an HTTP proxy to be configured; the proxy needs to be running on a different machine than the browser in order to most reliably reproduce the issue

### Source code

Test code instructions to reproduce the issue can be found here: [jbaldassari/playwright-webkit-websocket-hang](https://github.com/jbaldassari/playwright-webkit-websocket-hang).

**Comment by mxschmitt** [comment]
I apologise the late response. We were doing some networking stack changes in WebKit the couple of weeks. From Version 1.38 onwards WebKit on Ubuntu22+/Debian12+ will use libsoup3 instead of libsoup2. They are significantly different. This might resolve these issues.

Would it be possible that you try our [Canary version](https://playwright.dev/docs/canary-releases) in the meantime to see if thats the case?

I tried your reproducible with the following setup:
- Ubuntu 22 host to run the tests like you have.
- External machine in another data center with Ubuntu 22, for running mitmweb
- Playwright version 1.36.2 like you have
- Just modified test.sh slightly, so we log the number of attempts
- Ran it in total 700 times with your script, and it did not hang a single time. 

How often did you get the error surfaced? aka. the hang with the exception.

**Comment by jbaldassari** [comment]
@mxschmitt thank you very much for spending the time to try to reproduce this one.  I know it's not the easiest setup.  I'm sorry you were not able to observe the problem.  Maybe there's another variable I haven't identified yet.  When I run the steps outlined in this issue  I'm usually able to reproduce the hang in fewer than 10 attempts.  We also have a customer whose app is able to reproduce the issue nearly 100% of the time, but unfortunately it requires valid login credentials to trigger it.

It's interesting that you're in the process of rolling out some changes to the WebKit networking stack.  I will definitely try your suggestion of using the canary build and report back.  If I still see it there I'll try to get permission to obtain a set of credentials for our customer's app that could be shared privately.

**Comment by jbaldassari** [comment]
Hi @mxschmitt .  Sorry for the delay.  I did attempt to use the latest Canary version, but I am still observing the connection hangs with this version.  Could I share a separate test with you privately that reproduces the issue more reliably (100% of the time for me)?  It requires logging into a particular website in order to trigger the hang.  I've been authorized to share login credentials for this site with Playwright developers if you have time to take another look.

**Comment by mxschmitt** [comment]
> hangs with this version.

can you confirm that you are using Ubuntu 20.04?

> Could I share a separate test with you privately that reproduces the issue more reliably (100% of the time for me)?

We can do this yes. Pinging me on Discord is the easiest, alternatively "maxschmitt`@`microsoft.com. I can try to narrow it more down from there, but can't promise that much, since so far we didn't get many bug reports around that area, so it would be more low priority for now.

**Comment by jbaldassari** [comment]
> can you confirm that you are using Ubuntu 20.04?

It's Ubuntu 22.04

> Pinging me on Discord is the easiest

Will do!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
