### ISSUE TITLE
[.Net6 Alpine images/Lightweight image of Playwright]

### ISSUE THREAD

**Issue by starlordgit007** [microsoft/playwright#26368]
I was able to build and run playwright .Net6 project image using Podman.
But image size is around 3.5GB, Is there any lightweight image available or any plan for 
alpine images?

Please find below details of image that currently I am using.

**mcr.microsoft.com/playwright/dotnet:v1.36.0-jammy**

Thanks!

**Comment by mxschmitt** [comment]
We recommend building your own Docker image when you only need a specific browser engine. You can e.g. just install the Chromium dependencies and/or use a different .NET version:

https://playwright.dev/dotnet/docs/browsers#install-system-dependencies

You could do this e.g. with Debian 12 slim which is smaller than a normal Ubuntu.

We have unfortunately no plans to support Alpine Linux, since browsers rely on special libraries, aka. libc6/glibc which are not available there, also browsers like WebKit don't compile out of the box there.
