### ISSUE TITLE
[BUG] screenshot with clipping area doesnt work with locator

### ISSUE THREAD

**Issue by marwie** [microsoft/playwright#26379]
### System info
- Playwright Version: 1.36.2
- Operating System: Win 10
- Browser: Chrome
- Other info:

### Source code

```ts
 const screenshot = await page.locator(".myElement").screenshot({
            clip: {
                x: 50,
                y: 50,
                width: 55,
                height: 55
            },
        });
```

**Expected**

The page.locator screenshot result is clipped

**Actual**

the page.locator screenshot result is NEVER clipped

Possibly related to https://github.com/microsoft/playwright/issues/12730

**Comment by dgozman** [comment]
@marwie We need more information to act on this issue. Could you please provide a self-contained repro that we can run locally?

**Comment by marwie** [comment]
Hi, seems like I was mislead thinking a `Locator` could also be screenshot with the `clip` field but it seems that's not the case (it's not in the types)

When reading the docs I was under the impression the `page.screenshot` options would match with the `locator.screenshot` options which seems to not be the case. Maybe the docs could state that more clearly?

https://playwright.dev/docs/screenshots#element-screenshot

**Comment by dgozman** [comment]
> When reading the docs I was under the impression the page.screenshot options would match with the locator.screenshot options which seems to not be the case. Maybe [the screenshot docs](https://playwright.dev/docs/screenshots#element-screenshot) could state that more clearly?

Good point, I missed that when first read the issue. Indeed, we do not support clip on the element screenshot. We can update the docs to be more specific about it, or we can even repurpose this issue to be a feature request and see whether it would be a popular one.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
