### ISSUE TITLE
[Feature] Parameterize tests with iterations

### ISSUE THREAD

**Issue by Mikkvaal** [microsoft/playwright#26431]
I am trying to get my parameters from azure devops and run my playwright tests with those. Getting the parameters works fine, but if I want to run my tests in several iterations with different parameters I'm experiencing some issues.

There is two issues I've encountered:
1. Playwright does not wait for async response (in my example from the api request to azure devops) before it skips ahead to the test itself.
2. If i wrap my test inside a for-loop, and put the parameters request inside BeforeEach or BeforeAll, playwright doesn't enter the beforeEach/beforeAll functions untill it gets to the test itself. 
So for a loop that looks like this:
For (let i = 0; i < parameters.length; i++) it will tell me that there is no tests found because it can't access the test inside the loop.

To recreate the problem:

```
import { test } from '@playwright/test';

let parameters: number[] = [];

function fetchTestCaseParameters() {
    return new Promise(resolve => {
        setTimeout(() => {
            resolve([1, 2, 3]);
        }, 1000);
    });
}

async function initializeParameters() {
    return await fetchTestCaseParameters();
}

test.describe('Test suite', async () => {
    test.beforeAll(async () => {
        parameters = await initializeParameters();
    });
    
    // test(`my test`, async ({ page }) => {
    test(`${parameters[0]}`, async ({ page }) => {
        console.log(parameters);
    });
});
```

**Comment by dgozman** [comment]
@Mikkvaal You should make `parameters` available synchronously, because test runner needs to know about your tests synchronously.

I'd recommend to generate `parameters` before running `npx playwright test` and store them into a JSON file. Then you can read it here in the test file:

```ts
import { test } from '@playwright/test';

let parameters = require('./parameters.json');

test.describe('Test suite', async () => {
    test(`${parameters[0]}`, async ({ page }) => {
        console.log(parameters);
    });
});
```

Let me know whether this helps.

**Comment by mxschmitt** [comment]
It's unfortunately technically not possible to implement it, since we'd have to load the test-file twice, one with running the before hooks and then one time again with the data populated.

You can instead leverage [globalSetup](https://playwright.dev/docs/test-global-setup-teardown#configure-globalsetup-and-globalteardown) for that, would that work for you? So you can load the data there, store the parameters inside a temp file, or inside an env var and then access it inside your test files.

**Comment by yury-s** [comment]
@Mikkvaal  as Max mentioned above it is not currently possible. You can have a [global setup](https://playwright.dev/docs/test-global-setup-teardown#setup) project that would write `parameters.json` (e.g. fetch list of the tests to run from a server) before running all the tests and then use what @dgozman suggested to run only those tests. Would that work?

**Comment by yury-s** [comment]
Closing per the response above as there is no action planned on playwright side, feel free to open a new issue if you have a specific request after looking into that.
