### ISSUE TITLE
[Feature] Allow global setup to persist for some time

### ISSUE THREAD

**Issue by glenjamin** [microsoft/playwright#26470]
We've got a test suite that contains two different global setup tests, which log in with a couple of different users.

These sessions are valid for some time.

When iterating on a single test locally, it would be great if we could avoid having to re-execute the global setup each time, and continue to re-use the setup saved from the first attempt.

One way of doing this might be to allow setting a validity duration on the saved auth state. Another possibly simpler approach could be a skip-setup flag.

Does this make sense, is it a reasonable request or am I holding it wrong?

**Comment by mxschmitt** [comment]
It makes total sense. I'd recommend for now to manually persist the files in form of a storage state (await context.storageState() on your disk and e.g. if its older than 1 hour re-create the file and write it again to disk.

We did some experiments in the past around this and found out that fs.writeFileSync and fs.readFileSync is also straightforward to use.

Linking https://github.com/microsoft/playwright/pull/18522

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
