### ISSUE TITLE
[Feature] Fulfilling http-requests with any status codes

### ISSUE THREAD

**Issue by bezyakina** [microsoft/playwright#26495]
Hi! Today I found out that I can't change the request statuses to 295, 296, 299 using the fulfill method.
I found a restriction in the [source code ](https://github.com/microsoft/playwright/blob/d2165f3e2deb3dae0a79a23311248f41f93de64f/packages/playwright-core/src/server/network.ts#L618C20-L618C94) for unassigned statuses, but developers can use unassigned codes.
I would like to be able to replace the request code with any status, and not just one of the specified ones.

Like this:

```
import { test } from "@playwright/test";

test("open google and replace status code to 296 for https://www.google.com/complete/search* method", async ({ page }) => {
  await page.route(
    "https://www.google.com/complete/search*",
    async (route) => {
      void route.fulfill({
        status: 296,
      });
    }
  );
  await page.goto("https://www.google.com/");
  await page.waitForLoadState("networkidle");
});
```

**Comment by mxschmitt** [comment]
Investigation note:

Its Chromium which asserts it here: https://source.chromium.org/chromium/chromium/src/+/main:net/http/http_status_code.cc;l=22;bpv=1;bpt=1?q=http_status_code.cc&ss=chromium%2Fchromium%2Fsrc

getting called from [here](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/protocol/fetch_handler.cc;l=195;drc=0d6e097c1e1aeaa0c4200d8e2b1d887d14f74a63;bpv=1;bpt=1).

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
