### ISSUE TITLE
[Feature] Support `transitionType` and `referrerPolicy` attribute on `Page.navigate`

### ISSUE THREAD

**Issue by jjsaunier** [microsoft/playwright#26544]
Hi, 

I want to support those attributes to replicate correct behaviors and avoid hooking headers, but I don't know where to start regarding the wiring of the CDP protocol, the binding looks magic, and I don't get it. If you could give me some pointers to understand it 

https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-navigate

**Comment by mxschmitt** [comment]
How is the transitionType important for your web app itself?

And what is the scenario you want to test with the referrerPolicy?

**Comment by jjsaunier** [comment]
The use case for the transition type is to change the browser behavior to set https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-User; in our test, we tested the request was initiated by user action and is part of the logic to discard analytics/user event.

The referrer policy is primarily for marketing/origin tracking use cases to predict the behavior of each policy regarding the acquisition path and ensure the value matches and get a clear vision of the impact of the retrieved referer to prepare or update our internal matching rules

**Comment by jjsaunier** [comment]
I forgot to mention, but I'm using playwright-python, I opened the issue here, because AFAIK the protocol file for CDP binding is generated here, so that's the first place to update

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
