### ISSUE TITLE
[BUG] AndroidKeys inserts square brackets instead of parentheses

### ISSUE THREAD

**Issue by Nantris** [microsoft/playwright#26629]
### System info
- Playwright Version: v1.37.1
- Operating System:  Android (Version 13)
- Browser: Chrome
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

Relevant code after defining `device` is `device.input.press('(')`

I tried `LeftBracket` also as mentioned in [this file](https://github.com/microsoft/playwright/blob/00e65407995c2705598410ec5c79189ab5ad94e9/utils/generate_types/overrides.d.ts#L292) but the outcome is the same

**Test file (self-contained)**

TBD

**Steps**
Run `device.input.press('(')`

**Expected**

Inserts a parentheses

**Actual**

Inserts a square bracket instead

**Comment by yury-s** [comment]
Please provide a minimal self-contained project that we could run locally to reproduce the problem. We can't act on this report without seeing your code and being able to repeat the problem.

**Comment by Slapbox** [comment]
Hi @yury-s thanks for your reply. I provided the relevant piece of code but not a minimal self-contained project.

If a full repro is required could I suggest that the issue template be updated?

> You can still file without the exact code and we will try to help, but if we can't repro, it will be closed

**Comment by yury-s** [comment]
> If a full repro is required could I suggest that the issue template be updated?

The template says that we need a repro that is sufficient to reproduce the bug. Without a repro I'll assume that you are testing a web page, in that case you can use `locator.press()` like this:

```js
test('should check the box @smoke', async ({ page }) => {
  await page.setContent(`<input id='my-input' type='text'></input>`);
  await page.locator('input').press('(');
  expect(await page.evaluate(() => window['my-input'].value)).toBe('(');
});
```
this test passes for me with android simulator. Would this method work for you?


The following test does insert '[' instead of '(':

```js
test('should check the box @smoke', async ({ page }) => {
  await page.setContent(`<input id='my-input' type='text'></input>`);
  await page.locator('input').focus();
  const [device] = await android.devices();
  await device.input.press('(');
  expect(await page.evaluate(() => window['my-input'].value)).toBe('(');
});
```

**Comment by Slapbox** [comment]
Thanks for the detailed reply @yury-s. I see your point.

----

The locator method may work for us; I'll have to investigate more.

But I think that [Playwright can't produce `beforeinput` events](https://github.com/microsoft/playwright/discussions/26630#discussioncomment-6797408), so we probably can't use it anyway. Am I mistaken about `beforeinput`? Is it documented somewhere what events Playwright does/does not produce?

Regardless of whether we can use Playwright for our purpose, I wanted to report the bug since I encountered it. Thank you again.

**Comment by yury-s** [comment]
> Am I mistaken about `beforeinput`? Is it documented somewhere what events Playwright does/does not produce?

Playwright's keyboard actions should trigger the same browser events as a human user interacting with the app would do. If `beforeinput` is missing in case of automation but fired when you press a key on actual device, it is a bug.

**Comment by Slapbox** [comment]
Thank you so much for that information @yury-s. Knowing that it should work, I was able to confirm that `beforeinput` events do work, but the timing is a little weird; I had to add some artificial delays to get our use case working.

I'll still have to investigate whether the locator workaround could work for us. Thanks again!

**Comment by Nantris** [comment]
A very late update, but the locator workaround does work for us. I think this workaround is suitable for most things, but #28748 can be a blocker for certain cases as Playwright sends some events in a weird way, like a hybrid mobile and desktop event, rather than truly replicating the Android events as they would be produced by the device.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
