### ISSUE TITLE
[BUG] - test.AfterAll is being executed after each failed test instead of after all tests

### ISSUE THREAD

**Issue by alexkyrylenkoproven** [microsoft/playwright#26632]
### System info
- Playwright Version: v1.35.0
- Operating System: All
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

**Test file (self-contained)**

```js
const { test, expect } = require('@playwright/test');

test('test 1', async ({ page }) => {
    expect(true).toBeFalsy();
})

test('test 2', async ({ page }) => {
    expect(true).toBeTruthy();
})

test('test 3', async ({ page }) => {
    expect(true).toBeTruthy();
})

test.afterAll(({}, testInfo)=>{
    console.log(testInfo.status)
})

```

**Steps**
- [Run the test]
- [...]

**Expected**

test.AfterAll executed 1 time after all 3 tests ran regardless of the status of each one

**Actual**

test.AfterAll executed 2 times. first time after the failed test and a second one after the rest 2

**Comment by yury-s** [comment]
This is by design, when a test fails Playwright will stop the test worker process and create a new one for the remaining tests, so you never run more than one failing test in the same process. See [this page](https://playwright.dev/docs/test-retries#failures) for detailed description of the behavior.

**Comment by alexkyrylenkoproven** [comment]
@yury-s thank you, that makes sense. Is there any option that afterAll can be run truly after all the tests executed and only one time?
