### ISSUE TITLE
[Feature] Possibly registering a PlayWright DOM observer to listen if DOM changed?

### ISSUE THREAD

**Issue by shaoerkuai** [microsoft/playwright#26639]
For eg, mutationObserver could be used to monitor a DOM change in JavaScript API.

There is no native mutationObserver-like thing in Playwright rightway.   I am watching toasts popupping , it's randomized and a bit annoying for automation testing..

Alternatively, I listen for the request right away and get the contents of toast through locator in due course, but it leads to extra work and I will misses something when toast doesn't come from the request (likely from a logic exception?).

**Comment by yury-s** [comment]
We recommend [web assertions](https://playwright.dev/docs/test-assertions#auto-retrying-assertions), so that you test user-visible behavior. Instead of waiting for DOM to settle, you specify your expectations and Playwright waits until your expectations are met automatically. If the toast is optional and may not show up under some circumstances, you can use [localtor.or](https://playwright.dev/docs/api/class-locator#locator-or)  to wait for either the toast or some other element that will tell you that the toast will not be shown after that point. Would that work for you?

**Comment by yury-s** [comment]
Closing per the last comment above.
