### ISSUE TITLE
[Feature] Extend Playwright reports attachments section

### ISSUE THREAD

**Issue by IgnasCi** [microsoft/playwright#26763]
It would be nice to have extended attachments section of playwright reports so that:

- Attached html files are shown inline in the same as screenshots (no need to open html attachment to see the content). This would allow user to add any additional stuff to be a part of report directly. 
- Markdown attachments. Currently all the text attachment content are shown in text/plain style. What about text/markdown?
- Ability to control what attachments are collapsed / expanded. Basically some attachments could be more important than others.

**Comment by Vijay-Jose** [comment]
> It would be nice to have extended attachments section of playwright reports so that:

How do you add the HTML file as Attachment
is there any specific content type available for html like 'image/png', 'application/json'

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
