### ISSUE TITLE
[Feature] CPU usage debugger

### ISSUE THREAD

**Issue by ArtjomsFomins** [microsoft/playwright#26816]
I would like to see how many playwright consumes CPU when it runs.
I know that in cypress you can do like
`DEBUG=cypress:server:util:process_profiler cypress run`
at it will print CPU usage
![image](https://github.com/microsoft/playwright/assets/126476500/ffafb94b-44dc-4a57-9bae-7816de947612)
It Would be useful for me when my playwright runs in github actions

**Comment by cenfun** [comment]
The usage of CPU and memory can be seen in this custom report: [monocart-reporter](https://github.com/cenfun/monocart-reporter)
demo:
https://cenfun.github.io/monocart-reporter/#page=report

![image](https://github.com/microsoft/playwright/assets/334577/57d59462-f5a5-4005-aae2-0b8d9a4b1975)

**Comment by ArtjomsFomins** [comment]
> The usage of CPU and memory can be seen in this custom report: [monocart-reporter](https://github.com/cenfun/monocart-reporter) demo: https://cenfun.github.io/monocart-reporter/#page=report
> 
> ![image](https://user-images.githubusercontent.com/334577/265243690-57d59462-f5a5-4005-aae2-0b8d9a4b1975.png)

Hmm, I didn't know about that but looks nice. Although it would be nice to have such feature in the default playwright reporter, because I kinda don't want to spend my time on understanding and integration of the 3rd plugin of the playwright for my project.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
