### ISSUE TITLE
[BUG] TypeError: response.request is not a function

### ISSUE THREAD

**Issue by scottsantucci-8451** [microsoft/playwright#26819]
### System info
- Playwright Version: v1.37
- Operating System: macOS 13.5, (but maybe All)
- Browser: Chrome/Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
import { test } from '@playwright/test';

test("Check the headers on the request", async ({ request }) => {
    await request.get("https://github.com").request()
})
```

**Steps**
- npx playwright test

**Expected**

Test passes. Documentation has this example:

https://playwright.dev/docs/api/class-response#response-request

```ts
response.request();
```

**Actual**

> TypeError: request.get(...).request is not a function

**Comment by aslushnikov** [comment]
> Test passes. Documentation has this example:

@scottsantucci-8451 The documentation you refer to is for a browser network request; the API request documentation is actually here: https://playwright.dev/docs/api/class-apiresponse

As you see, there's no `.request()` method there. 

> By the way, the issue template is missing the   ] to close the projects list.

Thanks, fixed!

**Comment by aslushnikov** [comment]
@scottsantucci-8451 `page.request` is of type `APIRequestContext`: https://playwright.dev/docs/next/api/class-page#page-request

This is the API request that shares the same cookies as the page.

**Comment by aslushnikov** [comment]
@scottsantucci-8451 there's no good request object that has url/headers/postData right now; there's only the [`APIRequest`](https://playwright.dev/docs/next/api/class-apirequest) and [`APIRequestContext`](https://playwright.dev/docs/next/api/class-apirequestcontext); I don't think either of these are interesting to have.

So this API might require creating first an object that represents the submitted request. It might have different set of methods, like `url()`, `postData()`, `headers()` and so on. 

If you'd like to have this, then please submit a new feature request that emphasizes your usecase, so that we (and others) had an idea of what's missing and what's required. 

Thanks!
