### ISSUE TITLE
[BUG] Debug mode with Playwright runner does not work for remote browser connections

### ISSUE THREAD

**Issue by ankur-lt** [microsoft/playwright#26814]
### System info
- Playwright Version: 1.37.0
- Operating System: All
- Browser: All
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**
Link to the Playwright test suite: https://github.com/LambdaTest/playwright-sample/tree/main/playwright-test-js
The Playwright sample provided here connects to the LambdaTest cloud which runs the Playwright server.

**Steps**
- Run the test using `npx playwright test --config=./playwright.config.js --debug`
- The debug mode popup comes but it doesn't work. The popup is blank with no test code.
- When I run the same test suite locally, which can be done by running with these configs(https://github.com/LambdaTest/playwright-sample/blob/64495b605c6bb506b8ec4c097d77af567a92031b/playwright-test-js/playwright.config.js#L46-L73), the debug mode works as expected.

Rather than using the Playwright library function of `browserType.connect()`, I also tried connecting to the remote browser via the Playwright runner itself, via `connectOptions.wsEndpoint` in the project configuration, but the debug mode was not working.

**Expected**
The debug mode should work with remote browsers too, to debug the tests on any different OS and browser version.

**Actual**
The debug mode works only while executing tests locally.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
