### ISSUE TITLE
Add new FrameLocator.waitForFunction() method

### ISSUE THREAD

**Issue by ajssd** [microsoft/playwright#26829]
Today we have contentFrame.waitForFunction() but this does not work with Frame Locators.  What we would LIKE to do is this:
```
await locator.frameLocator('#my-frame').waitForFunction(() => { ... });
```
but what we have to do today is this:
```
const myFrame = await this.page.waitForSelector('#my-frame');
const myContentFrame = await myFrame.contentFrame();
await myContentFrame.waitForFunction(() => { ... });
```
Not the end of the world, but it's three async calls, and it takes away from a purely Locator-based approach that Playwright recommends.

Even something like this would get us halfway there:
```
const myContentFrame = await locator.frameLocator('#my-frame').contentFrame();
await myContentFrame.waitForFunction(() => { ... });
```
but there is no way to get the content frame from a frameLocator.

References:
- https://playwright.dev/docs/api/class-framelocator
- https://playwright.dev/docs/api/class-frame#frame-wait-for-function

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
