### ISSUE TITLE
[BUG] The requested module '@playwright/test' does not provide an export named 'createElement'

### ISSUE THREAD

**Issue by AlessioGr** [microsoft/playwright#26824]
### System info
- Playwright Version: 1.37.1 (patched with custom loader to support esm, see https://github.com/microsoft/playwright/issues/26822. I don't think the loader is causing this particular issue, as it only handles svg/png/scss files.)
- Operating System: macOS 14.0
- Browser: any
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/payloadcms/payload/tree/2.0-esm/packages/payload/test/refresh-permissions

**Steps**
1. Clone the [payload repository](https://github.com/payloadcms/payload/tree/2.0-esm/packages/payload/test/refresh-permissions) (`2.0-esm` branch)
2. Run `pnpm install`
3. Run `pnpm test:e2e refresh-permissions`

**Expected**

The test passes

**Actual**

The test fails with the following error:
![Screenshot 2023-08-31 at 19 45 56@2x](https://github.com/microsoft/playwright/assets/70709113/ae9ca491-0a1a-4c3f-99f1-66d43c41958c)

The issue is triggered by returning the `DefaultGlobalView` component in the [GlobalViewWithRefresh.tsx](https://github.com/payloadcms/payload/blob/2.0-esm/packages/payload/test/refresh-permissions/GlobalViewWithRefresh.tsx) component included in the test. If I return anything else, e.g. a paragraph, the issue does not happen.

My hypothesis is that playwright, for some reason, compiles the component down into nonsense where somehow `createElement` is imported from `@playwright/test` instead of from `React`. Running the test directory directly (`pnpm dev refresh-permissions`) which doesn't use playwright works fine.

This has been happening ever since we migrated payload from cjs+yarn to esm+pnpm+monorepo.

**Comment by jmikrut** [comment]
Hey all, just a bump on this one. We have to maintain a patched copy of Playwright for [Payload](https://payloadcms.com/) in order to get around this.

https://github.com/payloadcms/payload/blob/alpha/patches/playwright%401.42.1.patch

Any ideas for how we can work around this so we don't need to patch this?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by joeyvandijk** [comment]
Had the same error message, but found out that I had a recursive import loop where one of my Playwright files was using a barrel file in its imports which imported quite some other files and got stuck in the above very generic error-message.

The annoying thing was that `createElement` was not in my code anywhere to be found, but probably @AlessioGr had a good point that Playwright did not parsed the typescript correctly and failed on createElement.

Maybe useful for others when bumping into this issue.
