### ISSUE TITLE
[BUG] page.evaluate with function passed as string never executed using TypeScript

### ISSUE THREAD

**Issue by GoldenretriverYT** [microsoft/playwright#26851]
### System info
- Playwright Version: v1.37.1
- Operating System: Windows 11
- Browser: Chromium
- Other info:

### Source code
```ts
import * as playwright from 'playwright';

(async () => {
    const browser = await playwright.chromium.launch({
        headless: false,
    });
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('data:text/html,ok');

    await page.evaluate(`() => {
        document.write("If this would execute, we would see this in the browser window");
        console.log("If this would execute, we would see this in the browser console");
    }`);
})();
```
- [x] I provided exact source code that allows reproducing the issue locally.

**Steps**
- Create a TypeScript project
- Transpile the code and run the transpiled code
- Observe that the console.log is never executed, nor is the document.write

**Expected**

The code should be evaluated as expected

**Actual**

The code is never evaluated.

** Why this is important **

I need to use async/await but that transpiles to references to __awaiter, which are undefined in the browsers context so I took a look at the docs and they show that you can use strings instead which, logically, prevents TypeScript from transpiling it. See this https://playwright.dev/docs/test-typescript#transpilation-issues - whilst this is about imports, it shows off using strings for page.evaluate (the example shows async arrow functions, but that doesnt work either)

**Comment by pavelfeldman** [comment]
When you pass a string, it is assumed to be evaluatable expression. Something you pass to `eval()`. So in your case it would be 
```
(() => {
        document.write("If this would execute, we would see this in the browser window");
        console.log("If this would execute, we would see this in the browser console");
})();
```

But instead of doing that, I'd suggest that you change your transpilation target to a modern ESM version where async/await is supported. That way your problem will go away - no `__awaiter` will be generated because JS supports async/await natively for many years now and there is no need to emulate them. Somewhere you transpile the code yourself (not with automatic Playwright transpilation) and are using legacy (pre 2015) settings.

**Comment by GoldenretriverYT** [comment]
Alright, but I'd suggest to update the docs to correctly show this behaviour as https://playwright.dev/docs/test-typescript#transpilation-issues does not show it like that
