### ISSUE TITLE
[Feature] `headless` option as part of configuration to automatically apply correct flag (Chrome)

### ISSUE THREAD

**Issue by Zidious** [microsoft/playwright#26862]
As per the [docs](https://playwright.dev/docs/chrome-extensions#headless-mode), to load a Chrome Extension you must do: 

```ts
const pathToExtension = path.join(__dirname, 'my-extension');
const context = await chromium.launchPersistentContext('', {
  headless: false,
  args: [
    // the new headless arg for chrome v109+. Use '--headless=chrome'
    // as arg for browsers v94-108.
    `--headless=new`,
    `--disable-extensions-except=${pathToExtension}`,
    `--load-extension=${pathToExtension}`,
  ],
});
```
It would be an enhancement to not have to set `--headless=*` flag at all and rely on the `headless` configuration option Playwright provides. 

Would it be possible to dynamically load the Chrome flag as `-headless=new` or `headless=chrome` depending on what Chromium version the user is using?

**Comment by pavelfeldman** [comment]
Both, fast `--headless` and slow `--headless=new` Chromium modes are available in newer Chromium builds. The default mode is `--headless` in Playwright because it is faster and has better test coverage. When testing extensions, you need to opt into the `--new` mode, hence the setting. We should simply remove the --headless=chrome from the docs as in recent Chromium it is of no use.
