### ISSUE TITLE
[Feature] WebSockets supports

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#2695]
WebSocket support has been requested a few times already on the issue tracker:
- https://github.com/microsoft/playwright/issues/2675#issuecomment-649007234
- https://github.com/microsoft/playwright/issues/2572
- https://github.com/microsoft/playwright/issues/2162

The general consensus is that sniffing is very useful, and frame interception is desirable.
It'd be nice to have an API similar to `page.on('request')`, e.g. `page.on('websocket')` event that will
yield some handle for websocket.

Please upvote the issue and feel free to share your usecases to help us shape the API!

**Comment by gabrielmanara** [comment]
That would be really useful for negative test and to allow mock websocket responses. I was trying to find an way to do it since the core of the application I’m implementing the automated test (using playwright) it’s using websocket to fetch the data.

Do you still have plans to support it? @aslushnikov

**Comment by pavelfeldman** [comment]
Fixed
