### ISSUE TITLE
[BUG] Config dependencies is not runing for test if grep option is specified in config as RegExp array

### ISSUE THREAD

**Issue by SemenSizov** [microsoft/playwright#27083]
### System info
- Playwright Version: [v1.38]
- Operating System: [ Windows 10]
- Browser: [All]
- Other info:    In the project, the list of test IDs is provided as process.env.TEST_IDS_TO_RUN variable, parsed to the array of RegExp, and this array is passed to the config as grep option value.

### Source code

- [x] I provided the exact source code that allows reproducing the issue locally.

[**Link to the GitHub repository with the repro**](https://github.com/SemenSizov/playwright-grep)

**Steps**
- Specify process.env.TEST_IDS_TO_RUN with any value
- run `npx playwright test --list`

**Expected**
Before the execution of tests specified in  `process.env.TEST_IDS_TO_RUN`, a related setup file should be executed.

**Actual**
Only tests specified in  `process.env.TEST_IDS_TO_RUN` variable is executed. No run of any related setup files.

**Comment by dgozman** [comment]
The tests are filtered when I pass `TEST_IDS_TO_RUN=025` or `TEST_IDS_TO_RUN="025,026"`. However, there is a difference between setting `config.grep` and passing `--grep` option in the command line: the former filters out tests in dependencies, while the latter does not.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by dimau** [comment]
Faced the same problem

**Comment by dimau** [comment]
@pavelfeldman can you please consider fixing this problem one more time?
