### ISSUE TITLE
[Feature] Request for Mocking Functions in Request Fixture for API Testing

### ISSUE THREAD

**Issue by hardeep-qa** [microsoft/playwright#27166]
Dear Playwright Team,

I’ve been experimenting with the Typescript Playwright framework for API testing and I’m impressed with its capabilities. However, I noticed that the functions related to mocking, such as route(), unroute(), etc., are only available in the page fixture.

Given that my project is solely focused on API testing, I would prefer not to use the page fixture. Therefore, I kindly request that these mocking functions be made accessible through the request fixture. This would greatly streamline my API testing process.

Thank you for considering my request.

Best regards, Harry

**Comment by aslushnikov** [comment]
Hey @hardeep-qa, I'm not sure I follow your request. Could you please illustrate what issue do you have and what mocking API are you missing?

**Comment by hardeep-qa** [comment]
Hello Andrey, Thank you for your prompt response. I wanted to clarify that currently, I don’t have the ability to mock API responses using the request fixture. This functionality is available in the page fixture, but for my use case, which is solely API testing, I prefer not to use the Page fixture. I’m curious if it would be possible to incorporate the mocking feature into the request fixture as well.

Request fixture snapshot:
![image](https://github.com/microsoft/playwright/assets/43902698/6e22d333-f3d0-450d-9cdd-3762b5718413)

Page fixture snapshot:
![image](https://github.com/microsoft/playwright/assets/43902698/460d3e26-ed67-4097-85c5-cbe81dcfe9af)

**Comment by yury-s** [comment]
Can you give an example of where `route()` would be useful for API testing?

Intercepting and mocking network requests makes sense when testing a web page, because you don't normally have control over when the page sends network requests. With API testing it's the test code that issues all requests via `request` fixture and you can either modify the response after it has been received or even skip the request completely and construct the response data inside your test. You also control how the requests are constructed, so there is no need to intercept and modify them.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
