### ISSUE TITLE
[BUG] [Dependency] Replace `rimraf`

### ISSUE THREAD

**Issue by lukeed** [microsoft/playwright#2716]
**Context:**
- Playwright Version: 1.1.1
- Operating System: N/A
- Node version: N/A
- Browser: N/A
- Extra: N/A

**Describe the bug**

Playwright has [37 total dependencies](https://npm.anvaka.com/#!/view/2d/playwright), and `rimraf` accounts for [12](http://npm.anvaka.com//#!/view/2d/rimraf) of them. I (quickly) scanned your `rimraf` usage, and it didn't seem like you were even using the glob functionality.

It's one of my own, but I'd suggest [`premove`](https://github.com/lukeed/premove) which supports Node > 8, is Promise-based by default, offers a `sync` version, and has 0 dependencies. Since you don't seen to be glob-deleting, it supports your use case too.

The `2.0` adds native ESM support, which means you'd have to explicitly restrict Node 13.0 - 13.6, inclusive, (faulty `exports` parsing). The `1.0` does not have native ESM support nor a `sync` variant, but I can ship a `1.1.0` if that's your preference.

Either way, once minimum support is eventually raised, Node v12.10.0 includes the `recursive` option for `fs.rmdir` and `fs.rmdirSync` – dropping the need for _any_ external dependency.

Thanks

**Comment by pavelfeldman** [comment]
@aslushnikov did we use rimraf for Windows or something? I remember it was working around some trickery.

**Comment by aslushnikov** [comment]
@lukeed thanks for suggestion!

We use `rimraf` mostly because it has some trickery around windows:
- permission tricks: https://github.com/isaacs/rimraf/blob/8c10fb8d685d5cc35708e0ffc4dac9ec5dd5b444/rimraf.js#L183-L210
- retry tricks to workaround some handle issues: https://github.com/isaacs/rimraf/blob/8c10fb8d685d5cc35708e0ffc4dac9ec5dd5b444/rimraf.js#L333-L357

`rimraf` tricks are battle-tested, so I'd keep relying on them for now.
