### ISSUE TITLE
Playwright Python vs NodeJS vs Java

### ISSUE THREAD

**Issue by sramasub** [microsoft/playwright#27187]
I'm planning to use playwright for Oracle cloud applications testing. I want to know if I should go with NodeJS or python (I'm new to both so learning curve is the same). My test cases are integrated meaning the transaction created in one test case will be referenced in the other to continue with the testing process.

From the documentation, it looks like NodeJS offers more features than python. Is that so?

I also want to record the test execution so it can be submitted to business for verification. 

I'm also planning to generate all tests using codegen but observing it to be slow in python. Is this the case in NodeJS as well? Any pro or con would help w.r.t choosing NodeJS vs python vs Java

**Comment by aslushnikov** [comment]
> From the documentation, it looks like NodeJS offers more features than python. Is that so?

@sramasub in Node.js we provide our own, very capable and nicely integrated test runner - @playwright/test: https://playwright.dev/docs/intro So all in all, we'd recommend using Node.js if you don't have any preferences for language ecosystems.

> I'm also planning to generate all tests using codegen but observing it to be slow in python. Is this the case in NodeJS as well? 

If something is slow, then this is likely to be a bug. Feel free to file separately so that we can debug and fix it!
Hope this helps; if you think we still can be helpful to you, feel free to file a new issue!
