### ISSUE TITLE
[Feature] Ability to add watermarks to test execution video output

### ISSUE THREAD

**Issue by sramasub** [microsoft/playwright#27218]
Hi,

Is it possible that we can add a watermark to the test execution video output? If not, will be good to have this feature. Is there any other to add additional information that can show up on the video while it is running?

**Comment by aslushnikov** [comment]
Hey @sramasub,

It's not possible to add a watermark to the video, but you can try amending the website you're recording so that it shows some watermark atop of it.

The other option would be to use some video post-processing to add watermarks.

Overall, this falls outside of the scope of the Playwright, so I'll close this. But feel free to file a new issue if you think we still can be helpful!
