### ISSUE TITLE
[BUG] Headless webkit is not loading PayPal popup

### ISSUE THREAD

**Issue by gersanco** [microsoft/playwright#27228]
### System info
- Playwright Version: [v1.38.0]
- Operating System: [macOS 13.5.2]
- Browser: [WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/gersanco/playwright-webkit-paypal-popup

**Steps**
- Have video and trace set as "on"
- Run the test

**Expected**

The PayPal popup must be displayed with info.

**Actual**

It doesn't pass with Webkit when is headless

While I was preparing the project to report this, I discovered that if video and trace are not in the config or as 'on-first-retry' they pass.

https://github.com/microsoft/playwright/assets/12337026/a3707e08-ea68-434e-b84d-8439b0f69113

**Comment by yury-s** [comment]
All the tests are timing out when I run them locally, do we need NEXT_PUBLIC_PAYPAL_CLIENT_ID? Can you reduce the repro, so that it does not depend on PayPay token or share a test token that we can use? 

> While I was preparing the project to report this, I discovered that if video and trace are not in the config or as 'on-first-retry' they pass.

Enabling those features just makes the test slower but should not cause semantic changes in the behavior, so there might be a race in the test which is just more likely to occur when those options are set. It can also be that the server returns a different content based on some feature detection, try comparing the traces.

**Comment by gersanco** [comment]
Hi @yury-s you can try with this `NEXT_PUBLIC_PAYPAL_CLIENT_ID="AQwSpfPuE0nN08Hk6MvNkFCphq5ThZlCs1bcUC-PEtLRhYSFd9WvgKRmyPJ7gWlrbHKM6DwGssnK8p-m"`

> Enabling those features just makes the test slower but should not cause semantic changes in the behavior, so there might be a race in the test which is just more likely to occur when those options are set. It can also be that the server returns a different content based on some feature detection, try comparing the traces.

but as you can see in the video that I attached, it works when is not headless and the only browser that doesn't work is webkit.

**Comment by yury-s** [comment]
This is the same problem as https://github.com/microsoft/playwright/issues/27073 and was fixed by https://github.com/microsoft/playwright/pull/27098. Try with `npm i @playwright/test@next`, the problem should be gone.
