### ISSUE TITLE
[BUG] get_by_role() can't find <dd> elements with accessible name

### ISSUE THREAD

**Issue by michaeldmoser** [microsoft/playwright#27239]
### System info
- Playwright Version: 1.38.0
- Operating System: Debian bullseye
- Browser: Chromium
- Other info: Using with Django and pytest

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

I'm using python playwright and trying to locate a `<dd>` element using the Page.get_by_role() with an accessible name.

Here is the HTML:
```html
<dl class="grid grid-cols-2 gap-2">
  <dt id="term-acres" role="term">Acres</dt>
  <dd aria-labelledby="term-acres" role="definition">1.86</dd>
  <dt id="term-geocode">Geocode</dt>
  <dd aria-labelledby="term-geocode">04-2200-20-4-21-01-0000</dd>
  <dt id="term-property-type">Property Type</dt>
  <dd aria-labelledby="term-property-type">VAC_U - Vacant Land - Urban</dd>
</dl>
```

Here is the code to query for the element:
```python
page.get_by_role("definition", name="Acres") # finds nothing
page.locator("role=definition[name=Acres]") # finds nothing as well
page.get_by_label("Acres") # Does find the <dd> element
page.get_by_role("definition") # This does find elements with a role of definition
```

However a very similar situation with an `<h2>` and a `<ul>` does work:
```html
<h2 id="properties-title">Properties</h2>
<ul aria-labelledby="properties-title">
<li><a href="">...some address...</a></li>
</ul>
```

```python
page.get_by_role("list", name="Properties")
            .get_by_role("listitem")
            .get_by_role("link", name="...some address...", exact=True)
```

**Expected**

I would have expected that the `get_by_role` would have found the `<dd>` element by the associated label of `Acres`. 

**Actual**

Nothing is found.

**Comment by yury-s** [comment]
Can reproduce with the following js code snippet:

```js
  await page.setContent(`<dl class="grid grid-cols-2 gap-2">
  <dt id="term-acres" role="term">Acres</dt>
  <dd aria-labelledby="term-acres" role="definition">1.86</dd>
  <dt id="term-geocode">Geocode</dt>
  <dd aria-labelledby="term-geocode">04-2200-20-4-21-01-0000</dd>
  <dt id="term-property-type">Property Type</dt>
  <dd aria-labelledby="term-property-type">VAC_U - Vacant Land - Urban</dd>
</dl>`);
  await page.getByRole('definition', { name: 'Acres' }).click();
```

**Comment by michaeldmoser** [comment]
@yury-s Yes, the same issue was present with JS snippet you provided. I also tested with the HTML my app produces and the javascript failed to find the `<dd>` element there too. In addition the following worked:

```javascript
await page.getByRole("definition").first().click();
```
So it would seem from the outside that the python and javascript versions are in parity for the issue.

**Comment by michaeldmoser** [comment]
That's interesting, I hadn't notice that the `aria-labeledby` was not allowed. And the standard, as you point out, is not very clear on how to define the name. It does make a strong association between a `<dd>` and `<dt>` element but agreed the `name` is not clearly defined.

One possibility, which would turn this into a feature request I suppose, is to allow lookups based on the `aria-description` and `aria-describedby` which are allowed for the `definition` role.

Thank you for looking into this.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by jake-carpenter** [comment]
If anyone stumbles upon this and is just as disappointed as I was, I ended up testing this by using the ID attribute from the term to locate the definition. Used `aria-describedby` since apparently that's better than `aria-labeledby`.

```typescript
const definitionId = await page.getByText(/Term text/i).getAttribute('id')
await expect(page.locator(`dd[aria-describedby="${definitionId}"]`)).toHaveText('Definition text')
```

Ideally it wouldn't have to use non-user-visible selectors, but you can at least get the term from that. The term could also use `getByRole('term').filter(...)`.

**Comment by jasperdunn** [comment]
This is what I used as a workaround:

```ts
await expect(detailsCard.locator('dt:has-text("Year") + dd')).toHaveText(
    `${updatedYear}`,
  );
```

**Comment by GC-BenLeeHughes** [comment]
I must admit that I find it frustrating that Chrome both the browser and Chromium in Playwright _both show the term role as having a name / label_, but Playwright is following the specifications. I spent a decent chunk of time debugging this. If this is not an issue with Playwright, then I would either argue that this is an issue with Chromium or that perhaps the Web Accessibility Initiative should reconsider not having names for terms. Either way, I do wish we had some kind of FAQ or general location for people to figure this out a bit quicker than spending time hunting this issue down. I know Playwright wants to follow the spec, and I will also follow the spec best I can, but I am having to use @jasperdunn's suggestion above instead of using getByRole.

**Comment by GC-BenLeeHughes** [comment]
@jasperdunn and anyone else here, I have a Chromium issue regarding names existing on "term" roles filed here:
https://issues.chromium.org/issues/434005975

This is a regression in Chome caused by issue by this issue being fixed by incorrectly breaking WAI spec:
https://issues.chromium.org/issues/381418589
