### ISSUE TITLE
[Feature]  Reloading global setup in UI Mode (and global setup logs in UI Mode)

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#27258]
When I run Playwright tests in UI Mode it often happen that I need reload (close and open) this tool due to:
- need to run global setup (what is executed when UI is starting)

It is possible to add this to reload option in UI Mode?
  
Additionally global setup logs in UI Mode could be helpful, user will know whole context of test what are executed.

Currently user need to close UI Mode and start it again and look in console logs to find out what happen during global setup.

Example:
global.setup.ts
```typescript
import { defineConfig } from '@playwright/test';

export default defineConfig({
  globalSetup: 'global.setup.ts'
});
```

playwright.config.ts
```typescript
import { defineConfig } from '@playwright/test';

export default defineConfig({
  globalSetup: 'global.setup.ts'
});
```

After running: `npx playwright test --ui`
in console user get:
`⚠️  Global setup script`

In UI Mode there is no trace of those actions.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by RonNabuurs** [comment]
Is there a possibility to reopen this issue? Maybe there is more engagement this time. I would also like to see this feature.
