### ISSUE TITLE
[Feature] Launch doctor

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#2745]
Give us a script that we could use in the target environment that would tell us if Playwright will work there of point to the missing dependencies, libraries or arguments we need to pass into it.

Categorization of linked bugs:

- Windows
    - ~~https://github.com/microsoft/playwright/issues/2298 - Firefox is missing a DLL on Windows~~
    - ~~https://github.com/microsoft/playwright/issues/2840 - missing media DLL for WebKit~~
    - ~~https://github.com/microsoft/playwright/issues/2548 - missing media DLL for WebKit~~
    - https://github.com/microsoft/playwright/issues/2901 - missing media DLL for Chromium
- Linux
    - https://github.com/microsoft/playwright/issues/2321 - Google Cloud Functions is missing dependencies
    - ~~https://github.com/microsoft/playwright/issues/2386 - sandboxing issue~~ (sandboxing is addressed)
    - https://github.com/microsoft/playwright/issues/2404 - compile browsers for AWS lambda
    - https://github.com/microsoft/playwright/issues/2559 - support Ubuntu 20.04
    - ~~https://github.com/microsoft/playwright/issues/2621 - ArchLinux missing dependencies~~ (we punt it for now)
    - https://github.com/microsoft/playwright/issues/2660 - corrupted install, ubuntu 20.04
    - ~~https://github.com/microsoft/playwright/issues/2663 - sandboxing issue~~ (sandboxing is addressed)
    - https://github.com/microsoft/playwright/issues/2738 - Firefox fails on Ubuntu 16
    - ~~https://github.com/microsoft/playwright/issues/2298 - Firefox fails on Ubuntu 16~~

The scope of this bug:
- [x] Linux
    - [x] missing dependencies
    - [x] missing libraries
    - [x] Chromium sandboxing - [approach](https://github.com/microsoft/playwright/issues/2745#issuecomment-661956702)
    - [x] libc version mismatch for Firefox when running on Ubuntu 16
    - [x] Ubuntu 20.04 WebKit support
- [x] Windows
    - [x] missing media pack (Windows N, Server)
    - [x] missing C Runtime Redistributable
    - [x] missing DLLs
- [x] Mac - no problems so far with Mac.

**Comment by pavelfeldman** [comment]
Linking https://github.com/microsoft/playwright/issues/2298

**Comment by pavelfeldman** [comment]
Linking https://github.com/microsoft/playwright/issues/2321

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/issues/2386

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/issues/2404

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/issues/2559

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/issues/2621

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/issues/2624

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/issues/2660

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/issues/2645

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/issues/2663

**Comment by arjun27** [comment]
In addition to finding missing dependencies, this tool can also check for OS compatibility: eg. Firefox needs Ubuntu 18+. For example: #2738.

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/issues/2840

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/issues/2901

**Comment by mxschmitt** [comment]
Maybe WebKit on Heroku which crashes is also caused by not having all the dependencies installed:
https://github.com/mxschmitt/heroku-playwright-buildpack/issues/2

Discussion:  https://playwright.slack.com/archives/C0141EZ6ZNH/p1593729511002600?thread_ts=1593729511.002600&cid=C0141EZ6ZNH

**Comment by aslushnikov** [comment]
## `--no-sandbox` issues with Chromium

The `--no-sandbox` issue happens occasionally in different environments when launching Chromium; notably:
- without a properly configured seccomp profile for docker
- under `root` users in Linux (happens a lot in Docker as well)
- without enabled user namespace cloning in VMs (e.g. travis requires extra settings there in `.travis.yml`).

While tackling the `--no-sandbox` issue, our users face the following issues:
- getting lost in setting up sandbox following our instructions. Notably, it looks like SUID sandbox is no longer functional. #2386
- facing long error logs with error `Protocol error (Target.setAutoAttach): Target closed.` that doesn't surface sandboxing issue. #1887
- using `args` launch arguments for Chromium that doesn't port to other browsers. As a result, using the same launch options for webkit crashes webkit.

We considered running Chromium with `--no-sandbox` by default, or auto-detecting docker and adding `--no-sandbox` in docker only. Both are very strong measures: there are services that start containers with a nice seccomp profile (e.g. [Circle CI](https://circleci.com/docs/2.0/security/#sandboxing)) that we don't want to regress. 

Instead, we suggest the following:
- [ ] detect running under `root`, auto-add `--no-sandbox` there and print a warning into the terminal.
- [ ] detect sandbox startup failures and surface the error nicely
- [ ] provide the `chromiumSandbox` launch option instead of asking users to run with `args: ['--no-sandbox']`
- [ ] update sandboxing documentations

**Comment by mxschmitt** [comment]
@aslushnikov for Heroku we need also the `--no-sandbox` flag but on their environments it's not running as root.
Any way of detecting a not functional sandbox in such a case? (Since in your PR we add the parameter only if user ID is 0)

**Comment by aslushnikov** [comment]
> Any way of detecting a not functional sandbox in such a case?

@mxschmitt The only reliable way for me so far was running Chromium and seeing if it crashes =/ I'd like to look into Heroku to see what happens there - would I be able to do it on a free account? Can i SSH into their environment?

**Comment by mxschmitt** [comment]
> > Any way of detecting a not functional sandbox in such a case?
> 
> @mxschmitt The only reliable way for me so far was running Chromium and seeing if it crashes =/ I'd like to look into Heroku to see what happens there - would I be able to do it on a free account? Can i SSH into their environment? 

Can you ping me via Slack? "Max Schmitt" thanks!
