### ISSUE TITLE
[Feature]: Codespaces remove unavailable options

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#27481]
When running Codespaces we don't have the options of pick locator, record new, record at curser or show browser. 

When we click this it gives us an error message with no idea how to fix it. However if we just hide unavailable options when in a codespace it would make it a better user experience.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
