### ISSUE TITLE
[Feature] Expose PageFunction and Unboxed types

### ISSUE THREAD

**Issue by ghs** [microsoft/playwright#2752]
Have noticed that ~~some~~ many options types are not exported. **BrowserTypeLaunchServerOptions** as an example. Is it intentional?

Thanks!

**Comment by dakotaJang** [comment]
Many other return types such as `HTMLOrSVGElementHandle` are not exported as well.
I am trying to organize my instructions in to separate functions but it is very difficult when these types are not exposed.

Below is an example of what I want to do.
```ts
// Cannot import {HTMLOrSVGElementHandle} because it is not exported
import { HTMLOrSVGElementHandle } from "playwright";

// Cannot type the parameter because this type is not exported
function handler(handles: HTMLOrSVGElementHandle[]): string { /***/ } 

const e = await page.$$("*");
const result = handler(e);
```

It would be very useful to have these types exported to be available for developers.

**Comment by ghs** [comment]
@dakotaJang you can use Parameters<typeof ... > as mentioned here https://github.com/microsoft/playwright/issues/1732#issuecomment-611787788. Of course is bit dirtier, but it will work until there is some decision from @aslushnikov or @JoelEinbinder :)

**Comment by dizzyn** [comment]
Yes yes, please simple export the interfaces like "PageWaitForSelectorOptions", "PageClickOptions"... to allow us to do some abstractions. Thank You

**Comment by dbjorge** [comment]
We're also hurting for some of these as we migrate from a previously-Puppeteer test corpus that uses lots of helper functions that wrap assorted Puppeteer functions.

So far, it hasn't generally been too bad to apply the `Parameters<...>` workaround, with the notable exception of the `PageFunction<Arg, R>` type that `Page.evaluate` and its friends use as a first parameter. This particular type is problematic to pull out using the `Parameters<...>` workaround because every point where it's used is both overloaded and generic, and it's not something I'm thrilled about redefining ourselves because it relies on the quite complex `Unboxed` type. It would be really helpful to make an exception for `PageFunction` and `Unboxed`, specifically. In the meantime, if anyone has any bright ideas for type wizardry to pull out those types without repeating the `Unboxed` definition, I'd love to hear them :)

I'll echo @dizzyn that `PageWaitForSelectorOptions` and `PageClickOptions`, specifically, were the two interfaces that we used most often in our wrappers, so they might also be worth making usability exceptions for, though both of them are trivial to apply the `Parameters<...>` workaround for.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
