### ISSUE TITLE
[Feature] More granular control of trace file generation through a maxTraces flag.

### ISSUE THREAD

**Issue by damongabrielle** [microsoft/playwright#27551]
Trace files are enormously helpful in debugging failed tests. However they chew up a ton of disk space depending on how many tests failed. If things fail catastrophically and you're not setting a value for maxFailures you could generate a Gig or so of traces.

To avoid filling up disk space, we've "resorted" to setting maxFailures to a specific number. The downside of this of course is don't get the full picture of test status. 

I wish that I could pass a `maxTraces` flag that would let me set the maximum number of trace files to generate before it automatically shuts off trace file generation. For example if `--maxTraces=10` and `trace: on-first-retry` were set, then after 10 trace files were generated, it would disable `on-first-retry` and cease generating trace files for subsequent failed tests in that run. This would allow me to debug these 10 failures BUT also give me the visibility of how the rest of test results look as well.

Alternatively I could also see value in having a flag that lets you set the maximum amount of disk space you'd like to allocate to trace files. Possibly `--maxTraceStorage` might track how many Megabytes of tracing is filled. After it hits the set threshold, it stops generating traces because that's as much as I'm willing to store.

These features seems really beneficial especially in kubernetes environments where we really prefer to avoid allocating disk and prefer to rely on primarily ephemeral disk if possible. This would help us stick to a rough default disk budget per execution.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
