### ISSUE TITLE
[Feature] need edge in ie mode in playwright

### ISSUE THREAD

**Issue by KesabKC** [microsoft/playwright#27590]
Hi team ,  i tried to run edge in ie mode but it is not working . Is it possible to add the edge in ie mode feature to run using playwright?. We have to automate our application in ie mode to run correctly. Kindly let me know on this.
If any other solution is available also much appreciated.
Thanks

**Comment by mxschmitt** [comment]
Supporting IE Mode is outside of the scope for Playwright. We recommend updating your web-apps so they work with modern browsers.

**Comment by dinesh-bay** [comment]
We automate OpenText / Micro Focus ALM (formerly HP ALM / Quality Center), where most of the UI is ActiveX rendered only in Edge IE mode; Playwright works cleanly for the Chromium-compatible components (Site Admin, Web Runner / Web Client, Global Search, Quality Insights) but cannot reach the ActiveX slice because Edge IE mode runs on Trident (MSHTML), outside Playwright's Chromium / Firefox / WebKit surface. 

Our fallback there is UiPath, and costs roughly two months of engineering time per ALM version upgrade. We understand IE mode is retired tech and that Microsoft has committed to IE mode only until at least 2029, so we are not asking for full Trident support — just either an officially documented pattern for driving the Chromium tabs inside an IE-mode-enabled Edge session via Playwright (attach, coexist with an IE-mode tab), or a formal docs pointer toward Selenium 4 + IEDriverServer with the Edge ie. edgechromium = true flow, so enterprise teams stop re-raising this request.
