### ISSUE TITLE
[Feature] New Assertions - toEndWithText, toStartWithText

### ISSUE THREAD

**Issue by mmorris8** [microsoft/playwright#27663]
The JavaScript String object has startsWith() and endsWith() methods, and it would be nice to have matching complimentary methods in the assertions list for many of the same reasons. For example, the start of URL's can change depending on the server. We can use the contains method which is analogous to String.includes(), but the proposed methods are just a bit more exacting.

Example useage

```
expect(await page.getByText("Get Care").getAttribute('href')).toEndWithText('/get-care/')
```

Also, this is the sort of low hanging fruit issue I think I could tackle myself and issue a pull request on if the concept is accepted.

**Comment by yury-s** [comment]
Looks like RegEx value already covers these scenarios:

```js
await expect(page.getByText("Get Care")).toHaveAttribute('href', /\/get-care\/$/);
```
does it work for your use case?

**Comment by mmorris8** [comment]
The argument "just use regex" isn't very persuasive.  Why bother with the existing containsText method? Or half a dozen other methods that regex can do the job for.  I respect the power of regex, but I also recognize it is one of the most difficult parts of programming to master and hardly a suitable replacement.  It's like calling assembly a replacement for C#. Yeah, technically...

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
