### ISSUE TITLE
[REGRESSION]: deviceDescriptors: expected array,got undefined

### ISSUE THREAD

**Issue by keerthireddy1012** [microsoft/playwright#27687]
Browserstack connection used to work in 1.38.1 version but it is not working in 1.39.0 version

I am trying to run through Jenkins and facing the same issue. Even though i downgrade the version it is showing same error in Jenkins.
NEED FIX as soon as possible

Based on your previous comments, tried to restart visual studio but still same error.

**Comment by mxschmitt** [comment]
This is a browserstack issue, since they don't provide 1.39.0 yet on their infrastructure. We recommend downgrading to v1.38.0 until they have 1.39.0 available. 

Make sure to not put "^1.38.0" in your package.json. It needs to be "1.38.0" otherwise it will install latest.

See https://github.com/microsoft/playwright/issues/27566#issuecomment-1759353411.
https://github.com/microsoft/playwright/issues/27576
https://github.com/microsoft/playwright/issues/27586
