### ISSUE TITLE
[Feature] Set bypassCSP for existing context

### ISSUE THREAD

**Issue by ngugcx** [microsoft/playwright#27696]
```
const browser = await chromium.connectOverCDP(`http://127.0.0.1:9876`)
const context = browser.contexts()[0]
const page = await this.driver.newPage()
```
I'm using playwright to connect to a running chromium. 
There is no way to set bypassCSP for the default context or pages created by it. 

If creating new context, bypassCSP can be passed as an option, but it's a new window without plugins.

**Comment by qasamppa** [comment]
Voting +1 for this.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by alanalanlu** [comment]
+1 on this
