### ISSUE TITLE
[BUG] PWA crashes with "aw snap" (UI mode and Trace Viewer)

### ISSUE THREAD

**Issue by zerock54** [microsoft/playwright#27788]
Hello,

My tests are running fine in headless and headed mode but whenever, i try to open the generated traces, the PWA crashes and I have no logs expect the "Aw snap" Chrome screen. 
In the Trace Viewer, the crashes seem to occur when I hover something like a step or an item in the timeline.
The UI mode crashes during the test run.

If I import the trace with Firefox it does not crash but my Mac give me an out of memory warning

I have noticed that my CPU load goes quite high in UI mode so I guess it is performance related.
The inspector runs fine however.

### System info
- Playwright Version: [v1.39.0]
- Operating System: [macOS 13.4]
- Browser: [Chromium]

**Config file**

```js
// playwright.config.ts
import {defineConfig} from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['html'], ['list'], ['json', {outputFile: 'test-results.json'}]],
  use: {
    baseURL: 'http://localhost:4200',
    trace: 'on',
  },
  projects: [
    {
      name: 'chrome',
      use: {
        channel: 'chrome',
        launchOptions: {
          args: ['--start-maximized'],
        },
      },
    },
  ],
});

```

**Comment by zerock54** [comment]
More details that might be interesting:

I am using a components library built with StencilJS in my webapp. Stencil injects an inline style tag to the <head> section of my HTML page for each component. As the components have a lot of different styles, these tags are quite big and, when i look at the trace file content, i can see that some lines are very very heavy as they seem to contain the whole styles tags:

<img width="1105" alt="image" src="https://github.com/microsoft/playwright/assets/7101750/c9c2c7cf-7be9-44f2-9a8f-80b68f84f7db">

**Comment by yury-s** [comment]
Can you share the trace file that is crashing the browser?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by hadson172** [comment]
@yury-s We are using stencil.js as well and experience same issue. 
We wanted to migrate our apps from cypress to playwright but it seems it is impossible because trace viewer does not works correctly.

What is working:
- opening traces files with browser (like Firefox)

What is not working:
- running playwright with `-ui` - test passes correctly, then it is laggy and fails with "aw snap" - out of memory

This is a blocker for our migration, probably all of our projects are affected by this. (all our apps are cypress based, everything work fine). I found more bug reports like this.

@yury-s probably you can understand but we cannot share our company's internal data so it is impossible to upload traces.

Is there any possibility to increase memory in this trace viewer or something ?

**Comment by Egor-Koldasov** [comment]
I wonder if there is any workaround. I don't have many tests, but I have this issue very often on m3 macbook

**Comment by ScarletMcLearn** [comment]
Facing similar issue: https://github.com/microsoft/playwright/issues/36337

**Comment by ScarletMcLearn** [comment]
@zerock54, @hadson172 , @Egor-Koldasov   please do give it a look and suggest if you faced your issue under similar conditions!
