### ISSUE TITLE
How to Run Multiple test files parallelly  in CI/CD? 

### ISSUE THREAD

**Issue by biswasritu6** [microsoft/playwright#27837]
Hi Team, 

Currently, I have automated 200 apps, and each test file has an average of 10 test cases.  
While running all the apps parallelly using workers 10 - 12 apps are failing, but the same apps are passing for individual runs.

can anyone guide me, on how I can run all the test files parallelly in different ways in CI/CD? 
And 
How to run multiple test folders at the same time parallelly so that all test runs in a short span of time?

**Comment by yury-s** [comment]
Looks like there are several separate questions here:

> While running all the apps parallelly using workers 10 - 12 apps are failing, but the same apps are passing for individual runs.

Most likely your tests/app are not ready for the parallel execution and compete for a shared resource. If you think there is a bug in Playwright, please provide a repro, so that we can help you.

> can anyone guide me, on how I can run all the test files parallelly in different ways in CI/CD?

See [this page](https://playwright.dev/docs/test-parallel), you can increase number of workers to improve parallelism on single machine and [shard the tests](https://playwright.dev/docs/test-sharding) across multiple machines. [GitHub example](https://playwright.dev/docs/test-sharding#github-actions-example) may be particularly interesting.

> How to run multiple test folders at the same time parallelly so that all test runs in a short span of time?

Playwright, already parallelizes tests by default, see https://playwright.dev/docs/test-parallel for different ways to adjust it. In some cases you might benefit from [fullyParallel](https://playwright.dev/docs/api/class-testproject#test-project-fully-parallel) mode within files.

Closing this issue as there is no action on playwright end. If something specific does not work when you follow the docs, please open a new issue with a repro.
