### ISSUE TITLE
[BUG] Hover state is not displayed in traceviewer After tab

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#27932]
### System info
- Playwright Version: 1.39
- Operating System: Mac
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  use: {
    trace: 'on',
  },
  reporter: [['html', { open: 'never' }]],
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
 test('is a test', async ({ page }) => {
    await page.goto('http://the-internet.herokuapp.com/hovers');
    await page.getByRole('img', { name: 'User Avatar' }).first().hover();
    await page.waitForTimeout(3000);
  });
```

**Steps**
- npx playwright test
- Observe the hover() step in the trace file generated

**Expected**

- The hover() state (i.e. name and view profile) should show in the "After" tab so that I know my hover worked.

**Actual**

- The hover() state (i.e. name and view profile) doesn't show in the "After" tab so that I know my hover worked.

Here is what I see (in the below screenshot When I clicked on hover step, in the after tab the screenshot should show what happened on hover):
<img width="883" alt="Screenshot 2023-11-02 at 10 27 39 AM" src="https://github.com/microsoft/playwright/assets/22205721/8f1d1cda-f5ab-42e9-b792-127d4644c2fe">

**Comment by pavelfeldman** [comment]
This would be hard to implement...

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
