### ISSUE TITLE
[Suggestion] Unify launch() and launchPersistentContext() options

### ISSUE THREAD

**Issue by Niek** [microsoft/playwright#2794]
Right now the `launch()` and `launchPersistentContext()` calls support different options. The latter one supports the following options that are missing from the first one:
- acceptDownloads
- ignoreHTTPSErrors
- deviceScaleFactor
- isMobile
- hasTouch
- javaScriptEnabled
- timezoneId
- geolocation
- locale
- permissions
- extraHTTPHeaders
- offline
- httpCredentials
- colorScheme

Is there any specific reason that these two do not share the same options? Especially some options like `userAgent` would be quite useful to support in the regular `launch()` call.

**Comment by aslushnikov** [comment]
@Niek There's a concept of "contexts" in playwright: https://playwright.dev/#version=v1.1.1&path=docs%2Fcore-concepts.md&q=browser-contexts

There's the following difference between the `browserType.launch()` and `browserType.launchPersistentContext()` methods:
- The `launch` method launches a browser, that can later be used to create contexts. All the options you mention here are part of `browser.newContext()` method.
- The `launchPersistentContext` create a browser context backed by a user profile directory. It's a *context*, not a *browser*.

So if you have a browser launched with `browserType.launch()` method, you can later create new contexts with `browser.newContext()` method. The `browser.newContext()` has all these options you mentioned.

Hope this helps!

**Comment by Niek** [comment]
Thanks for your reply. I am aware of that, I think it's just strange the the "standard" `launch()` call which creates a default context doesn't support the same options.

**Comment by aslushnikov** [comment]
> I think it's just strange the the "standard" launch() call which creates a default context doesn't support the same options.

@Niek but `browserType.launch()` doesn't create default context 🤔 It creates [browser](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=class-browser) instead. Do I misunderstand something?

**Comment by Niek** [comment]
> > I think it's just strange the the "standard" launch() call which creates a default context doesn't support the same options.
> 
> @Niek but `browserType.launch()` doesn't create default context 🤔 It creates [browser](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=class-browser) instead. Do I misunderstand something?

@aslushnikov OK, I didn't explain myself well. The situation now is:
- `browserType.launch()` supports limited options, returns Browser
- `browserType.launchPersistentContext()` supports all options, returns BrowserContext
- `Browser.newPage()` supports all options
- `BrowserContext.newPage()` supports no options at all

In my opinion this is quite confusing, why can't `launch()` support the same options and have `Browser.newPage()` calls extend the options provided in `launch()`?

**Comment by yury-s** [comment]
There are several separate operations that the API methods do:
1. Launch a browser, 
1. Create a context in the browser,
1. Create a page in the context.

Some of the methods perform two out of these operations internally and hence take parameters to both:

* `browserType.launch()` just launches the browser => takes only browser params
* `browserType.launchPersistentContext()` launches the browser with user data directory _and_ creates `persistent` context. Takes browser and context params. Primary reason this method includes context creation is that there can only be one persistent context in a browser and it doesn't make sense to return browser instance separately in this case.
* `Browser.newPage()` this is just a _convenience_ method which creates a new context and then a new page in it. It takes parameters for the new context (as `BrowserContext.newPage` itself doesn't take any additional parameters).

We could probably go one step forward and allow passing _default_ context parameters to `launch()` so that they could be used to call `Browser.newPage()` without parameters but the benefits seem small while adding context parameters to `launch()` could confuse the users of the main path (i.e. launch(), newContext(), newPage()).

**Comment by Niek** [comment]
OK, I understand the reasoning.

But if you ask me, a more logical API design would have been to add all options to `launch()` and return a `BrowserContext` right away, I can't think of a reason to launch a browser without the need for a context. If it would be structured like this you wouldn't need a `Browser.newPage()` method which is confusing anyway. Since [the docs](https://playwright.dev/#version=v1.1.1&path=docs%2Fintro.md&q=first-script) suggest the `launch().newPage()` method, that would be a more logical flow IMHO. Just my 2 cents 😄

**Comment by yury-s** [comment]
> I can't think of a reason to launch a browser without the need for a context. 

That's a fair point, there is little reason to launch browser if you are not going to create a page in it :smile: The rationale for the Browser/Context/Page API is that `BrowserContext` is what we consider the primary isolation mechanism between different test cases. In the common case we expect Playwright to be used in a test suite where the tests could share same browser instance (for performance reasons) while create separate browser contexts and have their own network, geolocation, locale, timezone etc parameters isolated between the test cases (each would use its own context).

> Since [the docs](https://playwright.dev/#version=v1.1.1&path=docs%2Fintro.md&q=first-script) suggest the `launch().newPage()` method, that would be a more logical flow IMHO. Just my 2 cents

Yeah, `Browser.newPage` was added to make life easier for the people with muscle memory from Puppeteer and so that newcomers could start prototyping sooner without having to learn extra concept of `BrowserContext`.
