### ISSUE TITLE
[Question] Playwright Trace Viewer as a self-hosted service in Kubernetes

### ISSUE THREAD

**Issue by StasGrishaevTutu** [microsoft/playwright#27952]
Good afternoon ! I raised Playwright Trace Viewer as a service in a kubernetes cluster and I want to be able to open traces in it via the GET parameter, as it is indicated here - https://playwright.dev/docs/trace-viewer#viewing-remote-traces
The service is launched with an HTTPS route and works correctly for manually uploading the trace, but when I try to upload the trace via the GET parameter, the page simply reloads (see video)
Also, when I try to upload a trace this way, I see strange 404 errors in network requests, perhaps this is somehow connected. I am attaching the entire session as a har file - https://raw.githubusercontent.com/StasGrishaevTutu/files/main/playwright-trace-viewer.har
I also attach screenshots of the Dockerfile and entrypoint.sh of how the service is raised in kubernets.
What am I missing here?
![image](https://github.com/microsoft/playwright/assets/115224622/999a7df1-75ad-4df3-8a58-a749ee9b1012)

https://github.com/microsoft/playwright/assets/115224622/80cee601-0324-4236-baf6-de1aebeeed81

**Comment by MindaugasMateika** [comment]
Interesting approach. What I am doing is deploying just built trace to Kubernetes instead of using whole Playwright docker image. Basically you could create Playwright report and then just take trace folder from it and deploy it as a web server. That works for me.

**Comment by StasGrishaevTutu** [comment]
> What I am doing is deploying just built trace to Kubernetes instead of using whole Playwright docker image.

@MindaugasMateika could you please give a bit more details on this ? 

> Basically you could create Playwright report and then just take trace folder from it and deploy it as a web server.

Actually I'm using [Allure TestOps](https://qameta.io/) as a report service and try to figure out, how can I attach URI to self-hosted PW trace viewer service there :)

**Comment by MindaugasMateika** [comment]
Ah, basically if you enable traces and generate Playwright html report then in report folder will be a trace folder which is self contained trace viewer that you can deploy. I think that's the easiest way to get trace viewer but it would be possible to get it from node modules as well. I guess the issue you're getting stems from the entrypoint you're using.

**Comment by StasGrishaevTutu** [comment]
@MindaugasMateika got it, I’ll also try to look at attaching an PW html report in Allure TestOps, thanks ! 
Nevertheless, I’m not closing the question yet, perhaps PW team can suggest something about it.

**Comment by mxschmitt** [comment]
The manifest.webmanifest seems unrelated, it should not cause any issues.

It redirects here:

<img width="901" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/2fc402ce-4eea-4001-a8b6-2141f9ca146a">

via the actual web-server which serving the request. Which is us where we don't keep the searchParams for / redirects. I created a fix for it here: https://github.com/microsoft/playwright/pull/27956

If you use instead this, it would work:

https://playwright-trace-viewer.tutu.rc.rus.tutu.pro/trace/index.html?trace=...

As per above we recommend different things:

- Playwright HTML report contains trace viewer and a lot of more reporting, in the ideal world you upload the playwright-report folder after each test-run to some storage server e.g. S3 and then paste a link to your GitHub PR, thats what we are doing at Playwright see [here](https://github.com/microsoft/playwright/pull/27460#issuecomment-1749594954).
- Self hosting the Trace Viewer is also an option. You can either get the latest Trace viewer by looking at your NPM package folder, building it yourself or doing show-trace like you do. In your scenario the Docker image is quite large, since its our Docker image which includes browsers etc. so a normal Node.js alpine Docker image would work as well and is probably just 200MB large compared to 1GB.

I hope that helps!

**Comment by StasGrishaevTutu** [comment]
@mxschmitt thanks for the detailed answer! the option with the address `playwright-trace-viewer.tutu.rc.rus.tutu.pro/trace/index.html?trace=...` gives me a slightly different picture, namely a 500 error in the network request. Perhaps there is some problem with CORS or the fact that the link I am sending does not contain the zip extension? Just in case, I'll attach the updated har file (https://github.com/StasGrishaevTutu/files/raw/main/playwright-trace-viewer_2.har) and screenshot.
![image](https://github.com/microsoft/playwright/assets/115224622/1cf9d017-4493-4db2-9819-3c88eeef7996)

**Comment by pavelfeldman** [comment]
Could you help me triaging this issue? Is this a bug or a feature request?

**Comment by StasGrishaevTutu** [comment]
@pavelfeldman I think that most likely the problem is on my side and I configured something or am doing something wrong, I don’t think it’s a bug.

**Comment by mxschmitt** [comment]
I recommend to scroll a bit more down in DevTools. You should find the request to your trace file (which might be not a trace) and see if it succeeded (2xx status code) or not. Also Console might yield more helpful output.

**Comment by StasGrishaevTutu** [comment]
ok, I'll keep trying. I'll close it while I'm searching, I'll post if I get something :)
