### ISSUE TITLE
[Feature] page.evaluate shouldn't throw a new error ?

### ISSUE THREAD

**Issue by kapouer** [microsoft/playwright#27999]
```js
try {
 await page.evaluate(() => {
  return asyncThatThrows();
 });
} catch(ex) {
 // not the original exception here, it would be nice if it was, or at least, if it was accessible
}
```

**Comment by dgozman** [comment]
@kapouer Could you please be more specific? `page.evaluate()` will re-throw the error that was thrown by the evaluated code. It would not be the same error instance, because code runs in the browser vs in the node.js, but it should have the same error message at least. What exact functionality are you missing?

**Comment by kapouer** [comment]
It somewhat rewrites the error message (prepends "Evaluate" to it), and loses additional custom error fields.
Let alone keeping the stack trace, it might be nicer if it was more faithful to the initial error message.

**Comment by dgozman** [comment]
@kapouer If you could share a repro that illustrates some particular information that is lost, we might be able to fix it.
