### ISSUE TITLE
[feature] Flag for running only test files with snapshots within them

### ISSUE THREAD

**Issue by kkortes** [microsoft/playwright#28012]
I often find myself running `yarn playwright test` with expectation for a bunch of snapshots to differ.

Before I run it with `--update-snapshots` I want to have a brief look on the differences that took place, to see what changes to the code base did.

When doing this, running tests that _doesn't include snapshots_ is redundant and just adds a lot of extra time to running the tests.

What I do now is searching for `.toHaveScreenshot` globally in the project and taking note of all file names where its included. After that I run: `yarn playwright test fileA fileB fileC` but it's a time consuming process.

Suggestion:
```
yarn playwright test --has-snapshots
```

Sidenote: why is both words "snapshot" and "screenshot" used within playwright?

**Comment by dgozman** [comment]
@kkortes In general, Playwright cannot know whether the test is matching a snapshot without running it.

As a heuristic, we can look for any snapshots present in a location that we expect them to be at, but that would certainly fail for newly added tests where expectations are not generated yet.

Additionally, `snapshotPathTemplate` complicates things, because it can do weird things wrt the location of the snapshot.

I'll leave this feature request open for more feedback/prioritization.

**Comment by kkortes** [comment]
I figured that'd be the case @dgozman.

Since playwright knows which directories to look for playwright-files in would it be a good idea to parse file contents for `.toHaveScreenshot`?

I've been thinking of setting this up myself and pipe the file names to the `playwright test` command.

Mabye you feel like this kind of operation is out of the scope of what playwright is meant to do/be responsible for?

**Comment by kkortes** [comment]
I must've confused myself since I posted a identical issue in 2024:
https://github.com/microsoft/playwright/issues/29986

Closing this issue. Tags are a fine solution for this purpose. Otherwise I can refer to doing some file content scan myself and piping it to the `playwright test` command.

Thanks to everyone involved.
