### ISSUE TITLE
[Feature] addInitScript for Worker

### ISSUE THREAD

**Issue by doehyunbaek** [microsoft/playwright#28029]
Hi. We are currently working on a project that needs to monkey patch calls to [WebAssembly.instantiate()](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiate) and [WebAssembly.instantiateStreaming()](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiateStreaming). 

We have quite successfully done so using [addInitScript](https://playwright.dev/docs/api/class-page#page-add-init-script) api for main page, but I'm quite struggling to monkey patch calls inside worker.

Our main problem is that monkey patching worker is possible after initialization code of worker is evaluated, not before.

For example(example with Math.number for simplicity):

```ts
page.on('console', msg => console.log(msg));
  await page.addInitScript(monkeyPatch);
  // such api does not exist
  // await worker.addInitScript(monkeyPatch);
  
  // while initializing the worker, the monkey patch is not applied.
  await Promise.all([
    page.waitForEvent('worker'),
    page.goto('http://localhost:5173/')]);
  const worker = page.workers()[0];
  
  // this works but comes too late.
  await worker.evaluate(monkeyPatch);
  expect(await page.evaluate(() => self['workerFunction']())).toBe('42');
  expect(await worker.evaluate(() => self['workerFunction']())).toBe('42');
```

running above program, there's a initialization code of worker that utilizes the self['workerFunction']. This does not use monkey patched version that returns 42 as in last line, but uses the original one, returning some random number.

I made a repo that showcases the above problem to a [repo](https://github.com/doehyunbaek/monkeypatch-worker).

If these kinds of functionality is already supported, sorry for inconvenience and close the issue.

If not, I am planning to work on such features. It would be great if you let me know any technical reason why it is not appropriate or any pointers to get the implementation done.

**Comment by dgozman** [comment]
@doehyunbaek This feature is not supported today. I think implementing it the same way as `page.addInitScript()` would be really involved, because it would require changes in all three browser engines we support.

However, I think you can work around this issue by [routing the main worker script](https://playwright.dev/docs/mock#modify-api-responses). Something like this:

```ts
const mockScript = `
  self.WebAssembly = ...;
`;

await page.route('**/worker-script.js', async route => {
  const response = await route.fetch();
  const script = await response.text();
  await route.fulfill({ response, body: mockScript + script });
});
```

Let me know whether this helps.

**Comment by doehyunbaek** [comment]
This works like a charms! Thanks for your insight.

If the change is involved, would it help if I contribute a documentation PR?

As this case has a suitable workaround, if you feel it is appropriate to do so, feel free to close the issue.

Again thanks for your help.

**Comment by dgozman** [comment]
> If the change is involved, would it help if I contribute a documentation PR?

Absolutely! I think adding something to [this page](https://playwright.dev/docs/api/class-worker) would be great.

**Comment by jakobgetz** [comment]
Another reason why `worker.addInitScript()` is useful:
Let's say I want to execute code before each worker on arbitrary websites of which I have no knowledge about the internals. In that case using a hack like this will not work in a satisfying way, since it will yield a lot of false positives and false negatives:
>```
> await page.route('**/*.js', async route => {
>   const response = await route.fetch();
>   const script = await response.text();
>   await route.fulfill({ response, body: mockScript + script });
> });
>```

---

I also want to extend the scope for this issue a little bit:
In general a function like `addInitScript` would be useful in a lot of different contexts. Currently `page.addInitScript()` seems to only execute for the browsers main thread, hence for the top level frame. It would be nice to have that method available basically for every "thread" (or context) a webpage can run, in particular for every worker but also for every frame(, etc?). Concretely `frame.addInitScript()` would be useful as well.
Spinning this even further one could add an api to obtain handles to all the threads a webpage runs and then call `addInitScript()` on them. Maybe like this:
```
const threads: (Frame | Worker)[] = page.getThreads()
threads.addInitScript(script)
```
Let me know what you think.

**Comment by flen201** [comment]
addition would be nice...

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by jackfromeast** [comment]
Is there a way to inject scripts before new frames or worker context, like @jakobgetz described here?
