### ISSUE TITLE
[Feature] Support transparent PDFs like the JavaScript/TypeScript package and Pupeteer

### ISSUE THREAD

**Issue by Benexx** [microsoft/playwright#28063]
It is implemented for `page.ScreenshotAsync()` by settings the `OmmitBackground` to `true` but there is no such option for `page.PdfAsync()`.

In the JS library there is support for `page.setBackgroundColor()` (see [wiki](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/chromium/crPage.ts#L261C9-L261C84)) but this is not supported by .NET (at least I don;t see any documentation or workaround to get this to work.

Puppeteer does support [omitBackground](https://pptr.dev/api/puppeteer.pdfoptions) in the `.pdf(options)`.

I don't see a way to send the message myself (all the channels/connections are internal).

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
