### ISSUE TITLE
[QUESTION] Is there any problem with using same storagestate with multiple workers?

### ISSUE THREAD

**Issue by cortosi** [microsoft/playwright#28095]
Hello Guys.. 

Is there any problem if i use the same storage state with multiple workers?
I asked because, if I run the tests in parallel, the first tests run without a problem, but after 5/6 tests run the remaining ones fail because the session seems to have expired. In fact, if I look at the videos recorded by playwright (on failed tests) I notice that the browser takes me to the login page and therefore it is as if the storagestate no longer works.

By chance, if I have to work with multiple workers, do I need an account for each worker?
Thank you in advice for the answers.

**Comment by Az8th** [comment]
If no server-side changes made during your tests can alter other ones, you should be good to go.
Otherwise, you should definitely use an account for each worker (see the [docs](https://playwright.dev/docs/auth#moderate-one-account-per-parallel-worker))

Also, do you logout in one your tests (hence revoking your token) or does your token have a short expiration by any chance ? It may explain this behaviour.

**Comment by larsheylen** [comment]
I encountered something similar while testing a platform that automatically logged users out after a minute if the user closed all tabs (so the token has a short expiration time as @Az8th mentioned).  The localstorage typically has a lastActive key and it is possible that the platform you are testing uses this to check if your localstorage is still valid. I got around this problem by changing the value of lastActive to the current time at the start of each test and using the localstorage as follows in each test:

```
browserContext = await browser.newContext({storageState: resetLocalstorage(`localstorage.json`)});
page = await browserContext.newPage();
```

Maybe doing something similar will solve your problem.

**Comment by mxschmitt** [comment]
> Is there any problem if i use the same storage state with multiple workers?

This highly depends on your application, if the application and the way the application does authenticate always re-generates tokens and invalidates the previous one, then this won't work.

Since this is no feature request / bug report, I recommend reaching out to folks on Discord, since this is only for bugs.

**Comment by sriram-kothapalli** [comment]
I’m facing a similar issue:
I'm running the same tests with different test data, reusing the same authentication by cloning the session based on the worker index. However, a few tests fail immediately after completing the e-signature step.

Even though I’m not explicitly logging out, the session is getting kicked out of the UI on 2 workers, while it continues to work fine on 1 worker.

Please help me resolve this issue.

 

` test.beforeAll(async ({ browser }, tInfo) => {
        testInfo = tInfo;
        ({ admin, operator, auditor, qa, serialNumber, deviceType, EquipmentInfo } = testInfo.project.metadata);
        const workerId = testInfo.workerIndex;
        const defaultState = path.resolve(`storageStates/auth-${operator.username}.json`);
        const workerState = path.resolve(`storageStates/auth-${operator.username}-${workerId}.json`);

        if (!fs.existsSync(workerState)) {
            fs.copyFileSync(defaultState, workerState);
        }

        context = await browser.newContext({ storageState: workerState });
        page = await context.newPage();
        await page.goto('/', { waitUntil: 'domcontentloaded' });
    });
`
