### ISSUE TITLE
[QUESTION] - Missing trailing Semi-Colon in Single Cookie using addCookie

### ISSUE THREAD

**Issue by Thaweesak-sai** [microsoft/playwright#28125]
INFO: Playwright Version: [v1.37.1]

I'm currently working on a project where I'm utilizing the addCookie function to add a single cookie. However, I've noticed that the added cookie doesn't contain a semi-colon.

Here's the sample code I'm using:

>`await page.context().addCookies([{name: 'test', value: '{"val1":true, "val2":false}', url: 'http://www.example.com/'}]); `

and from trace viewer I can see in the Request Header Cookie section as
`Cookie: test={"val1":true,"val2":false}` without trailing semi-colon

Shouldn't the resulting document.cookie string contain a semi-colon to denote the end of the cookie? Or am I misunderstanding how the addCookie function works?

Thank you in advance.

**Comment by mxschmitt** [comment]
In HTTP headers, cookies are separated by semi-colons when multiple cookies are sent. However, when you're adding a single cookie using Playwright's `addCookies` method, the absence of a trailing semi-colon is expected behavior. The semi-colon is used as a delimiter only when there are multiple cookies. The browser and server correctly interpret the single cookie without a trailing semi-colon. Your `addCookies` usage is correct and should function as intended.

Same is the case for document.cookie.

How do you parse the cookies?

**Comment by Thaweesak-sai** [comment]
I found that there is an issue with how I'm handling the cookies. Currently, I'm using semi-colons as delimiters. However, if there are no semi-colons, I fall back and use commas as delimiters instead and it will have issue with a single cookie in object format.

Thank you for your response 🙏🏼 .
