### ISSUE TITLE
[Feature] What is the status of the release of a container compatible with OpenShift for Playwright?

### ISSUE THREAD

**Issue by tejaswikommineni** [microsoft/playwright#28131]
we would like to know when will the playwright will be available in the openshift.

As of now we are manually deploying it in openshift.so pain point is each time we have to deploy for every release.

**Comment by mxschmitt** [comment]
You can use our [official Docker container](https://playwright.dev/docs/docker) in conjunction with OpenShift templates.

The is nothing specifically else needed in order to make Playwright OpenShift compatible, as long as you are using the official OS Debian/Ubuntu or use our Docker image, things will just work.

Does this answer your question?

**Comment by mxschmitt** [comment]
Closing as per above.
