### ISSUE TITLE
[BUG] Component testing. Adding component test causes changing typescript behavior in all project

### ISSUE THREAD

**Issue by Giorno-Giovana** [microsoft/playwright#28147]
### System info
- Playwright Version: [v1.39.X]
- Operating System: [All]
- Browser: [All]
- Other info: "@playwright/experimental-ct-vue": "^1.39.0"

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/Giorno-Giovana/playwright-typescript-node-bug

**Steps to reproduce**
- Run `yarn serve`
- You will get `ERROR in src/App.vue:12:22
TS2365: Operator '+' cannot be applied to types 'Timeout' and 'number'.
`
- Commet all lines in `src/components/bug.spec.ts`
- All typescript errors disappears

**Comment by mxschmitt** [comment]
I was able to reproduce this. This seems unfortunately more like an issue in Vue CLI. I would recommend ignoring the Playwright Tests in your tsconfig.json under the exclude section.

---

Also keep in mind that Vue CLI is in maintenance mode, since they recommend Vite nowadays which most likely does not have this issue.
