### ISSUE TITLE
[Feature] is it possible to use it with jest 

### ISSUE THREAD

**Issue by sultan-arshi** [microsoft/playwright#28158]
Basically, I am working on a project and some of the tests already have written using `jest` i.e `expect` and I want to use `Playwright/test` in this project with no change in previous tests or a little change in them 

is it possible ?

**Comment by Huzaima11** [comment]
+1

**Comment by mxschmitt** [comment]
We strongly recommend using our test-runner since it gives you features like HTML Reporter, Retries, VS Code integration, UI Mode, Fixtures, etc. what other testing frameworks won't offer. Also @playwright/test works with TypeScript out of the box, supports trace-viewer out of the box and applies context per test best-practise to have them isolated and self contained.

So yes it is possible, but the experience will be significant worse.

Closing as per above.
