### ISSUE TITLE
[BUG] `test.fail(true)` will not pass if failure is caused by `.waitFor*()` function timeout

### ISSUE THREAD

**Issue by samijaber** [microsoft/playwright#28222]
### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
test('should pass', async ({ page }) => {
    test.fail(true);

    await page.goto('https://www.google.com');

    // this will cause a failure
    await page.waitForSelector('text=somerandomstring');
    // this will cause a failure
    await page.getByText('somerandomstring').locator('visible=true').waitFor();
    // this will pass
    await expect(page.getByText('somerandomstring')).toBeVisible();
  });
```

**Steps**
- Run the test
- test will fail until both `.waitFor*` commands are commented out

**Expected**

I would expect timeout errors caused by `.waitFor*` functions to be ignored when `test.fail(true)`.

**Actual**

`test.fail(true)` only "allows" `expect()` failures to pass. 

Let me know if my understanding of this feature is wrong!

**Comment by rob4629** [comment]
Do you believe setting `test.fail(true)` should ignore _ANY_ failure? I feel like tests could get into a broken (/_useless_) state if that were the case, whereas limiting it to just assertions can be more targeted/intentional.

Just commenting to provide an opinion, and follow along with any discussion.

**Comment by mxschmitt** [comment]
This sounds unexpected, I can repro. We'll look into it.

**Comment by mxschmitt** [comment]
Turns out this is working as expected as per https://github.com/microsoft/playwright/issues/9373#issuecomment-938161218. You should make your test fail before the test timeout has reached.

waitForSelector has a timeout of 0 by default, so you should reduce it if you expect a failure.
If expect() fails before the test-timeout has reached, it gets marked as passing.

**Comment by samijaber** [comment]
@mxschmitt I would like to bring this issue back up, because I still regularly struggle with it in my day-to-day.

Full context: 
- I have 8 SDKs for web frameworks (Vue, React, Svelte, Solid, Qwik, etc.) that are identical in functionality
- each SDK is tested in multiple servers (Nextjs, Remix, Nuxt, Vite, etc). 
- I have a large Playwright parametrized test suite running against each of the above servers that import these SDKs. 

Not all servers pass all tests: I am in the process of fixing bugs/adding feature coverage. I want to track which tests are falling for which parameters, to make sure I enable the tests when the bugs are fixed. This is why I rely on `test.fail(condition)` instead of `test.skip(condition)`.

However, according to this github issue, someone in my situation is unable to use the entirety of `waitFor*` helpers in Playwright, because then I cannot expect test failures.

This makes using playwright tricky, because I have to either: 
- constantly avoid a good chunk of Playwright's API 😓
- use `test.skip(isSDKFoo)` and hope that I remember to enable the tests when I fix the bug for `isSDKFoo`

What would your advice be for someone in my situation?

**Comment by zacc** [comment]
@samijaber , did you consider using  [overriding fixtures](https://playwright.dev/docs/test-fixtures#overriding-fixtures)  to override the default behaviour of failing on timeouts?  

I am in a similar predicament. In my case I have a click handler that has regressed and does nothing, so the wait to interact with the next element fails. I don't want to modify the test case (by adding a workaround) and `fixme` has the disadvantage you described, so I am adding arbitrary expects to my page object to cause the failing test to 'pass' but without modifying the test case.

I can see both sides of the argument for changing this behaviour. However I think Playwright tests specifically are so oriented around waits that in practical use we consider a waitFor timeout as equivalent to an expect failure. To be able to use `test.fail` as it's coded now we need to change waits to be expects.

**Comment by samijaber** [comment]
What I do right now is that whenever I have a test that expects to fail and it uses `waitFor*`, I make sure to add an appropriate `expect` before the problematic `waitFor*` so that the `expect` triggers the failure early.

**Comment by zacc** [comment]
@samijaber that's exactly what I'm doing too 👍

**Comment by vexx32** [comment]
@mxschmitt I understand y'all consider this "expected behaviour" but that severely limits the actual usefulness of `test.fail()`

_Almost every recommendation_ for Playwright assertions in the documentation very pointedly notes that any non-timeout-based `expect` calls will likely be quite flaky and to always prefer timeout-based assertions. This makes sense. But--

As a result, any decently well-written test _will not_ be able to use `test.fail`, leaving us in this situation where it is essentially useless without rewriting the test to fail early.

This makes it semantically quite similar to `test.fixme`, because the test then likely _will not_ ever pass without being rewritten. `test.fail` barely has a use case, in this way.

Suggestions/options I think make more sense:
- Remove `test.fail`
- Make it another alias for `test.fixme` and `test.skip`
- Change `test.fail` to accept timeouts (and likely shorten the default timeout as it's expected to fail anyway; I'd suggest perhaps 1/5th the default timeout set, as an inverse of `test.slow`)

Personally I think the last makes plenty of sense, and a documentation note can be added that tests failing due to timeout will likely cause slower CI if there are large numbers of expected failures, and to either rework the tests or mark them as `fixme` instead to avoid the issue.
