### ISSUE TITLE
[BUG] download with fulfill routing fails

### ISSUE THREAD

**Issue by ruifigueira** [microsoft/playwright#28253]
### System info
- Playwright Version: v1.40.0
- Operating System: Windows 11
- Browser: Chromium
- Other info:

When trying to download an intercepted request with a fulfill routing, it fails.

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```js
test('should download successfully when routing with fulfill', async ({ page }) => {
  await page.route('**/index.html', route => route.fulfill({ body: `<a href="/download.txt" download="download.txt">download</a>`, contentType: 'text/html' }));
  await page.route('**/download.txt', route => route.fulfill({ body: 'Hello world', contentType: 'text/plain' }));
  await page.goto(`http://localhost/index.html`);
  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.click('a'),
  ]);
  expect(await download.failure()).toBeFalsy();
});
```

**Expected**

Should pass the test

**Actual**

- Chrome:

```
Error: expect(received).toBeFalsy()


Received: "canceled"
    at tests\test-4.spec.ts:23:36
```

- Webkit:

```
Error: page.waitForEvent: Test timeout of 60000ms exceeded.
```

**Comment by yury-s** [comment]
What is your use case for intercepting downloads, are you testing if browser download logic works as expected?

**Comment by ruifigueira** [comment]
Yes, I want to mock a downloaded file and `route.fulfill` is a great way to mock server data and I even use it as a static content server as explained here:

https://github.com/microsoft/playwright/issues/13968#issuecomment-1784041622

I expected it would work normally in those scenarios (it works just fine for everything else), so I was surprised it didn't work for downloads.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
