### ISSUE TITLE
[Feature] Provide recommended system requirements in terms of CPU & memory

### ISSUE THREAD

**Issue by Laurens-makel** [microsoft/playwright#28261]
We are currently comparing Playwright with Cypress to make an educated decision which tool to use for running E2E tests in our Azure Pipeline. 

I've been browsing the documentation to find the recommended amount of memory & CPU to assign to the CI machine for an optimised test run but could not find any recommandations.

The Cypress documentation clearly mentions what the recommend amount of CPU & memory is, ideally the Playwright documentation should provide similair innformation and ideally specify how much CPU & memory is recommended per worker.

**Comment by yury-s** [comment]
Are you looking for guidance on the minimal resource requirements or something more general?

Playwright test runner will try to spawn optimal number of test workers depending on number of CPU cores your machine has. Browser memory footprint will vary depending on the application you are testing.

**Comment by Laurens-makel** [comment]
> Are you looking for guidance on the minimal resource requirements or something more general?
> 
> Playwright test runner will try to spawn optimal number of test workers depending on number of CPU cores your machine has to optimize resource utilization. Browser memory footprint will vary depending on the application you are testing.

It would be nice to describe the minimal resource requiremennts but also provide detailed information about the way Playwright will spawn optimal number of test workers.

For example, it would be helpful to gain insights in what you gain/lose when you add/remove CPU power to the machine. How many extra workers could I expect per how much CPU added, how much memory should I allocate per worker, etc 

I definitely understand that memory totally depends on the application under test but some generic guidelines could be provided.

**Comment by yury-s** [comment]
We recommend our users try running their tests and adjust resource allocation based on the actual performance of the tests. There is no one-size-fits-all solution. It doesn't matter what the minimal RAM requirement for launching a browser with about:blank is if your application will eat up 2Gb on load. You can follow browser recommendations regarding resource requirements (for those which provide those). Some people would won't to increase number of [parallel workers](https://playwright.dev/docs/test-parallel#worker-processes), but it won't work for everybody. Current allocation strategy is roughly number of workers = number of cores / 2, so that you have a core per browser and core per test worker.

Closing this issue as we are not planning to publish such minimal hardware requirements.
