### ISSUE TITLE
[Feature] Option to not record console messages in the trace

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#28281]
For applications that produce a lot of console messages, recording them in the trace slows everything down and inflates the trace size a bit.

Perhaps a boolean option, or a message text filter (regex?) would be helpful.

See also #20626.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
