### ISSUE TITLE
[Feature] Compile browsers for ARM

### ISSUE THREAD

**Issue by jimkang** [microsoft/playwright#2838]
I think it would be great if Playwright included browsers compiled for armv7 processors.

The reason I'm asking for it is that I'm trying to move my image-generating art programs to run on a Raspberry Pi, which rely on headless browsers to take screenshots of web pages. However, being able to run CI or web scrapers on Pis or other low-powered devices would probably help quite a few people, especially those without access to high-power cloud VPS instances.

(This is a follow up to #2834.)

**Comment by pavelfeldman** [comment]
This is outside of the scope of the Playwright project, but we are happy to help those with the necessary tool chains to build browsers for Playwright. WebKit and Firefox building instructions are a part of this repository, Chromium instructions are available upstream.

**Comment by ebourmalo** [comment]
Thank you for the update @pavelfeldman
I'd be also interested to compile the firefox binary but I can't find any building instructions as you mentionned `WebKit and Firefox building instructions are a part of this repository`.
Since playwright uses a custom version of firefox, is there any way to compile ourselves the binary for arm please?

**Comment by dbghb** [comment]
+1 for me as well. Giving instructions on how to compile the browser binaries for other platforms would increase the possible user base.

**Comment by arjunattam** [comment]
@ebourmalo, build scripts are in the repo. You can start by reviewing the buildbots that generate browser builds today: https://github.com/microsoft/playwright/tree/master/browser_patches/buildbots
