### ISSUE TITLE
[BUG] Restart Debug button ends the debug session instead of restarting it

### ISSUE THREAD

**Issue by ilorwork** [microsoft/playwright#28399]
**Context:**
- Playwright Version: 1.40.0
- Operating System: Windows
- Node.js version: 20.9.0
- Visual Studio Code version: 1.0.19
- Playwright for VSCode extension version: 1.84.2
- Browser: Chromium

**Code Snippet**
Any test

**Describe the bug**
Pressing the restart debug button ends the debug session instead of restarting it:
![Restart debug button screenshot](https://github.com/microsoft/playwright/assets/84942383/54845f0f-a0ba-4b58-9ec7-62552cc1322f)

This occurs on the extension's previous versions too,
updating it didn't solve the problem.

**Comment by ilorwork** [comment]
Hey.
Is there any updates on this issue?

**Comment by ilorwork** [comment]
Any updates?
@mxschmitt @pavelfeldman

**Comment by juliancastroorozco** [comment]
any?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by ilorwork** [comment]
@pavelfeldman This is a bug not a feature.
Features can be closed due to upvotes limitation, but upvotes and interest should be irrelevant for bugs.

**Comment by tansaku** [comment]
since this issue has been reported and closed twice, I have re-opened it linking back to this issue https://github.com/microsoft/playwright/issues/32655 - I love VSCode, but this gets in the way of my workflow over and over again (almost as much as the limited size in the terminal windows)

**Comment by ilorwork** [comment]
https://github.com/microsoft/playwright/issues/32655#issuecomment-2357823019
