### ISSUE TITLE
Uploading Files is not working on Selenium grid

### ISSUE THREAD

**Issue by mridiniveni** [microsoft/playwright#28402]
Hi I tried with 1.40  version now i see the size of the file is 46 KB  but some how its unable to upload the file please check below screenshot
page.locator(locator).setInputFiles(new FilePayload("sampleTest.pdf","application/pdf","this is sample pdf ;".getBytes(StandardCharsets.UTF_8)));

<img width="566" alt="image" src="https://github.com/microsoft/playwright/assets/113676808/81cbcd7b-8df8-4d01-805a-780e67523bb9">

_Originally posted by @mridiniveni in https://github.com/microsoft/playwright/issues/28081#issuecomment-1825745403_

**Comment by pavelfeldman** [comment]
@dgozman: action item here is to make it clear that the support for Selenium Grid is experimental and issues like this are unlikely to be resolved.

**Comment by mridiniveni** [comment]
Thanks for immediate response at the moment   i see issue in my local execution itself with FIlePayLoad .

**Comment by SaravananRavi** [comment]
Hi Team, Can you please fix this FileUpload isssue in the next release as it is blocking our entire automation activities and we are not able to move forward.

**Comment by mridiniveni** [comment]
Any update on this issue?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
