### ISSUE TITLE
[BUG] expect(page).toHaveScreenshot() does not wait for timeout

### ISSUE THREAD

**Issue by Schepetkov** [microsoft/playwright#28470]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Windows 10, Windows 11]
- Browser: [All]

### Source code
```
import { test, expect } from "@playwright/test";

test("screenshot bug", async ({ page }) => {
  await page.goto("https://playwright.dev/");

  //await page.locator(".toggle_vylO.colorModeToggle_DEke").click();
  await expect(page).toHaveScreenshot({ timeout: 10000 });
});
```

**Repository:**
https://github.com/Schepetkov/Playwright

**Steps**
- [Run the test]

**Expected**
I expected that the toHaveScreenshot method would retry taking and comparing screenshots until the time specified in the timeout option expires, or until a match is achieved. For example, if I set timeout to 10000, I expected that the method would work for up to 10 seconds before throwing an error.

**Actual**
However, the actual behavior of the toHaveScreenshot method may differ from the expected one. The toHaveScreenshot method may ignore the timeout option and fail with an error after the first attempt or within a very short time, for example, 597 milliseconds.

**For more information please look:**
<img width="1650" alt="ScreenshotBug" src="https://github.com/microsoft/playwright/assets/29506847/18492efa-6f9f-4f4c-9274-754de6386e4b">

**Comment by pavelfeldman** [comment]
Please refer to the method doc: https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1

**Comment by MindaugasMateika** [comment]
It retries taking screenshot until two consecutive screenshots yield same result and then compares, it does not retry comparison between actual vs expected.

**Comment by greenarrowdb** [comment]
I know this issue is closed, but if this behavior is working as designed there should be some consideration to updating the main playwright docs for clarity. https://playwright.dev/docs/test-assertions claims that the _assertion_ will get retried here for 10 seconds. A casual reading implies that the assertion to retry is the one between expected and actual, not an internal assertion about taking the same screenshot twice. I would even say that the specific documentation for `toHaveScreenshot` does not call that out clearly enough and is worded somewhat vaguely. This behaviour has been a bug bear for my team before finding this and is very misleading.

**Comment by sovetski** [comment]
The issue is closed but I am getting the same problem with the version 1.48.2

**Comment by Iaotle** [comment]
The docs still haven't been updated to reflect that this is the behavior 😞
