### ISSUE TITLE
[BUG] Component Testing from the docs does not work

### ISSUE THREAD

**Issue by dhaval-javia** [microsoft/playwright#28471]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:
- React V - 18.2.0

**Steps**
- [Create new react project using cra]
`npx create-react-app test-app`
- setup Playwright component testing
https://playwright.dev/docs/test-components
`npm init playwright@latest -- --ct`
- Create Test file as per the docs.
- Run the Test

**Expected**
Component test should work fine
[Describe expected behavior]

**Actual**
Giving ReferenceError: exports is not defined.

![image](https://github.com/microsoft/playwright/assets/122977029/e6497937-6436-4c19-a20a-084c5228cede)

**Comment by dgozman** [comment]
@dhaval-javia I followed your steps, and there is an error indeed, but it's a different one.

```
ReferenceError: test is not defined
   at src/App.test.js:4
```

This is because `create-react-app` created an `App.test.js` file with some other tests, but Playwright picks it up due to a similar naming convention. When I remove this file, `npm run test-ct` works as expected.

Let me know whether this helps.

**Comment by dhaval-javia** [comment]
@dgozman Did you try replacing the code with the playwright one??

`import { test, expect } from '@playwright/experimental-ct-react';
import App from './App';

test.use({ viewport: { width: 500, height: 500 } });

test('should work', async ({ mount }) => {
  const component = await mount(<App />);
  await expect(component).toContainText('Learn React');
});`

**Comment by dgozman** [comment]
> Did you try replacing the code with the playwright one??

I did follow the steps in the bug description, including pasting an example, and everything works for me. I am also not sure how do you get the screenshot above. The example test opens a 500x500 browser window, and there are no errors in the console.

**Comment by dhaval-javia** [comment]
Can you share the sample repo that's working for you? @dgozman

**Comment by dgozman** [comment]
@dhaval-javia I don't think we should be doing that. There are plenty open-source repositories that use playwright component testing already. Following the documentation also works.

**Comment by dhaval-javia** [comment]
Thanks, Will try out the demo code again. see if  it works

**Comment by dj0024javia** [comment]
So it turns out, its giving error on ubuntu 23.10 as its some OS related issue. Works fine on Windows 10.
@dgozman

**Comment by dgozman** [comment]
@dhaval-javia Ubuntu 23.10 is not officially supported yet. Take a look [at this doc](https://playwright.dev/docs/intro#system-requirements) for the supported configurations.

Since you've got this working, I'll close the issue. If you still encounter problems, please file a new issue and link to this one.
