### ISSUE TITLE
[BUG]Screen and snapshot of beforeAll missed when trace mode is set to "retain-on-failure"

### ISSUE THREAD

**Issue by Myron-Huang** [microsoft/playwright#28527]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [macOS 13.5]
- Browser: [Chromium]
- Other info:

### Source code
Here is the test code:
```
import {Browser, BrowserContext, chromium, expect, Page, test} from '@playwright/test'

test.describe('test', () => {
    let browser: Browser
    let context: BrowserContext
    let page: Page

    test.beforeAll(async () => {
        browser = await chromium.launch()
        context = await browser.newContext()
        page = await context.newPage()
        await page.goto("https://www.google.com/")
        await page.getByRole('button', { name: 'Google Search' }).waitFor()

    })

    test.afterAll(async () => {
        await page.goto("https://www.bing.com/")
    })


    test('TESTXX', async () => {
        await page.goto("https://playwright.dev/docs/intro")
        expect(0).toEqual(1)
    })
})
```

**Steps**
- Set trace mode to "retain-on-failure"
- Run "TESTXX" and wait it failed
- Show trace and check html-report

**Expected**
I can see all snapshots and screenshots in my "beforeAll", "test", "afterAll"

**Actual**

I can only see snapshots and screenshots in "test" and "afterAll", those in "beforeAll" is empty like this:
![image](https://github.com/microsoft/playwright/assets/153153942/743c42d8-6b0d-4fe7-b3f8-dc03868fc8fb)

**Other**
If I set trace mode to "on", all works ok, so I think this is a bug of "retain-on-failure"

**Comment by vilgeforc5** [comment]
Is there any solution?

**Comment by petarku** [comment]
is there any update on this issue or workaround. we are facing the same on our project and it is quite annoying that you cannot see screen and snapshot on setup of the tests and all tests are broken afterwards. we have limited space on jenkins machine so we dont want to set to always on

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
