### ISSUE TITLE
[Feature] Add .all as property of expect()

### ISSUE THREAD

**Issue by larsheylen** [microsoft/playwright#28549]
I would like to be able to assert that e.g. all buttons on a page are enabled without having to loop over all buttons. Something like the following would be nice: 
`await expect({locator pointing to multiple DOM elements}).all.toBeEnabled();`

To achieve this now, I would have to do something like the following:
```
for (const locator of {locator pointing to multiple DOM elements}.all()) {
    await expect(locator).toBeEnabled();
}
```

The use would be similar to the `.not` property already present on those assertions.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
