### ISSUE TITLE
[BUG] Clicks/Codegen does not work with Flutter (canvas rendered) 

### ISSUE THREAD

**Issue by sgondala** [microsoft/playwright#28583]
### System info
- Playwright Version: [1.40.1]
- Operating System: [macOS]
- Browser: [Chromium]
- Other info: This is a flutter website. There are few ongoing Issues on flutter websites (#26587) 

### Source code

**Steps**

1. Open codegen for the website  - https://flutter.github.io/samples/web/material_3_demo/
2. Capture any click

**Expected**

As the website is fully inside `canvas` tag, the expected behavior (#6737, #9503) is to print x/y coordinates in codegen. 

**Actual**

Codegen generates 

```
await page.locator('flutter-view').click();
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by larsbloch** [comment]
@sgondala 

Im having the same issue. Did you find a workaround ?

**Comment by cuervotux** [comment]
Same problem here!
