### ISSUE TITLE
[Question] get extra information from expect construction for report.

### ISSUE THREAD

**Issue by Aroot42** [microsoft/playwright#28622]
Hello.
I use playwright + [monocart reporter](https://github.com/cenfun/monocart-reporter) and want to know how possibly get extra information from expect construction for report?
- expect status
- expected value
- actual value
![image](https://github.com/microsoft/playwright/assets/100360547/adc1d330-b11a-4c45-8ea2-99b3c976a175)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
