### ISSUE TITLE
[BUG/FEATURE] Missing @playwright/test in playwright Docker image?

### ISSUE THREAD

**Issue by codinkai** [microsoft/playwright#28621]
### System info
- Other info:
-- Docker image: docker pull mcr.microsoft.com/playwright:v1.40.0-jammy

### Source code

```
% cat tests/example.spec.js 
import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects page to have a heading with the name of Installation.
  await expect(page.getByRole('heading', { name: 'Installation' })).toBeVisible();
});
```

**Steps**

```
docker run -it --rm -v ./tests:/tests --ipc=host mcr.microsoft.com/playwright:v1.40.0-jammy npx playwright test
Need to install the following packages:
playwright@1.40.1
Ok to proceed? (y) y
Error: Cannot find module '@playwright/test'
...
```

**Expected**

- No installation of playwright as it is a playwright container
- Module @playwright/test is found

**Actual**

- playwright needs to be installed
- module @playwright/test needs to be installed

**Comment by mxschmitt** [comment]
The Playwright Docker images don't contain any NPM libraries which is expected. They contain only the browsers and system dependencies to run the browsers as per [here](https://playwright.dev/python/docs/docker). Its up to the user to install @playwright/test with the preferred package manager.

**Comment by codinkai** [comment]
Unfortunately, the documentation does not provide a proper example on how to run a playwright test. It only shows how to enter the bash console of the container.

_The Playwright Docker images don't contain any NPM libraries which is expected._
Why is it expected? I do not understand and I haven't found a good explanation yet.

**Comment by mxschmitt** [comment]
Usually you use Docker in a more CI like environment where you have your usual steps like git checkout, npm install, npm run build, npm run test. This is why we did not add any documentation for how to use it locally. The CI providers do it usually like GitHub Actions or CircleCI. We did not include the library in the image since we act as a base image rather than a image which you can immediately use (Node.js package managers install dependencies in different locations etc. - we don't want to be opinionated there, so we didn't add it). Regarding the steps on how to use it, we recommend following getting started an the Docker documentation website, maybe using Docker is not the right fit for you too, if you let us more know about your situation, we can give more suggestions!

**Comment by codinkai** [comment]
Thank you for your explanation. We are using playwright docker in CI environment. We did it as you described, but it felt so wrong to install playwright in a playwright container.

We will build our custom container with the latest playwright-npm modules installed. Our use case is just to mount a volume with tests and start the tests, without any installation. 

By the way, having the modules pre-installed probably reduces network traffic. Might be worth considering.

**Comment by kicktipp** [comment]
I agree to @uglow and @codinkai  
Its difficult to get it running without proper examples and installing playwright in a playwright container feels wrong.
