### ISSUE TITLE
[BUG] Playwright not able to click an element

### ISSUE THREAD

**Issue by Sharathkumarcp** [microsoft/playwright#28668]
### System info
- Playwright Version:"^1.38.1"
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

Please find the 
<img width="156" alt="playwright" src="https://github.com/microsoft/playwright/assets/63232044/9010c612-848e-459d-affa-7fbe4964b352">
![image](https://github.com/microsoft/playwright/assets/63232044/bb97c3cf-9680-449e-b0c1-a6aea1056d52)

In My case upon right clicking we get a option to view edit and delete an entry in the table 

We are able to right click but not able to click on the view,edit and delete option
below is the code:

await page.locator(commonUtil.getRSNObject("TheHospitalSiteSelected").replace('value', this.RegisteredSiteHospitalName.HosName)).click({ button: 'right' });
            const det = await page.locator(commonUtil.getRSNObject("EditSiteOption"))
            console.log(det.isVisible())
            await det.click();
            
         Output: TimeoutError: locator.click: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('xpath=//span[text()=\'edit\']')

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by mxschmitt** [comment]
We unfortunately need a reproduction in order to debug issues like this. The error suggests, that there is no element with the given locator on the page. For that we recommend codegen/trace viewer to debug these issues yourself. So you see how the website behaved at the point in time when the error occurred. Feel free to re-file if you have a website you can share. Thanks for your understanding!
