### ISSUE TITLE
Soft update of HAR files [Feature]

### ISSUE THREAD

**Issue by dalv-happy** [microsoft/playwright#28695]
In Playwright there are 2 types of working with mocks:
- `update: false` – when we read mocks
- `update: true` – when we rewrite mocks

It seems that a third type of mock update is needed. This is the add mode. In this mode, Playwright would understand which endpoints are missing and record them.
Let me give you an example. I am loading the main page with advertising banners.
Since I am not satisfied with the link to the first banner, I go to HAR and change the link. After that I add click on the first banner, click on it and wait for the page to load. When I'm running the test for the second time I want the mocks not to be overwritten, but to add new endpoints to HAR of the opened page

**Comment by yury-s** [comment]
let's collect more feedback on this request. As a workaround for now you can either record a new har file if the page starts accessing new endpoints or add another `page.routeFromHar` that would record all requests not handled by existing har file. The latter would have the downside that you'd now have two har files to route from.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
