### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rickiesystem1** [microsoft/playwright#28722]
### System info
- Playwright Version: latest
- Operating System: [macOS 13.2]
- Browser: [Mobile Chrome, Chromium, WebKit]
- Other info:

### Source code

```js

import { Page } from "@playwright/test";

export async function checklyGoto(page:Page, inputString:string, options = {}) {
  const baseUrl = process.env.baseURL || 'https://phoenix-integration.aws.mapquest.com';
  const combinedUrl = new URL(inputString, baseUrl).toString();
  await page.goto(combinedUrl, options);
}

  test('@P0 Search result maintains after clicking other map pin result and going back ', async ({ page }) => {
    await checklyGoto(page, "/search/new%20york%20downtown%20pizza", { waitUntil: "domcontentloaded" });

    await page.waitForSelector('.maplibregl-map  img.marker-img', { state: 'visible' });
    await page.getByRole('img', { name: 'Friendly Gourmet Pizza' }).click();
    await page.waitForTimeout(3000);
    const firstUrl = page.url();

    await page.waitForSelector('.maplibregl-map  img.marker-img', { state: 'visible' });
    await page.getByRole('img', { name: 'Traditas Pizza' }).click();
    await page.waitForTimeout(3000);
    const secondUrl = page.url();

    expect(firstUrl).not.toEqual(secondUrl);

    await page.goBack({waitUntil: "domcontentloaded"});
    await page.waitForTimeout(3000);

    const urlAfterBack = page.url();
    expect(urlAfterBack).toEqual(firstUrl);
  });
```

**Steps**
- npx playwright test

**Expected**

test always pass

**Actual**

sometime fails,

**Comment by yury-s** [comment]
There is probably something wrong with the test and it fails due to a race condition. Instead of relying on timeouts please follow our [best practices](https://playwright.dev/docs/best-practices#use-web-first-assertions) and use web assertions such as [toHaveUrl](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-url) to check the page url, as it will auto-wait for the condition. If it doesn't help, try recording [a trace](https://playwright.dev/docs/trace-viewer-intro) and see what is not working as expected. If you deem it's due to a bug in Playwright, please file a new issue with a repro, detailed steps and a description of what is not working as intended.
