### ISSUE TITLE
[BUG] Error: mouse.wheel: Mouse wheel is not supported in mobile WebKit

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#28755]
### System info
- Playwright Version: "@playwright/test": "^1.36.2",
- Operating System: mac
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

seeing an error. please advise how to handle it, do we have a fix for the issue?

[BUG] Error: mouse.wheel: Mouse wheel is not supported in mobile WebKit

**Comment by yury-s** [comment]
As the error says, this is currently not supported in mobile mode in WebKit.

**Comment by InduKrish** [comment]
May i know when the support will be added to support mouse.wheel in mobile webkit? wondering if there is a solution until we have the actual fix.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
