### ISSUE TITLE
[Feature] Auto-wait should wait until all xhr are completed

### ISSUE THREAD

**Issue by maybee** [microsoft/playwright#28765]
The current actionability checks on elements, does not handle, if there is a pending xhr request on the site. 

This can end up in a changed DOM, if the script making the xhr call, modify the DOM

Playwright executes the action to early, and ends up in an error, because the DOM isn't as expected

Either auto-wait should wait until all xhr request is fullfilled, or it should be possible to implement a custom kind of actionability checks.

Currently I have to use a waitfor method between all steps, to ensure the xhr requests are fullfilled.

**Comment by yury-s** [comment]
If Playwright were to wait for outstanding XHRs, it could wait indefinitely if there are long-standing XHRs, so this is not feasible. We recommend testing [user-visible behavior](https://playwright.dev/docs/best-practices#test-user-visible-behavior) and use web assertions to auto wait instead of relying on some internal logic like current XHRs.
