### ISSUE TITLE
[BUG] `browser.cache.disk.parent_directory` of  `firefoxUserPrefs` doesn't work.

### ISSUE THREAD

**Issue by liuhui-eb** [microsoft/playwright#28822]
### System info
- Playwright Version: [>=v1.34]
- Operating System: [Ubuntu 22.04]
- Browser: [Firefox]
- Node Version: [v16.17.0]
- Other info: Playwright version < v1.34 works well.

### Source code
```node
import {firefox} from 'playwright-firefox';

let firefoxUserPrefs = {
  'browser.cache.disk.parent_directory': '/home/harley/Documents/GitHub/playwright_test/disk_cache',
};

const browser = await firefox.launch({
  headless: false,
  firefoxUserPrefs: firefoxUserPrefs
});
console.log("==== playwright.launch done ====");
const context = await browser.newContext();
await context.newPage();
```

**Steps**
- After Firefox launches, visit the `about:config` and `about:cache` pages.

**Expected**
- In the `about:config` page, the `browser.cache.disk.parent_directory` should be set as `/home/harley/Documents/GitHub/playwright_test/disk_cache`.
- In the `about:cache` page, the `Storage disk location` of the `disk` part should be set as `/home/harley/Documents/GitHub/playwright_test/disk_cache`.

**Actual**
- In the `about:config` page, the `browser.cache.disk.parent_directory` is set as `/home/harley/Documents/GitHub/playwright_test/disk_cache`.
![image](https://github.com/microsoft/playwright/assets/104953935/3455d148-bf1e-44a4-a2ad-6e7a00a6919d)

- In the `about:cache` page, the `Storage disk location` of the `disk` part is not set as `/home/harley/Documents/GitHub/playwright_test/disk_cache`.
![image](https://github.com/microsoft/playwright/assets/104953935/8a063438-2b5c-4cac-8309-761924b88352)

**Comment by liuhui-eb** [comment]
I have read the source code of branch `release-1.33` and `release-1.34` and I'm wondering if it's caused by this PR: https://github.com/microsoft/playwright/pull/22998.
I think this PR may set the config of Firefox after Firefox launches, but the cache setting should be set before Firefox launches or Firefox needs to be re-launched.

**Comment by DemonMartin** [comment]
+1 encountering same issue atm.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by webee** [comment]
I want to share disk cache between all runs, so this is really a problem.
