### ISSUE TITLE
Upload files to S3 bucket using presigned urls

### ISSUE THREAD

**Issue by Teddy937** [microsoft/playwright#28821]
I recently met a situation where I need to upload files to s3 using presigned urls but I found no documentation about this on official playwright documentation.

**Comment by mxschmitt** [comment]
Playwright acts like a normal user, the user usually does not know about uploading with a s3 presigned link. Instead you can either specify a path or a payload.

If I understand your question correctly, you either want to upload a file which lives on a S3 bucket, then you need to download it beforehand (using any http client) or you just use your application logic in order to upload it see [here](https://playwright.dev/docs/input#upload-files).

Please elaborate more on your scenario, thanks!

**Comment by Teddy937** [comment]
First of all these are playwright rest api tests. So we don't have UI here. And documentation also to upload the files in rest api is not quite clear or unless I didn't find it correctly. So my scenario am calling an endpoint which returns an s3 presigned url which is used  to upload file(s) to s3. Then I will use that presigned url as an endpoint with file as payload when uploading to s3. So thats where I have a challenge

**Comment by mxschmitt** [comment]
I see, since you upload files with the API client, [this](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-post) should help you. Since I don't know how your API looks like, the payload/http method/headers might be something which are different. Maybe the [AWS SDK](https://www.npmjs.com/package/@aws-sdk/client-s3) is also a better fit to interact with your S3 storage. If its just about making a POST/PUT request to the pre-signed URL, then [the examples](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-post) should work for you.

Do you have documentation which you can share with us? This would help a ton - since I struggle right now to understand the full picture.

**Comment by Teddy937** [comment]
`const filePath = path.join(__dirname, 'galleryImage.jpg');
    const file = fs.createReadStream(filePath)
    const attempt = await axios
      .put(presigned.resource.url, {
        headers: {
          Accept: 'application/json',
          ContentType: 'multipart/form-data',
          withCredentials: false,
        },
        data: {
          filePng: {
            name: filePath,
            buffer: file,
            mimeType: "image/jpg",
          },
        },
      })`
      
      This is how I finally did it. It seems to work fine. Thank you for the support
