### ISSUE TITLE
[BUG] Page.route URL matching is broken for IPv6 literals

### ISSUE THREAD

**Issue by BranislavBajuzik** [microsoft/playwright#28836]
### System info
- Playwright Version: 1.40.0
- Operating System: [All]
- Browser: [All]

### Source code

- [x] I provided an exact source code that allows reproducing the issue locally.

```python
from playwright.sync_api import sync_playwright

# Set up a localhost server that serves HTML at /page with a #button that just calls http://[::1]:3000/some-request

base_url = "http://[::1]:3000/"

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page(base_url=base_url)
    page.goto("/page")
    
    with page.expect_request("/some-request") as request_info:
        page.locator("#button").click()
    
    browser.close()
```

**Expected**
The request is captured as the `base_url` + "/some-request" matches what is called

**Actual**
The request gets ignored

### Explanation
In the `playwright._impl._helper.URLMatcher.__init__` the `base_url` gets prepended to the `"/some-request"`. It is then passed to the `fnmatch.translate` function and compiled as regex, which produces the following regex: `'(?s:http://[::1]:3000/some-request)\Z'`. This is incorrect, as the `[::1]` gets interpreted as "matches a single character in the list :1 (case sensitive)". 

#### Solution
Somehow prepend the base_url after the `fnmatch.translate` using `re.escape`

**Comment by NoamAnisfeld** [comment]
The root cause seems to be in the function [globToRegex](https://github.com/dgozman/playwright/blob/656209689c78778ed99a9499ef28eaa1244aebad/packages/playwright-core/src/common/netUtils.ts#L139) which doesn't escape square brackets when converting route URLs into regexes. The set of characters to escape (defined right above the function) should be modified to escape the characters `[`, `]` and `-`.

In addition, it might be desirable to modify the function [urlMatches](https://github.com/dgozman/playwright/blob/656209689c78778ed99a9499ef28eaa1244aebad/packages/playwright-core/src/common/netUtils.ts#L107) so that it doesn't convert literal strings to regexes unless certain characters (namely `*`, `?`, or `{`) are included in it.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by rpodgorny** [comment]
@SarthakNikhal are you still interested in working on this? let's get this fixed when upstream obviously doesn't care...
