### ISSUE TITLE
[Question] Enable More Verbose Logging for CI

### ISSUE THREAD

**Issue by savovuk-x** [microsoft/playwright#28844]
### System info
- Playwright Version: v1.39
- Operating System: Ubuntu Docker Gitlab CI
- Other info: Node 20, Angular, Angular Dev Server, WebServer

### Question
Hello there 👋

I am currently adding playwright to my ci and I am encountering a problem with the webserver config that one can set to have a development server running for the tests. 

Locally everything runs fine and i can use the webserver config but when running on the ci it tells me that the port is already in use. I checked with netstat but it shows nothing. 

My question is, can I enable more logs to maybe see if there is some misconfiguration on my side? Or if anybody experienced something similar?

Currently I add following option `DEBUG=pw:webserver npx playwright test` but the logs seem to be still very little can I add more options there?

**Comment by mxschmitt** [comment]
Hello! `DEBUG=pw:webserver npx playwright test` is our recommendation for debugging issues like that. It gives you stdout/stderr and the reasons why things end up like that.

Since the port is already used, we don't have many more information which we could print except that. Have you tried using a different port? Have you tried to narrow it down to a reproducible which you can share with us? This would help us a ton in order to debug this issue.

**Comment by savovuk-x** [comment]
Hey thanks for the fast answer is it possible to chain multiple `DEBUG` statements? like `DEBUG=pw:webserver,api` ?

**Comment by mxschmitt** [comment]
Yes, e.g. DEBUG=pw:browser,pw:api,pw:webserver

but since your WebServer is not able to start, a browser never gets launched, so pw:api won't produce anything.

**Comment by savovuk-x** [comment]
Thanks for the info. I've found the culprit it was due to the fact that my ci image was misconfigured and it used a proxy even for localhost requests. 

Anyways thanks for your time 😊
