### ISSUE TITLE
[Feature] Need drag and drop support ASAP

### ISSUE THREAD

**Issue by AnshPatel15** [microsoft/playwright#28853]
It's been 2 months since the Pull Request for drag and drop in Codegen was made and I have been patiently waiting for this implementation. We require drag-and-drop support for our playwright project as a necessity. Please look into this. I know I am not the only one since this feature keeps getting requested! We would appreciate your efforts on this one!
It is extremely tough to visualize mouse drags on a full page canvas to manually use mouse.up(), mouse.move() and mouse.down() 

Thank you!

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/19892 since its about the codegen drag'n drop integration. Normal drag'n drop support is available in Playwright as per [here](https://playwright.dev/docs/input#drag-and-drop).

Unfortunately we cannot commit on any eta for specific features. Thanks for your understanding.
