### ISSUE TITLE
[Feature] Show test steps test.step in ui mode and in the plugin 

### ISSUE THREAD

**Issue by HamzaMiz** [microsoft/playwright#28861]
Hello 
When i create test steps i want to see them in the ui mode before excuting the test to understand what does the test do and in the plugin also if possible 

<img width="925" alt="Screenshot 2024-01-04 at 14 45 34" src="https://github.com/microsoft/playwright/assets/94066399/cb3120ae-c7f9-4e3e-ac2b-e94f8eb86de0">
As u can see in the picture the actions list is empty , u only see the steps after the execution of the steps 
I suggest  to  add the list of steps in a new tab next to actions with title Steps and it will be the first tab by default  before execution it will enhance the user experience especially for people who will start the project and they don't know what the tests does  .
[
<img width="391" alt="Screenshot 2024-01-04 at 14 53 48" src="https://github.com/microsoft/playwright/assets/94066399/0880fdee-c42c-49ec-91d5-4bda8eb6c700">
]
When the user excute the test the tab action will be in the focus 
And thanks

**Comment by mxschmitt** [comment]
Thanks for your suggestion! We fully understand that this would be a helpful feature to have. However, due to the dynamic nature of how Playwright executes tests, displaying steps beforehand is technically challenging. Test steps are determined in real-time during execution, making prior visualization complex without running some part of the test in advance.

For now, we recommend running your tests once to have the test steps shown in UI mode.

Thanks for using Playwright!

**Comment by HamzaMiz** [comment]
hey max , thanks for fast reply , i based my suggestion on test.describe and test , the text is displayed before exécution so i thought it will be the same ^^
