### ISSUE TITLE
[BUG] Chromium 'notifications' permission does not work

### ISSUE THREAD

**Issue by ThisIsBenny** [microsoft/playwright#28865]
### System info
- Playwright Version: 1.40.1
- Operating System: MacOs 14.1.2
- Browser: Chromium
- Other info:

### Source code

Config
```
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  reporter: "html",
  use: {
    trace: "on-first-retry",
    permissions: ["notifications"],
  },

  projects: [
    {
      name: "Mobile Chrome",
      use: {
        ...devices["Moto G4"],
      },
    },
  ],
});
```

**Steps**
- Open a App which requires Push Notification permissions
- Check Browser Console

**Expected**
No error and permission is granted (or an option to run test in none Incognito mode, see below)

**Actual**
Tests failed because App detects that no permission is give.
Reason for that is that the Tests are running in Incognito mode and push notification permissions are denied in Incognito mode.

Error in the Console:

![image](https://github.com/microsoft/playwright/assets/66417262/08fbcde4-a180-4e06-9b3c-1767a53a635e)
https://bugs.chromium.org/p/chromium/issues/detail?id=401439

Remark:I created this new ticket because the already existing one is closed: https://github.com/microsoft/playwright/issues/5631

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
