### ISSUE TITLE
[BUG] Cannot wait for the animation to complete before triggering the click event

### ISSUE THREAD

**Issue by FrankWang117** [microsoft/playwright#28909]
### System info
- Playwright Version: [v1.31.2]
- Operating System: [macOS 13.5]
- Browser: [Chromium]
- Other info:

### Source code
```ts
// click 
await page.locator(`flow-property-custom-select[label="property"] .thy-select-custom`).click();
selectedPropertyName = 'someText';
// close the select popover by click option
await page
    .locator('.thy-option-item')
    .filter({ hasText: 'someText})
    .click();
// and open the other select popover
await page.locator(`flow-property-custom-select[label="操作"] .thy-select-custom`).click();
// Because the previous selection popup has animation, it results in obtaining the quantity of two popups
expect(await page.locator('.thy-option-item').count()).toEqual(6);
```
![image](https://github.com/microsoft/playwright/assets/21688648/bb9dfdd8-6750-4c6f-b986-7dd1ef18b580)

like this.

**Expected**
I hope to start clicking the next select box only after the completion of the previous animation.

**Actual**

The closure of the previous popup and the opening of the current popup occur simultaneously.

**Comment by dgozman** [comment]
@FrankWang117 I am not sure we can help you much here. Note that Playwright is just a really fast user, so it looks like it's possible to trigger both opening and closing at the same time on your web page. If that's a problem, there are two options: either fix the page so that's not possible (e.g. disable one of the controls during an animation), or wait for something specific  in the page, for example with `page.waitForFunction()`.

**Comment by FrankWang117** [comment]
@dgozman   Thank you, I understand. This issue can be closed now.

**Comment by FrankWang117** [comment]
@dgozman Thank you, I understand. This issue can be closed now.
