### ISSUE TITLE
While recording Playwright is not able to identify & capture " Embed " frame locator element in UI of system under test & gives error that it is looking for "iframe" type of frame locator instead 

### ISSUE THREAD

**Issue by abhiam1** [microsoft/playwright#28926]
### System info
- Playwright Version: 1.40.1
- Operating System: Windows 10 Enterprise LTSC Evaluation ,Version: 21H2 , OS build: 19044.3930 , 64 Bit OS 
- Browser: Chromium browser : 120.0.6099.28

Description 

While recording Playwright is not able to identify & capture " Embed " locator element in UI of system under test & gives error that it is looking for "iframe" type of locator instead

![Embed locator error_playwright1](https://github.com/microsoft/playwright/assets/30035443/4a23c950-2a2f-4b3e-8b20-881764891894)

Attached , snapshot of the error while recording a script in Playwright 

**Expected**

While recording Playwright should be able to capture the " Embed " locator element without any error . 

**Actual**

While recording Playwright is not able to identify & capture " Embed " locator element in UI of system under test & gives error that it is looking for "iframe" type of locator instead

**Comment by dgozman** [comment]
@abhiam1 Playwright does not work with `<embed>` elements today.

**Comment by abhiam1** [comment]
> @abhiam1 Playwright does not work with `<embed>` elements today.

Hello , is there a workaround for this issue . Also when will Playwright support working with `<embed>` elements , can you please let me know . Thanks & Best Regards . Abhijit

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
