### ISSUE TITLE
[BUG] Highlights get rendered behind the browser's #top-layer when using <dialog> tags

### ISSUE THREAD

**Issue by jojmaht** [microsoft/playwright#28944]
### System info
- Playwright Version: v1.40.1
- Operating System: macOS Sonoma
- Browser: Chromium
- Other info:

### Source code
[dialog.html.zip](https://github.com/microsoft/playwright/files/13902027/dialog.html.zip)

**Steps**
- Click on the "Open dialog" button
- execute `await page.locator("h1").highlight()`

**Expected**

The <x-pw-glass> container should be rendered in front of the page, and a highlight should appear around the `<h1>` tag in the dialog

**Actual**

The highlights' container is rendered behind the dialog, making the highlights invisible

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by maxfriedmann** [comment]
I have the same issue. While using the native dialog layer, the playwright recorder buttons aren't accessible anymore. It usually doesn't matter since you can start recording e.g. from VSCode or via the toolbar before you open the dialog, but it is really annoying if you want to assert a value or pick a locator. 

My current workaround: 
- open javascript console
- execute `document.getElementsByTagName("dialog")[0].appendChild(document.getElementsByTagName("x-pw-glass")[0])`

Example: 

<img width="1271" height="708" alt="Image" src="https://github.com/user-attachments/assets/1dc3c7da-33d0-4248-9aa2-64f979b30f8e" />

@pavelfeldman My suggestion would be to reopen the issue and fix it by watching `#top-layer` elements (like native dialogs)

#34657 would help in this case.

**Comment by Skn0tt** [comment]
this got refiled as https://github.com/microsoft/playwright/issues/39095, and we have a fix coming.
