### ISSUE TITLE
[Feature] Generating randomized test cases

### ISSUE THREAD

**Issue by KozynchenkoVS** [microsoft/playwright#28987]
Is it possible to use random test cases to produce tests?  
Currently, when I use random cases, the cases are redefined and playwright logs errors:
```
  1) [chromium] › example.spec.ts:6:5 › has title c17drh0j ─────────────────────────────────────────

    Test not found in the worker process. Make sure test title does not change.
```

Cases initialization(without external dependencies):
`const arr: ReadonlyArray<string> = Array(10)
  .fill(undefined)
  .map(() => Math.floor(Math.random() * Date.now()).toString(36));`

**Comment by mxschmitt** [comment]
Instead of defining the random test-cases inline during the test execution you can e.g. create a seed during the [globalSetup](https://playwright.dev/docs/test-global-setup-teardown#example) and then use this seed inside your tests, with seat you could e.g. use a real seed or a list of test files, constants etc. depending on your scenario.

Inline is not supported, since when we load them, they are called different to when we execute them in the worker.

Would that work for you?
