### ISSUE TITLE
[BUG] Enabling ignoreHTTPSErrors on globalSetup file

### ISSUE THREAD

**Issue by sjmc11** [microsoft/playwright#29001]
When using a globalSetup script, I'm unable to define the ignoreHTTPSErrors to true.

I have set as `true` in the defineConfig of playwright.config.js

```
module.exports = defineConfig({
  use: {
    /* Ignore SSL validity */
    ignoreHTTPSErrors: true,
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: process.env.APP_URL,
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry'
  },
  globalSetup: require.resolve('./tests/e2e/global.setup.js'),
})
```
But this does not seem to affect global setup. How would I make sure httpErrors are ignored for global setup scripts?

I don't see how to define it on the config arg either:

```
async function globalSetup (config) {
  config.use({ignoreHTTPSErors: true}) // does not work
  const browser = await chromium.launch()
  const page = await browser.newPage()
  await page.goto(process.env.APP_URL)
  // rest of setup logic
}
````

**Expected**

ignoreHttpsErrors to be respected during global setup scripts.

**Comment by mxschmitt** [comment]
It's expected that the config does not influence global setup. (since its not related to a project)

You need to manually set the launch/context options e.g. like this (see [here](https://playwright.dev/docs/api/class-browser#browser-new-page-option-ignore-https-errors) for docs):

    const page = await browser.newPage({ ignoreHTTPSErrors: true })

or you are using project dependencies instead, which will have the values of the config applied: https://playwright.dev/docs/test-global-setup-teardown
