### ISSUE TITLE
[BUG] The Playwright site (https://trace.playwright.dev/) does not currently support the loading of TraceViewer from a storage file URL.

### ISSUE THREAD

**Issue by darshandp007** [microsoft/playwright#29019]
**Steps**
- I have trigger this URL to access the traceviwer online but it's not work.
- URL: [https://trace.playwright.dev/?trace=https://demo.playwright.dev/reports/todomvc/data/cb0fa77ebd9487a5c899f3ae65a7ffdbac681182.zip](url)
- 
![image](https://github.com/microsoft/playwright/assets/42830249/e620aefe-2f6a-487b-9d1a-2f20b39b3725)

**Expected**
- It should work same as local file upload.

**Comment by mxlnk** [comment]
We are seeing the same Problem. We are serving traces from a public google cloud bucket

`Access to fetch at 'https://storage.googleapis.com/...-trace.zip' from origin 'https://trace.playwright.dev/' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'.
`
I guess it is because of this commit https://github.com/microsoft/playwright/commit/3f3f33206004d7d1b46b614e1db5cc13fc384b79
