### ISSUE TITLE
[Feature] allow `toMatchSnapshot` to refer to a `*.spec.ts` file independent snapshot 

### ISSUE THREAD

**Issue by michael-hoss** [microsoft/playwright#29048]
I want to use `toMatchSnapshot` in a `util.ts` file that refers to one single fixed snapshot, no matter which `.spec.ts` file calls the util.

```typescript
// in util.ts
expect(await element.screenshot()).toMatchSnapshot( {
    name: "../some_path_to_a_single_file_that_is_independent_of_the_spec_file_that_is_calling/my-snapshot.png",
    maxDiffPixels: 0,
    threshold: 0,
  });
```
It would be nice if this is possible such that I only need to create that snapshot once and use it for whatever `.spec.ts` file.
Right now, I would need duplicates of the snapshot for each `.spec.ts` file that uses this util (in their respective snapshots directories).

Don't know others' use cases, but I guess this could come handy for some people. 

Quick solution for me would be to just allow a path with `..` in the snapshot name. Currently, it looks like almost all path characters like `..` or `/` get turned into `-` (probably for some good reason I guess).

**Comment by michael-hoss** [comment]
Figured it out, closing now

**Comment by michael-hoss** [comment]
Wait, I cannot go `..` using `Array` in `name`: 
![image](https://github.com/microsoft/playwright/assets/33626467/38556f78-0206-4f11-af39-f076844724df)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
