### ISSUE TITLE
[Feature] CSS coverage supports anonymous style

### ISSUE THREAD

**Issue by cenfun** [microsoft/playwright#29040]
Currently, CSS Coverage doesn't include dynamically injected style tags without sourceURLs. see [note](https://playwright.dev/docs/api/class-coverage#coverage-stop-css-coverage)

Is it possible to support dynamically injected style tags without sourceURLs? Thanks.

### Why?
- When using CSS comments for sourceURLs such as `/*# sourceURL=anonymous.css */`, it could be removed by loader or plugin like `postcss-loader` or `css-minimizer-webpack-plugin`. 
- CSS can be written anywhere, such as css-in-js, *.vue files, and we don't know exactly how the final CSS will be dynamically injected.
- CSS coverage is also very important in modern front-end development.
- `startJSCoverage` has already supported the `reportAnonymousScripts` option, and it's worth supporting it in `startCSSCoverage` as well.
```js
await coverage.startJSCoverage({ reportAnonymousScripts: true }); // It has been supported
```
### Expect
```js
await coverage.startCSSCoverage({ reportAnonymousStyles: true }); // not supported yet
```

See issue: https://github.com/microsoft/playwright/issues/28510

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
