### ISSUE TITLE
[Feature] testInfo.stdout should be available during a test as this would allow stdout to be checked as part of the test

### ISSUE THREAD

**Issue by kspeers-r7** [microsoft/playwright#29062]
As part of our application we output logging to stdout to track progress of a request.
Currently, when testing we can use testInfo.stdinfo to report on those messages. However, while the test is running testInfo.stdout is always an empty array, which means that we can't include tests on those messages in the test.

Being able to have up-to-date testInfo.stdout data during the test would allow us to write more complete tests and ensure that we can test log messages being written to stdout

This also applies to testInfo.stderr

**Comment by mxschmitt** [comment]
Where are you starting your application? Are you using the webServer for that?

It was/is actually a bug that we have exposed `TestInfo.stdout/stderr` in the first place, we'll most likely remove it as part of https://github.com/microsoft/playwright/pull/29076.

**Comment by kspeers-r7** [comment]
For now, we're not using webserver to start our application but are using `process.stdout.on('data',` on our application to echo our the logging that we want to track to the PW tracked. It does track, but is only available after the test completes and not during the test.
Isn't there value in making stdout/stderr available on TestInfo? That should allow the test to check what is being logged, or is there a better way to do that?

**Comment by mxschmitt** [comment]
> we're not using webserver to start our application but are using 

Where are you running the webServer then? Do you manually launch it in beforeAll/beforeEach?

> Isn't there value in making stdout/stderr available on TestInfo

There is not as of today.

**Comment by kspeers-r7** [comment]
Yes - at present, we have custom code to manually launch our app with the param needed. While investigating testinfo.stdout and trying to see why I wasn't able to use testInfo.stdout during a test, I noticed the webServer command and we will switch to that.

Can we take this feature request as a use-case for making stdout and stderr available on testinfo?

**Comment by mxschmitt** [comment]
Having access to webServer stdout/stderr inside a test-run is out of scope as of today. We'd have to re-design the webServer feature and provide you the ability of having a webServer per project, (which is definitely something which would/could make sense) since otherwise it results in race conditions.

We recommend running a webServer per project using e.g. a fixture as of today, so you always have a single webServer for a specific test-run. concurrency/parallelism does then not infer with that what we are trying to avoid. It would look similar to [this](https://gist.github.com/mxschmitt/4fb26279108dc7c488fbdf033e873a27). (haven't tested it)

Closing by that, for webServer per project, I recommend filing a separate feature request/issue.
