### ISSUE TITLE
[FEATURE] Add support for recording video when connecting over CDP (connectOverCDP)

### ISSUE THREAD

**Issue by ignqa** [microsoft/playwright#29065]
Currently, it is not possible to record video when using Playwright to connect to a WebView2 app, which employs the instructions to connect Playwright to a WebView2 through the Chrome DevTools Protocol.

The [connect_over_cdp](https://playwright.dev/python/docs/api/class-browsertype#browser-type-connect-over-cdp) method returns a [browser ](https://playwright.dev/python/docs/api/class-browser) object, with its own [context](https://playwright.dev/python/docs/api/class-browsercontext) and [page](https://playwright.dev/python/docs/api/class-page).

[Recording on an existing context is not possible](https://github.com/microsoft/playwright-python/issues/1225#issuecomment-1078838600). So, the ideal would be:

- To allow the start of a video recording when the object is already created.
- To allow the same params related from the [browser.new_context() method](https://playwright.dev/python/docs/next/api/class-browser#browser-new-context) to add them to the `connect_over_cdp` method

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by jensakejohansson** [comment]
I disagree with this closure. I really expected this to work too... without having investigated the PW implemention I suppose it utilizes the CDP screencast-method - why should not this work when connecting to an already running process?

**Comment by Haprog** [comment]
This would be helpful to have.
