### ISSUE TITLE
[BUG] Screenshots in CI have additional padding

### ISSUE THREAD

**Issue by viraxslot** [microsoft/playwright#29117]
### System info
- Playwright Version: [v1.41.0]
- Operating System: [Ubuntu 22.04]
- Browser: [Chromium]
- Other info:

**Steps**
I have tests that check different graphs, I use `toHaveScreenshot` API for that.
I create reference screenshots locally inside `playwright:v1.41.0-jammy` docker container. In Github Actions Ubuntu 22.04.3 is used so basically the same OS.

**Expected** tests pass, screenshots are the same.

**Actual**
Screenshots in CI has additional padding (please see the screenshot) but images are the same except this: 
<img width="614" alt="image" src="https://github.com/microsoft/playwright/assets/20737672/5df1141b-35d2-4eef-82e2-e58e079b78eb">

I know it's hard to reproduce and investigate this issue but maybe you could advise how to make a workaround, because I have no ideas where this gap is come from.

FYI: I couldn't setup playwright sub-container in GH Actions because of some problems with Teleport. I'd like to try that but I can't. Thanks in advance!

**UPDATE**: works fine on non-default viewport { width: 1600, height: 1200 }

**Comment by yury-s** [comment]
Browser rendering is finicky about the environment where they run. In order to make the test reproducible we suggest to capture the screenshots on the same machine where you run the tests. There are some related issues like https://github.com/microsoft/playwright/issues/18373 or https://github.com/microsoft/playwright/issues/13873
