### ISSUE TITLE
[BUG] Basic auth not working in new tab with Desktop Chrome

### ISSUE THREAD

**Issue by Morgy93** [microsoft/playwright#29193]
### System info
- Playwright Version: [v1.41]
- Operating System: [Linux docker something, macOS 14.2.1]
- Browser: [Chromium]
- Other info:

### Source code

`playwright.config.ts`:

```
const btoa = (str: string) => Buffer.from(str).toString("base64");
const credentialsBase64 = btoa(
    "USERNAME:PASSWORD" // update to your credentials
);
```

Config `use`:
```
...devices["Desktop Chrome"]
```
```
extraHTTPHeaders: {
    Authorization: `Basic ${credentialsBase64}`,
},
```

**Steps**
- Have a site with basic auth enabled
- That page should have a link that can be clicked:
```
const someLink = await page.locator("a"); // update to get your link

const [newPage] = await Promise.all([
    context.waitForEvent("page"),
    someLink.click({ button: "middle" }),
]);
```

**Expected**

Using `...devices["Desktop Firefox"]` the new tab works fine. I expect all browsers to work.

**Actual**

Using `...devices["Desktop Chrome"]` the auth dialog is shown:
![image](https://github.com/microsoft/playwright/assets/7961978/71426f83-dd87-4865-bae2-e4fd8436a4b0)

It does not matter if you click "Sign In" or "Cancel", take page will then load simply fine.

**Comment by yury-s** [comment]
Please provide a self-contained repro that we could run locally to see the problem.

**Comment by Morgy93** [comment]
> Please provide a self-contained repro that we could run locally to see the problem.

What do you have in mind exactly? Some zip file with docker-compose and stuff that spins up an environment you could test against?

**Comment by yury-s** [comment]
More like a node package with a server and a test, or at least the test and a URL where it happens. I was not able to reproduce with simple examples.

**Comment by Morgy93** [comment]
This seems to replicate it:

`playwright.config.ts`:
```
extraHTTPHeaders: {
    Authorization: 'Basic ' + Buffer.from('user:pass').toString('base64'),
},
```

`test.spec.ts`:
```
import { expect, test } from "@playwright/test";

test("basic auth", async ({ context, page }) => {
    await page.goto("https://authenticationtest.com/");

    const linkToPageWithAuth = page.getByRole("link", {
        name: "HTTP/NTLM Auth",
    });

    const [newPage] = await Promise.all([
        context.waitForEvent("page"),
        linkToPageWithAuth.click({ button: "middle" }),
    ]);
    await newPage.waitForLoadState();

    await expect(
        newPage.getByText("Success! You are now logged"),
    ).toBeVisible();

    newPage.close();
});
```

If you run this with headed mode, it shows the basic auth login:

![image](https://github.com/microsoft/playwright/assets/7961978/a8f551f1-1906-456b-a127-2edeaafa3b3e)

But after clicking `Cancel` or `Sign In` you are in fact logged in already.

**Comment by yury-s** [comment]
This is indeed a bug in Chromium headed, when opening new page on middle click or shift+click we attach to it too late and the request gets sent before playwright sets the extra headers. It does work with target=_blank though, so you can use that as a workaround for the time being:

```js
import { expect, test } from "@playwright/test";

test("basic auth", async ({ context, page }) => {
    await page.goto("https://authenticationtest.com/");

    const linkToPageWithAuth = page.getByRole("link", {
        name: "HTTP/NTLM Auth",
    });

    await linkToPageWithAuth.evaluate((el) => el.setAttribute('target', '_blank'));
    const [newPage] = await Promise.all([
        context.waitForEvent("page"),
        linkToPageWithAuth.click(),
    ]);
    await newPage.waitForLoadState();

    await expect(
        newPage.getByText("Success! You are now logged"),
    ).toBeVisible();

    newPage.close();
});
```

Given that it's quite an edge case (middle click) that only affects headed, this issue is quite low priority.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
