### ISSUE TITLE
[Feature] - Possibility to reduce sizes of screenshots and trace files

### ISSUE THREAD

**Issue by OSnuszka** [microsoft/playwright#29218]
**Problem:**
Currently, we are exploring solutions to control the size of attachments generated by Playwright, aiming to stay within the constraints of artifact limits in GitLab pipelines. On our CI/CD, strict limits on artifact sizes pose a challenge, and even with significant restrictions on when we generate traces and screenshots, we still find ourselves exceeding these limits.

**Proposal:**
It would be immensely beneficial for me to have the ability to minimize attachments generated by Playwright through configurable options:

- Screenshots:

Introduce a compression level option for screenshot attachments, akin to the functionality in the Node library Sharp.

- Trace:

Implement a compression level option for trace attachments, similar to the approach in the Node library Sharp.
Provide the ability to limit the data collected by the trace report.

**Comment by LucaLis** [comment]
The options object of Page.screenshot method allows to switch the type of screeshot from default 'png' to 'jpeg'. After switching to the latter you are able to set another option - quality (0-100). This allows to reduce the size of images.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by samuel-cho-lendbuzz** [comment]
Are you able to set quality at the global level in playwright.config.ts?

**Comment by PhilippKemkes** [comment]
I would also like to know if the image compression can be defined globally for all screenshots?

**Comment by jimhigson** [comment]
lossy compression could introduce false positives due to compression artefacts

I think instead it would be better to scale down the images but keep as png. This is fully deterministic, so it wouldn't cause false positives. Most sites don't need high-resolution screenshots for visual regression testing.
