### ISSUE TITLE
[Feature] Storage State in Electron Apps

### ISSUE THREAD

**Issue by GinjiJizai** [microsoft/playwright#29239]
Hi,

the storage state is a great feature to authenticate to an application. Sadly, it seems that electron apps do not have this feature available. So my feature request would be to make this feature also usable for Electron apps. 

Also the documentation found here: https://playwright.dev/docs/auth does not mention that it cannot be used in electron apps. This should be updated, if possible.

I think everyone who needs to test electron apps, would appreciate that feature, which is already usable for all other browsers. 

PS: If i'm wrong and this feature can be used in the electron app it would be cool if you can help me out on how to do it or provide a workarround.

Thank you in advance.

**Comment by pavelfeldman** [comment]
Storage state is a part of the web platform implementation (browser) and not a part of the web tech stack (electron), so in general we consider it to be outside of the scope of support for Electron. Electron can use a wide range of programmatic approaches to achieve auth and it is typically easier for you to achieve them via running electron code instead of using the storage state.

**Comment by GinjiJizai** [comment]
Ok thank you for the Explanation. I will find another way then :).
