### ISSUE TITLE
Playwright Inspector debug mode pause button does not pause test run timeout.

### ISSUE THREAD

**Issue by billw4** [microsoft/playwright#29264]
### System info
- Playwright Version: [v1.41.1]
- Operating System: [Windows 11]
- Browser: [Chromium]

### Source code
Not needed.

**Steps**
When running a test in debug mode, and the Pause button is clicked in the Playwright Inspector window, the test run will pause, but the test run timeout is still enforced and the test will shut down the paused debugger when the test timeout limit is reached.  

Clicking the pause button in debug mode should pause the test timeout limit as well.

**Comment by pavelfeldman** [comment]
Could you provide a snippet as debug mode is supposed to suppress the timers. Maybe that is an expect timeout and not test timeout?

**Comment by billw4** [comment]
`export default defineConfig({
  outputDir: 'test-results',
  testDir: './tests',
  /* Maximum time one test can run for. */
  timeout: 30_000,  // Thirty seconds
  /* Maximum time the test suite can run for. */
  globalTimeout: 300_000, // Five minutes
...
`

**Comment by pavelfeldman** [comment]
A test snippet would be nice.

As I mentioned above, `--debug` disables the 'test timeout', so you can wait as much as you'd like on a pause, before you click 'Step over', there is no race between you and the test timeout. However, if you step over `await expect`, that call obeys to 'expect timeout', which is significantly shorter. This 'expect timeout' is not disabled because it does not race with the user controlling the debugger. If the condition is not met within the expect budget, expect fails. See https://playwright.dev/docs/test-timeouts for timeout differences.
