### ISSUE TITLE
[Feature]: include slotted content in CSS selector

### ISSUE THREAD

**Issue by bgotink** [microsoft/playwright#29357]
### 🚀 Feature Request

The css selector engine pierces shadow roots, but it doesn't pierce slots.

It would be helpful if it would pierce slots. This would also make the selector engine more correct as slots can have children but those are only active in the DOM tree if there is no slotted content, but as of right now playwright's selector engine will always access the slots children.

### Example

Suppose the following DOM

```html
<my-outer>
  #shadowRoot
    <my-inner>
      <slot><button>don't click me</button></slot>
    </my-inner>
  <button>click me</button>
</my-outer>
```

If I have a Locator or ElementHandle that points to the `my-inner` element, I currently can't access the "click me" button using `locator.locator('button')` /  `elementHandle.$('button')`. Instead, I'll get the "don't click me" button, which is not actually visible or accessible to the end-user.

Code for this example (single HTML file + script using playwright): [example.zip](https://github.com/microsoft/playwright/files/14163619/example.zip)

### Motivation

We use "page object"-like wrappers for our component library. We're currently moving our component library to Shadow DOM and discovered this breaks our ability to access slotted content.

For `my-outer` in the example this is not that big an issue, we can select via `[slot=...]` to get the slotted content for every slot via light DOM. In the case of the `my-inner` element object this won't work.

Slots always getting access to their children instead of slotted content is confusing and will lead to mistakes on our end.

**Comment by dgozman** [comment]
@bgotink Thank you for the feature request!

I understand your usecase, but I don't think we are going to change how CSS selectors work.
- Recursing into `slot` children is surprising. CSS selectors work in the light DOM, not in the flattened DOM. This would be a different version of CSS selectors altogether, that is affected by node distribution.
- We cannot break existing CSS selectors in the wild that rely on the current behavior.

I'd recommend creating a [custom selector engine](https://playwright.dev/docs/extensibility#custom-selector-engines) for you that would get distributed nodes for component slots. For example, `slot=<name>`, e.g:
```ts
const component = page.locator('my-inner');
// Passing `slot=<empty>` to access the slot without a name.
const button = component.locator('slot=').locator('button');
// For a named <slot name=footer>
const buttonInTheFooter = component.locator('slot=footer').locator('button');
```

**Comment by dgozman** [comment]
> While the "Don't click me!" button technically exists, it is invisible and unreachable.

I agree that it is confusing if you look at the rendered page. However, fallback content is not technically different from something like `<details>` content that is not visible until you open the details element.  If you check `isConnected` property of the `<button>` in your example, it will be `true`.

Such a button is still in the DOM, but is not rendered on the page, much like a `display: none` element. Since CSS selectors are not concerned with visibility of the element, it should be possible to locate it through CSS. Therefore, CSS returns all three buttons that are in the DOM.

---

Overall, if we were to implement something like this in Playwright, it would probably be a different selector engine, e.g. `css:flat` or `css:composed`.

**Comment by bgotink** [comment]
Yeah and that's probably why it's confusing to me. In my code I'm performing actions along the line of "click the confirm button in the footer", which no longer work if the button is placed in the footer via a slot.

I've experimented a bit and created a rough initial version of a selector engine that works on the composed DOM, in case you're interested:
https://github.com/bgotink/ngx-playwright/tree/7e2ff7e669e3d677ab75145758896acfb11de4a3/packages/composed-css

If this is something you'd be interested in supporting in playwright itself via a new selector engine, feel free to keep this issue open, otherwise I consider this issue closed.

**Comment by dgozman** [comment]
>  In my code I'm performing actions along the line of "click the confirm button in the footer", which no longer work if the button is placed in the footer via a slot.

Yeah, I understand that's inconvenient. Definitely a valid usecase.

> I've experimented a bit and created a rough initial version of a selector engine that works on the composed DOM

This looks awesome!

> feel free to keep this issue open, otherwise I consider this issue closed.

I will keep this feature request open to gather feedback. If this turns out to be a popular request, we might as well introduce a new selector engine.

**Comment by astearns** [comment]
I am currently running into a situation where I would like slot-piercing behavior (at least for `getByRole`).

I have code that selects menuitems that chains `getByRole` like this: 

`getByRole('menu').getByRole('menuitem', { name: 'Delete' });`

This has been working well over several iterations of two separate component systems. But I now have a sp-menu component where the menuitem elements are slotted into their menu element from a different part of the component tree (see https://opensource.adobe.com/spectrum-web-components/components/action-menu/). Playwright doesn’t see the menuitems inside of their slots, so the line above does not work with the new component.

**Comment by nip3o** [comment]
It would be very helpful to be able to do this one way or another. 

We are currently migrating a Dialog component to [Shoelace sl-dialog](https://shoelace.style/components/dialog). Currently we can access the dialog element itself using something like `getByRole("dialog", name="Dialog title")`, and then use a child locator such as `locator("div", { hasText: "Lorem ipsum" })` to access the dialog contents. This is not possible with `sl-dialog` since the dialog content is slotted in, so we have to rely on something less elegant like `locator("sl-dialog div", { hasText: "Lorem ipsum" })`.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
