### ISSUE TITLE
[Feature] How can I get first non-redirect reposne?

### ISSUE THREAD

**Issue by FANGOD** [microsoft/playwright#29361]
```
def on_response(data, response):
        print(111, response.status, response.url)
        if response.status not in [301, 302, 303] and first_response:
            data...

data = {}
page.on("response", lambda response: on_response(data, response))
try:
    response = page.goto(url, wait_until="load", timeout=20000)
except:
    pass
```
I want to get a response from `page.goto`, but it's None because of timeout.
How to get the first non-redirected response from page.on response ?

**Comment by dgozman** [comment]
@FANGOD Use [`request.redirected_from`](https://playwright.dev/python/docs/api/class-request#request-redirected-from):

```py
# you can go over the redirect chain by accessing "redirected_from"
response.request.redirected_from
```

**Comment by FANGOD** [comment]
> @FANGOD Use [`request.redirected_from`](https://playwright.dev/python/docs/api/class-request#request-redirected-from):
> 
> ```python
> # you can go over the redirect chain by accessing "redirected_from"
> response.request.redirected_from
> ```

Yes, it works. 
Is there a way to handle 403 codes like 302? The first time it was loaded, it was 403, and then the page automatically refreshed. This situation is also very common. Like this url "https://www.facct.ru/blog/"

**Comment by dgozman** [comment]
> Is there a way to handle 403 codes like 302? 

403 is not a redirect, so you have to use `page.on("response", handler)` to see the 403. Unfortunately, you will have to figure out whether a response is the one you are interested in or not. Playwright gives you all the information available about the request/response, but it does not know about the application logic to be able to determine the logical chain of requests.

Since there is no action item for Playwright here, closing the issue. If you have any further questions, we recommend [asking the community](https://playwright.dev/python/community/welcome).
