### ISSUE TITLE
[Bug]: In Webkit, text-align: justify does not work.

### ISSUE THREAD

**Issue by shilaca** [microsoft/playwright#29388]
### Version

1.41.2

### Steps to reproduce

1. Clone my repo at https://github.com/shilaca/playwright-text-align-justify
2. `npm install`
3. `npm run test`
4. You should check the screenshot

### Expected behavior

When text-align: justify is specified in CSS, the text should be justified on both ends.

**The result on Chrome (`devices["Pixel 7"]`)**

![snapshot-Pixel-7-linux](https://github.com/microsoft/playwright/assets/54238024/42ef4703-f5ad-4638-856f-50641eb528a4)

### Actual behavior

In Webkit (`devices["iPhone 14"]`), it seems that `text-align: justify` does not work.
It works fine with English, but not with Japanese.
One possible reason could be that Japanese does not use spaces, unlike English.

**The Japanese text has a gap on the right side.**

![snapshot-iPhone-14-linux](https://github.com/microsoft/playwright/assets/54238024/962a75d6-50eb-4c85-97f6-33dc97268169)

### Environment

```shell
System:
  OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  CPU: (5) arm64 unknown
  Memory: 13.92 GB / 15.61 GB
  Container: Yes
Binaries:
  Node: 20.11.0 - /usr/bin/node
  Yarn: 1.22.21 - /usr/bin/yarn
  npm: 10.2.4 - /usr/bin/npm
Languages:
  Bash: 5.1.16 - /usr/bin/bash
npmPackages:
  @playwright/test: ^1.41.2 => 1.41.2
```

**Comment by dgozman** [comment]
I can repro in the container. However, when running on MacOS, I do see the text aligned on both sides.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
