### ISSUE TITLE
[Bug]: Playwright is crashing as while clicking on the button which build on ASP.net applcation

### ISSUE THREAD

**Issue by manishsoni0407** [microsoft/playwright#29398]
### Version

1.9.0-alpha-0

### Steps to reproduce

1. login to application  ( This is working) 
2.  Search an contact through global search ( This is working) 
3.  Click on one Tab (Subscription)  and click on FI Subs
4.  Add a Topic 
5. Add a sub topic 
6. click on Add 

### Expected behavior

Playwright codegen should not crash 

### Actual behavior

Playwright codegen is getting crashed 

### Environment

```shell
QA, UAT and Prod
```

**Comment by dgozman** [comment]
@manishsoni0407 Thank you for the issue. Unfortunately, there is nothing we can do without a repro. And since you have not provided any source code to run, I am unable to reproduce the issue. Please file a new issue by carefully filling in the "Bug Report" template providing all the details, including source code that I can run to reproduce the issue.
