### ISSUE TITLE
Parallel load

### ISSUE THREAD

**Issue by Pooort** [microsoft/playwright#2940]
How could I open pages in parallel?

Thanks.

**Comment by yury-s** [comment]
You can call `newPage()` multiple time without waiting previous calls to finish:

```js
const context = await browser.newContext();
const pages = [];
for (let i = 0; i < 10; i++)
  pages.push(context.newPage());
await Promise.all(pages);
```
You can similarly create multiple contexts and create pages in them concurrently. All this operations will have to run on the same thread in node process but there will be parallelism on the browser end. Can you tell us a bit more about what you are trying to achieve so that we can better help you?

**Comment by Pooort** [comment]
@yury-s Thanks a lot. Your answer is 100% complete.
