### ISSUE TITLE
[Bug]: page.route(..) handled 'fulfill' responses do not appear in 'Network' requests in Firefox Developer Tools

### ISSUE THREAD

**Issue by epicwhale** [microsoft/playwright#29414]
### Version

1.41.1

### Steps to reproduce

1. Intercept a request (say a js file) and fulfill with a response
2. In Developer Tools of Firefox, look for the intercepted requested. Compare it to Firefox

```python
async def handle_js_route(route: Route) -> None:
    response = await route.fetch()
    js_code = await response.text()

    await route.fulfill(
        response=response,
        headers=response.headers,
        body=js_code,
    )

await page.route("**.js*", handle_js_route)
```

### Expected behavior

I expect to see the handled request/response in the Network tab of the browser's developer tools.

This is working fine in Chrome - where I see a (canceled) request and then the fulfilled 200. I can click on it and inspect the headers/request/response
[Chrome Screenshot - No Bug]
<img width="796" alt="image" src="https://github.com/microsoft/playwright/assets/670655/d2f22975-2f7b-4df8-bf90-666019b41bad">

### Actual behavior

In Firefox Developer Tools, the trace is unusual. I can see two entries but I can't access them and the columns like status, type, size, etc are all blank.
[Firefox Screenshot - Bug]
<img width="729" alt="image" src="https://github.com/microsoft/playwright/assets/670655/045ecd01-4dab-4d70-9121-ec734f84506c">

### Additional context

Firefox 121.0 (64-bit)

### Environment

```shell
System:
    OS: macOS
  Binaries:
    Python 3.11.7
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
