### ISSUE TITLE
[Feature]: Need feature of galen spec validation for layout testing using Playwright.

### ISSUE THREAD

**Issue by KrushnaMa** [microsoft/playwright#29430]
### 🚀 Feature Request

As part of Layout testing playwright has provided the feature of "Visual comparisons" where we compare the images. But for verifying css value more accurately galen spec validation is the best choice (to get exact height. color and many other css value)  as compare with image comparison. So I would like to request you to provide the feature for galen spec validation.

Also I have noted that "Visual comparisons" concept is available only for Node.js, but not for Java, Python and .net.

<img width="915" alt="Playwright" src="https://github.com/microsoft/playwright/assets/157467775/54c666c0-60e9-4c50-997e-555237f83cbc">

### Motivation

If we implement this feature in Playwright then we can do Layout testing more accurately using galen spec validation.
Using this feature we will be able to verify exact css value like height, color and many other on the basis the performed action.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
