### ISSUE TITLE
Skip subsequent actions in a data array object when any action fails

### ISSUE THREAD

**Issue by mkrishnan89** [microsoft/playwright#29453]
### Please do not submit this issue.

- [x] I understand

**Comment by mkrishnan89** [comment]
I have a playwright test with PageObject model where spec file contains test.describe with For loop to read each actions from a data file and call respective functions defined in separate file.

I got 10+ paths in each data file having 10+ actions for each Path.
Is there a way to skip the subsequent actions for the Path being executed if any action fails. 

Specfile.ts

test.describe( async () => {
    test.beforeAll(async ({ }) => { const browser = await playwright.chromium.launch({});   };
    testData.forEach((data) => {
       test(data.path , async() => {
         if (action= XXX) {Call Function A}
        if (action=YYY) {Call Function B}
}
}


Datafile.ts

const testData [
{  Path: path1, PathTitile : test1,   Actions [ Action1, Action2, Action3 ]  }
{  Path: path2, PathTitile : test2,  Actions [ Action1, Action2, Action3 ]  }
{  Path: path3, PathTitile : test2,  Actions [ Action1, Action2, Action3 ]  }

]

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
