### ISSUE TITLE
[Bug] writing to browser clipboard throws a DOMException: Write permission denied when running headless

### ISSUE THREAD

**Issue by marcusNumminen** [microsoft/playwright#29472]
### Version

1.41.2

### Steps to reproduce

Run this test both headed and headless;
```typeScript
test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await expect(page).toHaveTitle(/Playwright/);

  await page.evaluate('navigator.clipboard.writeText("XXXYYYZZZXXXYYYZZZ")');
});
```
In `headed mode` this works fine but in `headless mode` I get the error:
`Error: page.evaluate: DOMException: Write permission denied.`

### Expected behavior

I expect the same behavior in headed and headless mode

### Actual behavior

I get different behavior in headed and headless mode

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 21.29 GB / 31.85 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.2 - C:\Program Files\nodejs\pnpm.CMD
  IDEs:
    VSCode: 1.86.1 - C:\Users\marcus.numminen\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.21 - C:\Program Files\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
```

**Comment by mxschmitt** [comment]
In order to use clipboard, you need to give it clipboard permissions like that:

```ts
test.use({
    permissions: ['clipboard-write']
})

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await expect(page).toHaveTitle(/Playwright/);

  await page.evaluate('navigator.clipboard.writeText("XXXYYYZZZXXXYYYZZZ")');
});
```

in headed/headless the concept of permissions is implement different on Chromium since, hence its working. So far there's no good clipboard support in browsers for automation. Even the clipboard that works in headful version of browsers is not well isolated from the OS, so other things can interfere with running tests.

There's a request for better clipboard isolation: https://github.com/microsoft/playwright/issues/13097

I'll close this in favor of that request.
