### ISSUE TITLE
Drag to Make a Box (Not Drag and Drop) Isn't Working

### ISSUE THREAD

**Issue by awhisler** [microsoft/playwright#29482]
### Please do not submit this issue.

- [X] I understand

**Comment by awhisler** [comment]
Our software has the ability to drag and make a box to make notes. I tried using the following code and it did not work

```
await page.locator('[test-id="frame-in-modal"]').click({ position: { x: 10, y: 10 }, delay: 2000 });
await page.mouse.down();
await page.mouse.move(100, 100);
```
Where `[test-id="frame-in-modal"]` is the left side image from the video

https://github.com/microsoft/playwright/assets/2396250/3647ed03-2931-426c-b04d-72caa9d99888

Can anyone help?

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev/) 
- [Our Discord server](https://aka.ms/playwright/discord)

**Comment by awhisler** [comment]
@mxschmitt for the record, I used your guys template to make this.
<img width="1291" alt="image" src="https://github.com/microsoft/playwright/assets/2396250/746a0b78-e80d-455e-834c-b1f011d846bf">
