### ISSUE TITLE
[Feature]: Codegen should use `baseURL`

### ISSUE THREAD

**Issue by Luc45** [microsoft/playwright#29569]
### 🚀 Feature Request

When generating tests with codegen, instead of generating this:

```
await page.goto('http://qit.test:32917/');
```

It should generate:

```
await page.goto('/');
```

If my baseURL is `http://qit.test:32917`

### Motivation

Otherwise I can't use codegen on environments with dynamic ports (for instance, when we let Docker pick the first free port in the host).

I could manually tweak the codegen tests, but I'm building a programmatic integration where ideally this should work out of the box.

**Comment by mxschmitt** [comment]
How do you launch codegen? Via VSCode?

**Comment by Luc45** [comment]
Via terminal, with `npx playwright codegen`

**Comment by Luc45** [comment]
I'm not sure if `codegen` loads `playwright.config.js` at all, at which point it can't know what the `baseURL` is. It doesn't take a `--config` parameter, for instance.

**Comment by Luc45** [comment]
Maybe we could transform it [here](https://github.com/playwright/playwright/blob/59b8cf008e0f3e98936cfeb7776d0a0eda4b22da/packages/playwright-core/src/server/recorder/codeGenerator.ts#L153)

**Comment by mxschmitt** [comment]
`npx playwright codegen` is not loading the config which is expected, since its a library feature, which is also available across the language ports. If you want to have deeper integration with codegen which is linked to the config, then I recommend subscribing to https://github.com/microsoft/playwright/issues/26777.

Merging into https://github.com/microsoft/playwright/issues/26777
