### ISSUE TITLE
[Question]: I generate pdf, 'display_header_footer'='true' during pdf creation, imported header, downloaded font to header and footer not applied problem

### ISSUE THREAD

**Issue by kimGyeongSeok-web** [microsoft/playwright#29573]
Hello playwright team,

In this generate pdf code 

<img width="692" alt="스크린샷 2024-02-19 오후 6 03 52" src="https://github.com/microsoft/playwright-python/assets/79523251/fce96cac-7bbc-4ad0-9f92-b068ff1bc769">

in 75th row. 75th row

If you put a style tag in the head of the header_template_content html file, apply the font-face, and create a separate css file to make the font-face, it does not apply.
Does anyone have a similar experience to me?

🙇  There's nothing wrong with the font file's path. It prints very well when I open it with my browser, and I tried changing the font file to base64. 😢

**Comment by yury-s** [comment]
Does not seem like a bug report of feature request, please follow the issue templates.

**Comment by smartmeta** [comment]
Hi @KimGSeok,
did you get a answer/solution for that problem?

I have the same issue. I need to set a custom font for Header and Footer. 

In the content of the PDF it  works because there the style-sheet can be added with

page.addStyleTag({path: ".pdf-styles.css"});

but I did not find a way to do the same for Headers and Footers.

**Comment by KimGSeok** [comment]
> Hi [@KimGSeok](https://github.com/KimGSeok), did you get a answer/solution for that problem?
> 
> I have the same issue. I need to set a custom font for Header and Footer.
> 
> In the content of the PDF it works because there the style-sheet can be added with
> 
> `page.addStyleTag({path: ".pdf-styles.css"});`
> 
> but I did not find a way to do the same for Headers and Footers.
> 
> Would be nice if
> 
> `page.addStyleTag({path: ".pdf-styles.css"});`
> 
> would also affect/apply to the Headers and Footers.

Hello, here’s what I tried:

Applying <style>@font-face</style> in the tag of the HTML file
Injecting the font forcibly using VanillaJS when the script loads
Setting options for page.pdf
Installing the font I wanted to use directly on the operating system
I was able to solve the issue with option 4. I generated the PDF without the font initially on Docker and macOS, then installed it as a system font, and it rendered correctly.

So, I fixed the issue by adding the font installation to the Docker system as part of the Docker image build process. I thought the PDF rendering engine might rely on system fonts rather than embedded ones, and this approach worked well for me.

Playwright isn’t specifically designed for generating PDFs; it primarily leverages a browser engine, which sometimes leads to issues. When I encounter problems, I often find useful hints in release notes for Chromium or Chrome.

**Comment by smartmeta** [comment]
Hey @KimGSeok,

thanks a lot for your quick answer. 

I also set the <style>@font-face</style> and have the fonts installed on my system.

What exactly do yo mean by:
 Injecting the font forcibly using VanillaJS when the script loads  

And what are your options for page.pdf?

**Comment by KimGSeok** [comment]
> Hey [@KimGSeok](https://github.com/KimGSeok),
> 
> thanks a lot for your quick answer.
> 
> I also set the <style>[@font-face](https://github.com/font-face)</style> and have the fonts installed on my system.
> 
> What exactly do yo mean by: Injecting the font forcibly using VanillaJS when the script loads
> 
> And what are your options for page.pdf?

It was a while ago, so I don't remember the exact code. I tried methods like addStyleTag and addScriptTag from https://playwright.dev/docs/api/class-page, experimenting with ways to modify the rendering as well as fonts.

Forced injection through JavaScript was done similarly to how file downloads are created, like this:

```const styleItem = document.createElement('div');
styleItem.innerHTML = "<style>@font-face { ... }</style>";
document.head.appendChild(styleItem);
```
I hope this helps!
