### ISSUE TITLE
At page#1, after login, open page#2 in a new tab, but it redirected to page#1 instead of page#2

### ISSUE THREAD

**Issue by hanhnhk** [microsoft/playwright#29631]
I am using Playwight with Typescript. 
At page#1, I login successful, then I clicked a button to open a new tab with Page#2 loaded.
**Expected result**: page#2 is loaded in a new tab
**Actual result**: a new tab is open, the url was redirect to page#1
What should I do to resolve it?

![open a new tab](https://github.com/microsoft/playwright/assets/61803380/f3ad5d66-7bb1-43c2-9590-11965aa67bfc)

**Comment by hanhnhk** [comment]
I am using Playwight with Typescript. At page#1, I login successful, then I clicked a button to open a new tab with Page#2 loaded.
**Expected result**: page#2 is loaded in a new tab
**Actual result**: a new tab is open, the url was redirect to page#1
What should I do to resolve it?

![open a new tab](https://github.com/microsoft/playwright/assets/61803380/16e15a24-6888-4b5c-8b2d-52c9626c5c4c)

**Comment by ltsuda** [comment]
I think this is the same thing you are doing but does this help? Also, if you perform some action or wait for an element with `tab` page, does that works? Like, the action/wait in the `tab` to make it the active page instead of the main `page/loginPage`.

https://playwright.dev/docs/pages#handling-new-pages

**Comment by yury-s** [comment]
We cannot debug screenshots. Please file a new issue, follow the bug template and provide a repro that we could run locally to see the problem.
