### ISSUE TITLE
[Feature]: decorators (again)

### ISSUE THREAD

**Issue by ffMathy** [microsoft/playwright#29646]
### 🚀 Feature Request

These have been addressing this, but have all been closed:
- #14812
- #13996
- #12105
- #11440
- #15524

I'd love to track support for decorators, and argue that it is needed.

**It doesn't have to be default. Just allow people (who are aware of the potential consequences) to enable it.** Decorators recently got better support in TypeScript 5 now that decorators [is in stage 3](https://github.com/tc39/proposal-decorators). But even the experimental decorators are heavily used in Angular, Inversify, etc.

I feel like the argument that decorators are experimental has no real basis. That's like saying async/await was experimental when it wasn't widely adopted by EcmaScript yet, and required TypeScript to use. It is being used in the real world, and there are many who depend on it (even the big guns like Angular).

Another counter-argument seems to be that people can just enable TypeScript compilation of their tests manually, as described [here](https://playwright.dev/docs/next/test-typescript#manually-compile-tests-with-typescript). The problem with this is that it fails to work with projects that are monorepo based like NX etc.

### Motivation

Decorators are heavily used with dependency injection. We can't use Playwright right now because we can't reference any of our existing code, since it has classes with @injectable() decorators.

**Comment by pavelfeldman** [comment]
Do you mean these - https://youtu.be/KqVuRAlOkm0?t=398? Or is there anything else you'd like to see supported?

**Comment by ffMathy** [comment]
No, not decorators on playwright tests themselves. But referencing code that uses inversify decorators.

**Comment by pavelfeldman** [comment]
Could you give me a better idea on the exact scenario in a form of a repo?

**Comment by ffMathy** [comment]
This issue describes the exact error I'm getting.

https://github.com/microsoft/playwright/issues/12105

But it's quite easy to repro. Create a playwright project. Then add Inversify or Angular to that project. Then from your test, import a class that has a decorator on it from Inversify or Angular. Your test will fail with that error, and no way to enable decorators.

**Comment by pavelfeldman** [comment]
Playwright uses Babel to transpile TypeScript. In particular, [@babel/plugin-proposal-decorators](https://babeljs.io/docs/babel-plugin-proposal-decorators) is used to support decorators. We currently use `version=2023-05` as per Babel recommendation.

> "2023-05" is the proposal version after the updates that reached consensus in the March and May 2023 TC39 meetings, integrating [these changes](https://github.com/pzuraq/ecma262/compare/e86128e13b63a3c2efc3728f76c8332756752b02...c4465e44d514c6c1dba810487ec2721ccd6b08f9).

I.e. this is the latest version that is compatible with what is going to be signed off by TC39. With  2023-05, using `inversify` yields the following error: `Decorators cannot be used to decorate parameters.` Supporting this feature requires us to set `version=legacy` in Babel and use additional unofficial package [babel-plugin-transform-typescript-metadata](https://www.npmjs.com/package/babel-plugin-transform-typescript-metadata) to preserve the TS metadata.

Our understanding is that if we do that, we will inevitably break customers once decorators become a part of the standard. I understand that for some frameworks that ship has sailed, they already committed to support this fork of the language. But we would not want to repeat their path and would prefer to stay on the stable path. That's why we've only enabled decorators in TS after it has been promoted to stable TS.

**Comment by pavelfeldman** [comment]
Seeing examples where inversify is used by tests would help us prioritize the fix.

**Comment by ffMathy** [comment]
But if 99% of your user base is using decorators like everyone else and is on the legacy standard, why not just switch when your consumers switch as well?

Or even better, when they are even *able* to switch. Right now we have no choice. Angular users or Inversify users are stuck on legacy decorators. And it'll probably be like that for many years.

It feels like a weird thing to insist on when it's not actually used by a lot of people.

That's a claim not backed by anything else than gut feeling. I know. But I think if you looked around and did a case study on how your users use decorators, you'd find that it was way too early to make the switch to non-legacy decorators.

Look at the upvotes this issue already received, and the ones before it. There is demand for this.

What good is support for TC39 compliant decorators when they can't be used.

**Comment by ffMathy** [comment]
@pavelfeldman I'll do my best and make a simple repro.

**Comment by bshostak** [comment]
Came across this while researching and just wanted to provide some context of what we've noticed with using decorators. 
We currently publish an internal npm package that houses our page-modules and other utility related helper functions when doing api/ui testing. 
We recently found that when creating a decorator inside this package and using it on a method that a test inside the package itself calls, playwright would error out. However, installing that package in our external codebase that houses playwright automation would run just fine and the decorator worked as expected (currently it just logs some stuff about the method and passed in parameters). I assume because it was previously compiled is the reason we're not erroring out here.
Following this: https://playwright.dev/docs/test-typescript#manually-compile-tests-with-typescript also did not work for our situation. So I upvoted this feature because it would be nice to have the support and be able to use more in-depth decorators in the future.

**Comment by ffMathy** [comment]
> We consider feature requests with 80+ upvotes as having strong support - we have a lot of users at this point.

But thats easy to say when you are shutting down issues before they can reach a proper amount of upvotes. Look at all the linked issues.

Can we agree that you should be able to (from a Playwright project) reference some of your existing code if you want to? Even if some of that code contains legacy decorators? I think that's a reasonable ask.

Here's a real use case for us: We have a large monorepo backend written in Node. From our tests, we currently often need to call our existing code for setting up the preconditions for a particular test (like creating a user). Since our existing code uses Dependency Injection, we now can't do that, and our test becomes very limited.

*Any* type of project relying on Dependency Injection will now have this issue. There are no DI libraries that I know of that do not rely on legacy decorators.

**Comment by pavelfeldman** [comment]
> Can we agree that you should be able to (from a Playwright project) reference some of your existing code if you want to?

Yes!

> Even if some of that code contains legacy decorators? I think that's a reasonable ask.

No, that would not be our expectations.

We expect that if the code requires non-standard treatment it would be referenced as a JS library rather than as the TS source. Or if you have a lot of TS code, we would also expect it to be pre-transpiled. I can imagine that you have a `lib/` folder that contains compiled code with the decorators, sitting next to your `/src`. Our expectations are that you point your tests to `/lib` rather than to `/src` in that case. VSCode and TypeScript are smart enough to handle this scenario with proper paths set in tsconfig. That's why I keep asking for a concrete use case.

**Comment by ffMathy** [comment]
But not with NX. NX uses way more advanced settings than just paths. I can't share a repro due to NDA.

Why not just provide a way to then modify your babel config a bit?

What is it that you are afraid of? A support nightmare? Just trying to understand from your perspective. Because right now I can only see positive sides of allowing for this customization.

**Comment by pavelfeldman** [comment]
We can only act on this issue if we get the use cases and upvotes. I'll mark it as P3 which means we'll look at it next time either when it reaches ~80-100 upvotes or when it is archived after 6 months due to limited interest. For now I would recommend to point to /lib instead of /src as it probably solves your problem.

**Comment by ffMathy** [comment]
No, that doesn't solve our problem. Where did you get this from?

Also, I think the part that's not supported by NX is that every tsconfig has an extends field.

Is it true this is not respected by Playwright?

**Comment by pavelfeldman** [comment]
> No, that doesn't solve our problem. Where did you get this from?

I asked a question and you did not respond, I assumed it worked. Why didn't it work?

> Also, I think the part that's not supported by NX is that every tsconfig has an extends field. Is it true this is not respected by Playwright?

This is not a chat, this is an issue tracker where you can report issues. If you have a use case where `extends` is not working per your expectations, please file a separate issue with a repro.

**Comment by ffMathy** [comment]
Oh, sorry. No, that won't work for us. The referenced libraries also have decorators on them because they are used by dependency injection.

**Comment by pavelfeldman** [comment]
> The referenced libraries also have decorators on them because they are used by dependency injection.

I am not sure I understand - I'm not aware of native support for decorators in Node.js, I assume decorators are transpiled into the plain JS using babel or TSC. So swapping /src to /lib should just work.

**Comment by ffMathy** [comment]
Ah, I misunderstood what you meant. Yes I suppose that could still work. Still looking forward for real support though, as it is tedious to work with.

**Comment by pavelfeldman** [comment]
Given the straightforward workaround, I would recommend swapping src/ for lib/. I am not sure I understand the "tedious" bit, but I'm sure it is a small price to pay for staying on the official language track. Closing as won't fix that has a workaround.

**Comment by MarcRoemmelt** [comment]
We are in the same situation as @ffMathy 

We use a large NX monorepo (which supports sharing untranspiled source code between packages) and re-use various tooling in our tests, e.g. for seeding data via the actual pipelines/repositories. Since all of those heavily rely on parameter-decorater based DI, this is quite the pain.

The only workaround as of now seems to transpile each library exclusively to use it in Playwright. I really wonder how not everyone using DI has this issue.

A way to customize the transpiling would be super appreciated.

**Comment by prewk** [comment]
Same here (NX/Angular), I've read this thread on multiple revisits and it always striked me how rude and dismissive it is.

 > straightforward workaround

It's not straightforward, people have large complex monorepos and are trying to use Playwright in it. As soon as Playwright sees a `@` it throws a fit, for what reason? Who is this helping?

> I'm sure it is a small price to pay for staying on the official language track

Is this directed at users of Playwright or the Angular team? Because the latter aren't here, listening.

**Comment by jericirenej** [comment]
It would be really great if Playwright would support this, especially for users of Angular and / or Nx. 

Currently, it is impossible to import anything from a file which contains or refers indirectly to some code that uses legacy decorators, even if the imported function or variable does not use them. 

Angular is one of the major frontend frameworks and being able to use some code from an existing repo that would facilitate creating selector helpers would certainly help in creating better test suites.

**Comment by bbenoist** [comment]
>Given the straightforward workaround, I would recommend swapping src/ for lib/. I am not sure I understand the "tedious" bit, but I'm sure it is a small price to pay for staying on the official language track. Closing as won't fix that has a workaround.

@pavelfeldman The "workaround" cannot work with our [NestJS](https://nestjs.com/) code since is never transpiled into JS ; as we use the [Bun](https://bun.sh/) runtime.

**Comment by JesusGonzalezA** [comment]
I wanted to start using component testing using mount utility (https://playwright.dev/docs/test-components).
In my repo, some components connect with my backend. To do so, they rely on some services that are constructed using dependency injection (inversify).
This error is prompted so it is a stopper for us

**Comment by geigerzaehler** [comment]
Here’s how I got experimental (legacy) decorators to work

1. Add [tsx](https://tsx.is/) as a dependency
2. Set `exeperimentalDecorators: true` in `tsconfig.json`
3. Use the following playwright.config.ts

```typescript
import "tsx";

// Prevent the `source-map-support` package used by playwright from taking care
// of remapping stack traces. Instead we want Node’s native source map support
// used by `tsx` to work.
delete Error.prepareStackTrace;

export default defineConfig({
  // Let `tsx` take care of transforming code
  build: { external: ["*"] },
});
```

**Comment by vitalets** [comment]
### Workaround
There is an internal non-public field in the Playwright config, that can provide custom babel plugins for the transformation flow. It can enable decorators support:
```ts
export default defineConfig({
  // @ts-expect-error non-public field
  '@playwright/test': {
    babelPlugins: [
      ['@babel/plugin-proposal-decorators', { version: '2023-11' }]
    ]
  },
});
```
Don't forget to install `@babel/plugin-proposal-decorators` itself.

### Testing
Tested on the latest Playwright 1.56.

File with decorator:
```js
// decorator.js
@annotation
class MyClass {}

function annotation(target) {
  target.annotated = true;
}

export { MyClass };
```
Test file, that imports `decorator.js`:
```js
// index.spec.js
import { test } from '@playwright/test';
import { MyClass } from './decorator';

test('test 1', async () => {
  console.log('MyClass annotated:', MyClass.annotated);
});
```
Running with decorators config - OK:
```
$ npx playwright test

Running 1 test using 1 worker

  ✓  1 index.spec.js:4:5 › test 1 (4ms)
MyClass annotated: true

  1 passed (510ms)
```
Running without decorators config - ERROR:
```
$ npx playwright test

SyntaxError: /.../decorator.js: Support for the experimental syntax 'decorators' isn't currently enabled (1:1):

> 1 | @annotation
    | ^
  2 | class MyClass {}
  3 |
  4 | function annotation(target) {
```
Hope it helps.
