### ISSUE TITLE
[Feature]: Provide the ability to use a external playwright server in the vscode extension

### ISSUE THREAD

**Issue by nithinhrao** [microsoft/playwright#29645]
### 🚀 Feature Request

I'd like to propose a new ability for the Playwright extension that allows users to pass an external Playwright server through the "playwright.env" in settings.json for VSCode.

### Example

Currently, I am passing the PW_REUSE_BROWSER option from settings.json like this:

```
{
  ...
  "playwright.env": {
    "PW_REUSE_SERVER": "ws://localhost:8990/"
  },
  ...
}
```

### Motivation

The primary motivation for this feature is to facilitate running the Playwright server on a client machine and connecting to it from non-GUI containers like Github Codespaces. This would allow developers to run Playwright in headed mode/debug through the extension by starting a server and passing the URI in "playwright.env", which is currently not possible in Codespaces.

**Comment by nithinhrao** [comment]
I have a PR to read PW_REUSE_BROWSER env and connect to it instead of starting one:
https://github.com/microsoft/playwright-vscode/pull/426

**Comment by nithinhrao** [comment]
I have a PR to read PW_REUSE_SERVER and connect to it instead of starting a new server:
https://github.com/microsoft/playwright-vscode/pull/426

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
