### ISSUE TITLE
[Feature]: Support features provided by injectedScript on pages with strict Content-Security-Policy settings

### ISSUE THREAD

**Issue by rafl** [microsoft/playwright#29654]
### 🚀 Feature Request

The features provided by injecting code into the page under test, such as locator highlighting, are extremely helpful. Unfortunately, they don't currently work as you'd expect them to on pages with strict Content-Security-Policy settings, for example when no inline-styles such as the ones injected by `Highlight.install()` are allowed without the appropriate `nonce` as specified in the security headers. Highlights will be displayed in the wrong places, injected images won't be displayed, etc.

This makes playwright a less useful tool, unless site developers put additional effort into working around this issue, which has a number of potential practical downsides.

### Motivation

* This would improve the developer experience when working on modern sites that take security seriously.
* It'd avoid extra development work in order to make full use of playwright's features.
* It'd avoid the temptation to weaken security-restrictions only to be able use a testing tool to its full extent.
* It'd eliminate the chance of bugs being introduced by conditionally using different security policies between production and testing.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
