### ISSUE TITLE
[Bug]: Permissions: Sending MIDI Sysex (still) causes Chrome to crash

### ISSUE THREAD

**Issue by melkerydman** [microsoft/playwright#29686]
### Version

1.41.2

### Steps to reproduce

Opening up a new issue since [this](https://github.com/microsoft/playwright/issues/14346) was closed, and I experience the exact same problem.

The original repo still includes a working repro - https://github.com/lozjackson/plawright-midi-test

### Expected behavior

If running the project without Playwright, or without setting `context.grantPermissions(["midi", "midi-sysex"], { origin: "http://localhost:8080" });` you're prompted to manually allow midi, and everything works as expected.

As described in repo: 
- Sending CC messages works. You can see a log of sucessfully sent messages in the page
- Sending Sysex messages works. You can see a log of sucessfully sent messages in the page

### Actual behavior

As described in repo: 
- Sending CC messages works. You can see a log of successfully sent messages in the page
- Sending Sysex messages causes Chrome to crash and display the "Aw Snap" page - `Error code: RESULT_CODE_KILLED_BAD_MESSAGE`

### Additional context

See original issue, it describes the issue better than I could :)

### Environment

```shell
System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M2
  Memory: 87.95 MB / 16.00 GB
Binaries:
  Node: 18.16.0 - /nix/store/mfrzb46340qzyzf0laa24y0xg06xsif9-nodejs-18.16.0/bin/node
  npm: 9.5.1 - /nix/store/mfrzb46340qzyzf0laa24y0xg06xsif9-nodejs-18.16.0/bin/npm
npmPackages:
  playwright: ^1.41.2 => 1.41.2
```

**Comment by pavelfeldman** [comment]
Chrome Issue: https://issues.chromium.org/issues/327245889

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
