### ISSUE TITLE
[Bug]: testOptions.locale doesn't work with webkit

### ISSUE THREAD

**Issue by ladiza** [microsoft/playwright#29690]
### Version

1.41.2

### Steps to reproduce

1. In playwright config set:
`use: {
	locale: 'cs',
}`
2. Start test in webkit browser, check request headers made by browser

### Expected behavior

Accept-Language header is set to just 'cs'

### Actual behavior

Accept-Language header is set to 'cs, en-US'
![image](https://github.com/microsoft/playwright/assets/55128628/83d4f2da-0941-449d-9c6f-39ec7e8ac420)

### Additional context

Our application under test uses some templating which accepts just 'cs' or just 'en'. So when the header Accept-Language is sent as 'cs, en-US' textations break down and instead of some texts, this is displayed in the GUI: 
{cs='some czech text', en='some english text'}

Apparently on chromium and on firefox it behaves as it should, both browser sends Accept-Language just as 'cs' when set accordingly in playwright config.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
    Memory: 5.82 GB / 16.00 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE      
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD        
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
