### ISSUE TITLE
[Bug]: Typescript tests raise TypeError when one of project or file is a module

### ISSUE THREAD

**Issue by fedetibaldo** [microsoft/playwright#29747]
### Version

1.42.0

### Steps to reproduce

I'll start by saying that this is a duplicate of the (wrongly) closed #15862.
I've created a minimal reproduction of the issue at this repository: https://github.com/fedetibaldo/playwright-typescript-module-bug

### Expected behavior

When the extension of my test file is `.mts` or my project contains `"type": "module"` in the package JSON, my typescript test cases should run.

### Actual behavior

The test suite fails early due to a `TypeError: Unknown file extension` when reading the test file.

### Additional context

The failure is likely at this line: https://github.com/microsoft/playwright/blob/0da29959fa1274b352f34b19f22a8a3cfdd70bbe/packages/playwright/src/transform/transform.ts#L210

### Environment

```shell
System:
  OS: macOS 14.3.1
  CPU: (12) arm64 Apple M2 Pro
  Memory: 182.27 MB / 16.00 GB
Binaries:
  Node: 21.6.2 - ~/Library/Caches/fnm_multishells/24647_1709235810724/bin/node
  Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/1559_1709042388318/bin/yarn
  npm: 10.2.4 - ~/Library/Caches/fnm_multishells/24647_1709235810724/bin/npm
  pnpm: 8.9.2 - ~/Library/Caches/fnm_multishells/11525_1709222999745/bin/pnpm
IDEs:
  VSCode: 1.86.0 - /opt/homebrew/bin/code
Languages:
  Bash: 5.2.26 - /opt/homebrew/bin/bash
npmPackages:
  @playwright/test: ^1.42.0 => 1.42.0
```

**Comment by pavelfeldman** [comment]
Playwright needs to know whether it should be installing EMS loader when it starts. We will do that based on the type of the config. If config is a module, the loader will be installed. You can create a `playwright.config.mts` file to work around this issue.

```js
import { defineConfig } from '@playwright/test';
export default defineConfig({});
```

In the newer versions of Node, a better loader injection is supported, so this issue will resolve on its own over time. I'll keep this issue open so that we could close it when it happens.
