### ISSUE TITLE
[Feature]: Expose `testInfo.config.ignoreSnapshots`

### ISSUE THREAD

**Issue by Conduitry** [microsoft/playwright#29837]
### 🚀 Feature Request

The current value of the `ignoreSnapshots`/`--ignore-snapshots` option is not available to test code, at least not in an official way. It would be nice to have access to this.

### Example

I have a bunch of tests that are using a snapshot-esque mechanism without using the official snapshot mechanism. Currently, the operation of these tests are controlled via environment variables (ignore snapshots, create missing snapshots, update snapshots, etc.). Especially as I'm considering some new tests that would use official the snapshot mechanism, it would be confusing to need to specify both environment variables (for custom snapshots) and command line parameters (for official snapshots) to control the behavior.

### Motivation

As mentioned in the example, this would be to enable custom snapshot mechanisms that could be controlled the same way as the built-in snapshot mechanisms.

The adjacent `updateSnapshots`/`--update-snapshots` option is already exposed in `testInfo.config.updateSnapshots`.

`ignoreSnapshots` is in fact also already exposed in `testInfo.config`, although under a symbol key - `Symbol(configInternalSymbol)` - which is definitely not a public API.

**Comment by dgozman** [comment]
Note: we would likely expose this as `testInfo.project.ignoreSnapshots`.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
