### ISSUE TITLE
[Bug]: waitForURL has different behaviour when 'trace: on-first-retry' is set

### ISSUE THREAD

**Issue by 3rg1s** [microsoft/playwright#29858]
### Version

1.42.0

### Steps to reproduce

1. Clone https://github.com/3rg1s/playwright-on-retry-repo
2. cd into `playwright-on-retry-repo`
4. run `npm install`
5. run `npx playwright test`

### Expected behavior

Should pass the test

### Actual behavior

Test fails to pass, perhaps waitForURL is not waiting for the URL

### Additional context

Test passes without any error, when using `trace: 'retain-on-failure'`

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 704.63 MB / 32.00 GB
  Binaries:
    Node: 20.6.0 - ~/.nvm/versions/node/v20.6.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.6.0/bin/yarn
    npm: 10.4.0 - ~/.nvm/versions/node/v20.6.0/bin/npm
  IDEs:
    VSCode: 1.87.0 - /usr/local/bin/code
  Languages:
    Bash: 5.2.15 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.42.0 => 1.42.0 
    playwright: ^1.42.0 => 1.42.0
```

**Comment by 3rg1s** [comment]
Based on previously created issue: https://github.com/microsoft/playwright/issues/29653

**Comment by dgozman** [comment]
@3rg1s Thank you for the repro. I've played around with it:
- running with `trace: 'off'` makes it fail;
- running with `trace: 'retain-on-failure'` makes it pass.

I think the problem is that page takes some time to store "redirect to /ar" information, most likely in the local storage.
For example, waiting for a second before `3. Navigate again to /` makes the test pass no matter what.

Tracing makes things a bit slower and affects the timing, that's why you the issue seems to depend on the trace setting. However, if you run the test on a slow computer, e.g. on CI, it would exhibit the same behavior. To fix the test, you should wait for the page to actually persist the chosen language, maybe with a `page.waitForFunction()` call that reaches into page's internals.

As a side note, you should use auto-retrying assertions for things like checking the url:
```ts
// This might be flaky, depending on the timing.
expect(page.url()).toBe(`${baseURL}/ar`);

// This is a recommended way that automatically retries.
await expect(page).toHaveURL(`${baseURL}/ar`);
```

**Comment by 3rg1s** [comment]
Hello @dgozman, thank you for your response. I see where the issue was with the way I wrote the tests. Thanks for providing the recommended way as well. I will close this 'Issue'.
