### ISSUE TITLE
[Bug]: VSCode extension for Playwright: unable to find Node.js exec

### ISSUE THREAD

**Issue by ladiza** [microsoft/playwright#29898]
### Version

-

### Steps to reproduce

Prerequisities: Any playwright project, VSCode with extension "Playwright Test for VSCode" (I have version 1.0.22)
1. Go to Windows environment variables.
2. create new record in Path system variable, which looks like a path to shared network resource e.g. "\\\\myOrg.com\resources"
3. Move the record to the top of the list.
4. Start cli and make sure, that the node -v still yields version number
5. Start your project in VSCode
6. Go to Testing tab and look at tests loaded by the extension

### Expected behavior

I expect to see a list of tests, ready to run

### Actual behavior

I see message "No tests, have been found in this workspace yet."
VSCode console says:
```
[Playwright Test]: Unable to find 'node' executable.
Make sure to have Node.js installed and available in your PATH.
Current PATH: '\\myOrg.com\resources;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\Username\AppData\Local\Microsoft\WindowsApps;C:\Users\Username\AppData\Roaming\npm;C:\Users\Username\AppData\Local\Programs\Microsoft VS Code\bin'.
```
But I can clearly see "C:\ProgramFiles\nodejs" in the path and also the commands in cli works normally.

### Additional context

I know that by far the easiest solution is to move my nodejs path to the top, but in corporate environment it is not that easy. And since everything else works correctly even when setup like this, I suppose its probably the extensions problem.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
    Memory: 5.82 GB / 16.00 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE      
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD        
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
```

**Comment by mxschmitt** [comment]
Hi! Yes, the repro was excellent. It will be fixed in the next update for the VSCode extension. We unfortunately can't give an eta for when we release.

**Comment by craiggunson** [comment]
I solved this by dropping NVM and installing node to a more well known path.   (in my case /usr/local/bin/node) then the plug in works fine, finds test etc..

**Comment by ladiza** [comment]
Hi, @craiggunson, thanks for the update. In our case it was indeed a bug on playwrights side. The bug should not occur now, also it should not be important where your node is installed as long as the PATH variable is pointing to correct place.
I am not even sure if this was problem on unix devices (which you are probably on, considering the file path you showed), we had the problem on AD managed Windows.

**Comment by mpagot** [comment]
Other extensions (vitest) are providing a nodeExecutable setting

**Comment by rkrisztian** [comment]
I agree with @mpagot, I think this issue should be reopened. The Playwright extension should support a `nodeExecutable` or `nodePath` setting like other plugins do (Vitest, ESLint, SonarQube for IDE, etc.). I don't have a global installation of Node, and I don't plan to, because **each of my projects should define the Node path** for the version it requires. Then, I can use **per-project workspace settings** to store the Node path on my machine without committing the settings (VSCode supports workspaces in the File menu).

**Comment by jbergens** [comment]
I just got this error on Windows. When I open a terminal and check the path it has a node executable on it. It looks like Playwright is using the system path instead of the user path or something similar. Would be nice if it were a setting and even better if you could add a path for each project since they may use different node versions.
