### ISSUE TITLE
[Feature]:  Playwright extension for VSCode setting to set the path to the node executable

### ISSUE THREAD

**Issue by git-nico** [microsoft/playwright#29913]
### 🚀 Feature Request

I am always using the portable version of vscode in combination with a portable version of node. For opening terminals in vscode and also for some of the other extensions I use, I can set the PATH to node in the vscode settings. Unfortunately this is not (yet) possible for the Playwright extension and without node in the environment PATH the extension is not working. 

### Motivation

It will allow portable vscode to use playwright without the need to alter the system environment.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
