### ISSUE TITLE
[Feature]: Extend selectors to include finding by images 

### ISSUE THREAD

**Issue by craitose** [microsoft/playwright#29969]
### 🚀 Feature Request

Would be nice to extend existing selectors with a find element by image, with an image passed via file. 

### Example

Appium has something similar https://github.com/appium/appium-base-driver/blob/c750e6e1fe36d870bca73a1e9f7909ec5b594cf7/lib/basedriver/commands/find.js#L48 exploiting the good OpenCV library. Once an element has been found we should allow any following element action (click, type, etc..) is also supported by this new type of element (interaction is via pixel coordinates).

### Motivation

I know we have visual testing but I find it more useful to have that inbuilt directly in the test flows, more than play with global screenshots and matching if specific elements in them, plus helps to keep the business flows clear within the tests and a closer focus on the UX/UI.

**Comment by craitose** [comment]
Perhaps there is a way that I am just not aware of but I would like to be able to locate an image on HTML Canvas and click on it's location based on the matching image file.

**Comment by mxschmitt** [comment]
This would make tests dependent on the operating system, since browsers rasterise text differently based on the operating system. Sounds not like something we'd like to have in the core of Playwright - if you still want to have something like this implemented, you could create a custom selector engine: https://playwright.dev/docs/extensibility#custom-selector-engines

Folding into https://github.com/microsoft/playwright/issues/8274.

**Comment by craitose** [comment]
@mxschmitt could you provide an example of a custom selector engine that does what I require?
