### ISSUE TITLE
[Docs] Improve documentation for addLocatorHandler

### ISSUE THREAD

**Issue by Rafiot** [microsoft/playwright#30003]
### Page(s)

https://playwright.dev/docs/api/class-page#page-add-locator-handler

### Description

So I hope I'll not be hurting your soul too much with that one, but I really need to trigger the locator handler at an arbitrary time without doing anything else (I need to be able to bypass the cookies authorization on arbitrary websites).

My workaround is to run do that: 

`await page.locator("body").click(button="right")`

Which does nothing, but triggers the locator handlers whenever I want them triggered.

The full commit looks like that:

https://github.com/Lookyloo/PlaywrightCapture/commit/26348f7bf5f28f7d6c6a6d48cb41fe77ed99f6f5

Maybe two things:

1. Add in the documentation that the locator handlers are only checked when there is an action, it wasn't clear to me before I found this bug https://github.com/microsoft/playwright/issues/29701
2. Add a way to forcefully trigger the locator handlers?

**Comment by yury-s** [comment]
> Add a way to forcefully trigger the locator handlers?

You can extract the handler in a function and call it whenever you want in the tests, would that work for you?

**Comment by Rafiot** [comment]
I could, but I have a bunch of them (currently 6, most probably many more later) and using the locator handler seemed like a cleaner way to do it (?). But, now you say that, internally, they are all triggered sequentially, right?

**Comment by yury-s** [comment]
> I could, but I have a bunch of them (currently 6, most probably many more later)

You have flexibility to chose which one you need or you can wrap all of them in a function too.

> and using the locator handler seemed like a cleaner way to do it (?).

Locator handlers are only triggered during an action/assertion, I'm updating the docs to make it more clear.

> But, now you say that, internally, they are all triggered sequentially, right?

Yes.

**Comment by azad-resolver** [comment]
I agree that the documentation for `addLocatorHandler` could be improved, in terms of where it should be implemented.
The docs and the code example don't seem to give any indication at all. Where do we put the handler to make sure it gets automatically activated? Is it an auto-fixture? The docs fail to mention any of this.

Also, regarding this part:

> After executing the handler, Playwright will ensure that overlay that triggered the handler is not visible anymore.

What happens if the overlay is encountered again? Is there a way to specify what playwright should do next (e.g. abort the test)? Or will it just endlessly retry handling it until the test timeout is reached?
