### ISSUE TITLE
[Bug]: Permission denied: I can't click on Checkbox inside an iframe

### ISSUE THREAD

**Issue by dispotic1002** [microsoft/playwright#30032]
### Version

1.42.0

### Steps to reproduce

Playwright Version: 1.42.0
Windows 10
Browser: Firefox

### Expected behavior

**The error I get:** 
`playwright._impl._api_types.Error: Protocol error (Page.describeNode): error in channel "content::11/14/2": exception while running method "describeNode" in namespace "page": Permission denied to access property "docShell" on cross-origin object _describeNode@chrome://juggler/content/content/PageAgent.js:417:47 `

### Actual behavior

**explanation:**
When I try to run this code on the Firefox browser, it gives me this error, with the same code and everything. If I change to Chromium, it works without problems and does not give me any error, knowing that I tried to use **playwright's locator and frame_locator classes**: also the same problem and the same result in the Firefox browser. Only one who has this problem. webKit or Chromium work without problems.
I tried to use the library in all programming languages, and it leads to the same problem. I have tried most versions and there is no benefit.

### Additional context

```
from playwright.sync_api import sync_playwright

def find_and_click_checkbox(page):
    iframe = page.query_selector('iframe')
    if iframe:
        frame = iframe.content_frame()
        checkbox = frame.query_selector('input[type="checkbox"]')
        if checkbox:
            checkbox.click()
            print("Checkbox found and clicked inside iframe.")
        else:
            print("Checkbox not found inside iframe.")
    else:
        checkbox = page.query_selector('input[type="checkbox"]')
        if checkbox:
            checkbox.click()
            print("Checkbox found and clicked.")
        else:
            print("Checkbox not found on the page.")

with sync_playwright() as p:
    browser = p.firefox.launch(headless=False)
    context = browser.new_context( )
    page = context.new_page()
    page.goto('https://dash.nocaptchaai.com')
    input()
    find_and_click_checkbox(page)
    browser.close() 
```

### Environment

```shell
.
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
