### ISSUE TITLE
[Feature]: UI Mode: Allow starting/queuing tests while tests are being run

### ISSUE THREAD

**Issue by n4bb12** [microsoft/playwright#30090]
### 🚀 Feature Request

If tests are currently being run, it's not possible to trigger new tests until all queued tests completed. This seems like an artificial limitation.

### Example

Where this would be useful
- Enqeueing a test for retry
- Starting a hand full of individual tests from different files by clicking [Run] on each of them. The search / filter capabilities are usually not sufficient or not practical to match an arbitrary one-off  set of tests just for being able to start them in unison.

### Motivation

It would be a productivity boost.

Waiting for tests to complete or switching contexts and then forgetting to enqueue a test at the right time that you wanted to run earlier that could have been queued and then would have completed minutes ago, is not an ideal workflow.

**Comment by pavelfeldman** [comment]
This would result in additional complexity of the UI with the scheduled run sessions and their management. I'll leave it as P3, but it is unlikely to be implemented.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
