### ISSUE TITLE
[Feature]: do not wrap command output in ascii box

### ISSUE THREAD

**Issue by tills13** [microsoft/playwright#30126]
### 🚀 Feature Request

When attempting to run playwright before the appropriate browser and system packages are installed, a command to run is printed in an ascii box.

![image](https://github.com/microsoft/playwright/assets/1269421/550c2d83-bdf4-4efa-abf3-acdf69ecb153)

When copying the command, the ascii box is selected as well. 

I propose delimiting the command with top and bottom bars to ensure it's more visible but _not_ a full box. 

### Motivation

Streamlines the process for new users.

**Comment by pavelfeldman** [comment]
We should have prioritized ergonomics over the beauty here :smile:. Did `npx playwright install-deps` not work for you?

**Comment by tills13** [comment]
It did... but I will say a) I didn't even see that command at first and b) I'm a little uncomfortable running `sudo npx ...` anything 

while I do trust the maintainers of this repo supply chain attacks are increasing and it's nice to know what I'm running

If you're OK with like 

```
====================

<the same output

====================
```

I'll open a PR later

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
