### ISSUE TITLE
[Feature]: add counter to `snapshotPathTemplate`

### ISSUE THREAD

**Issue by SrBrahma** [microsoft/playwright#30130]
### 🚀 Feature Request

The option `snapshotPathTemplate ` should allow to explictly define the counter of the screenshots there, even if we pass a name the function, such as `toHaveScreenshot('foo')`.

The above could create the following filename: `1-foo-chromium-linux.png`

### Example

```ts
// playwright.config.ts
{
  snapshotPathTemplate: '{snapshotDir}/{testFileDir}/{testFileName}-snapshots/{counter}{-name}{-projectName}{-snapshotSuffix}{ext}';
}
```

### Motivation

If we don't pass a name to `toHaveScreenshot()`, the filename will have a counter.

If we pass a name, there won't be a counter.

The counter is useful, and so is the name of the screenshot. The counter keeps the files sorted and allows the dev to see the timeline of the events, and the name gives a summary of what the screenshot is about.

We can't simply have  `toHaveScreenshot('1-foo)`  `toHaveScreenshot('2-bar')`, as if this screenshot taking is somewhere else, like in a common function, we can't properly keep track of it, and the counter could not match the expected values.

The default is defined here
https://github.com/microsoft/playwright/blob/021c5c108c6a1166c1d2b701aafb9f021fe0cfca/packages/playwright/src/common/config.ts#L174

**Comment by SrBrahma** [comment]
Also, it this become a possibility, I would like to left pad it with a 0, so `10-xyz` doesn't appear before `2-xyz`, as it would be `02-xyz`.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
