### ISSUE TITLE
[Feature]: darwin find chrome/edge in ~/Applications

### ISSUE THREAD

**Issue by Le0Developer** [microsoft/playwright#30157]
### 🚀 Feature Request

Find binaries (like Google Chrome) in ~/Applications as well, since this is where you install applications that are only for the current user.

This is the official location for user-specific applications, as indicated by the special directory icon in Finder.

### Example

```js
await pw.chromium.launch({ channel: "chrome" }) // google chrome in ~/Applications
```

### Motivation

No need to install Google Chrome/Edge globally for testing.

**Comment by Le0Developer** [comment]
The functionality for multiple install locations is already implemented for Windows, so it can be easily added here: 
https://github.com/microsoft/playwright/blob/ffffb81c3b935b7c9c8b310f51e2fa1fdd522843/packages/playwright-core/src/server/registry/index.ts#L658-L660

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
