### ISSUE TITLE
[Docs]: Incorrect description for Frame.name

### ISSUE THREAD

**Issue by rushter** [microsoft/playwright#30167]
### Page(s)

https://playwright.dev/python/docs/next/api/class-frame#frame-name

### Description

The documentation says that it will return frame ID in case there is no name, but the actual code just returns an empty string.
https://github.com/microsoft/playwright-python/blob/7e5f197bf0402f7f292a36e5e30fcb75a038a3c2/playwright/_impl/_frame.py#L427

**Comment by rushter** [comment]
Thanks. Just to clarify, there are Frame IDs in CDP, and when I was reading the docs, I thought that I would get them as a result.

https://chromedevtools.github.io/devtools-protocol/tot/Page/#type-FrameId

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
