### ISSUE TITLE
[Feature]: allow to pass arbitrary location to test.step

### ISSUE THREAD

**Issue by vitalets** [microsoft/playwright#30160]
### 🚀 Feature Request

Currently `test.step` method binds location in file to the place of it's call. 
When `test.step` is wrapped with helper methods, it produces the same location for different steps.
Suggestion is to allow to pass arbitrary location to `test.step`. See example below.

### Example

Imagine I have a `helper.ts` where I define step helper for my tests:
```ts
export async function clickButton(text: string) {
  return test.step(`User clicks button "${text}"`, async () => {
    // ...
  }); 
}
```
Now I run the following test from `./e2e/test.ts`:
```ts
test('test', async ({}) => {
  await clickButton('foo');
  await clickButton('bar');
  await clickButton('baz');
});
```
In the report I get all steps with the same location:
<img width="50%" src="https://github.com/microsoft/playwright/assets/1473072/06191a10-4d0b-4b85-9d90-74079dff88f1">

It would be great to see more meaningful locations in the report, e.g.:
```
User clicks button "foo"— e2e/test.ts:2
User clicks button "bar"— e2e/test.ts:3
User clicks button "baz"— e2e/test.ts:4
```

If I were able to provide a custom location to `test.step`, I would achieve it. Example:
```ts
import { Location } from '@playwright/test/reporter';
import errorStackParser from 'error-stack-parser';

export async function clickButton(text: string) {
  const location = getStepLocation();
  return test.step(`User clicks button "${text}"`, async () => {
    // ...
  }, { location }); 
}

function getStepLocation(): Location {
  const frame = errorStackParser.parse(new Error()).find((frame) => frame.fileName.endsWith('.test.ts'));
  return {
      file: frame.getFileName(),
      line: frame.getLineNumber(),
      column: frame.getColumnNumber(),
  };
}
```

### Motivation

In general this feature provides more opportunities for writing high order step helpers.

Personally, I need it for managing `playwright-bdd` project. I'm wrapping `test.step` with `Given / When / Then` helpers to have correct step titles in the report:
```ts
const Given = (text: string) => test.step(`Given ${text}`, () => { ... });
const When = (text: string) => test.step(`When ${text}`, () => { ... });
const Then = (text: string) => test.step(`Then ${text}`, () => { ... });
```
Before Playwright 1.43 [I've used](https://github.com/vitalets/playwright-bdd/blob/v6.0.3/src/playwright/testTypeImpl.ts#L43) private `testInfo._runAsStep` method to run step with a custom location. Since 1.43 `testInfo._runAsStep` was replaced with a more complex logic and now I need [more tricky hacks](https://github.com/vitalets/playwright-bdd/blob/dd1f38d26b099ea5ff0bb38155947452c38f0a18/src/playwright/testTypeImpl.ts#L54) to achieve the same.

**Comment by pavelfeldman** [comment]
If you use boxing in the test.step it'll give you the right locations. https://playwright.dev/docs/release-notes#hide-implementation-details-box-test-steps

**Comment by vitalets** [comment]
> If you use boxing in the test.step it'll give you the right locations. https://playwright.dev/docs/release-notes#hide-implementation-details-box-test-steps

Yes, but it boxes only 1 stack frame up (I think because of [this line](https://github.com/microsoft/playwright/blob/release-1.43/packages/playwright/src/worker/testInfo.ts#L271)). If I wrap my `clickButton` into another function, locations become incorrect:
```ts
export async function clickButton2(text: string) {
  return clickButton(text);
}

export async function clickButton(text: string) {
  return test.step(`User clicks button "${text}"`, async () => {
    // ...
  }); 
}
```
Running:
```ts
test('test', async ({ }) => {
  await clickButton2('foo');
  await clickButton2('bar');
  await clickButton2('baz');
});
```
Output:
<img width="50%" src="https://github.com/microsoft/playwright/assets/1473072/8697f13e-8dca-412c-96a0-e2d531a50057">

**Comment by pavelfeldman** [comment]
That's because you did not box clickButton2. Any time you want to pass location to step, box it instead.

**Comment by vitalets** [comment]
> ```ts
> return test.step(
> ```

So I've re-written it this way:
```ts
export async function clickButton2(text: string) {
  return test.step('dummy step', () => clickButton(text), { box: true });
}
```
No it works. But I need to pass this `dummy step` every time I need to wrap helper.
I've also tried to pass empty string as a step title, but the report shows these empty steps as well:
<img width="40%" src="https://github.com/microsoft/playwright/assets/1473072/463c757d-1c71-4085-aa5a-3d4179e67c68">

And it creates an unnesessary step structure:
<img width="40%" src="https://github.com/microsoft/playwright/assets/1473072/0a7153f1-31f5-45ce-9433-daf6e538d53c">

I think just passing location is a more convenient option (if there no other difficulties).

**Comment by pavelfeldman** [comment]
That's something we can fix, open to making the step title optional. Marking as open to a pr.

**Comment by vitalets** [comment]
> Imagine I have a bunch of helpers that re-uses each other, the report structure in that case would reflect all this nesting. Although I just want flat steps with custom locations.

Will these empty-title steps keep nesting structure? Because I'm caring about this:

> Imagine I have a bunch of helpers that re-uses each other, the report structure in that case would reflect all this nesting. Although I just want flat steps with custom locations.

**Comment by WestonThayer** [comment]
We had this implemented us the non-public `TestInfo._runAsStep` API, but are now working on replacing it with `test.step` and `box: true` since v1.43 removed `_runAsStep`. Similar to others, we'd be fine with a custom location as well, we'd already built it for the previous implementation.

**Comment by osohyun0224** [comment]
Hello! :) @vitalets I made https://github.com/microsoft/playwright/pull/32504 PR
PTAL when you have time ... !

**Comment by vitalets** [comment]
> Hello! :) @vitalets I made #32504 PR PTAL when you have time ... !

Thank you!
Let's wait for Playwright team members to check.
@pavelfeldman

**Comment by dgozman** [comment]
@vitalets @osohyun0224 @WestonThayer @jan-molak Are you generating your playwright tests? We have discussed this with the team, and feel like for generated tests the best solution would be a source map. It is an established technology that gives you plenty of control over source locations. Let me know what you think.

**Comment by jan-molak** [comment]
Hi @dgozman and thanks for looking into this!

Serenity/JS doesn't generate Playwright tests, so source maps would not be appropriate in our case and being able to specify the location would be ideal.

To give you some more context, Serenity/JS [integrates with Playwright Test](https://serenity-js.org/handbook/test-runners/playwright-test/) and uses `test.step` API to make the descriptions of Serenity/JS tasks appear in Playwright Test reports, like [this one](https://serenity-js.github.io/serenity-js-playwright-test-template/playwright/#?testId=ccf068a57520f3c40c25-8bbb24cc36328d17e7ae):

<img width="994" alt="Screenshot 2024-09-10 at 22 50 49" src="https://github.com/user-attachments/assets/43beb50a-8695-4524-ab91-43ef71d68d66">

This integration also offers nice developer experience in VSCode with the Playwright extension:

![Serenity/JS Playwright Test scenario](https://serenity-js.org/assets/images/vs-code-running-test-scenarios-863f1cb60c7bf3dead8348fb1b147d39.gif)

Since, at the moment, the public [`test.step`](https://playwright.dev/docs/api/class-test#test-step) API does not allow for the caller to override the `location`, Serenity/JS Playwright Test integration has to [monkey-patch the `testInfo._addStep` method](https://github.com/serenity-js/serenity-js/blob/736cbf65799edb0fb2b1e25c19487f26b077f701/packages/playwright-test/src/api/PerformActivitiesAsPlaywrightSteps.ts#L22-L44). 

The need to monkey-patch is not ideal. However, this approach allows us to inject the location where the Serenity/JS task is instantiated in the test file (or in a user-land test library) instead of where the `test.step` is invoked somewhere inside the Serenity/JS framework. Of course, the user-land location is what developers writing Serenity/JS scenarios care about.

As per my [previous suggestion](https://github.com/microsoft/playwright/issues/30160#issuecomment-2045463854), we'd love for the `test.step` API to allow the caller to specify the `location`. For example:

```ts
test.step('my step', () => { ... }, { location: { ... } })
```

If your team prefers to keep the `test.step` method as is, another approach would be for Playwright Test to introduce a separate integration-specific API that achieves the same objective.

I'd be happy to answer any other questions your team has and collaborate on a solution.

**Comment by dgozman** [comment]
@vitalets @jan-molak Thank you for the information. We decided to proceed with adding `location` to `test.step`, so I am reviewing #32504.

**Comment by osohyun0224** [comment]
Sorry for the late reply.
I also think it is right to implement it by adding it as an option to the existing functions of @vitalets  and @jan-molak . If there are more ways to utilize your Source Map scalability method, then consider it again. 
First of all, I think what @vitalets  and @jan-molak suggested is correct in order to implement it the way we want.

I understood @vitalets  and @jan-molak  opinions well, and it's really cool! 👏🏻
I will be happy to answer any other questions the Playwright team may have and work with them to find a solution.

**Comment by WestonThayer** [comment]
@dgozman apologies for the delay as well. We also are not generating tests, we have a custom fixture similar to Page optimized for accessibility testing (it has access to a screen reader, etc). It has methods analogous to `Page.goto()` that make sense to show up as test steps in the report, and we have similar issues where it's not always possible to keep all `test.step()`s at the top level so boxing works.

**Comment by vitalets** [comment]
Thank you!
