### ISSUE TITLE
[Docs]: Update documentation on basic authentication with pytest

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#30182]
### Page(s)

https://playwright.dev/python/docs/auth

### Description

I'd like to add a section on basic authentication for pytest. 

```python
#In conftest.py, add the following:

@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        "http_credentials": {'username': E2E_USERNAME, 'password': E2E_PASSWORD},
    }

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by mascala** [comment]
It would be really good explanation. At least I could’ve found it here 👍
