### ISSUE TITLE
[Docs]: Unclear docs on broser.close() behavior about closing attached contexts

### ISSUE THREAD

**Issue by himat** [microsoft/playwright#30299]
### Page(s)

https://playwright.dev/docs/api/class-browser#browser-close

### Description

The doc page for `browser.close()` says:

```
In case this browser is obtained using [browserType.launch()](https://playwright.dev/docs/api/class-browsertype#browser-type-launch), closes the browser and all of its pages (if any were opened).

In case this browser is connected to, clears all created contexts belonging to this browser and disconnects from the browser server.
```
and then
```
NOTE
This is similar to force quitting the browser. Therefore, you should call [browserContext.close()](https://playwright.dev/docs/api/class-browsercontext#browser-context-close) on any [BrowserContext](https://playwright.dev/docs/api/class-browsercontext)'s you explicitly created earlier with [browser.newContext()](https://playwright.dev/docs/api/class-browser#browser-new-context) before calling [browser.close()](https://playwright.dev/docs/api/class-browser#browser-close).
```

The NOTE is confusing because it says that I need to close every context myself first before calling `browser.close()`, but the second line in the main part of the docs say that for connected browsers, this will clear all the contexts for me.

So I wanted to clarify if the NOTE only applies to sentence 1 in which case yes the user should clear the contexts first manually, OR is sentence 2 actually wrong, and even in the case of a remotely connected browser (over the CDP websocket URL), that we still need to manually clear the contexts first, OR is the NOTE itself entirely wrong?

**Comment by mxschmitt** [comment]
"connected to" in this case refers to [BrowserType.connect](https://playwright.dev/docs/api/class-browsertype#browser-type-connect) while the first paragraph is about launching the browser via [BrowserType.launch](https://playwright.dev/docs/api/class-browsertype#browser-type-launch).

The note applies to both, ideally you always close the context before you close the browser, otherwise it will impact negatively on e.g. video generation/har exports etc.

**Comment by himat** [comment]
@mxschmitt, I assume "connected to" also applies to [BrowserType.connectOverCDP](https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp)? Is that correct?

> otherwise it will impact negatively on e.g. video generation/har exports etc.
Could you explain this more? Would this only be true if there is still video generation/har exports going on when you close the browser? It would be the same if you closed the context though right - it could be in the middle of those then too?

**Comment by mxschmitt** [comment]
> I assume "connected to" also applies to [BrowserType.connectOverCDP](https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp)? Is that correct?

Yes, this also applies to connectOverCDP as well.

> otherwise it will impact negatively on e.g. video generation/har exports etc.

Har exports get saved when the context is gracefully closed. Browser.close will just close the browser immediately, and not do that, it would just abort them. Regarding video, saving the video via [saveAs](https://playwright.dev/docs/api/class-video#video-save-as) is also not possible, since the Page/Context/Browser is already gone.

I'm not following the "it could be in the middle of those then too?".

Are you running in some kind of issue with your code?

**Comment by himat** [comment]
Oh I see. The "it could be in the middle of those then too?" was about when you do context.close(), I thought that would also kill any har exports that are in the middle of exporting, but seems like the har exports only start when context.close() is called, so that would be fine it seems.

But I guess for video, you would need to call the `saveAs` before even closing the context yourself manually then?

**Comment by mxschmitt** [comment]
Yes, saveAs needs to happen before the context closes.

Closing as per above.
