### ISSUE TITLE
[Feature] Option turn on/off or override After hooks 

### ISSUE THREAD

**Issue by EldoradoEU** [microsoft/playwright#30309]
### 🚀 Feature Request

Is it possible to override fixtures in After Hooks or just turn off them?

We want execute test case with debug port 9222.
playwright.config.ts
  projects: [
    {
      name: 'Test',
      use: {
        channel: 'msedge',
        launchOptions: {args: ['--remote-debugging-port=9222']},

      },
    },
  ],
![Zrzut ekranu 2024-04-09 132738](https://github.com/microsoft/playwright/assets/84720864/c4427544-daef-44e6-acf9-9171934e6e55)

Don't close browser afer executing this test case and later connect from another test case to the same browser instance using 

export const debugTest = test.extend({
  browser: async({browser}, use) => {
    await use(await browser.browserType().connectOverCDP('http://localhost:9222'))
  },
  context: async({browser}, use) => {
    await use(browser.contexts()[0])
  },
  page: async ({context}, use) => {
    await use(context.pages()[0])
  },
})

Of course we can first run test case in existing external browser (for example opened by PowerShell script) but in this way, we're losing everything defined for context as BaseURL, HttpCredentials etc.
We have problem with sending credentials into existing browser context because method 'setHTTPCredentials' is deprecated 
![credentials](https://github.com/microsoft/playwright/assets/84720864/8ea46f1b-0b86-450d-9e55-2d19ee119255)

Generally also method 'connect()' doesn't work (we used debug url from http://localhost:9222/json/list as 'wsEndpoint') so we must use connectOverCDP()

Solution proposals:
- Option in configuration to set as boolean (marked as unsafe).  After hooks fixtures turn on/off
- Add possibility to add use options as BaseURL etc. into exisitng browser context
- More informations in documentation how to override fixtures (we found informations only how to override Before hooks)

### Motivation

We have unstable application (problem with loading), so we're searching for option to execute code in the same browser instance without closing. We can't use storage state, because application logout our user in this way.

**Comment by mxschmitt** [comment]
If you do something like this, you'll loose all the artifact features like tracing on/off/on-first-retry etc. Also connectOverCDP is Chromium only, so this would be also a limitation.

Could you elaborate a bit more on:

> We have unstable application (problem with loading), so we're searching for option to execute code in the same browser instance without closing. We can't use storage state, because application logout our user in this way.

Does it mean the application is slow and you want to re-use the browser because of that? Like e.g. a lot of JavaScript inside the page?

Or do you mean with "unstable" that the application takes more time to boot up, before Playwright can start running the tests?

**Comment by EldoradoEU** [comment]
Yes, a lot of JavaScript inside the page, sometimes it takes a lot of time until page appear. In part of our test cases we have a lot of steps like 2FA, do someting on another pages before expected page appear. We'are searching way to execute some code on page (checking if works as expected) without previous steps, because it takes a lot of time until this page again appear. 

This is the reason, why we want connect to existing instance. For example we have 10 steps, test stopped on 8, so we want continue running from 8 after adding changes in code. Someting like 'Run from step'

**Comment by mxschmitt** [comment]
For re-using authentication, we recommend following [this guide](https://playwright.dev/docs/auth). This should help you if the login is the bottle-neck, if e.g. every test needs a login, you can login once and then re-use the login for all the future tests.

If you want to re-use the page, we recommend following [this guide](https://playwright.dev/docs/test-retries#serial-mode). We usually don't recommend this, since it does prevent you from running them in parallel. If tests fail after test 8/10, it will still fail and not run test 9 + 10, since they are logic-wise depending on each other, which is the contract "serial tests" are making.

**Comment by EldoradoEU** [comment]
We tried storageStaste but our user was logout. Idea with retries is fine, but for executing tests. we're searching way to easier debug. Maybe is possible execute code line by line from console as in Python?

**Comment by EldoradoEU** [comment]
okay, thank you. We're using Trace Viewer and it's really cool. So last question. Is it possible to override after hooks?

**Comment by mxschmitt** [comment]
This is not possible.
