### ISSUE TITLE
[Feature]: connect to preinstalled browser

### ISSUE THREAD

**Issue by leoharrison2001** [microsoft/playwright#30314]
### 🚀 Feature Request

Hey,

I am not sure how feasible it is but can I use playwright to control an a preinstalled browser, say a chrome. I understand that playwright already uses CDP for browser communication. Is there a way to enable CDP on a preinstalled browser and then let playwright take over the control?

-- Leo

### Example

Connect playwright to an instance of some preinstalled browser.

### Motivation

There can be some prerequisites that are available in the preinstalled browser. The browser that comes with playwright normally does not have those.

**Comment by mxschmitt** [comment]
3 resources which might help you:

- You can use an existing browser by using channels, see [here](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge).
- If you want to take Playwright take over control, you can use [connectOverCDP](https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp) in order to connect to a running browser
- If you want to open an existing browser profile, you can use [launchPersistentContext](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context).

If I understand you correctly, you want to run your current browser with `--remote-debugging-port=9222` and then use connectOverCDP in order to connect to it.
