### ISSUE TITLE
[Feature] mouse.getPosition()

### ISSUE THREAD

**Issue by terion-name** [microsoft/playwright#3032]
Mouse instance stores position inside `_x` and `_y` props. Of course it is JS and nobody can stop one of accessing them, but they are not part of interface and it's not good to use them like this. And it is often useful to get current cursor position and don't track it manually.

**Comment by pavelfeldman** [comment]
First of all, thank you for filing this issue. We appreciate your input, in many ways Playwright is based on it. This particular feature request didn't get enough stars for us to prioritize the work on it and hence is being closed. We are a relatively small team and we need to prioritize aggressively to deliver support and new features to you.

**Comment by terion-name** [comment]
@pavelfeldman you already have a PR for this that was closed for no reason

**Comment by Rumatoid** [comment]
> 

How I can get private fields in NodeJS?

**Comment by qnsi** [comment]
Hey guys. I am not the best programmer so perhaps you might not like my hack, but maybe someone doesn't care.
I think private fields `_x` and `_y` were removed from the code, and that's why the PR was closed.

My use case for getting a current mouse position is: I am doing an editor and wanted to click on the right of the bullet. Here is what I did:

Basically, I want my browser to somehow communicate with test runner. To do so, I am adding a `mousemove` event listener that changes one element dataset to current mouse position. 

```
// I think this needs to be at the start of your test
await page.addInitScript(() => {
    document.addEventListener('mousemove', event => {
      var bullet = document.getElementsByClassName("editor-bullet")[0] as HTMLElement
      bullet.dataset.mousePosX = String(event.pageX);
      bullet.dataset.mousePosY = String(event.pageY);
    })
  })
  // ... some actions ommited
 ```

Then, when I need to get last position I use `page.evaluate`
```
  const [mousePosX, mousePosY] = await page.evaluate(() => {
      var bullet = document.getElementsByClassName("editor-bullet")[0] as HTMLElement
      return [Number(bullet.dataset.mousePosX), Number(bullet.dataset.mousePosY)]
  })
 ```

and finally I can use "relative" mouse move.
`  await page.mouse.move(mousePosX + 50, mousePosY)`

Hope it's not too hacky for some of you.
