### ISSUE TITLE
Playwright test runner failed to trigger test run

### ISSUE THREAD

**Issue by acheng1102** [microsoft/playwright#30321]
### Version

1.38.0

### Steps to reproduce

I used the command "npx playwright test --ui" to start Test Runner. All tests have been loaded to the plan but when I click to run tests, no test is triggered successfully
![image](https://github.com/microsoft/playwright/assets/106506389/ddfafa0e-f980-4806-9540-aa0f36d65c44)

### Expected behavior

Test should be triggered to run properly

### Actual behavior

 when I click to run tests, no test is triggered successfully

### Environment

```shell
OS: Window 11 Pro
Node: 16.14.2
Playwright: 1.38.0
```

**Comment by mxschmitt** [comment]
Hello! You are not using the latest Playwright version - could you try version v1.43 which is latest as of today? Also your Node.js version is not supported [anymore](https://playwright.dev/docs/intro#system-requirements). We recommend [version 20](https://nodejs.org/en/download). If it still does not work for you, we need a reproduction which we can run locally, otherwise we unfortunately can't act on it. Thanks for your understanding!

**Comment by mxschmitt** [comment]
Closing as per above. Feel free to re-file with more details.
