### ISSUE TITLE
[Feature]: Re-run the last test when manually reloading browser window

### ISSUE THREAD

**Issue by alectrocute** [microsoft/playwright#30356]
### 🚀 Feature Request

When you have the browser window open alongside a code editor, refreshing the browser window should re-run the last played test.

### Example

Many developers have multiple physical or virtual displays and would find use in not having to go back to VS Code. It would save a lot of time.

### Motivation

My motivation is watching my coworkers use Playwright and instinctively reload the browser window to no avail.

**Comment by yury-s** [comment]
You can already configure a shortcut in VS Code for rerunning last test, search for "Test: Rerun Last Run" in the command palette:

<img width="748" alt="image" src="https://github.com/microsoft/playwright/assets/9798949/ba214516-d09f-4a22-8f92-974e83bb397c">

is that what you are looking for?

**Comment by alectrocute** [comment]
@yury-s, thank you so much for your response. That shortcut would effectively do what I want, but not in the way I want. The friction point I've observed is developers new to Playwright attempting to re-run the last run via `CMD + R` in the actual Playwright browser window.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
