### ISSUE TITLE
[Question] TypeScript compilation must include the browser environment

### ISSUE THREAD

**Issue by mightyiam** [microsoft/playwright#3037]
In order to get a successful TypeScript compilation, the `dom` types must be included (previously mentioned in https://github.com/microsoft/playwright/issues/2659#issuecomment-647108753).

Doing that results in TypeScript allowing access to browser globals such as `window`, `document`, `URL` and many more, which do not really exist in Node.js.

Is this recognized as an issue that would possibly be addressed, please?

**Comment by mxschmitt** [comment]
How do you see there an issue? It's just the types which allow then the usage of the browser types in Node.js. But if you use them incorrectly it would result in an error thrown by Node.js.
Mostly it's useful for page.evaluate() e.g. and used for some internal scenarios.

**Comment by mightyiam** [comment]
I use type checking to prevent runtime errors. Regarding `page.evaluate`, If you ask me, it should accept only a string. So I don't value this convenience. I value type checking much more. Having all the browser globals in the Node.js seems like a down-side.

**Comment by JoelEinbinder** [comment]
We've seen a lot of value from having `page.evaluate` be typed, and doing so requires having the browser globals. Moving evaluation to be string only would be a huge change to the project, so I'm closing this as wontfix.

**Comment by mightyiam** [comment]
@JoelEinbinder I am not for the parameter of `page.evaluate` to be a string only. If anything, I am asking to not have browser globals in my TypeScript Node.js project in order to use Playwright. Please do not close for a misunderstanding.

**Comment by paya-cz** [comment]
I am having the same issue - in order to use DOM types inside of `page.evaluate`, I have to import DOM lib for the entire nodeJs project. The nodeJs project is doing a lot more things than just interface with `playwright` and having the global namespace polluted with DOM types, `window`, `document` and others is really not that great - imagine writing a server-side database client with access to these! This effectively causes TypeScript to ignore a bunch of clear compile-time errors until runtime.

Please resurrect this issue. No idea why the unrelated `page.evaluate should accept string` idea completely shadowed the issue described in the first post.

**Comment by davelosert** [comment]
Yes definitly. We are having the same problem here.

**Comment by davelosert** [comment]
I agree - this issue was closed too early. Playwright is a tool running in NodeJS - so why would I have to add all the browser types to my globals just for the use of some evaluating functions?

Please reconsider finding another solution here...

**Comment by DetachHead** [comment]
i think https://github.com/microsoft/TypeScript/issues/43434 would solve this problem
