### ISSUE TITLE
[Feature]: codegen for hover the same as codegen for assert visibility

### ISSUE THREAD

**Issue by chenshuichao** [microsoft/playwright#30447]
### 🚀 Feature Request

If we add the hover
![hover-click-icon](https://github.com/microsoft/playwright/assets/77186544/d852950e-926e-43c6-b50c-c5ff879f4360)
in the icons in the toolbar ,we can gencode the hover code the same as codegen for assert visibility .
the interaction is click the hover icon in the toolbar, then select the target element of hovering.
the same as assert visibility
<img width="150" alt="Screen Shot 2024-04-20 at 19 53 16" src="https://github.com/microsoft/playwright/assets/77186544/62d0f8da-7069-4e73-9488-f9cb2139b130">

### Motivation

codegen for hover

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
