### ISSUE TITLE
[Feature]: Enhancements for HTML Reporter

### ISSUE THREAD

**Issue by shashwatahalder01** [microsoft/playwright#30456]
### 🚀 Feature Request

- [ ] Indication for skipped test on HTML reporter
- [ ] Option to hide skipped tests altogether from HTML report

[**Previous closed Issue**](https://github.com/microsoft/playwright/issues/14703#event-9690208104)

### Motivation

It would enhance the clarity of the HTML report to provide clear indications of the test status. Tests might be skipped for various reasons, such as being in progress or not currently required. In my scenario, I have tests in the global setup using Project Dependencies, and when running tests with a certain tag, I need to skip some tests from the global setup. I prefer to hide these skipped tests from the reporter in such cases. Therefore, having an option to hide skipped tests would be beneficial.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
