### ISSUE TITLE
[BUG] miss export type BrowserTypeConnectOptions

### ISSUE THREAD

**Issue by bluelovers** [microsoft/playwright#3047]
**Context:**
- Playwright Version: ^1.2.1
- Operating System: [e.g. Windows, Linux or Mac]
- Node version: [e.g. 10.12, 10.14]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

![image](https://user-images.githubusercontent.com/167966/87989321-6acfa900-cb14-11ea-9fb8-c8ee0e0f2937.png)

**Describe the bug**

miss export type BrowserTypeConnectOptions

**Comment by JoelEinbinder** [comment]
We don't export most options in order to avoid breaking changes to the typescript api. Things get tricky if we ever wanted to add a connect option for one but not all browsers.

It is a little hacky, but you can pull the type into your project today like so:
```ts
type BrowserContextOptions = Parameters<BrowserType<Browser>['connect']>[0];
```

I think connect options is stable enough that we can export. I sent a PR to export it as `ConnectOptions`. So in the future, you will be able to use `import {ConnectOptions} from 'playwright'`.

**Comment by arjun27** [comment]
Hey @bluelovers, out of curiosity, how would the exported type help? I'm assuming the built-in TS support in the editor would give you autocompletion for connect options without explicitly imported the types. Did I get this wrong?

**Comment by bluelovers** [comment]
this is why need import it

```ts
async connect(connectOptions?: Parameters<BrowserType<any>["connect"]>[0], contextOptions?: BrowserContextOptions)
	{
		if (!this.#_launched || !this.browser)
		{
			await this.browser?.close?.();

			this.browser = await this._class()
				.connect(connectOptions)
			;

			await this._launch(contextOptions);
		}

		return this
	}
```
