### ISSUE TITLE
[Bug]: Disabling the "Block insecure private network requests" experiment in Google Chrome is not effective.

### ISSUE THREAD

**Issue by 406722575** [microsoft/playwright#30536]
### Version

1.43.0

### Steps to reproduce

。

### Expected behavior

After setting the experimental items to "disabled" in chrome://flags/, they will take effect when using Playwright Codegen.

### Actual behavior

In Google Chrome, I tried to disable the "Block insecure private network requests" experimental feature. By disabling this, a pop-up should appear when my project submits a form, but I have not seen the pop-up after trying several methods.

1、I set up Playwright's built-in Chromium browser by following these steps:

1）Open Google Chrome, enter and visit the URL address chrome://flags/#block-insecure-private-network-requests.
2）Type "Block insecure private network requests" in the search box to quickly find this experiment item.
3）Change the setting of this experiment item to "Disabled".
4）lose Google Chrome and then reopen it to make the changes effective. 
After setting up, I started the project with playwright codegen xxx, submitted the form without seeing a pop-up, and checked that the state of block-insecure-private-network-requests in the browser was still default.
![PixPin_2024-04-25_14-25-53](https://github.com/microsoft/playwright/assets/39303693/e97f98be-bf8a-44c2-a7d6-0fa41d274ade)

2、In the project root directory, I created a conftest.py file and overrode the browser_type_launch_args method, but still, there was no effect. Perhaps there is an issue with my settings.
![PixPin_2024-04-25_15-06-37](https://github.com/microsoft/playwright/assets/39303693/4aef05a7-27cd-42e1-8788-184836098fe3)

### Environment

```shell
System:
    OS: Windows 10
```

**Comment by pavelfeldman** [comment]
chrome://flags are not experiments, they implement the process features are being deployed in Chrome. It starts with feature disabled by default so that users could give it a try and then it becomes enabled by default with a way to opt out. When it has been there for a long time, it might be that the flag gets removed (or it might stay there for a long time).

Playwright uses default set of enabled features with minimal modifications to allow for automation. That way what you test matches the user experience.

Adjusting disable features argument is the move in the right direction if you must disable this feature, but a) it uses wrong notation for feature naming and b) it will be overridden or will override the value that Playwright already passes: https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/chromium/chromiumSwitches.ts#L39. In either case, running browsers with non-default arguments are at your own risk, so we won't be able to help or provide support.

**Comment by Rafaelpanin666** [comment]
Bien bloquear todos malware espías y que intervienen con el trabajo de uno bloquear Windows pc block.

**Comment by joseguadalupecervantes2008-wq** [comment]
chrome://flags/#block-insecure-private-network-

**Comment by joseguadalupecervantes2008-wq** [comment]
chrome://flags/#block-insecure-private-network-

**Comment by joseguadalupecervantes2008-wq** [comment]
about://flags/#block-insecure-private-network-requests
