### ISSUE TITLE
[Feature]: Generate trace even for codegen use

### ISSUE THREAD

**Issue by esther-86** [microsoft/playwright#30548]
### 🚀 Feature Request

A trace is available when tests run but not when doing the code generation/manual testing. It would be great to generate the trace at code generation time so that the correlation between generated code and the UI can be easily seen without having to separately record the video during the code generation time.

### Motivation

Playwright's code generation is the product that will enable manual testers to utilize their domain knowledge and help with the automation effort. We have manual testers record the script and devs/automation engineer transform the script into automated and reusable tests. If a trace is available, the process will be even more streamlined without the need for video recordings

**Comment by pavelfeldman** [comment]
>  If a trace is available, the process will be even more streamlined without the need for video recordings

Could you explain how trace is helpful here?

**Comment by esther-86** [comment]
Yes, so, I ask manual testers to record the flow and send me the script to convert to be reusable. If there is a trace, I can see the UI at each interaction instead of having to rely on the video recording of the recording or go through the flow myself

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by RogerW-STR** [comment]
Care to explain how this issue got closed 10 days BEFORE it was raised?
