### ISSUE TITLE
Logout verification for parallel tests with login thru global setup with single user

### ISSUE THREAD

**Issue by AM1988** [microsoft/playwright#30566]
Hi there.

I want to get a recommendation from the community on the best practices for handling the next use case.

I have a lot of tests that run in parallel mode. To simplify the explanation - A, B, C, D, E tests and 2 workers.
In the global setup, we do login and share it across all the tests.

One of the test check the logout process, let's say it is test B.
Test are executed in the next order:

Worker 1 - A, B, C
Worker 2 - D, E

All tests in worker 2 are passing successfully, but for tests from worker 1: A- pass, B - pass (logout happened), C - fails because of not logged-in user.

**Comment by TomasHubelbauer** [comment]
I understand that the Playwright repository issues are not a place for questions (which I assume is why this was closed with no response), but this issue is the top Google hit for the situation described and the https://playwright.dev/docs/auth documentation does not cover this scenario at all. Given this, I will link this article I found that describes the only somewhat clean way I found to do this, which is to create a temporary storage state different from the reused one so the shared one doesn't get invalidated by the logout: https://playwrightsolutions.com/handling-multiple-login-states-between-different-tests-in-playwright/
