### ISSUE TITLE
[Feature]: press enter in contenteditable doesn't make keypress code in codegen

### ISSUE THREAD

**Issue by ed-jinyoung-park** [microsoft/playwright#30590]
### Version

1.43.1

### Steps to reproduce

1. run ``playwright codegen``
2. go to contenteditable demo site (https://d-toybox.com/studio/lib/input_event_viewer.html)
3. write any word in contenteditable element
4. press enter

![playwright test](https://github.com/microsoft/playwright/assets/26531678/599ee41c-7a78-4c6f-a3a5-d73c70f763e5)

### Expected behavior

i expect codegen generated code to make like this
```ts
...
await page.keyboard.press('enter')
... 
```

### Actual behavior

enter event just append '\n\n' word at last of fill method value
```ts
...
await page.locator('#editor').fill('aaaaa\n\n\n\n\n\n');
...
```

### Environment

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 401.03 MB / 32.00 GB
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    pnpm: 8.15.3 - ~/.nvm/versions/node/v18.16.1/bin/pnpm
  IDEs:
    VSCode: 1.88.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1 
    playwright: ^1.43.1 => 1.43.1
```

```[tasklist]
### Tasks
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
