### ISSUE TITLE
[Bug]: trace stop_chunk. the network in chunk includes the network data from the previous chunk

### ISSUE THREAD

**Issue by bingosam** [microsoft/playwright#30591]
### Version

1.43.0

### Steps to reproduce
```python
with sync_playwright() as playwright:
    browser = playwright.chromium.launch(channel="chrome")
    context = browser.new_context()
    context.tracing.start(name='trace')

    context.tracing.start_chunk(name='trace', title='case1')
    page = context.new_page()
    page.goto('url of case 1')
    context.tracing.stop_chunk(path='case1.zip')

    context.tracing.start_chunk(name='trace', title='case2')
    page = context.new_page()
    page.goto('url of case 2')
    context.tracing.stop_chunk(path='case2.zip')
```

### Expected behavior

The network data in case2.zip should not include the network data from case1.zip

### Actual behavior

The network data in case2.zip include the network data from case1.zip.

### Environment

```Text
- Operating System: [Windows 11]
- Browser: [Chrome]
- Python Version: [3.9.16]
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
