### ISSUE TITLE
[Feature]: Ability to extend the trace information

### ISSUE THREAD

**Issue by taras** [microsoft/playwright#30610]
### 🚀 Feature Request

If we don't use locators, we'll lose trace information about the elements we're interacting with in the test. Is there a way for us to write to the trace without using locators?

### Example

We want to be able to call trace API from the browser or node to add information that locators would otherwise provide. 

### Motivation

![image](https://github.com/microsoft/playwright/assets/74687/f9249cdd-ccf9-4795-96e8-5b0978a17a22)

https://frontside.com/interactors 

I'm part of the team that maintains Frontside Interactors. We're considering creating an integration with Playwright. We tried using async locators, but Interactors's API design doesn't align well with Locators.

**Comment by dgozman** [comment]
@taras You can use `test.step()` to add steps that would be visible in the trace viewer. However, most of Playwright APIs show in the trace. What do you use under the hood that's missing in the trace viewer?

**Comment by uchagani** [comment]
It would be nice to be able to write arbitrary logs to the trace.

**Comment by taras** [comment]
![Locators in Trace](https://github.com/microsoft/playwright/assets/74687/29073e74-f007-4112-bbb2-17479d715e90)

@dgozman Since we're not using locators, I assume we won't get the traces I highlighted in the image. We want to add these from the node or the browser for interactor interactions.

**Comment by dgozman** [comment]
@taras Most of Playwright APIs show in the trace, not only locators. What APIs do you use that's missing in the trace viewer?

**Comment by taras** [comment]
We're building a custom testing harness that uses the Playwright library to start up the browser. We have a custom test runner. So, our traces would only show HTTP requests because we don't currently use the `test` function or locators. We would essentially like to be able to use the trace functionality without relying on Playwright's test runner.

**Comment by dgozman** [comment]
@taras I see, so you basically use Playwright to launch the browser. In this case, there is indeed not much to see in the trace. I will keep this issue open, but the usecase seems to be low priority for Playwright. It looks like it would be easier for you to record your own trace and show it in whatever UI you would like, because there is pretty much nothing from Playwright that could show up in the trace.

**Comment by taras** [comment]
Thank you for considering my request. It might be helpful to clarify that I we have 2 separate use cases.

The primary use case that prompted this request is to add support for Playwright to Interactors. This would make it possible for users of Interactors to use the Playwright runner with interactors for their component library. In this case, they'd be using everything except locators.

The second use cases is for BigTest where we're considering to replace WebDriver with Playwright. In the case of BigTest, we have our own declarative [test syntax](https://github.com/thefrontside/bigtest/blob/v0/sample/app/src/test/bigtest.test.js) and it's own test runner.

The Interactors use case is a much higher priority for us. Would you be able to give some pointers on how we can send trace information to Playwright even via some unofficial APIs would be ok for now.

**Comment by dgozman** [comment]
> In this case, they'd be using everything except locators.

I think the usual Playwright trace would be almost there. I guess you are using something else instead of locators, probably some kind of `page.evaluate()` or similar? That should show up in the trace anyway, albeit under the actual API name, not under your wrapper name. I didn't understand whether you use Playwright's test runner in this case, but if you do you can wrap it all with `test.step()`.

> Can you give some pointers on how we can send trace information to Playwright, even via some unofficial APIs? I would appreciate it.

Unfortunately, there is no way to achieve this today.

**Comment by taras** [comment]
> I guess you are using something else instead of locators, probably some kind of page.evaluate() or similar?

The design of Intractors is very similar to Playwright locators. They're both convergent and perform chained DOM look-up in one tick of the event loop. You might find this blog post interesting https://frontside.com/blog/2020-07-16-the-lesson-of-bigtest-interactors/

We only use `page.evaluate` to send the agent what Interactor to call and arguments to that interactor. Actual lookup and interaction happen in the browser context. So it sounds like we should expect to see `page.evaluate` and arguments in the trace?

> I didn't understand whether you use Playwright's test runner in this case, but if you do you can wrap it all with test.step().

In this case, the users would be using Playwright test runner.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
