### ISSUE TITLE
[Feature]: First-class support for scrolling within an element

### ISSUE THREAD

**Issue by RenderMichael** [microsoft/playwright#30654]
### 🚀 Feature Request

The ability to scroll within an element's scroll box.

### Example

``` csharp
ILocator element = ...;

element.Scroll(deltaX: 0, deltaY: 10);
```

### Motivation

There is access to the raw mouse wheel, but scrolling within an element requires ceremony and may be finnicky. My current solution is something like:

``` csharp
public static async Task ScrollAsync(IPage page, ILocator locate, int steps)
{
    await locate.FocusAsync().ConfigureAwait(false);
    await locate.HoverAsync().ConfigureAwait(false);
    await page.Mouse.WheelAsync(0, steps).ConfigureAwait(false);
}
```

First-class support for this would be very helpful.

**Comment by mxschmitt** [comment]
Scrolling inside an element is not a common scenario testing/Playwright wise (since we automatically scroll for actions). We recommend the user to do it manually, rather than adding a Playwright method for it.

Some customers want to scroll based on percentage, some based on pixel, so we would let the user decide.

**Comment by gund** [comment]
When there is a virtual scroll used for some lists - it is important to be able to scroll that element manually so that the elements would be rendered in the DOM before they are actionable.
So this feature would be really helpful for such scenarios.
