### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Tyler86** [microsoft/playwright#30650]
### Version

1.43.1

### Steps to reproduce

1 download latest version of selenium grid being 4.20.0
2. open terminal and navigate to where you downloaded selenium grid. 
3. in terminal type in java -jar selenium-server-4.20.0.jar hub and press enter 
4. open a another terminal go to the same folder where you downloaded selenium grid
5. type in terminal  java -jar selenium-server-4.20.0.jar node --max-sessions 2 --port 5555
6. open a third terminal create a react a new playwright project using npm init playwright@latest
7. in the terminal navigate into your new playwright folder 
8. using your favorite code editor comment out the browser options in playwright config except chrome
9. add the code to turn headless off 
10. save all changes 
11 on the terminal execute your playwright scripts on your new grid  SELENIUM_REMOTE_URL=http://<replace with grid ip>:4444 npx playwright test
12. notice when the test are complete you have a chrome window left open (may not happen the first time run you script a few times if it doesnt)
13. 

### Expected behavior

chrome browser should close on test completion 

### Actual behavior

either chrome browser doesn't close on completion or grid node is stuck with super high cpu utilization or both 

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 16.56 GB / 31.68 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.88.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.15 - C:\Users\twheelwright\AppData\Local\Programs\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
