### ISSUE TITLE
[Feature]: replay in trace viewer

### ISSUE THREAD

**Issue by chensce** [microsoft/playwright#30702]
### 🚀 Feature Request

When the test run is end,I want to replay the running to debug the test script. 
1)move the filmstrip panel from the top to the bottom;
2)add the play/pause control button
3)the same as the movie editor in mac os `x.```

### Example
it is open moment:
<img width="2048" alt="playFilmstrip" src="https://github.com/microsoft/playwright/assets/93559562/2e13dc36-64d4-4ef3-aa33-bd5651b3ef73">

it is pause moment:
<img width="2048" alt="pauseFilmstrip" src="https://github.com/microsoft/playwright/assets/93559562/dc002957-9b3d-4167-8a36-a5ca18437908">

the movie is :

https://github.com/microsoft/playwright/assets/93559562/348ad477-4423-4974-98f6-c41a7cb3ac27

### Motivation

When the test run is end,I want to replay the running to debug the test script.

**Comment by chensce** [comment]
yes,now it is awesome!thank you for your great work.
if we could replay ,it is more awesome!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
