### ISSUE TITLE
[Feature]: A option for `colorScheme` to follow the OS preference

### ISSUE THREAD

**Issue by silverwind** [microsoft/playwright#30704]
### 🚀 Feature Request

The [colorScheme](https://playwright.dev/docs/api/class-testoptions#test-options-color-scheme) setting should provide a option to have it follow the current OS setting, e.g. emulate dark when OS prefers dark, and light when OS prefers light.

### Example

Add a new `colorScheme: "auto"` option which when set, emulates the current OS color scheme preference.

### Motivation

This is how it works in regular browsers, so playwright should offer it optionally. The default should stay at `light` to retain stable tests.

In my testing with OS set to dark, neither `'no-preference'` nor `null` have any effect and it stays in light. Maybe `null` is meant to provide the OS behaviour, not sure.

**Comment by silverwind** [comment]
> Playwright is about having reproducible tests 

Yes I agree and that's why I suggest leaving the default at light mode, but a option should be provided imho because other aspects of the browser like `viewport` can also be changed and would lead to unstable tests.

Why single out `prefers-color-scheme`?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by silverwind** [comment]
It seems this got implemented in https://github.com/microsoft/playwright/pull/38264. Edit: actually not, this only affects the https://trace.playwright.dev/ UI.
