### ISSUE TITLE
[Feature]: 'retain-on-first-failure' option for screenshots

### ISSUE THREAD

**Issue by bmendoza0123** [microsoft/playwright#30701]
### 🚀 Feature Request

Since I'm using the option `trace: 'retain-on-first-failure'` with `retries: 3` and `screenshot: 'only-on-failure'`, I am oftentimes left with artifacts for tests that have retried and only contain screenshots without traces. This isn't a problem but more so, I'd prefer to omit those screenshots that don't have corresponding traces, as they don't really give me much to debug a test failure on, as opposed to the combination of a screenshot and a trace. I'd be awesome to have the option of `screenshot: 'retain-on-first-failure'` so that all artifacts retained contain both screenshots and traces.

### Example

```
projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        trace: 'retain-on-first-failure',
        screenshot: 'retain-on-first-failure',
      },
    }
]
```

### Motivation

I believe this will make Playwright better by providing a larger set of options that allows it's consumers to configure exactly how they'd like to digest artifacts. For example, I'm highly motivated to reduce the size of artifacts created by Playwright tests without sacrificing the tooling provided by Playwright to debug, therefore, having just artifacts with screenshots isn't super helpful and just increases artifacts size. A win win situation would be having the option `screenshot: 'retain-on-first-failure'` to go along with `trace: 'retain-on-first-failure'` 😃.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
