### ISSUE TITLE
[Feature]: Ability to consume matching entries using routeFromHAR

### ISSUE THREAD

**Issue by SimonSikstrom** [microsoft/playwright#30754]
### 🚀 Feature Request

Add ability to consume each matching entry using `routeFromHAR`, then it would be possible to have a recorded `.har` with multiple matching entries without needing to switch .har in the middle of the tests.
Possible solution to #18288

### Example

Have a recorded `.har` with a new server state after reload.

Replay `.har` using a `consume` (or similar) flag for `routeFromHAR`.

```
await context.routeFromHAR(path, {
    consume: true
  });
```

Implementation POC https://github.com/microsoft/playwright/compare/main...SimonSikstrom:playwright:consume-har-entry-18288

### Motivation

Its not possible to handle subsequent requests using har replay, see #18288 .

My proposal is to add ability to consume each matching entry with `routeFromHAR`, then it would be possible to have a recorded `.har` with many matching entries that could return different results for subsequent calls.

**Comment by yury-s** [comment]
The reason we haven't taken any action on this is that we didn't want a sub par solution. If we improve the replay from har logic we'd like its functionality to y comparable to Web Page Replay. If your proposed change aligns with this standard, we would be open to reviewing and accepting PRs.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
