### ISSUE TITLE
[Docs]: test-configuration For .Net

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [microsoft/playwright#30890]
### Page(s)

https://playwright.dev/docs/test-configuration exists but 
https://playwright.dev/dotnet/docs/test-configuration doesn’t exist

### Description

The page “ Test configuration” https://playwright.dev/docs/test-configuration  shows Node.js instructions.
However when I tried to switch to .Net, it returned “ This page is not available for .NET.”
It will be good to document how to do Test configuration in .Net

**Comment by michael-freidgeim-webjet** [comment]
I am not alone, who miss Playwright settings for .NET documentation https://medium.com/@dneprokos/playwright-with-net-what-is-it-useful-bafc85898b5

> To be honest, I have not found a complete description of the supported Playwright settings for .NET. And this is something that really bothers me. Maybe there is a luck of documentation or maybe the .NET version of Playwright has limited support of config (compare to Node.js)

.

**Comment by mxschmitt** [comment]
Switching from the Node.js documentation to the .NET documentation is not always supported, since the doc structure is different. We recommend switching once and then following the guides on the left side along.

Playwright for Node.js is significant different, since it provides a test-runner while in .NET, we mostly provide a library with NUnit and MSTest integrations. So there is a dedicated chunk of documentation in Node.js, like in your case the test-configuration page, which is not needed in .NET.

We just released an update to the .NET docs which should make it more clear, does this help you?

- [Recording a trace](https://playwright.dev/dotnet/docs/trace-viewer#recording-a-trace)
- [Recording it on failure](https://playwright.dev/dotnet/docs/trace-viewer#run-trace-only-on-failure)
- [Customising context options](https://playwright.dev/dotnet/docs/test-runners#customizing-browsercontext-options) (for MSTest see below)
- [Customising launch options](https://playwright.dev/dotnet/docs/test-runners#customizing-browserlaunch-options) (for MSTest see below)

**Comment by michael-freidgeim-webjet** [comment]
@mxschmitt Thanks for the links to. .Net documentation.
 I’ve posted  a question on stackoverflow [How to set values in Playwright BrowserContext options from config file?](https://stackoverflow.com/questions/78544898/how-to-set-values-in-playwright-browsercontext-options-from-config-file)
Please consider it as a feedback.

**Comment by mxschmitt** [comment]
ContextOptions can only be set via the runtime, see here: https://github.com/microsoft/playwright-dotnet/issues/2555
