### ISSUE TITLE
Hello Folks, Is their any way to provide the UI element in headless mode and return a locator for the same.

### ISSUE THREAD

**Issue by Zubair2019** [microsoft/playwright#31123]
### Please do not submit this issue.

- [X] I understand

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)
