### ISSUE TITLE
[Bug]: Console error not reported

### ISSUE THREAD

**Issue by kaihendry** [microsoft/playwright#31142]
### Version

1.44.1

### Steps to reproduce

https://github.com/kaihendry/playwright-console-error

### Expected behavior

Expected to see the error `Failed to load resource: the server responded with a status of 400 ()`

### Actual behavior

No console error messages

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 14.52 GB / 15.61 GB
    Container: Yes
  Binaries:
    Node: 20.13.1 - /opt/hostedtoolcache/node/20.13.1/x64/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.5.2 - /opt/hostedtoolcache/node/20.13.1/x64/bin/npm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
```

**Comment by mxschmitt** [comment]
This is actually a race condition, since your site does issue the request to your API after the page has loaded. If you add an artificial delay after the navigation, it works.

We recommend using e.g. polling for it instead of waiting for a random time: `await expect.poll(() => messages).not.toEqual([])`
