### ISSUE TITLE
Is there a way to test my application with 2 login accounts? Right now my setup looks like, I have a global file where I login once for all the entire tests.

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#31153]
### Please do not submit this issue.

- [ ] I understand

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)
