### ISSUE TITLE
[Feature]: DOM load event listener for page

### ISSUE THREAD

**Issue by darshandp007** [microsoft/playwright#31164]
### 🚀 Feature Request

Is there an event listener that constantly listens for page (DOM) load events? 

**Expectation:** I want to attach a page (DOM) load listener at a global level to avoid adding auto-wait code for every step.

### Example

Assume I have 5 steps as attach below. 

**Steps:**
1. Go to x URL.
2. enter username and password.
3. click on login
4. click on profile icon (From Dashboard page)
5. click on save button (From Profile Page)

After the 3rd step, the UI will call the login API. Upon successful authentication, the UI will redirect to the dashboard page. Therefore, I need to add wait code before the fourth step to load the dashboard page, and similarly, before the fifth step. My goal is to avoid duplicating code and to manage this efficiently in one place with a page(DOM) load listener.

### Motivation

Everyday i'm working with playwright and it's help me to achieve my goal in testing automation industry.

**Comment by mxschmitt** [comment]
DOM load event listeners have proven to be unreliable over the last years, so end-to-end testing frameworks tend to do polling instead. In your scenario, it should work without any explicit waits at all, since Playwright will automatically wait until the element is on the page, clickable etc. see [here](https://playwright.dev/docs/actionability). 

Looking e.g. at this code:

```ts
await page.goto();
await page.getByRole('textbox', ...).fill()
await page.getByRole('textbox', ...).fill()
await page.getByRole('button', { name: 'Profile' }).click()
await page.getByRole('button', { name: 'Save' }).click()
```

So this would always wait for a navigation to complete, element to appear, etc.

In your 3rd step, if you would immediately click, Playwright would wait for the click element to be appear on the page etc. like a real user and then click it once its there not moving anymore etc.

If you have concrete examples which don't work, let us know!

**Comment by ChintanVasoya** [comment]
I have the same query is there any event listener which can constantly listens for page load events.
For example :: 

1.  Go to x URL.
2. enter username and password.
3. click on login
4. click on profile icon (From Dashboard page)
5. click on save button (From Profile Page)

**Comment by mxschmitt** [comment]
Image being a user - does the user every time wait for 2 seconds before clicking somewhere? Some users are very fast and click immediately somewhere on the page. So it looks like a bug in the application rather than something Playwright should fix by waiting for 2 seconds.

**Comment by Exoow** [comment]
@ChintanVasoya if you really need this, why not write a wrapper method that first navigates and then `await page.waitForTimeout(2000)` so you can have this behavior everywhere you navigate.

**Comment by yury-s** [comment]
As Max mentioned above, Playwright's recommended approach is to test the user visible behavior, i.e. wait for a UI change that would be observable by a human, rather than waiting for a timeout after some internal load event. 

> The issue arises when a user clicks on a button that redirects to a new page. At such moments, I encounter difficulties.

Why can't you wait for an expected state of the page's UI by using one of the web assertions or Playwright actions that [auto-wait](https://playwright.dev/docs/actionability) internally?

**Comment by yury-s** [comment]
Closing per the responses above, feel free to open a new issue if it doesn't work.
