### ISSUE TITLE
How to integrate Rally in playwright cucumber BDD typescript 

### ISSUE THREAD

**Issue by prasathmscss** [microsoft/playwright#31174]
### Please do not submit this issue.

- [X] I understand

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)


--- 

Folding into https://github.com/microsoft/playwright/issues/11975
