### ISSUE TITLE
Is there a way that playwright with run the teardown of a playwright project even if test gets interrupted by using cmd + c

### ISSUE THREAD

**Issue by kdaHMCTS** [microsoft/playwright#31184]
### Please do not submit this issue.

- [X] I understand

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)
