### ISSUE TITLE
[Bug]: Multiple videos are created while working with windows/popups. Single video should be created for the entire test which will help  to understand the flow of the test case.

### ISSUE THREAD

**Issue by akila0791** [microsoft/playwright#31241]
### Version

1.44.0

### Steps to reproduce

1. Enable video recording in playwright.
2. Execute test case which includes handling popups and new pages.

### Expected behavior

1. Single video should be created for the entire test.

### Actual behavior

1. Separate video is created for each of the pages which makes it difficult to understand the flow.

### Environment

```shell
TESTNG, playwright, java
```

**Comment by yury-s** [comment]
Consider using tools like [tracing](https://playwright.dev/docs/trace-viewer-intro) for a more comprehensive view of the app. Videos is a low level API and its one per page by design, there are no plans to change that.

**Comment by acecilia** [comment]
Hi 👋 I have the same expectation on behaviour as the author of this ticket: obtain a single video for the execution of a test.

I appreciate the alternative of using tracing for more comprehensive debugging instead of using video, but I believe the proposal is unrelated: in my case the video is not needed for debugging - is needed to be able to show how the website behaves to non-technical stakeholders.

@yury-s if you were in need for obtaining a single video from a test execution (this is: what a user would observe when performing the same actions as the test) - how would you do it, is there currently a way?

Example: 
* At the moment when presenting a popup in the same window, the main video does not show the popup, and instead it is recorded as a separate video
* My goal would be to obtain a single video of the test execution that shows what a user would see when performing the same steps as the test: a popup appearing
