### ISSUE TITLE
[Bug]: Visibility check succeeds for "invisible" element

### ISSUE THREAD

**Issue by Germandrummer92** [microsoft/playwright#31398]
### Version

1.43.1

### Steps to reproduce

Run the following playwright test case:

```
import { setTimeout } from "node:timers/promises";

import { expect, test } from "@playwright/test";

test.describe(() => {
  test.only("should be able to enter email", async ({ page }) => {
    await page.goto("https://app.staging.shiftcontrol.io/");

    const emailField = page.getByRole("textbox", { name: "Email" });
    // this should not be visible
    await expect(emailField).toBeVisible();

    await emailField.fill("hello");

    await setTimeout(20_000);

    await expect(emailField).toHaveValue("hello");
  });
});
```

### Expected behavior

Test expected to pass, since the expect.toBeVisible at the start should wait until the element is actually visible.

### Actual behavior

Test fails since the element is filled while it's still invisible (and then hydration overrides it).

### Additional context

[trace.zip](https://github.com/user-attachments/files/15915585/trace.zip)

https://trace.playwright.dev/?trace=https://github.com/user-attachments/files/15915585/trace.zip

screenshot of the snapshot when the assertion returns "visible": 
![image](https://github.com/microsoft/playwright/assets/6311872/278fdde2-3acf-4f7b-82a8-99ae568251c5)

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 815.77 MB / 32.00 GB
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.12.1/bin/npm
    pnpm: 9.3.0 - ~/Library/pnpm/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.43.1 => 1.43.1 
    playwright-core: 1.43.1 => 1.43.1
```

**Comment by dgozman** [comment]
@Germandrummer92 That email field is "invisible" because `div.mantine-Stack-root mantine-tzdwu8` has `opacity:0`. However, [Playwright's definition of visible](https://playwright.dev/docs/actionability#visible) does not consider `opacity` on purpose.

Users can still interact with the email field by tabbing into it and typing some text before the page is hydrated, as explained in [this section of the docs](https://playwright.dev/docs/navigations#hydration). In addition, this email field is perfectly visible to accessibility tools like a screen reader, and will be interacted with.

The proper way to hydrate is to disable user interaction on the page before it is actually hydrated and presented to the user, instead of hiding the visuals. Perhaps, if you do not want the user to see the page before it is hydrated, you can just disable hydration altogether - there is no need to send initial markup if it's not helping the user at all.

Let me know whether this helps, or if you have any questions.

**Comment by Germandrummer92** [comment]
Hey @dgozman, thanks for the explanation. I absolutely agree with you on the server-rendered html being completely useless here. 

Unfortunately we do not control the page in question, our use case is a little different trying to auto-generate (playwright) e2e tests automatically with AI at [octomind](https://octomind.dev).

But I suppose the correct thing here is to go back to our user and let him know his page is, if not broken for, at least very annoying for accessible technologies.

**Comment by dgozman** [comment]
@Germandrummer92 Thank you for explaining your usecase. It seems like there is no action item for Playwright here, so I'll close the issue now.
