### ISSUE TITLE
[Feature]: Extract pdf data to text and read the data in playwright 

### ISSUE THREAD

**Issue by prasathmscss** [microsoft/playwright#31594]
### 🚀 Feature Request

1) How to Verify text inside pdf file in playwright typescript.
2) Is there any way we can compare two pdf files in playwright.

### Motivation

= Extract pdf data to text and read the data in playwright

**Comment by marcusNumminen** [comment]
I had the same problem that I wanted to compare two PDF files. What I did was that I used 'pdfToPng' lib to convert all the PDF pages to PNG files and then I used Pixelmatch to compare them then I did an expect that the pixelDiff was 0.

What I think would be great if playwright had expects for comparing PDF using the approach I did above (or at least for PNGs) that would in the report generates the same as expect(page).toHaveScreenshot(myScreenshot.png)

**Comment by mxschmitt** [comment]
Comparing PDFs is outside of the scope for Playwright. We recommend using [Network Events](https://playwright.dev/docs/network#network-events) to listen for your PDF file, getting the content via [response.body()](https://playwright.dev/docs/api/class-response#response-body) and then using a third-party library to convert it to text in order to make the assertion.

**Comment by prasathmscss** [comment]
Thanks @marcusNumminen  & @mxschmitt

**Comment by Dhana958** [comment]
This is one the great feature that our team is also looking forward to. It would be really awesome if playwright implements this feature maybe in future!
