### ISSUE TITLE
[Docs]: techniques to reliably detect browser crashes?

### ISSUE THREAD

**Issue by DavidSouther** [microsoft/playwright#31630]
### Page(s)

https://playwright.dev/docs/best-practices#productivity-tips maybe? Or a new page? Or section?

### Description

#6674 and #31320 both ask for features around detecting when a browser has crashed. In my project, I have a [bug report](https://github.com/nand2tetris/web-ide/issues/391) from users that the page becomes unresponsive "After several hours of use". While we have a hunch on what the underlying issue might be, isolating it has been a bear. We're hoping to use e2e testing to, basically, fuzz it for a couple hours. I have `test.setTimeout(/* 1 hour*/)` and a loop that goes `while (true) { /* do page stuff */ }`. I'm hoping this triggers it? But I don't actually know that it will. I'm also hoping if it does trigger it, I'll see the "page unresponsive" browser.

Are there techniques or APIs to better catch this specifically?

From @mxschmitt "It's usually not common that such errors appear," which, yes, that's why I'd like specific features to test this! And, yes, I recognize that page unresponsive is much easier to conceptualize an API to detect than "out of memory". (Firefox and Chromium have some forum posts about adding a max memory flag, though I don't see any progress in issue trackers.)

The value I see in this is that, yes, I know these issues are bugs in my program - we're unresponsive, or out of memory, because my app code is wrong, but I need tools to a) help track these down and b) assert that they don't regress.

So I opened this under "Documentation" but really I'm hoping more for discussion :)

**Comment by yury-s** [comment]
> I'm hoping this triggers it? But I don't actually know that it will. I'm also hoping if it does trigger it, I'll see the "page unresponsive" browser.
> 
> Are there techniques or APIs to better catch this specifically?

If the browser is unresponsive, the regular actions you perform should start failing (e.g. timing out) too. So you can keep execution playwright actions to simulate human user and if they fail that would be a good indicator of the page misbehaving.


> we're unresponsive, or out of memory, because my app code is wrong, but I need tools to a) help track these down and b) assert that they don't regress.

Our recommendation is to write regression tests based on observed user behavior of the page. If the page crashes due to OOM or some bug in the browsers the playwright actions will start failing. There is also a ['crash'](https://playwright.dev/docs/api/class-page#page-event-crash) event which you can listen to.

You can also try looking at the memory usage using [performance](https://developer.mozilla.org/en-US/docs/Web/API/Performance/memory) API but that may be misleading in many cases as the memory mat not be freed up immediately by the browser. For more sophisticated analysis you can take and analyze heap snapshots of the page using CDP protocol.

**Comment by DavidSouther** [comment]
TIL on('crash'), tyvm
