### ISSUE TITLE
How not to close the browser using playwright?

### ISSUE THREAD

**Issue by mayorov30099** [microsoft/playwright#31692]
### Please do not submit this issue.

- [X] I understand

**Comment by mayorov30099** [comment]
I use playwrite to automatically take tasks in messenger. I need to take the latest new message in the messenger, for this I need to keep playwrite in the background mode always and not close the browser. How can I do it?

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)

---

If you are using [the library](https://playwright.dev/docs/library), then you can just keep the context open and the browser stays there.I recommend to reach out to the Discord community, which is a good place for open ended discussions.
