### ISSUE TITLE
[Bug]: Some of your media failed to load 【Twitter Issue】

### ISSUE THREAD

**Issue by Louis24** [microsoft/playwright#31735]
### Version

1.43

### Steps to reproduce

      file_input = page.query_selector('input[type="file"]')
                file_input.set_input_files(file_name)
                
                

### Expected behavior

upload

### Actual behavior

can not upload videos (imgs is ok)

### Environment

```shell
System:
os: win11
@playwright/test: Version: 1.43.0
```

**Comment by nico-olivares** [comment]
@Louis24 Please add more details to the description. I don't really understand it as is. I'm interested because I myself am seeing a bug that I think may be related to this one, but I'm not sure. I'll try to explain as well as I can. I'll try to create a mini repo with an example as well, but I see the issue happening sometimes, not always.

I have several tests that check for the loading of videos. Some of them are working, but some are only working on headed execution, not on headless. 
I am seeing the same issue with some tests that check for downloaded files as well.

I am attaching a screenshot of the relevant video page when running headed. The video does load and the test passes (even though there's a message about the player). 
![Screenshot 2024-07-18 at 11 26 17](https://github.com/user-attachments/assets/583f18c6-a8f1-44f4-9af3-2be385bfbaff)


When the same test is run headless the video doesn't load at all. I am attaching a screenshot of the trace.
![Screenshot 2024-07-18 at 11 20 56](https://github.com/user-attachments/assets/18efc42d-e235-48db-9204-ca438d9f9fc0)


Here's the relevant section of the test (the bug is not on the code, but on the browsers I think):
```
    let responsePromise = page.waitForResponse(
      'https://player.vimeo.com/video/**',
    )
    await l.global[modifiedRoot][path].click()
    let response = await responsePromise
    expect(response.status()).toBe(200)
```

**Comment by nico-olivares** [comment]
> @Louis24 We need more information to act on this issue.
> 
> @nico-olivares Well, it says "We couldn't verify the security of your connection". Perhaps, your site does not like headless browsers? I'd recommend talking to a developer to enable headless testing somehow.

I do need to add some information.
The issue started with V 1.44 and continues in 1.45. Before that the same tests had no issues.
The idea that my website is not headless enabled doesn't hold any water. I have hundreds of tests all working without any issue. As a matter of fact I also have similar tests that don't have issues either. What's really strange is that there's no issue in headed playwright vs headless playwright. You would think they would be the same engine (or almost the same).

**Comment by Louis24** [comment]
> > @Louis24 We need more information to act on this issue.
> > @nico-olivares Well, it says "We couldn't verify the security of your connection". Perhaps, your site does not like headless browsers? I'd recommend talking to a developer to enable headless testing somehow.
> 
> I do need to add some information. The issue started with V 1.44 and continues in 1.45. Before that the same tests had no issues. The idea that my website is not headless enabled doesn't hold any water. I have hundreds of tests all working without any issue. As a matter of fact I also have similar tests that don't have issues either. What's really strange is that there's no issue in headed playwright vs headless playwright. You would think they would be the same engine (or almost the same).

Sure I will add a video, dont know if github support video. as I mention the playwright can upload image (both head and headless), I guess some of the element change during upload videos

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this. It includes the code snippet that we can run locally to demonstrate the problem.
