### ISSUE TITLE
Is it possible to record videos only on failure for Electron app? Tried all options from the doc, but it didn't work

### ISSUE THREAD

**Issue by ypolishchuk-ledger** [microsoft/playwright#31895]
### Please do not submit this issue.

- [X] I understand

**Comment by mxschmitt** [comment]
Stopping recording is not supported as of today. You would need to start always and stop at the end and then decide to throw away or not. We recommend tracing, since it gives you a much better developer experience. The following resources might help you:

See here: https://playwright.dev/docs/api/class-tracing
That might help you as well: https://github.com/microsoft/playwright/pull/31437/files#diff-e2d41da267d99a638c95d506a28c9bdc5baec7ed34209f91badf95315122996bR44

Folding into https://github.com/microsoft/playwright/issues/8208
