### ISSUE TITLE
[Bug]:  /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /var/task/playwright/driver/node)

### ISSUE THREAD

**Issue by nessmahm** [microsoft/playwright#31891]
### Version

1.45.0

### Steps to reproduce

`# Stage 1: Build stage using Playwright image
FROM mcr.microsoft.com/playwright/python:v1.45.0-jammy as builder

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies

# Copy the function code
COPY handler.py .
COPY data_processing.py .
COPY aws.py .
COPY web_scraper.py .
COPY supabase_functions.py .

# Stage 2: Final image using AWS Lambda Python base image
FROM public.ecr.aws/lambda/python:3.8

# Set the working directory for the Lambda function
WORKDIR ${LAMBDA_TASK_ROOT}

# Copy the installed dependencies and function code from the build stage to the Lambda task root
COPY --from=builder /app ${LAMBDA_TASK_ROOT}

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt  --target "${LAMBDA_TASK_ROOT}"

# Set the handler function
CMD ["handler.future_ice_repports"]
`

### Expected behavior

That's my docker file i am trying to build an image with.
I am using playwright in aws lambda function but i keep geeting the GLIBC error. 

### Actual behavior

|  +6785ms Scraping iteration  1
|  +6806ms /var/task/playwright/driver/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /var/task/playwright/driver/node)
|  +6806ms /var/task/playwright/driver/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/playwright/driver/node)  

### Additional context

I has checked the GLIBC version in the image and it's 2.26.
Any idea how can handle this issue ?

### Environment

```shell
System : docker image - aws lambda function
```

**Comment by mxschmitt** [comment]
Your last `FROM` is `FROM public.ecr.aws/lambda/python:3.8` which is [Amazon Linux 2 based](https://hub.docker.com/r/amazon/aws-lambda-python#:~:text=These%20base%20images%20contain%20the%20Amazon%20Linux%20Base%20operating%20system%2C%20the%20runtime%20for%20a%20given%20language%2C), which we don't support. You need to use a supported linux distribution, see [here](https://playwright.dev/python/docs/intro#system-requirements). 

Since this is not a Playwright bug report, I'm going to close it for now. I recommend using e.g. Playwright's [Discord server](https://aka.ms/playwright/discord) community or StackOverflow for follow-up questions.
