### ISSUE TITLE
[Bug]: webkit defaultBrowserType doesn't even open the browser, but marks passed

### ISSUE THREAD

**Issue by MVenell** [microsoft/playwright#31905]
### Version

1.45.3

### Steps to reproduce

1. npm init playwright@latest

2. Add a project to playwright.config.ts:
name: "project 1",
      use: {
        viewport: {
          width: 1080,
          height: 2340
        },
        defaultBrowserType: "webkit"
      }

3. npx playwright test --headed

### Expected behavior

I expect the test to run. Nothing happens. Headed doesn't open the browser. Trace doesn't show anything actions.

### Actual behavior

The test shows the test passed, which is quite a big problem. If the test doesn't even open the browser, it CANNOT mark the test passed ever.

### Additional context

I tried it with all the different configurations with user agent, ismobile, and so on.

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 327.19 MB / 8.00 GB
  Binaries:
    Node: 22.3.0 - ~/.nvm/versions/node/v22.3.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v22.3.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.45.3 => 1.45.3
```

**Comment by mxschmitt** [comment]
I was not able to reproduce, for me it was running as expected, when I was adding the project as a 4th project, 4 projects were running: 
<img width="376" alt="image" src="https://github.com/user-attachments/assets/2c2b7516-7188-4d8b-84f2-9c0e693f9796">

> If the test doesn't even open the browser, it CANNOT mark the test passed ever.

Where do you want to mark the tests as passed? Are you running them by any chance via the VSCode extension?

Are you maybe in the wrong CWD?

(We recommend `browserName` instead of `defaultBrowserType` - should yield to the same outcome tho)

**Comment by MVenell** [comment]
I updated the Sonoma OS. It was outdated.
