### ISSUE TITLE
[Question] How to compare two screenshots?

### ISSUE THREAD

**Issue by randomactions** [microsoft/playwright#3193]
I am going through the documentation regarding screenshots https://playwright.dev/#version=v1.2.1&path=docs%2Fverification.md&q=screenshots

But I can't fine any methods that compare two screenshots. Am I missing something here?

**Comment by mxschmitt** [comment]
We did not include such a method into the library since not all users would use image comparisons. There are multiple ways of using it e.g. in combination with Jest you can use [jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot) or as a standalone JS library you can use [pixelmatch](https://github.com/mapbox/pixelmatch). In both you can pass then the raw image as a Buffer.

**Comment by randomactions** [comment]
Max, thank you for your reply! We use image comparison a lot as a cheap and easy way to track UI changes in our app.
