### ISSUE TITLE
[Feature]: playwright install function should be able to be silenced.

### ISSUE THREAD

**Issue by Tlo-l-w** [microsoft/playwright#32000]
### 🚀 Feature Request

A simple -q tag attached to !playwright install seems pointless bc it's a one time run, but would be useful for virtual environments that need to be reset regularly.

### Example

!playwright install -q
!playwright install --quiet

### Motivation

Should be a simple change and removes screen clutter.

**Comment by mxschmitt** [comment]
I'll close it for now since we don't plan to have this implemented in Playwright itself. It touches too many files / adds too much complexity to the already complex logic. Thank your for your attempt to implement it @JacksonLei123 tho. Appreciate looking into it.

As a workaround we recommend piping it into `/dev/null`

    playwright install > /dev/null
