### ISSUE TITLE
[Feature]: Make locator actions message customizable

### ISSUE THREAD

**Issue by Az8th** [microsoft/playwright#32002]
### 🚀 Feature Request

Hello, would it be possible to provide a way to custom locator actions messages/logs from the report (aside from test.step, which provides a way to wrap them)

### Example

Could be done by adding a `message` argument to all locator methods :
`await page.getByLabel('password').clear("I empty the password field");`

Another way would be to make locators extendable with custom functions, with their own messages (or at least make existing ones overridable)

### Motivation

As it has already been implemented for assertion in both cases, it would respect the existing logic.
`await expect(page.getByText('Name'), 'should be logged in').toBeVisible();`

Firstly, it would open a way to make those messages language agnostic, as they are actually only provided in english.
Secondly, it would avoid using to much test.step definition, thus removing 2 lines of code, a level of indentation, and limiting the reporters arborescence depth

Please don't hesitate to provide feedback or propose alternatives,
Thanks !

**Comment by yury-s** [comment]
We recommend `test.step` as the primary method of adding custom messages to the reports and grouping actions there. 
Wrapping with `test.step` requires extra code but it could be extracted into functions if repeated multiple times. Also with the [`box`](https://playwright.dev/docs/api/class-test#test-step-option-box) option you can hide some implementation complexity from the reports. 

> Another way would be to make locators extendable with custom functions, with their own messages (or at least make existing ones overridable)

There are no plans to make locators extensible. If new functionality is needed we can consider adding it to the core APIs, otherwise we expect clients to implement their helpers on top of the existing API.

Closing as there is an existing solution with test.step and there are no plans for adding custom messages to the API.
