### ISSUE TITLE
Successful button click on issue with Google Chrome[Bug]: 

### ISSUE THREAD

**Issue by sleepmac** [microsoft/playwright#32044]
### Version

1.45.0

### Steps to reproduce

Hi. Google Chrome browser has an open issue. https://issues.chromium.org/issues/40851596
When our team deployed out to production, some of the buttons in the Chrome MOBILE browser stopped working on click. The reason is in the issue above.
BUT IMPORTANTLY, we ran our tests with the config before the release. And they all passed successfully.
`{
			name: 'lg',
			testDir: './tests',
			use: { ...devices['LG Optimus L70'] },
			dependencies: ['setup'],
},`

Why when running the playwright tests the bug was not reproduced and button clicks were successful?

### Expected behavior

Tests failed, playwright could not successfully click a button.

### Actual behavior

The button clicks were successful.

### Environment

```shell
Operating System: Ubuntu 22.04.3 LTS x86_64
Extra: node v20.9.4
```

**Comment by yury-s** [comment]
> Why when running the playwright tests the bug was not reproduced and button clicks were successful?

If the bug is present in that version of the browser it should be detected by Playwright, there was likely a version mismatch between prod and your testing environment. Each Playwright version comes with browsers which match Chrome beta at the time of publishing. You can find the versions in the release notes, e.g. for [1.45](https://playwright.dev/docs/release-notes#browser-versions-1) it was Chromium 127.0.6533.5.  You can also test with particular version of vendor browser by specifying [a channel](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge).

If you think Playwright erroneously failed to catch the bug, please provide a self contained reproduction which we could run locally.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
