### ISSUE TITLE
[Feature] Set breakpoint on a javascript sources or URL contains (XHR)

### ISSUE THREAD

**Issue by asgmeonerandom** [microsoft/playwright#3213]
After doing it, I would like to get the variable and then stopped the execution. This is very useful and hopefully there is a way to do it. I looked googled everywhere but i didn't find this thing exist.

Thanks in advance

**Comment by dgozman** [comment]
Could you please provide more details?
- What is your debugging workflow? I assume you are debugging playwright script or test? How do you start debugging?
- Are you using some IDE? Maybe browser developer tools?
- Where would you want to set a breakpoint? In some javascript file of the page? In playwright script? In evaluation function, e.g. the one passed to `page.evaluate(myFunction)`?

**Comment by asgmeonerandom** [comment]
> Could you please provide more details?

I would like to know how can I do the same thing when I break `XHR containing URL` on chrome developer tools.

> * What is your debugging workflow? I assume you are debugging playwright script or test? How do you start debugging?

I'm using VSCode for coding if that is what you are asking. But the idea come from debugging using chrome developer tools.

> * Are you using some IDE? Maybe browser developer tools?

VSCode for programming

> * Where would you want to set a breakpoint? In some javascript file of the page? In playwright script? In evaluation function, 
e.g. the one passed to `page.evaluate(myFunction)`?

Setting the breakpoint will be from playwright script like of `break XHR Containing URL` works
For example this image,
![image](https://user-images.githubusercontent.com/64754175/88960775-aef94100-d2ac-11ea-9557-05f50023409a.png)

> In playwright script

If that's possible, that will be nice!

I would appreciate if there is a way to achieve this functionality or is there one exist and that I am not aware of?

(If that possible, it would be nice to control the breakpoint like calling bp.continue - make javascript to continue, getting information from this breakpoint, reading debugging variables)

Thanks again!

**Comment by dgozman** [comment]
Thank you for the details! I am a bit confused: why not use Developer Tools directly?

The easiest solution I'd suggest is the following:

1. Set a breakpoint (or debugger statement) in your Playwright script before navigating:
```js
const page = await context.newPage();  // Get the page in your preferred way.
debugger;
await page.goto(...);
```

2. Run your script with `PWDEBUG=true` environment variable. For example (on mac/linux): `PWDEBUG=true node script.js`.

3. Playwright should launch the browser in headful mode. Manually open Developer Tools for your page. If you prefer, pass `chromium.launch({ devtools: true })` option instead of opening DevTools manually.

4. Playwright script should be paused in your IDE of choice. You can step over, resume, etc. Before doing that, set up any XHR breakpoints or anything else in Developer Tools.

5. Now you can use your familiar tools to debug both the Playwright script (in your IDE) and the web page (in Developer Tools).

Let us know whether this works, or if there are any issues.

**Comment by asgmeonerandom** [comment]
thank you
