### ISSUE TITLE
[Feature]: Fluent Wait Support Similar to Selenium

### ISSUE THREAD

**Issue by razorblack** [microsoft/playwright#32203]
## Feature: Fluent Wait Support Similar to Selenium

**Description:** I would like to propose adding fluent wait support to Playwright, similar to what is available in Selenium. Fluent waits allow for more flexible and configurable waiting for conditions, which can be very useful for handling dynamic content.

**Current Behaviour:** Currently, Playwright supports fixed-time waits and `waitForSelector` which can handle simple cases. However, more complex scenarios requiring conditional waits or retries with configurable intervals are not as straightforward.

**Proposed Solution:** I propose adding a `FluentWait` class to Playwright, similar to Selenium. This class could include methods like:
- `withTimeout(Duration timeout)`: Sets the maximum time to wait.
- `pollingEvery(Duration interval)`: Defines the interval at which the condition is checked.
- `until(ExpectedCondition condition)`: Specifies the condition to be met.

This would allow users to specify more flexible waiting conditions and intervals, improving the reliability of tests with dynamic content.

### Example usage of FluentWait in Playwright (hypothetical syntax)
```js
await new FluentWait(page)
    .withTimeout(Duration.ofSeconds(30))
    .pollingEvery(Duration.ofMillis(500))
    .until(() => page.locator('#myElement').isVisible());
```

### Motivation

**Motivation:** I was doing migration of test cases from Selenium to Playwright in a project. During that time I realized the need for having a Fluent wait in Playwright.

I am open to discussing the design and implementation details further and would be happy to contribute to the development of this feature.

**Benefits:** Implementing fluent waits would make it easier to handle cases where elements appear or change state at unpredictable intervals. This would lead to more stable and reliable tests, reducing the need for hard-coded sleep statements and improving overall test performance.

**Comment by pavelfeldman** [comment]
Functionality like this would go against the Playwright principles. If we saw a snippet like this in the user's code, we would strongly recommend removing it, because it is a noop at best. Subsequent action on `page.locator('#myElement')` would already perform the necessary waiting. You can cap that specific action with the timeout, but event that is something we would not recommend. So if your wait is followed by some action, say click, instead of this snippet you should say:

```
await page.locator('#myElement').click()
```

*Site note: we don't recommend using element ids as locators either.*

**Comment by razorblack** [comment]
Okay, Thanks!
