### ISSUE TITLE
[Feature]: Ability to throttle CPU

### ISSUE THREAD

**Issue by davidbarratt** [microsoft/playwright#32207]
### 🚀 Feature Request

Chrome Dev Tools allows you to [throttle the CPU](https://developer.chrome.com/docs/devtools/device-mode#cpu) which is invaluable when attempting to test the performance impacts on mobile devices.

It would be extremely helpful if Playwright had a similar feature.

### Example

Since mobile devices have a lot less system resources at their disposal, being able to throttle the resources can help determine if tests start failing. This can help discover issues that are specific to mobile devices that wouldn't necessarily show up on systems with more resources (local development machine, CI, etc.)

### Motivation

Currently, if you run Playwright tests, sometimes they can sucsseed or fail depending on the resources available to playwright. I have several tests that consistantly sucsseed locally, but are flakey in GitHub Actions. I figured out that it was a resource constraint by running the tests in Docker and constrainting the resources. This feature would make testing more consistant between environments that have different resource constraints.

**Comment by pavelfeldman** [comment]
> Chrome Dev Tools allows you to [throttle the CPU](https://developer.chrome.com/docs/devtools/device-mode#cpu) which is invaluable when attempting to test the performance impacts on mobile devices.

Although I was leading the development of that feature in Chrome and this is nice to hear, I have to say that it is quite imperfect for this particular scenario and in general.

It seems like you have flaky tests that suffer from race conditions. Throttling CPU might trigger some of them, but that's definitely not the most efficient way of doing that. I would recommend running flaky tests on maximum workers your CPU can handle in a --repeat-each=1000 mode. You can also overbook those cores. Bump the test / expect timeouts to let the test run for longer due to the system being busy. That would surface all kinds of issues, including those that throttling would surface. If your test runs 100-1000 times in the overbooked manner, your test is good.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by ngraf** [comment]
You can already tell Playwright to throttle the CPU via the Chrome Developer Protocol (CDP) like this:

```
const context = page.context();
const cdpSession = await context.newCDPSession(page);
await cdpSession.send('Emulation.setCPUThrottlingRate', { rate: 6 }); 
```

It works like a charm and this is all I need. Not sure what your feature request asks for on-top.
The only caveat is that this is "chromium" only. Not Firefox or Webkit.

---

You can even put this code in a [Playwright fixture](https://playwright.dev/docs/test-fixtures) to potentially slow down ALL your tests at once. 

```
cpuThrottle: [
    async ({ browserName, page }, use)=> {
      if (process.env.THROTTLE) {
         const context = page.context();
         const cdpSession = await context.newCDPSession(page);
         await cdpSession.send('Emulation.setCPUThrottlingRate', { rate: parseInt(process.env.THROTTLE) }); 
     }
      await use(page)
    },
    { auto: true }
  ],
```
Then you can run something like `THROTTLE=6 npx playwright test` on-demand.
