### ISSUE TITLE
[Bug]: "URL did not settle" error in azureportal-test framework's navigateTo function when running e2e tests in mock replay mode

### ISSUE THREAD

**Issue by shadyabarada** [microsoft/playwright#32228]
### Version

"@axe-core/playwright": "^4.8.4", "playwright": "^1.33.0", "node_modules/playwright": {       "version": "1.44.1"}

### Steps to reproduce

1. In your e2e test call the openResourceBlade function of microsoft-azureportal-test framework which calls the navigateTo function.
2. Run the test in mock record mode: It passes.
3. Run the test in mock replay mode: fails with URL did not settle error in the navigateTo function.

### Expected behavior

I expect the blade to load as expected just like how it did in the mock record run.

### Actual behavior

The test fails opening the blade with the url did not settle error.

### Additional context

![image](https://github.com/user-attachments/assets/87cfa8da-e91d-4527-bd18-eb74be528ab5)

note that when I set the browser automation to be "web driver" instead of playwright, the test works and the blade loads successfully. 

### Environment

```shell
System:
    OS: Windows 10 10.0.20348
    CPU: (32) x64 AMD Ryzen Threadripper PRO 3955WX 16-Cores
    Memory: 104.27 GB / 127.86 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.92.2 - C:\Users\shadiabarada\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

Also it looks like you are not using the [official test-runner](https://playwright.dev/docs/intro), we strongly recommend using it for having access to the VSCode integration and other valuable tooling.
