### ISSUE TITLE
[Bug] [VSCODE extension]: Multi-root workspaces with playwright confuses the extension, both test suites never show up

### ISSUE THREAD

**Issue by alexrecuenco** [microsoft/playwright#32338]
### Version

1.46.1

### Steps to reproduce

1. Clone my repo `https://github.com/alexrecuenco/playwright-multiroot-report`
2.  `cd playwright-multiroot-report`
3.  `npm install` in both `a` and `b`
4. Open it with `code ./report-playwright.code-workspace` to open a multi-root workspace
5. Go to the `Testing` View, 
6. See that not both `a` and `b` ever show up, and if you refresh you get either a or b showing up their tests suites

<img width="306" alt="Screenshot 2024-08-27 at 2 32 49 PM" src="https://github.com/user-attachments/assets/372181fb-2178-4b44-9520-d54a6c4ddb41">
<img width="263" alt="Screenshot 2024-08-27 at 2 32 54 PM" src="https://github.com/user-attachments/assets/9aa8b9d9-a12a-4aba-9ef4-95d38ccce8b0">

 

### Expected behavior

I see both test suites, the test suites of `a` and `b`

### Actual behavior

The test suite of `a` shows up, or `b` , it appears to be random

### Additional context

We currently have multiple projects. And I prefer to have them all collected into one workspace from which to work, and playwright seems to be causing some conflict

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M2
    Memory: 87.95 MB / 16.00 GB
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
  IDEs:
    VSCode: 1.92.2 - /usr/local/bin/code
  Languages:
    Bash: 5.2.26 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1
```

**Comment by alexrecuenco** [comment]
I would put it in `microsoft/playwright-vscode` but that place repository doesn't allow issues. So I imagine you want the report here

**Comment by LiamLamb** [comment]
I also saw this, but I have managed to get around it. 
I have a branch [here ](https://github.com/LiamLamb/playwright-shared/tree/multi-root-workspace) with instructions on reproducing it. 

I managed to get it to work with the following steps:
1. Click on the playwright gear icon at the bottom of the test view:
![Image](https://github.com/user-attachments/assets/81c1d580-18cd-402c-a658-9e287f7317a7)

2. Select the missing project(s):
![Image](https://github.com/user-attachments/assets/e49dd628-944b-45e6-a418-5a6a658e6f59)

Now both projects are showing up in the test window and I can run them with the top-level controls:
![Image](https://github.com/user-attachments/assets/6a864694-b9a3-43f2-81a4-f1e95aa1ec09)

**Comment by mxschmitt** [comment]
@alexrecuenco could you try this as well on the latest VSCode extension version?

**Comment by alexrecuenco** [comment]
Hey, nop. Same issue with v1.1.11. I just tried it by cloning the repo with the steps provided above.

But @LiamLamb steps seem to circumvent this issue

Are the steps I showed difficult to replicate?

**Comment by mxschmitt** [comment]
I was able to reproduce that when you open the projects initially, you sometimes get `a` and sometimes `b` shown. This is because we pick internally the first one which resolves from `findFiles` which has a non-deterministic order. I created a patch to workaround this here: https://github.com/microsoft/playwright-vscode/pull/563.

To address the issue that only one project is getting listed I was able to fix by enabling it. See the following steps similar to the ones shown in https://github.com/microsoft/playwright/issues/32338#issuecomment-2423659833.

1. Open "Testing" view
2. In Playwright click the gear icon:

![Image](https://github.com/user-attachments/assets/af3950cf-33fe-493d-8107-db4fb8b97dc9)

3. Make sure to select both projects:

![Image](https://github.com/user-attachments/assets/3500398e-cc3c-48b7-9bc0-ae48e303c52c)
