### ISSUE TITLE
[Feature]: "trace" config should treat screenshots in the same way as trace.zip

### ISSUE THREAD

**Issue by Exoow** [microsoft/playwright#32405]
### 🚀 Feature Request

The `trace` setting in the config should treat screenshots (actual-diff-expected) according to this logic.

### Example

- our playwright config has `trace: "on-first-retry"` with the intention to only have 1 folder per failing test (regardless of number of retries)
- when there is a test with a failing screenshot comparison, the output is per the image below. This is **unexpected** for us, because now we have two folders for one failing test.

![image](https://github.com/user-attachments/assets/e1d6c516-3e88-4aed-85a2-6ccb503e6388)

### Motivation

Unnecessary test artifacts will no longer be generated, making it cleaner without "duplicate" failing test folders.

**Comment by dgozman** [comment]
@Exoow Playwright generates screenshot expectations for each run to avoid data loss. How do you use files from `test-results`, in a way this is a problem? We recommend looking at the report instead. For example, html report will show you trace/screenshots inline, so you don't care about the folder structure. Please tell us more about your workflow.

**Comment by pavelfeldman** [comment]
> isn't that the same for the trace files

We think of those as different. Trace file is a byproduct of the test execution. It contains a recording of the test run, it can't affect the test outcome (passed / failed). It is not essential to correctness. It is also adding certain overhead to the test execution so that we don't want to record it at all times.

Screenshots are essential part of the visual regression testing. They define the correctness of the test. When a screenshot test fails, we must print old and new value, much like you expect to see an error message for `expect(1).toBe(2)` regardless of whether you ran this test for the first time or for the second time.

If you'd like to rely upon the folder structure for your process, I'd suggest that you implement a custom reporter that copies the artifacts that you need (and only those you need) into a sibling folder. Otherwise, the structure of the test-results folder is an implementation detail of Playwright, it can change at any point. Not that we have plans to change it, but it is easier to make a point this way.

**Comment by Exoow** [comment]
Okay, fair enough. :)

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
