### ISSUE TITLE
[Bug]: Recorder doesn't work when `Array.prototype.toJSON` is declared

### ISSUE THREAD

**Issue by ruifigueira** [microsoft/playwright#32507]
### Version

1.47.0

### Steps to reproduce

I was trying recorder on a site that defines `Array.prototype.toJSON` (it uses prototype.js 1.7), which messes up `JSON.stringify`.

To replicate it, run the following command (I ran it in powershell, so maybe it needs to be adjusted):

```bash
npx playwright codegen 'data:text/html,<script>Array.prototype.toJSON = () => `[]`;setTimeout(() => delete Array.prototype.toJSON, 5000)</script>'
```

Recorder only starts working when `Array.prototype.toJSON` gets deleted.

**Edit:** It also impacts `exposeFunction`:

```ts
test('should work with busted Array.prototype.toJSON', async ({ page }) => {
  await page.setContent(`<script>
    Array.prototype.toJSON = () => '';
  </script>`);
  await page.exposeFunction('add', (a, b) => a + b);
  expect(await page.evaluate('add(5, 6)')).toBe(11);
});
```

### Expected behavior

It should record the page.

### Actual behavior

It doesn't record the page.

### Additional context

This is a very similar to #22528. 

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i5-1335U
    Memory: 10.19 GB / 31.66 GB
  Binaries:
    Node: 20.17.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    npm: 10.8.2 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  IDEs:
    VSCode: 1.93.0 - C:\Users\rui.figueira\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.26 - C:\Users\rui.figueira\scoop\shims\bash.EXE
  npmPackages:
    @playwright/test: ^1.47.0 => 1.47.0
```

**Comment by ruifigueira** [comment]
I added a patch proposal in PR #32508

**Comment by dgozman** [comment]
I'll keep the issue open because the recorder still does not work, in case it turns out to be a popular problem.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
