### ISSUE TITLE
[internal] firefox flaky tests that needs investigation

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#32541]
- `page/frame-goto.spec.ts:46 - should continue after client redirect` is disabled because script.js is requested before navigationCommitted arrives
- [`page/page-event-request.spec.ts:169 - should return response body when Cross-Origin-Opener-Policy is set`](https://devops.playwright.dev/flakiness.html#show_flaky=true&filter_spec=should+return+response+body+when+Cross-Origin-Opener-Policy+is+set) times out flakily
- `page/page-click.spec.ts:88 - should not throw UnhandledPromiseRejection when page closes` is disabled because it makes the next test to always timeout

**Comment by unlikelyzero** [comment]
This is still happening. \`page/page-event-request.spec.ts:181 - should return response body when Cross-Origin-Opener-Policy is set\` on firefox currently fails on its first attempt in ~15% of CI runs (287/1869 in the recent test-results window), always rescued by retry. Most recently seen on PR #42191 ([run](https://github.com/microsoft/playwright/actions/runs/31450894460)), unrelated to that PR's diff.

I wasn't able to reproduce it locally after 15 repeated runs (single worker), which lines up with the existing code comment that the root cause is unclear and likely tied to CI load/timing. I don't have permissions to reopen this issue — could someone with write access reopen it, since the underlying flake was never actually fixed?
