### ISSUE TITLE
[Regression]: MCR latest tag still points to 1.46

### ISSUE THREAD

**Issue by marekdedic** [microsoft/playwright#32544]
### Last Good Version

1.46.1

### First Bad Version

1.47.0

### Steps to reproduce

Hi,
I'm using Docker images from MCR. I noticed that after the realease of 1.47, the latest tag wasn't updated and still points to 1.46

1. Go to https://mcr.microsoft.com/en-us/product/playwright/tags
2. Search for `02810c978d5396bf382ab6015c25ad6bed9e39f4a41c5b9c829e9fea439274e2`
3. You will see `1.46.1` and `latest` both with this hash

### Expected behavior

latest is an alias for 1.47

### Actual behavior

latest is an alias for 1.46

### Environment

```shell
N/A
```

**Comment by mxschmitt** [comment]
Looks like https://github.com/microsoft/playwright/issues/32483#issuecomment-2334265736. Could you help us understand why you are using `:latest` and not a pinned Docker tag? 

We never documented `:latest` and decided as per the last release to stop publishing it (see the release notes) in order to recommend the best practises (pinning to an exact version).

**Comment by marekdedic** [comment]
Hah didn't search the closed issues, sorry for the duplicate.
