### ISSUE TITLE
[Feature]: --only-changed option to only compare test files, no dependencies

### ISSUE THREAD

**Issue by jwenclOG** [microsoft/playwright#32561]
### 🚀 Feature Request

The current --only-changed test run option will run all tests affected by import changes.  This frequently results in all of the tests running on version bumps.

A new option for --only-changed that would allow us to only run changed test files instead of all test files affected by changes.

### Example

An additional argument for running tests.

```
npx playwright test --only-changed
```

we would instead run

```
npx playwright test --only-changed-tests
```

This would instead run only changed test files.

### Motivation

We intended to use --only-changed to run tests as part of our check-in gate so that users are not merging broken tests.  We've found that if there's a dependency change it will run ALL of our tests.  Since our test suite is quite long and we need to setup additional parallelization to handle it, --only-changed isn't a viable option for us.  We typically validate dependency changes in a separate action via workflow dispatch.

An option to run only affected test files would simplify this process for us.

**Comment by Skn0tt** [comment]
Hello Josh, thanks for elaborating on the use case! We're a little hesitant of introducing this as a CLI flag because of the ambiguity it would create.

You should be able to build your own `--only-changed` by performing the git diff yourself. Here's a snippet that worked for me:

```bash
npx playwright test  $(git diff $YOUR_BASE_COMMIT --name-only) 
```

This is very similar to how `--only-changed` works under the hood. Let me know if this helps your use case 😁

**Comment by jwenclOG** [comment]
This looks like it resolves my issue, thank you!
