### ISSUE TITLE
[Feature] Page.click() add log entry if > 1 elements will be found in actionability checks

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#3264]
We faced into the issue that we have element A and B with the same buttons and the same text inside. Element A does not pass the actionability checks. But element B does.

For me as a user the best would be if element B will be used instead then, since @pavelfeldman mentioned in a chat we should not change the API, a log message would make sense there if more than 1 element will be found so we can give the user a hint in the Error which will be thrown.

Minimal example: https://try.playwright.tech/?s=47h4i
Removing the first div with the hidden class will lead to the popup 2. If we don't modify it it won't find any element since its waiting for the first div.

**Comment by dbjorge** [comment]
This would be great! This would have saved me 30 minutes of debugging the other day.

Personally, I think the most reliable behavior would be for Playwright to consider "there are multiple candidate elements that match the selector" to be an actionability failure itself, regardless of whether the individual candidates are themselves actionable, but that would be a hard sell for backcompat. Logging it is a good intermediate step.

**Comment by rstarkov** [comment]
When testing a modal dialog that obscures a large UI, spurious matches for things that aren't clickable become fairly common, and the only workaround is to tag those with something like `data-test-id` (or employ complex selectors that are bound to change when unrelated things get refactored).

Cypress manages to ignore matches behind a modal quite well, and I can't help but wish for some way to replicate that in Playwright, instead of tagging everything with test IDs. I realise that it's ambiguous, for example should it try to scroll, or what if scrolling makes something else clickable. But it only needs to be repeatable and consistent to avoid flake, and coupled with succeeding only if there is a single usable match I feel it would go a long way. Perhaps as a new API?
