### ISSUE TITLE
[Regression]: Docker "latest" tag not updated

### ISSUE THREAD

**Issue by othiman** [microsoft/playwright#32676]
### Last Good Version

v1.46.1

### First Bad Version

v1.47.0

### Steps to reproduce

docker pull mcr.microsoft.com/playwright:latest

### Expected behavior

I expect to get v1.47.1 instead of v1.46.1 when pulling "latest"

### Actual behavior

I get version v1.46.1

### Additional context

I am not sure if this is on purpose, but normally "latest" should be linked to the latest release, I think.

### Environment

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 39.31 GB / 62.17 GB
    Container: Yes
  Binaries:
    Node: 22.8.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.47.1 => 1.47.1
```

**Comment by mxschmitt** [comment]
Looks like https://github.com/microsoft/playwright/issues/32483#issuecomment-2334265736. Could you help us understand why you are using `:latest` and not a pinned Docker tag? 

We never documented `:latest` and decided as per the last release to stop publishing it (see the [release notes](https://github.com/microsoft/playwright/releases/tag/v1.47.0)) in order to recommend the best practises (pinning to an exact version).

**Comment by othiman** [comment]
Thanks for the fast answer. :-)

Good to know. We use the latest tag in our build system, but when I think about it, it would be better to use the matching version for better reproducibility.

If possible it might be an idea to actually delete the latest tag (if this is possible). As it was never really documented and supported it gives people a hint that are not using the correct/up-to-date version.

Best regards,
Thomas
