### ISSUE TITLE
My app's backend is salesforce, sometimes when i try to login to my app ,it asks for 2f authentication. ?How to overcome this issues? because of this my script gets failed

### ISSUE THREAD

**Issue by Rifaudeen** [microsoft/playwright#32732]

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)
