### ISSUE TITLE
[Bug]: `Locator.focus` does not respect the default timeout of 0 (no timeout)

### ISSUE THREAD

**Issue by u1f992** [microsoft/playwright#32872]
### Version

1.47.2

### Steps to reproduce

```javascript
import { chromium } from "playwright";

const browser = await chromium.launch();
try {
    const page = await browser.newPage();
    await page.setContent(`
    <html>
        <body>
        <script>
            setTimeout(() => {
                const input = document.createElement('input');
                input.id = 'delayed';
                input.type = 'text';
                document.body.appendChild(input);
            }, 35000);
        </script>
        </body>
    </html>`);
    const locator = page.locator('#delayed');

    try {
        await locator.focus();
        console.log('success');
    } catch (error) {
        console.error('failed:', error);
    }
} finally {
    await browser.close();
}
```

### Expected behavior

According to the `types.d.ts` [documentation](https://github.com/microsoft/playwright/blob/2f7b06736fb0684830b781095ae02af54f6b357e/packages/playwright-core/types/types.d.ts#L13074), the `timeout` option of the `Locator.focus` method should default to 0, meaning there should be no timeout. In the provided script, calling `locator.focus()` without setting a `timeout` should wait indefinitely for the element to appear and then focus on it once it exists.

### Actual behavior

When running the script, the following error is thrown: `"failed: locator.focus: Timeout 30000ms exceeded."`

However, when the `timeout` option is explicitly set to `{timeout: 0}`, the script works as expected, and `"success"` is logged. This indicates that the default timeout of 0 (no timeout) is not being applied as documented.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (14) x64 Intel(R) Core(TM) Ultra 7 155U
    Memory: 15.96 GB / 31.52 GB
  Binaries:
    Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.8.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.93.1 - C:\Users\mukai\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Windows\system32\bash.EXE
  npmPackages:
    playwright: ^1.47.2 => 1.47.2
```

**Comment by Skn0tt** [comment]
Thanks for reporting, can reproduce. This indeed looks weird. We document a different default timeout for JS than for other languages, which is surprising because the implementation is the same: https://github.com/microsoft/playwright/blob/aa3146785f2eb1add5bfafdd7d61bf663e0ad59a/docs/src/api/params.md?plain=1#L49-L62
I'll see what's going on here.

**Comment by Skn0tt** [comment]
Alright, so it turns out that the default timeout is different when used as a library than when used with the test runner. Our JS documentation focuses on usage with the test runner, so it says that the default timeout is 0. You're using it with the library though, and then the default timeout is 30s - as you found out yourself. So this is very much intended, but our docs are unclear on it. Sadly, it's really hard for us to make this clear in the docs without becoming very lengthy. We've added a note about it in https://github.com/microsoft/playwright/pull/32883 though, hope that helps a little.
