### ISSUE TITLE
[Feature]: need support to run playwright in amazon linux 2033 os

### ISSUE THREAD

**Issue by ujjwaljamuar** [microsoft/playwright#33067]
### 🚀 Feature Request

Thousands of ci are now migrating from ubuntu to amazon linux os, 

Unfortunately playwright does not support it,

When we run playwright python on AML it says install drivers manually to install and run browsers,

And its very difficult to find all the browser with all the drivers.

Look into this if possible.

### Motivation

Working on browser automation, but stuck with amazon linux

**Comment by pavelfeldman** [comment]
This falls outside of the scope for Playwright.

**Comment by quantizor** [comment]
> This falls outside of the scope for Playwright.

Respectfully I think it is in Playwright's scope to get your binary to work on RPM-based distros.

**Comment by Ahmed-Soli** [comment]
I know this issue is a bit old, but I recently faced the same problem and managed to get it working on Amazon Linux 2023 by installing the necessary dependencies.

My OS details:

```
Amazon Linux release 2023.6.20250107 (Amazon Linux)
cpe:2.3:o:amazon:amazon_linux:2023
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023.6.20250107"
```

To fix the issue, I installed the following packages:

```bash
sudo dnf install -y libXcomposite libXcursor libXdamage libXext libXi libXtst cups-libs \
libXScrnSaver libXrandr gtk3 pango alsa-lib atk at-spi2-atk at-spi2-core libdrm \
libxkbcommon nss xorg-x11-server-Xvfb libgbm
```

Then I ran:

```bash
playwright install chromium
```

Don't worry if you see warnings like this:

```
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
```

That’s expected — Amazon Linux 2023 isn’t officially supported by Playwright, so it defaults to Ubuntu 20.04 builds. In most cases, this fallback works just fine as long as all required system libraries are present — which the above install command covers.

Hope this helps someone else!

**Comment by JoseAFerrer** [comment]
Thank you so much, @Ahmed-Soli , I did this and it worked!
Just in case anyone else comes looking, I installed the packages as Ahmed suggested and then I added this to the script (I am running this in Azure DevOps pipelines, self hosting in AWS Amazon Linux 2023):
```
                sudo cp $(envTest.secureFilePath) .env.test
                yarn playwright install
                yarn playwright install-deps
                yarn playwright install chromium
                yarn test
```

Additionally, it seems I need to run headless and it still doesn't work perfectly for me, but that's unrelated and I'm on it.
