### ISSUE TITLE
[Docs]: Better separation of Playwright API and Playwright Test features in Releases

### ISSUE THREAD

**Issue by Snooz82** [microsoft/playwright#33187]
### Page(s)

https://playwright.dev/docs/release-notes

### Description

We are API users of Playwright NodeJS. (Robot Framework)

It would be really nice, if the Release notes could be separated in new features of Playwright Test vs new stuff in Playwright API (core).
So stuff that is imported from '@playwright/test' vs those features that are base on browser, context or page...
We as a pure API users can not use Test features and i think other language adaptations have the same need.

Also it would be really nice, if there would be a more detailed information about all new features to the API and not "just" the Highlights.
Maybe we just did not find them yet. But we had the experience, that a nice feature was just discovered by going through all interfaces and we could not find a word about it in the release notes.

Thanks for this great technology !!!
Cheers
René

**Comment by scott-au** [comment]
> But we had the experience, that a nice feature was just discovered by going through all interfaces and we could not find a word about it in the release notes.  

what was the nice feature ?

**Comment by mxschmitt** [comment]
We used to have them separate but learned that our customers are more interested in the overall release notes. Nowadays the users mostly look at Playwright in a single tool rather than two different tools, library + test-runner. To get a best idea of what the library release notes are we recommend looking a the [Python release notes](https://github.com/microsoft/playwright-python/releases).

I'll close it for now since we don't plan to split them in the future.
