### ISSUE TITLE
[Feature]: Add a setting for saving alert messages to the test report before playwright dismiss them

### ISSUE THREAD

**Issue by marcusNumminen** [microsoft/playwright#33192]
### 🚀 Feature Request

Hi!
I would love to have a setting where we could enforce alert messages to be stored as attachments to the test report before playwright dismisses them. We have seen cases where something goes wrong and the alert message prints valid information but since playwright screenshots do not capture alert dialog we miss this information and need reproduce this issue manually.

I know that I can add this by myself by do something like this:
```
page.on('dialog', async (dialog) => {
   // attach dialog.message() to the report
   await dialog.dismiss();
});
// rest of the code
```
But then I need to update all the test manually to this... 

The setting could have 'dismiss', 'report-and-dismiss' and 'console-log-and-dismiss' as options and default to 'dismiss', it could look something like this in the config:
`dialogs: 'report-and-dismiss' `

### Motivation

With this feature we wouldn't miss important information that is stated in dialogs, we wouldn't miss that there have been a alert dialog open during the test either.

**Comment by mxschmitt** [comment]
Instead of updating all your tests, you could also override the `page` fixture and just [do it once](https://playwright.dev/docs/test-fixtures#overriding-fixtures) and change your @playwright/test import. We only dismiss the dialog when there is no event listener attached, so adding one like you did overrides this behaviour.

Would that work for you?

We are usually careful with adding new features like this, since e.g. dialogs are not really recommended from the web-platform perspective anymore, most websites use in-page alternatives inside the DOM, since they are more flexible.

**Comment by marcusNumminen** [comment]
Hi!
I have been thinking of that as well but due to a poor design choice from start we can't really do that without doing a major change.....
