### ISSUE TITLE
[Bug]: Global tear down not running automatically when using vs code extension

### ISSUE THREAD

**Issue by JohnAllenTech** [microsoft/playwright#33193]
### Version

1.48.0

### Steps to reproduce

1. Create a global tear down file called teardown.ts like [here](https://playwright.dev/docs/test-global-setup-teardown#option-2-configure-globalsetup-and-globalteardown)
2. Add globalTeardown: "./e2e/teardown.ts" to your playwright config
3. Install the latest playwright plugin for VS code
4. Run all tests. It doesnt run the global teardown automatically.

### Expected behavior

I expect the global teardown to be ran after each test suite run

### Actual behavior

The global teardown doesnt run after each test suite run.

### Additional context

The global setup script runs on every test suite run

https://github.com/user-attachments/assets/ef267892-afbe-4929-b8df-098cd9da98b2

### Environment

  System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 309.41 MB / 16.00 GB
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.18.0/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.15.5 - ~/.nvm/versions/node/v18.18.0/bin/pnpm
  IDEs:
    VSCode: 1.94.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.0 => 1.48.0

**Comment by mxschmitt** [comment]
You need to run the global teardown manually when using the VSCode extension:

![Image](https://github.com/user-attachments/assets/d3d97d10-06fa-4f01-9845-4e62bbe7dffa)

See [here](https://playwright.dev/docs/getting-started-vscode#global-setup).

**Comment by mxschmitt** [comment]
Its expected that you need to run global teardown manually, see [here](https://playwright.dev/docs/getting-started-vscode#global-setup). Would you like to run it automatically?

**Comment by JohnAllenTech** [comment]
Hi @mxschmitt 👋🏻 the only reference to global teardown on the link you shared was

"You can also run global teardown tests by clicking the Run global teardown option."

To me this might just be a documentation issue. If the documentation specified I need to run it manually then I would know. Because it didnt I assumed like global setup that it would run automatically.

**Comment by JohnAllenTech** [comment]
The option to run it automatically after each test run might be a nice to have

**Comment by maddox05** [comment]
global teardown is grayed out I cant even run it manually

**Comment by markomirtic** [comment]
This is bug for sure, teardown isn't triggered after global setup.

**Comment by sonicviz** [comment]
I have the same issue. It works fine manually triggered, but refuses to run automatically after all tests complete. 
Playwright is a great system, but has some frustrating flaky behavior like this.

**Comment by sonicviz** [comment]
You need to be able to run globalTeardown automatically. 

The only way to clear out your test data is to move the globalTeardown code to the globalSetup and run it before you run your tests, but I've found even that doesn't work.

Why?

What happens is once you run globalSetup, it doesn't run the next time automatically. 
globalSetup manual button is now grayed out, but globalTeardown, even if you haven't configured one, is now active, and you need to click that - even if it does nothing - to reenable globalSetup to run automatically again. 

This is a very bizarre setup, and completely illogical. 

The whole concept of a globalSetup/teardown process is to be able to automatically setup/teardown test configs, but it doesn't even do half of it properly, as it will only run setup once and then you have to manually intervene again. 

How is that logical for an automated testing suite/system?

Can someone shed some light on this, because this is the behavior I've observed after much frustrating testing trying to figure out why it's not doing what you logically would expect it to do. 

Even if the documentation is right that teardown has to be run manually, that shouldn't stop globalSetup from being run automatically every time.

**Comment by gilad905** [comment]
I agree that this should be able to be run automatically. if not by default, at least somehow to specify it in the config.
a workaround that might fit can be a custom reporter with the onEnd hook:

playwright.config.ts:
```
  reporter: [["./my/custom/reporter.ts"], /* ["list"], etc. */ ],
```

./my/custom/reporter.ts:
```
export default class {
  async onEnd() {
    // your code here
  }
}

```

(onExit is also documented, however for some reason doesn't get triggered on my setup)
