### ISSUE TITLE
[Feature]: project-scoped fixtures

### ISSUE THREAD

**Issue by mfulton26** [microsoft/playwright#33232]
### 🚀 Feature Request

I'd like to do setup and teardown of resources for each project. I can use [test project dependencies](https://playwright.dev/docs/next/api/class-testproject#test-project-dependencies) but I'd much rather manage these resources the same way I manage my worker-scoped resources and test-scoped resources: it feels more consistent, and I believe yields more reusable and readable code.

### Example

Very similar to https://playwright.dev/docs/test-parallel#isolate-test-data-between-parallel-workers but instead of isolating test data between parallel workers the isolation applies to projects (which are possibly running in parallel but not necessarily).

### Motivation

I thought [test project dependencies](https://playwright.dev/docs/next/api/class-testproject#test-project-dependencies) would work but then I realized I would need to define a different setup project for each of my other projects just so that I can pass a unique type into the same setup code. It seems cumbersome and not as dynamic/easy as test-/worker- scoped fixtures.

**Comment by mxschmitt** [comment]
Fixtures live inside a worker and are able to share state between before and after a test execution or worker execution. Its one of the core concepts, that they are type/data driven. In case of "project-scope fixtures" this would not be possible, since the first test could run in worker[0] and the last test could run in worker[42]. Between these you can't share any state, have no access to the page variables etc. We introduced project dependencies for that to fix it which work for your use-case as you said. I'll close it for now since we don't plan to add another abstraction.

Similar to https://github.com/microsoft/playwright/issues/12084#issuecomment-1414389721
