### ISSUE TITLE
[Bug]: XPath for text nodes fail with element(s) not found error

### ISSUE THREAD

**Issue by viveleroi** [microsoft/playwright#33234]
### Version

1.48.1

### Steps to reproduce

Clone repo and run tests: https://github.com/viveleroi/playwright-text-node-repro

### Expected behavior

The text node should be located and `textContent` read correctly.

### Actual behavior

Element is not found.

### Additional context

We need to verify some DOM logic operates correctly and want to verify that the text nodes of a DOM element contain the exact text.

Using the playwright dev site as an example, `//h1/span/text()[1]` is a valid XPath. When executing this xpath manually, it returns `Playwright`

```
document.evaluate(
  '//h1/span/text()[1]',
  document,
  null,
  XPathResult.FIRST_ORDERED_NODE_TYPE
).singleNodeValue.textContent
```

However, when used in playwright it fails, claiming it can't find the element.

Yet when I use an xpath for the `span` itself and ask for it's text (or even `textContent`) it returns correctly, so it's *only xpaths for text nodes*.

```
Error: Timed out 5000ms waiting for expect(locator).toHaveText(expected)

Locator: locator('//h1/span/text()[1]')
Expected string: "Playwright"
Received: <element(s) not found>
Call log:
  - expect.toHaveText with timeout 5000ms
  - waiting for locator('//h1/span/text()[1]')


  5 |
  6 |   await expect(page.locator('//h1/span')).toHaveText('Playwright');
> 7 |   await expect(page.locator('//h1/span/text()[1]')).toHaveText('Playwright');
    |                                                     ^
  8 | });
  9 |
```

### Environment

 System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 9.48 GB / 31.73 GB
  Binaries:
    Node: 21.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.14.2 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.6 - C:\Program Files\nodejs\bun.CMD
  IDEs:
    VSCode: 1.94.0 - C:\Users\mbotsko\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.1

**Comment by mxschmitt** [comment]
Its known that it doesn't work on Text nodes as of today, what is your use-case? Ideally you use the recommend locators instead of XPath, see [here](https://playwright.dev/docs/best-practices#use-locators). This will not only make the test much more readable, it will also if you are using role selectors do partial accessibility testing as a drive-by.

Similar to https://github.com/microsoft/playwright/issues/11174.

**Comment by viveleroi** [comment]
For example, given `<p>one<br>two</p>` I need to verify that the first text node is `one` and the second text node is `two`. We're using playwright to test some DOM changes performed by some basic content editing tools. getByText, p.textContent, etc won't work because they won't verify that `br` is in the right spot. Counting `p.childNodes` length won't either.

**Comment by mxschmitt** [comment]
Imagine a user - the user usually doesn't know what element a text node or span is. You could do the following instead which is much more user-facing: 

```ts
await page.setContent(`
    <div role="main">
      <p>one<br>two</p>
    </div>
  `);
  await expect(page.getByRole('main')).toContainText('one\ntwo', { useInnerText: true });
```

**Comment by viveleroi** [comment]
The problem is that only addresses this specific instance, `br`, which is my fault for not expanding. We're testing a plugin we're writing for TinyMCE which is a content editor, so we have to simulate user actions in browsers and then verify the content _and_ DOM are correct. 95% of the time, normal locators, getByText, etc works fine. But it's when text nodes are broken up that this became a problem. `br` is an example but it could be any inline element, like `<p>normal text <strong>bold text</strong></p>`

**Comment by mxschmitt** [comment]
I see, when testing editors etc. we recommend more low-level primitives, e.g.:

```
await expect.poll(() => page.locator('.edit').innerText()).toContain('<p>normal text <strong>bold text</strong></p>');
```

Depending on your use-case, you could use `toBe`, `toContain` etc. I'm using `expect.poll` so that it does retry over and over again until the condition is met or the timeout has been reached.

Our XPath selector engine is unfortunately designed like that it can't receive any test-values, it only looks at Elements, see [here](https://github.com/microsoft/playwright/blob/0d12fbe0025729d372800934dc01a9283cb348b5/packages/playwright-core/src/server/injected/xpathSelectorEngine.ts#L29).

I hope that helps a bit!
