### ISSUE TITLE
[Bug]: The Runner doesnt stop on VSCode even if you click Stop button. I have to disable extension to stop it.

### ISSUE THREAD

**Issue by mglennon** [microsoft/playwright#33299]
### Version

1.1.11

### Steps to reproduce

1. Add the playwright test  in VScode
2. Run a test, mine is playwright ts
3. Try and stop the Run via Button above.

**Actual Outcome**
Still running 
**Expected Outcome**
test run stops 

See Video file.https://github.com/user-attachments/assets/856727dc-c7df-4dd3-a223-73ad605ff6db

### Expected behavior

I expect the test to stop.

### Actual behavior

The test just keeps running 

### Environment

Windows 23h2.

**Comment by Skn0tt** [comment]
We can't investigate without a repro. If you continue seeing the issue, please file another bug report and follow the instructions.

**Comment by marc-guenther** [comment]
Same here, I'm on 1.1.13, and sometimes the test runner just continues on forever, and there is no way to stop or restart it, except for restarting VSCode.
This was already reported for version 1.1.1 in #30808 and #30849, and fixed in microsoft/playwright-vscode#478, but it still happens for me, not every time, but often enough to be annoying.

**Comment by sKopheK** [comment]
second that, this time i run a test, it failed, tried to run it again, it took 90 secs! to start the test, besides the timer increasing its value nothing was changing in the IDE
