### ISSUE TITLE
[BUG] global variables are not getting initialized after test is getting failed

### ISSUE THREAD

**Issue by KAjayGoutham** [microsoft/playwright#33337]
i have added a global variables under describe block and the variables are only getting initialized when test is passed, when the test is failed the variables are not getting initialized 

example : 
```typescript
describe.test('backup',async ()=>{
let createdProxy:string
test('backup',async(backupPage)=>{
createdProxy= await backupPage.createResources();
})

test('clear resources',async(backupPage)=>{
await backupPage.deleteResource(createdProxy); // if the test is failed this block of code is not working cause the variable initialization is not happening
})

}
```

**Comment by Skn0tt** [comment]
Tests should be solo-runnable. Don't share state between multiple tests like this. If you'd like to break up your test into sections, use [`test.step`](https://playwright.dev/docs/api/class-test#test-step).

Besides, what you're experiencing is standard Javascript behaviour. `backup` fails because `createResources` throws an exception. So `createdProxy` never gets assigned.

**Comment by KAjayGoutham** [comment]
Thank you @Skn0tt , will work with test.step
