### ISSUE TITLE
[Bug]: Playwright inspector is pausing on a first call

### ISSUE THREAD

**Issue by vmachacek** [microsoft/playwright#33353]
### Version

latest

### Steps to reproduce

here https://github.com/microsoft/playwright/issues/19425

### Expected behavior

Playwright should not pause 

### Actual behavior

Playwright pauses for no good reason

### Environment

System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 10.53 GB / 63.88 GB
  Binaries:
    Node: 22.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.94.2 - C:\Users\vmach\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Windows\system32\bash.EXE

**Comment by Skn0tt** [comment]
The behaviour of `--debug` is to stop at the first API call, as mentioned in the linked issue. That's the intended behaviour.

`page.pause` is a different way to engage the inspector. You don't need `--debug` for that.

The recommended way to debug is the debugger in the VS Code Extension: https://playwright.dev/docs/getting-started-vscode#debugging-tests

**Comment by Skn0tt** [comment]
Could you elaborate on why you don't want to use `page.pause()`? It allows you to engage the debugger anywhere. Once you've paused, you can unpause immediately and step through the execution.

**Comment by vmachacek** [comment]
I want to 
 - start running any test (without a code change)
 - with open debugger (and keep running without interruption) 
 - when I hit breakpoint I can go inspect what's in the debugger 

In this scenario I keep clicking "play" button with every window being opened for any test - which is annoying and ineffective

**Comment by Skn0tt** [comment]
I understand. You talk about hitting a breakpoint - where are you setting the breakpoint? Is it in your IDE?

**Comment by vmachacek** [comment]
yes

**Comment by Skn0tt** [comment]
The command line, and by extension the Playwright CLI has no means of accessing the breakpoints in your IDE; so it's not possible to support this i'm afraid. We do in VS Code, because we have a special extension that integrates with the VS Code debugger. Some other IDEs like JetBrains Aqua might also support it, but that's not under Playwright's control

**Comment by vmachacek** [comment]
no it works, I hit a breakpoint (IDE), than click pause in the "Playwrigtht Inspector" and release the breakpoint in IDE. And now I have frozen page paused with a state I need.

**Comment by vmachacek** [comment]
@Skn0tt would it be possible to add switch which disables the first pause?

**Comment by Skn0tt** [comment]
`--debug` is that switch.

**Comment by vmachacek** [comment]
okay, please help me understand - for the test run I'm setting `PWDEBUG` env var which makes Playwright Inspector appear. Is there a way to make it appear and not to break on first occasion?

**Comment by Skn0tt** [comment]
Yes. Remove `PWDEBUG`, add a `await page.pause()` call to your test code, and then run tests with `--headed`. The inspector will appear when `page.pause()` is called.

**Comment by vmachacek** [comment]
That is not what I want. First off, I don't want to change my code everytime I want to run with inspector. And also what you are suggesting opens the Inspector paused. Which is whole point. I want to have Inspector open "just in case" (not pause when it appears) and if I get to the point where I'm interested into what is happening I pause manually in-flight.

**Comment by Skn0tt** [comment]
Sounds like you should open a feature request!

**Comment by mscuthbert** [comment]
I was super frustrated by this as well until Skn0tt's answer let me know that PWDEBUG and --headed are similar but different interfaces into the same system, and that --headed is what this and #33503 etc. are wanting.  I think that Playwright could make it easier to use headed mode with PWHEADED=1 or something since passing the headed attribute can be a pain in some testing systems (the way my Django setup was working, for instance).  So I think it's a clarifying user understanding and documentation issue rather than a feature issue (which can sometimes be even harder!)  Thanks @Skn0tt and others.
