### ISSUE TITLE
Is it possible to interact with vscode dropdowns?

### ISSUE THREAD

**Issue by roco1234** [microsoft/playwright#33361]
![Image](https://github.com/user-attachments/assets/87883394-edc8-4196-938c-db38ca735c2c)

Is it possible to interact with this dropdown with a playwright selector?

**Comment by Skn0tt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)

**Comment by Skn0tt** [comment]
Apart from that, it probably depends on how VS Code implements this. If it's a browser-standard element, then it should work. If it's some Electron-specific OS stuff, then it probably won't.

**Comment by Skn0tt** [comment]
Playwright is about automating browsers, not the operating system. So moving the mouse won't work.
