### ISSUE TITLE
[Feature]: Allow Devuan installs to fall back to Debian

### ISSUE THREAD

**Issue by asherwoodcnet** [microsoft/playwright#33432]
### 🚀 Feature Request

Hello! We'd like to be able to install playwright on Devuan machines by falling back to Debian installation. I submitted a PR which I believe will accomplish this: https://github.com/microsoft/playwright/pull/32990

### Motivation

Due to internal restrictions™, our github runners are only using Devuan, but we would like to use playwright tests as part of our automated pipeline checks. Currently, dependencies have to be installed manually because `npx playwright install` falls back to Ubuntu, but falling back to Debian would be more likely to succeed. I see that there are other fallbacks for OSes that are not officially supported, so it seems like this would not be interpreted as Playwright having responsibility if the Debian installation process does not give perfect results on Devuan machines.

**Comment by yury-s** [comment]
The PR you mentioned was reverted as we decided not to grow the list of special cases for the linux flavors that Playwright does not officially support. You can still install all the deps manually, but after the team discussion we concluded that we'd rather reduce the list and find a better solution that would allow to force install deps on an unsupported platform rather than adding new distros to the list.

**Comment by yury-s** [comment]
New environment variable `PLAYWRIGHT_HOST_PLATFORM_OVERRIDE` will allow to override platform detection logic. Supported values can be found here: https://github.com/microsoft/playwright/blob/36a975c30b12b39b81375800a34d5dbc3165cc52/packages/playwright-core/src/utils/hostPlatform.ts#L29-L34

**Comment by asherwoodcnet** [comment]
thanks for taking the time to explain, and thanks for the quick turnaround on a solution! 👏
