### ISSUE TITLE
[Bug]: can't inject custom function to window object with addInitScript

### ISSUE THREAD

**Issue by naayra** [microsoft/playwright#33486]
### Version

1.48.2

### Steps to reproduce

1. clone the repo (https://github.com/naayra/explore-playwright)
2. bun install
3. bun run test

### Expected behavior

How to proper inject a custom function to window object with playwright?

I expect it return 
```
{ baseUrl: 'https://example.com', enable: [Function] }
```
but, it return this instead
```
{ baseUrl: 'https://example.com', enable: undefined }
```

### Actual behavior

any idea why it return undefined?

```ts
await page.addInitScript(() => {
  window.hello = 'world';

  window.config = {
    baseUrl: 'https://example.com',
    enable: () => { // it will return undefined
      return true;
    },
  };
});
```

### Environment

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 7700X 8-Core Processor
    Memory: 27.61 GB / 31.21 GB
    Container: Yes
  Binaries:
    Node: 20.18.0 - ~/.volta/tools/image/node/20.18.0/bin/node
    npm: 10.8.2 - ~/.volta/tools/image/node/20.18.0/bin/npm
    pnpm: 9.12.3 - ~/.volta/bin/pnpm
    bun: 1.1.34 - ~/.bun/bin/bun
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2
```

**Comment by yury-s** [comment]
`const config = await page.evaluate(() => window.config);` returns config object serialized to json, since functions cannot be serialized they are placed with `undefined`. You can still call the method within eval as you do in the other test `  const enable = await page.evaluate(() => window.config.enable());`. You can pass arguments to the function as described in [this document](https://playwright.dev/docs/evaluating#evaluation-argument).
