### ISSUE TITLE
[Bug]: Blobs not being cleared

### ISSUE THREAD

**Issue by ss-221** [microsoft/playwright#33484]
### Version

1.48.2

### Steps to reproduce

1. Clone my repo at https://github.com/ss-221/pw-blobs-not-cleared
2. `npm install`
3. `npm run test`

The test first opens https://maps.google.com, and then opens `chrome://blob-internals` a minute later.

### Expected behavior

Thirty seconds after the page loads, there should be no more than 1 blob left.

### Actual behavior

On browsers launched using Playwright, there are multiple active blobs even after a full minute.

### Environment

  System:
    OS: macOS 15.0
    CPU: (12) arm64 Apple M3 Pro
    Memory: 171.61 MB / 18.00 GB
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2

**Comment by yury-s** [comment]
The blobs are collected at browser's discretion, the time varies between platforms and depends on multiple factors. Some flags that are used when launching the browser with playwright might affect the timing too. I'm going to close this report as there is no effect on the page under test and the blobs do get collected eventually. If you have an example where the blobs get stuck in memory and cause observable changes in the web app's behavior due to playwright, please share a minimal repro that includes code of the web app too (rather than loading a complex third-party page such as Google Maps).
