### ISSUE TITLE
[Bug]: Desktop chrome connection using wsl2 and vscode

### ISSUE THREAD

**Issue by rdurnin** [microsoft/playwright#33605]
### Version

1.48.1

### Steps to reproduce

Add the following to your configuration:

    {
      name: "chromeWsl",
      use: {
        channel: "chrome",
        launchOptions: {
          executablePath:
            "/mnt/c/Program Files/Google/Chrome/Application/chrome.exe",
          args: [
            "--headless=new",
            "--remote-debugging-port=9222",
          ],
          headless: false,
        },
      },
    },

Run the following command:

PWDEBUG=1 npx playwright test --project=chromeWsl

### Expected behavior

The chrome session should open on Windows and connect using the debug connect port.

### Actual behavior

The chrome session should open using debug port 9222, but instead fails due to debugging file descriptors not existing.

Using Show Browser (instead of headless: false) causes default chromium to open instead.
Using default chromium does not allow me to connect to web cam or other devices.

### Additional context

If there is an existing workflow which would allow me to launch chrome directly from vscode (wsl2) it would be preferred, 

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 28.48 GB / 31.31 GB
    Container: Yes
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
  IDEs:
    VSCode: 1.95.2 - /home/myUserName/.vscode-server/bin/e8653663e8840adaf45af01eab5c627a5af81807/bin/remote-cli/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.1
```

**Comment by pavelfeldman** [comment]
> The chrome session should open on Windows and connect using the debug connect port.

Your expectations are wrong, you can't run windows binaries inside wsl

**Comment by rdurnin** [comment]
Vscode (wsl2) launches desktop Chrome (Windows 11) and communicates with it over localhost using debug file descriptors. Is this possible with Playwright? I am not looking to manage the binary in wsl, but to communicate with it over a network interface.

**Comment by pavelfeldman** [comment]
You can run Playwright server on one host and connect to it from another, see https://github.com/microsoft/playwright/issues/26482 for the hints. They should mostly apply to your scenario. I don't see a BUG here though, so closing this.

**Comment by sebastian-altamirano** [comment]
Recently, I wanted to do the same thing and encountered this problem. I managed to solve it using `connectOverCDP`. I'll explain how I did it to save time for others who run into the same issue.

As context, I used WSL2 (I don't know if the procedure is the same in WSL1) and Windows 10 (in Windows 11, you can use mirrored mode networking, which simplifies things a bit). I use Playwright to generate PDF files and wanted my application to use the browser installed on Windows if it was running on WSL, but in the end, I didn't implement the functionality due to the complexity it would introduce in my code (everything I explain below).

`launch` and `connectOverCDP` return a `Browser` instance, so both can be used for the same purposes. The difference between them is that in `launch`, the browser's lifecycle is managed by Playwright, and in `connectOverCDP`, we have to manage it ourselves. Also, `connectOverCDP` [only works with Chromium-based browsers](https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp:~:text=Connecting%20over%20the%20Chrome%20DevTools%20Protocol%20is%20only%20supported%20for%20Chromium%2Dbased%20browsers.) (though those not supported by Playwright might present issues).

So, what we need to do is:

1. Start a browser on a specific port, usually 9222.
2. Connect to the browser with `const browser = playwright.chromium.connectOverCDP("http://localhost:9222")` and do what we need to do.
3. When finished, we need to kill the browser instance; [when using `connectOverCDP`, `browser.close()` only cleans up the context and disconnects from the instance](https://playwright.dev/docs/next/api/class-browser#browser-close:~:text=In%20case%20this%20browser%20is%20connected%20to%2C%20clears%20all%20created%20contexts%20belonging%20to%20this%20browser%20and%20disconnects%20from%20the%20browser%20server.), so we also need to do it manually. As mentioned before, when using `connectOverCDP`, we are responsible for managing the browser's lifecycle.

It seems simple, but first, we need to solve a series of prerequisites:

1. By default, WSL2 uses a NAT-based network architecture, which means the Linux and Windows networks are isolated. Due to this, we need to get the Windows IP address to communicate with the network applications running there. The Windows IP address can be obtained with `ip route show | grep -i default | awk '{ print $3}'`. The IP address may change when the computer is restarted. [In Windows 11, you can enable mirrored mode networking](https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking) to skip this step.
2. If we try to `ping` the Windows IP address we won't get a response, [this is because the firewall blocks it](https://github.com/microsoft/WSL/issues/4585). We need to create a firewall rule to allow traffic, which is done from an elevated PowerShell terminal with `New-NetFirewallRule -DisplayName "WSL" -Direction Inbound -InterfaceAlias "vEthernet (WSL)" -Action Allow` (below it is explained how to run PowerShell from WSL). The rule loses effect when the computer is restarted. If using mirrored mode networking, the command is different `Set-NetFirewallHyperVVMSetting -Name '{40E0AC32-46A5-438A-A0B2-2B479E8F2E90}' -DefaultInboundAction Allow`.
3. Now we should be able to `ping`, but still, we cannot call a Windows application from Linux (with `curl` for example). To do this, we need to forward the ports, which is done by executing the following in PowerShell `netsh interface portproxy add v4tov4 listenport=<port> listenaddress=<windows-ip> connectport=<port> connectaddress=127.0.0.1` (in our case the port would be 9222, or the one you choose to use).

Having solved this, I can explain how to start and kill Chrome (with other browsers, the steps are similar) from WSL2.

**To launch it**, it must be executed with the arguments `--headless --remote-debugging-port=9222` (or the port you choose), for example, we can start Chrome with `"/mnt/c/Program Files/Google/Chrome/Application/chrome.exe" --headless --remote-debugging-port=9222`. However, there are some things to keep in mind:

- The browser may be installed in a different location.
- Windows may be mounted in a different directory than `/mnt` ([the directory can be changed in the WSL configuration](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#automount-settings:~:text=/mnt/-,Sets%20the%20directory%20where%20fixed%20drives%20will%20be%20automatically%20mounted.,-By%20default%20this)).

To obtain the true location of the browser, you can use PowerShell: `"/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" -Command "(Get-ItemProperty 'HKLM:\Software\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe' -ErrorAction SilentlyContinue).'(default)'"`. This command will return a Windows path, for example, "C:\Program Files\Google\Chrome\Application\chrome.exe". You need to convert it to a Linux path, which can be done using `wslpath` (it is necessary to install [wslu](https://github.com/wslutilities/wslu)). Another way to execute PowerShell from WSL is with `powershell.exe`, [but for this to work, `appendWindowsPath` must not be `false` in the WSL configuration](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings:~:text=Setting%20this%20key%20will%20determine%20whether%20WSL%20will%20add%20Windows%20path%20elements%20to%20the%20%24PATH%20environment%20variable).

The PowerShell path will always be the same (it comes installed with the operating system), but it is different for 32-bit and 64-bit operating systems. What may change is the "/mnt" portion of the path, so it is advisable to use the previously mentioned `wslpath` command to obtain its path.

**To kill it**, the following must be executed in PowerShell `Get-CimInstance Win32_Process -Filter "CommandLine LIKE '%chrome.exe%--headless --remote-debugging-port=9222%'" | %{Stop-Process $_.ProcessId}` (to execute it from WSL, you can follow the instructions given when explaining how to start it).
