### ISSUE TITLE
[Bug]: Method .fill does not accept type number.

### ISSUE THREAD

**Issue by cuberinooo** [microsoft/playwright#33623]
### Version

1.48.2

### Steps to reproduce

This problem has already been addressed elsewhere but not resolved. It is only unclear to me why the .fill() method does not accept the type number.  
As you can see here: [Input Number](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) -> such an element should only accept numeric values.

Now to my specific problem:
We are using Vue with PrimeVue and PrimeVue provides the following component for InputFields with only numeric values: [InputNumber PrimeVue](https://primevue.org/inputnumber/)

The following leads to a problem: 
Assuming foo is the locator for the input field, then 
`foo.fill('123')` -> primeVue turns this into a `0`, as strings is not allowed here. 

foo.fill(123) will throw an error since it can only accept strings

Here are some issues that describe exactly the same thing:
https://github.com/microsoft/playwright/issues/16660
https://github.com/microsoft/playwright/issues/33200
https://github.com/microsoft/playwright/issues/28671

### Expected behavior

I expect that fill should also allow numeric values

### Actual behavior

fill() does not allow numeric values

### Environment

```shell
System:
    OS: Linux 6.8 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 10.34 GB / 31.09 GB
    Container: Yes
  Binaries:
    Node: 20.18.0 - /usr/bin/node
    npm: 10.9.0 - /projects/core/node_modules/.bin/npm
  Languages:
    Bash: 5.2.15 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.43.0 => 1.48.2 
    playwright-bdd: ^7.1.0 => 7.5.0
```

**Comment by mxschmitt** [comment]
The bug reports you were referring to were about accepting number as a type while the issue in your scenario is different. Custom elements or number elements which are pre-filled need to be cleared first, since they only listen on keydown/keypress events. The following would work for me:

```ts
it('should work', async ({ page, server }) => {
  await page.goto('https://primevue.org/inputnumber/');
  await page.getByLabel('Integer Only').focus();
  await page.keyboard.press('Meta+A');
  await page.keyboard.press('Backspace');
  await page.getByLabel('Integer Only').pressSequentially('987654321');
});
```

Similar to what a user would do. The alternative what a user would do is e.g. to click in it and press Backspace so often until all the values are gone.

---

I also found an issue that Inspector controls only showed up sometimes when opening Codegen, this will be fixed with https://github.com/microsoft/playwright/pull/33627.

When interacting with the page Codegen didn't work for me because they call `ev.preventDefault()` [here](https://github.com/primefaces/primevue/blob/180c921c894f0537767c33b0568754c773caa960/packages/primevue/src/inputnumber/InputNumber.vue#L540-L542) and then no `'input'` event gets dispatched. Playwright Codegen only listens for the `'input'` event. This might be something we could fix on our side.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue by filling in the "Bug Report" template and link to this one.

**Comment by cuberinooo** [comment]
@mxschmitt I was on the wrong track. Many thanks for pointing this out. I did not realize that the custom element does not listen on the input event.
