### ISSUE TITLE
[Bug]: browsers Issue

### ISSUE THREAD

**Issue by gowththota-sfa** [microsoft/playwright#33677]
### Version

1.48.2

### Steps to reproduce

I am using default microsoft edge browser and its the only one we can use as per our policy.Cant download the browsers.
I have installed playwright and configured it as per the playwright website removed all the browsers and kept the and ran the sample tests .
 {
      name: 'Microsoft Edge',
     use: { ...devices['Desktop Edge'], channel: 'msedge' },
    
   },

### Expected behavior

It worked fine with the example specs.
It should trigger my tests as well

### Actual behavior

I have created simple pageobject model framework and tried to run the tests but getting issue with browsers 

Error: browserContext.newPage: Executable doesn't exist at     path\AppData\Local\ms-playwright\ffmpeg-1010\ffmpeg-win64.exe                                      
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝

how can i resolve this issue inorder to use the default browser Microsoft edge in my system.

### Environment

```shell
Windows11
```

**Comment by dgozman** [comment]
@gowththota-sfa Thank you for the issue. A few questions:
- Did you run `npx playwright install`? This was not clear from the description?
- Did you run `npx playwright install msedge`? This should auto-detect your existing Microsoft Edge installation, but also install `ffmpeg` required for the video recording to work.
- Have you considered turning off video recording in your `playwright.config.ts`? That's the only feature that needs `ffmpeg`. If you cannot run any non-approved binaries, perhaps this would be the best solution.

**Comment by dgozman** [comment]
@gowththota-sfa Did you have any chance to try the suggestions above?

**Comment by jfoo1984** [comment]
I'm seeing a very similar issue [in a github action](https://github.com/chanzuckerberg/czid-web/blob/main/.github/workflows/e2e-automation.yml) that has been running fine for months.  (We perform the CI/CD runs in a private version of that repo, but the code it copied there).  Our GHA isn't configured to run `npx playwright install`, so has something changed in a dependency recently where that is now required?

**Comment by jfoo1984** [comment]
Even after adding that command in our CI and bumping our playwright version, I still see the error.  I also added changed the command to `npx playwright install --with-deps`.  We had `playwright-chromium` as a dependency in our package.json, so I tried removing that and allowing the `playwright install` step to take care of it.  I do see ffmpeg being explicitly installed by that step in CI now:

     ```
    Downloading FFMPEG playwright build v1010 from https://playwright.azureedge.net/builds/ffmpeg/1010/ffmpeg-linux.zip
    ...
    FFMPEG playwright build v1010 downloaded to /home/runner/.cache/ms-playwright/ffmpeg-1010
    ``` 

Still get the error on tests: `Error: browserContext.newPage: Executable doesn't exist at /Volumes/Sauce/saucectl-runners/sauce-playwright-runner/2.34.0/bundle/Cache/ffmpeg_mac12_special-1010/ffmpeg-mac`

The path from `playwright install` is different, not sure if that is significant.  In our GHA, we are installing `@playwright/test` globally, so that is an issue I'll investigate.

**Comment by mxschmitt** [comment]
I'll close it for now since the original issue has been answered.


re @jfoo1984

It looks like that the saucelabs package you are using is overriding the Playwright browser paths via `PLAYWRIGHT_BROWSERS_PATH` see [here](https://github.com/saucelabs/sauce-playwright-runner/blob/c4ccaa528ae48ff778563bd36beb17a38b861f34/scripts/bundle.sh#L2).

I recommend reaching out to them - this is unfortunately not something where we can help much.e
