### ISSUE TITLE
[Feature]: Add lint/typescript rule for `PageFunction` strict execution scope

### ISSUE THREAD

**Issue by ShaMan123** [microsoft/playwright#33752]
### 🚀 Feature Request

Add a lint/typescript rule to force `PageFunction` strict execution scope (`window` only) warning when using args that are out of scope.

I think it can be done in both lint/typescript. I am willing to look into it if this will be accepted.

### Example

```typescript

const authStorageKey = 'auth'
const accessToken = {}

// good
await this.page.evaluate(
      ([key, value]) => window.localStorage.setItem(key, value),
      [authStorageKey, JSON.stringify(accessToken)]
);

// bad - print error: `authStorageKey` and `accessToken` are out of scope, please pass them down to the page function.
await this.page.evaluate(() => window.localStorage.setItem(
       authStorageKey,
       JSON.stringify(accessToken)
));


```

### Motivation

I am using playwright extensively the last 2-3 months, and in general for >2 years. 
It is a fantastic tool, thank you all for the great work.

I find myself falling into the `PageFunction` pitfall (using non-scoped args) repeatedly due to negligence/I have enough on my mind, it is too detailed to remember this.
If there would be an error showing when a `PageFunction` has dependencies (unscoped args) that would be great OR if the build step could wrap the `PageFunction` and determine which args it needs by itself that would also be good, but might be too involved to maintain.

For new adopters this will reduce a lot of friction IMO.

**Comment by mxschmitt** [comment]
Sounds like a feature request to https://github.com/playwright-community/eslint-plugin-playwright - Playwright does not perform any linting as of today.

It seems like a hard problem to solve - since sometimes you intentionally rely on global functions or variables.

I'll close it per above since it would be great to solve but hard to implement / we don't see us doing it inside the Playwright project.
