### ISSUE TITLE
[Bug]: Clock API prevents running intervals from being cleared

### ISSUE THREAD

**Issue by atsikov** [microsoft/playwright#33837]
### Version

1.49.0

### Steps to reproduce

General case: 
1. Call `setInterval` in the page
2. Use `context.clock.install()` or `context.clock.runFor()`
3. Call `clearInterval` in the page
4. Interval continues to tick

You could clone https://github.com/atsikov/playwright-runFor-clearInterval to have a repro case
1. Clone the repo
2. `yarn`
3. `yarn test` or `yarn test:ui`
4. See two tests where `context.clock` is used failing

### Expected behavior

`clearInterval` works as usual and stops currently running interval even after Clock API is used

### Actual behavior

Clock API prevents running intervals from being cleared in at least two scenarios
1. Fake timers are installed, even if then runFor is not called
2. Fake timers are used with runFor without being previously installed

### Environment

```shell
System:
    OS: macOS 14.7.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 65.58 MB / 16.00 GB
  Binaries:
    Node: 22.10.0 - ~/.nvm/versions/node/v22.10.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.10.0/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.10.0/bin/npm
  IDEs:
    VSCode: 1.95.3 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.49.0 => 1.49.0
```

**Comment by Skn0tt** [comment]
Hello Aleksei! When you call `clock.install`, behind the scenes Playwright will install a mocked version of methods like `setInterval` and `clearInterval` . So when you call `clearInterval`, it operates on the mocked one, while you `setInterval` on the real one. The fix is to move up `clock.install` to the start of your test. Sounds like we should mention that in docs!

**Comment by atsikov** [comment]
Hi @Skn0tt, thanks a lot for your reply

Generally, what you are saying makes perfect sense, and you are right that fake timers should be installed first thing before the page is loaded, although it might be tricky depending on the specific setup.

However, an impact of `clock.install` is not the main issue and was found later while I was playing around with the repro case. The biggest problem is that `clock.runFor` also affects existing intervals even if fake timers were not installed in advance. I would expect all Clock API calls to be a noop in case real timers are in use.

Also, replacing an interval with a self-rescheduling timeout in the repro case works as expected: all tests pass and a timeout is cleared even if I install fake timers when it is already scheduled. Such different behaviour in seemingly very similar scenarios is frustrating.

**Comment by Skn0tt** [comment]
> Also, replacing an interval with a self-rescheduling timeout in the repro case works as expected

That's probably because the self-rescheduling timeout will start using the real clock, and then the mocked clock after it's installed.

Calling `runFor` without calling `install` prior to that is not supported, and won't give you defined behaviour. Make sure to call `clock.install` first thing in your test, as we showcase in the docs. It's not super obvious from the current docs, so maybe we can change that.

**Comment by atsikov** [comment]
> > Also, replacing an interval with a self-rescheduling timeout in the repro case works as expected

> That's probably because the self-rescheduling timeout will start using the real clock, and then the mocked clock after it's installed.

The scenario is the same as with intervals: `setTimeout` is scheduled with real clock, then `context.clock.install()` is called, then `clearTimeout` is called. I could add this test to the repro case if you want.

> Calling runFor without calling install prior to that is not supported, and won't give you defined behaviour

Could you please clarify what you mean with "defined behaviour" here? My expectation is that `clock.runFor` does exactly nothing if called without a prior installation, however apparently it does some timers patching.

**Comment by Skn0tt** [comment]
> Could you please clarify what you mean with "defined behaviour" here?

"Defined behaviour" is what happens if you use Playwright APIs as they are intended to be used. In this case, you are required to call `.install` before calling `.runFor`. Any other usage is not supported. And if you still use it that way, you get "undefined behaviour".

Quoting from our [docs on Clock](https://playwright.dev/docs/clock): "`install` initializes the clock and allows you to: [...] `runFor`: Run the time for a specific duration.".
