### ISSUE TITLE
[Question] Does playwright support browser network emulation?

### ISSUE THREAD

**Issue by devalevenkatesh** [microsoft/playwright#3393]
I guess Puppeteer supports network emulation / throttling. I am looking for something similar using Playwright. I checked the API reference but did not found anything in Network section. Thanks for such a great library.

**Comment by aslushnikov** [comment]
@devalevenkatesh Puppeteer's network throttling is done using Chrome DevTool Protocol; you can do the same with chromium in Playwright using [`context.newCDPSession()`](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=chromiumbrowsercontextnewcdpsessionpage):

```js
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  const cdp = await context.newCDPSession(page);
  // Set throttling property
  await cdp.send('Network.emulateNetworkConditions', {
    'offline': false,
    'downloadThroughput': 200 * 1024 / 8,
    'uploadThroughput': 200 * 1024 / 8,
    'latency': 20
  });
  // Go on with the throttled page...
  await page.goto('https://example.com');
})();
```

This method, however, has a few downsides:
- will not work in other browsers in Playwright since there's no CDP
- does not work ideally in Chromium either since webrtc and websockets are not throttled

To throttle "for real", we'd recommend user-land solutions:
- [Charles Proxy](https://www.charlesproxy.com/) is quite popular and works across OS'es.
- On Linux, network shaping could be configured per network interface with tools like [`tc`](https://en.wikipedia.org/wiki/Tc_(Linux)). [wondershaper](https://github.com/magnific0/wondershaper) is a convenience wrapper atop of `tc` and might be a good starting point.
- On Mac, there's [Network Link Conditioner](https://nshipster.com/network-link-conditioner/). 

Hope this helps!
