### ISSUE TITLE
I want to automate green screen (window base application ) can I use playwright with Winium?

### ISSUE THREAD

**Issue by Abhijit1919** [microsoft/playwright#34064]
### Please do not submit this issue.

- [x] I understand

**Comment by mxschmitt** [comment]
Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)
