### ISSUE TITLE
[Bug]: Debug on Firefox doesn't work without Chromium installed

### ISSUE THREAD

**Issue by 5-tom** [microsoft/playwright#34131]
### Version

1.49.1

### Steps to reproduce

1. Clone [https://github.com/5-tom/playwright-bug-repro](https://github.com/5-tom/playwright-bug-repro)
2. Run (important: do not have chromium installed):
```
npm i -D @playwright/test
npx playwright install firefox
npx playwright test --project=firefox --debug
```

### Expected behavior

Debug on Firefox should work without Chromium installed.

### Actual behavior

```
Running 1 test using 1 worker

  ✘  1 [firefox] › example.spec.ts:3:5 › has title (21ms)
Testing stopped early after 1 maximum allowed failures.


  1) [firefox] › example.spec.ts:3:5 › has title ──────────────────────────────────────

    Error: browser.newContext:
    ╔═══════════════════════════════════════════════════╗
    ║ No chromium-based browser found on the system.    ║
    ║ Please run the following command to download one: ║
    ║                                                   ║
    ║     npx playwright install chromium               ║
    ║                                                   ║
    ║ <3 Playwright Team                                ║
    ╚═══════════════════════════════════════════════════╝

  1 failed
    [firefox] › example.spec.ts:3:5 › has title ───────────────────────────────────────
  1 error was not a part of any test, see above for details
```

### Environment

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 9.54 GB / 15.35 GB
    Container: Yes
  Binaries:
    Node: 23.0.0 - ~/.config/nvm/versions/node/v23.0.0/bin/node
    npm: 10.9.0 - ~/.config/nvm/versions/node/v23.0.0/bin/npm
  Languages:
    Bash: 5.2.15 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.49.1 => 1.49.1
```

**Comment by Skn0tt** [comment]
Hi Tom! You're passing `--debug`, which opens up the [Playwright Inspector](https://playwright.dev/docs/running-tests#debug-tests-with-the-playwright-inspector). We [always use chromium for that](https://github.com/microsoft/playwright/blob/1c8e6f0921b1cc517afb5f8549609f356e81cf85/packages/playwright-core/src/server/recorder/recorderApp.ts#L106), so that's where the error message comes from. You can fix it by either installing standard chrome or edge on your machine, or by running `npx playwright install chromium`. If you don't pass `--debug`, it won't show the error message.
