### ISSUE TITLE
[Question] How to manually download file (donwload dialog) ?

### ISSUE THREAD

**Issue by ruslanx3m** [microsoft/playwright#3498]
![scrn](https://user-images.githubusercontent.com/24808164/90532956-62947900-e167-11ea-8964-1cc0abb68701.jpg)
```
const { chromium } = require("playwright");
const path = require("path");


(async () => {

    const browser = await chromium.launch({
        headless: false,
        // downloadsPath: path.join(__dirname, 'downloads')
    });

    const context = await browser.newContext({
        acceptDownloads: true,
    });

    const page = await context.newPage();

    await page.goto('https://file-examples.com/index.php/sample-documents-download/sample-xls-download/');

    // how to manually download file by User click ????




    // // Automatic Download
    // const handles = await page.$$("#table-files td.text-right.file-link");

    // for (let num of handles) {

    //     const [download] = await Promise.all([
    //         page.waitForEvent('download'),
    //         num.click("a.btn")
    //     ]);

    //     await download.saveAs(path.join(__dirname, 'downloads', download.suggestedFilename()));
    // }

    // await browser.close();
})();
```

**How to manually download file (donwload dialog) ?**

**Comment by mxschmitt** [comment]
What is a manual download for you?

**Comment by ruslanx3m** [comment]
..when user click on download link, to show download dialog for saving file ..

**Comment by pavelfeldman** [comment]
Not sure I follow though, please provide more details. The commented out code "Automatic Download" is exactly how Playwright is supposed to be used!

**Comment by ruslanx3m** [comment]
I know, but ... look at screenshot, I want as in regular browser 'download files dialog box' to appear .. when clicking on download link

**Comment by dgozman** [comment]
Playwright is an automation library, tailored for the scripts executing without human interactions. Interoperability with actions manually done by humans is not among Playwright goals. However, if there is a compelling enough usecase, we might try to help in a particular scenario.

**Comment by tim-munn** [comment]
I am experiencing the identical issue.
My use case is I need to download a pdf file to be able to query the contents.
In a similar way as ruslanx3m needed to use an xls file
Some download options (such as save a pdf), when you open a pdf in a browser (Chrome), launch a native file dialog that needs accepting before the download can progress, rather than using the in browser download option, because the download hasn't technically started at that point and an event hasn't been created a 'download' object can't be created, but one is needed to set the path for the download.

In my case I was able to awkwardly work round, by determining the URL of the file I needed to download and separately doing a fetch to that url and saving the Buffer from the response to a file.
However it would have been much easier to be able to use a the 'Download' functionality.

**Comment by Ciantic** [comment]
> @tim-munn In my case I was able to awkwardly work round, by determining the URL of the file I needed to download and separately doing a fetch to that url and saving the Buffer from the response to a file.

How you saved it to the file? Since the fetch is called inside the page process it doesn't save to file by default.

I tried to return the buffer through the `page.evaluate()` call, but I'm noticing that with *big* files playwright just crashes with: "Protocol error (Runtime.callFunction): Target closed.Error:". It works fine with smaller files.

**Comment by tim-munn** [comment]
@Ciantic I used axios (https://www.npmjs.com/package/axios) to perform the request as it writes out to a stream I could buffer into a file

const DownloadFileFromURL = async (url,path) => {
    const writer = Fs.createWriteStream(path)
    const response = await axios({
        url,
        method: 'GET',
        responseType: 'stream'
      })

    response.data.pipe(writer)

    return new Promise((resolve, reject) => {
      writer.on('finish', resolve)
      writer.on('error', reject)
    })
}

**Comment by paulohenrique001** [comment]
Solução do problema
---------------------------------
const { chromium } = require('playwright');
const shell = require('node-powershell');
const fs = require('fs');

//console
var powershell = new Shell({
    executionPolicy: 'Bypass',
    noProfile: true
});

// Autamatização inicio
const browser2 = await chromium.launch({
    headless: false,
    downloadsPath: './downloads'
});

// Solução para download
const [download] = await Promise.all([
    await page.waitForEvent('download')
]);

const path = await download.path();

fs.rename(path, '${path}.xml', function(err) {
    if (err) console.log('ERROR: ' + err);
});

await powershell.addCommand("Unblock-File -Path .\\downloads\\*");
await powershell.invoke();

Sobre o erro
-------------------------------------------------
Acredito que o erro acontece por conta dos arquivos baixados pelo Playwright vem com a propriedade de outro computador, bloqueando assim algumas coisas, para burla isso, renomeei os arquivos e depôs usei uma biblioteca que me permite usar comando powershell direto pelo script e então executei o 'Unblock-File -Path' na pasta do meus arquivos para desbloquear os arquivos baixados.


Aqui está alguns links uteis:
[fs](https://nodejs.org/api/fs.html)
[Unblock-File Doc](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file?view=powershell-7.1)
