### ISSUE TITLE
[BUG] Playwright does not see iframe element as visible

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#3499]
**Context:**
- Playwright Version: 1.3.0
- Operating System: Mac
- Node.js version: v12.16.3
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: false });

  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto(
    "https://5d559397bae39100201eedc1-cmvxjddyww.chromatic.com/?path=/story/all-components-form--all-examples"
  );
  const frame = await (
    await page.$("#storybook-preview-iframe")
  ).contentFrame();
  await frame.click("input");
})();
```

I checked the input has height and width of 1 and is visible. 

```
// inside iframe
const element = document.querySelectorAll('input')[0];
const isVisible = element.getBoundingClientRect().width > 0 && element.getBoundingClientRect().height > 0 && window.getComputedStyle(element).visibility === 'visible';
console.log(isVisible); // true
```

**Describe the bug**

The element never seems to be visible.

```
    [api] retrying click action
    [api]   waiting for element to be visible, enabled and not moving
    [api]   element is visible, enabled and does not move
    [api]   scrolling into view if needed
    [api]   done scrolling
    [api]   element is outside of the viewport
    [api] retrying click action
    [api]   waiting for element to be visible, enabled and not moving
```

**Comment by dgozman** [comment]
I can repro this. There are two issues.
1. We only click elements of the size "more than one". I think we can do "more than or equal to one" instead. I tried that locally, and it revealed another problem.
2. That input has `clip: rect(1px, 1px, 1px, 1px) !important;`, and that somehow makes it non-targetable by pointer events. Instead, all the pointer events go to the parent `span` element. Removing this style manually helps. Using `{force: true}` option to click at the target point instead of the target element also helps.

**Comment by jperl** [comment]
Thank you for investigating this and for explaining why it was not clickable. 🙏

**Comment by dgozman** [comment]
This is fixed now.
