### ISSUE TITLE
[Feature] Allow set proxy per context

### ISSUE THREAD

**Issue by dilame** [microsoft/playwright#3534]
I am requesting the feature - allow set proxy per context.
It is a useful feature to test how does the site reflect users from different countries. Sometimes it is legally important to restrict the access from certain countries, sometimes just check if currency was determined right. A lot of different use cases, it is very necessary function. Why have context if you can not set a proxy for this?

**Comment by Mreddi1** [comment]
Hello. Please tell me if this feature is planned to be implemented in the future?

**Comment by mjgp2** [comment]
I can see how to implement for Firefox. Can anyone from the team let me know what the policy is if only one browser supports a function? Thanks!

**Comment by creage** [comment]
Hey @aslushnikov, could you guys please clarify the behavior of current `proxy` setting in the `launch` options? Because we had an impression that every browser we launch with different proxy setting should stick to it, but it appears that the last proxy wins, overwriting settings of previously launched instances.

This behavior makes it impossible to test multi-user scenarios that depend on proxies (like NTLM proxies).

We definitely need per-context proxies!

**Comment by 0x0480** [comment]
proxy per page also'd be awesome!
