### ISSUE TITLE
[Question] Why beta versions of browsers are used instead of stable?

### ISSUE THREAD

**Issue by niyarlatotep** [microsoft/playwright#4028]
Why beta versions of browsers are used instead of stable? I'd prefer to test my app against stable versions.

**Comment by pavelfeldman** [comment]
Being on the front line is the only way for customers to find out that their site will break once beta becomes stable. Browser vendors won't ask you before they promote and roll their browsers to all of your customers. Or is there some other aspect you were concerned with?

**Comment by niyarlatotep** [comment]
Yes I see, it's because of automatic browsers updating but in this case I have to test my app against beta version so I can't be sure if it's bug of beta browser or my app I understand that stable version doesn't garantee it eather but there is more confidence in stable version. Second argument is that companies can use internal enterprise versions which as i understand likely are stable versions and for example I want to tetst my app with current release versions while beta version will be applyed bit later. I understand that beta version is quite stable and if there are defects it's likely a problem in the testing application but shouldn't we consider these cases? The way out for now is to use older versions of playwright am I right? May be it was good to have at least stable versions for docker containers but as I understand playwright comes with specific versions of browsers don't know if it's possible.

**Comment by pavelfeldman** [comment]
Going after pre-release versions was a deliberate decision on our side. You can be on the front line or you can use older versions of Playwright if you specifically target certain browser version. Since Playwright updates are only happening in the managed environment, users know immediately if the test failed as a result of the roll. We believe this gives users enough flexibility and transparency into the process.
