### ISSUE TITLE
[BUG] $eval & $$eval return native DOM elements instead of ElementHandle

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright#4094]
**Context:**
- Playwright Version: 1.4.2
- Operating System: Windows
- Node.js version: v12.18.3
- Browser: Chromium

**Code Snippet**
```javascript
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();

  const array = await page.$$eval('some-selector', elements => elements.find(element => element.id = "some-id"));
  const single = await page.$eval('some-selector', element => {
    element.id = "some-id";
    return element;
  });
})();
```

**Describe the bug**

I think the type of `array` & `single` should be `ElementHandle<SVGElement | HTMLElement>`
![image](https://user-images.githubusercontent.com/9786571/95505111-7e253e80-09b6-11eb-83d6-7f0207305f63.png)
![image](https://user-images.githubusercontent.com/9786571/95505120-82515c00-09b6-11eb-99ab-6d9b780f2b19.png)

**Comment by pavelfeldman** [comment]
This works as designed. When you return an object from the browser, we don't know if you want to return it as a serialized object because it is a simple JSON struct, or you want to return a handle to a remote object that you will call methods on. So you need to tell us which form you'd like. Similarly to `evaluate`, `$eval` and `$$eval` return serializable values. `evaluateHandle` is the only one that returns the handles.
