### ISSUE TITLE
[Feature] pass arguments like proxy to each context not to whole browser

### ISSUE THREAD

**Issue by Shinoby92** [microsoft/playwright#4321]
Like the title say's
creating one browser and one context results that only the browser can get a proxy value, so testing different proxys needs to create multiple browsers. Better it would be that these arguments can get passed to the context , so adding each proxy to the context having 1 browser with multiple contexts each of them their own proxy ( I guess there are more arguments that would be benefit generally to having the arguments passed to the context if wished)

**Comment by mxschmitt** [comment]
Hi, there was already an issue for it #3534 which got implemented in the tip-of-tree (master) version. You can try it out directly and don't have to wait for a release if you want. Otherwise it gets released in the upcoming weeks.
- NPM package: `npm install playwright@next`
- docs: https://playwright.dev/#version=master&path=docs%2Fapi.md&q=browsernewcontextoptions--options-proxy

**Comment by Shinoby92** [comment]
thanks I just found it now in the master tree, but im using playwright python and I can't install the master tree with pip because I get the failure that the package misses /site-packages/playwright/driver/playwright-cli

so I guess I have to wait for the next version push and release that I can install it normally via pip install  for python right :x?

**Comment by Nisthar** [comment]
@mxschmitt i am getting error ```npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND```
when using `npm install playwright@next`

**Comment by yifeikong** [comment]
Is this feature available in python? I still got errors like:

```
playwright._impl._api_types.Error: Browser needs to be launched with the global proxy.
```

**Comment by mxschmitt** [comment]
Yes, which Playwright Python version are you using?
