### ISSUE TITLE
[Feature] Fake video capture

### ISSUE THREAD

**Issue by jruizaranguren** [microsoft/playwright#4532]
I have reviewed the documentation, but i have not found an answer to this. Is it possible in `playwright` to configure a fake video capture?

Something like `--use-file-for-fake-video-capture` option for chrome. This is a nice to have popular request, for instance, in [alike frameworks](https://github.com/cypress-io/cypress/issues/2704) such as cypress.

**Comment by pavelfeldman** [comment]
You can pass chrome launch arguments to achieve it, but there is no support for it on non-Chromium browsers.

**Comment by viraxslot** [comment]
Hi, you should check [this page](https://webrtc.org/getting-started/testing).
Fake webcam video in Firefox also works just fine, but there's no option to use your video file afaik.

**Comment by dgozman** [comment]
Leaving as a feature request. For now, please use available workarounds for Chromium and Firefox. Thanks @viraxslot!

**Comment by jruizaranguren** [comment]
> You can pass chrome [launch arguments](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-args) to achieve it, but there is no support for it on non-Chromium browsers.

This worked like a charm:

```
args=["--use-fake-device-for-media-stream",
        "--use-file-for-fake-video-capture=/path/to/video.y4m"]
```

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by acanyasar** [comment]
@eleveShi do you know does it only support .y4m files? Here is my playwright.config.js setup for chromium however I can not simulate webcams on google chrome. 

```javascript
 name: "chromium",
      use: {
        ...devices["Desktop Chrome"],

        video: 'on',
        trace : 'retain-on-failure',
        screenshot: 'on',


        launchOptions: {
          args: [
            "--use-fake-ui-for-media-stream",
            "--use-fake-device-for-media-stream",
            "--use-file-for-fake-video-capture=/sample_files/samplevideo.mp4",
            '--use-fake-device-for-media-stream',
            '--no-sandbox'
          ],
        },
        permissions: ["camera", "microphone", "accessibility-events"]
      },
```

**Comment by alramalho** [comment]
I have tested out every stated solution here, it is not working.
I'm on macOS. 

Is there an update on this?

**Comment by mirao** [comment]
> Fake webcam video in Firefox also works just fine, but there's no option to use your video file afaik.

Yes, it's a pity that Firefox doesn't allow to stream a custom video file (in simplest way an image) by a fake camera, the same way as Chrome. A solution using `v4l2loopback` and FFmpeg exists, but it's not so straightforward.

**Comment by addame2** [comment]
anyone fixed issue? without detection when use file path ? it have to be coming from real cam thanks

**Comment by Murderlon** [comment]
One more update, the absolute most consistently working solution is using `launchPersistentContext`:

```ts
import { chromium } from '@playwright/test'

// ...
const context = await chromium.launchPersistentContext('/tmp/playwright', {
  permissions: ['camera', 'microphone'],
  args: [
    '--disable-web-security',
    '--auto-accept-camera-and-microphone-capture',
    '--use-fake-device-for-media-stream',
    `--use-file-for-fake-video-capture=${__dirname}/fake-webcam-video.y4m`,
  ],
})
const page = await context.newPage()
await page.goto('http://localhost:5173')
```

`y4m` files are super heavy, to create a minimal one:

```
ffmpeg -f lavfi -i color=c=black:s=1x1:d=1 -pix_fmt yuv420p -f yuv4mpegpipe fake-webcam-video.y4m
```

**Comment by MauroBW** [comment]
Hi @Murderlon, thanks for posting this solution.

I'm trying to adapt it but am running into an issue when I move from my local machine to a Docker container.

- Local: Works perfectly. I can use both a .y4m and a .wav file using the --use-file-for-fake-video-capture and --use-file-for-fake-audio-capture flags. 
Using MacOS Sequoia 15.6.1

- Docker: Fails. The fake media does not seem to be loaded by Chromium inside the container. The MediaSessionHandler throws: `MediaSessionsHandler.setVideoDevice NotFoundError: Requested device not found`
Using: mcr.microsoft.com/playwright:v1.54.2-jammy

I have two main questions:

Config vs. Context Fixture: Instead of using launchPersistentContext in the test file, I'm trying to set these flags globally in my playwright.config.ts under `use: { launchOptions: { args: [...] } }`. Is this a valid approach, or is launchPersistentContext mandatory for these flags to work?

Docker Paths: Your example uses a relative path with ${__dirname}. Inside my Docker container, I'm copying the media files to a location (e.g., /app/media/) and using the absolute path in the flag (e.g., --use-file-for-fake-video-capture=/app/media/fake-video.y4m).

Have you encountered this Docker issue before? I'm struggling to figure out if my problem is with the config, the file paths, or some kind of permissions/codecs/dependencies issues inside the container.

Any advice would be greatly appreciated!
cc: @pavelfeldman
