### ISSUE TITLE
[Question] page.click() and CSS extension: visible - documentation confusion

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#4849]
https://github.com/microsoft/playwright/blob/v1.7.0/docs/selectors.md#css-extension-visible says:

> The :visible pseudo-class matches elements that are visible as defined in the actionability guide. For example, input matches all the inputs on the page, while input:visible matches only visible inputs. This is useful to distinguish elements that are very similar but differ in visibility.

I tried to grok this, but couldn't. What confuses me is that https://github.com/microsoft/playwright/blob/v1.7.0/docs/actionability.md#visible states that `page.click()` does the [Visible](https://github.com/microsoft/playwright/blob/v1.7.0/docs/actionability.md#visible) actionability check.

Then how can these differ, since the first already checks for Visible?

```js
// Clicks the first button.
await page.click('button');
// Clicks the first visible button. If there are some invisible buttons, this click will just ignore them.
await page.click('button:visible');
```

**Comment by dgozman** [comment]
Consider a page with two buttons, first invisible and second visible.
```html
<button style='display: none'>Invisible</button>
<button>Visible</button>
```

- ```js
   await page.click('button');
   ```
   This will find the first button, because it is the first one in DOM order. Then it will wait for the button to become visible before clicking, or timeout while waiting.

- ```js
   await page.click('button:visible');
   ```
   This will find a second button, because it is visible, and then click it.

We recommend to use `aria-label`, `data-test-id` or text value to make sure that you target the correct button. However, if you cannot do that for some reason, using `:visible` might help target the second button. That said, on the modern sites/apps that animate many transitions, you cannot be sure whether some element is already visible or not, and using `:visible` may be flaky - a more precise selector would work much better.

Does this answer your question?

**Comment by thernstig** [comment]
Thanks, it does. I had _no_ idea it worked like this. I would have intuitively thought `await page.click('button');` would have been clicked via the Visible actionability, considering the first element is not visible. It would have made the most sense to me. But now I know. I am fine with closing this if you want.

**Comment by dgozman** [comment]
I've added more details to `:visible` docs in #4939. Thank you for the question!
