### ISSUE TITLE
[Question] - FFMPEG license

### ISSUE THREAD

**Issue by karanmarjara** [microsoft/playwright#4895]
"We noticed that your build script (to check) and executables appear to for the LGPL-2.1 version of ffmpeg. Is there a reason you put a GPL-3.0 license file in there <https://github.com/microsoft/playwright/blob/master/third_party/ffmpeg/COPYING.GPLv3>?"

**Comment by JoelEinbinder** [comment]
@aslushnikov

**Comment by yury-s** [comment]
According to https://ffmpeg.org/doxygen/3.4/md_LICENSE.html "Most files in FFmpeg are under LGPL v2.1+". Does v3 cause you any issues that could be addressed by using v2.1?

**Comment by mxschmitt** [comment]
From my understanding since you can have a LGPL and GPL version of ffmpeg in our case the wrong license was put into the repo. If you execute the Playwright ffmpeg with `ffmpeg -L` you see, that its a `Lesser General Public License` -> LGPL

So the action item out of that is that the `COPYING.LGPLv2.1` file should be copied, see here for [ref](https://video.stackexchange.com/questions/14802/can-i-use-ffmpeg-in-a-commercial-product) instead of `COPYING.GPLv3`.

**Comment by yury-s** [comment]
Oh, I thought the question was about the version 2.1 vs 3, it should be LGPL not GPL as Max pointed out. I'll fix that.

**Comment by karanmarjara** [comment]
Thank you for looking into this and resolving the issue. Appreciate your help.
