### ISSUE TITLE
[Question] Ability to disconnect from browser server without closing contexts

### ISSUE THREAD

**Issue by calebeby** [microsoft/playwright#4956]
Hi, is it possible to disconnect from a browser server while keeping open the browser contexts that were opened?

In puppeteer, the [`browser.disconnect`](https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-browserdisconnect) method does this. It looks like playwright doesn't have a `disconnect` method, just a `close` that disconnects _and_ closes the browser contexts

**Comment by calebeby** [comment]
Also [this issue](https://github.com/microsoft/playwright/issues/2775) has a similar title but AFAICT is unrelated (I could be wrong)

**Comment by JoelEinbinder** [comment]
Unlike puppeteer, the browser server controls the websocket server in playwright. So you should instead leave the browser server open and "disconnect" from the node process in which it is running.

**Comment by calebeby** [comment]
When I disconnect from the browser server (which is running in a separate process), the contexts that I opened are closed. Is there a way for me to disconnect from the browser server while keeping the contexts open?

**Comment by calebeby** [comment]
I made a repo that is hopefully helpful: https://github.com/calebeby/playwright-test

1. `node browser-server.js` - leave this running in a separate terminal
2. `node index.js` - This will connect to the browser server in the other process and create a new context and a new tab. I'd like this process to be able to end while leaving the tab/context that it created open. In puppeteer browser.disconnect does this, but playwright only has browser.close:
   > In case this browser is obtained using `browserType.connect(params)`, clears all created contexts belonging to this browser and disconnects from the browser server.
   I want something like this but that does not clear the created contexts

**Comment by yury-s** [comment]
> When I disconnect from the browser server (which is running in a separate process), the contexts that I opened are closed. Is there a way for me to disconnect from the browser server while keeping the contexts open?

No, the contexts are 'owned' by the connected client. When the client disconnects its contexts will be closed automatically. There is no API to retrieve contexts that have been created from other connections, i.e. `Browser.contexts()` returns only contexts that were created in the current connection.

> 2\. I want something like this but that does not clear the created contexts

This is intentionally not supported as we want different connections to be isolated from each other. Can you say more about what you are trying to achieve, perhaps we can suggest a different way to do it with playwright API?

**Comment by calebeby** [comment]
@yury-s I am running a browser test, and when the test finishes, if the test failed, I want it to leave the browser opened (for debugging), while exiting the node process that the test ran in.

**Comment by yury-s** [comment]
I see, in that case not exiting the test runner node process is your best bet.

**Comment by calebeby** [comment]
Thanks for clarifying. Unfortunately Jest force-kills test processes that don't terminate gracefully, so that's not an option for me:

![image](https://user-images.githubusercontent.com/13206945/104387694-811b5800-54ec-11eb-8b3b-a9d5275f36fd.png)

I'll be sticking to Puppeteer for now, thanks for your help anyways!

**Comment by PeterCassell92** [comment]
I am also in need of this feature.

My use case:
I am running automated tests for applications in an embedded browser (powered by Chromium) and I am connecting Playwright using `Chromium.connectOverCDP()`. The embedded browser (deliberately) has limited functionality so `newPage()` is not valid here and neither is `browserContext.close()`. There can only ever be one browser context and one page per instance of the desktop application.
In the jest environment setup, I connect to using `connectOverCDP()` however in the environment teardown I cannot use `browserContext.close()` as closing the browser context will close the desktop application (and therefore will disrupt other tests).

In puppeteer, I used to use `browser.disconnect()` and this worked because it does not try to close the browserContext, allowing my jest tests to finish correctly, with no open processes. I would like to know how to achieve the same result in Playwright or suggest a similar feature for a future release.

**Comment by IvanBalyasnikov** [comment]
In python its simple `del ur_browser`, I have tested it today
