### ISSUE TITLE
[Question] Debugging in Playwright Chromium in Docker

### ISSUE THREAD

**Issue by cozmo8691** [microsoft/playwright#5000]
Hi, 

When running and debugging Playwright tests running inside a docker container I'm finding it hard to see what's happening. DEBUG=pw:api gets me so far but do you have any guidance on how to:

1. access the Chromium console logs of the browser instance
2. get any screenshots of errors when running inside a docker container
3. debugging with breakpoints etc eg inside VS code?

Thanks in advance

**Comment by yury-s** [comment]
> * access the Chromium console logs of the browser instance

Adding `DEBUG=pw:browser` will enable browser logs in the console.

> * get any screenshots of errors when running inside a docker container

You can use `page.screenshot()` to capture the state of your page or even record [video](https://playwright.dev/docs/verification#videos)

> * debugging with breakpoints etc eg inside VS code?

There are some [tips](https://playwright.dev/docs/next/debug#visual-studio-code-debugger-nodejs) about using VS Code debugger and playwright debugging in general. It doesn't cover connecting to Node instances running in Docker though, this [VS Code page](https://code.visualstudio.com/docs/containers/debug-node) could be useful.

**Comment by bennettdams** [comment]
@yury-s Is there any more information for this? I can't seem to get it working. The debugger attaches in my setup, but breakpoints are ignored. I suspect this is caused by missing source maps. [You'll need to let VS Code know where they're located in the container](https://code.visualstudio.com/docs/containers/debug-node#_mapping-docker-container-source-files-to-the-local-workspace), but I have no idea where Playwright stores them. Do I need to compile the test files and create source maps manually?

**Comment by bmikaili** [comment]
I also find myself faced with this issue. I find it really hard to set up playwright with docker being inexperienced with it, as there is almost no documentation on it, and for now few 3rd party tutorials.
