### ISSUE TITLE
[Question] New browser windows are opened instead of tabs on every newPage()

### ISSUE THREAD

**Issue by apmcodes** [microsoft/playwright#5034]
Trying to use a single browser instance with mutiple sessions (pages/ tabs), but on every newPage() a new window is launched instead of a tab. 

main.js
```
const chromium = require('playwright').chromium;
const options =  {
  headless: false,
  timeout: 30000,
},
const browser = await chromium.launch(options);
app.set('browser', browser);
```
At this point browser window is not opened. (Unlike puppeteer which opens a new browser window on launch)

/lib/other.js
```
const browser = app.get('browser');
const page = await browser.newPage();

```
Now a new browser window is opened every time newPage is called, instead of opening a new page in the existing window. 

So, Is this the expected behaviour with PlayWright?

_NOTE: Puppeteer would open a window once (on launch) and add tabs on every newPage()._

**Comment by yury-s** [comment]
> So, Is this the expected behaviour with PlayWright?

Yes, this intentional behavior. Each page is opened in its own window. We had to split it for video recording to properly work in other browsers and wanted to keep it consistent across browsers. Moreover, in your code snippet each page created by `const page = await browser.newPage();` will have its own context and we do not want to mix pages from separate contexts in the same window (similar to how pages from different chrome profiles could never be combined as tabs in the same window). Your code is equivalent to:

```js
const context = await browser.newContext();
const page = await context.newPage();
```

Is there a test scenario that doesn't work with separate window per page approach?

**Comment by shirshak55** [comment]
@yury-s Yes it doesn't work when you are using headful mode and vnc server.  If it was multi tab we could access all tab easily but multiple windows are not accessible. We test chat application and it has become too annoying. and we need headful mode because some of the tests are done in headful mode with manual intervention. It only happens in launchPersistantContext .

**Comment by pavelfeldman** [comment]
It is unclear why vnc has a problem with multiple windows though?

**Comment by shirshak55** [comment]
@pavelfeldman vnc is always like that. When there is window on top on another window old window is hidden . And its usually hard to manage window and tabs are easier to manage in heedful mode too.

**Comment by pavelfeldman** [comment]
But there is bringToFront that is equivalent to surfacing the tab or does that not work?

**Comment by apmcodes** [comment]
> Is there a test scenario that doesn't work with separate window per page approach?

Well, our use case is not exactly related to testing but scrapping at high volume. Thus, opening many windows paralelly would hamper the memory footprint of our apps.
