### ISSUE TITLE
[DEVOPS] automate chromium builds

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#5067]
we need to do 5 builds:
- [x] mac
- [x] mac-arm (transpilation from mac intel 10.15)
- [x] linux
- [x] win32
- [x] win64

Having our custom builds will let us use Dev versions of chromium instead of Canary/Nightly. See https://github.com/microsoft/playwright/issues/5159

**Comment by Denbox** [comment]
Linking #4984 in case you haven't seen it. I'm not sure how much work it would be to automate the builds for raspberry pi ARM, and totally understand if it doesn't make the cut. That being said, here's a potential use case and some of my own efforts to get it to work.

Playwright runs smoothly on raspberry pi 4, even with 2 gigabytes of RAM (running headless on ubuntu server). I know this because I managed to get an old version of node playwright (1.4.2) running with the compiled version of chromium on the pi, which is only at version 86 or 87 last time I checked.

If this is supported out of the box, it would probably be the cheapest self hosted way for people to use playwright for scheduled, automated tests.

**Comment by aslushnikov** [comment]
> If this is supported out of the box, it would probably be the cheapest self hosted way for people to use playwright for scheduled, automated tests.

@Denbox I've never heard of anyone running automated tests on RPI. Why would you do it? Is this popular in some circles?

**Comment by Denbox** [comment]
@aslushnikov to be honest, I'm not sure that it's popular anywhere.
I guess it makes sense for anything that needs to slowly work on a large job - I use playwright for a personal web archiver and just leave large delays to be respectful of the sites I am visiting. The pi is perfect for this, although I'm not sure it's an intended or accepted use case!

**Comment by aslushnikov** [comment]
@Denbox I'd punt this for now - we're laser-focusing on testing atm. But thank you for bringing this up and explaining the use case! :)

**Comment by aslushnikov** [comment]
This is fixed now. We sometimes occasionally hit problems with GOMA, but we'll create a separate issue to track those if necessary.
