### ISSUE TITLE
[Question] How to know whether context is closed?

### ISSUE THREAD

**Issue by ocherniavskyi-lohika-tix** [microsoft/playwright#5230]
How to know whether context is closed?
There is such option for browser (isConnected) and for page (isClosed) but i cant find how to check whether context was closed

**Comment by aslushnikov** [comment]
@ocherniavskyi-lohika-tix why would you need it? No one but your own code can close the context.

**Comment by shirshak55** [comment]
@aslushnikov may be just to check if context exists are not at the runtime?  Like it may be useful at runtime to know if this context exists I will spawn this page like load balancing?

**Comment by ocherniavskyi-lohika-tix** [comment]
@aslushnikov could a context be crashed?

**Comment by aslushnikov** [comment]
> could a context be crashed?

@ocherniavskyi-lohika-tix I don't think so

> may be just to check if context exists are not at the runtime? Like it may be useful at runtime to know if this context exists I will spawn this page like load balancing?

@shirshak55 I'm not sure I follow. Since your code already manages the creation and destruction of contexts for load balancing, you should already know which contexts are created?

**Comment by dgozman** [comment]
Closing without additional information available.

**Comment by Joe118** [comment]
+1 for implementing + THANKS!

**Comment by shirshak55** [comment]
With this logic why would we even need to use the playwright(pw) instead of directly working on CDP? But we choose pw because it provides features, proper error handling, makes everything easy, etc.? 

The page also provides .isClosed and the same argument can be applied there too. Why need to provide .isClosed for page when the user can easily scan for pages in context. But we choose to provide it so it is easy for users?

To answer your question specifically, sometimes the user closes the cross icon which means the context is closed. Yes, it may be easy to do it but I may not be that talented to figure it out and I expect the playwright team to be better in handling edge cases to know whether the context is closed or not. 

I am currently doing this
```js
let isContextClosed = false;

page.context().on("close", () => isContextClosed = true)
```

It would be nice if pw provide it out of the box. It's a simple implementation but I don't know if there are edge cases.
Thank you.

**Comment by dgozman** [comment]
> To answer your question specifically, sometimes the user closes context via the cross icon which means the context is closed.

This sounds very strange - probably a bug. Context is an ephemeral entity, and does not get closed by clicking on any UI element. Do you have a repro by any chance? The only way to close the context should be an explicit call to `context.close()`.

**Comment by shirshak55** [comment]
@dgozman 

Sorry, I mean page.on("close", () => isContextClosed = true) because I wanted to check if user has clicked on X icon or not. Maybe I was confused because adding a page to context means adding a page to the browser window ( this doesn't apply to firefox though). With this rule I add only 1 page to 1 context.

What's the best way to know if the user closed the browser or not. What I wanted to do is if the user has used X it means he has closed all the pages of context so wanted to clean the context. I want to clean the context so there is no memory leak. This is a long-running process.
