### ISSUE TITLE
[Question] Differences between headless and headful execution

### ISSUE THREAD

**Issue by anderslangballe** [microsoft/playwright#5240]
From my time working with Selenium, I recall that there were some test cases that behaved differently when running in headless mode compared to headful mode.

As far as I understand, Playwright accomplishes headless execution in a different manner than Selenium. Are there any theoretical or practical differences I should be aware of in terms of headful and headless execution when writing test cases?

**Comment by shirshak55** [comment]
i think sometime website with cookies behave different. In headful I remain logged in but in headless login doesn't work I don't know why :(

**Comment by aslushnikov** [comment]
> As far as I understand, Playwright accomplishes headless execution in a different manner than Selenium. 

@anderslangballe Playwright uses headless versions of browsers. For example, both Chromium and Firefox have official headless versions: [Chromium Headless](https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md) and [Firefox Headless](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Headless_mode). 

When it comes to WebKit, Playwright team maintains webkit fork that supports headless operation across all platforms.

>  Are there any theoretical or practical differences I should be aware of in terms of headful and headless execution when writing test cases?

- Chromium vs Chromium Headless:
    * Headless does not support extensions
    * Intricate details could be found in the https://github.com/paulirish/headless-cat-n-mouse
- Firefox vs Firefox Headless:
    * We're not aware of differences
- When it comes to WebKit, you probably care about Playwright WebKit differences wrt Safari. There are documented [here](https://github.com/microsoft/playwright/blob/master/docs/development/webkit.md)

**Comment by dgozman** [comment]
Let me close this one. Please reopen if there are more questions.

**Comment by mmoossen** [comment]
Sorry to open the discussion again.
But there is a big point to be taken.
Everything depends on the browser implementation of its headless mode.
I have not encounter any flaws in the headless mode of firefox. 
AFAIK everything works the same in both, headless and headful modes.
BUT chrome is a nightmare. If you have to rely on any Policy you are doomed, since headless mode does not support Policies.
For instance, if you need a Client-Certificate or just an specific Downloads directory, it is not going to work. Forget it.
