### ISSUE TITLE
[QUESTION] - Logged in cookies don't stay set in headless but do on headless

### ISSUE THREAD

**Issue by nataliekk** [microsoft/playwright#5264]
See: https://github.com/microsoft/playwright/issues/5240#issuecomment-770897902

When I log in on adobe.com, and am rerouted to behance.net, in playwright, in *headed* I remain logged in, and in *headless* I do not. Is there a way to get the cookies to stay set in headless mode? Is this a bug, and is there any workaround?

**Comment by nataliekk** [comment]
also see: https://github.com/microsoft/playwright/issues/717

**Comment by dgozman** [comment]
- Do you mind sharing a script with us?
- When you say "rerouted", do you mean in the same page/browser? Note that #717 is about launching two browsers - that's probably not the case here?
- I won't be surprised to see that adobe.com and/or behance.net are detecting headless browsers and behave differently. A repro script would definitely help.

**Comment by shirshak55** [comment]
@dgozman its not detecting headless as they don't have any reason anyway?. I think I have couple of website having same issue. I tested with yahoo. On headful mode I remain logged in but if I flip the switch to headless there is no login probably cookies doesn't gets populated. And after I again flip to headful mode I am logged in. I am sure something is different with cookie in headless mode. Let me check on firefox and let me know. Its probably due to chrome as they have done similar thing in past.

**Comment by aslushnikov** [comment]
@shirshak55 this might be the Yahoo treating user agent / headless differently. If there is a bug indeed, it's worth filing it separately outside of this one with a repro steps that we can run locally.

As for the original bug, I'll close this due to lack of response.
