### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by nataliekk** [microsoft/playwright#5337]
Is there a way to log `expect`, as you would textContent, etc?

**Comment by dgozman** [comment]
Could you please provide more details? Below I make some assumptions, but you could mean something totally different.

I assume that you are talking about something like `DEBUG=pw:api` that is logging Playwright actions, and you'd like to see expect statements there. This is not possible, because `expect` calls do not belong to Playwright, but rather to your test runner. Which test runner do you use? Depending on the test runner, there might be a solution specific to it, or you could file an issue.

**Comment by JoelEinbinder** [comment]
I don't think we have enough info at this time to tackle this.
