### ISSUE TITLE
[Question] When will playwright-electron support Playwright's 1.8.0 API?

### ISSUE THREAD

**Issue by evanwalsh** [microsoft/playwright#5357]
I noticed that `playwright-electron` is not using the latest release of Playwright. Is this intentional? Is there any timeline for when a new version of the package will be available?

Thanks for all the hard work! Playwright is a terrific project.

**Comment by JoelEinbinder** [comment]
I'll ask about it in our meeting today :)

**Comment by pixelastic** [comment]
ping. Interested in knowing as well.

More generally, I'm interested in knowing what the release cycle for playwright-electron is, compared to the main playwright. We're having failing builds on our end with issues that seems related to https://github.com/microsoft/playwright/issues/4002 (and that should be fixed by updating to a more recent Chromium version, but playwright-electron 0.5.0 is still with `854489`)

**Comment by aslushnikov** [comment]
@pixelastic with Playwright 1.9 we now ship electron with playwright itself. Check out our docs: https://playwright.dev/docs/api/class-electron?_highlight=electron

**Comment by evanwalsh** [comment]
Excellent!
