### ISSUE TITLE
[Question] How do I open a new window within the current browser context on Chrome?

### ISSUE THREAD

**Issue by moderatemisbehaviour** [microsoft/playwright#5361]
I'm testing a Chrome extension that manages the windows you have open. For the tests I'd like to be able to create multiple windows each with whatever set of tabs I choose but I've not found a way to do that in Playwright.

From using Playwright so far it seems that with a regular browser context each page opens in a new window and with a persistent browser context each page opens in a new tab. Is there any way to have more control over this?

**Comment by JoelEinbinder** [comment]
No sorry, we don't have this functionality. We are more focused on automating the web content inside the tab, rather than the browser ui around it. So I'll close this as out of scope.

That being said, you might have luck using the chrome extension api to manage windows for your tests: https://developer.chrome.com/docs/extensions/reference/windows/#method-create

**Comment by moderatemisbehaviour** [comment]
Thanks @JoelEinbinder, and I appreciate the suggestion 👍
