### ISSUE TITLE
[Question] screenshot resolution is different in headless vs headful / UI mode

### ISSUE THREAD

**Issue by ychaudhari** [microsoft/playwright#5371]
I have seen a behavior in playwright 1.8.0 that is very similar to this issue in puppeteer (https://github.com/americanexpress/jest-image-snapshot/issues/156) where a headless element.screenshot() or page.screenshot() is 2 to 5 pixel different in size compared to headful / ui mode element.screenshot() or page.screenshot(). This is for the same browser and same viewport size. 

I can force UI mode and or play with threshold/blur etc to match images but can someone give me clues on exploring the issue further (to find the root cause)?

Does anyone know if anything is being done around this area?

**Comment by JoelEinbinder** [comment]
I'm not too concerned about the element screenshot, because subtle differences in the rendering pipeline between headless and headful could cause fonts to be slightly different.

But the page screenshot size not matching the viewport size is a very serious issue. Can you provide some tips to help me reproduce this? Thanks!

**Comment by ychaudhari** [comment]
Thanks @JoelEinbinder for your reply

on further investigation and retries, I think I can confirm that the issue only in `element.screenshot()` and not in `page.screenshot()`. I understand that there would be external variables that could cause size issue in `element.screenshot()`

I'm happy to close the question for now and explore further offline into `element.screenshot()`

**Comment by JoelEinbinder** [comment]
I'm trying to fix the issue with fonts mismatching in screenshots, but its a long and slow process. If you have a demo page or can just point me tot he font in question, ill add it to my own set of test cases. But otherwise I think you should just change your testing system to accept some size mismatch.

**Comment by bvaughn** [comment]
In case it's helpful, I ran into this issue when playing around with a pet project: https://github.com/bvaughn/planner/pull/7

Headless screenshots are different on my MacBook which causes tests to fail:

# Headless
![canvas-screenshot-1-actual](https://user-images.githubusercontent.com/29597/147839399-72421248-0449-4d4c-9351-56d917774ef9.png)

# Visible
![canvas-screenshot-1-expected](https://user-images.githubusercontent.com/29597/147839401-704a4f27-c3ab-4471-8e66-cc2e323f1024.png)

# Diff
![canvas-screenshot-1-diff](https://user-images.githubusercontent.com/29597/147839400-fca3904e-781e-40d5-975d-b30406df6ca3.png)

**Comment by bbigras** [comment]
> otherwise I think you should just change your testing system to accept some size mismatch.

@JoelEinbinder is that doable with `expect(await page.screenshot()).toMatchSnapshot('landing.png');`?
