### ISSUE TITLE
doc: Why use Promise.all when await works?

### ISSUE THREAD

**Issue by roselan** [microsoft/playwright#5470]
in [https://playwright.dev/docs/api/class-browsercontext#browsercontextonpage](https://playwright.dev/docs/api/class-browsercontext#browsercontextonpage)

there is

```
const [page] = await Promise.all([
  context.waitForEvent('page'),
  page.click('a[target=_blank]'),
]);
console.log(await page.evaluate('location.href'));
```

but this work too in our test:

```
await page.click('a[target=_blank]');
const page = await context.waitForEvent('page');
console.log(await page.evaluate('location.href'));
```

What is the reason Promise.all is used for this scenario?

**Comment by pavelfeldman** [comment]
if `'page'` event emits before `page.click` finishes, second line of your snippet will stall. The way you read our recommended snippet is: 
- start waiting for the 'page' event first
- perform click
- wait for both click to finish and for 'page' event to arrive.

**Comment by roselan** [comment]
Why didn't I see this? ty!

**Comment by advename** [comment]
I'll hijack this issue as it's the first result searching for the need of `Promise.all` in Playwright.

I'll use the [`waitForResponse()`](https://playwright.dev/docs/api/class-page#page-wait-for-response) method to showcase the issue.

---

Let's say, we have a Search Input field and a button that triggers the search, eventually making a request to an API (`https://example.com/api/search`, the search term is in the request body)

You would probably write something like this
```js
await page.locator("button").click() // search button

await page.waitForResponse("https://example.com/api/search")  
```

With the above code, there's a (high) chance that we already received a response from `https://example.com/api/search` before we reached the `await page.waitForResponse("https://example.com/api/search")` line. The `.click()` method doesn't resolve immediately, but [performs a range of (time-consuming) steps](https://playwright.dev/docs/api/class-locator#locator-click) before resolving the await promise and continuing to the next line.

`await` executes code asynchronous in sequence, one after another.

What we want here is for `await page.locator("button").click()` and `await page.waitForResponse("https://example.com/api/search")` to be executed at the same time - so that both can do their job properly. 
That's where `Promise.all()` comes into play.

`Promise.all()` executes promises concurrently, meaning,
```js
const [response] = await Promise.all([
  page.locator("button").click(),
  page.waitForResponse("https://example.com/api/search")  
]);
```
executes both `.click()` and `.waitForResponse()` at the same time. The `await Promise.all()` as a whole only resolves when all of its argument promises passed. The issue we've noticed here is called *race condition*.

Many Playwright events ([`.waitForRequest()`](https://playwright.dev/docs/api/class-page#page-wait-for-request), [`.waitForResponse()`](https://playwright.dev/docs/api/class-page#page-wait-for-response), [`.waitForEvent()`](https://playwright.dev/docs/api/class-page#page-event-popup), ...) must execute concurrently with their triggers using `Promise.all`.

---

### Bonus

The initial confusion may originate from conventional event listeners, as we know, in JavaScript (e.g. `document.addEventListener("keydown", fn())`. The above-mentioned events are promise-based, one-time events. Unless their event is triggered, you're just blocking the rest of the test.

Playwright provides "conventional" event listeners, as we know, but they may lead in many nested layers to achieve the same result.

E.g:
```js
page.once('response', async response =>{
  if(response.url() === "https://example.com/api/search" ){
    // additional events have to be nested in here as this now is the scope of the rest of the test
  }
})

await page.locator("button").click(),
```

### Bonus 2
You can also verify/inspect above statements by skipping the additional steps of the `.click()` method using the `noWaitAfter` and `force` option:

```js
await page.locator("button").click({noWaitAfter: true, force: true}) // immediately resolve

await page.waitForResponse("https://example.com/api/search")  
```
If the API does not respond immediately, then the above code should work too. However, this likely ends in untrustworthy tests that should not be used.
