### ISSUE TITLE
[Feature] Global or browser timeout

### ISSUE THREAD

**Issue by Mirobit** [microsoft/playwright#5495]
There is setDefaultTimeout for browserContext and for page but not for the browser. Maybe I missed something but it would be really nice to have a global or browser based timeout.

**Comment by anirudh-modi** [comment]
Hi @dgozman 

Can I pick this issue up? 

Here is what I understand the implementation will be similar to that of `browserContext` and `page`, ie, 

if playwright has to be depend on `timeout`, and the `timeout` value is not passed, it first looks up to a `page` default timeout, and if the same is not present it will look upto the `browserContext` default timeout..  and if we include `browser.setDefaultTimeout` then it will look at the browser's default timeout..


Please, correct me if I am wrong..

**Comment by anirudh-modi** [comment]
@Mirobit I would like to know if this is the use case you are trying to ask..  
Where at a browser level you set the default and then leave individual method to override as and when required..

Or if there is any other use case for the same..

**Comment by Mirobit** [comment]
Hi @anirudh-modi, thankyou very much for picking up the issue. Your implementation is exactly my use case.
```
browser = await chromium.launch();
browser.setDefaultTimeout(2000);

browserPlayer1 = await browser.newContext();
browserPlayer2 = await browser.newContext();
browserPlayer3 = await browser.newContext();

browserAdmin = await browser.newContext();
browserAdmin.setDefaultTimeout(4000);
```
The browserContext timeout (4000) should override the browser level timeout (2000).

**Comment by aslushnikov** [comment]
@anirudh-modi we discussed this on the team meeting and there are some reasonable concerns about this API. I'm sorry for adding the "good-first-issue" label and luring you into jumping into code.

Now, to the concerns:
- it does look like `playwright.setDefaultTimeout()` might be a better API then `browser.setDefaultTimeout()`
- both of them aren't useful for Playwright Test since we already have a test timeout there
- there hasn't been much interest for either `playwright.setDefaultTimeout()` or `browser.setDefaultTimeout()`
- currently released API `context.setDefaultTimeout()` can be used to easily polyfill the suggested API in the user land
- adding sugar API like this does add to the code footprint in both Playwright and its language ports, e.g. `playwright-java`, `playwright-python` and `playwright-dotnet`. 

Given all of this, we'd love to hold back on landing this and wait for more feedback to gauge interest.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
