### ISSUE TITLE
[Question] Why is this test failing sporadically? Screenshot shows JSON Ajax response

### ISSUE THREAD

**Issue by staterium** [microsoft/playwright#5544]
I have a straightforward test that checks if a user that enters the wrong password on the login screen is shown an error message. Under the hood, the page does the login call via Ajax and processes the result in Javascript to redirect (on success) or display the error message (on failure). 

The test has about a 40% pass rate, without any code changes in either the SUT or the test script inbetween executions. The test inputs invalid credentials, clicks the login button, and then waits for the visibility of the element that displays the error message.

When my tests fail, I take a screenshot. When this particular test fails, the screenshot displays the JSON response that was received from the Ajax call, rather than the site itself (see below). I have set exitOnPageError to false to rule out any JavaScript errors, but that didn't make a difference. I also checked for JavaScript errors in Developer Tools, and confirmed that the system displays the error message correctly when I manually try to log in with an invalid password. The test has failed on both Chromium and Firefox browsers.

Why is this happening?

![202102223022 --  A portal administrator  -- cant log in with an invalid password](https://user-images.githubusercontent.com/29271998/108674404-e6039e00-74ed-11eb-9e5d-ea094cce574c.png)

Edit: The error that the test returns is:
```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "//h2[normalize-space(.)='Login failed']" to be visible
============================================================
```

**Comment by aslushnikov** [comment]
> Why is this happening?

@staterium there's not enough information to say anything for sure. 

Some questions that might help to pinpoint issue:
- Given that it fails for you in same fashion on different browsers, I'd speculate that web server is behaving fishy. If you run it manually multiple times, does it always correctly render?
- Do you run headless or headful browsers? If headless, does the test fail when you run headful instead?

Ideally, there's a way we can repro this behavior locally - in this case we can be really helpful. Otherwise, you can send
us some artifacts and maybe we'll spot something curious in there.

For example:
- You can try running test with `DEBUG=pw:protocol*` env variable and sending the log to us
- You can try showing us some code snippet - maybe we'll see something there.

**Comment by staterium** [comment]
> * Given that it fails for you in same fashion on different browsers, I'd speculate that web server is behaving fishy. If you run it manually multiple times, does it always correctly render?

I can confirm that the UI always behaves perfectly when testing manually, which leads me to believe that...

> * Do you run headless or headful browsers? If headless, does the test fail when you run headful instead?

you are on the right track with this question. Tests always run headless in CI, but headful in dev (where it also has never failed). I will do some testing to confirm.

**Comment by aslushnikov** [comment]
Looks like it's a server behavior, I'll close this for now. Please re-submit if you think there are problems on the Playwright side!
