### ISSUE TITLE
[Docker] Follow up in docs

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#5591]
Some findings which would improve the docs regarding Docker where I saw issues coming up:

- [ ] Use focal by default
  - [ ] Promote focal by default in the documentation
  - [ ] Publish maybe even focal on the `:latest` tag
- [ ] Promote that users will use tags when they are using the image -> Otherwise correct browsers are not installed

Any other ideas?

```
Glossar:
- Bionic = Ubuntu 18.04
- Focal = Ubuntu 20.04
```

**Comment by aslushnikov** [comment]
> Promote focal by default

@mxschmitt Let's do this once github switches their `ubuntu-latest` GHA to ubuntu focal?

**Comment by mxschmitt** [comment]
@aslushnikov they are already mostly using `ubuntu-20.04` as `ubuntu-latest` and the rollout is mostly over. (see [here](https://github.com/actions/virtual-environments/issues/1816)), just tested on a repo and I got `ubuntu-20.04` with `ubuntu-latest`. Not sure if we should wait until they reflect it officially in the docs.

**Comment by aslushnikov** [comment]
Oh, perfect then! I was under impression they're going to do this some time next month.

**Comment by pavelfeldman** [comment]
Hey Max! We are trying to keep the issues list manageable and all the potential improvements like this or Node 10 deprecation are kind-of going against that trend. I'd rather only have those that our users reported or we need to act upon in a timely manner...

**Comment by haikyuu** [comment]
I ran onto https://github.com/microsoft/playwright/issues/5590 again when I upgraded playwright.

I'm a bit confused on what's necessary to upgrade. 

Then I checked the [container registry](https://mcr.microsoft.com/v2/playwright/tags/list) to find out the exact name of the tag I need to use.

But even then, I faced the same issue.

It seems like the culprit is the[ missing release](https://github.com/microsoft/playwright-test/commit/f7c2cd9445736ac006b658a66001272f0fd838a8) of `@playwright/test`. The version is now 0.1100 but it wasn't released to npm
