### ISSUE TITLE
[Feature] Get response size by API

### ISSUE THREAD

**Issue by Sinator** [microsoft/playwright#5632]
Something like: [Feature] Report page assets size #4469

Need to be able to get the size of the response like in the Network tab.

At the same time, be able to get 2 sizes:
1) transferred over network (from cache, compressed or full size)
2) the size of the resource itself

API like:
- response.getTransferredSize();
- response.getResouceSize();

![2021-02-26_14-21-03](https://user-images.githubusercontent.com/1321158/109294281-08731f80-783e-11eb-8bf6-27f033b7e81b.png)

**Comment by aslushnikov** [comment]
@Sinator You can get the size of the resource with the [`response.body()`](https://playwright.dev/docs/api/class-response?_highlight=response.bo#responsebody) and then taking the size of the buffer.

For the transfer size - there's already a feature request for this: https://github.com/microsoft/playwright/issues/4469
Feel free to upvote since we do look at feature request popularity to prioritize our work.
