### ISSUE TITLE
[BUG] Playwright Inspector window is opened outside of visible screen

### ISSUE THREAD

**Issue by bckdp0340** [microsoft/playwright#5696]
**Context:**
- Playwright Version: 1.9.0
- Operating System: Windows10 
- Node.js version: v12.18.2
- Browser: Chromium 
- Extra: laptop with 13,3" screen, 1920 x 1080 (FullHD) resolution, scaled to 150%, setup with external monitor placed above laptop screen

Example script 
```javascript
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
})().then(() => console.log('finished'));
```

When trying to debug script (set PWDEBUG=1) Playwright Inspector window is opened by Playwright outside of visible screen space - it is opened past the right border of the screen.

in 
src\server\supplements\recorder\recorderApp.ts RecorderApp.open
there is a definitions of arguments for opening the window
const args = [
      '--app=data:text/html,',
      '--window-size=600,600',
      '--window-position=1280,10',
    ];
when 1280 is changed to say 700 then Playwright Inspector windows is visible after it is first opened by Playwright.

**Comment by joelhellman** [comment]
We're new to Playwright and our internal business app is built for an audience running 1920 wide screens or larger. When we trigger the inspector, the app's browser window and the inspector overlap each other, so we have to spend some time each the inspector opens up to focus and move the inspector to the right of my app's window. Which is pretty annoying.

I understand from the discussion in here and (#7457), that at one point the inspector did open to the right of the window defined by the `viewport` config option; but that then caused issues for users with less wide screens (where the inspector disappeared/was moved off screen). And that it was prioritized to cater to the experience of users running the default/below 1280px wide screens, since the UX was really bad there (=where the inspector disappeared off screen). Fair enough I think, since that sounds really confusing and annoying. 

But for my team testing on wider screens (1280+), we would love if someone could find a way to a solution that works for both of us user groups: the ones testing on wider as well as less wide screen resolutions. 

Maybe an optional config parameter specifically relating to the inspector, like `inspector: { alwaysPositionRightOfWindow: true }` at some appropriate place could be a way? Then the users testing on wider than "default width" screens could use that. Those impacted negatively by the default behavior - i.e. overlapping window annoyance, like us :) - might get searching the playwright docs for options on inspector positioning, which hopefully then lands a hit at the documentation page where this option is brought up. 

Or I guess some dynamic magic to figure out actual screen estate etc without any extra options needed, but that feels it could be a bit complicated to get working on all devices and for all users? (As an end-user, I'll admit I'm mostly looking for a way for us to get a practical solution delivered.) 

I feel I'm too new to using the Playwright framework to have a good opinion on the area(s) where that option would make sense, but we're definitey feeling the annoyance when using the inspector to test apps designed for wider screens. 

Or maybe there is an easy workaround to this that I don't know, I'd be open to what that might be.

**Comment by joelhellman** [comment]
Since it's not completely unrelated, I'll also add that I find the inspector default size quite small, and typically spend some time every time the inspector opens to resize it; most often I increase it's height (which is not affected by the height set by the `viewport` option).

**Comment by peterblazejewicz** [comment]
I have the same issue on high density 13.*ish laptop (4k, Win 11). The codegen is trully unusable and requires attaching secondary monitor. Those x/y should be optional (via environment), most users know how to reposition multiple windows I think.
Can we work on parametrizing those? (for `codegen` command at least),
thx!

**Comment by peterblazejewicz** [comment]
this also impacts 'Debug" mde when run, e.g. from VSCode:
![image](https://user-images.githubusercontent.com/14539/144107583-17ddbb2b-a4e3-46d0-bb61-a5dc0bde9e5b.png)

Debug window unusable and cannot be moved, rendered off-screen on HDPi screen

**Comment by dgozman** [comment]
We have moved inspector position from `1280;10` to `1020;10`. Hopefully this works for most setups.

**Comment by abubelinha** [comment]
@dgozman it doesn't work for me.
Windows 10
Screen resolution 1024 x 768
I am trying to learn playwright following a couple of youtube tutorials. 
One for python: https://www.youtube.com/watch?v=CK6MWehq7vI&t=165s
```python
c:\python39\scripts\pip install playwright
c:\python39\scripts\plawright install
c:\python39\scripts\playwright codegen https://www.google.com
```

The other for node: https://www.youtube.com/watch?v=wGr5rz8WGCE&t=300s
```
C:>npx playwright codegen https://www.google.com
```

In both cases, Chromium opens and shows Google page, but I cannot see the inspector window. I only see its traybar icon (but not being able to show the window by clicking that icon).

**Comment by Radhika186** [comment]
playwright inspector is not visible , opens outside window on windows 10.

**Comment by NoahStahl** [comment]
Is the inspector window position configurable or hard-coded now? In my setup the inspector always opens behind the browser, requiring a move every launch before use.

**Comment by petetnt** [comment]
I updated to `1.25.1` and the behaviour on MacOS is seemingly even worse now: the browser window open behind other windows and the inspector window opens behind the blank browser window. Worse yet, neither of the windows create an icon in the task bar, which they previously did.

![image](https://user-images.githubusercontent.com/7641760/189084483-17b60149-f163-46d0-b222-96a3b1a64552.png)
![image](https://user-images.githubusercontent.com/7641760/189084538-55e84ae2-73b0-4f50-8050-ba8735cff42e.png)

**Comment by josch-001** [comment]
In my setup, the browser opens on the main screen and the inspector opens on the left side of the secondary screen. This is extremely annoying.
Why can't this be configured? Playwright.config and/or environment variables?

Playwright is a great tool, and this would make life so much easier.
