### ISSUE TITLE
[Question] Docker debian slim image

### ISSUE THREAD

**Issue by materia2021** [microsoft/playwright#5857]
any plans on supporting slim debian image? the base image ubuntu is so big.

**Comment by mxschmitt** [comment]
The size difference between Debian slim and Ubuntu in Docker is not that big (55.3MB vs 72.9MB). The reason why the Docker image is so big is that it includes all the dependencies for all the browsers, Node.js and a Python installation which results in currently 1.88GB. If you need a smaller one and use e.g. only Chromium, then you can reduce the size significantly by only installing the needed Chromium dependencies, see for that the comments in the [Dockerfile](https://github.com/microsoft/playwright/blob/master/utils/docker/Dockerfile.focal).

So its more the question if there should be by browser specific Docker images, I think its not worth it since on NPM most of the people also use the `playwright` package instead of the browser specific packages.
