### ISSUE TITLE
[BUG] Security report when using 1.9.2 docker image: openssl

### ISSUE THREAD

**Issue by weyert** [microsoft/playwright#5954]
**Context:**
- Playwright Version: 1.9.2
- Operating System: Linux
- Node.js version: 14.16.0
- Browser: All
- Extra: [any specific details about your environment]

If I am using the Google Cloud docker image checker I am getting the following warning when letting it scan my Playwright docker image:

```
Affected Location: cpe:/o:canonical:ubuntu_linux:18.04
Package: openssl
Version: 1.1.1
Revision: 1ubuntu2.1~18.04.6
```

I think this is related to the following:
https://www.openssl.org/news/secadv/20210325.txt

**Comment by mxschmitt** [comment]
If you are using `mcr.microsoft.com/playwright:focal` instead of `bionic` that should fix the issue and a newer OpenSSL version should be used (tested and checked version, looks ok).

For bionic you need to wait until it gets backported into the security apt repository, takes probably a few hours or days (I think so far it isn't yet). Then Playwright either needs to rebuild and push or you need to do `apt-get update && apt-get upgrade`.

**Comment by weyert** [comment]
Thank you! Let me try out `focal` :)

**Comment by aslushnikov** [comment]
@weyert did it work?

**Comment by weyert** [comment]
Yes, it worked for me :) Ended up doing what @mxschmitt suggested:

```
FROM mcr.microsoft.com/playwright:v1.10.0-focal
# Attempt to update the security updates to ensure openssl is updated
RUN apt-get update && apt-get upgrade -y libssl1.1 libudev1 libzstd1 openssl
```

After this it didn't complain about the openssl vulnerabilities anymore
