### ISSUE TITLE
[Question] How can i see the first request in devtool?

### ISSUE THREAD

**Issue by Suniron** [microsoft/playwright#6180]
Hey there!

I'm using the latest version of **Playwright** and I don't see the first request in the devtool.

For exemple, with the code below in async function:

```javascript
  const browser = await chromium.launch({ headless: false, devtools: true });
  const context = await browser.newContext({
    userAgent:
      "Mozilla/5.0 (Linux; Android 5.1.1; SHIELD Tablet Build/LMY48C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.63 Mobile Safari/537.36",
    });
  const page = await context.newPage();

  await page.evaluate(async () => {
    const req = await fetch("https://google.fr"); // or every other url
    console.log(await req.text());
  });
```

I i put `await page.waitForTimeout(1000);` after the page init, the request result appear correctly in the devtool.

Can i wait another event which is more accurate ?

Thank's ! :-)

**Comment by JoelEinbinder** [comment]
Unfortunately I don't think there is anything reasonable for you to wait for here. There is a race when the devtools page is starting up. It doesn't track network requests until it fully loads. `waitForTimeout` seems like the best option.

Instead, you can create a HAR file from playwright, and drop it into the devtools network panel to inspect it. Check out the `recordHar` option when creating a new context: https://playwright.dev/docs/api/class-browser?_highlight=newcontex#browsernewcontextoptions

Closing this issue because it's not actionable for us.
