### ISSUE TITLE
[Question] How I wait for all XHR requests to be completed?

### ISSUE THREAD

**Issue by edscript** [microsoft/playwright#6325]
I am running end to end tests and the site works a lot through ajax, how do I wait for all XHR requests to be completed and then validate/execute the test?
```js
      await page.waitForResponse('https://site/search/internalsearch')
      // test
      const valueExpected = await page.$eval('#SearchTitle', (el) => el.innerHTML)
      expect(valueExpected).toContain('320')
```
So far I have been using _waitForResponse_, but I need to open the Network tab in the dev tools and see which request contains the response, which is very time consuming. I think the best alternative is to wait for all requests and after that execute the tests.

**Comment by mxschmitt** [comment]
As you said waiting for a response might be not ideal. Also from the Playwright's perspective, there is no way of detecting when all the requests of a web application are done. (There is `networkide` in Page.goto or Page.waitForLoadState which waits for an idle of 500ms but its not recommended since requests of an application can happen after it). The best would be to wait for the selector where you want to click on, or the data you want to assert for, only in edge-cases you should rely on waiting on actual http resources. See here for the documentation for auto-waiting: https://playwright.dev/docs/actionability

Let me know if this made it more clear for you. Thanks!

**Comment by mxschmitt** [comment]
Closed for now since we didn't get any response. If the problem is still persistent, feel free to reopen.
