### ISSUE TITLE
[Question]Can I replace the default Webkit with another version?

### ISSUE THREAD

**Issue by ChijinZ** [microsoft/playwright#6388]
I'm looking for a way to replace the Webkit in `~/.cache/ms-playwright/webkit-*` with a customized one (I built it from webkit's source code).  But I notice that the MiniBrowser binaries of them are quite different. For example, the playwright's wpe MiniBrowser has an `inspector-pipe` option, which the original webkit's MiniBrowser doesn't have.

Did I miss something? Can I replace the default Webkit with a older/newer version?

**Comment by mxschmitt** [comment]
WebKit and Firefox are custom built by using the build infra in the [browser_patches](https://github.com/microsoft/playwright/tree/master/browser_patches#readme) directory. It is generally not intended to use a custom WebKit version to test it e.g. on lower versions, since there are custom patches made against the upstream browser.

Are you trying to test it with older versions or do you want to test certain scenarios?

**Comment by ChijinZ** [comment]
Thanks! In fact, I'm trying to use an instrumented browser to visit some websites so that I can collect the browser's coverage and do some analysis. So I turn to playwright and hope it can drive a headless mode for the instrumented WebKit. But it seems that playwright is not a good fit for this task. Any suggestion?

**Comment by yury-s** [comment]
I you already have an environment where you can build stock WebKit you can apply our patches and build it from source with playwright patches (see [instructions](https://github.com/microsoft/playwright/tree/master/browser_patches#1-setting-up-local-browser-checkout) how to get our patch applied). We use [build.sh](https://github.com/microsoft/playwright/blob/master/browser_patches/webkit/build.sh) to compile it on linux/mac which just calls the same toolchain as stock WebKit build.

**Comment by ChijinZ** [comment]
Thanks!
