### ISSUE TITLE
[FEATURE] Linux Mint

### ISSUE THREAD

**Issue by FatuityCookie** [microsoft/playwright#6554]
Kernel: 5.4.0-73-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.8.6 
  wm: muffin dm: LightDM Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 

when run this cmd

npx playwright install-deps

Cannot install dependencies for this linux distribution!

**Comment by mxschmitt** [comment]
Playwright does only support Ubuntu 18.04 and 20.04 officially. Other Linux distributions or modifications are not supported. See here: https://playwright.dev/docs/intro#linux

**Comment by JoelEinbinder** [comment]
We officially only support ubuntu, but I think we can probably extend that to ubuntu-derived distros like Mint. I'll take a look.

**Comment by JoelEinbinder** [comment]
Fixed. Should land in the release sometime next month.

**Comment by osmenia** [comment]
Hi @JoelEinbinder 

Can you pls help, does Plw support Linux Mint?

#########################
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21
DISTRIB_CODENAME=vanessa
DISTRIB_DESCRIPTION="Linux Mint 21 Vanessa"
NAME="Linux Mint"
VERSION="21 (Vanessa)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21"
VERSION_ID="21"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vanessa
UBUNTU_CODENAME=jammy
cat: /etc/upstream-release: Is a directory

####################
Error: 

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package ttf-unifont is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  fonts-unifont

E: Package 'ttf-unifont' has no installation candidate
E: Package 'ttf-ubuntu-font-family' has no installation candidate
E: Unable to locate package libenchant1c2a
E: Unable to locate package libicu66
E: Unable to locate package libvpx6
E: Unable to locate package libwebp6
Failed to install browser dependencies
Error: Installation process exited with code: 100
