### ISSUE TITLE
waitForLoadState waitUntil domcontentloaded doesn't wait

### ISSUE THREAD

**Issue by guzzur** [microsoft/playwright#662]
Sorry if I am misusing the method.

```js
await page.waitForLoadState({ waitUntil: "domcontentloaded" });
let elementHandle = await page.$('input[name="username"]');
await elementHandle.type(USER_DETAILS.username); <- crashes as elementHandle is null
```

but

```js
await page.waitFor('input[name="username"]');
let elementHandle = await page.$('input[name="username"]');
await elementHandle.type(USER_DETAILS.username); <- works fine
```

Thanks a lot!

**Comment by pavelfeldman** [comment]
I can repro with the following snippet:

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
   // fire async navigation
  page.goto('https://www.chromium.org/');
   // await state
  await page.waitForLoadState({ waitUntil: 'domcontentloaded' });
  const elementHandle = await page.$('input[name="q"]');
  // elementHandle is null
  await elementHandle.type('username');
})();
```

It looks like `waitForLoadState` does not respect the script-initiated navigations. We didn't have a unit test for this because we would typically `await page.goto(...)` itself and that ensures load event is fired by default.

Btw, there is a convenience [`page.fill()`](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagefillselector-value-options) method that awaits for the given element to become available and then fills the input. So we would typically do something like this:

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  // Awaiting newPage is the same as awaiting page and awaiting page.goto
  const page = await context.newPage('https://www.chromium.org/');
  await page.fill('input[name="q"]', 'username');
})();
```

**Comment by guzzur** [comment]
Actually I can reproduce with:
```
  await page.goto('https://www.chromium.org/');
  await page.waitForLoadState({ waitUntil: 'domcontentloaded' });
  let elementHandle = await page.$('input[name="username"]');
  // elementHandle is null
```

"playwright": "0.9.21"

**Comment by pavelfeldman** [comment]
`await page.waitForLoadState({ waitUntil: 'domcontentloaded' });` is a no-op after `page.goto` since `goto` waits for the `load` event by default. Load event for non-blank pages happens after the `domcontentloaded`.

It looks like the input is being added into the page dynamically and the recommended way of handling it is using `page.waitForSelector`, `page.click`, `page.fill` or any other selector-based method. They are waiting for the element to become available and visible.

**Comment by guzzur** [comment]
But even i `await page.goto(...)`, I am getting these still-loading screenshots. Doesn't that mean the `domcontentloaded` haven’t fired yet?

How can I ensure that the page is fully loaded before I continue?

**Comment by aslushnikov** [comment]
@guzzur can you please share your exact script with the website URL that you try to load? I'd help us to see and debug what's going on

**Comment by guzzur** [comment]
@aslushnikov 

```
const playwright = require("playwright").chromium;

const address = "https://app.produp.co"; // <- same with localhost:3000
const screenshotPath = "./screenshots";
const USER_DETAILS = {
  username: "some@email.com",
  password: "somepassword"
}

(async () => {
  const browser = await playwright.launch();
  const context = await browser.newContext();
  const page = await context.newPage();

  try {
    await page.setViewport({
      width: 1920,
      height: 1080,
      deviceScaleFactor: 1
    });

    // -----------------------------------------------------------
    await page.goto(address); // <- this one should wait for the page to be fully loaded, but it doesn't
    await runLoginTest();
    // -----------------------------------------------------------
  } catch (e) {
    // ...
  }

  async function runLoginTest() {
    await page.waitFor('input[name="username"]'); // <- doesn't work without this

    await page.screenshot({ path: screenshotPath }); // <- without waitFor input, the screenshot is a loading page (background only)

    let elementHandle = await page.$('input[name="username"]'); // <- without waitFor input, elementHandle is undefined
    await elementHandle.type(USER_DETAILS.username);

    elementHandle = await page.$('input[name="password"]');
    await elementHandle.type(USER_DETAILS.password);
    
    await elementHandle.press('Enter');
    await page.waitFor('#fuse-toolbar');
  }
})();

```

**Comment by guzzur** [comment]
> I can repro with the following snippet:
> 
> ```js
> const { chromium } = require('playwright');
> 
> (async () => {
>   const browser = await chromium.launch();
>   const context = await browser.newContext();
>   const page = await context.newPage();
>    // fire async navigation
>   page.goto('https://www.chromium.org/');
>    // await state
>   await page.waitForLoadState({ waitUntil: 'domcontentloaded' });
>   const elementHandle = await page.$('input[name="q"]');
>   // elementHandle is null
>   await elementHandle.type('username');
> })();
> ```
> 
> It looks like `waitForLoadState` does not respect the script-initiated navigations. We didn't have a unit test for this because we would typically `await page.goto(...)` itself and that ensures load event is fired by default.
> 
> Btw, there is a convenience [`page.fill()`](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagefillselector-value-options) method that awaits for the given element to become available and then fills the input. So we would typically do something like this:
> 
> ```js
> const { chromium } = require('playwright');
> 
> (async () => {
>   const browser = await chromium.launch();
>   const context = await browser.newContext();
>   // Awaiting newPage is the same as awaiting page and awaiting page.goto
>   const page = await context.newPage('https://www.chromium.org/');
>   await page.fill('input[name="q"]', 'username');
> })();
> ```

**Comment by dgozman** [comment]
I took a closer look here, and we have two problems:
- `page.waitForLoadState` does not wait for the "upcoming" navigation, e.g. after non-awaited `page.goto` because it does not know there will be a navigation. This is by design, but clearly not obvious. We should be able to tweak our apis here.
- We don't have an option 'wait for my site to be ready and stable for a while so that I am sure it did load everything'. This is what happens on `https://app.produp.co`, where domcontentloaded and load fire before the login form will start rendering (which comes from `componentDidMount` after async check for firebase auth).

**Comment by dgozman** [comment]
> * `page.waitForLoadState` does not wait for the "upcoming" navigation, e.g. after non-awaited `page.goto` because it does not know there will be a navigation. This is by design, but clearly not obvious. We should be able to tweak our apis here.

We decided to leave `page.waitForLoadState`, and update documentation/snippets to make the difference between `waitForLoadState` and `waitForNavigation` more obvious.

> * We don't have an option 'wait for my site to be ready and stable for a while so that I am sure it did load everything'. This is what happens on `https://app.produp.co`, where domcontentloaded and load fire before the login form will start rendering (which comes from `componentDidMount` after async check for firebase auth).

This is a stretch feature, and we'll keep thinking in this direction.

**Comment by Pomax** [comment]
is there a link to that stretch feature? Because I'm running into the lack of "wait for DOM to be stable" and it makes running visual diffing *considerably* harder than it needs to be because neither `networkidle` nor `domcontentready` are useful for modern sites that use React or Vue or the like. For those, the `networkidle`/`domcontentready` events in fact signal the _start_ of the DOM mutation process, rather than any "this page is now stable" event.

**Comment by florianbepunkt** [comment]
I would also be interested in what are the best practices for react.

**Comment by sytolk** [comment]
I'm not sure is this a the cleanest solution? but it works for me in React. 
For example after click on Delete button and needs to waitFor rerender React component:
`await page.waitForLoadState('networkidle');`
..next check if deleted item exist
