### ISSUE TITLE
core version?

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#666]
I don't want to download binaries especially when i have already installed firefox, edge or chrome. It would be very helpful if there will be core version of it just like puppeteer. 

Thanks.

**Comment by pavelfeldman** [comment]
There is [playwright-core](https://www.npmjs.com/package/playwright-core), but you can't point to a stock version of any browser yet:
- there is no Chrome stable that would already contain all of the changes required for Playwright (same story as with Puppeteer here, we are a bit ahead of the Stable train)
- it'll take time to upstream the WebKit & FF changes

Is the main motivation for your request to be on the stable channels of the browers following their release cadence? Or do you want to reuse the same binaries instead of downloading them over and over for each playwright install?

**Comment by shirshak55** [comment]
@pavelfeldman  Yes want to save space mostly and time. When binaries get downloaded it takes too much time etc. Puppeteer core has really worked well with current version of chrome so I don't think playwright-core will also suffer problem .

**Comment by aslushnikov** [comment]
> Puppeteer core has really worked well with current version of chrome so I don't think playwright-core will also suffer problem .

@shirshak55 Currently, `playwright-core` is guaranteed to work only with Chrome 81 - which is Chrome Canary. Puppeteer has a compatibility table to match puppeteer-core versions against separately-installed browser versions:

![image](https://user-images.githubusercontent.com/746130/73224721-3d82df00-411f-11ea-9661-2febdd2871a1.png)

We're too young atm to have a similarly looking table: as Pavel mentioned, we need some time to upstream our webkit & firefox patches. But as the project matures, we'll come up with some pretty story to run playwright against separately installed / stable versions of browsers.
