### ISSUE TITLE
Default Context Set Options

### ISSUE THREAD

**Issue by Sue9445** [microsoft/playwright#667]
Hi,

How to set useragent,timezone,viewport,csp for default context? Can you add some functions for settings like puppeteer?

page.setBypassCSP();
page.setUserAgent();
page.emulateTimezone();

**Comment by pavelfeldman** [comment]
We could, but we think that users should create new contexts when they emulate other user agents. That way cookies and other relevant state is consistent within the browser context. We would even prefer to add `browser.newContext({userDataDir})` that would be persistent. Would that work for you? Could you share more about your use case?

**Comment by xprudhomme** [comment]
Hi,

@pavelfeldman 
The main problem with what you are suggesting, is the fact we would always have at least two browser windows opened (one for the defaultContext, and another one for the newContext).

- What if for some reason the defaultContext crashes?
- How about performances issues ? I'd rather have only one window opened, not two, especially if only one is used

Furthermore, this behavior is not consistent with the Puppeteer's one.

I agree that page.setUserAgent() might not be the best place where to set the user agent and it should be done at the browser context level. But that would definitively be helpful if we could set the user-agent for the default context, without having to open a second browser context.

**Comment by aslushnikov** [comment]
> What if for some reason the defaultContext crashes?

@xprudhomme Browser crashes are nasty - and happen unrelatedly to the opened windows. I'd rather not bring this in.

> How about performances issues ? I'd rather have only one window opened, not two, especially if only one is used

Performance-wise, these are not demanding at all. I don't think you'll be able to measure a difference with your tests running if you have an extra idle browser window. Furthermore, creating browser contexts is extremely cheap.

--- 

Having said this all, we do know that having a window from a default context is unfortunate. We poked a few times into removing it, but it turns out to be a hard task in the browsers-land.

For now, we consider this to be a cosmetic bug: it shouldn't affect any of the functionality or regress performance, but it doesn't look good in a headful browsers.

**Comment by pavelfeldman** [comment]
We have no longer have 2 windows open.
