### ISSUE TITLE
[BUG] timeout option in `page.isVisible` is not clear

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#6673]
Does it wait for the specified timeout before checking for visibility? Does it wait for the element to be attached to the DOM with a timeout? Same goes for `isHidden`.

**Comment by emakhachek** [comment]
Please consider the following use case:
I have several tests where I need to verify that the element is appeared after some actions. I prefer to get a boolean value in the return. That's why I have created the following method:
`async isElementVisible(
    selector: string
  ): Promise<boolean> {
    try {
      return Boolean(await page.waitForSelector(selector));
    } catch (e) {
      return false;
    }
  }`
So, to have page.isVisible with timeout option can cover such case.

**Comment by dgozman** [comment]
@emakhachek This is a nice use case, but it does not suite the semantics of other methods. I think we'll address this on the `expect` level, for example with `expect(page).toHaveVisible('selector')` or similar.

**Comment by dgozman** [comment]
For now, this timeout option has been removed in #7414.
