### ISSUE TITLE
[Question]How to listen "Aw, Snap! Something went wrong while displaying this webpage. Error code:Out of Memory"

### ISSUE THREAD

**Issue by selang** [microsoft/playwright#6674]
How to listen "Aw, Snap! Something went wrong while displaying this webpage. Error code:Out of Memory"

![1621482630(1)](https://user-images.githubusercontent.com/26321918/118916490-a4a25380-b961-11eb-88bc-f7629bfeb811.png)

**Comment by mxschmitt** [comment]
It's usually not common that such errors appear, most commonly when your computer runs out of memory and Chromium can't get new memory.What is your use-case which you want to cover?

**Comment by selang** [comment]
Sometimes this happens when running a test. But the program cannot recognize this situation. So I want to ask if there is a good way to deal with it.

**Comment by mxschmitt** [comment]
If this happens during a test, then it's either a bug in the web-application that it leaks a huge amount of memory or your system has too less memory available to run the tests on. In both cases we don't guarantee anymore the Playwright library to work since the system is overloaded or the application is unresponsive.

It should also lead to a Page.crash event, see here: https://playwright.dev/docs/api/class-page#pageoncrash

```js
page.on("crash", () => console.log("Page crashed"))
```
