### ISSUE TITLE
[Question]how to run playwright Java code in docker

### ISSUE THREAD

**Issue by techshashank80** [microsoft/playwright#6726]
Hi There,

Can someone guide that on how to run playwright Java code in Docker? I understand that we have to use WebSocket, here is my code:
```java
        playwright = Playwright.create() ;
        playwright.chromium().connect("ws://0.0.0.0:3000/chromium", new BrowserType.ConnectOptions());
        browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false).setArgs(Arrays.asList("--ipc=host","--no sandbox","--disable-dev-shm-usage")).setChromiumSandbox(false));
        context = browser.newContext(new Browser.NewContextOptions());
        page = context.newPage();
```

I am trying to run docker using the following command, anything I am missing, please correct.

docker run -it --rm --ipc=host mcr.microsoft.com/playwright/java:focal /bin/bash

I am on a Mac machine, Docker. Above run docker command runs in docker without localhost/port number

**Comment by yury-s** [comment]
You can pull your project into a Docker container based on one of playwright images (`mcr.microsoft.com/playwright/java:focal` is good) and run Playwright tests there as you would do on your host machine (e.g. `mvn test`). To run [PageScreenshot](https://github.com/microsoft/playwright-java/tree/master/examples) example in Docker you can do the following:

```sh
// Launch docker container
docker run -it --rm --ipc=host mcr.microsoft.com/playwright/java:focal /bin/bash

// Inside docker container:
apt install git
cd
git clone https://github.com/microsoft/playwright-java.git
cd playwright-java/examples/
mvn compile exec:java -Dexec.mainClass=org.example.PageScreenshot
```
Now instead of playwright examples copy your project into the Docker and run it there.

Looks like you are trying to launch playwright server inside Docker and connect to it from a client running in the host system. To do so you'd have to start Playwright server with a browser inside the Docker container manually and then configure port forwarding to the host system. Note that [launchServer](https://playwright.dev/docs/api/class-browsertype#browsertypelaunchserveroptions) API is only available in JavaScript so you'd need to run the server in js.

Is there a reason you want to run your client in the host system while browsers are in the Docker? In general it's easier to run both of them on the same system.

**Comment by yury-s** [comment]
Please reopen if you have further questions.

**Comment by techshashank80** [comment]
Thank you for explaining in detail.

Yes, I wanted to run with headless ==false. and see the physical browser running. Generally wanted to use wsEndpoint.
Since it's not available in Java then will wait for it. Thanks
