### ISSUE TITLE
[BUG] webkit not running on Linux Solus

### ISSUE THREAD

**Issue by allanpfreitas** [microsoft/playwright#6730]
**Context:**
- Playwright Version: 1.11.1
- Operating System: Linux - Solus
- Node.js version: 16.2.0
- Browser: Webkit
- Extra: Using Linux Solus 

**Code Snippet**

```javascript
import {webkit, firefox} from 'playwright';

for (const browserType of [webkit, firefox]) {
    console.log('running', browserType.name());
    const browser = await browserType.launch();
    const page = await browser.newPage();
    await page.goto('https://www.google.com/')
    await page.screenshot({
        path: `screenshot-${browserType.name()}.png`,
    });
    await browser.close();    
}
```

**Describe the bug**

I'm trying to run this basic script against webkit but I'm getting this error of missing dependencies: 

![Screenshot from 2021-05-24 19-28-55](https://user-images.githubusercontent.com/2490836/119419501-cb011f80-bcd0-11eb-94b3-a1c753c86d70.png)

**Comment by mxschmitt** [comment]
Only Ubuntu 18.04 and 20.04 are officially supported on the Linux side, see [here](https://playwright.dev/docs/intro#system-requirements). For the other distributions you need to install the dependencies yourself via the system package manager, sometimes it's not possible (or not straightforward) to launch certain browsers there, because we compile these browsers only on these two Linux Ubuntu LTS releases.

Something which will always work is using the system package manager and install Google Chrome / Chromium there - if its available, then you can use this Chromium via the executablePath in the [BrowserType.launch](https://playwright.dev/docs/api/class-browsertype#browsertypelaunchoptions) which should work.

**Comment by allanpfreitas** [comment]
> Only Ubuntu 18.04 and 20.04 are officially supported on the Linux side, see [here](https://playwright.dev/docs/intro#system-requirements). For the other distributions you need to install the dependencies yourself via the system package manager, sometimes it's not possible (or not straightforward) to launch certain browsers there, because we compile these browsers only on these two Linux Ubuntu LTS releases.
> 
> Something which will always work is using the system package manager and install Google Chrome / Chromium there - if its available, then you can use this Chromium via the executablePath in the [BrowserType.launch](https://playwright.dev/docs/api/class-browsertype#browsertypelaunchoptions) which should work.

Hi, thanks for your reply, but the Chromium browser is running okay my problem is to run Webkit browser.

**Comment by allanpfreitas** [comment]
> Yeah for WebKit and Firefox you unfortunately rely on the Playwright builds and can't install them via your package manager. So you need to try if the listed dependencies are available on your linux distribution.

Ok thanks, I'll try to set up Ubuntu.
