### ISSUE TITLE
[Feature request] "Self-healing" locators support

### ISSUE THREAD

**Issue by radekBednarik** [microsoft/playwright#6874]
Hello, would it be possible/feasible to implement some kind of support for "self-healing" locators in Playwright library?

My use case:

I usually work on projects, when I have to develop automated tests on already developed web applications. These are often NOT developed with automated testing in mind, and so lots of element locators are rather complicated/chained/brittle. And it is not always possible to have developers of the app to add @id s to needed elements.

This increases needed maintenance and lowers reliability and effectiveness of the automated tests.

Thank you for great tool and your work.

RB

**Comment by pavelfeldman** [comment]
Looks like you want "resilient" selectors rather than "self-healing". I'd suggest that you take a look at our text selectors https://playwright.dev/docs/next/selectors#text-selector and CSS selector extensions: https://playwright.dev/docs/next/selectors#selecting-elements-matching-one-of-the-conditions. There are no plans for self-healing selectors at the moment because they defeat the testing purpose.
