### ISSUE TITLE
Add typescript example to getting started docs

### ISSUE THREAD

**Issue by maxwell8888** [microsoft/playwright#6971]
I chose to use Playwright because it is written in TS and so I assume has good TS support. However I struggled to get a simple hello world working in typescript because I was importing chromium like `import chromium from "playwright"` not `import { chromium } from "playwright"`.

Please add a minimal TS example, currently the only TS code in the docs is `let page: import('playwright').Page;`. I suggest adding a TS version of your getting started script:
```js
const { webkit } = require('playwright');

(async () => {
  const browser = await webkit.launch();
  const page = await browser.newPage();
  await page.goto('http://whatsmyuseragent.org/');
  await page.screenshot({ path: `example.png` });
  await browser.close();
})();
```

**Comment by pavelfeldman** [comment]
We picked JS for examples because every JS file is a valid TS file. So you can use all of our examples in the .ts files. IDE will also help you converting the imports should you want to use the import syntax:

<img width="450" alt="Screen Shot 2021-06-10 at 4 46 22 PM" src="https://user-images.githubusercontent.com/883973/121610734-7fa67b00-ca0b-11eb-8ebe-bff599ae0506.png">

We are getting better at it though, so our new docs for test runner (which is the way we expect most people to consume Playwright) are TS-first: https://playwright.dev/docs/test-intro

**Comment by mxschmitt** [comment]
Closed for now, since it seems not needed.
