### ISSUE TITLE
[Feature] add Allure reporter

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#7034]
See here; https://github.com/zaqqaz/jest-allure/blob/master/src/Reporter.ts

And here: https://github.com/allure-framework/allure-js

Please thumbs up if you are interested. 👍

**Comment by mpuertao** [comment]
This is possible?->, add screenshots to the report with allure in the version 1.13.0 of @playwright/test

**Comment by kshrestha99** [comment]
I would like to second the need for screenshots to the report for each test 'it' statement, for both passing and failing tests.

**Comment by pavelfeldman** [comment]
```bash
npx playwright test --reporter=line,experimental-allure-playwright
```

or 

```ts
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  reporter: 'experimental-allure-playwright',
};
export default config;
```

You can specify target folder using `ALLURE_RESULTS_DIR` environment variable.

Once https://github.com/allure-framework/allure-js/pull/297 lands and Allure team pushes the NPM, it'll become `allure-playwright` instead of `experimental-allure-playwright`.

**Comment by vsravuri** [comment]
@pavelfeldman Could you please share JS example ?

**Comment by AlexKomanov** [comment]
@pavelfeldman 
Please provide the code example for output directory definition.

**Comment by mpuertao** [comment]
it doesn't work for me

![image](https://user-images.githubusercontent.com/33495827/126580677-f2c1b26d-7903-4ccc-86f7-73b73f122899.png)

Has someone worked for you and can you share some example code?

**Comment by JoelEinbinder** [comment]
You have to `npm i experimental-allure-playwright` first.

**Comment by mpuertao** [comment]
Ok, thanks @JoelEinbinder. Question: Where is the HTML generated?

**Comment by mailtogagan** [comment]
allure reports are looking good.. with traces and screenshots also embedded in the report.. still needs to be explore a bit more.

**Comment by AlexKomanov** [comment]
> Ok, thanks @JoelEinbinder. Question: Where is the HTML generated?

@mpuertao 
It depends on your definition of the directories.
Allure requires installation of the server (local or remote) or it can be used as a plugin in the case of Jenkins. See more [here](https://docs.qameta.io/allure/#_commandline)
I used the local installation of the allure server.

Then I defined the report (still experimental):

![image](https://user-images.githubusercontent.com/52656401/126595591-fc06c6c6-d45d-479c-98d8-5b6357c0e6b6.png)

Then, performed this command (the path to the directory is up to you):

![image](https://user-images.githubusercontent.com/52656401/126598505-d695cd78-5c62-41fd-bf08-268c5cb114c7.png)

After the test run - the defined folder will be created:

![image](https://user-images.githubusercontent.com/52656401/126598934-7641c836-1c32-4d9e-a265-0bf72222287c.png)

But the created results are kind of RAW data. In order to generate a report in the case of the local server, we need to run another command - 'allure generate <path-to-source-directory> -o <path-to-output-directory:

![image](https://user-images.githubusercontent.com/52656401/126599208-545a0265-3e89-4fd6-adbe-5783236d845a.png)

It will generate a folder with the report files:

![image](https://user-images.githubusercontent.com/52656401/126599259-a110f235-0f3d-4f70-8232-e8f14c2ea536.png)

Then, in order to open the report - we need to open a server with the command 'allure open <path-to-generated-folder>, as the following:

![image](https://user-images.githubusercontent.com/52656401/126599426-38779d02-e5cd-4c9d-b253-e81f0ca587c1.png)

And then - the report will open in the browser:

![image](https://user-images.githubusercontent.com/52656401/126599584-3f5b6ff9-f8aa-474c-bb00-be58b07ca249.png)

Hope it is clear enough.

**Comment by mpuertao** [comment]
Very thanks @AlexKomanov . I was missing the: allure open. I worked perfect for me. thanks again

**Comment by BMayhew** [comment]
Following @pavelfeldman post, my local allure results were being saved to allure-results (vs allure-result) so for the report to load with results I had to adjust the run commands as 

`npx playwright test --reporter=line,experimental-allure-playwright
allure generate ./allure-results --clean
allure open ./allure-report` 

Great work on this, super easy to get allure wired up!!!

**Comment by ssurabhi10** [comment]
Facing error on ubuntu `allure: command not found` when running `allure generate ./allure-results --clean
`

**Comment by mxschmitt** [comment]
You need to install Allure, see here for instructions: https://docs.qameta.io/allure/

**Comment by ssurabhi10** [comment]
Get this error
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-16-openjdk-amd64/lib/libawt_xawt.so` 
while running `allure open ./allure-report`

**Comment by ssurabhi10** [comment]
Is there any other way to open reports other than `allure open ./allure-report` ?

**Comment by mxschmitt** [comment]
This is not an Playwright related error, please use the Allure support channels e.g. on their GitHub for that.

Allure is required to open an allure report.

**Comment by itasworkshop** [comment]
I tried to use it but it's giving ![image](https://user-images.githubusercontent.com/24596705/128579644-b615567a-696b-4b0b-b3ee-d64c32f77fdd.jpeg)

**Comment by baev** [comment]
btw https://www.npmjs.com/package/allure-playwright was released

**Comment by Himani33** [comment]
Hi.. Does anyone know which allure package to use for playwright with jest runner (I AM NOT USING PLAYWRIGHT/TEST RUNNER). I am using [jest-allure](https://github.com/zaqqaz/jest-allure) npm package but it does not take screenshots in failure tests. I am looking for a npm package to generate allure reporting with screenshots for my Playwright + jest runner tests. Any recommendations will be highly appreciated.

**Comment by dharitreesahoo** [comment]
How can I print Execution Environment in Allure report. I am using playwright Test Runner. In Jest runner I am able to get the solution. Can any body help  on this.
