### ISSUE TITLE
[Feature] Shuffle tests with a random order

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#7040]
This will help users to find tests which depend on other tests. Go has it for example in their test-runner: https://twitter.com/inancgumus/status/1397168068955021312

**Comment by pavelfeldman** [comment]
I've seen this in many projects I worked on and although a good idea, it was inevitably disabled and abandoned. I'd wait for real customer-initiated request.

**Comment by humbienri** [comment]
As we comment on our test automation effort and move away from Capybara, I'd like to implement random execution of the specs we port over to Playwright, or any other tool such as Cypress for that matter. I think this random execution will help us stay honest from the get go, even if it's initially a PITA. I consider this random approach another way to fight off flakiness in specs.

Thanks fellas.

**Comment by andobolocco** [comment]
> I've seen this in many projects I worked on and although a good idea, it was inevitably disabled and abandoned. I'd wait for real customer-initiated request.

I got this case where we're running playwright tests in github actions, when multiple merges to master occur our full test suite starts to run. sometimes our staging backend server where these integrations are being run against gets overloaded, the tests start failing or timing out, and then each retry is also shadowed by the multiple merges being run in parallel.

having an easy way of randomizing the order of execution of tests targeted by a --project would be a very useful trick for us.

**Comment by JavierMoya954** [comment]
@pavelfeldman @mxschmitt I have a near identical scenario to andobolocco. Multiple PRs are automatically created which triggers multiple test-runs. The same tests run at the same time, the same API calls are made to the same database, and things slow down and time out. Randomizing the order of execution would easily solve this problem. 

"I'd wait for real customer-initiated request" it appears now you have multiple.

Also in [this thread,](https://github.com/microsoft/playwright/issues/9297#issuecomment-1231742487) someone suggested using random seeds so that the same order could be tested again, to address the issue of non-determinism.
