### ISSUE TITLE
[QUESTION] Is there a docker image for playwright-test?

### ISSUE THREAD

**Issue by vzakharchuk** [microsoft/playwright#7140]
it's not mentioned here: 
[https://mcrflowprodcentralus.data.mcr.microsoft.com/mcrprod/playwright?P1=1623758495&P2=1&P3=1&P4=mMT%2Fz0KCZ3OHPAvRacLcSkprfMMdDk%2F2ziqwy%2FFPbKA%3D&se=2021-06-15T12%3A01%3A35Z&sig=F6qlF1D086xD1aacwAdsHuybc6%2BN8BEws0CJ9yMBk00%3D&sp=r&sr=b&sv=2015-02-21](url)

I want to dockerize existing playwright tests with the new runner.

**Comment by mxschmitt** [comment]
Playwright-test is a NPM module. So you can create a package.json (`npm init -y`) and install Playwright-test with it (`npm install @playwright/test). Then you can run it inside the Docker container. See here: https://www.npmjs.com/package/@playwright/test

**Comment by vzakharchuk** [comment]
ok, got it, thank you!

Just to confirm my thoughts:
- I have tests written with playwright and playwright-test as a runner (both of the same specific versions). 
- wanna run them in a docker container with playwright.
- tests will be executed against browsers that are provided with this container. 
- if I want to run those tests against browsers of newer versions - will it be enough just to update the image version?

**Comment by mxschmitt** [comment]
- You don't need Playwright anymore, since Playwright is contained in @playwright/test.
- Tests are executed against the browsers in the container when the version matches. Otherwise it re-downloads them. For the Docker-tag naming scheme, see here: https://playwright.dev/docs/docker#pull-the-image
- When you want to use more recent versions, you need to update the version in the package.json of @playwright/test and ideally the Docker image tag.

**Comment by vzakharchuk** [comment]
Will try, thank you!
