### ISSUE TITLE
[Feature] Diff for Trace Viewer

### ISSUE THREAD

**Issue by NickTulett** [microsoft/playwright#7201]
When triaging bugs, it's useful to compare the current run against a known good one.
Give that Trace Viewer includes test steps, screenshots, DOM snapshots and Network activity, it would be hugely useful if any or all of this data could be compared between runs so changes can be quickly/automatically identified.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
