### ISSUE TITLE
[Question] How to share singleton class instance with test fixtures?

### ISSUE THREAD

**Issue by Tverous** [microsoft/playwright#7218]
Hi all,

I have a hash map that will store some info during the tests.
Then it will write the data into local storage in `globalTeardown()` after all the tests are finished.

If I want to access the object during the test, I have to extend the fixture:
``` javascript
import { test as baseTest } from "@playwright/test";

baseTest.extend<{map: CustomHashMap}>({
    map: new CustomHashMap(),
});
```

However, every time a new test start or a worker process init, a new instance will be generated.  
As a result, the object can not be shared between different tests or workers and write to local disk after all the tests.

Export the object doesn't work as well since there will be a new instance every time importing the module.

Does there a way to share a single global object with all test fixtures and worker process during the test?

It will be much appreciated if anyone can help.

Thanks.

**Comment by mxschmitt** [comment]
There are worker fixtures, which are created one time per worker. See [here](https://playwright.dev/docs/next/test-fixtures#worker-fixtures).

Out of curiosity, what are you storing inside this map?

**Comment by pavelfeldman** [comment]
As you say, there is no way to share a global object among all tests. The reason is that tests run in worker processes, which are operating system processes and are completely isolated. What kind of data would you like to share? The default recommendation is to build this data in each worker, either via beforeAll or via introducing a worker fixture. Alternatively, you can collect all global data in global setup, save it to file and load in each worker. But there will be no 'live' global object sharing between processes.

**Comment by Tverous** [comment]
Thanks for the answers.

I am using a hashmap to store the info from the frontend element during e2e tests, for instance, the traversed HTML tags and whether they triggered specified events or not.
Then the test will generate a report writing to local storage.
