### ISSUE TITLE
[Feature] Add custom message to expects

### ISSUE THREAD

**Issue by emakhachek** [microsoft/playwright#7256]
Besides the custom matchers it would be good to have a custom expect message:
`test("Test name", async () => {`
`expect(cardsCount, "Cards quantity on the page is not within 3 to 6 (exclude).").toBeWithin(3, 6);`
`})`
Currently I am using playwright + jest and [jest-expect-message](https://www.npmjs.com/package/jest-expect-message) gives an ability to do so.

**Comment by aslushnikov** [comment]
`jest-expect-message` is a jest plugin and relies on global scope poisoning, @playwright/test doesn't do any global scope poisoning, so these too don't play well together.

However, we can quite easy re-use the custom message functionality from the `jest-expect-message` with @playwright/test.

Typescript version:

```typescript
import {test} from '@playwright/test';
import withMessage from 'jest-expect-message/dist/withMessage.js';

// Get a new expect function with custom message
const expect = withMessage(test.expect);

test(`should work`, () => {
  expect(1, 'whoa not equal').toBe(3);
});
```

And JavaScript version:

```js
const {test} = require('@playwright/test');
const expect = require('jest-expect-message/dist/withMessage.js').default(test.expect);

test(`should work`, () => {
  expect(1, 'whoa not equal').toBe(2);
});
```

Would this work for you?

**Comment by emakhachek** [comment]
Great! Thank you.

**Comment by rbhaviri-spotnana** [comment]
Hi...using playwright with cucumber runner and this does not seem to work.
I'm receiving error like this, instead of the custom message
`Error: expect(received).toBeGreaterThanOrEqual(expected)
Expected: >= 1
Received:    0`
What am I missing? Or does it work only with playwright runner?
I see that others also face this issue: example [stackoverflow](https://stackoverflow.com/questions/76882428/custom-message-for-failed-assertion-in-playwright-using-cucumber-js) thread
