### ISSUE TITLE
[Feature] Add Download.cancel in Firefox and WebKit

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#7283]
Relates #7279
Relates #6236

**Comment by mxschmitt** [comment]
@starrify are you interested in collaborating to Playwright for adding Firefox and WebKit Download.cancel support?

**Comment by starrify** [comment]
Hi @mxschmitt, thanks for asking and the answer is surely a yes! :)

Initially I was waiting for the Chromium-only PR (#6236) to be merged for that contained some generic changes.
Since that happened, I have started looking into Firefox a few days ago (was rather unfamiliar with its implement before) and also the way Playwright applies its browser patches. I'm expecting to spend more time on that (major learning, though) however I'm unable to propose a promising timeline.
