### ISSUE TITLE
[BUG] loading iframe in Firefox bypasses service worker

### ISSUE THREAD

**Issue by jhiesey** [microsoft/playwright#7288]
**Context:**
- Playwright Version: 1.12.2
- Operating System: Mac
- Node.js version: 16.3.0
- Browser: Firefox

**Code Snippet**

```javascript
const { firefox } = require('playwright')

(async () => {
  const browser = await firefox.launch()

  const page = await browser.newPage({
    acceptDownloads: true
  })
  await page.goto('http://localhost:4000')

  // In our app, clicking this button creates an element like
  // <iframe hidden src="/download-stream/randomId"></iframe>
  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.click('text="Download file"')
  ])

  // Test never reaches here (times out)
})()

```

**Describe the bug**

In our app, we create an  `<iframe>` with `src` that should load from our page's service worker. (For a little context, the service worker sets the header `Content-Disposition: attachment; filename='file.jpg'` to trigger a download once the service worker sends the response.)

When Firefox is running in Playwright, the request for the iframe's `src` goes directly to our server instead of to the service worker. I confirmed that the service worker is registered by running Playwright in headed mode. If I create an `<img>` instead of `<iframe>` with the same src, it does load through the service worker.

Works:
* Chromium/Webkit/FIrefox running outside Playwright
* Chromium/Webkit running in Playwright

Doesn't work:
* Firefox running in Playwright

**Comment by jhiesey** [comment]
It should be possible to reproduce this behavior on the deployed version of our app: https://wormhole.app/

**Comment by aslushnikov** [comment]
I can reproduce: I uploaded file to wormhole and used it as download URL.

**Comment by aomarks** [comment]
I can also reproduce this with another project (https://github.com/google/playground-elements). Service Workers do not seem to function at all in Firefox when launched by Playwright.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by justinfagnani** [comment]
This is still an issue with the playground-elements. We're have to use Puppeteer for Firefox tests.
