### ISSUE TITLE
[Question] My test is over after that the expect() function is called

### ISSUE THREAD

**Issue by arkjel** [microsoft/playwright#7397]
Hi guys!
I have an issue with my test. When I run my test it is over and failed after the expect statement. I think it is related to the async await pattern but I cannot find the solution for that.

My function in the page object model:
```
async checkIfSideMenuIsClosed(selector: string) {
    expect(await this.page.isHidden(selector)).toBeTruthy();
  }
```

During the test I call this function but the test is over after that without any issue in the inspector. It is not the last command in my test but it is over for now.
![image](https://user-images.githubusercontent.com/13696203/123951722-6444e500-d9a5-11eb-91d9-04422512bd6e.png)

I see that the test gets failed but I don't understand why I got:
```
Error: expect(received).toBeTruthy()
```
![image](https://user-images.githubusercontent.com/13696203/123952694-a3c00100-d9a6-11eb-9782-511cdb54ce19.png)

Could you support me with that?

**Comment by pavelfeldman** [comment]
What you see is expected, but I understand how it looks confusing. Playwright Inspector is a low level tool, it debugs all the Playwright calls and helps you understand where things went wrong. In this case, `isHidden` worked just fine as far as inspector is concerned. It returned `false`, inspector does not know that you expect it to be `true`. Test runner saw the wrong value and told Playwright to capture a screenshot on failure and quit. This is exactly what you see in the log.

We'll leave this issue open to think about how we can make inspector expect-aware to avoid this confusion in the future.

**Comment by arkjel** [comment]
Ok, thanks for your answer! In the other hand, could you help me with that test? I get the error message but I don't know how to fix the test using `async/await` pattern. What do I do wrong in my test?

**Comment by JoelEinbinder** [comment]
I don't think your test has anything to do with async await, you seem to be using it fine.

The side menu isn't closed by the time you call `checkIfSideMenuIsClosed`. Instead of asserting that the selector is hidden, perhaps you want to [wait for it to be hidden](https://playwright.dev/docs/api/class-page#page-wait-for-selector):
```ts
await page.waitForSelector(selector, { state: 'hidden' });
```

**Comment by arkjel** [comment]
Thanks @JoelEinbinder for your tip but it doesn't resolve my issue. I would like to check that the side menu is closed. I used your method in my custom function but I still get the error.

My function:
```
async checkIfSideMenuIsClosed() {
    await this.page.waitForSelector(indexSelectors.sideMenuDrawerContainer, {
      state: "hidden",
    });
    expect(
      await this.page.isHidden(
        dataTestId(indexSelectors.sideMenuDrawerContainer)
      )
    ).toBeTruthy();
  }
```
Result:
![image](https://user-images.githubusercontent.com/13696203/123998851-2dd18f00-d9d2-11eb-9213-7837083d6709.png)

**Comment by pavelfeldman** [comment]
Note that you call `indexSelectors.sideMenuDrawerContainer` in one place and `dataTestId(indexSelectors.sideMenuDrawerContainer)` in another place. Also, you should not need the expect one since you've already awaited it to be hidden.

Since the original issue of 'test is over when expect is called' is now resolved / explained, could you file a new issue for this new inexplicable behavior if me hint does not help?
