### ISSUE TITLE
[Question] How to prevent test exit on page error ?

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#7458]
How to prevent test exit on page error?

```javascript
test('my test', async ({ page }) => {
    await page.goto('https://playwright.dev/');

    // Expect a title "to contain" a substring.
    expect(await page.title()).toContain('Playwright1');

    // Expect an attribute "to be strictly equal" to the value.
    expect(await page.getAttribute('text=Get Started', 'href')).toBe('/docs/intro');

    // Expect an element "to be visible".
    expect(await page.isVisible('text=Learn more')).toBeTruthy();

    await page.click('text=Get Started');
    // Expect some text to be visible on the page.
    expect(await page.waitForSelector('text=System requirements')).toBeTruthy();

    // Compare screenshot with a stored reference.
    //expect(await page.screenshot()).toMatchSnapshot('get-started.png');
});
```

In the sample code, after the test failed here, I would like to continue the test execution.
```javascript
    expect(await page.title()).toContain('Playwright1');
```

It becomes difficult in large enterprise e2e testing, where Playwright exit the test case because one assertion failed.

I have 10 assertions in a test case, just because the first assertion failed, the remaining 10 assertions are not validated.

I have 1000+ test cases and it's difficult to organize the test cases. Migrating from Protractor.

Looking for a flag to turn on / off in the Playwright configuration to exit or continue on page error.

Appreciate if you could provide me a solution for this as this issue is blocking me from running e2e test scenarios.

**Comment by pavelfeldman** [comment]
What did your protractor test look like?

**Comment by vsravuri** [comment]
Here is how it looks with Protractor.

```javascript
        expect('a').toEqual('b');
        expect('a').toEqual('a');
        expect('b').toEqual('b');
        expect('c').toEqual('b');
        expect('1').toEqual('2');
        expect('3').toEqual('3');
```

```javascript
  - Expected 'a' to equal 'b'.
  - Expected 'c' to equal 'b'.
  - Expected '1' to equal '2'.
```

I use Protractor with Jasmine.

**Comment by pavelfeldman** [comment]
I see. I guess because of the unusual control flow in Protractor, it adjusted the default Jasmine behaviour to not throw. Playwright is running your script like a regular program, no control flow magic. So our expect throws as everyone else's.

For your pattern, as a workaround, you could  compute several values `a, b, c, d` and then compare them to golden values all at once like this:
```js
expect({ a, b, c, d }).toEqual({
  a: 'avalue',
  b: 'bvalue',
    ...
});
```

**Comment by vsravuri** [comment]
Thanks for your time looking into this. I understand Playwright is doing what a normal program would do.

Appreciate if you could review these two use cases.

**Case -1
========**
What would be the expectation in this test case if the page title assertion fails? Playwright runner will stop further execution and exit the test case with error? This is how it's working today.

    expect(await page.title()).toContain('Playwright1');

```javascript
test('my test', async ({ page }) => {
    await page.goto('https://playwright.dev/');

    // Expect a title "to contain" a substring.
    expect(await page.title()).toContain('Playwright1');

    // Expect an attribute "to be strictly equal" to the value.
    expect(await page.getAttribute('text=Get Started', 'href')).toBe('/docs/intro');

    // Expect an element "to be visible".
    expect(await page.isVisible('text=Learn more')).toBeTruthy();

    await page.click('text=Get Started');
    // Expect some text to be visible on the page.
    expect(await page.waitForSelector('text=System requirements')).toBeTruthy();

    // Compare screenshot with a stored reference.
    //expect(await page.screenshot()).toMatchSnapshot('get-started.png');
});
```

**Case -2
========**
Test Case -1 - Authenticate application
Test Case -2 - Create new user (here assertion failed due to incorrect label displayed in UI, Playwright test runner stop further execution, user is not created)
Test Case -3 - Do something with new user....

Test Case -2 blocks further execution of flow because user is not created

If this is the intended behavior of Playwright test runner, then every failed assertion has to be fixed in order to run the complete 2e2 test cases (if there is dependency between test cases).

**Comment by pavelfeldman** [comment]
> Case -1 What would be the expectation in this test case if the page title assertion fails? Playwright runner will stop further execution and exit the test case with error? This is how it's working today.

Yes, when `expect` condition is not met,  it throws an exception. We aren't unusual here, same happens in all the test runners, including Jest, Jasmine, Mocha, etc. So if you want runner to tolerate some of the assertions and report them in bulk when the test ends, you would need to fight this expect paradigm via wrapping expect with try/catch or substituting expect with your own version that defers error reporting until the end of the test.

> Case -2

Playwright does not tolerate dependencies between the test cases, it endorses complete test isolation. The rationale is that if one test fails, it should not affect other tests. In your use case, a dedicated test would be checking the label in the UI when user is created. It would fail if and only if that label is wrong. Created user would not be used in another test.

Test isolation is always good and the only downside of this isolation is that each test that needs a new user would be creating one, hence putting more pressure on the system. For that, we allow capturing the persistent state of the context so that it could be loaded in a subsequent test. Basically you log in once, you capture that logged in state and then each test gets its independent copy of that state. Obviously your backend needs to be ready to this kind of operation. [More details here](https://playwright.dev/docs/auth#reuse-authentication-in-playwright-test).

**Comment by mostor-v** [comment]
For example you can use https://www.npmjs.com/package/soft-assert  for soft assertions

**Comment by vsravuri** [comment]
Thanks!

I will try the library.

**Comment by pavelfeldman** [comment]
Closing as per above!

**Comment by JorensM** [comment]
Personally I have tests where I run loops with independent `expect`s in them, for example when I want to check each page of my website. In such cases they are independent and I think it would make more sense to not stop the test when an `expect` fails, because otherwise I have to rerun the test each time, as opposed to just getting all the necessary information in a single test.

My proposal would be to add an option like `stopTestOnFail` that would determine whether the `expect` should stop the test or not.
