### ISSUE TITLE
Single browser-level video recording that includes all tabs

### ISSUE THREAD

**Issue by ajssd** [microsoft/playwright#7459]
While testing our web app using Playwright, we open and close tabs repeatedly.  This produces many video recording files, each with random non-sequential names.  This makes it very hard to use the recordings.  

What would be better is if the recording was at the overall *browser* level, rather than at the page/tab level.  In other words, produce a single recording that shows the browser "window" just as the use would see it.  This would significantly improve the usefulness of the video recording feature.

**Comment by mxschmitt** [comment]
Are you using the [official test-runner](https://playwright.dev/docs/test-intro)? Each test should have its own recording because we apply best practises to make each test isolated from each other and have by that a new context for each test. See [here](https://playwright.dev/docs/next/test-configuration) with `video: 'on'` which should result in having a folder for each test with the test name and the recording in it.

What is your use-case for having the recordings? Are you using them to debug failing or flaky tests?

**Comment by ajssd** [comment]
No, we are not using the PW runner. We are using mocha as the test runner. Which means we are initiating the recording in the browserContext.  In that scenario, is there a way to get one recording per test?  I guess we would have to instantiate the browserContext at the start of each test?  And what about if the test involves a new browser tab?  Thanks for the assistance.

**Comment by mxschmitt** [comment]
I see two solutions there for your problem.

a) use a single context and page for all your test
- not recommended, since tests are not isolated
- might end up in a very big file

b) have a context per test
- this enforces test isolation which is great
- there you can call page.video().saveAs("foo.webm") while closing the context at the end of your test. See the following ressources
  - https://playwright.dev/docs/videos
  - https://playwright.dev/docs/api/class-video
  - https://playwright.dev/docs/api/class-page#page-video

This is unfortunately a test-runner problem. Using Playwright Test would do this for you out of the box.

**Comment by pavelfeldman** [comment]
You request is clear, collecting votes.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
