### ISSUE TITLE
[Question] Why do we get a UUID/GUID as file name when downloading a file?

### ISSUE THREAD

**Issue by calebepaglioza** [microsoft/playwright#7464]
Hello,

When using the Download class, the downloaded file doesn't keep its original name. Instead the original file name is converted into a hash/UUID/GUID like this: `f6746de9-95f6-4c06-b636-3ac7c2fb73bc`

Is it supposed to be like this? If so, why?
Can't see any reference for that behaviour in the documentation [here](https://playwright.dev/docs/api/class-download).

In this given test suite a "download test" would be followed by an "upload test" which requires the file to keep the original name. We can use `download.suggestedFilename()` to solve that, but it would be interesting to understand why the file is renamed.

Here's the code snippet of what we currently do:

```
it('imports a profile', async () => {
    await addProfile('import_profile_test');
    await page.click('"import_profile_test"');
    await page.click('"Actions"');
    const [download] = await Promise.all([
      page.waitForEvent('download'),
      page.click('[label="Export"]'),
    ]);
    await removeSelectedProfile();
    const downloadPath = await download.path();

    if (downloadPath) await fsp.rename(downloadPath, `${downloadPath}.yaml`);

    page.on('filechooser', async (fileChooser) => {
      await fileChooser.setFiles(`${downloadPath}.yaml`);
    });
    await page.click('"Import profile"');
    await expect(page).toHaveSelector('"Profile imported successfully"');
    await page.click('"import_profile_test"');
    await removeSelectedProfile();
  });
```

We're using Playwright v1.12.3.

![image](https://user-images.githubusercontent.com/6879705/124471588-52948080-dd9d-11eb-99c0-0b4087ce94b8.png)

Thanks in advance!

Kind regards,
Calebe

**Comment by yury-s** [comment]
> When using the Download class, the downloaded file doesn't keep its original name. Instead the original file name is converted into a hash/UUID/GUID like this: `f6746de9-95f6-4c06-b636-3ac7c2fb73bc`
> 
> Is it supposed to be like this? If so, why?
> Can't see any reference for that behaviour in the documentation [here](https://playwright.dev/docs/api/class-download).

This is expected behavior. We pick unique name for each file in the downloads directory (note that same file can be downloaded multiple times and it would have to have a unique name every time, with GUIDs this problem is solved automatically), moreover the actual download [path](https://playwright.dev/docs/api/class-download#download-path) is not accessible in case of a remote connection. It's up to Playwright how to name downloaded files, you can call [`saveAs`](https://playwright.dev/docs/api/class-download#download-save-as) to create a copy with desired name or use [`createInputStream`](https://playwright.dev/docs/api/class-download#download-create-read-stream) to just get the downloaded content. I guess in your scenario the problem is that the file name doesn't have certain extension, so yes you need to manually create a file with the desired name or use [`setFiles`](https://playwright.dev/docs/api/class-filechooser#file-chooser-set-files) version that takes name and buffer.

**Comment by calebepaglioza** [comment]
Thanks for clarifying, @yury-s.
Wouldn't that be valid to include in the documentation the expected file name when downloading a file?

Thanks,
Calebe
