### ISSUE TITLE
[BUG] Dragging the slider is not recorded

### ISSUE THREAD

**Issue by 000xiaoxiao000** [microsoft/playwright#7472]
playwright version 1.12.1 
playwright codegen URL

You need to hold the mouse down to move the slider. This action cannot be recorded while recording.

**Comment by 000xiaoxiao000** [comment]
> What kind of slider do you mean, like a [`<input type="range" />`](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_rangeslider)?
> 
> A URL with your slider would be helpful.

Is <div ...>, may also be a Vue control.

**Comment by jayson-labarrete** [comment]
Hi @mxschmitt , 
I have a similar problem, I think. 

This is how my slider looks like 
![image](https://user-images.githubusercontent.com/92701239/140857925-49b94870-9b48-4d02-afba-50d4a49db872.png)

This is its code

![image](https://user-images.githubusercontent.com/92701239/140857895-e68eefe9-ab0f-4129-a2a2-8f2760c6382b.png)

**Comment by ddemoss222** [comment]
I am also having issues with dragAndDrop. Following along stepwise at the debugger, the mouse click actions appears to happen at the source element and it moves to the target element location, but no dragging or dropping happens. Are there known workarounds to better capture this event? I have tried await page.waitForLoadState('networkidle'), so I believe the element would be "ready" for this event. Are there known situations where elements would not recognize the click and drag via playwright?

**Comment by yjbdsky** [comment]
+1

**Comment by tsvetkovamaria** [comment]
Also tried using codegen to capture drag and drop, it doesn't work on any of the places I've tried. 

An example can be run on https://jqueryui.com/droppable/ to verify drag and drop is not recorded, and on https://jqueryui.com/slider/ to verify that slider dragging is not recoded either.

**Comment by NikkTod** [comment]
+1

**Comment by asvignesh-qae** [comment]
+1

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
