### ISSUE TITLE
[Question]: playwriter-jest-import module 

### ISSUE THREAD

**Issue by ViaMay** [microsoft/playwright#7499]
### Your question

I used this project https://github.com/playwright-community/jest-playwright for start my tests. But I have a problem.

I want to use Import and Export (https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_modules_ecmascript_modules) for my code. 
I can’t understand it is possible to configure its or you don’t support it yet?

**Comment by mxschmitt** [comment]
I would recommend opening an issue on [their](https://github.com/playwright-community/jest-playwright) repository, since this is something which needs to to get implemented on the jest plugin preset level.

You can also instead use the [official test-runner](https://playwright.dev/docs/test-intro), which works in the `npm i -D next@playwright` version (or wait until 1.14) with ESM files when the `.mjs` extension is used.

**Comment by ViaMay** [comment]
Thanks!
