### ISSUE TITLE
[Feature]: Electron app change viewport: app width and height

### ISSUE THREAD

**Issue by sytolk** [microsoft/playwright#7557]
### Feature request

I have successful change app initial browser window size for web app like:
```
const app = await chromium.launch();

const context = await app.newContext({
        viewport: { width: 1920, height: 1080 }
      });

const page = await context.newPage();
```
but this not work on [Electron](https://playwright.dev/docs/api/class-electron/) and there is no options for this in doc. I have try with command line arguments like this but without success:
```
const { _electron: electron } = require('playwright');
    // Launch Electron app.
    const app = await electron.launch({
      args: [pathLib.join(__dirname, '..', '..', 'app', 'main.prod.js'), '--window-size=1280,1024']  // '-width=1280', '-height=1024'
    });

    // Get the first window that the app opens, wait if necessary.
   const page = await app.firstWindow();
```

**Comment by andreabisello** [comment]
@sytolk have you found a way to set the screen size?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
