### ISSUE TITLE
[Question]: Does 'await context.close();' prevents taking a screenshot?

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#7700]
### Your question

I take the screenshot at the end of the test. I use the 'screenshot' option in the 'playwright.config.ts':

![image](https://user-images.githubusercontent.com/52656401/126060401-c773ddaf-9e38-4cf8-9809-b8be9c43c6f6.png)

In the fixture test.afterEach(), I've used the command 'await context.close();' in order to clean the context and clean the memory. But using this command - prevents taking screenshots.

![image](https://user-images.githubusercontent.com/52656401/126060522-e1d9bd8a-95e7-4a39-b3a0-a341dec614da.png)

If I put a comment on this command - the screenshots are stored as well.

![image](https://user-images.githubusercontent.com/52656401/126060510-6a7e340b-fa83-4b66-afb4-6c9f36c86ede.png)

Does it a normal behavior?

**Comment by mxschmitt** [comment]
Yes this is expected. With Playwright Test you should not close the context manually since its done internally by default after each test. Also clearCookies is not necessary, since you will receive a new fresh context in each test. For tracing we recommend to use the [Playwright Test option](https://playwright.dev/docs/test-configuration) instead of doing it manually.

Did you experience memory issues? Since you mentioned it.

**Comment by AlexKomanov** [comment]
@mxschmitt 
No, I didn't. Just thought that it is necessary.

Thanks for the quick answer.

Since you mentioned internally closing - does it the same behavior for the browser closing - does the runner closes internally all instances of the browser/s?

**Comment by mxschmitt** [comment]
Yes Playwright Test will handle that as well for you.

**Comment by AlexKomanov** [comment]
@mxschmitt 
Thanks a lot!!! You can close. I got all information!
