### ISSUE TITLE
[Bug]: Can not get baseURL to work in playwright.config

### ISSUE THREAD

**Issue by Romeodewit** [microsoft/playwright#7815]
### Playwright version

1.13.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

Trying to get baseURL set up in the playwright config file but it just doesn't seem to find it.
I've just updated to 1.13.0. Here's some snapshots.
![error message](https://user-images.githubusercontent.com/68374567/126774874-fcdcee31-94b3-4430-9ba8-7ef64fcc30df.PNG)
![help 2](https://user-images.githubusercontent.com/68374567/126774875-0490cd52-8d0d-470a-8e2f-e1fe6b2bc86f.PNG)
![help 3](https://user-images.githubusercontent.com/68374567/126774876-6c9fd4cf-ff37-4251-87ad-2521c982c121.PNG)
![help](https://user-images.githubusercontent.com/68374567/126774877-3696b1a7-612e-4a1e-838c-51c01cb0945b.PNG)

Am I doing something wrong here?

**Comment by mxschmitt** [comment]
Its failing because you are creating your context and page yourself instead of using the context and page provided via the fixtures. This then does not reflect the options which you pass over the CLI or via the Playwright Test configuration. (see [here](https://playwright.dev/docs/api/class-fixtures/) about the fixtures.

**Comment by dgozman** [comment]
Fixed by #8083.
