### ISSUE TITLE
[Question]: How to reliably wait for network call to complete

### ISSUE THREAD

**Issue by macroking** [microsoft/playwright#7823]
### Your question

OS: Windows
@Playwright/test Version: 1.13.0

There is a input field which is using [select2](https://select2.org] to let the user enters a few character and filters/searches the relevant result by sending an API request.

When the user adds new character,  the previous network gets automatically cancelled and a new request will be sent.

What I come up with is not working reliably

```javascript
page.type('#examplefield', {delay:500});

page.waitForSelector(':nth-match(li.ui-select-row,1)');
```
Note: I am converting existing protractor tests to Playwright. Protractor waits for all the network request to complete before moving forward.

**Comment by henrydzung** [comment]
Have you tried [`page.waitForLoadState('networkidle')`](https://playwright.dev/docs/api/class-page#page-wait-for-load-state)? 
It also waits until there are no network connections.

**Comment by dgozman** [comment]
Here is the documentation: https://playwright.dev/docs/network#network-events.

You'd usually use `Promise.all` to wrap the action and waiting for network together:
```js
const [response] = await Promise.all([
  page.waitForResponse('**/api/fetch_data'),
  page.fill('#examplefield'),
]);
```

Also note that `page.fill` is usually better because it fills the input in a single go (like a copy+paste operation would do), so you probably won't get many network requests that are hard to track and wait for.

Does this help?

**Comment by mxschmitt** [comment]
Closing since the issue seems stale and answered. Please reopen/create a new issue if you still encounter issues.
