### ISSUE TITLE
[Feature]: extend expect assertions

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#7835]
### Feature request

Locators:
- [x] toHaveAttr(name, [value])
- [x] toHaveProp(name, [value])
- [x] toHaveCSS(name, [value])
- [x] toHaveData(name, [value])
- [x] toHaveClass(className)
- [x] toHaveId(id)
- [x] toHaveText(text)
- [x] toHaveValue(value)
- [x] toHaveLength(value)
- [x] toContainText(text)
- [x] toBeVisible
- [x] toBeHidden
- [x] toBeSelected
- [x] toBeChecked
- [x] toBeFocused
- [x] toBeEditable
- [x] toBeEnabled
- [x] toBeDisabled
- [x] toBeEmpty
- [ ] toMatchSnapshot

Page / Frame:
- [x] toHaveTitle
- [x] toHaveURL

**Comment by mskelton** [comment]
Many of these matchers are available in the community library [expect-playwright](https://github.com/playwright-community/expect-playwright) that @mxschmitt created and I have helped to continue to improve.  A few thoughts or questions regarding this proposal:

1. It looks like these matchers only work on element handles.  One of the really beneficial features of expect-playwright is that the matchers work with element handles, page + selector, and iframes which are automatically resolved if given an element handle that points to an iframe.
2. Will the value that is compared support regex?  In expect-playwright we made the matchers to do a full string comparison when passing a string and a regex comparison when passing a regex.  For example `expect(locator).toHaveAttr('src', /http.+/)`.
3. We also automatically resolve promises that are passed to the `expect` function removing the double await in certain scenarios like this:
   ```js
   // before
   await expect(await todoPage.button()).toBeChecked()

   // after 
   await expect(todoPage.button()).toBeChecked()
   ```

All of these features feel higher level that the Playwright API tends to be, which makes me wonder if matchers like this should remain in user land rather than the core.  Thoughts?

**Comment by pavelfeldman** [comment]
Thank you for your feedback.

1. This api is built around [locators](https://playwright.dev/docs/next/api/class-locator), we will consider supporting the ElementHandles, but the idea is to steer away users from using ElementHandles for testing, ever.

2. So far I landed toHaveText and toMatchText for exact and substring/regex matching. We'll see how it feels and either leave both or merge regex support into toHaveText.

3. Locators don't have that problem

Yes, Playwright API remains lower level. These features will not be a part of the Playwright Library API, they are a part of the Playwright Test Runner.

**Comment by mskelton** [comment]
@pavelfeldman Thanks for the info.  Using locators makes sense as you mentioned since it removes a lot of the pains of element handles and await chains.  Also, the idea the you can get a locator and then call `elementHandle`, `nth`, etc is really smart, so great work on the locators API!

The one thing that I am curious about with locators is the ability to retrieve the underlying selector.  For example, if I have a test like this which uses a locator (realistically it would be from a page object), interacts with the item, then waits for the element to appear/disappear using the `toHaveSelector` matcher from expect-playwright.  Locators would work great for this, but one would need to access the underlying selector from the locator.

```js
test('', async ({ page }) => {
  const item = page.locator('#todo-item')
  await item.click()
  await expect(page).not.toHaveSelector(item.selector) // imaginary code here
})
```

Curious to hear your thoughts around these type of use cases and how they would work with locators.

**Comment by mskelton** [comment]
So, thinking more about it, I'm realizing that `toHaveSelector` is covered by `toBeVisible` and `toBeHidden` in the list of matchers, so disregard my last comment 🙂

**Comment by pavelfeldman** [comment]
Considering this one Done!
