### ISSUE TITLE
[Question]: Difference between jest-playwright.config.ts and playwright.config.ts

### ISSUE THREAD

**Issue by ssachdevatwist** [microsoft/playwright#7852]
### Your question

As a new user to the playwright,  I want to understand the difference between jest-playwright.config.ts and playwright.config.ts

Are both of them necessary? Also, there are few options that are common to both. For example

In playwright.config.ts browserName is similar to  [browsers] in jest-playwright.config.

Which one overrides the other?

**Comment by mxschmitt** [comment]
`playwright.config.{ts,js}` is for [Playwright Test](https://playwright.dev/docs/intro), a custom built test-runner from scratch by the Playwright team which is optimised for Playwright. (It does **not** use Jest under the hood).

`jest-playwright.config.js` is for [jest-playwright](https://github.com/playwright-community/jest-playwright) a Jest preset to bring Playwright support to Jest.

Only one is necessary, depends which solution you want to use, we would recommend Playwright Test, since it brings a lot of features of Playwright out of the box, including trace-viewer support, screenshot on-failure, video support, context isolation etc.

**Comment by ssachdevatwist** [comment]
Thanks @mxschmitt for your reply. Playwright Test seems to be full of features.
