### ISSUE TITLE
[Question]: WebGL with Firefox Headless

### ISSUE THREAD

**Issue by herecy** [microsoft/playwright#7889]
### Your question

It seems like there is still no support for WebGL when running Firefox headless. The proposed fix at [https://github.com/microsoft/playwright/pull/4358](https://github.com/microsoft/playwright/pull/4358) seems no longer applicable, the current WebGLContext.cpp does not seem to have the mentioned check any more.

Is there any way to enable it?

Thanks in advance.

**Comment by JoelEinbinder** [comment]
There's been some movement on the firefox bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1375585#c27

I am hesitant to fix it in our fork for fear of diverging too much with upstream. And I am not knowledgable enough to fix it upstream in in Firefox.

Linking #1032 which was closed due to not enough demand.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
