### ISSUE TITLE
[Feature]: make `page` available in `test.beforeAll`

### ISSUE THREAD

**Issue by kshrestha99** [microsoft/playwright#7934]
### Feature request

Currently `page` is available in `test`, `test.beforeEach`, etc but it is not in `test.beforeAll`. This is making us have to do `await page.goto(URL) in every single test in a spec file. So each of our spec file ends up having to open a browser, navigate to URL and login multiple times. Is this request possible?
Thank you

**Comment by radekBednarik** [comment]
@kshrestha99 hi, `page` is actually a fixture with test scope.  That is why you cannot use it in beforeAll() hook.

https://playwright.dev/docs/intro#test-fixtures

What you can do, is write your own page fixture with worker scope. Such fixture will be usable in beforeAll() hook and also test() function.

**Comment by kshrestha99** [comment]
is there an example of a simple custom page fixture in the playwright config file and how it is used in beforeAll() hook in the test file?

**Comment by radekBednarik** [comment]
@kshrestha99 your own worker page fixture can be written like this https://github.com/microsoft/playwright/issues/7881#issuecomment-888799627

Custom fixture is then used in test() like any other standard fixture, eg page or  context. 

Also, maybe it is possible to just override existing `page` fixture by adding worker scope, in the spirit shown here, but this I did not try https://playwright.dev/docs/test-fixtures#overriding-fixtures

Also, generally, I would recommend to read thru the examples shown here https://playwright.dev/docs/test-fixtures, and here https://playwright.dev/docs/intro#test-fixtures

**Comment by mxschmitt** [comment]
As already mentioned, overwriting the `page` fixture and keep it as base fixtures which you use everywhere makes probably the most sense. See: https://playwright.dev/docs/test-fixtures#overriding-fixtures

You can also create a new fixture for it to have the flexibility afterwards to have certain tests which are not on the specific site.

In your case, since you are mentioning login, a login fixture is probably also handy to get logged in in every test automatically. See [here](https://playwright.dev/docs/test-fixtures/#test-fixtures).

**Comment by kshrestha99** [comment]
@mxschmitt and @radekBednarik Thank you guys, this was very helpful and I really like what the fixtures allow me to do. Fantastic!
