### ISSUE TITLE
[Question]:How to run 1 test file with multiple workers.

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#7957]
### Your question

How to run one spec file with multiple workers.
`My Config file`:

```ts
import { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
    timeout: 120000000,
    globalTimeout: 12000000,
    maxFailures: 0,
    use: {
        headless: false,
        browserName: "chromium",
        //channel: "chrome",
        screenshot: "only-on-failure",
        video: "on",
        trace: 'on',
    },
    workers: 20,
    testMatch: [
        "login.test.ts",
        // "trace.test.ts",
        // 'loginWithoutFixture.test.ts',
        // 'category.test.ts'
    ],
    retries: 1,
    //grep: [new RegExp("@smoke"), new RegExp("@slow"), new RegExp("@fast"), new RegExp("@reg"), new RegExp('@sanity')],
    reporter: [["line"], ["json", { outputFile: "test-result.json" }],
    ['experimental-allure-playwright']],
}
```

**Comment by Lakshmi-Yaswanth** [comment]
When iam running.I can only see 1 worker is processing.I can able to test 20 workers for same login.test.ts.
Please help me whether Tam doing any mistake. Thank u in advance.

**Comment by mxschmitt** [comment]
A worker processes only a whole file at a time. So having multiple tests inside a single file does not end up getting processed on multiple workers. You need to split the tests in multiple files as well.

**Comment by Lakshmi-Yaswanth** [comment]
If we want to do load test for only 1 page such as Login page. I want 20 users to work on login page. How can i achieve this using playwright.
can u help me on this.

**Comment by mxschmitt** [comment]
Then this is not something for Playwright Test - there are alternative load testing tools available. In general running 20 browser contexts at the same time, would mean that you should have in the ideal world 20 CPU cores available -> big machine.

So it would be better if you would scale the machines/pods instead. Maybe even testing the API only would make more sense, but not sure. Since then the CPU/memory consumption is not high.
