### ISSUE TITLE
[Feature]: Add explicit EXECUTABLE_PATH environment variables

### ISSUE THREAD

**Issue by braderhart** [microsoft/playwright#7960]
### Feature request

# Problem

Currently, PLAYWRIGHT_BROWSERS_PATH only points to the top-level directory. I would like to have explicit environment variables for the actual path. Puppeteer already supports this:

https://developers.google.com/web/tools/puppeteer/troubleshooting#running_on_alpine

# Proposal
Add `EXECUTABLE_PATH` environment variables for each browser and ensure they work with the [CLI](https://playwright.dev/docs/cli):
- `PLAYWRIGHT_FIREFOX_EXECUTABLE_PATH` (e.g. `PLAYWRIGHT_FIREFOX_EXECUTABLE_PATH=/usr/bin/firefox`)
- `PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH` (e.g. `PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/bin/chromium`)
- `PLAYWRIGHT_WEBKIT_EXECUTABLE_PATH` (e.g. `PLAYWRIGHT_WEBKIT_EXECUTABLE_PATH=/usr/bin/qutebrowser`)
  - > Just an example, not sure if this would actually work.

## If an open source Edge browser is ever released
- `PLAYWRIGHT_EDGE_EXECUTABLE_PATH` (e.g. `PLAYWRIGHT_EDGE_EXECUTABLE_PATH=/usr/bin/microsoft-edge`

**Comment by mxschmitt** [comment]
It's not supported to use the normal Firefox or qtbrowser with Playwright. Only Chromium browsers can be easily switched by "branded ones", see [here](https://playwright.dev/docs/browsers) by using the channels feature when launching the browser.

When you mentioned the CLI, are you interested there in the codegen feature or what exactly do you mean?

**Comment by braderhart** [comment]
@mxschmitt I think not supported here means "use at your own risk" though, not that it can't work? The only exception may be `qutebrowser` as I'm not familiar with what WebKit browsers enable headless support that would be compatible.

I believe the distro-installed Firefox would still work, unless the bundled driver adds features. I am primarily interested in screenshots from the CLI at the moment. I'm just looking for some way to set the executable path from an environment variable to test various commands in an Alpine container using the distro chromium package (again I realize this is "use at your own risk" and will only have limited use unless I add a display server):

https://hub.docker.com/r/equalos/playwright

I am familiar with the `Codegen with custom setup` here, however that example appears to circumvent the CLI entirely:

https://playwright.dev/docs/cli#codegen-with-custom-setup

I think there is some benefit to adding this, even if it is just for testing at the moment... and again, this is something that Puppeteer already supports to some degree.

**Comment by mxschmitt** [comment]
No, it can't work since we have modified browsers which provide custom APIs to interact with them. See [here](https://github.com/microsoft/playwright/tree/master/browser_patches). Only Chromium based browsers can be easily switched.

When making screenshots over the CLI, you can use the `--channel` parameter to specify e.g. Google Chrome or Microsoft Edge. If you want to have there support for Chromium so it picks up an apt installed Chromium e.g., let us know (separate feature request).

What is the reason that using our Chromium does not work for you?

Also it might make sense for your use-case to create a custom script which you run inside, then you can specify everything manually for your own needs:

https://github.com/microsoft/playwright/blob/600d82b17cabacb798898feb0e3c826bbfabd888/src/cli/cli.ts#L463-L471

**Comment by braderhart** [comment]
I can see that there are some changes there.

> What is the reason that using our Chromium does not work for you?

In my example I'm using Alpine Linux which uses the `musl` standard library:

https://playwright.dev/docs/docker#alpine

---
The reason is I want to test on Alpine Linux is because the difference in image size is over 1.5GB between `mcr.microsoft.com/playwright:latest` and `equalos/playwright:alpine`. I guess a request could be made to create builds for distros using `musl` but it seemed more logical to go the other route. I am open-minded to a separate feature request to pick up the distro installed packages from the CLI, whereas if I wanted to add support for Firefox then I'd need to create a distro package with the patches used in the bundled package. However, ideally I'd like the option to set this from an environment variable as well.

**Comment by pavelfeldman** [comment]
You can use one of the two ways to achieve it:
- https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-channel
- https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-executable-path

All you need is to read your own env variable and use it in place of `executablePath`.

**Comment by braderhart** [comment]
@pavelfeldman Thank you, but as noted this will not work with the CLI which is what I am primarily trying to test at the moment.

**Comment by mxschmitt** [comment]
Since your use-case is highly specific and making screenshots is not complex we would recommend to create an own script. Why does this not work for you?

See here about creating screenshots:https://playwright.dev/docs/screenshots

**Comment by mxschmitt** [comment]
codegen can't work, since it will run a browser inside your Docker container which the user can't control. Codegen is about to generate code from a browser with which the user will interact with. PDF is a fair point but its the same as screenshot, calling a method on the page instance. Since you mentioned a remote desktop client, then I would doubt that it results in a lightweight image and it runs on alpine out of the box.

Your comparison about speed is not really fair, since our Docker image contains all the necessary dependencies to run Chromium, Firefox, WebKit, a lot of fonts etc. and including the browser binaries. Usually the image is cached on some caching layer, e.g. your local machine or a CDN.

As we said you can use Alpine with Playwright right now, use the `executablePath` or `channels` and it will work for Chromium. For WebKit and Firefox it can't work and we unlikely provide support for that in the near future.

**Comment by braderhart** [comment]
@mxschmitt It doesn't sound like you will end up adding support, but I would like to mention that codegen would work with a remote desktop client and there are several lightweight Wayland display/kiosk managers, wayvnc, neatvnc, and novnc. This would add minimal size to the image. Even with Firefox, although you are doing some patches, if it were recompiled for `musl`, it would probably only add maybe 120MB to the image.

Thank you for creating the additional request and maybe this will be something to revisit in the future.

**Comment by pavelfeldman** [comment]
I think multiple things are being discussed here. For the original request for the executable path env, the response is to use the `executablePath: process.env.MY_EXECUTABLE_PATH` in your code. This effectively works around this request in full.

But it looks like there are remaining things that you want supported, and for those, could you file separate issues?

**Comment by braderhart** [comment]
@pavelfeldman Having an environment variable to specify browser executable path(s) is the only thing I was asking for, specifically in my interest for the CLI, but the solution you propose does not solve the issue since I can't use the CLI then. #7983 may help, but it seems like like auto-detecting will be more error prone. Regardless, I have to work with what I am given here.

**Comment by mxschmitt** [comment]
Since it's only about PDF and screenshot we recommend to create an own small script, this would work on Alpine but has no official support.

Closing since there is no action item and Alpine is not on our roadmap.
