### ISSUE TITLE
[Question]: How to resolve this error Argument of type 'ElementHandle<SVGElement | HTMLElement>' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#8040]
### Your question

Here is my code:
```
 protected async click(ele: string) {
    await this.page.waitForSelector(ele);
    await Promise.all([
      this.page.waitForNavigation(),
      this.page.click(ele)
    ]);
  }
```
```
async selectDropdownbyValue(suggesestionDivID, visibleText) {
    let ele = await this.page.$(
      `//*[@id='${suggesestionDivID}']//*[contains(text(),'${visibleText.trim()}')]`
    );
    this.click(ele)
  }
```
In this.click(ele)  here iam getting the error. how to clear it. please can u give work around for this.
Thank u in advance.

**Comment by mxschmitt** [comment]
`this.page.$` returns a `ElementHandle` and `page.click` excepts a `string`. `ElementHandle` != `string`. We would recommend to use `page.click` directly, because there you don't need to wait manually for the element via `waitForSelector`. 

Reference:
- https://playwright.dev/docs/api/class-page#page-click
- https://playwright.dev/docs/next/api/class-page#page-query-selector
- https://playwright.dev/docs/next/api/class-elementhandle
