### ISSUE TITLE
[Question]:  Playwright/OpenFin compatability

### ISSUE THREAD

**Issue by hptabster** [microsoft/playwright#8057]
### Your question

I am trying to get Playwright to "drive" testing in OpenFix. I can successfully connect over the CDP to a spawned OpenFin process and run my tests. However one issue fails, when a window is popped out from OpenFin, I can find the page from within the context, but the page will not render. Performing these steps manually (without Playwright) is successful.

I do not see any particular messages in the console (Inspect/Dev Tools) indicating a failure on loading the page of the popout.

I'm wondering if there are version issues of the embedded Chromium used in OpenFin and Playwright. The versions I observed (browser.version()):
- Playwright: 93.0.4530.0
- OpenFin: 89.0.4389.114
I've tried to discuss this issue with OpenFin support, but they are as familiar with Playwright as your team is with OpenFin!

Another thing to consider is perhaps a permission issue.

Any further suggestions of what to do in terms of debugging are welcome.

**Comment by mxschmitt** [comment]
On each release Playwright gets tested with the current stable Chromium version (see in the release notes) to ensure Playwright works also with the current stable versions. Since OpenFin is not using >= 92 (which is the current stable) this could be an issue and might explain it. (But probably not). Another one is that OpenFin might modify Chromium in some ways, add security stuff etc. Since the team is not familiar with OpenFin and not much users requested support for it, I would mark it as p3-collecting-feedback for now. 

Linking https://github.com/microsoft/playwright/issues/6936

**Comment by hptabster** [comment]
Are there ways to check the security/permission of Chromium? Perhaps it's preventing popouts from running JS (the popouts however do launch).

**Comment by hptabster** [comment]
Note - I can successfully run a _spawn_'ed (or _exec'ed_) OpenFin process from NodeJS comsole (same version that Playwright uses) and see the popouts. So, it appears to be something on the Playwright side preventing these popouts from running the JS code.

Is there additional verbosity to add for Playwright beside pw:api?

**Comment by hptabster** [comment]
Cannot attack trace (it's 26MB). Is there a limit on the file?

**Comment by hptabster** [comment]
Any update on this?

**Comment by pavelfeldman** [comment]
Here is my guess, based on the symptoms:

When Playwright connects to the browser, it throttles all the top level navigations in the browser. It does so in order to instantiate necessary instrumentation and apply emulation / overrides. Electron is managing its web contents slightly differently, so when Playwright starts speaking to it using its default Chromium speak, things fail.

The only way to resolve it is to officially support Electron / OpenFin and cover it with the tests. My understanding is that OpenFin is a flavor of Electron as well, so wile unlikely, those could also diverge slightly. We don't commit to Electron support for now, but if you point OpenFin folks our way, given that there are no real alternatives to Electron testing these days, we could work on some mutual commitment together.

**Comment by TonyBarkell** [comment]
You are correct, OpenFin incorporates a customised build of Electron.

We have a Selenium Example that includes a modified Chrome driver that can be used to help analyse if it is possible for Playwright to support OpenFin: https://github.com/openfin/hello-openfin-selenium-example.  Please let us know if you have any questions about OpenFin.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by SabFloki** [comment]
Any source to see how to launch openfin .exe file with Playwright which then takes to chromium shell upon tapping any links on exe file launched.
