### ISSUE TITLE
[Feature] Option to install only a selection of browser engines

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#812]
Currently once you install `playwright`, `playwright-core` will be installed, which will install all 3 browser engines (takes quite long). It would be awesome, if we could give somehow the option that only some engines will be installed.
Either by specifying it e.g. in the `package.json` or by splitting `playwright-core` up in different packages, which the user has to install. (for webkit, chromium and firefox).

**Comment by pavelfeldman** [comment]
We have convenience npms [playwright-chromium](https://www.npmjs.com/package/playwright-chromium), [playwright-webkit](https://www.npmjs.com/package/playwright-webkit) and [playwright-firefox](https://www.npmjs.com/package/playwright-firefox) that only download that single browser. Note that we will change the export signatures for them so that they matched playwright itself (see https://github.com/microsoft/playwright/issues/814).

**Comment by bennycode** [comment]
@pavelfeldman how to use [playwright-chromium](https://www.npmjs.com/package/playwright-chromium)? The README file of it isn't very descriptive.

I tried to use it with `npx -y playwright-chromium install` but it is still downloading firefox & webkit:

![image](https://user-images.githubusercontent.com/469989/158802490-5471322a-ba1e-40a8-a879-be60ae265541.png)

**Comment by mxschmitt** [comment]
If you are using Playwright Test (@playwright/test) then you only have to do: `npx playwright install chromium`. And uninstall all the other packages besides it :)

**Comment by bennycode** [comment]
Cool. Thank you very much for your input. Looks like it shipped with: https://github.com/microsoft/playwright/pull/4952 🎷

**Comment by aslushnikov** [comment]
> Is there a command to uninstall other browsers installed by Playwright?

@gajus Garbage collection happens automatically whenever the installed browser is not used by any other playwright installation.
There's no dedicated command to uninstall used browsers though; please file an issue to request one!

**Comment by Pomax** [comment]
Rather than [playwright-chromium](https://www.npmjs.com/package/playwright-chromium), [playwright-webkit](https://www.npmjs.com/package/playwright-webkit) and [playwright-firefox](https://www.npmjs.com/package/playwright-firefox), could we get "normally" namespaced packages instead? e.g. `@playwright/playwright`, `@playwright/chromium`, `@playwright/webkit`, and `@playwright/firefox`?
