### ISSUE TITLE
[BUG] website does not extend to full size

### ISSUE THREAD

**Issue by bpasero** [microsoft/playwright#813]
**Context:**
- PlayWright Version: [what PlayWright version do you use?] 0.10.0
- Operating System: [e.g. Windows, Linux or Mac] macOS 10.15.2

I wonder how to get my app span the entire window?

![image](https://user-images.githubusercontent.com/900690/73660081-cc4fa880-4697-11ea-8d21-a6cd7042cb11.png)

I experimented with passing over viewport, but I am not sure that is correct. I simply want the viewport of whatever the browser window size is.

**Comment by pavelfeldman** [comment]
:wave: @bpasero 

That would be set on the [browser.newContext](https://github.com/microsoft/playwright/blob/master/docs/api.md#browsernewcontextoptions) level: 

```js
const { chromium, firefox, webkit } = require('playwright');
  
(async () => {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext({ viewport: null });
  const page = await context.newPage('https://visualstudio.microsoft.com/services/visual-studio-online/');
})();
```

We'd like users to create a browser context per test and all the configurations would go there. We can't make `headless` a part of it since `headless` controls the binary being launched, since the split. Note that we might change some names before we hit 1.0 since we aren't entirely happy about the Browser/BrowserContext naming.

**Comment by bpasero** [comment]
Hi @pavelfeldman, I would if possible try to not create a new context but use the tab that opens by default to reduce the number of things that open. My current code to run is this:

```ts
const browser = await playwright[engine].launch({
	headless
});
const page = (await browser.defaultContext().pages())[0];
await page.setViewport({ width, height });
await page.goto(`${endpoint}&folder=vscode-remote://localhost:9888${URI.file(workspacePath!).path}`);
```

**Comment by pavelfeldman** [comment]
Got it. Just testing the waters here: would it work for you if defaultContext was not opening its first page? Rationale: default context is extremely limited in the emulations that you can apply and can't be used in the cloud scenario - we want to maintain a 'context per user story' operation.

**Comment by bpasero** [comment]
@pavelfeldman yeah I think that would work. Summarising my requirements:
* browser opens with a good size in the middle of the screen (like VSCode default window size and position)
* there is just 1 tab opened
* I can load my test URL into that 1 tab
* the contents of the tab fill the entire size of that tab (e.g. VSCode appears fully in that size)

**Comment by pavelfeldman** [comment]
I believe this is now possible!

**Comment by Treshch1** [comment]
solution with `context = browser.newContext(viewport=None)` does not work in python playwright version. Or maybe I'm trying it in the wrong way?

**Comment by alterhu2020** [comment]
> solution with `context = browser.newContext(viewport=None)` does not work in python playwright version. Or maybe I'm trying it in the wrong way?

Same question here, Team, Do we have any options to open the browser in full screen size? thanks

**Comment by ameyanatu** [comment]
use '--window-position=0,0' in args and capture the current viewport using pyautogui or any other python library, which will properly maximize the browser window in playwright python

**Comment by frapbod** [comment]
Leaving this here since I found this issue when searching for viewport issues with python playwright.
At least for playwright version 1.32.1 (only one I tested)
When opening the new browser context provide the argument:
no_viewport=True 
[Archived Source link](https://web.archive.org/web/20230409001250/https://playwright.dev/python/docs/next/api/class-browser#browser-new-context-option-no-viewport)
