### ISSUE TITLE
[Feature] Expose Reporter api for getting skipped testSuites 

### ISSUE THREAD

**Issue by vmelikyan** [microsoft/playwright#8192]
It would be nice to be able to get the number of skipped suites via the Reporter api, something similar to `testCase.outcome()` but for suites.
E.g.
```javascript
test.describe('Suite1', () => {
  test.skip(true);
   test('test1', async ({ page }) => {
    await page.goto('/');
  });
  test('test2', async ({ page }) => {
    await page.goto('/');
  });
});
```
In the above example all of the tests inside the `Suite1` suite will be skipped, and there is no easy way of finding suites where all tests are skipped.

**Comment by dgozman** [comment]
I think `suite.allTests().filter(test => test.outcome() === 'skipped')` does exactly this, doesn't it?

**Comment by dgozman** [comment]
Sorry, I misread the description. Could you please tell more about the usecase? Why specifically about skipped, and not failed/flaky/etc?

Perhaps this snippet is a good approximation?
`suite.allTests().every(test => test.outcome() === 'skipped')` ?

**Comment by vmelikyan** [comment]
> Could you please tell more about the usecase?

We are collecting and sending test metrics to datadog. 

> Why specifically about skipped, and not failed/flaky/etc?

Good point. I guess it's a bit easier to determine skipped/expected/unexpected from `suite.allTest()`. E.g. if there is one failed test in a suite we can declare the suite has failed. To be able to declare a suite was skipped all tests must be skipped and I could not come up with an easy way of determining this.

There is also the challenge of nested suites, `suite.allTests()` will get us ALL of the test cases in that suite including tests from nested suites.

**Comment by dgozman** [comment]
> To be able to declare a suite was skipped all tests must be skipped and I could not come up with an easy way of determining this.

I think this works, doesn't it? `suite.allTests().every(test => test.outcome() === 'skipped')`

> There is also the challenge of nested suites, suite.allTests() will get us ALL of the test cases in that suite including tests from nested suites.

I am afraid that defining the semantics that works for everyone would be hard. Like you mention here, do you consider only direct tests or all tests from subsuites? If we were to introduce an API for this, it should not be controversial, and so far it does not look that straightforward.

--- 

Overall, I believe that we should expose all the basic information, so that users of the API can determine for themselves what do they consider a "skipped" suite or a "failed" suite. If you have some definition that cannot be expressed using existing API methods, please let us know.

**Comment by vmelikyan** [comment]
@dgozman makes sense, thank you for looking into this.
