### ISSUE TITLE
[Question] Recommended approach to write selector

### ISSUE THREAD

**Issue by macroking** [microsoft/playwright#8210]
Hello,

Now we have the new locators API, we had `$`, `$$`, and now the `locators`. Is there any recommendation that the team which one to use and when?

I could do the following,
```js
const locator = page.$('text=login')
await locator.click()

const locator = page.locator('text=Submit');
await locator.click();

Is there any recommendation for writing Page Objects with the new locator api?
```

**Comment by pavelfeldman** [comment]
Yes, there will be a doc for POM with locators. Unless you are doing something special to element handles obtained via $$ and $, you should use Locators. They are more convenient and are integrated with our new expect() methods: https://playwright.dev/docs/test-assertions

**Comment by ltsuda** [comment]
Hi, taking the opportunity in this thread. What should it be the best option for me?

Today, I'm using the `ElementHandle` class with $$ to select a list of items with the same class name, then I iterate over them getting their child elements/texts using the $('child-selector'). 

In this case, I think is the best way of doing that because the `Locator` class is strict to select only one occurrence of the selector. Do you agree with that? Or there's a way of getting a list of elements with the same class using the `Locator` API?

Thanks for the awesome library.

**Comment by pavelfeldman** [comment]
Locator is only strict on the actions, it can still work with lists: you can do `locator.evaluateAll` and similarly to $$eval it'll get array of elements in the callback. My preference is to work with locators because they are overall more useful in other use cases.

**Comment by pavelfeldman** [comment]
So the answer is Locators at all times!
