### ISSUE TITLE
[Question] Reaching instances of WKSession

### ISSUE THREAD

**Issue by vdeturckheim** [microsoft/playwright#8231]
Hey,

I am trying to get a hand on an instance of `WKSession` while doing Webkit instrumentation (to do some similar things that what I do with `CDPSession`s).
But I did not really find a way to access the instances of these objects.
Would there be a way to achieve that? 

Thanks a lot!

**Comment by JoelEinbinder** [comment]
Due to the fragile nature of these apis we don't expose them in playwright. Can you file issues for what are you trying to do with the WebInspector protocol? If they are a good fit for this project we can just add those apis for you.

**Comment by vdeturckheim** [comment]
@JoelEinbinder thanks for the quick reply. I think the uses cases I have are very edgy and would probably not make a lot of sense to have in the lib.

Out of curiosity, when you say these APIs are fragile, are you referring to the protocol itself (things like `Runtime.evaluate`) or the way to interact with the browser to forward the commands? If it is about the former, it might still make sense to expose a raw way of sending commands and leave the rest at the risks of the end user.

**Comment by JoelEinbinder** [comment]
Things like `Runtime.evaluate` are pretty stable, but you can use those already via `page.evaluate`. With CDP we have some session isolation so that we can be confident playwright still works even if the user is sending their own commands. No such thing exists for webkit, every command goes over the same channel, so its way more likely that sending your own commands will break playwright. Of course if you are careful you can make anything work, but this not an api we want to add/encourage users to use. If you are trying to do something outside the scope of playwright I'd recommend you fork and modify playwright for your own needs. We are open source after all :)

**Comment by vdeturckheim** [comment]
Thanks make sense. Yeah, `Runtime.evaluate` is not the best example, I mostly play with the debugger scope atm 😓.
Thanks for the clarification on the risks, that helps. I'll probably not fork but monkeypatch stuff before instanciations to get the refs and accept the eternal doom if it breaks something ^^
