### ISSUE TITLE
[Feature] Smaller trace files

### ISSUE THREAD

**Issue by frost555** [microsoft/playwright#8263]
I propose to exclude large network requests to JS and CSS files from trace zip file. They can be quite large and are not very important when looking at trace.

**Comment by frost555** [comment]
Our production bundle is about ~3mb of zipped JS (I know that's a lot), therefore each trace file will be 3mb+. 

I'm currently trying out Playwright but can imagine CI server spacing issues with a lot of test runs (and failures).

**Comment by JoelEinbinder** [comment]
We of course want traces to be as small as possible, but it's hard for us to act on speculative problems. Traces are big because they provide a huge amount of debugging features, but in theory they should be used by the developers to fix the tests.

If you are capturing thousands of traces but nobody is looking at them, then maybe you don't want to be capturing them rather than wanting them to be smaller?

I don't think this is actionable for us right now. But if you come back with an overflowing CI I can promise I'll help you find a way to reduce the size.

**Comment by dgozman** [comment]
@frost555 What is your Playwright version? I believe that in v1.14 we do not include JS files into the trace anymore. Could you please double check?

**Comment by frost555** [comment]
@dgozman I was on 1.13.1, tried out 1.14 and trace file size against the same dev environment is down from 27mb to 3mb. 
Great!
