### ISSUE TITLE
[Question] - Do we have download function

### ISSUE THREAD

**Issue by PeterNgTr** [microsoft/playwright#829]
Hi, I already checked the api documentations but cannot find anything refer to download files function. May I know if we are currently supporting it or will be in the near future?

**Comment by aslushnikov** [comment]
@PeterNgTr Hi! What is the `download` function?

**Comment by edi2004** [comment]
@aslushnikov maybe something similar to Save As option in right click?

**Comment by PeterNgTr** [comment]
@aslushnikov ah I meant, something like this of puppeteer -> https://pptr.dev/#?product=Puppeteer&version=v2.1.0&show=api-browserfetcherdownloadrevision-progresscallback

**Comment by aslushnikov** [comment]
> @aslushnikov maybe something similar to Save As option in right click?

Joel just filed a tracking bug for this: https://github.com/microsoft/playwright/issues/853
Feel free to star and put your thoughts there!

> ah I meant, something like this of puppeteer -> https://pptr.dev/#?product=Puppeteer&version=v2.1.0&show=api-browserfetcherdownloadrevision-progresscallback

We're converging on a much simpler version here: https://github.com/microsoft/playwright/pull/834
The actual issue is https://github.com/microsoft/playwright/issues/823

Closing this in favor of related issues
