### ISSUE TITLE
[BUG] waiting for firstPageProxy failed

### ISSUE THREAD

**Issue by FezVrasta** [microsoft/playwright#830]
**Context:**
- PlayWright Version: 0.10.0
- Operating System: macOS 10.15.3
- Extra: node 11.15.0

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```
git clone git@github.com:popperjs/popper-core.git
git checkout test/playwright
yarn
JEST_BROWSER=webkit yarn test:functional
```

**Describe the bug**

I'm migrating a test suite from Puppeteer to Playwright.
The Chromium tests run correctly, like they used to with Puppeteer.

The WebKit tests, though, report this error whenever I run them:

```
    TimeoutError: waiting for firstPageProxy failed: timeout 30000ms exceeded

      at Function.waitWithTimeout (node_modules/playwright-core/lib/helper.js:120:30)
      at WKBrowser._waitForFirstPageTarget (node_modules/playwright-core/lib/webkit/wkBrowser.js:74:31)
      at Function.connect (node_modules/playwright-core/lib/webkit/wkBrowser.js:47:23)
```

It looks like other people have the same issue:
https://stackoverflow.com/questions/59942461/playwright-error-unhandledpromiserejectionwarning-timeouterror-waiting-for-fi

**Comment by pavelfeldman** [comment]
/CC @mmarkelov

Posting investigation note here.

`jest-playwright` launches a browser once and then connects to it over webSocket for each environment. That works for Chromium and Firefox since they support multiple web socket clients, but fails for WebKit. I guess we did not do a great job explaining our launcherApp apis and limitations.

What our local harness does instead is running an instance of a browser app per test process. It uses regular `playwright.launch` for that and then exposes browser.newContext with test environment. @mmarkelov is this something you could do in jest-playwright?

**Comment by pavelfeldman** [comment]
Thinking out loud, if this turns out to be problematic in jest, we can try multiplexing the web socket in WebKit for now. I'll look into it.

**Comment by aslushnikov** [comment]
There's an alternative approach that creates a browser instance per jest worker.
Submitted a PR:  https://github.com/mmarkelov/jest-playwright/pull/9

**Comment by aslushnikov** [comment]
@FezVrasta jest-playwright is now updated to v0.0.5 with the fix to the webkit - there should be no ` TimeoutError: waiting for firstPageProxy failed: timeout 30000ms exceeded` error any more! Please give it a try!

**Comment by FezVrasta** [comment]
I confirm it's working, thanks
