### ISSUE TITLE
[BUG] page.route is not a function (mac osx)

### ISSUE THREAD

**Issue by cjroebuck** [microsoft/playwright#845]
**Context:**
- Playwright Version: 0.10.0
- Operating System: Mac (catalina 10.15.2 (19C57))

```javascript
const playwright = require("playwright");

(async () => {
  const browser = await playwright.firefox.launch({ headless: false });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.route("**/*", req => {
    console.log("ON REQUEST", req.url());
    req.continue();
  });
  await page.goto("https://bbc.co.uk", { waitUntil: "networkidle2" });
  await page.setViewport({ width: 1280, height: 1024 });
  await page.screenshot({ path: "test.png" });
  await browser.close();
})();

```

Running the above, i'm seeing:

**UnhandledPromiseRejectionWarning: TypeError: page.route is not a function**

**Comment by pavelfeldman** [comment]
Thanks for the heads up. The reason is that `page.route` will appear in `v0.11.0` with the next update. This will be a breaking change, but we believe it makes API shape much more friendly, so we are going for it before we release `v1.0` and commit to semver.

 In order to address the docs issue, API link now points to the docs that correspond to the `v0.10.0` release.
