### ISSUE TITLE
[Feature] api to customize the outputs in the trace viewer

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#8605]
it would be nice to be able to customize the outputs that appear in the trace viewer. for example, in this trace it's difficult to tell what actually called these methods:
![image](https://user-images.githubusercontent.com/57028336/131597248-468c0737-0ca4-4e59-b241-98c4ae849ed0.png)

if there was an api that allows you to output custom function calls to the trace, as well as group outputs such that it's clear where they come from, that could be customized to look something like this:
![image](https://user-images.githubusercontent.com/57028336/131600903-6039f050-f8aa-459d-b752-99be794bc832.png)

**Comment by uchagani** [comment]
100% agree. Also the ability to add logs to the trace viewer would be great.

**Comment by A-ZC-Lau** [comment]
I would also like to add that the trace log should be grouped by workers instead of tests.

Take for example the test:

```javascript
import { test, expect, Page } from "@playwright/test";

test.describe.serial("serial", () => {
    let page : Page;
    test.beforeAll(async ({browser}) => {
        page = await browser.newPage();
        await page.goto("https://getbootstrap.com/docs/5.1/components/modal/");
    });

    test("On modal page", async function () {
        const titlePage = await page.title();

        expect(titlePage).toContain("Modal");
    });
    test("Can open a modal", async function () {
        await page.locator("[data-bs-target='#exampleModalLive']").click();

        const modalText = await page.locator("#exampleModalLive .modal-body").innerText();

        expect(modalText).toBe("Woohoo, you're reading this text in a modal!");
    });
});
```

Logically, there should only be one output, but in reality, there are two outputs.

![Screen Shot 2021-09-20 at 8 06 30 pm](https://user-images.githubusercontent.com/20273647/133985780-6be6c3f1-7e43-45cb-9990-eafc4cf62384.png)

This is the trace from the first test.

![Screen Shot 2021-09-20 at 8 13 35 pm](https://user-images.githubusercontent.com/20273647/133986531-639acbb3-b33f-4410-89cf-53ca6c1074a8.png)

And this is from the second.

![Screen Shot 2021-09-20 at 8 08 28 pm](https://user-images.githubusercontent.com/20273647/133985956-e0aa25d4-d7b2-4901-bf54-eb300902b06b.png)

<hr>

The fragmentation makes the trace much less helpful.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by DetachHead** [comment]
the trace file is really messy and difficult to read without this feature, i think it's important. it also has 7 upvotes already @pavelfeldman

**Comment by DetachHead** [comment]
this is now possible as of `@playwright/test` v1.34 using `test.step`:
```ts
test('asdf', () => {
    await test.step('foo', async () => {
        await page.click('foo')
        await page.click('bar')
        await test.step('checks', async () => {
            expect(await page.locator('asdf').count()).toBe(1)
        })
    })
})
```
![image](https://github.com/microsoft/playwright/assets/57028336/6584fceb-7347-407c-a363-92308c1d8b29)
