### ISSUE TITLE
[Feature] Migrate protractor to playwright

### ISSUE THREAD

**Issue by MPonraj** [microsoft/playwright#8649]
Is there any best way to convert from Protractor Typescript to Playwright Typescript? Can you please provide any documentation for the migration?

**Comment by aslushnikov** [comment]
@MPonraj There's a simple polyfill for the `waitForAngular` function they have in Protractor: [see here](https://github.com/microsoft/playwright/issues/8433#issuecomment-910186722). 

But you might not even need it since Playwright has a nice auto-waiting functionality. 

On a related note: is your protractor test suite public? We'd love to take a look on any real-world protractor test suites to have a better idea what they look like.

**Comment by aslushnikov** [comment]
@MPonraj Here's a guide on migrating from Protractor: https://playwright.dev/docs/next/protractor

**Comment by MPonraj** [comment]
Thank you so much @aslushnikov.
Thanks for accepting the request and implementing it.
