### ISSUE TITLE
[Feature] Audible alarm when a test exceeds a time threshold before timeout

### ISSUE THREAD

**Issue by srguiwiz** [microsoft/playwright#8657]
We have evasive failures.  The test suite passes most of the time.  Some days we find a page didn't proceed past a progress bar.  For example one or two out of a hunrded near identical tests, in a one hour run.

It would be nice if the computer beeps a unique (globally configurable) sound when a test takes longer than a configurable time, e.g. `audibleTimeout`, for example two minutes.  With a test timeout of let's say ten minutes, it would be nice if it would beep or start beeping every minute `audibleInterval` after it passes two minutes, so a person can pay attention and look with the Developer Tools in the test browser to inspect the situation.

There isn't enough information in the log, there is too much going on on the page, and it doesn't happen often enough to sit and watch.  An audible alarm would be perfect to attract a real person's attention, to a machine that sits on a desktop, maybe with the screensaver having kicked in, or a VM in the background, just not something a person can keep watching for an hour or many hours.

**Comment by yury-s** [comment]
If your want your test harness to beep when a test is taking too long you can do something like this:

```js
let timer;
it.beforeEach(() => {
  timer = setInterval(() => console.log('\u0007'), 1000);
});

it.afterEach(() => {
  clearInterval(timer);
});

it.only('should beep if running too long', async ({page, server}) => {
  await new Promise(r => setTimeout(r, 10000));
});
```
What playwright could do in such case is to print some warning if a test is running longer than X seconds and then an external tool would be able to watch the output and play a sound. Since you can already achieve this using existing hooks we are not likely to implement this at the moment.
