### ISSUE TITLE
[BUG] Screenshot of canvas inside a iframe is not seen captured for firefox with playwright

### ISSUE THREAD

**Issue by ajinkya201991** [microsoft/playwright#8677]
**Context:**
- Playwright Version: 1.14
- Operating System: Windows
- Node.js version: v12.21.0
- Browser : Firefox

**Code Snippet**

const frame = page.frame('Name of frame');
const elementHandle = await frame.$('xpath of graphical canvas');
await page.waitForTimeout(5000);
console.log(elementHandle)
await elementHandle.screenshot({ path: 'screenshot.png' });
await page.screenshot({ path: 'screenshot1.png', fullPage: true });

**Describe the bug**

Screenshot of canvas is not seen captured for firefox.
Screenshot is accessed from iframes
No issue occurs for same code to get screenshot for chrome and msedge

**Comment by yury-s** [comment]
Can you share the page where it fails and failing code snippet?

The following snippet works fine across all browsers:
```js
it('should take canvase screenshot', async ({page, browserName}) => {
  await page.goto('https://www.w3schools.com/html/html5_canvas.asp');
  const canvas = await page.$('canvas');
  await canvas.screenshot({path: `/tmp/s-${browserName}.png`});
});

```

Also do you not see it in both full page screenshot and the element screenshot or only one of them?

**Comment by ajinkya201991** [comment]
hi yury-s, Thank you for your reply......screenshot capturing is fine for firefox when canvas element is accessed via page.....
Issue is for canvas element accessed via frame.....
Actually cant share the page, due to some copyright issues.....
I have changed the bug summary for better clarity....can you please recheck for combination of screenshot of canvas inside a iframe using firefox browser

**Comment by pavelfeldman** [comment]
Since page.$ and frame.$ are the same under the hood, it is likely that something else is wrong. We need a repro we can try locally to be able to address the issue. Our test that tests exactly this passes on all platforms, so it is likely to have something to do with your page. The fact that Firefox is the issue suggests that this is a timing issue. Other browsers are faster, so there probably is some race in the way you obtain that element handle. It is unlikely that we are able to help remotely, so I'll close it.

If you still think this is a Playwright bug rather than the way you obtain the handle, we would appreciate a small repro script that we could run locally in a new issue. Please link this one to retain all the context should you decide to file it.

**Comment by ajinkya201991** [comment]
Hi pavelfeldman, 
Mentioned issue is seems resolved by a workaround to disable hardware acceleration in firefox.
Currently hardware acceleration is disabled by adding  a line in this file (00-playwright-prefs.js).......in location (C:\Users\<username>\AppData\Local\ms-playwright\firefox-1281\firefox\defaults\pref)........line (pref("layers.acceleration.disabled", true);).....

Regarding setting preference for browser launch with firefox......i can see a setting in here.......https://playwright.dev/docs/api/class-browsertype#browser-type-launch.....................with options...... firefoxUserPrefs........Can you please mention usage of it ?
