### ISSUE TITLE
[Question] How to ignore first argument in test()

### ISSUE THREAD

**Issue by Nhasa** [microsoft/playwright#8798]
I'm using @playwright/test v1.14.1.
I followed the instruction in this page https://playwright.dev/docs/test-parallel/#reusing-single-page-between-tests. 
All seems fine, until I try to ignore first parameter in the `test()` by using _ as I normally doing in typescript.
When I try to run the test I got this error: `Error: First argument must use the object destructuring pattern: _`

```js
test.describe.serial('test case 1', () => {
  test('test step 1', async (_, testInfo) => {
    // Error: First argument must use the object destructuring pattern: _
  })
})
```

**Comment by mxschmitt** [comment]
```
  test('test step 1', async ({}, testInfo) => {
  })
```

is currently the preferred way of doing it.

**Comment by Nhasa** [comment]
@mxschmitt thanks for your answer. 
Yes, that solve the error, but I need to turn off my `eslint` rule.
https://eslint.org/docs/rules/no-empty-pattern
I will live with this for now. I would be great if we could use `_` instead of `{}` in the future.

**Comment by A-ZC-Lau** [comment]
Curious, why is the destructuring required?

Why can't I just do `test("test", async (t) => t.page.goto(somewhere))`

**Comment by mxschmitt** [comment]
Playwright's test-runner does internally determine what kind of fixtures it has to create and load. When using a single variable name without destructing, this is not possible (since it needs to load all fixtures?). Also when using an underscore its in theory also just a variable, so auto-complete might be off and confusing to the user.

**Comment by oneinchman** [comment]
I also get this message after manually compiling Typescript as suggested on
[https://playwright.dev/docs/test-typescript](https://playwright.dev/docs/test-typescript)

However, I do use the destructuring pattern:
```TSX
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {
  await page.goto('/markets');
  const content = await page.textContent('h1');
  expect(content).toBe('Markets');
});
```

The transpiled Javascript:
```Javascript
Object.defineProperty(exports, "__esModule", { value: true });
var test_1 = require("@playwright/test");
//import { Texts } from '~app/config';
(0, test_1.test)('basic test', function (_a) {
    var page = _a.page;
    return __awaiter(void 0, void 0, void 0, function () {
        var content;
        return __generator(this, function (_b) {
            switch (_b.label) {
                case 0: return [4 /*yield*/, page.goto('/markets')];
                case 1:
                    _b.sent();
                    return [4 /*yield*/, page.textContent('h1')];
                case 2:
                    content = _b.sent();
                    (0, test_1.expect)(content).toBe('Markets');
                    return [2 /*return*/];
            }
        });
    });
});
```

**Comment by ChristianMayAvixa** [comment]
^Same

**Comment by alexdao3** [comment]
@mxschmitt Is there an alternative approach/syntax for defining which fixtures to use aside from the destructured form in the argument? Personally I am using a compile-to-js language (Clojurescript) to write my Playwright tests, and I don't believe the compiler knows how to generate this exact syntax. I also don't think I would expect most compilers to do this

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
