### ISSUE TITLE
[Feature] Option to save image snapshot in provided directory rather than close to tests spec files.

### ISSUE THREAD

**Issue by ajaskolski** [microsoft/playwright#8912]
User case:
Got over 300 screenshots in tests. So far with jest image snapshot we just keep them in git lfs as submodule in the repository so the main repository app builded with webpack doesn't get too big. Over 300 image snapshots already take some considerable space. 

Overall option to keep snapshots in one directory makes it easier to manage them as one.

**Comment by jithinjosejacob** [comment]
It would be great if this feature can enhance the same in such that a way we can connect to a cloud directory like s3 bucket,blob storage or gcloud bucket. Keeping images in repo is not a great idea and results in huge maintenance when more files are there. if some test fails in CI.we still need to bring those images files outside to know the failed results.

**Comment by schickling** [comment]
Another use case: I'm compiling my TS source code manually (via `tsc --watch`) because I'm relying on some TS compiler plugins which aren't supported by PW/Babel. This means I'm pointing Playwright to the pre-compiled tests living in a `dist` folder. Hence snapshots won't be persisted in version control.

**Comment by nickofthyme** [comment]
@ajaskolski would #9260 solve your issue?

**Comment by schickling** [comment]
@nickofthyme it would for my use case. Thanks for working on this! 🙏
