### ISSUE TITLE
[Feature] Prepend os and browser to video recording on failure

### ISSUE THREAD

**Issue by haikyuu** [microsoft/playwright#8939]
First of all, thank you for your amazing work on this library. It has been a joy to work with ❤️ 

We started using Playwright to write automated e2e tests for [Imba language](https://imba.io) and we run the tests on all platforms and browsers.

We record failed tests and upload them as artifacts in github actions. Here is how the folder looks like:

![image](https://user-images.githubusercontent.com/8558836/133430854-6f221fb5-a30e-4374-a171-9d7f9073821f.png)

Unique names are good to have. But it would be super nice to prepend the OS and the browser used in the recording. That would be super helpful.

**Comment by dgozman** [comment]
@haikyuu Do you use playwright test runner, or just playwright library? We usually leave things like this to the test runner to figure out, because everyone has a different opinion 😄 

You can always use [`video.saveAs`](https://playwright.dev/docs/api/class-video#video-save-as) and rename files however you'd like if test harness does not handle it for you.

Also, did you try [recording a trace](https://playwright.dev/docs/next/trace-viewer)? It has much more utility than videos, give it a try.

**Comment by dgozman** [comment]
Closing because we cannot repro the issue, and `video.saveAs` should work in this case. Feel free to open a new issue with a repro script if there's still a problem.
