### ISSUE TITLE
Enable 3rd-party cookies in Chromium

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#8940]
As discussed on 14.09.

**Comment by JoelEinbinder** [comment]
There is a preference in the browser which defaults to blocking third party cookies in incognito. Because we run incognito unless a user data dir a specified, this means our behavior is to block third party cookies which doesn't match the current Chrome behavior.
![image](https://user-images.githubusercontent.com/4624233/133460432-0c369a8b-ba07-4316-8130-580dcafae661.png)

I hoped to avoid a chromium patch by finding a way to change the setting automatically. In linux and windows we can put an `initial_preferences` file next to the chrome binary to be loaded on first run. However on MacOS this only looks at a global location in `~/Library` so it would conflict with whatever file the user put there. I am also not sure if it works for headless. I expected a command line switch like `--set-preference=name=value` but I could not find one.

**Comment by pavelfeldman** [comment]
Looks like we are fine here, OTR is not incognito.
