### ISSUE TITLE
[BUG] page.locator(selector).inputValue() returns an empty object for an input

### ISSUE THREAD

**Issue by c-kirkeby** [microsoft/playwright#8954]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Linux 5.11 Zorin OS 16
- Node.js version: v14.17.6
- Browser: Chromium Version 94.0.4595.0 (Developer Build) (64-bit)
- Extra: Node version is controlled by Volta

**Code Snippet**

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
</head>
<body>
    <main class="main">
       <input class="joinDate" value="16/09/2021"></input>
    </main>
</body>
</html>
```

```bash
❯ npm run test:e2e

> playwright-inputvalue-test@0.1.0 test:e2e
> playwright test


Running 1 test using 1 worker

  ✘  tests/example.spec.mjs:3:1 › Check join date (1s)


  1) tests/example.spec.mjs:3:1 › Check join date =================================================

    Error: expect(received).toEqual(expected) // deep equality

    Expected: "2021-09-16"
    Received: {}

        at file:///home/christian/Documents/projects/playwright-inputvalue-test/tests/example.spec.mjs:6:57
        at WorkerRunner._runTestWithBeforeHooks (/home/christian/Documents/projects/playwright-inputvalue-test/node_modules/@playwright/test/lib/test/workerRunner.js:426:7)


  1 failed
    tests/example.spec.mjs:3:1 › Check join date ==================================================
```

```javascript
import { test, expect } from '@playwright/test'

test('Check join date', async ({ page }) => {
  await page.goto('file:///home/christian/Documents/projects/test/src/index.html')
  await expect(page.locator('.joinDate').inputValue()).toEqual(new Date().toISOString().slice(0, 10))
})
```

**Describe the bug**

I try to access the value attribute on the input field but I get an empty object instead.

**Comment by ltsuda** [comment]
I think you are mixing the Playwright/Test extended assertion with the jest assertion.

`await expect()....`  is for async web assertions provided here https://playwright.dev/docs/test-assertions

As you are using `.toEqual`, you don't need the `await` before the `expect()`.

Also, the `.inputValue()` returns a Promise, so you need to call like this `expect(await page.locator('.joinDate').inputValue())...`. See here for more details: https://playwright.dev/docs/api/class-locator#locator-input-value

The `.locator()` is synchronous, but the locator's functions are asynchronous (returns a Promise), that's why you need to use `await`  inside the expect like I've shown above.

**Comment by c-kirkeby** [comment]
Thanks, I'm new to using Playwright so I must've missed this. Happy to close this.
