### ISSUE TITLE
[Feature] Allow user to select actionability checks

### ISSUE THREAD

**Issue by irharrier2** [microsoft/playwright#8966]
First of all, thank you for the amazing testing framework, where everything just works!

I have encountered an issue where I am trying to `page.fill(myElementSelector, "myText")` a `<textarea>` and Playwright is simply too fast, causing the application to throw an error as `<textarea>` is not stable.

I tried waiting for element state to be stable and it works:
```
await page.waitForSelector(myElementSelector)
let elementHandle = await page.$(myElementSelector)
await elementHandle?.waitForElementState("stable")
await elementHandle?.fill("myText")
```

Of course, I can also use a `click`  functions before `fill` functions as `click` waits for the element to be stable ([refrence](https://playwright.dev/docs/actionability/)):
```
await page.click(myElementSelector)
await page.fill(myElementSelector, "myText")
```

So my request is to either:
1.  Allow users to select additional actionability checks in `[, options]`  
2.  Add stability check to `fill` and `type` functions.

**Comment by dgozman** [comment]
@irharrier2 Interesting! Ideally, we would make `fill` just work for you. What does it say if you don't wait for "stable"? Mind sharing a repro script?

Regarding your fetature proposal, let us think about this API, perhaps we'll come up with something like this.

**Comment by irharrier2** [comment]
I am not sure how can I come up with reproducible script without you having access to a Salesforce instance. Please let me know if you have any idea.
it basically throws a `Uncaught Action failed:  [Cannot read properties of null]` if I fire `fill()` without waiting for the element to be stable.

The general flow of the test is pretty simple:
1. Navigate to a page
2. Click on a button that opens a dialog (not a pop-up)
3. Fill in the text field -> application throws a `Uncaught Action failed`
4. Press send button

Other things that I tried between step 2 and 3:
- Explicit wait for 100ms -> works
- Wait for network to be idle -> does not work

**Comment by dgozman** [comment]
@irharrier2 When you say "application throws an error", do you mean that error is thrown inside the page itself, not in the test? If so, what does Playwright say when you `fill()`? Does it throw any errors?

We usually suggest to fix such an issue in the page, because it is not ready for the fast user and slow connections. You can probably trigger the same issue manually without Playwright if you open Chrome DevTools, go to Network tab and choose "Slow 3G" network throttling.

If you need to fix the test, look for a signal to wait. Usually that's a network response that triggers some updates in the page and you can use [`page.waitForResponse()`](https://playwright.dev/docs/next/api/class-page#page-wait-for-response) for that. I think that `waitForElementState("stable")` just happens to luckily wait long enough, but in reality "stable" is about elements moving on the screen, which is probably not the case here. Same goes for `waitForTimeout(100)` - it could help most of the times, but can still fail on very slow CI machines.

**Comment by irharrier2** [comment]
I was sure that it is not by luck as other `wait for` condition did not work (assuming that they have the same built-in wait time). You are absolutely right and `page.waitForResponse()` works like a charm even in a throttled connection.


> waitForTimeout(100) - it could help most of the times, but can still fail on very slow CI machines.

That is exactly why I am here. 

> When you say "application throws an error", do you mean that error is thrown inside the page itself

Yes by the application itself.
