### ISSUE TITLE
[Feature Request] Add a way to use custom codegen recorders

### ISSUE THREAD

**Issue by haikyuu** [microsoft/playwright#8992]
I have built a recorder for [Imba](imba.io) language, but I think it makes sense to put it in a separate repo rather than including in Playwright itself. PR: #8988 

The reporter itself is working fine. But I need some help in order to add custom recorders support. I'm interested in contributing that, but I need some guidance.

Thank you

**Comment by dgozman** [comment]
@haikyuu Exciting! Thank you for your work to improve Playwright!

I agree with you that it does not make sense to bundle this into Playwright, because Playwright is not available in Imba language out of the box.

The feature request to extend codegen tool looks similar to #5266. It definitely makes sense. However, we have hundreds of bugs and feature requests and have to prioritize accordingly. I'll leave this issue open in case it turns out to be a popular feature request and collects a lot of upvotes, but I don't think we'll work on this in the nearest future.

**Comment by haikyuu** [comment]
Thanks @dgozman 

I will try to contribute it myself. I'll ask questions in slack as I make progress.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
