### ISSUE TITLE
[Question] How i can navigate to the Baseurl automatically beforeAll tests block?

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#9008]
How navigation to baseUrl can be hooked in beforeAll instead of navigating beforeEach test using playwright/test ?

**Comment by dgozman** [comment]
@Amrkamel1 You can put `page.goto('./')` anywhere in your code - in `beforeEach`, `beforeAll`, etc. But I guess you are looking for something different? Please tell us more details about your usecase so we can help.

**Comment by Amrkamel1** [comment]
@dgozman  it seems that beforeAll not supporting {page} since its running even before launching the context

![image](https://user-images.githubusercontent.com/32042806/133895639-cf33e2f5-508d-4430-825c-503ed97cd669.png)

**Comment by pavelfeldman** [comment]
Each test gets its own page, so you can't use it on beforeAll. Either use beforeEach or implement your own fixture that navigates the page to the initial url. 

https://playwright.dev/docs/test-fixtures/#overriding-fixtures - looks like exactly what you need.

**Comment by Amrkamel1** [comment]
@pavelfeldman 
I will check it thanks, but currently, it seems your sever is down 
![image](https://user-images.githubusercontent.com/32042806/133930252-deed5ffa-0dab-4266-a0c6-a11281e43b65.png)

**Comment by Amrkamel1** [comment]
> Each test gets its own page, so you can't use it on beforeAll. Either use beforeEach or implement your own fixture that navigates the page to the initial url.
> 
> https://playwright.dev/docs/test-fixtures/#overriding-fixtures - looks like exactly what you need.

So Basically, the browser is launching/ terminating for every single test.
would navigating once beforeAll tests could be supported.

**Comment by pavelfeldman** [comment]
> So Basically, the browser is launching/ terminating for every single test

No, the browser is launching for each parallel worker, not per test.

> i don't know how I could navigate initially before all tests

You can't navigate before all tests because each test gets its own isolated page. So you can navigate before each test only. You can do that in beforeEach or via fixtures.

Could you share more about your use case? It looks like we are talking about different things.

**Comment by Amrkamel1** [comment]
@pavelfeldman 

okay, actually I was comparing the pros and cons of using the native playwright test runner comparing to mocha then I stumble on the beforeAll hook, which cant be used to launch the baseUrl before all test blocks, the alternative is to use beforeEach which will consume extra time.
so I have created a scenario and try it once using playwright runner and mocha runner, I have found big difference in the execution time as shown below, and the main reason was actually the beforeAll hook 

down below is the execution time for playwright runner 
![image](https://user-images.githubusercontent.com/32042806/134063674-2a8adfde-97be-405d-b892-670a85297513.png)


here is mocha runner for the exact test
![image](https://user-images.githubusercontent.com/32042806/134065494-9836a52c-760f-46f0-9750-692ca4cb5206.png)

**Comment by mxschmitt** [comment]
@Amrkamel1 its hard to compare when the [core-concepts](https://playwright.dev/docs/next/intro/) are different (mocha, jest-playwright vs. playwright test-runner). The Playwright test-runner gives you a new context for each test by-default. This is called context-isolation to ensure that a previous test can't mess up another test. Then its natural, that in beforeAll you cannot navigate to your baseURL since there is no page yet. For that you have to use beforeEach. If you want to have the concept of sharing a page and by that context for your tests, then you can follow [this guide](https://playwright.dev/docs/test-parallel#reusing-single-page-between-tests) and use the serial mode.

In general creating a context is a cheap and fast operation, so its the question if you want to have context isolation or the risk that tests can affect other tests.

**Comment by Amrkamel1** [comment]
@mxschmitt  Thanks for clarification this option will definitely help.
