### ISSUE TITLE
How can get a clear context?[Question]

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright#9013]
Hello,
How can I get a clear context not reopen context ?  Delete cookies  localstorage...

**Comment by mxschmitt** [comment]
Playwright is designed for end-to-end testing. To ensure you have a clean state between tests, a new context gets created. Usually you don't clean them yourself and create a new one instead, because this is a cheap and fast operation see [here](https://playwright.dev/docs/core-concepts#browser-contexts).

Does creating a new context work for you?
