### ISSUE TITLE
[Question] Multi Page Scenarios in Page object model and/or fixtures

### ISSUE THREAD

**Issue by bsteffensTempus** [microsoft/playwright#9132]
Hello! What is the best way to handle multi page scenarios in the page object model? Should I be using 'this.page.context' in a page object to create new contexts? Should creating new contexts happen at the test level? I also have a global config handling session persistence and a playwright.config.js, not sure if that matters.

I'm just looking to add a newContext method to the SearchPage class laid out in the official documentation. 
https://playwright.dev/docs/pom

**Comment by mxschmitt** [comment]
If you want to test mulit page scenarios as you said, you need a different context, since the pages inside a context share the state (e.g. localStorage).

It depends on how you structure your tests, if you only create a page currently via beforeAll, then creating there a new context is fine. But if you instead use the default page fixture for it, which will internally create a new context for you for every test (test fixture) then beforeEach (same as a test fixture) would be required.

Related docs:
- https://playwright.dev/docs/test-pom/
- https://playwright.dev/docs/test-fixtures

**Comment by aslushnikov** [comment]
@bsteffensTempus can you explain your usecase? Are you testing a chat application or something like this?

I'd strongly recommend using "fixtures" to create a second page in a new isolated context. This way you can easily manage lifetime of the newly created page:

```js
const { test } = require('@playwright/test');

const myTest = test.extend({
  page2: async ({browser}, use) => {
    const context = await browser.newContext();
    const page = await context.newPage();
    await use(page);
    await context.close();
  },
});

myTest('foo', async ({ page, page2 }) => {
  // page and page2 are from separate contexts!! 
});
