### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by yeucodonvn** [microsoft/playwright#9148]
how do set Fingerprinting browser to playwright
I want change this after close a session
thank you

**Comment by shirshak55** [comment]
It depends on how the finger printing is calculated.  You need to patch the browser yourself because it depends on the website. The website can use canvas to fingerprint, or use the available font, user agent.

There are many things they rely on so I don't think this question is appropriate here. Thanks.

**Comment by yeucodonvn** [comment]
> patch the browser

thank you
