### ISSUE TITLE
[Feature] option for selectors to ignore invisible elements

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#9162]
use case: in sapui5 applications, there's usually a duplicated invisible version of every element on the page, meaning that to interact with most fields we need to add additional logic to make sure it's getting the right selector:

```ts
const handle = (await page.querySelectorAll(selector).find(element => element.isVisible())
await page.click(handle)
```

it would be nice if there was an option in the methods that take selectors to filter out invisible ones, ie:
```ts
await page.click(selector, {includeInvisible: false})
```

or alternatively, if #9153 is implemented it would be as simple as adding `:not(:matches-css(display: none))` to the selector

**Comment by mxschmitt** [comment]
Instead of using ElementHandles, I would recommend to use [Locators](https://playwright.dev/docs/api/class-locator) and [Playwright's Assertions](https://playwright.dev/docs/test-assertions). Regarding visible/invisible element, you can use the following selector engine which should help you with that: https://playwright.dev/docs/selectors#selecting-visible-elements
