### ISSUE TITLE
[BUG] Trace Viewer does not show selected text from a select dropdown

### ISSUE THREAD

**Issue by TheChosenQA** [microsoft/playwright#9212]
**Context:**
- Playwright Version: 1.15.0
- Operating System: Windows
- Node.js version: 15.14.0
- Browser: Chromium
- Extra: Specific to trace viewer

Trace viewer doesn't show the selected option in a dropdown after using the page.SelectOption command.
We can see from the logs that the action does happen.
![image](https://user-images.githubusercontent.com/45701241/135223611-98954266-8c41-4b69-a74b-bb9d19adbe97.png)

The timeline at the top of traceviewer shows the selected item as it should appear on the front end, it is only in the 'After' section where it still shows the value before the value was selected.

**Comment by sweideh** [comment]
Hey,

we have the same issue. I attached a trace.
[trace-AddAddress_StateRequired_ShowsErrorOnAddAddressView-context-0.zip](https://github.com/microsoft/playwright/files/8519757/trace-AddAddress_StateRequired_ShowsErrorOnAddAddressView-context-0.zip)
.

I might need to open up another issue, but there is also another problem. Via JS we added a change event listener on the select. It should hide the input element with label "state" and should show an new select element for that label. So maybe the change event wont be triggered too, because of the lack of updating the view?
