### ISSUE TITLE
[Question]Can I do an automation test with playwright in github actions?

### ISSUE THREAD

**Issue by hugetiny** [microsoft/playwright#926]
Can I do an automation test with playwright in github actions?

**Comment by pavelfeldman** [comment]
We run Playwright tests using GH actions with the following recipes: https://github.com/microsoft/playwright/tree/master/.github/workflows.

Note that we run both headless and headful tests, so we use xvfb, but regular Playwright customers should not need that, everything should just run headlessly.

**Comment by arjun27** [comment]
Thanks @hugetiny. I created this example project that shows how to run Playwright scripts on GH Actions: https://github.com/arjun27/playwright-github-actions

**Comment by FezVrasta** [comment]
Thanks @arjun27 for the repository!

When I try to run my tests I get `Running as root without --no-sandbox is not supported`, ideas?

**Comment by arjun27** [comment]
Thanks @FezVrasta, investigating this issue here: https://github.com/arjun27/playwright-github-actions/issues/1

Curiously, the error message that you are running into (`Running as root without --no-sandbox is not supported`) is thrown by Chromium - Firefox seems to throw a different string for me (see aforementioned issue). Would be helpful to get a confirmation just in case it's a separate issue.

**Comment by arjun27** [comment]
@fezvrasta - Firefox is now working, please use `arjun27/playwright-bionic:0.1.1` as the container image. Closing this issue.

**Comment by FezVrasta** [comment]
With that image I can't `npm i -g yarn` anymore. :-(

`Error: EACCES: permission denied, access '/usr/lib/node_modules'`
