### ISSUE TITLE
[Feature] Add configuration options to GitHub Reporter

### ISSUE THREAD

**Issue by sidharthv96** [microsoft/playwright#9293]
Possible useful configs:

- maxAnnotations: number = 50 | To set a limit on annotations so the PR isn't cluttered. 
- stacktrace: boolean = true | Include stacktrace or not. Sometimes the trace might be really long. [Example webkit failure](https://github.com/microsoft/playwright/actions/runs/1304035251)
- annotations: string[] = ["error", "slowTest", "summary"] | Category of annotations to print.

**Comment by jjeff** [comment]
> * annotations: string[] = ["error", "slowTest", "summary"] | Category of annotations to print.

It would be really useful to define which annotation categories to print. 👍

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
