### ISSUE TITLE
[BUG] responseBodySize unexpectedly negative in Chromium when 404 has content

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#9329]
**Context:**
- Playwright Version: 1.15.2, and ToT
- Operating System: MacOS
- Node.js version: v14.17.6
- Browser: Chromium

**Code Snippet**

See the test case here: https://github.com/microsoft/playwright/pull/9328

**Describe the bug**

`responseBodySize` is negative in Chromium if there is 404 with content.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
