### ISSUE TITLE
[BUG] request.sizes() hangs (CR)

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#9350]
**Context:**
- Playwright Version: 1.15.2, ToT
- Operating System: macOS
- Node.js version: [e.g. 12.22, 14.6]
- Browser: CR

**Code Snippet**

See test case here: https://github.com/microsoft/playwright/pull/9349

**Describe the bug**

We use `.sizes()` generically in some network capture code; sometimes it hange, esp on third-party embedded SDK code we can't control. For now, we've wrapped it in a timeout.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
