### ISSUE TITLE
[Feature] Preferences API

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#9384]
Currently, Playwright only supports conveniently setting command line switches for the browser. Some features cannot be controlled via these switches and it's instead necessary to user persistent context with some magic prefs.json, it would be nice to be able to do something like:

```
await browser.newContext({
    preferences: { key: val, …}
})
```

where preferences is an arbitrary dict that PW handles seeding into the correct location in the user data directory. IMO, this is basically the same feature as the `args: […]` option, but supports more customization of the browser.

Some uses that have come up:
* customize cookie setting to test site under different cookie profiles
* disable native PDF viewer

**Comment by weyert** [comment]
Yes, I love this idea. I would love to test a case were enabling blocking third party cookies also blanks accessing `localStorage`. I would like to test with and without this blocking enabled as part of regression tests to avoid accidental breaking things.

**Comment by rwoll** [comment]
@JoelEinbinder If this is something the Playwright team is on board with, I'd be interested in helping contribute it.

Off the top of your head (if not I can do some research if this seems like something the PW team is willing to accept), are FF and WK similar to CR in that there is theoretically a file that drives the prefs/settings at launch per-context?

Cheers!

**Comment by chenzanyu** [comment]
Hope to support this requirement

**Comment by easyrepro** [comment]
+1 Hope this gets prioritized

**Comment by jhanpiier** [comment]
+1

**Comment by kachkaev** [comment]
Please add 👍 or ❤️ to the original comment instead of adding new comments. This creates spam in GitHub notifications for folks who are subscribed to this issue 🙏

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by kachkaev** [comment]
This issue is in top-10 [by the number of ❤️ reactions received at all times](https://github.com/microsoft/playwright/issues?q=is%3Aissue+sort%3Areactions-heart-desc):

<img width="1238" alt="Screenshot 2023-06-30 at 22 16 25" src="https://github.com/microsoft/playwright/assets/608862/f9e65e6b-83d6-481f-b532-a1c9df8b95ea">


It did not get any 👍, but if imagine all ❤️ replaced by 👍, this feature request would be on the [fourth page of all currently open issues](https://github.com/microsoft/playwright/issues?page=4&q=is%3Aissue+sort%3Areactions-%2B1-desc+is%3Aopen) (out of 25):

<img width="1251" alt="Screenshot 2023-06-30 at 22 15 43" src="https://github.com/microsoft/playwright/assets/608862/9b0c65a9-95b6-43c8-9b4c-0eb58463995f">

If this issue was closed mechanically, judging by the number of 👍, can this decision be reconsidered? 🙏

**Comment by fungairino** [comment]
This issue is suddenly more relevant to us since the latest version of chrome now doesn't let us run our extension unless developer mod is turned on. We could fix this by setting the `pref`, `{"extensions.ui.developer_mode": True,}`.

**Comment by pirate** [comment]
@pavelfeldman please see @kachkaev's comment and consider reopening this, it's one of your most requested features

**Comment by anexplore** [comment]
we need it
