### ISSUE TITLE
[BUG] page.goto: Navigation failed because page was closed!

### ISSUE THREAD

**Issue by cakmakfatih** [microsoft/playwright#9418]
- Playwright Version: 1.15.2
- Operating System: Windows 11 21H2
- Node.js version: 16.10.10
- Browser: Firefox

Here is the code:

```
const { firefox } = require('playwright');

(async () => {
  const browser = await firefox.launch();
  const page = await browser.newPage();
  await page.goto("https://www.kbb.com/car-finder/?manufacturers=hyundai");
})();
```

Here is the full error log:

```
ERROR: The process with PID 21328 (child process of PID 16812) could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 16812 (child process of PID 4360) could not be terminated.
Reason: There is no running instance of the task.
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.goto: Navigation failed because page was closed!
=========================== logs ===========================
navigating to "https://www.kbb.com/car-finder/?manufacturers=hyundai", waiting until "load"
============================================================
    at -project-path/start.js:6:16 {
  name: 'Error'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Extra:

Running this code using `chromium`  or `chrome` works perfectly fine. Running the Firefox build of Playwright from `ms-playwright/firefox/firefox.exe` and manually opening the website also works fine. However, whenever I try to run this code, headless or not, the page suddenly closes. I only saw this issue on this website (I've been using Playwright with Firefox for more than a year).  Also, most of the other pages of this website work fine using Playwright with Firefox. Still some webpages including this one suddenly close the browser.page and throw this error. I couldn't figure out what causes it.

**Comment by aslushnikov** [comment]
## Investigation results

Firefox has [webcompat shims](https://github.com/mozilla/gecko-dev/tree/master/browser/extensions/webcompat/shims) – a bunch of hardcoded resources they use instead of fetching them from the internet. 

Once browser tries to fetch the resource, firefox captures it and fulfills with the shim: [see here](https://github.com/mozilla/gecko-dev/blob/a2e24ac271796097f60b9371902b193694791d20/browser/extensions/webcompat/lib/shims.js#L794)

This interception technology replaces internal `HTTPChannel` with `SimpleChannel`, so all channel callbacks suddenly
start receiving some instance of `SimpleChannel` as `aRequest` argument, e.g. here:

https://github.com/aslushnikov/juggler/blob/65eb8026274f3393c25745cc690939ddc39ce573/juggler/NetworkObserver.js#L542

Us calling original `onDataAvailable` callback on `SimpleChannel` instance results in a crash here: 

https://github.com/aslushnikov/juggler/blob/65eb8026274f3393c25745cc690939ddc39ce573/netwerk/base/SimpleChannelParent.cpp#L93
