### ISSUE TITLE
[BUG] ignoreHTTPSErrors flag is being ignored when using WebKit on Linux through https proxy

### ISSUE THREAD

**Issue by sabjank** [microsoft/playwright#9466]
**Context:**
- Playwright Version: 1.15.2
- Operating System: Linux Mint 19.2 Tina / 4.15.0-54-generic
- Node.js version: 14.17.1
- Browser: WebKit

**Code Snippet**

```javascript
import { webkit } from "playwright";

(async () => {
    const browser = await webkit.launch({
        proxy: {
            server: "https://example-proxy-address:89",
            username: "proxy_username",
            password: "proxy_password",
        }
    });

    const context = await browser.newContext({
        ignoreHTTPSErrors: true
    })

    const page = await context.newPage();

    await page.goto("https://google.com");
})();

```

**Describe the bug**

Currently it's not possible to open a page in webkit when the proxy setting is enabled as you'll be redirected to a new **about:blank** page while getting the following error message: **UnhandledPromiseRejectionWarning: page.goto: Unacceptable TLS certificate**

**Comment by yury-s** [comment]
Looks like your proxy has invalid certificates.

**Comment by cameroncf** [comment]
Leaving breadcrumbs for anyone who may still run into this. I'd cut/pasted some example code that used GitHub's `ubuntu-18.04` image and was running into "Unacceptable TLS certificate" on Webkit only. Updating to use `ubuntu-latest` fixed the error.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
