### ISSUE TITLE
[Bug]: Video duration is different than real duration of the run (chromium)

### ISSUE THREAD

**Issue by qwark97** [microsoft/playwright#9611]
### Playwright version

1.15.3

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

Repo to present bug:
https://github.com/qwark97/video_length_bug

Given command in the repo takes ~2min

Bug occurs also outside the docker image

### What happened? / Describe the bug

To be honest I'm not sure if this is a bug or an expected behavior but videos recorded with playwright (by passing `record_video_dir`) at Chromium, at both headless/headed mode, with and without `slow_mo` parameter are longer than "real" execution time. For example, one of the executions of the test (from the example repo) took ~18s while recorded video took 36s (such 2x ratio is just a coincidence)

I haven't noticed such behavior with other browsers but on the other hand the same test took at them quite longer time (I don't know whether it is connected)

So my question is: if this is a bug? And if not, am I able to do anything to make execution and the recorded video the same duration?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by MohammadMDSA** [comment]
> #### Why was this issue closed?
> We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

I have worked with the video a lot, and it has been very problematic for us. I can provide you as much feedback and data as you want. We are using python, and since there is a lack of an audio feature for the recordings, I am recording an audio alongside the video. The audio is perfect, but the video seemed to be in slow motion. We investigated it and realized the video is being recorded at a slower rate than it should. It's time could be as much as twice of the time it should be. So we sped up the video (with ffmpeg) so its time would match the audio. The result was more satisfying, but because the video starts with an unknown time offset from when the context creation method is called, there still is an unknown time offset compared to the audio time. Is there at least any way that Playwright would return a certain duration for the recorded video some other way, so I would know how much the video should be sped up to match what it is supposed to?

**Comment by MohammadMDSA** [comment]
It is worth mentioning that the slowing down is not homogenous. This means that some parts of the video are recorded at a higher rate and some at a slower one. I realized this when I manually matched the audio recording with the video recording at a specific point in the recording. Sometimes, the video got behind the audio, and sometimes, it got ahead. I know the audio is ok for sure, because it was a recording of a conversation and there was absolutely no problem with the speaches.

**Comment by adamnolte** [comment]
This bug is especially apparent with web pages that have variable frame rates such as a remote desktop stream.

We observed the following drift that grows as the recording gets longer when interacting with a remote desktop stream:
2 min mark: recording 3s behind
5 min mark: recording 11s behind
10 min mark: recording 25s behind

I believe this issue is related and is the root cause: https://github.com/microsoft/playwright/issues/35776

**Comment by gpiszczek** [comment]
Some time ago I tried to push a fix for this but without success. I've opened new issue #38219 with some additional information. Hope I will make it pass now.
