### ISSUE TITLE
[Question] Cannot find module 'timers/promises' 

### ISSUE THREAD

**Issue by sb-michal-murray** [microsoft/playwright#9712]
Trying to use feature [Timers Promises API](https://nodejs.org/dist/latest-v17.x/docs/api/timers.html#timers-promises-api) from node 15.9, but I'm getting: 

`Error: Cannot find module 'timers/promises'`

```sh
node -v
v17.0.1
npx playwright --version
Version 1.16.0
```
```
"@types/node": "^16.11.3"
```

I tested this API and it runs w/o playwright (using just `node`), so it must be somewhere inside playwright that it throws.

**Comment by mxschmitt** [comment]
The following works for us, @sb-michal-murray do you do anything differently?

```ts
import { test } from '@playwright/test';
import { setTimeout } from 'timers/promises';

test("foo", async () =>  {
  console.log("before")
  await setTimeout(2000);
  console.log("after")
})
```

Make sure that you use Node.js 15+ since it was added in 15.0.0: https://nodejs.org/api/timers.html

The `@types/node` package version is not relevant, since this is only about typings and your error comes from Node.js itself.

**Comment by mxschmitt** [comment]
Closing since it seems answered and we can't repro. Please create a new issue if you still encounter issues!

**Comment by giugiozza** [comment]
It seems to be that should be
import { setTimeout } from "timers-promises";
instead of
import { setTimeout } from 'timers/promises';
