### ISSUE TITLE
[Feature] Drag and Drop for uploading  folders

### ISSUE THREAD

**Issue by Vanish404** [microsoft/playwright#9823]
I wondering, is it possible to simulate drag and drop from file manger? For example Finder. I just want to drag and drop multiple folders and files and upload them directly to the S3. The problem is that [File](https://developer.mozilla.org/en-US/docs/Web/API/File) class has `path` field that read only. So if I drop a folder I will get 
```
{
  name: "a.txt", // file name
  path: "/folder/a.txt",
  size: 2473, // 2kb
  type: "text/plain",
  lastModifiedDate: ...,
...
  ```
  Do you have some workaround to set this `path` field?

**Comment by dgozman** [comment]
@Vanish404 No updates on this one, sorry.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
