### ISSUE TITLE
[BUG] page.click clicks incorrect item due to element reuse

### ISSUE THREAD

**Issue by sidharthv96** [microsoft/playwright#9855]
**Context:**
## System:
 - OS: macOS 11.3
 - Memory: 216.95 MB / 16.00 GB
## Binaries:
 - Node: 14.17.6 - ~/.volta/tools/image/node/14.17.6/bin/node
 - Yarn: 1.22.11 - ~/.volta/tools/image/yarn/1.22.11/bin/yarn
 - npm: 6.14.15 - ~/.volta/tools/image/node/14.17.6/bin/npm
 - playwright: 1.16.2
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // ...
})();
```

**Describe the bug**

I found a race condition when clicking an element.
Should we be throwing an error/warning instead of clicking the wrong element?
When Page is Loaded, table is loaded unsorted.

| Item | Date      |
| ---- | --------- |
| One  | `<dateOne>` |
| Two  | `<dateTwo>` |

After Sort

| Item | Date      |
| ---- | --------- |
| Two  | `<dateTwo>` |
| One  | `<dateOne>`|

Problem 
```ts
await page.click('"Date"'); // To sort by date. This triggers a network call to fetch the data.
await page.click('"Two"'); // Expected to click "Two", but clicks "One", without any error/warning
```

Workaround

```ts
await Promise.all([
  this.page.waitForResponse(/-Date/), // Based on the URL
  this.page.click('"Date"'),
]);
await page.click('"Two"');
```

If it was clicking `Two` sorted/unsorted, it's not an issue. But it's clicking `One` after sort, without any kind of warning/error. This was happening in an unrelated area of the tests, so had to dig in to find the root cause.

**Comment by karesztrk** [comment]
Hey guys. I'm experiencing the same issue inside a `<table>` rendered by React ^18.1.0
@sidharthv96 's workaround indeed solves the problem.
However im interested in about how to overcome with this in React since im already using `key=` for each row inside the table. Any advice @dgozman ?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
