### ISSUE TITLE
[Feature] Change passed/fail/flaky logic

### ISSUE THREAD

**Issue by AndreyMelnichenko** [microsoft/playwright#9905]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

I think that main statistic of test result should contain only passed or failed test, and after some of passed test should be mark as flaky
**Example**
Actual:
![image](https://user-images.githubusercontent.com/30802024/139576688-50f1596f-a1af-4bab-a453-06fb4a4bb877.png)
Proposal:
![image](https://user-images.githubusercontent.com/30802024/139577333-846f660b-fe65-42b2-b9e8-749b656dc786.png)

**Comment by pavelfeldman** [comment]
Let's collect more feedback on this one!

**Comment by arukiidou** [comment]
### What you need

- the test mark as flaky
https://playwright.dev/docs/api/class-test#test-slow

```typescript
import { test, expect } from '@playwright/test';

test('flaky test', async ({ page }) => {
  test.flaky();
  // ...
});
```

- The test marked as "flaky" , then testCase.outcome is flaky(Regardless of the test results)
https://playwright.dev/docs/api/class-testcase#test-case-outcome

### usecase

- Most flaky tests fail randomly; a test that always fails the second time is stable because you can expect it to fail
- Therefore, flaky tests may "all succeed" or may "all failed", but it should be "flaky"

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
