### ISSUE TITLE
[BUG] playwright install failed on windows 10

### ISSUE THREAD

**Issue by namilkimfree** [microsoft/playwright#9914]
**Context:**
- Playwright Version: [1.6]
- Operating System: [Windows,10]
- Node.js version: [v16.13.0]
- Browser: [All]
- Extra: []

getting started example 
![image](https://user-images.githubusercontent.com/44854923/139635335-61e7670f-396a-48d9-b1e4-0bc5698c69ed.png)

i try this command
`
playwright install

`![image](https://user-images.githubusercontent.com/44854923/139635419-b48a72e7-ce13-4b2f-8f6c-8beabfc3c1d2.png)

**Comment by mxschmitt** [comment]
It seems that the certificates on your system are outdated or does not include the root certificate which we are using.

Could you try manually navigating to this host? https://playwright.azureedge.net/builds/index.html

Updating your Windows with the latest Windows updates might help.

**Comment by namilkimfree** [comment]
windwos already updated  and  wget https://playwright.azureedge.net/builds/index.html  status 200,

npm i playwright command complete but playwright install command throw error

![image](https://user-images.githubusercontent.com/44854923/139789906-7cff784e-284d-41e7-9ef3-15c59fb777f1.png)

**Comment by mxschmitt** [comment]
Super weird issue, it seems like the certificates on your system are broken. As a temporary workaround you can set the [`NODE_TLS_REJECT_UNAUTHORIZED=0`](https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request) environment variable,

It would be `$env:NODE_TLS_REJECT_UNAUTHORIZED=0` in PowerShell.

Since you are the first one reporting this, I think most likely something i broken on your end rather on our end.

**Comment by namilkimfree** [comment]
@mxschmitt  

Ok, thank you.

I have installed npm i playwright, so there are currently no issues.
